Repository microsoft/vscode-python, pull requests merged in 2019-08, with the labels that each got.

#6797 Revert "Revert "Move .env file and environment variable parser into the extension (#6773)" (#6794)"
  news/3 Code Health/6770.md
  src/client/debugger/debugAdapter/DebugClients/LocalDebugClient.ts
  src/client/debugger/extension/configuration/resolvers/helper.ts
  src/client/debugger/extension/configuration/resolvers/launch.ts
  src/client/debugger/extension/serviceRegistry.ts
  src/test/debugger/envVars.test.ts
  src/test/debugger/extension/configuration/resolvers/launch.unit.test.ts
  src/test/testing/common/debugLauncher.unit.test.ts
Labels: skip news

#6819 Fix nightly failures from debugger code lenses
  package-lock.json
  package.json
  src/client/common/types.ts
  src/client/datascience/debugLocationTracker.ts
  src/client/datascience/gather/gather.ts
  src/datascience-ui/history-react/cell.tsx
  src/datascience-ui/history-react/contentPanel.tsx
  src/datascience-ui/history-react/mainPanelState.ts
  src/datascience-ui/react-common/settingsReactSide.ts
  src/test/datascience/color.test.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/editor-integration/codewatcher.unit.test.ts
  src/test/datascience/execution.unit.test.ts
  src/test/datascience/interactiveWindow.functional.test.tsx
  src/test/datascience/interactiveWindowCommandListener.unit.test.ts
  src/test/datascience/interactiveWindowTestHelpers.tsx
Labels: skip news

#6781 Return relfile and location as-is (do no normcase).
  pythonFiles/testing_tools/adapter/pytest/_pytest_item.py
  pythonFiles/tests/testing_tools/adapter/pytest/test_discovery.py
Labels: skip news

#6830 Add more logging for environment output
  build/ci/vscode-python-nightly-ci.yaml
  package-lock.json
  src/client/common/utils/decorators.ts
  src/client/interpreter/locators/services/condaService.ts
Labels: skip news

#6831 Fix npm security vulnerabilities
  package-lock.json
  package.json
Labels: data science, skip news

#6856 Make sure filenames are not norm-cased on Windows.
  build/ci/templates/test_phases.yml
  pythonFiles/testing_tools/adapter/pytest/_pytest_item.py
  pythonFiles/tests/testing_tools/adapter/.data/NormCase/tests/A/__init__.py
  pythonFiles/tests/testing_tools/adapter/.data/NormCase/tests/A/b/C/__init__.py
  pythonFiles/tests/testing_tools/adapter/.data/NormCase/tests/A/b/C/test_Spam.py
  pythonFiles/tests/testing_tools/adapter/.data/NormCase/tests/A/b/__init__.py
  pythonFiles/tests/testing_tools/adapter/.data/NormCase/tests/__init__.py
  pythonFiles/tests/testing_tools/adapter/pytest/test_discovery.py
  pythonFiles/tests/testing_tools/adapter/test_functional.py
Labels: skip news

#6860 Added all serviceRegistry tests
  src/test/common/dotnet/serviceRegistry.unit.test.ts
  src/test/common/installer/serviceRegistry.unit.test.ts
  src/test/common/platform/serviceRegistry.unit.test.ts
  src/test/common/process/serviceRegistry.unit.test.ts
  src/test/common/terminals/serviceRegistry.unit.test.ts
  src/test/common/variables/serviceRegistry.unit.test.ts
  src/test/linters/serviceRegistry.unit.test.ts
  src/test/providers/serviceRegistry.unit.test.ts
Labels: skip news

#6864 Remove extra logging
  src/client/common/utils/decorators.ts
Labels: skip news

#6866 Add missing decorator
  src/client/testing/common/enablementTracker.ts
Labels: skip news

#6868 August 2019 Release
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
  news/1 Enhancements/6672.md
  news/2 Fixes/6729.md
  news/2 Fixes/6738.md
  news/2 Fixes/6748.md
  package-lock.json
  package.json
Labels: skip news

#6869 Extend timeout for functional tests
  build/.mocha.functional.opts
Labels: skip news

#6872 Exclude .env file from extension
  .vscodeignore
Labels: skip news

#6878 Merge august release into master
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
  news/2 Fixes/6738.md
  news/2 Fixes/6748.md
  package-lock.json
  package.json
  src/client/datascience/data-viewing/dataViewerProvider.ts
  src/client/datascience/interactive-window/interactiveWindow.ts
  src/client/datascience/types.ts
Labels: skip news

#6889 Temporarily enable old smoke tests
  build/ci/templates/test_phases.yml
  build/ci/vscode-python-pr-validation.yaml
  package.json
Labels: skip news

#6877 Send "relpath" back for all test files/folders.
  pythonFiles/testing_tools/adapter/discovery.py
  pythonFiles/testing_tools/adapter/info.py
  pythonFiles/testing_tools/adapter/pytest/_discovery.py
  pythonFiles/testing_tools/adapter/pytest/_pytest_item.py
  pythonFiles/testing_tools/adapter/report.py
  pythonFiles/testing_tools/adapter/util.py
  pythonFiles/tests/testing_tools/adapter/pytest/test_discovery.py
  pythonFiles/tests/testing_tools/adapter/test_discovery.py
  pythonFiles/tests/testing_tools/adapter/test_functional.py
  pythonFiles/tests/testing_tools/adapter/test_report.py
  pythonFiles/tests/testing_tools/adapter/test_util.py
  src/client/testing/common/services/discoveredTestParser.ts
  src/client/testing/common/services/types.ts
Labels: skip news

#6936 Fix smoke tests
  build/ci/templates/test_phases.yml
  src/test/standardTest.ts
Labels: skip news

#6945 Revert "Add regex to dedent `else` and friends (#6497)"
  src/client/extension.ts
  src/client/language/languageConfiguration.ts
  src/test/language/languageConfiguration.unit.test.ts
Labels: skip news

#6955 Point release for September
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip news

#6954 Throw error when unable to compute file hash
  src/client/common/platform/fileSystem.ts
  src/client/common/platform/types.ts
  src/test/common/platform/filesystem.unit.test.ts
Labels: skip news

#6848 Tweaked Message for restarting insider build
  news/2 Fixes/6838.md
  package.nls.json
  src/client/common/utils/localize.ts
Labels: external contributor

#6879 Added unit tests for client/linters/pylint.ts
  src/client/linters/pylint.ts
  src/test/application/diagnostics/applicationDiagnostics.unit.test.ts
  src/test/linters/pylint.unit.test.ts
Labels: skip news

#6964 Hash providers for Python Interpreters
  src/client/interpreter/contracts.ts
  src/client/interpreter/locators/services/hashProvider.ts
  src/client/interpreter/locators/services/hashProviderFactory.ts
  src/client/interpreter/locators/services/windowsRegistryService.ts
  src/client/interpreter/locators/services/windowsStoreInterpreter.ts
  src/client/interpreter/locators/types.ts
  src/client/interpreter/serviceRegistry.ts
  src/test/interpreters/locators/hasProviderFactory.unit.test.ts
  src/test/interpreters/locators/hashProvider.unit.test.ts
  src/test/interpreters/locators/windowsStoreInterpreter.unit.test.ts
  src/test/interpreters/serviceRegistry.unit.test.ts
  src/test/interpreters/windowsRegistryService.unit.test.ts
Labels: skip news

#6997 Fixes to hash provider
  src/client/interpreter/locators/services/windowsStoreInterpreter.ts
  src/test/interpreters/locators/windowsStoreInterpreter.unit.test.ts
Labels: skip news

#6988 Fix linter issues
  build/ci/templates/build_compile_steps.yml
  src/client/activation/serviceRegistry.ts
  src/client/common/application/types.ts
  src/client/common/featureDeprecationManager.ts
  src/client/common/net/socket/socketServer.ts
  src/client/common/utils/multiStepInput.ts
  src/client/datascience/editor-integration/codeLensFactory.ts
  src/client/datascience/interactive-window/interactiveWindow.ts
  src/client/debugger/debugAdapter/Common/debugStreamProvider.ts
  src/client/debugger/debugAdapter/DebugClients/LocalDebugClient.ts
  src/client/debugger/extension/configuration/providers/pyramidLaunch.ts
  src/client/debugger/extension/configuration/types.ts
  src/client/formatters/baseFormatter.ts
  src/client/interpreter/configuration/pythonPathUpdaterService.ts
  src/client/interpreter/contracts.ts
  src/client/interpreter/helpers.ts
  src/client/interpreter/interpreterService.ts
  src/client/interpreter/locators/helpers.ts
  src/client/interpreter/locators/services/baseVirtualEnvService.ts
  src/client/providers/jediProxy.ts
  src/client/providers/renameProvider.ts
  src/client/providers/simpleRefactorProvider.ts
  src/client/providers/updateSparkLibraryProvider.ts
  src/client/refactor/proxy.ts
  src/client/terminals/codeExecution/codeExecutionManager.ts
  src/client/terminals/codeExecution/djangoContext.ts
  src/client/terminals/codeExecution/helper.ts
  src/client/testing/display/main.ts
  src/client/testing/main.ts
  src/datascience-ui/react-common/textMeasure.ts
  src/test/activation/languageServer/downloader.unit.test.ts
  src/test/application/diagnostics/checks/updateTestSettings.unit.test.ts
  src/test/common/installer/installer.unit.test.ts
  src/test/common/installer/moduleInstaller.unit.test.ts
  src/test/common/platform/filesystem.unit.test.ts
  src/test/common/terminals/helper.unit.test.ts
  src/test/debugger/extension/configuration/providers/moduleLaunch.unit.test.ts
  src/test/debugger/extension/configuration/providers/pyramidLaunch.unit.test.ts
  src/test/format/extension.format.test.ts
  src/test/format/formatter.unit.test.ts
  src/test/testing/pytest/pytest.run.test.ts
Labels: skip news

#6998 Ensure smoke tests fail CI
  src/test/smokeTest.ts
  src/test/standardTest.ts
Labels: skip news

#6905 Document telemetry captured
  src/client/extension.ts
  src/client/interpreter/contracts.ts
  src/client/interpreter/display/progressDisplay.ts
  src/client/interpreter/serviceRegistry.ts
  src/client/telemetry/index.ts
  src/client/telemetry/types.ts
  src/test/interpreters/serviceRegistry.unit.test.ts
Labels: skip news

#7022 Document missing telemetry
  src/client/telemetry/index.ts
Labels: skip news

#7049 gulp changes
  gulpfile.js
Labels: skip news

#7011 #7010: Replaced 'python.enableJedi' setting with 'python.languageServ…
  .vscode/settings.json
  news/.vscode/settings.json
  news/1 Enhancements/7010.md
  package.json
  src/client/activation/activationService.ts
  src/client/activation/languageServer/languageClientFactory.ts
  src/client/common/configSettings.ts
  src/client/common/featureDeprecationManager.ts
  src/client/common/types.ts
  src/client/datascience/interactive-window/intellisense/dotNetIntellisenseProvider.ts
  src/client/datascience/interactive-window/intellisense/jediIntellisenseProvider.ts
  src/client/languageServices/proposeLanguageServerBanner.ts
  src/client/linters/linterAvailability.ts
  src/client/linters/linterInfo.ts
  src/client/telemetry/index.ts
  src/client/testing/common/updateTestSettings.ts
  src/test/.vscode/settings.json
  src/test/activation/activationService.unit.test.ts
  src/test/application/diagnostics/checks/updateTestSettings.unit.test.ts
  src/test/common.ts
  src/test/common/configSettings/configSettings.unit.test.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/intellisense.functional.test.tsx
  src/test/datascience/intellisense.unit.test.ts
  src/test/linters/common.ts
  src/test/linters/linter.availability.unit.test.ts
  src/test/linters/linterinfo.unit.test.ts
  src/test/performance/settings.json
  src/test/performanceTest.ts
  src/test/smoke/common.ts
  src/test/smokeTest.ts
Labels: external contributor

#7048 Add unit tests for diagnostics/checks/pythonInterpreter.ts
  src/test/application/diagnostics/checks/pythonInterpreter.unit.test.ts
Labels: skip news

#7082 revert gulp change
  build/ci/vscode-python-ci.yaml
  build/ci/vscode-python-nighly-flake-ci.yaml
  build/ci/vscode-python-nightly-ci.yaml
  build/ci/vscode-python-nightly-uitest.yaml
  build/ci/vscode-python-pr-validation.yaml
  gulpfile.js
Labels: skip news

#7078 Fix failing CI for pylint.test.ts & lint.provider.test.ts
  src/test/linters/lint.provider.test.ts
  src/test/linters/pylint.test.ts
Labels: skip news

#6923 Fix typo in method name
  news/3 Code Health/7072.md
  src/client/linters/pylint.ts
  src/test/linters/pylint.test.ts
  src/test/linters/pylint.unit.test.ts
Labels: external contributor

#6925 Allow code like ABC123 for flake8 v3 plugin
  news/2 Fixes/4074.md
  src/client/linters/baseLinter.ts
Labels: external contributor

#7138 Change experiment values
  experiments.json
Labels: skip news

#6570 Renamed pep8 to pycodestyle
  .github/test_plan.md
  build/existingFiles.json
  build/test-requirements.txt
  data/.vscode/settings.json
  data/test.py
  news/2 Fixes/410.md
  package.json
  src/client/common/configSettings.ts
  src/client/common/installer/productInstaller.ts
  src/client/common/installer/productNames.ts
  src/client/common/installer/productService.ts
  src/client/common/types.ts
  src/client/linters/constants.ts
  src/client/linters/linterManager.ts
  src/client/linters/pycodestyle.ts
  src/client/linters/types.ts
  src/client/testing/common/updateTestSettings.ts
  src/test/.vscode/settings.json
  src/test/.vscode/tags
  src/test/common.ts
  src/test/linters/common.ts
  src/test/linters/lint.args.test.ts
  src/test/linters/lint.functional.test.ts
  src/test/linters/lint.unit.test.ts
  src/test/mockClasses.ts
  src/test/multiRootWkspc/multi.code-workspace
  src/test/pythonFiles/linting/pep8config/.pep8
  src/test/pythonFiles/linting/pycodestyleconfig/.pycodestyle
  src/test/pythonFiles/linting/pycodestyleconfig/file.py
  src/testMultiRootWkspc/multi.code-workspace
Labels: external contributor

#7115 Ship 2 versions of PTVSD in the extension
  CONTRIBUTING.md
  build/ci/templates/build_compile_steps.yml
  build/ci/templates/test_phases.yml
  gulpfile.js
  pythonFiles/install_ptvsd.py
  pythonFiles/ptvsd_launcher.py
  requirements.txt
Labels: skip news

#7158 add cron job to nightly tests (#7128)
  build/ci/vscode-python-nightly-ci.yaml
Labels: skip news

#7162 Update LS experiment values
  experiments.json
Labels: skip news
