Repository microsoft/vscode-python, pull requests merged in 2019-10, with the labels that each got.

#7709 Refactor command finder into a separate class
  src/client/datascience/constants.ts
  src/client/datascience/jupyter/jupyterCommandFinder.ts
  src/client/datascience/jupyter/jupyterExecution.ts
Labels: skip news

#7713 Temporarily disable python news tests (currently failing and blocking PRs).
  build/ci/templates/test_phases.yml
Labels: skip news

#7723 Fast CI/PR pipeline. Tests need not wait for build
  build/ci/vscode-python-ci.yaml
  build/ci/vscode-python-pr-validation.yaml
Labels: skip news

#7741 Preparing for 2019.10 RC - fix toml and change log
  CHANGELOG.md
  tpn/distribution.toml
  tpn/tpn/__main__.py
Labels: skip news

#7748 Updating master version to 2019.11.0-dev
  package-lock.json
  package.json
Labels: skip news

#7714 Ensure search for jupyter commands are cancelled early
  src/client/common/cancellation.ts
  src/client/datascience/jupyter/jupyterCommandFinder.ts
Labels: skip news

#7744 Use correct resource to retrieve settings in activationService.ts
  src/client/activation/activationService.ts
Labels: skip news

#7740 Variable explorer and mime test fixes for tests
  pythonFiles/datascience/getJupyterVariableValue.py
  src/client/datascience/interactive-common/interactiveWindowTypes.ts
  src/datascience-ui/interactive-common/mainStateController.ts
  src/test/datascience/nativeEditor.functional.test.tsx
  src/test/datascience/variableexplorer.functional.test.tsx
Labels: skip news

#7755 Ensure datas cience smoke tests run only on python3
  uitests/features/datascience/basic.feature
Labels: skip news

#7749 Add missing PyPI packages to toml
  ThirdPartyNotices-Distribution.txt
  tpn/distribution.toml
Labels: skip news

#7742 Added button to get more info related to inheritEnv setting when prompt is dispalyed
  package.nls.json
  src/client/common/utils/localize.ts
  src/client/interpreter/virtualEnvs/condaInheritEnvPrompt.ts
  src/client/telemetry/index.ts
  src/test/interpreters/virtualEnvs/condaInheritEnvPrompt.unit.test.ts
Labels: skip news

#7758 Cherry-pick Add missing PyPI packages to toml
  ThirdPartyNotices-Distribution.txt
  tpn/distribution.toml
Labels: skip news

#7762 Enabled Python tests for news
  build/ci/templates/test_phases.yml
Labels: skip news

#7774 Disable smoke tests against Python 2.7
  build/ci/templates/jobs/smoke.yml
Labels: skip news

#7777 Turn on the native editor by default
  package.json
Labels: skip news

#7763 Adding both apache and BSD licenses for `packaging` based on CELA recommendation
  ThirdPartyNotices-Distribution.txt
  tpn/distribution.toml
Labels: skip news

#7785 Cherry-pick license update from master to release
  ThirdPartyNotices-Distribution.txt
  tpn/distribution.toml
Labels: skip news

#7689 Add command to clear LS analysis cache
  package.json
  package.nls.json
  src/client/activation/languageServer/constants.ts
  src/client/activation/languageServer/languageServer.ts
  src/client/common/application/commands.ts
  src/test/activation/languageServer/languageServer.unit.test.ts
Labels: skip news

#7797 Tests for keyboard shortcuts in native editor
  src/datascience-ui/interactive-common/cellOutput.tsx
  src/datascience-ui/react-common/monacoEditor.tsx
  src/test/datascience/nativeEditor.functional.test.tsx
  src/test/datascience/nativeEditorTestHelpers.tsx
  src/test/datascience/testHelpers.tsx
Labels: skip news

#7819 Smoke tests does not depend on build stage
  build/ci/vscode-python-ci.yaml
  build/ci/vscode-python-pr-validation.yaml
Labels: skip news

#7824 Tests for undo using keyboard shortcut 'z'
  src/datascience-ui/interactive-common/mainStateController.ts
  src/test/datascience/nativeEditor.functional.test.tsx
Labels: skip news

#7828 Preparing for release
  CHANGELOG.md
  news/1 Enhancements/4441.md
  news/2 Fixes/7624.md
  news/2 Fixes/7638.md
  news/2 Fixes/7688.md
  package-lock.json
  package.json
Labels: skip news

#7829 Rename startup telemetry property to lsStartup
  src/client/activation/activationService.ts
  src/client/telemetry/index.ts
Labels: skip news

#7863 Remove jison dependency
  package-lock.json
  package.json
Labels: skip news

#7883 Another fix for focus on add
  src/datascience-ui/native-editor/nativeEditor.tsx
Labels: skip news

#7814 Remove --ci flag from install_ptvsd.py
  build/ci/templates/steps/build.yml
  build/ci/templates/test_phases.yml
  news/2 Fixes/7814.md
  pythonFiles/install_ptvsd.py
Labels: external contributor, unplanned

#7901 Don't prompt to update inheritEnv when on Windows
  package.nls.json
  src/client/common/utils/localize.ts
  src/client/interpreter/virtualEnvs/condaInheritEnvPrompt.ts
  src/test/interpreters/virtualEnvs/condaInheritEnvPrompt.unit.test.ts
Labels: skip news

#7918 Fix function test for auto save
  src/test/datascience/nativeEditor.functional.test.tsx
Labels: skip news

#7940 Fixes to functional test failures on Windows
  package-lock.json
  src/datascience-ui/interactive-common/mainState.ts
  src/test/activation/activationService.unit.test.ts
  src/test/datascience/datascience.unit.test.ts
  src/test/datascience/editor-integration/cellhashprovider.unit.test.ts
  src/test/datascience/editor-integration/codewatcher.unit.test.ts
  src/test/datascience/editor-integration/helpers.ts
  src/test/datascience/intellisense.unit.test.ts
  src/test/datascience/interactiveWindow.functional.test.tsx
  src/test/datascience/interactiveWindowTestHelpers.tsx
  src/test/datascience/liveshare.functional.test.tsx
  src/test/datascience/mockDocumentManager.ts
  src/test/datascience/mockJupyterManager.ts
  src/test/datascience/mockLiveShare.ts
  src/test/datascience/nativeEditor.functional.test.tsx
  src/test/datascience/notebook.functional.test.ts
  src/test/debugger/extension/configuration/resolvers/attach.unit.test.ts
  src/test/debugger/extension/configuration/resolvers/launch.unit.test.ts
  src/test/mocks/vsc/charCode.ts
  src/test/mocks/vsc/index.ts
  src/test/mocks/vsc/uri.ts
  src/test/testing/codeLenses/testFiles.unit.test.ts
  src/test/testing/pytest/services/discoveryService.unit.test.ts
  src/test/vscode-mock.ts
Labels: skip news

#7996 Disable new debug adapter experiments
  experiments.json
Labels: skip news

#7867 add task to fix pywin32 issue
  build/ci/templates/test_phases.yml
  news/3 Code Health/7798.md
Labels: skip news

#8082 Add telemetry for idle timeout and shorten timeout time
  package.json
  src/client/common/types.ts
  src/client/datascience/constants.ts
  src/client/datascience/interactive-common/interactiveBase.ts
  src/client/datascience/jupyter/jupyterConnection.ts
  src/client/datascience/jupyter/jupyterExecution.ts
  src/client/datascience/jupyter/jupyterNotebook.ts
  src/client/datascience/jupyter/jupyterSession.ts
  src/client/datascience/jupyter/jupyterSessionManager.ts
  src/client/datascience/jupyter/jupyterSessionManagerFactory.ts
  src/client/datascience/jupyter/jupyterWebSocket.ts
  src/client/datascience/types.ts
  src/client/telemetry/index.ts
  src/test/datascience/notebook.functional.test.ts
Labels: skip news

#8081 Fixes to allowing users to open a diff view for ipynb files
  src/client/datascience/interactive-ipynb/nativeEditorProvider.ts
  src/test/datascience/interactive-ipynb/nativeEditorProvider.unit.test.ts
Labels: skip news

#8109 Ensure metadata for notebooks are always present
  src/client/datascience/interactive-common/interactiveBase.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/test/datascience/nativeEditor.functional.test.tsx
Labels: skip news

#7964 Fix typo in package.json
  package.json
Labels: external contributor, skip news

#8095 Do not auto save if notebook is untitled
  src/client/datascience/interactive-ipynb/autoSaveService.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/types.ts
Labels: skip news

#8135 Fix unit test build error
  src/client/datascience/interactive-ipynb/nativeEditor.ts
Labels: skip news

#7812 Fix: sonar issues
  news/2 Fixes/7812.md
  src/client/datascience/interactive-ipynb/nativeEditorProvider.ts
  src/datascience-ui/native-editor/nativeEditor.less
  src/datascience-ui/react-common/imageButton.css
Labels: data science, external contributor

#8129 Cherry pick inhertEnv and disable debug adapter experiment into release
  experiments.json
  news/2 Fixes/7836.md
  package.nls.json
  pythonFiles/install_ptvsd.py
  pythonFiles/ptvsd_folder_name.py
  pythonFiles/tests/__init__.py
  pythonFiles/tests/debug_adapter/test_ptvsd_folder_name.py
  pythonFiles/tests/debug_adapter/test_ptvsd_folder_name_functional.py
  src/client/common/utils/localize.ts
  src/client/interpreter/virtualEnvs/condaInheritEnvPrompt.ts
  src/client/telemetry/index.ts
  src/test/interpreters/virtualEnvs/condaInheritEnvPrompt.unit.test.ts
Labels: skip news

#8185 Merging from release into master
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
  build/ci/templates/steps/initialization.yml
  news/1 Enhancements/4441.md
  news/2 Fixes/7688.md
  package-lock.json
  package.json
  tpn/distribution.toml
Labels: skip news

#8220 Fix broken test in native editor
  src/test/datascience/interactive-ipynb/nativeEditor.unit.test.ts
Labels: skip news

#8224 Validation fixes for color theming in plot selection list
  src/datascience-ui/react-common/svgList.css
  src/datascience-ui/react-common/svgList.tsx
Labels: skip news

#8119 Use python debug adapter when in experiment
  ThirdPartyNotices-Distribution.txt
  pythonFiles/install_ptvsd.py
  pythonFiles/ptvsd_folder_name.py
  pythonFiles/tests/debug_adapter/test_install_ptvsd.py
  pythonFiles/tests/debug_adapter/test_ptvsd_folder_name.py
  pythonFiles/tests/debug_adapter/test_ptvsd_folder_name_functional.py
  requirements.txt
  src/client/api.ts
  src/client/debugger/extension/adapter/factory.ts
  src/client/debugger/extension/types.ts
  src/test/debugger/extension/adapter/factory.unit.test.ts
  src/test/extension.unit.test.ts
  src/test/mocks/vsc/extHostedTypes.ts
  tpn/distribution.toml
Labels: skip news

#8092 Add command translation for Farsi/Persian
  news/1 Enhancements/8092.md
  package.nls.fa.json
Labels: external contributor, unplanned

#8113 Fix name of launch option in docs
  CONTRIBUTING.md
Labels: external contributor, skip news

#8258 Re-Enable ability to use built in debugger for DS
  src/client/datascience/jupyter/jupyterDebugger.ts
Labels: skip news

#8282 Fix gulp install python libs commands with `python`
  gulpfile.js
Labels: skip news

#8281 removed max-width from .controls-div to give it the space it need with bigger font sizes
  src/datascience-ui/native-editor/nativeEditor.less
Labels: skip news

#8283 Ensure ctrl+s is not supported on Mac for Notebooks
  src/datascience-ui/native-editor/nativeCell.tsx
  src/datascience-ui/native-editor/nativeEditor.tsx
  src/test/datascience/nativeEditor.functional.test.tsx
Labels: skip news

#8288 removed extra space at the left of the native editor
  build/ci/templates/globals.yml
  build/ci/templates/jobs/uitest.yml
  src/datascience-ui/native-editor/nativeEditor.less
Labels: skip news

#8305 added telemetry to the errorHandler when jupyter is or isn't installed
  src/client/datascience/constants.ts
  src/client/datascience/errorHandler/errorHandler.ts
  src/client/telemetry/index.ts
Labels: skip news

#8299 Enhance "select a workspace" message when selecting interpreter
  news/1 Enhancements/8103.md
  src/client/interpreter/configuration/interpreterSelector.ts
Labels: external contributor, unplanned

#8313 Fix Language Server download typo
  package.nls.json
  src/client/common/utils/localize.ts
Labels: skip news

#8267 Changing NewDebugAdapter experiment to be on for 50% of insiders users
  experiments.json
  src/client/common/experimentGroups.ts
Labels: skip news

#8312 Ensure data science debugger works with the shipped version of PTVSD
  src/client/datascience/jupyter/jupyterDebugger.ts
  src/test/datascience/dataScienceIocContainer.ts
Labels: skip news

#8317 Cache the promise returned by the command finder
  src/client/datascience/jupyter/jupyterCommandFinder.ts
Labels: skip news

#8328 fix text/html to concat multiline strings
  news/2 Fixes/7873.md
  src/datascience-ui/interactive-common/cellOutput.tsx
Labels: data science

#8322 Adjust line number styles to line up with VSCode
  news/1 Enhancements/8289.md
  src/datascience-ui/interactive-common/mainStateController.ts
  src/datascience-ui/native-editor/nativeEditorStateController.ts
  src/datascience-ui/react-common/monacoEditor.css
Labels: data science
