Repository microsoft/vscode-python, pull requests merged in 2019-02, with the labels that each got.

#4289 Add ability to navigate to tests
  .vscode/settings.json
  pythonFiles/symbolProvider.py
  src/client/activation/jedi.ts
  src/client/activation/languageServer/languageServer.ts
  src/client/common/constants.ts
  src/client/common/types.ts
  src/client/extension.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/client/unittests/codeLenses/main.ts
  src/client/unittests/common/services/storageService.ts
  src/client/unittests/common/types.ts
  src/client/unittests/display/picker.ts
  src/client/unittests/main.ts
  src/client/unittests/navigation/commandHandler.ts
  src/client/unittests/navigation/fileNavigator.ts
  src/client/unittests/navigation/functionNavigator.ts
  src/client/unittests/navigation/helper.ts
  src/client/unittests/navigation/serviceRegistry.ts
  src/client/unittests/navigation/suiteNavigator.ts
  src/client/unittests/navigation/symbolProvider.ts
  src/client/unittests/navigation/types.ts
  src/client/unittests/serviceRegistry.ts
  src/client/unittests/types.ts
  src/test/activation/languageServer/languageServer.unit.test.ts
  src/test/interpreters/locators/workspaceVirtualEnvService.test.ts
  src/test/unittests/navigation/commandHandlers.unit.test.ts
  src/test/unittests/navigation/fileNavigator.unit.test.ts
  src/test/unittests/navigation/functionNavigator.unit.test.ts
  src/test/unittests/navigation/helper.unit.test.ts
  src/test/unittests/navigation/serviceRegistry.unit.test.ts
  src/test/unittests/navigation/suiteNavigator.unit.test.ts
  src/test/unittests/navigation/symbolNavigator.unit.test.ts
  src/test/vscode-mock.ts
Labels: skip news

#4304 Add TreeView data model and hook up existing test data
  src/client/extension.ts
  src/client/providers/testTreeViewItem.ts
  src/client/providers/testTreeViewProvider.ts
  src/client/providers/types.ts
  src/client/unittests/common/services/storageService.ts
  src/client/unittests/common/types.ts
  src/client/unittests/main.ts
  src/client/unittests/providers/testTreeViewItem.ts
  src/client/unittests/providers/testTreeViewProvider.ts
  src/client/unittests/serviceRegistry.ts
  src/test/vscode-mock.ts
Labels: skip news

#4315 Add "Configure Unit Tests" to the testing quick-pick.
  src/client/unittests/display/picker.ts
Labels: skip news

#4319 Raise event when status of a test manager changes
  src/client/unittests/common/managers/baseTestManager.ts
  src/client/unittests/common/services/storageService.ts
  src/client/unittests/common/services/workspaceTestManagerService.ts
  src/client/unittests/common/testUtils.ts
  src/client/unittests/common/types.ts
  src/client/unittests/main.ts
  src/client/unittests/providers/testTreeViewProvider.ts
  src/client/unittests/types.ts
Labels: skip news

#4324 Fix compiler issues in tests
  src/test/common/utils/cacheUtils.unit.test.ts
Labels: skip news

#4332 Add commands to run, debug and open tests
  package.json
  pythonFiles/symbolProvider.py
  resources/dark/debug.svg
  resources/dark/open-file.svg
  resources/dark/start.svg
  resources/light/debug.svg
  resources/light/open-file.svg
  resources/light/start.svg
  src/client/common/constants.ts
  src/client/extension.ts
  src/client/telemetry/types.ts
  src/client/unittests/common/constants.ts
  src/client/unittests/common/testUtils.ts
  src/client/unittests/navigation/types.ts
  src/client/unittests/providers/commandHandlers.ts
  src/client/unittests/providers/testTreeViewItem.ts
  src/client/unittests/providers/testTreeViewProvider.ts
  src/client/unittests/serviceRegistry.ts
  src/test/unittests/explorer/testExplorerCommandHandler.unit.test.ts
Labels: skip news

#4012 Added Dutch language
  news/1 Enhancements/4186.md
  package.nls.nl.json
Labels: external contributor

#4354 Set focus to editor and navigate to tests upon selection in test explorer
  src/client/telemetry/index.ts
  src/client/unittests/navigation/fileNavigator.ts
  src/client/unittests/navigation/functionNavigator.ts
  src/client/unittests/navigation/helper.ts
  src/client/unittests/navigation/suiteNavigator.ts
  src/client/unittests/navigation/types.ts
  src/client/unittests/providers/commandHandlers.ts
  src/client/unittests/providers/testTreeViewItem.ts
  src/test/unittests/explorer/testExplorerCommandHandler.unit.test.ts
  src/test/unittests/navigation/fileNavigator.unit.test.ts
  src/test/unittests/navigation/functionNavigator.unit.test.ts
  src/test/unittests/navigation/suiteNavigator.unit.test.ts
Labels: skip news

#4407 Attempt to fix CI build for functional on 2.7
  build/ci/templates/test-phase.yml
Labels: skip news

#4428 Fix up venv tests
  src/test/common/terminals/environmentActivationProviders/terminalActivation.testvirtualenvs.ts
  src/test/smoke/debugger.smoke.test.ts
  src/test/smoke/runInTerminal.smoke.test.ts
  src/testMultiRootWkspc/smokeTests/testExecInTerminal.py
Labels: external contributor, skip news

#4365 Clean up/refactor TestTreeViewProvider & TestViewItem
  src/client/providers/types.ts
  src/client/unittests/explorer/commandHandlers.ts
  src/client/unittests/explorer/testTreeViewItem.ts
  src/client/unittests/explorer/testTreeViewProvider.ts
  src/client/unittests/main.ts
  src/client/unittests/providers/testTreeViewItem.ts
  src/client/unittests/providers/testTreeViewProvider.ts
  src/client/unittests/serviceRegistry.ts
  src/client/unittests/types.ts
  src/test/unittests/explorer/explorerTestData.ts
  src/test/unittests/explorer/testExplorerCommandHandler.unit.test.ts
  src/test/unittests/explorer/testTreeViewItem.unit.test.ts
  src/test/unittests/explorer/testTreeViewProvider.unit.test.ts
  src/test/vscode-mock.ts
Labels: skip news

#4395 Make sure *no* settings are updated under cancellation.
  src/client/unittests/common/managers/testConfigurationManager.ts
  src/client/unittests/configuration.ts
  src/test/unittests/configuration.unit.test.ts
Labels: skip news

#4454 Fix icons in test explorer and items
  package.json
  resources/dark/run-failed-tests.svg
  resources/dark/run-tests.svg
  resources/dark/start-failed.svg
  resources/light/run-failed-tests.svg
  resources/light/run-tests.svg
  resources/light/start-failed.svg
Labels: skip news

#4360 Fix precedence in `parsePyTestModuleCollectionResult`
  news/2 Fixes/4360.md
  src/client/unittests/pytest/services/parserService.ts
Labels: external contributor

#4208 Set up tests for the extension's Python files.
  pythonFiles/tests/__init__.py
  pythonFiles/tests/datascience/__init__.py
  pythonFiles/tests/run_all.py
Labels: skip news

#4461 Add status indicator for icons in test explorer
  package.json
  resources/dark/debugging.svg
  resources/dark/discovering-tests.svg
  resources/dark/status-error.svg
  resources/dark/status-ok.svg
  resources/light/debugging.svg
  resources/light/discovering-tests.svg
  resources/light/status-error.svg
  resources/light/status-ok.svg
  src/client/common/constants.ts
  src/client/common/utils/icons.ts
  src/client/extension.ts
  src/client/unittests/codeLenses/testFiles.ts
  src/client/unittests/common/constants.ts
  src/client/unittests/common/managers/baseTestManager.ts
  src/client/unittests/common/services/contextService.ts
  src/client/unittests/common/services/storageService.ts
  src/client/unittests/common/services/testsStatusService.ts
  src/client/unittests/common/testUtils.ts
  src/client/unittests/common/testVisitors/folderGenerationVisitor.ts
  src/client/unittests/common/testVisitors/visitor.ts
  src/client/unittests/common/types.ts
  src/client/unittests/common/xUnitParser.ts
  src/client/unittests/explorer/commandHandlers.ts
  src/client/unittests/explorer/testTreeViewItem.ts
  src/client/unittests/explorer/testTreeViewProvider.ts
  src/client/unittests/main.ts
  src/client/unittests/nosetest/services/parserService.ts
  src/client/unittests/pytest/services/parserService.ts
  src/client/unittests/pytest/services/testMessageService.ts
  src/client/unittests/serviceRegistry.ts
  src/client/unittests/unittest/main.ts
  src/client/unittests/unittest/runner.ts
  src/client/unittests/unittest/services/parserService.ts
  src/test/unittests/common/services/contextService.unit.test.ts
  src/test/unittests/common/services/testStatusService.unit.test.ts
  src/test/unittests/common/testUtils.unit.test.ts
  src/test/unittests/explorer/explorerTestData.ts
  src/test/unittests/explorer/testTreeViewItem.unit.test.ts
  src/test/unittests/explorer/testTreeViewProvider.unit.test.ts
  src/test/unittests/mocks.ts
  src/test/unittests/pytest/pytest.run.test.ts
  src/test/unittests/pytest/pytest_run_tests_data.ts
  src/test/unittests/serviceRegistry.ts
  src/test/unittests/unittest/unittest.discovery.unit.test.ts
Labels: skip news

#4460 Travis package fixup (insiders not being uploaded)
  gulpfile.js
Labels: skip news

#4485 Fix smoke tests
  src/client/application/diagnostics/checks/invalidPythonPathInDebugger.ts
  src/client/datascience/jupyter/liveshare/liveShareParticipantMixin.ts
  src/test/application/diagnostics/checks/invalidPythonPathInDebugger.unit.test.ts
Labels: skip news

#4488 Fixes to bundling of extension
  .travis.yml
  build/webpack/common.js
  build/webpack/common.ts
  gulpfile.js
Labels: skip news

#4492 2019.2.0 release candidate
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
  news/1 Enhancements/3171.md
  news/1 Enhancements/3275.md
  news/1 Enhancements/332.md
  news/1 Enhancements/3581.md
  news/1 Enhancements/4064.md
  news/1 Enhancements/4183.md
  news/1 Enhancements/4184.md
  news/1 Enhancements/4186.md
  news/1 Enhancements/4272.md
  news/1 Enhancements/4275.md
  news/1 Enhancements/4279.md
  news/1 Enhancements/4286.md
  news/1 Enhancements/4287.md
  news/1 Enhancements/4288.md
  news/1 Enhancements/4317.md
  news/1 Enhancements/4318.md
  news/1 Enhancements/4348.md
  news/1 Enhancements/4362.md
  news/1 Enhancements/4364.md
  news/1 Enhancements/4371.md
  news/1 Enhancements/4457.md
  news/2 Fixes/3008.md
  news/2 Fixes/3914.md
  news/2 Fixes/3995.md
  news/2 Fixes/4057.md
  news/2 Fixes/4145.md
  news/2 Fixes/4237.md
  news/2 Fixes/4255.md
  news/2 Fixes/4360.md
  news/2 Fixes/4394.md
  news/2 Fixes/4418.md
  news/3 Code Health/3973.md
  news/3 Code Health/4058.md
  news/3 Code Health/4091.md
  news/3 Code Health/4148.md
  news/3 Code Health/4199.md
  news/3 Code Health/4201.md
  news/3 Code Health/611.md
  package-lock.json
  package.json
Labels: skip news

#4498 Add an icon for stopping tests and remove unwanted icons
  package.json
  package.nls.json
  resources/dark/debugging.svg
  resources/dark/stop.svg
  resources/light/debugging.svg
  resources/light/discovering-tests.svg
  resources/light/stop.svg
  src/client/unittests/common/managers/baseTestManager.ts
Labels: skip news

#4446 Dev/ianhu/fetch variables impl
  package.nls.json
  pythonFiles/datascience/getJupyterVariableList.py
  src/client/common/utils/localize.ts
  src/client/datascience/history.ts
  src/client/datascience/jupyter/jupyterServer.ts
  src/client/datascience/jupyter/jupyterServerFactory.ts
  src/client/datascience/jupyter/jupyterServerManager.ts
  src/client/datascience/jupyter/jupyterVariables.ts
  src/client/datascience/jupyter/liveshare/guestJupyterServer.ts
  src/client/datascience/serviceRegistry.ts
  src/client/datascience/types.ts
  src/test/datascience/jupyterVariables.unit.test.ts
  src/test/datascience/notebook.functional.test.ts
Labels: skip news

#4536 Do not throw error in launch.json does not exist
  src/client/unittests/common/debugLauncher.ts
  src/test/unittests/common/debugLauncher.unit.test.ts
Labels: skip news

#4533 Run failed tests when using unit tests
  src/client/unittests/common/managers/baseTestManager.ts
  src/client/unittests/unittest/main.ts
  src/test/unittests/unittest/unittest.unit.test.ts
Labels: skip news

#4538 Remove package opn
  package-lock.json
  package.json
Labels: skip news

#4548 Ensure subsequent npm installs do not fail
  build/ci/postInstall.js
  build/ci/postInstall.ts
  news/3 Code Health/4109.md
Labels: skip news

#4435 Added command translations for polish
  README.md
  news/1 Enhancements/4435.md
  package.nls.pl.json
Labels: external contributor

#4500 update test plan
  .github/test_plan.md
Labels: external contributor, skip news

#4565 Disable output pane on isort failures
  news/1 Enhancements/2522.md
  src/client/providers/importSortProvider.ts
Labels: external contributor
