Repository microsoft/vscode-python, pull requests merged in 2019-01, with the labels that each got.

#3860 Add default debug config and fix labels
  resources/default.launch.json
  src/client/common/utils/localize.ts
  src/client/debugger/extension/configuration/debugConfigurationProvider.ts
  src/client/debugger/extension/configuration/debugConfigurationService.ts
  src/client/debugger/extension/configuration/providers/moduleLaunch.ts
  src/client/debugger/extension/types.ts
  src/test/debugger/attach.ptvsd.test.ts
  src/test/debugger/extension/configuration/debugConfigurationProvider.unit.test.ts
  src/test/debugger/extension/configuration/debugConfigurationService.unit.test.ts
  src/test/debugger/extension/configuration/providers/moduleLaunch.unit.test.ts
  src/test/debugger/extension/configuration/providers/providerFactory.unit.test.ts
  src/test/initialize.ts
Labels: skip news

#3838 Extend pvsc script
  news/3 Code Health/3837.md
  pvsc-dev-ext.py
Labels: external contributor

#3912 Explicitly find the full path to the executable being run
  pvsc-dev-ext.py
Labels: skip news

#3303 Show diagnostics for failed/skipped tests run with pytest
  .github/test_plan.md
  news/1 Enhancements/120.md
  package.nls.json
  src/client/common/utils/localize.ts
  src/client/unittests/common/managers/baseTestManager.ts
  src/client/unittests/common/services/unitTestDiagnosticService.ts
  src/client/unittests/common/types.ts
  src/client/unittests/common/xUnitParser.ts
  src/client/unittests/pytest/main.ts
  src/client/unittests/pytest/services/testMessageService.ts
  src/client/unittests/serviceRegistry.ts
  src/client/unittests/types.ts
  src/test/pythonFiles/testFiles/pytestFiles/results/one.output
  src/test/pythonFiles/testFiles/pytestFiles/results/one.xml
  src/test/pythonFiles/testFiles/pytestFiles/results/two.again.xml
  src/test/pythonFiles/testFiles/pytestFiles/results/two.output
  src/test/pythonFiles/testFiles/pytestFiles/results/two.xml
  src/test/pythonFiles/testFiles/standard/tests/external.py
  src/test/pythonFiles/testFiles/standard/tests/test_foreign_nested_tests.py
  src/test/unittests/debugger.test.ts
  src/test/unittests/pytest/pytest.discovery.test.ts
  src/test/unittests/pytest/pytest.run.test.ts
  src/test/unittests/pytest/pytest.testMessageService.test.ts
  src/test/unittests/pytest/pytest_run_tests_data.ts
  src/test/unittests/serviceRegistry.ts
  src/test/unittests/stoppingDiscoverAndTest.test.ts
  src/test/unittests/unittest/unittest.diagnosticService.unit.test.ts
  src/test/unittests/unittest/unittest.run.test.ts
Labels: external contributor

#3888 Fix logic for skipped test
  src/test/interpreters/locators/workspaceVirtualEnvService.test.ts
Labels: skip news

#3900 Improvements to execution times of CI on Travis
  .travis.yml
  gulpfile.js
  news/3 Code Health/3899.md
Labels: external contributor

#3907 Move svg-inline-react into dev dependencies
  package.json
Labels: external contributor, skip news

#3929 Skip venv discovery tests for Linux in VSTS
  src/test/interpreters/locators/workspaceVirtualEnvService.test.ts
Labels: skip news

#3923 Disable unreliable linting tests
  src/test/linters/lint.test.ts
Labels: skip news

#3975 gh-978: Escape the pipenv executable for activation.
  src/client/common/terminal/environmentActivationProviders/pipEnvActivationProvider.ts
  src/test/common/terminals/environmentActivationProviders/pipEnvActivationProvider.unit.test.ts
Labels: skip news

#3996 Revert changes to gulpfile.js
  gulpfile.js
Labels: skip news

#4000 Corrected keys in localize.ts
  src/client/common/utils/localize.ts
Labels: skip news

#4008 Fix broken telemetry unit tests
  src/test/telemetry/index.unit.test.ts
Labels: skip news

#4015 Skip functional tests that aren't successful in Linux on AzDO
  src/test/datascience/history.functional.test.tsx
  src/test/datascience/notebook.functional.test.ts
Labels: skip news

#3903 Add more logging for auto selection of interpreters
  .github/PULL_REQUEST_TEMPLATE.md
  src/client/common/logger.ts
  src/client/interpreter/autoSelection/index.ts
  src/client/interpreter/autoSelection/rules/baseRule.ts
  src/client/interpreter/autoSelection/rules/cached.ts
  src/client/interpreter/autoSelection/rules/currentPath.ts
  src/client/interpreter/autoSelection/rules/system.ts
  src/client/interpreter/autoSelection/rules/winRegistry.ts
  src/client/interpreter/autoSelection/rules/workspaceEnv.ts
  src/client/interpreter/autoSelection/types.ts
Labels: skip news

#4017 Send original event name when sending error event
  src/client/telemetry/index.ts
  src/test/datascience/history.functional.test.tsx
  src/test/telemetry/index.unit.test.ts
Labels: skip news

#4037 Ensure configuration changes are debounced correctly
  src/client/common/configSettings.ts
Labels: skip news

#3992 Use enums for telemetry event names
  news/3 Code Health/2904.md
  src/client/activation/activationService.ts
  src/client/activation/downloader.ts
  src/client/activation/languageServer/languageServer.ts
  src/client/activation/languageServer/languageServerCompatibilityService.ts
  src/client/activation/languageServer/manager.ts
  src/client/activation/progress.ts
  src/client/application/diagnostics/base.ts
  src/client/application/diagnostics/checks/powerShellActivation.ts
  src/client/application/diagnostics/commands/execVSCCommand.ts
  src/client/application/diagnostics/commands/ignore.ts
  src/client/application/diagnostics/commands/launchBrowser.ts
  src/client/common/configSettings.ts
  src/client/common/installer/productInstaller.ts
  src/client/common/nuget/azureBlobStoreNugetRepository.ts
  src/client/common/platform/platformService.ts
  src/client/common/process/pythonExecutionFactory.ts
  src/client/common/terminal/helper.ts
  src/client/common/terminal/service.ts
  src/client/debugger/extension/configuration/debugConfigurationService.ts
  src/client/debugger/extension/configuration/providers/djangoLaunch.ts
  src/client/debugger/extension/configuration/providers/fileLaunch.ts
  src/client/debugger/extension/configuration/providers/flaskLaunch.ts
  src/client/debugger/extension/configuration/providers/moduleLaunch.ts
  src/client/debugger/extension/configuration/providers/pyramidLaunch.ts
  src/client/debugger/extension/configuration/providers/remoteAttach.ts
  src/client/debugger/extension/configuration/resolvers/base.ts
  src/client/debugger/extension/hooks/childProcessAttachService.ts
  src/client/extension.ts
  src/client/formatters/autoPep8Formatter.ts
  src/client/formatters/blackFormatter.ts
  src/client/formatters/yapfFormatter.ts
  src/client/interpreter/activation/service.ts
  src/client/interpreter/autoSelection/index.ts
  src/client/interpreter/autoSelection/rules/baseRule.ts
  src/client/interpreter/configuration/pythonPathUpdaterService.ts
  src/client/interpreter/interpreterService.ts
  src/client/interpreter/locators/services/cacheableLocatorService.ts
  src/client/linters/linterCommands.ts
  src/client/linters/lintingEngine.ts
  src/client/providers/completionProvider.ts
  src/client/providers/definitionProvider.ts
  src/client/providers/hoverProvider.ts
  src/client/providers/importSortProvider.ts
  src/client/providers/objectDefinitionProvider.ts
  src/client/providers/referenceProvider.ts
  src/client/providers/renameProvider.ts
  src/client/providers/replProvider.ts
  src/client/providers/signatureProvider.ts
  src/client/providers/simpleRefactorProvider.ts
  src/client/providers/symbolProvider.ts
  src/client/providers/terminalProvider.ts
  src/client/providers/updateSparkLibraryProvider.ts
  src/client/telemetry/constants.ts
  src/client/terminals/codeExecution/codeExecutionManager.ts
  src/client/unittests/common/managers/baseTestManager.ts
  src/client/unittests/main.ts
  src/client/workspaceSymbols/generator.ts
  src/client/workspaceSymbols/provider.ts
Labels: skip news

#4031 Strong typing of telemetry properties
  src/client/application/diagnostics/base.ts
  src/client/application/diagnostics/types.ts
  src/client/common/logger.ts
  src/client/common/terminal/helper.ts
  src/client/datascience/constants.ts
  src/client/datascience/history.ts
  src/client/datascience/historycommandlistener.ts
  src/client/telemetry/index.ts
  src/client/telemetry/types.ts
  src/test/application/diagnostics/applicationDiagnostics.unit.test.ts
  src/test/application/diagnostics/checks/envPathVariable.unit.test.ts
  src/test/application/diagnostics/checks/invalidPythonPathInDebugger.unit.test.ts
  src/test/application/diagnostics/checks/lsNotSupported.unit.test.ts
  src/test/application/diagnostics/checks/macPythonInterpreter.unit.test.ts
  src/test/application/diagnostics/checks/powerShellActivation.unit.test.ts
  src/test/application/diagnostics/checks/pythonInterpreter.unit.test.ts
  src/test/application/diagnostics/commands/ignore.unit.test.ts
  src/test/application/diagnostics/promptHandler.unit.test.ts
  src/test/telemetry/index.unit.test.ts
Labels: skip news

#4041 Manually trigger creation of venvs to resolve flaky venv creation tests
  src/client/interpreter/locators/services/workspaceVirtualEnvWatcherService.ts
  src/test/interpreters/locators/workspaceVirtualEnvService.test.ts
Labels: skip news

#4045 Ensure code compiles in strict mode
  build/webpack/webpack.extension.dependencies.config.ts
  src/client/activation/languageServer/analysisOptions.ts
  src/client/common/utils/localize.ts
  src/client/common/variables/systemVariables.ts
  src/client/common/variables/types.ts
  src/client/datascience/history.ts
  src/client/datascience/jupyter/jupyterExecution.ts
  src/client/datascience/jupyter/jupyterServer.ts
  src/client/debugger/debugAdapter/DebugClients/helper.ts
  src/client/debugger/types.ts
  src/client/extension.ts
  src/client/interpreter/locators/services/cacheableLocatorService.ts
  src/client/interpreter/locators/services/pipEnvService.ts
  src/client/jupyter/provider.ts
  src/client/language/tokenizer.ts
  src/client/language/types.ts
  src/client/linters/bandit.ts
  src/client/linters/baseLinter.ts
  src/client/linters/errorHandlers/baseErrorHandler.ts
  src/client/linters/errorHandlers/errorHandler.ts
  src/client/linters/linterInfo.ts
  src/client/providers/jediProxy.ts
  src/client/telemetry/index.ts
  src/client/typeFormatters/dispatcher.ts
  src/client/unittests/display/picker.ts
  src/client/unittests/unittest/socketServer.ts
  src/datascience-ui/react-common/locReactSide.ts
  src/test/common/localize.unit.test.ts
  src/test/common/terminals/environmentActivationProviders/terminalActivation.testvirtualenvs.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/mockCommandManager.ts
  src/test/datascience/mockJupyterSession.ts
  src/test/debugger/envVars.test.ts
  src/test/debugger/extension/configuration/resolvers/base.unit.test.ts
  src/test/debugger/extension/configuration/resolvers/launch.unit.test.ts
  src/test/format/extension.format.test.ts
  src/test/interpreters/mocks.ts
  src/test/language/characterStream.test.ts
  src/test/language/textRange.test.ts
  src/test/languageServers/jedi/autocomplete/base.test.ts
  src/test/linters/lint.args.test.ts
  src/test/linters/linter.availability.unit.test.ts
  src/test/mockClasses.ts
  src/test/mocks/mementos.ts
  src/test/mocks/vsc/arrays.ts
  src/test/mocks/vsc/extHostedTypes.ts
  src/test/mocks/vsc/index.ts
  src/test/mocks/vsc/range.ts
  src/test/mocks/vsc/uri.ts
  src/test/performanceTest.ts
  src/test/smokeTest.ts
  src/test/telemetry/index.unit.test.ts
  src/test/testRunner.ts
  src/test/unittests/pytest/pytest.test.ts
  src/test/vscode-mock.ts
Labels: skip news

#3948 Match dots in ignorePatterns globs; fixes .venv not being ignored
  news/2 Fixes/3947.md
  src/client/linters/lintingEngine.ts
Labels: external contributor, type-bug

#4036 Ensure all diagnostic checks accept resource args
  src/client/activation/activationService.ts
  src/client/application/diagnostics/applicationDiagnostics.ts
  src/client/application/diagnostics/base.ts
  src/client/application/diagnostics/checks/envPathVariable.ts
  src/client/application/diagnostics/checks/invalidDebuggerType.ts
  src/client/application/diagnostics/checks/invalidPythonPathInDebugger.ts
  src/client/application/diagnostics/checks/lsNotSupported.ts
  src/client/application/diagnostics/checks/macPythonInterpreter.ts
  src/client/application/diagnostics/checks/powerShellActivation.ts
  src/client/application/diagnostics/checks/pythonInterpreter.ts
  src/client/application/diagnostics/types.ts
  src/client/application/types.ts
  src/client/common/terminal/activator/powershellFailedHandler.ts
  src/client/extension.ts
  src/test/activation/activationService.unit.test.ts
  src/test/application/diagnostics/applicationDiagnostics.unit.test.ts
  src/test/application/diagnostics/checks/envPathVariable.unit.test.ts
  src/test/application/diagnostics/checks/invalidPythonPathInDebugger.unit.test.ts
  src/test/application/diagnostics/checks/macPythonInterpreter.unit.test.ts
  src/test/application/diagnostics/checks/powerShellActivation.unit.test.ts
  src/test/application/diagnostics/checks/pythonInterpreter.unit.test.ts
  src/test/application/diagnostics/promptHandler.unit.test.ts
  src/test/interpreters/autoSelection/rules/cached.unit.test.ts
  src/test/interpreters/autoSelection/rules/currentPath.unit.test.ts
  src/test/interpreters/autoSelection/rules/system.unit.test.ts
  src/test/interpreters/autoSelection/rules/workspaceEnv.unit.test.ts
Labels: skip news

#4038 Ensure all diagnostic services do not handle the same messages more than once
  src/client/application/diagnostics/base.ts
  src/client/application/diagnostics/checks/envPathVariable.ts
  src/client/application/diagnostics/checks/invalidDebuggerType.ts
  src/client/application/diagnostics/checks/invalidPythonPathInDebugger.ts
  src/client/application/diagnostics/checks/lsNotSupported.ts
  src/client/application/diagnostics/checks/macPythonInterpreter.ts
  src/client/application/diagnostics/checks/powerShellActivation.ts
  src/client/application/diagnostics/checks/pythonInterpreter.ts
  src/client/application/diagnostics/types.ts
  src/test/application/diagnostics/checks/envPathVariable.unit.test.ts
  src/test/application/diagnostics/checks/invalidPythonPathInDebugger.unit.test.ts
  src/test/application/diagnostics/checks/lsNotSupported.unit.test.ts
  src/test/application/diagnostics/checks/powerShellActivation.unit.test.ts
  src/test/application/diagnostics/checks/pythonInterpreter.unit.test.ts
Labels: skip news

#3991 Fix typo in pythonPath setting name
  news/2 Fixes/4047.md
  src/client/extension.ts
Labels: external contributor

#4087 Slow updates to pip
  .travis.yml
  build/ci/templates/compile-and-validate.yml
  build/ci/templates/test-phase.yml
Labels: skip news

#4097 Telemetry tests fail when run locally on windows
  src/test/common.ts
  src/test/telemetry/index.unit.test.ts
Labels: skip news

#4105 Fixes for pipenv activation
  src/client/interpreter/contracts.ts
  src/client/interpreter/display/index.ts
  src/client/interpreter/interpreterService.ts
  src/test/datascience/notebook.functional.test.ts
  src/test/interpreters/interpreterService.unit.test.ts
Labels: skip news

#4118 Ensure diagnostic handlers are always displayed
  src/client/application/diagnostics/base.ts
  src/client/application/diagnostics/checks/invalidDebuggerType.ts
  src/client/application/diagnostics/checks/invalidPythonPathInDebugger.ts
  src/client/application/diagnostics/checks/powerShellActivation.ts
  src/client/application/diagnostics/types.ts
  src/test/application/diagnostics/applicationDiagnostics.unit.test.ts
  src/test/application/diagnostics/checks/invalidPythonPathInDebugger.unit.test.ts
  src/test/application/diagnostics/promptHandler.unit.test.ts
Labels: skip news

#4113 Change names of telemetry properties captured during load of ext
  src/client/extension.ts
  src/client/telemetry/types.ts
Labels: skip news

#4135 Register test services after starting LS
  src/client/activation/languageServer/languageServer.ts
  src/test/activation/languageServer/languageServer.unit.test.ts
Labels: skip news

#4136 Fixing validation of 'Improvements to message displayed when python path is invalid (in launch.json)'
  src/client/application/diagnostics/checks/invalidPythonPathInDebugger.ts
  src/client/application/diagnostics/types.ts
  src/client/debugger/extension/configuration/resolvers/base.ts
  src/client/debugger/extension/configuration/resolvers/launch.ts
  src/client/debugger/extension/types.ts
  src/test/application/diagnostics/checks/invalidPythonPathInDebugger.unit.test.ts
  src/test/debugger/extension/configuration/resolvers/launch.unit.test.ts
Labels: skip news

#4181 Making sure PreStartupHealthCheck works correctly
  src/client/application/diagnostics/applicationDiagnostics.ts
  src/test/application/diagnostics/applicationDiagnostics.unit.test.ts
  src/test/interpreters/autoSelection/index.unit.test.ts
  src/test/interpreters/autoSelection/rules/workspaceEnv.unit.test.ts
  src/test/interpreters/pipEnvService.unit.test.ts
  src/test/telemetry/index.unit.test.ts
Labels: skip news

#4193 Fix debugger tests to remove --file from the PTVSD CLI
  src/test/debugger/attach.ptvsd.test.ts
  src/test/debugger/capabilities.test.ts
Labels: skip news
