Repository microsoft/vscode-python, pull requests merged in 2019-09, with the labels that each got.

#7195 Modify experiments.json
  experiments.json
Labels: skip news

#7202 Update contributing guide
  CONTRIBUTING.md
Labels: skip news

#7203 Update experiments.json
  experiments.json
Labels: skip news

#7216 Extend description of dataScience.runStartupCommands
  package.json
Labels: data science, skip news

#7268 Preparation for point release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip news

#7295 Fix timeout logic to be back how it was before native editor fix
  package-lock.json
  src/client/datascience/jupyter/jupyterSession.ts
Labels: skip news

#7315 Add more logging for debugging to the nightly tests
  build/ci/vscode-python-nightly-flake-ci.yaml
  src/client/datascience/jupyter/jupyterDebugger.ts
Labels: skip news

#7387 Fixes to sourcing of fish scripts in terminal
  news/2 Fixes/7343.md
  src/client/common/terminal/environmentActivationProviders/bash.ts
  src/test/common/terminals/activation.bash.unit.test.ts
Labels: external contributor

#7384 Fixes to detection of shell
  news/2 Fixes/6928.md
  src/client/common/terminal/shellDetector.ts
  src/test/common/terminals/shellDetector.unit.test.ts
Labels: external contributor

#7403 Display python debug configurations in launch.json
  news/2 Fixes/7304.md
  src/client/debugger/extension/serviceRegistry.ts
  src/test/debugger/extension/serviceRegistry.unit.test.ts
Labels: external contributor

#7277 Remove `donjamayanne.jupyter` integration
  news/3 Code Health/6052.md
  src/client/common/constants.ts
  src/client/extension.ts
  src/client/jupyter/provider.ts
  src/client/linters/lintingEngine.ts
  src/client/linters/types.ts
Labels: external contributor

#7281 Use jsonc-parser instead of strip-json-comments
  news/3 Code Health/4819.md
  package-lock.json
  package.json
  src/client/datascience/codeCssGenerator.ts
Labels: external contributor

#7402 Ensure typescript import is relative to file path
  .vscode/settings.json
Labels: external contributor, skip news

#7415 Disable nightly test failures
  package-lock.json
  requirements.txt
  src/test/common/process/proc.observable.test.ts
  src/test/debugger/attach.ptvsd.test.ts
  src/test/debugger/capabilities.test.ts
Labels: skip news

#7427 Refactor native cell toolbar into the nativeCell itself
  src/datascience-ui/native-editor/nativeCell.tsx
  src/datascience-ui/native-editor/nativeEditor.tsx
Labels: skip news

#7435 Change name of generated analysis html file
  build/webpack/webpack.debugadapter.config.js
  build/webpack/webpack.debugadapter.config.ts
Labels: skip news, type-code health

#7432 Run smoke tests for Windows and others on CI and Nightly
  build/ci/vscode-python-ci.yaml
  build/ci/vscode-python-nightly-ci.yaml
  build/ci/vscode-python-pr-validation.yaml
Labels: external contributor, skip news

#7388 Handle situations where language client is disposed earlier than expected
  news/3 Code Health/6865.md
  src/client/activation/languageServer/languageServer.ts
  src/test/activation/languageServer/languageServer.unit.test.ts
Labels: external contributor

#7400 Restore "Ensure Windows Store install of Python is detected correctly" 6980
  news/2 Fixes/5926.md
  src/client/common/process/pythonExecutionFactory.ts
  src/client/common/process/pythonProcess.ts
  src/client/common/process/windowsStorePythonProcess.ts
  src/client/interpreter/helpers.ts
  src/client/interpreter/interpreterService.ts
  src/client/interpreter/locators/index.ts
  src/client/interpreter/locators/services/interpreterFilter.ts
  src/client/interpreter/locators/services/windowsStoreInterpreter.ts
  src/client/interpreter/locators/types.ts
  src/client/interpreter/serviceRegistry.ts
  src/test/common/installer.test.ts
  src/test/common/moduleInstaller.test.ts
  src/test/common/process/pythonExecutionFactory.unit.test.ts
  src/test/common/process/pythonProc.simple.multiroot.test.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/format/extension.format.test.ts
  src/test/interpreters/helpers.unit.test.ts
  src/test/interpreters/interpreterService.unit.test.ts
  src/test/interpreters/locators/index.unit.test.ts
  src/test/linters/lint.functional.test.ts
  src/test/refactor/rename.test.ts
  src/test/serviceRegistry.ts
  src/test/testing/nosetest/nosetest.disovery.test.ts
  src/test/testing/nosetest/nosetest.run.test.ts
  src/test/testing/pytest/pytest.discovery.test.ts
  src/test/testing/pytest/pytest.run.test.ts
  src/test/testing/unittest/unittest.discovery.test.ts
  src/test/testing/unittest/unittest.run.test.ts
Labels: external contributor

#7430 Refactor pipelines into stages
  .vscode/settings.json
  build/ci/templates/globals.yml
  build/ci/templates/jobs/build_compile.yml
  build/ci/templates/jobs/coverage.yml
  build/ci/templates/jobs/smoke_test.yml
  build/ci/templates/jobs/uitest.yml
  build/ci/templates/steps/build.yml
  build/ci/templates/steps/build_compile.yml
  build/ci/templates/steps/compile.yml
  build/ci/templates/steps/generate_upload_coverage.yml
  build/ci/templates/steps/initialization.yml
  build/ci/templates/steps/lint.yml
  build/ci/templates/steps/merge_upload_coverage.yml
  build/ci/templates/steps/uitest.yml
  build/ci/templates/test_phases.yml
  build/ci/vscode-python-ci.yaml
  build/ci/vscode-python-nightly-ci.yaml
  build/ci/vscode-python-nightly-flake-ci.yaml
  build/ci/vscode-python-pr-validation.yaml
  news/3 Code Health/7431.md
Labels: external contributor

#7455 Fixes to datascience ci pipeline
  src/test/datascience/dataScienceIocContainer.ts
Labels: external contributor, skip news

#7464 Ability to prevent logging python execution info
  src/client/common/constants.ts
  src/client/common/process/logger.ts
Labels: skip news

#7467 Decrease refresh rate of test progress indicator
  src/client/testing/display/main.ts
Labels: external contributor, skip news

#7468 Add setting for caching level in the language server analysis
  package.json
Labels: external contributor, skip news

#7498 Update LS experiment numbers
  experiments.json
Labels: skip news

#7263 Clean up XUnitParser and add tests.
  src/client/testing/common/services/discoveredTestParser.ts
  src/client/testing/common/services/testResultsService.ts
  src/client/testing/common/testUtils.ts
  src/client/testing/common/types.ts
  src/client/testing/common/xUnitParser.ts
  src/client/testing/explorer/commandHandlers.ts
  src/client/testing/explorer/failedTestHandler.ts
  src/client/testing/explorer/testTreeViewItem.ts
  src/client/testing/explorer/testTreeViewProvider.ts
  src/client/testing/nosetest/runner.ts
  src/client/testing/pytest/runner.ts
  src/client/testing/types.ts
  src/test/testing/common/services/storageService.unit.test.ts
  src/test/testing/common/services/testResultsService.unit.test.ts
  src/test/testing/common/services/testStatusService.unit.test.ts
  src/test/testing/common/testUtils.unit.test.ts
  src/test/testing/common/xUnitParser.unit.test.ts
  src/test/testing/explorer/testTreeViewItem.unit.test.ts
  src/test/testing/explorer/testTreeViewProvider.unit.test.ts
  src/test/testing/helper.ts
  src/test/testing/pytest/pytest.testMessageService.test.ts
  src/test/testing/results.ts
  src/test/testing/unittest/unittest.unit.test.ts
Labels: skip news

#7477 Guarantee that master branch has "-dev" tag in version
  build/ci/templates/globals.yml
  news/3 Code Health/7471.md
  src/test/extension.unit.test.ts
Labels: skip news

#7504 Grid layout for cell-results and expanding collapse bar
  src/datascience-ui/interactive-common/cellOutput.tsx
  src/datascience-ui/native-editor/nativeCell.tsx
  src/datascience-ui/native-editor/nativeEditor.less
Labels: skip news

#7507 prevent input text extraction from messing with cell source
  src/datascience-ui/interactive-common/mainState.ts
Labels: skip news

#7279 Drop `python.updateSparkLibrary` command
  build/existingFiles.json
  build/unlocalizedFiles.json
  news/3 Code Health/6091.md
  package.json
  package.nls.de.json
  package.nls.es.json
  package.nls.fr.json
  package.nls.it.json
  package.nls.ja.json
  package.nls.json
  package.nls.ko-kr.json
  package.nls.nl.json
  package.nls.pl.json
  package.nls.pt-br.json
  package.nls.ru.json
  package.nls.zh-cn.json
  package.nls.zh-tw.json
  src/client/common/constants.ts
  src/client/extension.ts
  src/client/providers/updateSparkLibraryProvider.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
Labels: external contributor

#7541 Run fish activation scripts with `source` instead of `.
  news/2 Fixes/7343.md
  src/client/common/terminal/environmentActivationProviders/bash.ts
  src/test/common/terminals/activation.bash.unit.test.ts
Labels: external contributor

#7152 Pass PTVSD folder name to the new debug adapter executable
  build/ci/templates/steps/build_compile.yml
  build/ci/templates/test_phases.yml
  build/test-requirements.txt
  pythonFiles/install_ptvsd.py
  pythonFiles/ptvsd_folder_name.py
  pythonFiles/tests/__init__.py
  pythonFiles/tests/__main__.py
  pythonFiles/tests/debug_adapter/__init__.py
  pythonFiles/tests/debug_adapter/test_ptvsd_folder_name.py
  pythonFiles/tests/debug_adapter/test_ptvsd_folder_name_functional.py
  requirements.txt
  src/client/api.ts
  src/client/debugger/extension/adapter/factory.ts
  src/client/debugger/extension/serviceRegistry.ts
  src/client/debugger/extension/types.ts
  src/test/debugger/extension/adapter/factory.unit.test.ts
Labels: skip news

#7545 Add bug and feature templates for Data Science features
  .github/ISSUE_TEMPLATE/ds_bug_report.md
  .github/ISSUE_TEMPLATE/ds_feature_request.md
Labels: skip news

#7555 Install ptvsd wheels for all tests
  build/ci/templates/test_phases.yml
  build/ci/vscode-python-pr-validation.yaml
Labels: skip news

#7560 Adjust new DS issue titles
  .github/ISSUE_TEMPLATE/ds_bug_report.md
  .github/ISSUE_TEMPLATE/ds_feature_request.md
Labels: skip news

#7539 Fix Gather and update py analysis
  build/ci/postInstall.js
  package-lock.json
  package.datascience-ui.dependencies.json
  package.json
  pythonFiles/datascience/getJupyterVariableDataFrameInfo.py
  pythonFiles/datascience/getJupyterVariableDataFrameRows.py
  pythonFiles/datascience/getJupyterVariableList.py
  pythonFiles/datascience/getJupyterVariableValue.py
  pythonFiles/datascience/getServerInfo.py
  src/client/datascience/gather/gather.ts
  src/client/datascience/interactive-common/interactiveBase.ts
  src/client/datascience/jupyter/jupyterNotebook.ts
  src/client/datascience/types.ts
Labels: skip news

#7577 Update timeout value for CI builds
  build/ci/vscode-python-ci.yaml
Labels: skip news

#7566 data science label shouldn't be quoted in template
  .github/ISSUE_TEMPLATE/ds_bug_report.md
  .github/ISSUE_TEMPLATE/ds_feature_request.md
Labels: skip news

#7551 Davidkutu/intellisense refactor
  src/client/datascience/interactive-common/intellisense/baseIntellisenseProvider.ts
  src/client/datascience/interactive-common/intellisense/intellisenseDocument.ts
Labels: skip news

#7254 Update experiment numbers for the new debug adapter
  experiments.json
  src/client/common/experimentGroups.ts
  src/client/debugger/extension/adapter/activator.ts
Labels: skip news

#7616 When code runner extension gets installed, disable the play button icon immediately
  package.json
  resources/dark/run-file.svg
  resources/light/run-file.svg
  src/client/common/application/extensions.ts
  src/client/common/types.ts
  src/client/terminals/activation.ts
  src/test/datascience/mockExtensions.ts
  src/test/terminals/activation.unit.test.ts
Labels: skip news

#7617 Use env variables to disable features for UI Tests
  src/client/common/insidersBuild/insidersExtensionService.ts
  src/client/common/process/logger.ts
Labels: external contributor, skip news

#7621 Add missing command entry into package.json
  package.json
Labels: skip news

#7625 Add more logging for kernelspec listing
  src/client/datascience/jupyter/jupyterExecution.ts
Labels: skip news

#7626 Fix debugger to not use on disk ptvsd while it doesn't work.
  news/2 Fixes/7627.md
  package-lock.json
  src/client/datascience/jupyter/jupyterDebugger.ts
Labels: skip news

#7635 Add switch channel commands into activationEvents
  news/2 Fixes/7636.md
  package.json
Labels: external contributor

#7534 Attempt to use uri of active text editor document to determine virtual env to use with terminal
  news/2 Fixes/6282.md
  src/client/terminals/activation.ts
  src/test/common/terminals/activation.unit.test.ts
Labels: external contributor

#7648 Update ptvsd version to 5.0.0a5
  requirements.txt
Labels: skip news

#7654 Fixes to CSS selectors of test explorer
  uitests/src/selectors.ts
  uitests/src/vscode/testExplorer.ts
Labels: skip news

#7656 Miscellaneous API and fixes related to uitests
  uitests/src/selectors.ts
  uitests/src/steps/documents.ts
  uitests/src/steps/statusbar.ts
  uitests/src/steps/testing.ts
  uitests/src/types.ts
  uitests/src/vscode/statusbar.ts
  uitests/src/vscode/testExplorer.ts
Labels: skip news

#7655 UI tests for tests explorer in Extension with ptvsd, pytest and flask repos
  build/ci/vscode-python-nightly-uitest.yaml
  uitests/features/testing/externalRepos.feature
  uitests/src/helpers/python.ts
  uitests/src/steps/documents.ts
  uitests/src/steps/interpreter.ts
Labels: skip news

#7661 Ability to hide status bar and Git status bar item
  uitests/src/setup/setup.ts
  uitests/src/steps/main.ts
  uitests/src/steps/statusbar.ts
  uitests/src/types.ts
  uitests/src/vscode/statusbar.ts
Labels: skip news

#7659 Fixes to UI Tests related to LS
  uitests/bootstrap/extension/extension.js
  uitests/features/languageServer/README.md
  uitests/features/languageServer/basic.feature
  uitests/features/languageServer/goToDefinition.feature
  uitests/features/languageServer/intellisense.feature
  uitests/src/steps/statusbar.ts
  uitests/src/types.ts
  uitests/src/vscode/application.ts
  uitests/src/vscode/panels.ts
  uitests/src/vscode/quickOpen.ts
Labels: skip news

#7662 Fixes to 'unresolved import' tests in UI Tests
  uitests/features/languageServer/unresolvedImport.feature
  uitests/src/selectors.ts
  uitests/src/steps/problems.ts
Labels: skip news

#7669 Fixes to test explorer UI Tests
  build/ci/templates/jobs/uitest.yml
  uitests/README.md
  uitests/features/README.md
  uitests/features/interpreter/basic.feature
  uitests/features/languageServer/basic.feature
  uitests/src/steps/testing.ts
Labels: skip news

#7670 Capture vscode logs with failed tests results
  uitests/src/setup/setup.ts
  uitests/src/steps/main.ts
Labels: skip news

#7683 Increase ui test timeout from 90m to 120m
  build/ci/templates/jobs/merge_upload_uitest_report.yml
  build/ci/templates/jobs/uitest.yml
Labels: skip news

#7673 Skip node_modules files when debugging extension
  .vscode/launch.json
Labels: skip news

#7676 Rename test data item types in package.json
  package.json
Labels: external contributor, skip news

#7643 Decreasing experiment numbers for debug adapter and wheels
  experiments.json
Labels: skip news
