Repository microsoft/vscode-python, pull requests merged in 2019-04, with the labels that each got.

#5021 Merge march release into master
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
  news/1 Enhancements/4448.md
  news/1 Enhancements/4796.md
  news/1 Enhancements/4855.md
  news/1 Enhancements/4960.md
  news/2 Fixes/4687.md
  news/2 Fixes/4791.md
  news/2 Fixes/4853.md
  news/2 Fixes/4868.md
  news/2 Fixes/4876.md
  news/3 Code Health/4801.md
  package.json
  requirements.txt
  src/client/common/utils/localize.ts
  src/client/datascience/constants.ts
  src/client/datascience/history/historyProvider.ts
  src/client/debugger/debugAdapter/main.ts
  tpn/distribution.toml
  tpn/tpn/npm.py
Labels: skip news

#5003 Fix tests for analysis options in Language Server
  gulpfile.js
  src/test/activation/languageServer/analysisOptions.unit.test.ts
Labels: skip news

#5051 Ensure debounce decorator for async methods returns a promise
  src/client/activation/languageServer/analysisOptions.ts
  src/client/activation/languageServer/manager.ts
  src/client/common/configSettings.ts
  src/client/common/utils/decorators.ts
  src/test/common/utils/decorators.unit.test.ts
Labels: skip news

#5056 March 2019 point release with debugger fixes
  CHANGELOG.md
  package-lock.json
  package.json
  requirements.txt
  src/client/activation/languageServer/analysisOptions.ts
  src/client/common/installer/moduleInstaller.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
Labels: skip news

#5118 Merge release branch into master
  CHANGELOG.md
  requirements.txt
  src/client/activation/languageServer/analysisOptions.ts
  src/client/common/installer/moduleInstaller.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
Labels: skip news

#5108 Fix testing-related user-facing messages.
  package.nls.json
  src/client/common/utils/localize.ts
  src/client/unittests/common/services/unitTestDiagnosticService.ts
  src/client/unittests/display/main.ts
  src/test/unittests/display/main.unit.test.ts
  src/test/unittests/unittest/unittest.diagnosticService.unit.test.ts
Labels: skip news

#5160 Point release with fixes for Debugger
  CHANGELOG.md
  package.json
  requirements.txt
Labels: skip news

#5164 Track telemetry when switching to and from LS
  CHANGELOG.md
  src/client/activation/activationService.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/test/activation/activationService.unit.test.ts
Labels: skip news

#5167 Merge release into master
  CHANGELOG.md
  package.json
  requirements.txt
  src/client/activation/activationService.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/test/activation/activationService.unit.test.ts
Labels: skip news

#5168 Fix localized label IDs.
  package.nls.nl.json
Labels: skip news

#5166 Use namespace commands for refactor keys
  news/3 Code Health/5204.md
  src/client/common/constants.ts
  src/client/providers/simpleRefactorProvider.ts
Labels: skip news

#5215 Add tests
  src/test/application/diagnostics/commands/execVSCCommands.unit.test.ts
  src/test/common/installer/condaInstaller.unit.test.ts
Labels: skip news

#5217 Fix issues related to renaming of commands
  package.json
  src/client/common/application/commands.ts
  src/client/unittests/main.ts
Labels: skip news

#5265 Disable failing tests on CI
  src/test/application/diagnostics/checks/invalidDebuggerType.unit.test.ts
Labels: skip news

#5288 Fixes to python tests
  src/test/testing/pytest/pytest.run.test.ts
  src/test/testing/pytest/pytest.testMessageService.test.ts
Labels: skip news

#5297 Update README to include new features
  README.md
  images/ConfigureDebugger.gif
  images/ConfigureTests.gif
  images/InterpreterSelectionZoom.gif
Labels: skip news

#5245 Update naming of console type to be consistent with vscode
  news/3 Code Health/4321.md
  package.json
  package.nls.json
  src/client/application/diagnostics/checks/invalidLaunchJsonDebugger.ts
  src/client/application/diagnostics/constants.ts
  src/client/application/diagnostics/serviceRegistry.ts
  src/client/common/utils/localize.ts
  src/client/debugger/debugAdapter/DebugClients/helper.ts
  src/client/debugger/extension/configuration/resolvers/launch.ts
  src/client/debugger/types.ts
  src/client/extension.ts
  src/client/linters/linterCommands.ts
  src/client/telemetry/types.ts
  src/client/testing/common/debugLauncher.ts
  src/test/application/diagnostics/checks/invalidLaunchJsonDebugger.unit.test.ts
  src/test/debugger/envVars.test.ts
  src/test/testing/common/debugLauncher.unit.test.ts
Labels: external contributor

#5306 Fix functional test order for 3.5 and earlier.
  pythonFiles/tests/testing_tools/adapter/test_functional.py
Labels: skip news

#5307 specify full https path to README images
  README.md
Labels: skip news

#5308 Use fully qualified paths to nodejs on CI for tests
  build/ci/templates/test_phases.yml
  src/test/debugger/misc.test.ts
  src/test/debugger/portAndHost.test.ts
  src/test/debugger/utils.ts
Labels: skip news

#5309 Fix failing test on CI
  build/ci/templates/test_phases.yml
  src/test/application/diagnostics/checks/invalidLaunchJsonDebugger.unit.test.ts
Labels: skip news

#5328 Return an empty result from the pytest adapter if no tests found.
  pythonFiles/testing_tools/adapter/pytest.py
  pythonFiles/tests/testing_tools/adapter/.data/notests/tests/__init__.py
  pythonFiles/tests/testing_tools/adapter/test_functional.py
  pythonFiles/tests/testing_tools/adapter/test_pytest.py
Labels: skip news

#5329 Ensure tests in root directory are displayed
  src/client/testing/common/services/discoveredTestParser.ts
  src/client/testing/explorer/testTreeViewProvider.ts
  src/test/testing/explorer/explorerTestData.ts
  src/test/testing/explorer/testTreeViewProvider.unit.test.ts
  src/test/testing/pytest/pytest.testMessageService.test.ts
Labels: skip news

#5338 Update pinned version of Language Server 0.2.59
  package.json
Labels: feature-intellisense, needs PR, skip news, type-enhancement

#5335 Prompt to turn on Pylint if a pylintrc file is found
  package.nls.json
  src/client/common/utils/localize.ts
  src/client/linters/linterAvailability.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/test/linters/lint.provider.test.ts
  src/test/linters/linter.availability.unit.test.ts
Labels: skip news

#5361 update functional test for matplotlib
  src/test/datascience/variableexplorer.functional.test.tsx
Labels: data science, skip news

#5363 Update ptvsd to latest version
  requirements.txt
Labels: skip news

#5353 Fix up the debug config labels and messages.
  package.nls.de.json
  package.nls.es.json
  package.nls.fr.json
  package.nls.it.json
  package.nls.ja.json
  package.nls.json
  package.nls.ko-kr.json
  package.nls.nl.json
  package.nls.pt-br.json
  package.nls.ru.json
  package.nls.zh-cn.json
  package.nls.zh-tw.json
  src/client/common/application/webPanel.ts
  src/client/common/utils/localize.ts
  src/client/debugger/extension/configuration/debugConfigurationService.ts
  src/client/debugger/extension/configuration/launch.json/completionProvider.ts
  src/client/debugger/extension/configuration/providers/djangoLaunch.ts
  src/client/debugger/extension/configuration/providers/fileLaunch.ts
  src/client/debugger/extension/configuration/providers/flaskLaunch.ts
  src/client/debugger/extension/configuration/providers/moduleLaunch.ts
  src/client/debugger/extension/configuration/providers/pyramidLaunch.ts
  src/client/debugger/extension/configuration/providers/remoteAttach.ts
  src/test/common/localize.unit.test.ts
  src/test/common/utils/localize.functional.test.ts
  src/test/debugger/extension/configuration/launch.json/completionProvider.unit.test.ts
  src/test/debugger/extension/configuration/providers/djangoLaunch.unit.test.ts
  src/test/debugger/extension/configuration/providers/fileLaunch.unit.test.ts
  src/test/debugger/extension/configuration/providers/flaskLaunch.unit.test.ts
  src/test/debugger/extension/configuration/providers/moduleLaunch.unit.test.ts
  src/test/debugger/extension/configuration/providers/pyramidLaunch.unit.test.ts
  src/test/debugger/extension/configuration/providers/remoteAttach.unit.test.ts
Labels: skip news

#5322 Fixed a typo
  package.json
Labels: skip news

#5369 Ensure pylint is available if "pylintrc" file is present
  src/client/linters/constants.ts
  src/client/linters/linterAvailability.ts
  src/test/linters/linter.availability.unit.test.ts
Labels: skip news

#5383 Fixes to the test explorer in displaying root
  src/client/testing/explorer/testTreeViewProvider.ts
  src/test/testing/explorer/explorerTestData.ts
  src/test/testing/explorer/testTreeViewProvider.unit.test.ts
Labels: skip news

#5409 Fix the flask app name prompt for launch config.
  package.nls.json
  src/client/common/utils/localize.ts
  src/client/debugger/extension/configuration/providers/flaskLaunch.ts
Labels: skip news

#5412 Upload vsix to artifacts
  build/ci/templates/build.yml
  build/ci/templates/uitest_phases.yml
  build/ci/vscode-python-ci.yaml
  gulpfile.js
  package.json
  src/test/datascience/dataviewer.functional.test.tsx
Labels: skip news

#5436 Fixes to creation of json for Language Server
  src/client/activation/languageServer/activator.ts
  src/test/activation/languageServer/activator.unit.test.ts
Labels: skip news

#5481 Merge release into master
  CHANGELOG.md
  package.json
  src/client/activation/languageServer/activator.ts
  src/test/activation/languageServer/activator.unit.test.ts
Labels: skip news

#5510 make set test less restrictive
  src/test/datascience/variableexplorer.functional.test.tsx
Labels: skip news

#5517 Revert discovery of pytest by scraping the output
  CHANGELOG.md
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/client/testing/common/services/discovery.ts
  src/client/testing/common/testUtils.ts
  src/client/testing/pytest/services/discoveryService.ts
  src/client/testing/pytest/services/parserService.ts
  src/client/testing/serviceRegistry.ts
  src/test/pythonFiles/testFiles/pytestFiles/results/five.output
  src/test/pythonFiles/testFiles/pytestFiles/results/four.output
  src/test/pythonFiles/testFiles/pytestFiles/results/one.output
  src/test/pythonFiles/testFiles/pytestFiles/results/three.output
  src/test/pythonFiles/testFiles/pytestFiles/results/two.output
  src/test/testing/common/services/discovery.unit.test.ts
  src/test/testing/common/testUtils.unit.test.ts
  src/test/testing/pytest/pytest.discovery.test.ts
  src/test/testing/pytest/pytest.run.test.ts
  src/test/testing/pytest/pytest.test.ts
  src/test/testing/pytest/pytest.testMessageService.test.ts
  src/test/testing/pytest/pytest_run_tests_data.ts
  src/test/testing/pytest/services/discoveryService.unit.test.ts
  src/test/testing/serviceRegistry.ts
  src/test/unittests/pytest/pytest.discovery.unit.test.ts
  src/test/unittests/pytest/pytest.testparser.unit.test.ts
Labels: skip news
