Repository microsoft/vscode-python, pull requests merged in 2020-05, with the labels that each got.

#11527 Second refactor for non-jupyter kernel search
  src/client/datascience/jupyter/jupyterExecution.ts
  src/client/datascience/jupyter/kernels/kernelSelector.ts
  src/client/datascience/jupyter/liveshare/hostJupyterServer.ts
  src/client/datascience/raw-kernel/liveshare/hostRawNotebookProvider.ts
  src/client/datascience/raw-kernel/rawNotebookProviderWrapper.ts
  src/test/datascience/execution.unit.test.ts
  src/test/datascience/jupyter/kernels/kernelSelector.unit.test.ts
Labels: skip news

#11517 Fix smoke tests & correctly running tests using Python 2.7
  .github/workflows/ci.yml
  src/client/common/configSettings.ts
Labels: skip news

#11561 End tests reliably on Github actions
  .github/workflows/ci.yml
Labels: skip news

#11118 Add status bar item with icon during installs
  news/1 Enhancements/10495.md
  src/client/common/installer/extensionBuildInstaller.ts
  src/test/common/installer/extensionBuildInstaller.unit.test.ts
Labels: external contributor

#11544 Fix multiroot flaky CI tests
  src/test/initialize.ts
  src/test/multiRootTest.ts
Labels: skip news

#11546 Skip venv tests for 2.7 and disable fail fast
  .github/workflows/ci.yml
  src/test/common/terminals/environmentActivationProviders/terminalActivation.testvirtualenvs.ts
Labels: skip news

#11573 Fix failing debugger tests on GHA
  .github/workflows/ci.yml
Labels: skip news

#11538 Non-jupyter kernel finder
  src/client/datascience/jupyter/kernels/kernelSelections.ts
  src/client/datascience/kernel-launcher/kernelFinder.ts
  src/client/datascience/kernel-launcher/types.ts
  src/test/datascience/kernelFinder.unit.test.ts
Labels: skip news

#11572 Fix slashes in telemetry unit tests
  src/test/telemetry/index.unit.test.ts
  src/test/testing/helper.ts
Labels: skip news

#11591 Use a timeout when checking if proc is dead in proc.poll
  pythonFiles/vscode_datascience_helpers/kernel_launcher_daemon.py
Labels: skip news

#11592 fix kernel finder tests
  src/test/datascience/kernelFinder.unit.test.ts
Labels: skip news

#11586 Bump up version of setup-python action
  .github/workflows/ci.yml
Labels: skip news

#11598 Wait for kernel to die instead of polling it
  pythonFiles/vscode_datascience_helpers/kernel_launcher_daemon.py
Labels: skip news

#11599 Preparing RC : updated version, TPN and change logs
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
  news/1 Enhancements/10495.md
  news/1 Enhancements/10818.md
  news/1 Enhancements/10885.md
  news/1 Enhancements/10988.md
  news/1 Enhancements/11052.md
  news/1 Enhancements/11083.md
  news/1 Enhancements/11108.md
  news/1 Enhancements/11236.md
  news/1 Enhancements/11294.md
  news/1 Enhancements/11327.md
  news/1 Enhancements/11446.md
  news/1 Enhancements/216.md
  news/2 Fixes/10006.md
  news/2 Fixes/10356.md
  news/2 Fixes/10370.md
  news/2 Fixes/10521.md
  news/2 Fixes/10552.md
  news/2 Fixes/10587.md
  news/2 Fixes/10708.md
  news/2 Fixes/10785.md
  news/2 Fixes/10825.md
  news/2 Fixes/10884.md
  news/2 Fixes/10942.md
  news/2 Fixes/11065.md
  news/2 Fixes/11127.md
  news/2 Fixes/11153.md
  news/2 Fixes/11291.md
  news/2 Fixes/11306.md
  news/2 Fixes/11399.md
  news/2 Fixes/11451.md
  news/2 Fixes/11469.md
  news/2 Fixes/11530.md
  news/2 Fixes/11576.md
  news/2 Fixes/11579.md
  news/2 Fixes/9801.md
  news/3 Code Health/10447.md
  news/3 Code Health/10809.md
  news/3 Code Health/11128.md
  news/3 Code Health/11221.md
  news/3 Code Health/11297.md
  news/3 Code Health/11436.md
  news/3 Code Health/11470.md
  news/3 Code Health/11542.md
  package-lock.json
  package.json
Labels: skip news

#11601 Update master version
  package-lock.json
  package.json
Labels: skip news

#11588 Don't use cached requirements installation when running the tests on GHA
  .github/workflows/ci.yml
Labels: skip news

#11161 Logging cleanup: move and split files.
  src/client/common/logger.ts
  src/client/common/types.ts
  src/client/logging/_console.ts
  src/client/logging/_trace.ts
  src/client/logging/formatters.ts
  src/client/logging/index.ts
  src/client/logging/logger.ts
  src/client/logging/transports.ts
  src/client/logging/types.ts
  src/client/logging/util.ts
Labels: skip news

#11602 Revert vscode-extension-telemetry changes for the release
  CHANGELOG.md
  gulpfile.js
  package-lock.json
  package.json
  src/client/telemetry/index.ts
  src/client/telemetry/vscode-extension-telemetry.d.ts
  src/test/telemetry/index.unit.test.ts
  src/test/testing/helper.ts
Labels: skip news

#11635 Skip flaky testing framework discovery against actual python process test
  src/test/testing/unittest/unittest.test.ts
Labels: skip news

#11656 Revert vscode-extension-telemetry changes for the release (#11602)
  CHANGELOG.md
  gulpfile.js
  package-lock.json
  package.json
  src/client/telemetry/index.ts
  src/client/telemetry/vscode-extension-telemetry.d.ts
  src/test/telemetry/index.unit.test.ts
  src/test/testing/helper.ts
Labels: skip news

#11673 Port storage fix to release branch
  CHANGELOG.md
  src/client/datascience/interactive-ipynb/nativeEditorOldWebView.ts
  src/client/datascience/interactive-ipynb/nativeEditorStorage.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/interactive-ipynb/nativeEditorStorage.unit.test.ts
  src/test/datascience/nativeEditor.functional.test.tsx
Labels: skip news

#11664 Show the prompt again if user clicks on more info
  package.nls.json
  src/client/application/diagnostics/checks/pythonPathDeprecated.ts
  src/client/common/utils/localize.ts
  src/test/application/diagnostics/checks/pythonPathDeprecated.unit.test.ts
Labels: skip news

#11606 Logging cleanup.
  src/client/common/logger.ts
  src/client/common/utils/async.ts
  src/client/common/utils/decorators.ts
  src/client/common/utils/misc.ts
  src/client/logging/_console.ts
  src/client/logging/_global.ts
  src/client/logging/_trace.ts
  src/client/logging/formatters.ts
  src/client/logging/index.ts
  src/client/logging/levels.ts
  src/client/logging/logger.ts
  src/client/logging/trace.ts
  src/client/logging/transports.ts
  src/client/logging/types.ts
  src/client/logging/util.ts
Labels: skip news

#11688 Port scrolling fix to release
  CHANGELOG.md
  package.json
  src/client/common/types.ts
  src/datascience-ui/history-react/interactivePanel.tsx
  src/datascience-ui/interactive-common/contentPanel.tsx
Labels: skip news

#11654 Leave pipenv in a corner until the user decides to select an interpreter
  src/client/activation/activationManager.ts
  src/client/application/diagnostics/checks/macPythonInterpreter.ts
  src/client/common/terminal/environmentActivationProviders/pipEnvActivationProvider.ts
  src/client/interpreter/autoSelection/rules/system.ts
  src/client/interpreter/configuration/interpreterSelector/interpreterSelector.ts
  src/client/interpreter/contracts.ts
  src/client/interpreter/locators/index.ts
  src/client/interpreter/locators/services/cacheableLocatorService.ts
  src/client/interpreter/locators/services/pipEnvService.ts
  src/client/interpreter/serviceRegistry.ts
  src/client/interpreter/virtualEnvs/index.ts
  src/client/startupTelemetry.ts
  src/test/activation/activationManager.unit.test.ts
  src/test/application/diagnostics/checks/macPythonInterpreter.unit.test.ts
  src/test/configuration/interpreterSelector/interpreterSelector.unit.test.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/interpreters/autoSelection/rules/currentPath.unit.test.ts
  src/test/interpreters/autoSelection/rules/system.unit.test.ts
  src/test/interpreters/locators/index.unit.test.ts
  src/test/interpreters/pipEnvService.unit.test.ts
  src/test/interpreters/serviceRegistry.unit.test.ts
  src/test/interpreters/virtualEnvManager.unit.test.ts
  src/test/interpreters/virtualEnvs/index.unit.test.ts
  src/test/serviceRegistry.ts
Labels: skip news

#11696 Skip flaky testing framework discovery against actual python process test
  src/test/testing/unittest/unittest.test.ts
Labels: skip news

#11700 Cherry-pick pipenv changes and pythonpath prompt changes to release
  package.nls.json
  src/client/activation/activationManager.ts
  src/client/application/diagnostics/checks/macPythonInterpreter.ts
  src/client/application/diagnostics/checks/pythonPathDeprecated.ts
  src/client/common/terminal/environmentActivationProviders/pipEnvActivationProvider.ts
  src/client/common/utils/localize.ts
  src/client/interpreter/autoSelection/rules/system.ts
  src/client/interpreter/configuration/interpreterSelector/interpreterSelector.ts
  src/client/interpreter/contracts.ts
  src/client/interpreter/locators/index.ts
  src/client/interpreter/locators/services/cacheableLocatorService.ts
  src/client/interpreter/locators/services/pipEnvService.ts
  src/client/interpreter/serviceRegistry.ts
  src/client/interpreter/virtualEnvs/index.ts
  src/client/startupTelemetry.ts
  src/test/activation/activationManager.unit.test.ts
  src/test/application/diagnostics/checks/macPythonInterpreter.unit.test.ts
  src/test/application/diagnostics/checks/pythonPathDeprecated.unit.test.ts
  src/test/configuration/interpreterSelector/interpreterSelector.unit.test.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/interpreters/autoSelection/rules/currentPath.unit.test.ts
  src/test/interpreters/autoSelection/rules/system.unit.test.ts
  src/test/interpreters/locators/index.unit.test.ts
  src/test/interpreters/pipEnvService.unit.test.ts
  src/test/interpreters/serviceRegistry.unit.test.ts
  src/test/interpreters/virtualEnvManager.unit.test.ts
  src/test/interpreters/virtualEnvs/index.unit.test.ts
  src/test/serviceRegistry.ts
Labels: skip news

#11705 Disable 'run.test.ts' system tests
  src/test/debugger/run.test.ts
Labels: skip news

#11735 Skip debugger smoke test
  src/test/smoke/debugger.smoke.test.ts
Labels: skip news

#11714 Update run by line color
  src/datascience-ui/react-common/images/RunByLine/runbyline_dark.svg
  src/datascience-ui/react-common/images/RunByLine/runbyline_light.svg
Labels: skip news

#11732 Revert "Logging cleanup."
  src/client/common/logger.ts
  src/client/common/utils/async.ts
  src/client/common/utils/decorators.ts
  src/client/common/utils/misc.ts
  src/client/logging/_console.ts
  src/client/logging/_global.ts
  src/client/logging/_trace.ts
  src/client/logging/formatters.ts
  src/client/logging/index.ts
  src/client/logging/levels.ts
  src/client/logging/logger.ts
  src/client/logging/trace.ts
  src/client/logging/transports.ts
  src/client/logging/types.ts
  src/client/logging/util.ts
Labels: skip news

#11717 Streamline DS Dependency installs
  package.nls.json
  src/client/common/installer/productInstaller.ts
  src/client/common/utils/localize.ts
  src/client/datascience/jupyter/kernels/kernelDependencyService.ts
  src/test/common/installer.test.ts
  src/test/common/installer/installer.unit.test.ts
  src/test/datascience/jupyter/kernels/kernelDependencyService.unit.test.ts
Labels: skip news

#11730 Update extension version
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip news

#11702 Notify cell subscriber only when there are changes in the cell
  src/client/datascience/jupyter/jupyterNotebook.ts
Labels: skip news

#11757 Remove APIs related to ptvsd paths
  src/client/api.ts
  src/client/debugger/extension/adapter/remoteLaunchers.ts
  src/test/api.functional.test.ts
  src/test/debugger/extension/adapter/remoteLaunchers.unit.test.ts
Labels: skip news

#11755 Remove TS debugAdapter
  .vscode/launch.json
  build/existingFiles.json
  build/webpack/webpack.debugadapter.config.js
  gulpfile.js
  package.json
  src/client/datascience/jupyterDebugService.ts
  src/client/datascience/serviceRegistry.ts
  src/client/debugger/debugAdapter/Common/Contracts.ts
  src/client/debugger/debugAdapter/Common/debugStreamProvider.ts
  src/client/debugger/debugAdapter/Common/processServiceFactory.ts
  src/client/debugger/debugAdapter/Common/protocolLogger.ts
  src/client/debugger/debugAdapter/Common/protocolWriter.ts
  src/client/debugger/debugAdapter/DebugClients/DebugClient.ts
  src/client/debugger/debugAdapter/DebugClients/DebugFactory.ts
  src/client/debugger/debugAdapter/DebugClients/LocalDebugClient.ts
  src/client/debugger/debugAdapter/DebugClients/RemoteDebugClient.ts
  src/client/debugger/debugAdapter/DebugClients/launcherProvider.ts
  src/client/debugger/debugAdapter/DebugClients/localDebugClientV2.ts
  src/client/debugger/debugAdapter/DebugClients/nonDebugClientV2.ts
  src/client/debugger/debugAdapter/DebugServers/BaseDebugServer.ts
  src/client/debugger/debugAdapter/DebugServers/LocalDebugServerV2.ts
  src/client/debugger/debugAdapter/DebugServers/RemoteDebugServerv2.ts
  src/client/debugger/debugAdapter/main.ts
  src/client/debugger/debugAdapter/serviceRegistry.ts
  src/client/debugger/debugAdapter/types.ts
  src/client/debugger/extension/adapter/factory.ts
  src/client/debugger/extension/helpers/protocolParser.ts
  src/client/debugger/extension/types.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/debugger/capabilities.test.ts
  src/test/debugger/common/debugStreamProvider.test.ts
  src/test/debugger/common/protocolWriter.test.ts
  src/test/debugger/common/protocoloLogger.test.ts
  src/test/debugger/common/protocolparser.test.ts
  src/test/debugger/debugAdapter/debugClients/launcherProvider.unit.test.ts
  src/test/debugger/debugAdapter/serviceRegistry.unit.test.ts
  src/test/debugger/extension/adapter/factory.unit.test.ts
Labels: skip news

#11701 Update VSCode engine and notebook scheme
  package.json
  src/client/activation/common/analysisOptions.ts
  src/client/common/constants.ts
  src/test/activation/languageServer/analysisOptions.unit.test.ts
  tsconfig.json
Labels: skip news

#11764 Update change log with additional notes.
  CHANGELOG.md
Labels: skip news

#11766 Remove unused file
  data/get-pip.py
Labels: skip news

#11703 Split to INotebookModel and INotebookStorage
  src/client/datascience/interactive-common/interactiveWindowTypes.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/interactive-ipynb/nativeEditorOldWebView.ts
  src/client/datascience/interactive-ipynb/nativeEditorProvider.ts
  src/client/datascience/interactive-ipynb/nativeEditorProviderOld.ts
  src/client/datascience/interactive-ipynb/nativeEditorStorage.ts
  src/client/datascience/interactive-ipynb/notebookStorageProvider.ts
  src/client/datascience/serviceRegistry.ts
  src/client/datascience/types.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/interactive-ipynb/nativeEditorProvider.unit.test.ts
  src/test/datascience/interactive-ipynb/nativeEditorStorage.unit.test.ts
  src/test/datascience/jupyter/jupyterCellOutputMimeTypeTracker.unit.test.ts
  src/test/datascience/mockCustomEditorService.ts
  src/test/datascience/testNativeEditorProvider.ts
Labels: skip news

#11765 Remove tpn
  .github/release_plan.md
  .vscodeignore
  build/ci/templates/test_phases.yml
  tpn/README.md
  tpn/__main__.py
  tpn/distribution.toml
  tpn/requirements.in
  tpn/requirements.txt
  tpn/tpn/__init__.py
  tpn/tpn/__main__.py
  tpn/tpn/config.py
  tpn/tpn/data.py
  tpn/tpn/npm.py
  tpn/tpn/tests/__init__.py
  tpn/tpn/tests/test_config.py
  tpn/tpn/tests/test_npm.py
  tpn/tpn/tests/test_tpnfile.py
  tpn/tpn/tpnfile.py
Labels: skip news

#11720 Fix typo lanaguage -> language
  news/3 Code Health/11775.md
  src/test/smoke/common.ts
Labels: external contributor

#11708 Clarify that using a custom jedi also means a custom parso
  package.json
Labels: external contributor, skip news

#11802 Some fixes for nightly
  build/ci/conda_base.yml
  build/ci/conda_env_1.yml
  build/ci/conda_env_2.yml
  build/ci/templates/test_phases.yml
  build/conda-functional-requirements.txt
  src/client/common/platform/fileSystem.ts
  src/client/common/platform/fs-temp.ts
  src/client/common/platform/types.ts
  src/client/datascience/baseJupyterSession.ts
  src/client/datascience/interactive-common/interactiveBase.ts
  src/client/datascience/interactive-common/notebookProvider.ts
  src/client/datascience/interactive-window/interactiveWindow.ts
  src/client/datascience/jupyter/debuggerVariables.ts
  src/client/datascience/jupyter/jupyterNotebookProvider.ts
  src/client/datascience/jupyterDebugService.ts
  src/client/datascience/kernel-launcher/kernelProcess.ts
  src/client/datascience/types.ts
  src/test/common/platform/fs-temp.unit.test.ts
  src/test/common/platform/utils.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/interactiveWindow.functional.test.tsx
  src/test/datascience/kernelLauncher.functional.test.ts
  src/test/datascience/notebook.functional.test.ts
Labels: skip news

#11769 Remove DebugAdapterNewPtvsd and DebugAdapterDescriptorFactory experiment.
  experiments.json
  package.json
  package.nls.json
  package.nls.zh-tw.json
  src/client/common/experimentGroups.ts
  src/client/common/utils/localize.ts
  src/client/datascience/jupyter/jupyterDebugger.ts
  src/client/debugger/extension/adapter/outdatedDebuggerPrompt.ts
  src/client/debugger/extension/configuration/resolvers/attach.ts
  src/client/debugger/extension/configuration/resolvers/launchConfigExperiment.ts
  src/test/debugger/attach.ptvsd.test.ts
  src/test/debugger/extension/adapter/outdatedDebuggerPrompt.unit.test.ts
  src/test/debugger/extension/configuration/resolvers/attach.unit.test.ts
  src/test/debugger/extension/configuration/resolvers/launchConfigExperiments.unit.test.ts
  src/test/debugger/run.test.ts
Labels: skip news

#11820 turn on raw kernel for insiders
  src/client/datascience/constants.ts
  src/client/datascience/raw-kernel/rawNotebookProvider.ts
  src/client/telemetry/index.ts
Labels: skip news

#11835 Fix memleaks during tests
  build/conda-functional-requirements.txt
  package-lock.json
  package.json
  src/client/datascience/jupyter/jupyterConnection.ts
  src/datascience-ui/interactive-common/redux/reducers/monaco.ts
  src/datascience-ui/interactive-common/redux/reducers/transfer.ts
  src/datascience-ui/interactive-common/tokenizer.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/dataviewer.functional.test.tsx
  src/test/datascience/debugger.functional.test.tsx
  src/test/datascience/helpers.ts
  src/test/datascience/intellisense.functional.test.tsx
  src/test/datascience/interactiveWindow.functional.test.tsx
  src/test/datascience/kernelLauncher.functional.test.ts
  src/test/datascience/nativeEditor.functional.test.tsx
  src/test/datascience/notebook.functional.test.ts
  src/test/datascience/variableexplorer.functional.test.tsx
  src/test/unittests.ts
Labels: skip news

#11841 Prelimnary support to load ipyn files in native Notebook editor
  build/ci/templates/steps/compile.yml
  experiments.json
  gulpfile.js
  package.json
  src/client/common/constants.ts
  src/client/common/experimentGroups.ts
  src/client/datascience/notebook/contentProvider.ts
  src/client/datascience/notebook/helpers.ts
  src/client/datascience/notebook/integration.ts
  src/client/datascience/notebook/serviceRegistry.ts
  src/client/datascience/serviceRegistry.ts
  src/datascience-ui/common/cellFactory.ts
  src/test/activation/languageServer/analysisOptions.unit.test.ts
  tsconfig.extension.json
  tsconfig.json
  types/vscode.proposed.d.ts
Labels: skip news

#11846 Add cell execution to the new VSC Notebooks
  gulpfile.js
  src/client/common/utils/misc.ts
  src/client/datascience/notebook/executionHelpers.ts
  src/client/datascience/notebook/helpers.ts
  src/client/datascience/notebook/integration.ts
  src/client/datascience/notebook/notebookKernel.ts
  src/client/datascience/notebook/serviceRegistry.ts
Labels: skip news

#11848 Debug and variable test failures on nightly
  .github/workflows/ci.yml
  build/ci/templates/test_phases.yml
  src/client/datascience/jupyter/debuggerVariables.ts
  src/client/datascience/jupyterDebugService.ts
  src/datascience-ui/interactive-common/redux/reducers/variables.ts
  src/datascience-ui/interactive-common/redux/store.ts
  src/test/datascience/debugger.functional.test.tsx
  src/test/datascience/variableTestHelpers.ts
  src/test/datascience/variableexplorer.functional.test.tsx
Labels: skip news

#11849 Sync VSCode output Cell Output & add INotebookEditor/INotebookEditorProvider
  src/client/datascience/notebook/executionHelpers.ts
  src/client/datascience/notebook/notebookEditor.ts
  src/client/datascience/notebook/notebookEditorProvider.ts
  src/client/datascience/notebook/serviceRegistry.ts
  src/client/ioc/serviceManager.ts
  src/client/ioc/types.ts
Labels: skip news

#11876 Handling `Save as` of notebooks when using new VSC Notebook API
  src/client/datascience/interactive-common/interactiveWindowTypes.ts
  src/client/datascience/interactive-common/notebookProvider.ts
  src/client/datascience/interactive-ipynb/nativeEditorProvider.ts
  src/client/datascience/interactive-ipynb/nativeEditorStorage.ts
  src/client/datascience/interactive-ipynb/notebookStorageProvider.ts
  src/client/datascience/notebook/executionHelpers.ts
  src/client/datascience/notebook/notebookEditorProvider.ts
  src/client/datascience/notebook/serviceRegistry.ts
  src/client/datascience/types.ts
  src/test/datascience/interactive-common/notebookProvider.unit.test.ts
  src/test/datascience/interactive-ipynb/nativeEditorProvider.unit.test.ts
Labels: skip news

#11871 Fixes bugs #11777 and #11726, 'outputPrepend' needed to be cleared on each cell execute.
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/jupyter/jupyterNotebook.ts
  src/datascience-ui/interactive-common/kernelSelection.tsx
Labels: external contributor, skip news

#11881 Get more nightly tests to pass
  build/conda-functional-requirements.txt
  src/client/datascience/common.ts
  src/client/datascience/jupyter/jupyterDebugger.ts
  src/test/common/platform/filesystem.functional.test.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/mockCommandManager.ts
  src/test/datascience/testexecutionLogger.ts
Labels: skip news

#11878 Cherry picks and version updates for bug fix release
  CHANGELOG.md
  package-lock.json
  package.json
  src/client/interpreter/configuration/interpreterSelector/commands/setShebangInterpreter.ts
  src/client/interpreter/contracts.ts
  src/client/interpreter/display/shebangCodeLensProvider.ts
  src/test/providers/shebangCodeLenseProvider.unit.test.ts
Labels: skip news

#11882 Place VS Code API behind an interface, add tests
  build/ci/templates/globals.yml
  src/client/common/application/notebook.ts
  src/client/common/application/types.ts
  src/client/common/serviceRegistry.ts
  src/client/datascience/notebook/cellUpdateHelpers.ts
  src/client/datascience/notebook/executionHelpers.ts
  src/client/datascience/notebook/helpers.ts
  src/client/datascience/notebook/integration.ts
  src/client/datascience/notebook/notebookEditor.ts
  src/client/datascience/notebook/notebookEditorProvider.ts
  src/client/datascience/notebook/notebookKernel.ts
  src/client/datascience/notebook/serviceRegistry.ts
  src/test/datascience/notebook/contentProvider.unit.test.ts
  src/test/datascience/notebook/helpers.unit.test.ts
  src/test/mocks/vsc/extHostedTypes.ts
  src/test/vscode-mock.ts
Labels: skip news

#11810 Ensure uses of isolate script in combination with sendCommand is correctly quoted
  src/client/common/installer/moduleInstaller.ts
  src/client/common/process/internal/python.ts
  src/client/common/terminal/helper.ts
  src/client/interpreter/locators/services/currentPathService.ts
  src/test/common/installer/moduleInstaller.unit.test.ts
  src/test/common/moduleInstaller.test.ts
  src/test/common/terminals/helper.unit.test.ts
Labels: skip news

#11844 Replace machine ID from survey with session ID
  src/client/activation/extensionSurvey.ts
  src/test/activation/extensionSurvey.unit.test.ts
Labels: skip news

#11895 Merge from release back to master
  CHANGELOG.md
  news/2 Fixes/11554.md
  news/2 Fixes/11557.md
  news/2 Fixes/11687.md
Labels: skip news

#11900 Ensure our notebook cmds work with VSC Notebooks
  package.json
  src/client/common/application/notebook.ts
  src/client/common/application/types.ts
  src/client/common/experiments.ts
  src/client/datascience/context/activeEditorContext.ts
  src/client/datascience/editor-integration/codelensprovider.ts
  src/client/datascience/editor-integration/decorator.ts
  src/client/datascience/notebook/integration.ts
  src/client/datascience/notebook/notebookEditorProvider.ts
  src/client/datascience/serviceRegistry.ts
  src/client/extensionActivation.ts
  src/test/common/experiments.unit.test.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/editor-integration/codelensprovider.unit.test.ts
  src/test/datascience/editor-integration/codewatcher.unit.test.ts
Labels: skip news

#11910 Hook up commands to notebook API and add tests
  .vscode/launch.json
  build/ci/templates/test_phases.yml
  build/ci/vscode-python-pr-validation.yaml
  package.json
  src/client/common/application/commands.ts
  src/client/common/application/notebook.ts
  src/client/common/application/types.ts
  src/client/common/experiments.ts
  src/client/common/types.ts
  src/client/datascience/context/activeEditorContext.ts
  src/client/datascience/interactive-ipynb/nativeEditorProvider.ts
  src/client/datascience/notebook/executionService.ts
  src/client/datascience/notebook/notebookEditor.ts
  src/client/datascience/notebook/notebookEditorProvider.ts
  src/client/datascience/notebook/notebookKernel.ts
  src/client/datascience/notebook/serviceRegistry.ts
  src/client/datascience/notebook/types.ts
  src/test/.vscode/settings.json
  src/test/datascience/editor-integration/codelensprovider.unit.test.ts
  src/test/datascience/notebook/executionService.ds.test.ts
  src/test/datascience/notebook/notebookEditorProvider.ds.test.ts
  src/test/index.ts
  src/test/standardTest.ts
  types/vscode.proposed.d.ts
Labels: skip news

#11923 Build machine raw kernel functional test fix
  src/test/datascience/raw-kernel/rawKernel.functional.test.ts
Labels: skip news

#11928 Handle execution errors, remove autosave for VSC Notebook
  src/client/common/application/commands.ts
  src/client/datascience/context/activeEditorContext.ts
  src/client/datascience/notebook/executionService.ts
  src/client/datascience/notebook/notebookEditor.ts
  src/client/datascience/serviceRegistry.ts
  src/test/datascience/notebook/executionService.ds.test.ts
  src/test/datascience/notebook/notebookEditorProvider.ds.test.ts
  src/test/initialize.ts
Labels: skip news

#11941 More ipywidget nightly flake failures
  src/test/common/platform/filesystem.functional.test.ts
  src/test/datascience/uiTests/notebookHelpers.ts
  src/test/datascience/uiTests/notebookUi.ts
Labels: skip news

#11946 Skip incoming message processing if the ZMQ socket was closed
  src/client/datascience/raw-kernel/rawSocket.ts
Labels: skip news

#11692 Fix the instructions for how to run a specific system test suite
  CONTRIBUTING.md
Labels: external contributor, skip news

#9128 Ensure sorting imports in a modified file picks up the proper configuration
  news/2 Fixes/4891.md
  pythonFiles/sortImports.py
  src/client/providers/importSortProvider.ts
  src/test/format/extension.sort.test.ts
  src/test/providers/importSortProvider.unit.test.ts
Labels: external contributor

#11990 Ignore test failures in DataScience job
  build/ci/templates/test_phases.yml
Labels: skip news

#11994 Fix more nightly test failures
  src/client/common/process/baseDaemon.ts
  src/client/datascience/interactive-common/intellisense/intellisenseProvider.ts
  src/client/datascience/interactive-common/interactiveBase.ts
  src/client/datascience/interactive-common/interactiveWindowTypes.ts
  src/client/datascience/interactive-common/notebookProvider.ts
  src/client/datascience/interactive-common/synchronization.ts
  src/client/datascience/jupyter/jupyterNotebook.ts
  src/client/datascience/kernel-launcher/kernelDaemon.ts
  src/client/datascience/kernel-launcher/kernelProcess.ts
  src/datascience-ui/interactive-common/redux/store.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/intellisense.functional.test.tsx
  src/test/datascience/mockJupyterSession.ts
  src/test/datascience/uiTests/helpers.ts
  src/test/datascience/uiTests/ipywidget.ui.functional.test.ts
  src/test/datascience/uiTests/notebookHelpers.ts
Labels: skip news

#12005 Disable all stream tests
  src/test/common/platform/filesystem.functional.test.ts
Labels: skip news

#12003 More nightly fixes
  src/client/datascience/jupyter/jupyterExecution.ts
  src/client/datascience/jupyter/liveshare/roleBasedFactory.ts
  src/client/datascience/kernel-launcher/kernelProcess.ts
  src/test/datascience/notebook.functional.test.ts
Labels: skip news

#12013 Update DS issue templates
  .github/ISSUE_TEMPLATE/1_ds_bug_report.md
  .github/ISSUE_TEMPLATE/3_ds_feature_request.md
Labels: skip news

#12007 Update pinned node version
  build/ci/templates/globals.yml
Labels: skip news

#12016 Revert LS issue template changes
  .github/ISSUE_TEMPLATE/1_ds_bug_report.md
  .github/ISSUE_TEMPLATE/2_bug_report.md
Labels: skip news

#12008 Remove TS debug adapter subprocess support
  src/client/debugger/extension/hooks/childProcessAttachHandler.ts
  src/client/debugger/extension/hooks/childProcessAttachService.ts
  src/client/debugger/extension/hooks/constants.ts
  src/client/debugger/extension/hooks/types.ts
  src/test/debugger/extension/hooks/childProcessAttachHandler.unit.test.ts
  src/test/debugger/extension/hooks/childProcessAttachService.unit.test.ts
Labels: skip news

#11998 Remove ptvsd install
  .github/release_plan.md
  .github/test_plan.md
  .github/workflows/ci.yml
  .gitignore
  CONTRIBUTING.md
  build/ci/templates/steps/build.yml
  build/ci/templates/test_phases.yml
  gulpfile.js
  package.nls.json
  src/client/api.ts
  src/client/common/process/internal/scripts/index.ts
  src/client/common/utils/localize.ts
  src/client/datascience/jupyter/jupyterDebugger.ts
  src/client/datascience/jupyterDebugService.ts
  src/client/debugger/constants.ts
  src/client/debugger/extension/types.ts
  src/test/datascience/mockJupyterManager.ts
  src/test/debugger/attach.ptvsd.test.ts
  src/test/debugger/extension/adapter/factory.unit.test.ts
  src/test/debugger/misc.test.ts
  src/testMultiRootWkspc/workspace5/remoteDebugger-start-with-nowait.py
  src/testMultiRootWkspc/workspace5/remoteDebugger-start.py
  tpn/distribution.toml
Labels: skip news

#12019 Changed variable explorer grid column header order
  src/datascience-ui/interactive-common/variableExplorer.tsx
Labels: skip news

#12018 log exception in raw kernel session start
  src/client/datascience/raw-kernel/rawJupyterSession.ts
Labels: skip news

#12022 Disable cdn tests again
  src/test/datascience/ipywidgets/cdnWidgetScriptSourceProvider.unit.test.ts
Labels: skip news

#12002 Enable pythonPath deprecation experiment to 4% of users
  experiments.json
Labels: skip news

#12042 Fix pythonPath control group min and max values
  experiments.json
Labels: skip news

#12001 Scale down number of users seeing survey prompt
  experiments.json
Labels: skip news

#11999 Support Notebook Renderers with VS Code Notebooks (disabled)
  .vscode/launch.json
  build/webpack/webpack.datascience-ui-renderers.config.js
  build/webpack/webpack.datascience-ui.config.builder.js
  gulpfile.js
  src/client/datascience/notebook/helpers.ts
  src/client/datascience/notebook/integration.ts
  src/client/datascience/notebook/renderer.ts
  src/client/datascience/notebook/serviceRegistry.ts
  src/datascience-ui/interactive-common/transforms.tsx
  src/datascience-ui/renderers/index.tsx
  src/datascience-ui/renderers/main.ts
  src/datascience-ui/renderers/pvscDummy.ts
  src/datascience-ui/renderers/render.tsx
Labels: skip news
