Repository microsoft/vscode-python, pull requests merged in 2020-02, with the labels that each got.

#9872 Run tests against insiders
  src/datascience-ui/interactive-common/redux/store.ts
  src/test/multiRootTest.ts
  src/test/standardTest.ts
Labels: skip news

#9880 Update master version number.
  package-lock.json
  package.json
Labels: skip news

#9840 Ensure we have a base type for all action payloads
  src/client/datascience/data-viewing/types.ts
  src/client/datascience/interactive-common/interactiveWindowTypes.ts
  src/client/datascience/interactive-common/types.ts
  src/client/datascience/messages.ts
  src/datascience-ui/data-explorer/mainPanel.tsx
  src/datascience-ui/history-react/redux/actions.ts
  src/datascience-ui/history-react/redux/mapping.ts
  src/datascience-ui/history-react/redux/reducers/creation.ts
  src/datascience-ui/history-react/redux/reducers/effects.ts
  src/datascience-ui/history-react/redux/reducers/execution.ts
  src/datascience-ui/history-react/redux/reducers/index.ts
  src/datascience-ui/interactive-common/redux/postOffice.ts
  src/datascience-ui/interactive-common/redux/reducers/commonEffects.ts
  src/datascience-ui/interactive-common/redux/reducers/helpers.ts
  src/datascience-ui/interactive-common/redux/reducers/kernel.ts
  src/datascience-ui/interactive-common/redux/reducers/monaco.ts
  src/datascience-ui/interactive-common/redux/reducers/transfer.ts
  src/datascience-ui/interactive-common/redux/reducers/types.ts
  src/datascience-ui/interactive-common/redux/reducers/variables.ts
  src/datascience-ui/interactive-common/redux/store.ts
  src/datascience-ui/native-editor/redux/actions.ts
  src/datascience-ui/native-editor/redux/mapping.ts
  src/datascience-ui/native-editor/redux/reducers/creation.ts
  src/datascience-ui/native-editor/redux/reducers/effects.ts
  src/datascience-ui/native-editor/redux/reducers/execution.ts
  src/datascience-ui/native-editor/redux/reducers/index.ts
  src/datascience-ui/native-editor/redux/reducers/movement.ts
  src/datascience-ui/plot/mainPanel.tsx
  src/datascience-ui/react-common/postOffice.ts
  src/datascience-ui/react-common/reduxUtils.ts
Labels: skip news

#9882 Remove root level flags used to track cell selection and focus
  src/datascience-ui/history-react/redux/reducers/creation.ts
  src/datascience-ui/history-react/redux/reducers/execution.ts
  src/datascience-ui/interactive-common/mainState.ts
  src/datascience-ui/interactive-common/redux/reducers/transfer.ts
  src/datascience-ui/interactive-common/redux/store.ts
  src/datascience-ui/native-editor/nativeEditor.tsx
  src/datascience-ui/native-editor/redux/reducers/creation.ts
  src/datascience-ui/native-editor/redux/reducers/effects.ts
  src/datascience-ui/native-editor/redux/reducers/execution.ts
Labels: skip news

#9877 Speed up the before all hook for debugger tests
  src/test/testing/debugger.test.ts
Labels: skip news

#9895 Davidkutu/ds interactive window focus fix
  CHANGELOG.md
  src/datascience-ui/history-react/interactiveCell.tsx
  src/datascience-ui/history-react/interactivePanel.tsx
  src/datascience-ui/interactive-common/cellInput.tsx
  src/datascience-ui/interactive-common/code.tsx
  src/datascience-ui/native-editor/nativeCell.tsx
  src/datascience-ui/native-editor/nativeEditor.tsx
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/interactiveWindow.functional.test.tsx
  src/test/datascience/testHelpers.tsx
Labels: skip news

#9894 Disable webHostNotebook experiment and fix name of exp
  experiments.json
Labels: skip news

#9885 Fix focusing of cells when navigating cells using up/down arrow
  src/datascience-ui/native-editor/redux/reducers/effects.ts
  src/datascience-ui/native-editor/redux/reducers/execution.ts
Labels: skip news

#9897 Fix variables on mac and linux
  src/client/datascience/jupyter/jupyterVariables.ts
  src/datascience-ui/data-explorer/globalJQueryImports.ts
  src/datascience-ui/data-explorer/reactSlickGrid.tsx
Labels: skip news

#9896 Turn new debugger experiment to 50% of users and reload to 10% of users.
  experiments.json
Labels: skip news

#9903 Fix variables on mac and linux
  src/client/datascience/jupyter/jupyterVariables.ts
  src/datascience-ui/data-explorer/globalJQueryImports.ts
  src/datascience-ui/data-explorer/reactSlickGrid.tsx
Labels: skip news

#9843 Start running CI using a GitHub Action: build, compile, hygiene, check deps
  .github/workflows/ci.yml
  .prettierrc.js
Labels: skip news

#9908 Fix focusing of cells when navigating cells using up/down arrow (#9885)
  src/datascience-ui/native-editor/redux/reducers/effects.ts
  src/datascience-ui/native-editor/redux/reducers/execution.ts
Labels: skip news

#9907 Disable webHostNotebook experiment and fix name of exp (#9894)
  experiments.json
Labels: skip news

#9886 Synchronize contents in multiple editors for same nb file
  src/client/datascience/interactive-common/interactiveBase.ts
  src/client/datascience/interactive-common/interactiveWindowMessageListener.ts
  src/client/datascience/interactive-common/interactiveWindowTypes.ts
  src/client/datascience/interactive-common/synchronization.ts
  src/client/datascience/interactive-common/types.ts
  src/datascience-ui/history-react/interactiveCell.tsx
  src/datascience-ui/history-react/redux/actions.ts
  src/datascience-ui/history-react/redux/reducers/creation.ts
  src/datascience-ui/history-react/redux/reducers/effects.ts
  src/datascience-ui/history-react/redux/reducers/execution.ts
  src/datascience-ui/interactive-common/redux/helpers.ts
  src/datascience-ui/interactive-common/redux/postOffice.ts
  src/datascience-ui/interactive-common/redux/reducers/kernel.ts
  src/datascience-ui/interactive-common/redux/reducers/monaco.ts
  src/datascience-ui/interactive-common/redux/reducers/transfer.ts
  src/datascience-ui/interactive-common/redux/reducers/types.ts
  src/datascience-ui/interactive-common/redux/reducers/variables.ts
  src/datascience-ui/interactive-common/redux/store.ts
  src/datascience-ui/native-editor/redux/actions.ts
  src/datascience-ui/native-editor/redux/reducers/creation.ts
  src/datascience-ui/native-editor/redux/reducers/effects.ts
  src/datascience-ui/native-editor/redux/reducers/execution.ts
  src/datascience-ui/native-editor/redux/reducers/movement.ts
Labels: skip news

#9912 Davidkutu/ds scrapbook render fix
  CHANGELOG.md
  src/datascience-ui/interactive-common/cellOutput.tsx
  src/datascience-ui/interactive-common/transforms.tsx
Labels: skip news

#9919 Run tests against insiders
  src/test/common/insidersBuild/insidersExtensionService.unit.test.ts
  src/test/debuggerTest.ts
  src/test/multiRootTest.ts
  src/test/standardTest.ts
Labels: skip news

#9922 fail requirements install on stderr
  gulpfile.js
Labels: skip news

#9767 CONTRIBUTING: Clarify how to run vscode w/ extension dev build
  CONTRIBUTING.md
Labels: external contributor, skip news

#9905 Tests for navigation of cells using up/down arrow
  src/datascience-ui/react-common/monacoEditor.tsx
  src/test/datascience/nativeEditor.functional.test.tsx
Labels: skip news

#9937 Disable the terminal activation experiment
  experiments.json
Labels: skip news

#9936 Notebook should use kernel from metadata
  src/client/datascience/interactive-common/interactiveBase.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/jupyter/jupyterServer.ts
  src/client/datascience/jupyter/jupyterServerWrapper.ts
  src/client/datascience/jupyter/liveshare/hostJupyterServer.ts
  src/client/datascience/types.ts
Labels: skip news

#9932 Port server cache fix to release
  CHANGELOG.md
  src/client/datascience/jupyter/liveshare/serverCache.ts
Labels: skip news

#9938 Port variable restart fix
  CHANGELOG.md
  src/datascience-ui/interactive-common/redux/reducers/variables.ts
Labels: skip news

#9958 Do not override kernels info in other notebooks
  src/client/datascience/jupyter/liveshare/hostJupyterServer.ts
Labels: skip news

#9957 Update bug report template
  .github/ISSUE_TEMPLATE/2_bug_report.md
Labels: skip news

#9924 Add tests (excluding smoke) to CI GitHub Action
  .github/workflows/ci.yml
Labels: skip news

#9967 Disables the use of a terminal to activate an environment
  src/client/interpreter/activation/service.ts
  src/client/interpreter/serviceRegistry.ts
  src/test/interpreters/activation/service.unit.test.ts
  src/test/interpreters/serviceRegistry.unit.test.ts
Labels: skip news

#9970 Port server name fix to release
  CHANGELOG.md
  package.nls.json
  src/client/common/utils/localize.ts
  src/datascience-ui/interactive-common/kernelSelection.tsx
  src/datascience-ui/interactive-common/redux/store.ts
Labels: skip news

#9972 When starting Jupyter activate conda env
  src/client/common/terminal/helper.ts
  src/test/common/terminals/helper.unit.test.ts
Labels: skip news

#9987 Porting K8 fix to release
  CHANGELOG.md
  src/client/datascience/jupyter/notebookStarter.ts
Labels: skip news

#9964 Add smoke tests to GH Action
  .github/workflows/ci.yml
Labels: skip news

#9994 Fix open to work for non text documents
  src/client/common/application/commands.ts
  src/client/datascience/interactive-common/linkProvider.ts
Labels: skip news

#9995 Fix func test in DS failing due to FS issues
  src/test/datascience/mockCustomEditorService.ts
Labels: skip news

#9993 Fix dirty state not matching save button state
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/interactive-ipynb/nativeEditorProvider.ts
  src/client/datascience/interactive-ipynb/nativeEditorStorage.ts
  src/datascience-ui/native-editor/redux/reducers/creation.ts
Labels: skip news

#9920 Minor changes to dispatchers (action creators will dispatch multiple actions)
  src/client/datascience/interactive-common/synchronization.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/datascience-ui/history-react/redux/actions.ts
  src/datascience-ui/interactive-common/redux/helpers.ts
  src/datascience-ui/interactive-common/redux/reducers/types.ts
  src/datascience-ui/interactive-common/redux/store.ts
  src/datascience-ui/native-editor/nativeCell.tsx
  src/datascience-ui/native-editor/nativeEditor.tsx
  src/datascience-ui/native-editor/redux/actions.ts
  src/datascience-ui/native-editor/redux/reducers/creation.ts
  src/datascience-ui/native-editor/redux/reducers/effects.ts
  src/datascience-ui/native-editor/redux/reducers/execution.ts
  src/datascience-ui/native-editor/redux/reducers/index.ts
  src/datascience-ui/native-editor/redux/reducers/movement.ts
  src/datascience-ui/react-common/monacoEditor.tsx
  src/test/datascience/nativeEditor.functional.test.tsx
  src/test/datascience/testHelpers.tsx
Labels: skip news

#10018 Fix problem with undoing entire stack
  src/client/datascience/interactive-ipynb/nativeEditorStorage.ts
Labels: skip news

#10019 Refactor how messages are posted to reducers and to the extension
  src/client/datascience/interactive-common/synchronization.ts
  src/datascience-ui/history-react/redux/reducers/creation.ts
  src/datascience-ui/history-react/redux/reducers/effects.ts
  src/datascience-ui/history-react/redux/reducers/execution.ts
  src/datascience-ui/interactive-common/redux/helpers.ts
  src/datascience-ui/interactive-common/redux/reducers/kernel.ts
  src/datascience-ui/interactive-common/redux/reducers/transfer.ts
  src/datascience-ui/interactive-common/redux/reducers/variables.ts
  src/datascience-ui/interactive-common/redux/store.ts
  src/datascience-ui/native-editor/redux/reducers/effects.ts
  src/datascience-ui/native-editor/redux/reducers/execution.ts
Labels: skip news

#10022 Update version and changelog date for release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip news

#10028 Fixes to tests for clearing cell output
  src/test/datascience/nativeEditor.functional.test.tsx
Labels: skip news

#10039 Fixes to enablement of ds commands
  package.json
Labels: skip news

#9956 Replace console.* with trace* when possible
  src/client/common/featureDeprecationManager.ts
  src/client/common/logger.ts
  src/client/common/net/socket/socketServer.ts
  src/client/ioc/container.ts
Labels: skip news

#10041 Update change log for release
  CHANGELOG.md
  news/2 Fixes/9901.md
Labels: skip news

#10035 Run nightly pipelines at midnight PST
  build/ci/vscode-python-nightly-ci.yaml
  build/ci/vscode-python-nightly-flake-ci.yaml
  build/ci/vscode-python-nightly-uitest.yaml
Labels: skip news

#9762 Update jedi
  news/3 Code Health/9765.md
  requirements.in
  requirements.txt
Labels: external contributor

#10036 Complete refactoring of creation and queueing of actions
  src/client/datascience/interactive-common/interactiveBase.ts
  src/client/datascience/interactive-common/interactiveWindowMessageListener.ts
  src/client/datascience/interactive-common/synchronization.ts
  src/datascience-ui/history-react/redux/actions.ts
  src/datascience-ui/interactive-common/redux/helpers.ts
  src/datascience-ui/interactive-common/redux/postOffice.ts
  src/datascience-ui/interactive-common/redux/reducers/monaco.ts
  src/datascience-ui/interactive-common/redux/store.ts
  src/datascience-ui/native-editor/redux/actions.ts
  src/datascience-ui/native-editor/redux/reducers/creation.ts
  src/datascience-ui/native-editor/redux/reducers/execution.ts
  src/datascience-ui/native-editor/redux/reducers/movement.ts
Labels: skip news

#10077 Add tests to ensure localization files can be loaded
  src/test/extension.unit.test.ts
Labels: skip news

#10089 cherrypick into release: Fix for zh-tw loading issue. (#10085)
  news/2 Fixes/10072.md
  package.nls.zh-tw.json
Labels: skip news

#10076 Add coverage step to the GitHub action CI workflow
  .github/workflows/ci.yml
Labels: skip news

#10091 Update version and changelog for point release.
  CHANGELOG.md
  news/2 Fixes/10071.md
  news/2 Fixes/10072.md
  package-lock.json
  package.json
Labels: skip news

#10095 Perf improve to load time of extension
  news/2 Fixes/10094.md
  src/client/extension.ts
Labels: skip news

#10099 Tag GHA CI successful build as LKG
  .github/workflows/ci.yml
Labels: skip news

#9955 Mark poetry.lock as toml file
  news/1 Enhancements/9955.md
  package.json
Labels: external contributor

#10118 Fix credit in news
  news/1 Enhancements/9955.md
  news/2 Fixes/10111.md
Labels: skip news

#10114 Use different method for checking if kernelspec is available
  pythonFiles/datascience/getJupyterKernelspecVersion.py
  src/client/datascience/jupyter/interpreter/jupyterCommand.ts
  src/client/datascience/jupyter/interpreter/jupyterInterpreterDependencyService.ts
  src/test/datascience/jupyter/interpreter/jupyterInterpreterDependencyService.unit.test.ts
Labels: skip news

#10132 More logging for kernelspec problems
  src/client/datascience/jupyter/interpreter/jupyterCommand.ts
  src/client/datascience/jupyter/interpreter/jupyterInterpreterDependencyService.ts
  src/test/datascience/variableexplorer.functional.test.tsx
Labels: skip news

#10113 Check our saved jupyter interpreters before allowing any of them to be used as active interpreters
  src/client/common/process/types.ts
  src/client/datascience/activation.ts
  src/client/datascience/jupyter/interpreter/jupyterInterpreterService.ts
  src/client/datascience/jupyter/interpreter/jupyterInterpreterStateStore.ts
  src/test/datascience/activation.unit.test.ts
  src/test/datascience/jupyter/interpreter/jupyterInterpreterService.unit.test.ts
Labels: skip news

#10146 Port fixes for second point release.
  CHANGELOG.md
  PYTHON_INTERACTIVE_TROUBLESHOOTING.md
  package.json
  package.nls.json
  pythonFiles/datascience/getJupyterKernelspecVersion.py
  resources/InstallJupyter.png
  src/client/common/installer/productInstaller.ts
  src/client/common/process/types.ts
  src/client/common/utils/localize.ts
  src/client/datascience/activation.ts
  src/client/datascience/constants.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/jupyter/interpreter/jupyterCommand.ts
  src/client/datascience/jupyter/interpreter/jupyterCommandInterpreterDependencyService.ts
  src/client/datascience/jupyter/interpreter/jupyterInterpreterDependencyService.ts
  src/client/datascience/jupyter/interpreter/jupyterInterpreterService.ts
  src/client/datascience/jupyter/interpreter/jupyterInterpreterStateStore.ts
  src/client/datascience/jupyter/interpreter/jupyterInterpreterSubCommandExecutionService.ts
  src/client/datascience/jupyter/jupyterExecution.ts
  src/client/datascience/jupyter/jupyterVariables.ts
  src/client/datascience/jupyter/kernels/kernelSelector.ts
  src/client/datascience/jupyter/kernels/kernelService.ts
  src/client/datascience/jupyter/kernels/kernelSwitcher.ts
  src/client/telemetry/index.ts
  src/datascience-ui/history-react/interactivePanel.tsx
  src/datascience-ui/interactive-common/redux/reducers/variables.ts
  src/test/datascience/activation.unit.test.ts
  src/test/datascience/jupyter/interpreter/jupyterInterpreterDependencyService.unit.test.ts
  src/test/datascience/jupyter/interpreter/jupyterInterpreterService.unit.test.ts
  src/test/datascience/jupyter/interpreter/jupyterInterpreterSubCommandExecutionService.unit.test.ts
  src/test/datascience/jupyter/kernels/kernelSelector.unit.test.ts
  src/test/datascience/jupyter/kernels/kernelSwitcher.unit.test.ts
  src/test/datascience/notebook.functional.test.ts
  src/test/datascience/variableexplorer.functional.test.tsx
Labels: skip news

#10174 Include interpreter name in message
  src/client/datascience/jupyter/interpreter/jupyterInterpreterSubCommandExecutionService.ts
  src/test/datascience/jupyter/interpreter/jupyterInterpreterSubCommandExecutionService.unit.test.ts
Labels: skip news

#10175 Ignore display name when searching kernels matching an interpreter
  src/client/datascience/jupyter/kernels/kernelService.ts
Labels: skip news

#10179 Fix creation of lightweight CI LKG tag
  .github/workflows/ci.yml
Labels: skip news

#10120 Correctly log unit test error logs
  src/client/testing/unittest/runner.ts
Labels: skip news

#10187 Revert "Correctly log unit test error logs"
  src/client/testing/unittest/runner.ts
Labels: skip news

#10191 added stages to yaml file
  build/ci/performance/vscode-python-performance.yaml
Labels: skip news

#10195 Fixed Yaml syntax
  build/ci/performance/perfJobs.yaml
  build/ci/performance/strategy.yaml
  build/ci/performance/vscode-python-performance.yaml
Labels: skip news

#10208 Disable use of focusPending in notebooks
  src/datascience-ui/interactive-common/redux/reducers/commonEffects.ts
  src/datascience-ui/native-editor/nativeEditor.tsx
Labels: skip news

#10210 Further fixes for whitespace
  src/datascience-ui/history-react/redux/reducers/creation.ts
Labels: skip news

#10213 Clean up CI recipes.
  build/ci/templates/jobs/smoke.yml
  build/ci/templates/test_phases.yml
  build/ci/vscode-python-ci.yaml
  build/ci/vscode-python-nightly-ci.yaml
  build/ci/vscode-python-nightly-flake-ci.yaml
  build/ci/vscode-python-pr-validation.yaml
Labels: skip news

#10218 Some more ds telemetry
  CHANGELOG.md
  src/client/datascience/constants.ts
  src/client/datascience/interactive-common/interactiveBase.ts
  src/client/datascience/jupyter/jupyterExecution.ts
  src/client/telemetry/index.ts
Labels: skip news

#10044 fixing a typo in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: external contributor, skip news

#10244 Skip flaky FS test
  src/test/common/platform/filesystem.test.ts
Labels: skip news

#10254 Point release with fix for Issue 10250
  CHANGELOG.md
  package.json
  src/client/common/logger.ts
  src/client/interpreter/activation/service.ts
  src/test/interpreters/activation/service.unit.test.ts
Labels: skip news

#10229 Fix order of cells inserted
  src/datascience-ui/native-editor/redux/reducers/creation.ts
Labels: skip news

#10260 Fix more ds functional tests
  src/client/datascience/interactive-ipynb/nativeEditor.ts
Labels: skip news

#10284 Fix DS startup and shutdown functional tests
  src/test/datascience/nativeEditor.functional.test.tsx
Labels: skip news

#10258 Merge release branch into master
  CHANGELOG.md
  news/2 Fixes/10071.md
  news/2 Fixes/10072.md
  news/2 Fixes/10074.md
  news/2 Fixes/10075.md
  news/2 Fixes/10168.md
  news/2 Fixes/10170.md
  news/2 Fixes/10250.md
  news/2 Fixes/9693.md
  news/2 Fixes/9740.md
  news/2 Fixes/9796.md
  news/2 Fixes/9901.md
  news/2 Fixes/9904.md
  news/2 Fixes/9926.md
  news/2 Fixes/9933.md
  news/2 Fixes/9976.md
  news/2 Fixes/9991.md
  news/3 Code Health/10049.md
  news/3 Code Health/10098.md
  news/3 Code Health/10176.md
  news/3 Code Health/10212.md
  news/3 Code Health/9819.md
  news/3 Code Health/9883.md
Labels: skip news

#10300 More scrollbar fixes and some CSS cleanup
  src/client/datascience/types.ts
  src/client/datascience/webViewHost.ts
  src/datascience-ui/history-react/interactivePanel.less
  src/datascience-ui/history-react/interactivePanel.tsx
  src/datascience-ui/interactive-common/buildSettingsCss.ts
  src/datascience-ui/interactive-common/common.css
  src/datascience-ui/interactive-common/contentPanel.tsx
  src/datascience-ui/native-editor/nativeCell.tsx
  src/datascience-ui/native-editor/nativeEditor.less
  src/datascience-ui/react-common/settingsReactSide.ts
Labels: skip news

#10239 Restore old webview provider
  package.json
  src/client/common/application/commands.ts
  src/client/common/application/customEditorService.ts
  src/client/common/constants.ts
  src/client/datascience/constants.ts
  src/client/datascience/interactive-ipynb/autoSaveService.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/interactive-ipynb/nativeEditorOldWebView.ts
  src/client/datascience/interactive-ipynb/nativeEditorProvider.ts
  src/client/datascience/interactive-ipynb/nativeEditorProviderOld.ts
  src/client/datascience/interactive-ipynb/nativeEditorStorage.ts
  src/client/datascience/serviceRegistry.ts
  src/client/datascience/types.ts
  src/client/telemetry/index.ts
  src/datascience-ui/native-editor/nativeCell.tsx
  src/datascience-ui/native-editor/nativeEditor.tsx
  src/datascience-ui/react-common/constants.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/nativeEditor.functional.test.tsx
  src/test/datascience/testNativeEditorProvider.ts
Labels: skip news

#10203 removed jobs from parameters
  build/ci/performance/checkPerformanceResults.js
  build/ci/performance/perfJobs.yaml
  build/ci/performance/savePerformanceResults.js
  build/ci/performance/vscode-python-performance.yaml
Labels: skip news

#10338 Adds a prompt that shows up when user attaches to `ptvsd`
  package.nls.json
  src/client/common/utils/localize.ts
  src/client/debugger/extension/adapter/activator.ts
  src/client/debugger/extension/adapter/outdatedDebuggerPrompt.ts
  src/client/debugger/extension/adapter/types.ts
  src/client/debugger/extension/serviceRegistry.ts
  src/client/debugger/extension/types.ts
  src/test/datascience/mockJupyterManager.ts
  src/test/debugger/extension/adapter/activator.unit.test.ts
  src/test/debugger/extension/adapter/outdatedDebuggerPrompt.unit.test.ts
  src/test/debugger/extension/serviceRegistry.unit.test.ts
Labels: skip news

#10350 Fixes to setting focus to markdown cells
  src/datascience-ui/interactive-common/editor.tsx
  src/datascience-ui/interactive-common/mainState.ts
  src/datascience-ui/react-common/monacoEditor.tsx
  src/test/datascience/nativeEditor.functional.test.tsx
  src/test/datascience/nativeEditorTestHelpers.tsx
Labels: skip news
