Repository microsoft/vscode-python, pull requests merged in 2020-09, with the labels that each got.

#13589 Identify conda and windows store environments from given interpreter path
  src/client/common/utils/platform.ts
  src/client/pythonEnvironments/common/environmentIdentifier.ts
  src/client/pythonEnvironments/discovery/locators/helpers.ts
  src/test/pythonEnvironments/common/environmentIdentifier.unit.test.ts
  src/test/pythonEnvironments/common/envlayouts/conda1/conda-meta/history
  src/test/pythonEnvironments/common/envlayouts/conda1/python.exe
  src/test/pythonEnvironments/common/envlayouts/conda2/bin/python
  src/test/pythonEnvironments/common/envlayouts/conda2/conda-meta/history
Labels: skip news

#13665 Update renderers and notebooks to use new API
  .vscode/launch.json
  package-lock.json
  package.json
  src/client/common/application/notebook.ts
  src/client/common/application/types.ts
  src/client/datascience/notebook/integration.ts
  src/client/datascience/notebook/notebookEditor.ts
  src/client/datascience/notebook/renderer.ts
  src/client/datascience/notebook/serviceRegistry.ts
  src/datascience-ui/renderers/index.tsx
  src/datascience-ui/renderers/webviewApi.d.ts
  src/test/datascience/notebook/contentProvider.unit.test.ts
  src/test/datascience/notebook/helper.ts
  src/test/datascience/notebook/helpers.unit.test.ts
  src/test/datascience/notebook/rendererExension.unit.test.ts
  src/test/mocks/vsc/extHostedTypes.ts
  types/vscode-proposed/index.d.ts
  types/vscode.proposed.d.ts
  typings/vscode-proposed/index.d.ts
Labels: skip news

#13722 Disable prevention of running cells when restarting
  src/client/datascience/notebook/notebookEditor.ts
Labels: skip news

#13708 Add PyEnvInfo and the other base info types for the Python environments component.
  src/client/pythonEnvironments/base/info/index.ts
Labels: skip news

#13723 Mark some of the metadata as transient
  src/client/common/application/notebook.ts
  src/client/common/application/types.ts
  src/client/datascience/notebook/integration.ts
Labels: skip news

#13733 Don't run workflow jobs in forks
  .github/workflows/insiders.yml
  .github/workflows/release.yml
Labels: skip news

#13725 Update and pin LSP libraries for new APIs
  package-lock.json
  package.json
  src/test/datascience/mockCode2ProtocolConverter.ts
  src/test/datascience/mockProtocol2CodeConverter.ts
Labels: skip news

#13741 Remove unused LS settings from package.json
  package.json
  src/client/common/types.ts
Labels: skip news

#13748 Update package version for point release
  package-lock.json
  package.json
Labels: skip news

#13742 Provide an id for native notebook kernels returned to VSCode
  src/client/datascience/jupyter/kernels/types.ts
  src/client/datascience/notebook/kernelProvider.ts
Labels: skip news

#13753 Up idle timeout to match launch timeout (nightly flake failure)
  src/client/datascience/jupyter/jupyterSession.ts
  src/client/datascience/jupyter/jupyterSessionManager.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/jupyter/jupyterSession.unit.test.ts
Labels: skip news

#13756 Cherry picks for LS
  package-lock.json
  package.json
  src/test/datascience/mockCode2ProtocolConverter.ts
  src/test/datascience/mockProtocol2CodeConverter.ts
Labels: skip news

#13758 PORT showStartPage setting fix (#13706)
  CHANGELOG.md
  src/client/common/configSettings.ts
  src/test/common/configSettings/configSettings.unit.test.ts
Labels: skip news

#13746 ESLint update: Add new files to eslintignore + rename file
  .eslintignore
  src/test/pythonEnvironments/common/environmentIdentifier.unit.test.ts
  src/test/telemetry/extensionInstallTelemetry.unit.test.ts
Labels: skip news

#13735 Add the base Python environments "watchers".
  src/client/pythonEnvironments/base/watcher.ts
  src/client/pythonEnvironments/base/watchers.ts
  src/test/pythonEnvironments/base/watcher.unit.test.ts
  src/test/pythonEnvironments/base/watchers.unit.test.ts
Labels: skip news

#13761 Ignore dependency check when finding a kernel spec
  src/client/datascience/jupyter/kernels/kernelSelector.ts
  src/client/datascience/kernel-launcher/kernelFinder.ts
  src/client/datascience/kernel-launcher/types.ts
  src/client/datascience/notebook/kernelProvider.ts
  src/test/datascience/jupyter/kernels/kernelSelector.unit.test.ts
Labels: skip news

#13765 Fixes to preferred kernels in Native Notebooks
  src/client/datascience/jupyter/kernels/helpers.ts
  src/client/datascience/jupyter/kernels/kernelSelector.ts
  src/client/datascience/kernel-launcher/kernelFinder.ts
  src/client/datascience/kernel-launcher/kernelProcess.ts
  src/client/datascience/kernel-launcher/types.ts
  src/client/datascience/notebook/kernelProvider.ts
  src/test/datascience/kernelFinder.unit.test.ts
  src/test/datascience/mockKernelFinder.ts
Labels: skip news

#13767 Hide Interpreter status bar when opening a Jupyter notebook
  src/client/datascience/notebook/interpreterStatusBarVisbility.ts
  src/client/datascience/notebook/serviceRegistry.ts
  src/client/interpreter/contracts.ts
  src/client/interpreter/display/index.ts
  src/test/interpreters/display.unit.test.ts
Labels: skip news

#13772 Replace `newNotebook` with `notebookEditor` in commands
  package.json
  package.nls.json
  src/client/common/application/commands.ts
  src/client/datascience/commands/notebookCommands.ts
  src/client/datascience/constants.ts
Labels: skip news

#13774 Bump plotly.js-dist at v1.55.1
  package-lock.json
  package.json
Labels: skip news

#13773 WebViewHost => WebviewPanelHost WebView => WebviewPanel refactor
  src/client/common/application/types.ts
  src/client/common/application/webPanels/webPanel.ts
  src/client/common/application/webviewPanels/webviewPanel.ts
  src/client/common/application/webviewPanels/webviewPanelProvider.ts
  src/client/common/application/webviews/webview.ts
  src/client/common/installer/serviceRegistry.ts
  src/client/common/startPage/startPage.ts
  src/client/common/startPage/startPageMessageListener.ts
  src/client/datascience/data-viewing/dataViewer.ts
  src/client/datascience/data-viewing/dataViewerMessageListener.ts
  src/client/datascience/interactive-common/interactiveBase.ts
  src/client/datascience/interactive-common/interactiveWindowMessageListener.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/interactive-ipynb/nativeEditorOldWebView.ts
  src/client/datascience/interactive-ipynb/nativeEditorProviderOld.ts
  src/client/datascience/interactive-window/interactiveWindow.ts
  src/client/datascience/interactive-window/interactiveWindowProvider.ts
  src/client/datascience/notebookStorage/nativeEditorProvider.ts
  src/client/datascience/plotting/plotViewer.ts
  src/client/datascience/plotting/plotViewerMessageListener.ts
  src/client/datascience/webviews/webviewHost.ts
  src/client/datascience/webviews/webviewPanelHost.ts
  src/datascience-ui/react-common/postOffice.ts
  src/test/common/installer/serviceRegistry.unit.test.ts
  src/test/datascience/data-viewing/dataViewer.unit.test.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/interactive-ipynb/nativeEditorStorage.unit.test.ts
  src/test/datascience/mountedWebView.ts
  src/test/datascience/uiTests/webBrowserPanel.ts
  src/test/datascience/uiTests/webBrowserPanelProvider.ts
  src/test/startPage/startPage.unit.test.ts
Labels: skip news

#13757 Fix Eslint in legacyIOc
  .eslintrc
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/pythonEnvironments/legacyIOC.unit.test.ts
Labels: skip news

#13764 Add the base Python envs locators.
  src/client/common/utils/async.ts
  src/client/pythonEnvironments/base/locator.ts
  src/client/pythonEnvironments/base/locators.ts
  src/client/pythonEnvironments/base/watcher.ts
  src/client/pythonEnvironments/base/watchers.ts
  src/test/pythonEnvironments/base/common.ts
  src/test/pythonEnvironments/base/locators.unit.test.ts
  src/test/pythonEnvironments/base/watcher.unit.test.ts
  src/test/pythonEnvironments/base/watchers.unit.test.ts
Labels: skip news

#13784 Disable the "Interpreters - Workspace VirtualEnv Service" standard tests.
  src/test/pythonEnvironments/discovery/locators/workspaceVirtualEnvService.test.ts
Labels: skip news

#13786 All languages in native notebooks, default Python
  src/client/datascience/notebook/helpers/helpers.ts
  src/test/datascience/notebook/contentProvider.unit.test.ts
  src/test/datascience/notebook/helpers.unit.test.ts
Labels: skip news

#13787 Store kernel info into ipynb only when saving
  src/client/datascience/notebook/helpers/helpers.ts
  src/client/datascience/notebook/kernelProvider.ts
Labels: skip news

#13790 Store interpreter name in metadata of nb
  src/client/datascience/notebookStorage/baseModel.ts
Labels: skip news

#13797 Fix raw notebooks opening with old webview
  src/client/datascience/raw-kernel/liveshare/hostRawNotebookProvider.ts
  src/test/common/installer/moduleInstaller.unit.test.ts
Labels: skip news

#13803 More tests failing as result of isolated change
  src/test/common/process/pythonProcess.unit.test.ts
  src/test/common/terminals/synchronousTerminalService.unit.test.ts
Labels: skip news

#13825 Merge back from release to master
  CHANGELOG.md
  news/1 Enhancements/13535.md
  news/1 Enhancements/13656.md
  news/2 Fixes/11711.md
  news/2 Fixes/13387.md
  news/2 Fixes/13551.md
Labels: skip news

#13817 Disable flaky file system tests
  src/test/common/platform/filesystem.test.ts
Labels: skip news

#13777 Update to typescript 4.0
  package-lock.json
  package.json
  src/client/providers/jediProxy.ts
  src/client/testing/explorer/testTreeViewItem.ts
  src/ipywidgets/src/manager.ts
  src/test/common/configSettings.test.ts
  src/test/common/net/fileDownloader.unit.test.ts
  src/test/datascience/mockProtocol2CodeConverter.ts
  src/test/datascience/notebook.functional.test.ts
Labels: skip news

#13828 Bump plotly.js-dist at v1.55.2
  package-lock.json
  package.json
Labels: external contributor, skip news

#13798 Add join mailing list prompt
  .eslintignore
  src/client/application/misc/joinMailingListPrompt.ts
  src/client/application/serviceRegistry.ts
  src/client/common/experiments/groups.ts
  src/client/interpreter/display/interpreterSelectionTip.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/test/application/diagnostics/serviceRegistry.unit.test.ts
  src/test/application/misc/joinMailingListPrompt.unit.test.ts
Labels: skip news

#13836 Update notebook API with latest changes
  src/client/datascience/jupyter/kernels/kernelSelections.ts
  src/client/datascience/notebook/kernelProvider.ts
  types/vscode-proposed/index.d.ts
  types/vscode.proposed.d.ts
  typings/vscode-proposed/index.d.ts
Labels: skip news

#13841 Fixes for point release
  CHANGELOG.md
  package-lock.json
  package.json
  src/client/common/experiments/manager.ts
Labels: skip news

#13840 Fix nyc compile errors
  package-lock.json
  src/client/datascience/common.ts
Labels: skip news

#13845 Replace 'master' with 'main' in readme
  README.md
Labels: skip news

#13780 Add an extension-specific locator that will wrap the low-level locators.
  src/client/common/utils/async.ts
  src/client/pythonEnvironments/discovery/locators/index.ts
  src/test/pythonEnvironments/base/common.ts
  src/test/pythonEnvironments/discovery/locators/index.unit.test.ts
Labels: skip news

#13498 Initialize/activate the `ExtensionLocators` when the extension activates.
  src/client/extensionInit.ts
  src/client/pythonEnvironments/index.ts
Labels: skip news

#13851 Fix git diff detection code
  src/client/datascience/interactive-ipynb/nativeEditorProviderOld.ts
Labels: skip news

#13834 Add compiler support for ES2020 wherever we support ES2019
  src/test/datascience/extensionapi/exampleextension/ms-ai-tools-test/tsconfig.json
  tsconfig.extension.json
  tsconfig.json
Labels: skip news

#13852 Static analysis cleanup
  CHANGELOG.md
  build/ci/TSAOptions.json
  build/ci/static_analysis/policheck/exceptions.mdb
  build/ci/vscode-python-ci-static-analysis.yaml
  src/client/common/editor.ts
  src/client/datascience/notebookStorage/vscNotebookModel.ts
  src/client/testing/codeLenses/testFiles.ts
Labels: skip news

#13857 ESLint fixes for unrelated files in pythonEnvironments/discovery
  src/client/pythonEnvironments/discovery/index.ts
  src/client/pythonEnvironments/discovery/locators/types.ts
  src/client/pythonEnvironments/discovery/subenv.ts
Labels: skip news

#13872 Make uri expiration test more robust
  src/test/datascience/jupyterUriProviderRegistration.functional.test.ts
Labels: skip news

#13879 Make sure renderers output is generated
  package.json
Labels: skip news

#13888 Fix 2.7 unit test requirements
  requirements.in
  requirements.txt
Labels: skip news

#13896 Fix pygls for 2.7 too
  requirements.in
  requirements.txt
Labels: skip news

#13922 Turn off custom editor until we ship
  experiments.json
Labels: skip news

#13897 Add the "skip news" entry for some dependabot PRs
  .github/dependabot.yml
Labels: skip news

#13900 removed experiment code and extra setting
  package.json
  src/client/common/experiments/groups.ts
  src/client/common/startPage/startPage.ts
  src/client/common/types.ts
  src/client/datascience/data-viewing/dataViewer.ts
  src/client/datascience/interactive-common/interactiveBase.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/interactive-ipynb/nativeEditorOldWebView.ts
  src/client/datascience/interactive-ipynb/nativeEditorProviderOld.ts
  src/client/datascience/interactive-window/interactiveWindow.ts
  src/client/datascience/interactive-window/interactiveWindowProvider.ts
  src/client/datascience/notebookStorage/nativeEditorProvider.ts
  src/client/datascience/plotting/plotViewer.ts
  src/client/datascience/types.ts
  src/client/datascience/webviews/webviewHost.ts
  src/client/datascience/webviews/webviewPanelHost.ts
  src/datascience-ui/history-react/interactivePanel.tsx
  src/datascience-ui/react-common/settingsReactSide.ts
Labels: skip news

#13925 Merge back from release
  CHANGELOG.md
Labels: skip news

#13928 Up release version for new release
  CHANGELOG.md
  package.json
Labels: skip news

#13930 Workaround test issue
  build/ci/templates/globals.yml
  src/test/standardTest.ts
Labels: skip news

#13931 update version
  package-lock.json
  package.json
Labels: skip news

#13853 Implement the high-level component API.
  src/client/pythonEnvironments/index.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/format/extension.format.test.ts
  src/test/pythonEnvironments/legacyIOC.unit.test.ts
  src/test/serviceRegistry.ts
  src/test/testing/nosetest/nosetest.disovery.test.ts
  src/test/testing/pytest/pytest.discovery.test.ts
  src/test/testing/pytest/pytest.run.test.ts
  src/test/testing/unittest/unittest.discovery.test.ts
  src/test/testing/unittest/unittest.run.test.ts
Labels: skip news

#13893 Virtualenv locator
  src/client/pythonEnvironments/common/environmentIdentifier.ts
  src/client/pythonEnvironments/discovery/locators/services/virtualenvLocator.ts
  src/test/pythonEnvironments/common/environmentIdentifier.unit.test.ts
  src/test/pythonEnvironments/common/envlayouts/virtualenv1/bin/activate
  src/test/pythonEnvironments/common/envlayouts/virtualenv2/bin/activate.sh
  src/test/pythonEnvironments/common/envlayouts/virtualenv3/bin/activate.ps1
  src/test/pythonEnvironments/discovery/locators/virtualenvLocator.unit.test.ts
Labels: skip news

#13762 Add API to identify pipenv
  src/client/pythonEnvironments/common/environmentIdentifier.ts
  src/client/pythonEnvironments/common/externalDependencies.ts
  src/client/pythonEnvironments/discovery/locators/services/pipEnvHelper.ts
  src/test/pythonEnvironments/common/environmentIdentifier.unit.test.ts
  src/test/pythonEnvironments/common/envlayouts/pipenv/globalEnvironments/project2-vnNIWe9P/.project
  src/test/pythonEnvironments/common/envlayouts/pipenv/globalEnvironments/project2-vnNIWe9P/bin/python
  src/test/pythonEnvironments/common/envlayouts/pipenv/globalEnvironments/project3-2s1eXEJ2/.project
  src/test/pythonEnvironments/common/envlayouts/pipenv/globalEnvironments/project3-2s1eXEJ2/Scripts/python.exe
  src/test/pythonEnvironments/common/envlayouts/pipenv/project1/.venv/Scripts/python.exe
  src/test/pythonEnvironments/common/envlayouts/pipenv/project1/CustomPipfileName
  src/test/pythonEnvironments/common/envlayouts/pipenv/project2/Pipfile
  src/test/pythonEnvironments/common/envlayouts/pipenv/project3/Pipfile
  src/test/pythonEnvironments/common/envlayouts/pipenv/project3/parent/child/folder/dummyFile
  src/test/pythonEnvironments/discovery/locators/pipEnvHelper.functional.test.ts
  src/test/pythonEnvironments/discovery/locators/pipEnvHelper.unit.test.ts
Labels: skip news

#13950 Add an optional onUpdated event to the iterator returned by ILocator.iterEnvs().
  src/client/pythonEnvironments/base/locator.ts
  src/client/pythonEnvironments/base/locators.ts
  src/client/pythonEnvironments/discovery/locators/index.ts
  src/client/pythonEnvironments/index.ts
  src/test/pythonEnvironments/base/common.ts
Labels: skip news

#13941 fully bump raw kernel
  experiments.json
Labels: skip news

#13895 Virtualenvwrapper locator
  src/client/pythonEnvironments/common/environmentIdentifier.ts
  src/client/pythonEnvironments/common/virtualenvwrapperUtils.ts
  src/client/pythonEnvironments/discovery/locators/services/virtualenvwrapperLocator.ts
  src/test/pythonEnvironments/common/environmentIdentifier.unit.test.ts
  src/test/pythonEnvironments/common/envlayouts/virtualenvwrapper1/.virtualenvs/myenv/bin/python
  src/test/pythonEnvironments/common/envlayouts/virtualenvwrapper1/Envs/myenv/Scripts/python.exe
  src/test/pythonEnvironments/common/envlayouts/virtualenvwrapper2/myenv/bin/python
  src/test/pythonEnvironments/common/virtualenvwrapperUtils.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/virtualenvwrapperLocator.unit.test.ts
Labels: skip news

#13951 Clean up eslint errors
  src/client/pythonEnvironments/discovery/locators/helpers.ts
  src/client/pythonEnvironments/discovery/locators/index.ts
  src/client/pythonEnvironments/discovery/locators/progressService.ts
  src/client/pythonEnvironments/discovery/locators/services/KnownPathsService.ts
  src/client/pythonEnvironments/discovery/locators/services/baseVirtualEnvService.ts
  src/test/pythonEnvironments/discovery/locators/index.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/progressService.unit.test.ts
Labels: skip news

#13858 Add a legacy DI adapter for the Python envs component.
  src/client/interpreter/contracts.ts
  src/client/pythonEnvironments/legacyIOC.ts
Labels: skip news

#13923 Extension api for DataScience
  src/client/api.ts
  src/client/datascience/api/jupyterIntegration.ts
Labels: skip news

#13973 Extension API to return path to debugpy for DS
  src/client/datascience/api/jupyterIntegration.ts
Labels: skip news

#13975 Port ipykernel install fix to release
  CHANGELOG.md
  package.nls.json
  src/client/common/utils/localize.ts
  src/client/datascience/jupyter/kernels/kernelSelector.ts
  src/client/datascience/kernel-launcher/kernelFinder.ts
  src/test/datascience/jupyter/kernels/kernelSelector.unit.test.ts
  src/test/datascience/kernelFinder.unit.test.ts
Labels: skip news

#13976 Merge in changes to release
  CHANGELOG.md
  build/ci/templates/globals.yml
  src/client/datascience/interactive-common/interactiveBase.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/jupyter/kernels/helpers.ts
  src/datascience-ui/history-react/interactivePanel.tsx
  src/datascience-ui/interactive-common/jupyterInfo.tsx
  src/datascience-ui/interactive-common/mainState.ts
  src/datascience-ui/interactive-common/redux/reducers/kernel.ts
  src/datascience-ui/interactive-common/redux/store.ts
  src/datascience-ui/native-editor/toolbar.tsx
  src/test/datascience/interactivePanel.functional.test.tsx
  src/test/datascience/nativeEditor.functional.test.tsx
  src/test/datascience/nativeEditor.toolbar.functional.test.tsx
  src/test/datascience/testHelpers.tsx
  src/test/debuggerTest.ts
  src/test/multiRootTest.ts
  src/test/standardTest.ts
Labels: skip news

#13869 Use the Python environments component DI adapter in the extension.
  src/client/application/diagnostics/checks/macPythonInterpreter.ts
  src/client/common/process/pythonExecutionFactory.ts
  src/client/interpreter/contracts.ts
  src/client/interpreter/helpers.ts
  src/client/interpreter/interpreterService.ts
  src/client/interpreter/locators/types.ts
  src/client/pythonEnvironments/discovery/locators/index.ts
  src/client/pythonEnvironments/discovery/locators/services/condaService.ts
  src/client/pythonEnvironments/discovery/locators/services/hashProviderFactory.ts
  src/client/pythonEnvironments/discovery/locators/services/windowsRegistryService.ts
  src/client/pythonEnvironments/discovery/locators/services/windowsStoreInterpreter.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/application/diagnostics/checks/macPythonInterpreter.unit.test.ts
  src/test/common/process/pythonExecutionFactory.unit.test.ts
  src/test/interpreters/helpers.unit.test.ts
  src/test/interpreters/interpreterService.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/condaService.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/hasProviderFactory.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/helpers.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/index.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/windowsRegistryService.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/windowsStoreInterpreter.unit.test.ts
Labels: skip news

#13978 Port api
  src/client/api.ts
  src/client/jupyter/jupyterIntegration.ts
Labels: skip news

#13985 Disable split views of custom editors
  src/client/datascience/notebookStorage/nativeEditorProvider.ts
Labels: skip news

#13987 update localization files
  package.nls.json
  package.nls.nl.json
  package.nls.pl.json
  package.nls.zh-tw.json
  src/client/common/application/webviewPanels/webviewPanel.ts
  src/client/common/insidersBuild/insidersExtensionPrompt.ts
  src/client/common/utils/localize.ts
  src/test/common/insidersBuild/insidersExtensionPrompt.unit.test.ts
Labels: skip news

#13993 update test plan for ipykernel (python repo)
  .github/test_plan.md
Labels: skip news

#13995 Port two fixes to the release branch
  CHANGELOG.md
  src/client/datascience/export/exportUtil.ts
  src/client/datascience/interactive-ipynb/nativeEditorProviderOld.ts
  src/client/datascience/interactive-ipynb/trustCommandHandler.ts
  src/client/datascience/interactive-window/interactiveWindow.ts
  src/client/datascience/notebook/contentProvider.ts
  src/client/datascience/notebook/notebookEditorProvider.ts
  src/client/datascience/notebookStorage/nativeEditorProvider.ts
  src/client/datascience/notebookStorage/nativeEditorStorage.ts
  src/client/datascience/notebookStorage/notebookStorageProvider.ts
  src/client/datascience/types.ts
  src/test/datascience/export/exportUtil.test.ts
  src/test/datascience/interactive-ipynb/nativeEditorStorage.unit.test.ts
  src/test/datascience/mockCustomEditorService.ts
  src/test/datascience/notebook/contentProvider.ds.test.ts
  src/test/datascience/notebook/contentProvider.unit.test.ts
Labels: skip news

#13977 add jedi-language-server to 3rd party notices
  ThirdPartyNotices-Distribution.txt
  ThirdPartyNotices-Repository.txt
Labels: skip news

#13856 Find interpreter based on hash in kernelspec of nb metadata
  src/client/datascience/jupyter/kernels/kernelSelector.ts
  src/client/datascience/notebookStorage/baseModel.ts
Labels: skip news

#13996 Pyenv locator
  src/client/pythonEnvironments/common/environmentIdentifier.ts
  src/client/pythonEnvironments/discovery/locators/services/pyenvLocator.ts
  src/test/pythonEnvironments/common/environmentIdentifier.unit.test.ts
  src/test/pythonEnvironments/common/envlayouts/pyenv1/.pyenv/versions/3.6.9/bin/python
  src/test/pythonEnvironments/common/envlayouts/pyenv2/.pyenv/pyenv-win/versions/3.6.9/bin/python.exe
  src/test/pythonEnvironments/common/envlayouts/pyenv3/versions/3.6.9/bin/python
  src/test/pythonEnvironments/common/envlayouts/pyenv3/versions/3.6.9/bin/python.exe
  src/test/pythonEnvironments/discovery/locators/pyenvLocator.unit.test.ts
Labels: skip news

#14015 Update api
  src/client/jupyter/jupyterIntegration.ts
Labels: skip news

#14024 disable test_discover_complex_default and
  pythonFiles/tests/testing_tools/adapter/test_functional.py
Labels: skip news

#13997 Modify environment info worker to support new type and to work with resolver
  pythonFiles/interpreterInfo.py
  src/client/common/process/internal/scripts/index.ts
  src/client/common/process/pythonDaemon.ts
  src/client/pythonEnvironments/base/info/interpreter.ts
  src/client/pythonEnvironments/base/info/pythonVersion.ts
  src/client/pythonEnvironments/info/environmentInfoService.ts
  src/client/pythonEnvironments/info/interpreter.ts
  src/test/pythonEnvironments/base/common.ts
  src/test/pythonEnvironments/info/environmentInfoService.functional.test.ts
Labels: skip news

#14036 Remove crossProcessLock
  src/client/datascience/crossProcessLock.ts
  src/test/datascience/crossProcessLock.unit.test.ts
Labels: skip news

#14021 Add API to get language server from external extensions
  src/client/activation/common/activatorBase.ts
  src/client/activation/jedi/multiplexingActivator.ts
  src/client/activation/refCountedLanguageServer.ts
  src/client/activation/types.ts
  src/client/datascience/api/jupyterIntegration.ts
  src/client/datascience/interactive-common/intellisense/intellisenseProvider.ts
  src/client/datascience/interactive-common/intellisense/notebookLanguageServer.ts
  src/datascience-ui/interactive-common/intellisenseProvider.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/intellisense.unit.test.ts
  src/test/datascience/mockJupyterExtensionIntegration.ts
  src/test/datascience/mockLanguageServer.ts
  src/test/mocks/vsc/index.ts
  src/test/vscode-mock.ts
Labels: skip news

#14012 Fix failing virtualenvwrapper Windows unit tests
  src/client/pythonEnvironments/discovery/locators/services/virtualenvwrapperLocator.ts
  src/test/pythonEnvironments/discovery/locators/virtualenvwrapperLocator.unit.test.ts
Labels: skip news

#13878 Rely on AppInsights API for exceptions
  src/client/activation/node/languageServerProxy.ts
  src/client/telemetry/index.ts
  src/test/telemetry/index.unit.test.ts
Labels: internal contributor, skip news

#14041 Delete ds commands settings constants
  .eslintignore
  .github/test_plan.md
  .prettierrc.js
  .sonarcloud.properties
  .vscode/launch.json
  .vscode/tasks.json
  .vscodeignore
  build/.mocha.performance.json
  build/.nycrc
  build/ci/performance/DS_test_benchmark.json
  build/ci/static_analysis/credscan/CredScanSuppressions.json
  build/ci/templates/test_phases.yml
  build/ci/vscode-python-pr-validation.yaml
  build/debug/replaceWithWebBrowserPanel.js
  build/webpack/plugins/less-plugin-base64.js
  build/webpack/webpack.startpage-ui.config.builder.js
  gulpfile.js
  package.datascience-ui.dependencies.json
  package.json
  pythonFiles/vscode_datascience_helpers/__init__.py
  pythonFiles/vscode_datascience_helpers/dummyJupyter.py
  pythonFiles/vscode_datascience_helpers/getJupyterKernels.py
  pythonFiles/vscode_datascience_helpers/getJupyterKernelspecVersion.py
  pythonFiles/vscode_datascience_helpers/getJupyterVariableDataFrameInfo.py
  pythonFiles/vscode_datascience_helpers/getJupyterVariableDataFrameRows.py
  pythonFiles/vscode_datascience_helpers/getJupyterVariableShape.py
  pythonFiles/vscode_datascience_helpers/getServerInfo.py
  pythonFiles/vscode_datascience_helpers/jupyter_daemon.py
  pythonFiles/vscode_datascience_helpers/jupyter_nbInstalled.py
  pythonFiles/vscode_datascience_helpers/kernel_launcher.py
  pythonFiles/vscode_datascience_helpers/kernel_launcher_daemon.py
  pythonFiles/vscode_datascience_helpers/kernel_prewarm_starter.py
  pythonFiles/vscode_datascience_helpers/win_interrupt.py
  src/client/common/application/commands.ts
  src/client/common/configSettings.ts
  src/client/common/process/internal/scripts/index.ts
  src/client/common/process/internal/scripts/vscode_datascience_helpers.ts
  src/client/common/startPage/codeCssGenerator.ts
  src/client/common/startPage/constants.ts
  src/client/common/startPage/startPage.ts
  src/client/common/startPage/types.ts
  src/client/common/startPage/webviewHost.ts
  src/client/common/startPage/webviewPanelHost.ts
  src/client/common/types.ts
  src/client/telemetry/index.ts
  src/startPage-ui/react-common/postOffice.ts
  src/test/common/configSettings/configSettings.unit.test.ts
  src/test/common/utils/localize.functional.test.ts
  src/test/smoke/datascience.smoke.test.ts
  src/test/startPage/mockWorkspaceConfig.ts
  tsconfig.extension.json
  tsconfig.json
  tsconfig.startpage-ui.json
Labels: skip news

#14042 Final updates for release
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
  news/1 Enhancements/14027.md
  package-lock.json
  package.json
Labels: skip news

#14046 Put back when clause for execselectioninterminal
  package.json
Labels: skip news

#14049 Fixed annoying warnings
  CHANGELOG.md
  package.nls.json
Labels: skip news

#14039 Have dependabot ignore pytest and py
  .github/dependabot.yml
Labels: skip news

#14057 Ensure CI runs against PRs
  build/ci/vscode-python-pr-validation.yaml
Labels: skip news

#14060 Fix compilation errors
  build/webpack/webpack.startpage-ui.config.builder.js
  experiments.json
  gulpfile.js
  package.json
  pvsc.code-workspace
  src/client/common/experiments/groups.ts
  src/client/common/experiments/manager.ts
  src/client/common/startPage/codeCssGenerator.ts
  src/client/common/types.ts
  src/test/common/experiments/manager.unit.test.ts
  src/test/startPage/startPageIocContainer.ts
  tsconfig.json
  tslint.json
Labels: skip news

#13953 Added environments reducer
  src/client/pythonEnvironments/base/info/index.ts
  src/client/pythonEnvironments/base/locator.ts
  src/client/pythonEnvironments/collection/environmentsReducer.ts
  src/test/pythonEnvironments/base/common.ts
  src/test/pythonEnvironments/collection/environmentsReducer.unit.test.ts
Labels: skip news

#14063 Restore API changes
  src/client/jupyter/jupyterIntegration.ts
Labels: skip news

#14059 Merge release back to master
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
  ThirdPartyNotices-Repository.txt
  build/ci/templates/globals.yml
  package.nls.json
  pythonFiles/tests/testing_tools/adapter/test_functional.py
  src/test/debuggerTest.ts
  src/test/multiRootTest.ts
  src/test/standardTest.ts
Labels: skip news

#14050 Fix object sort order in tools tests
  pythonFiles/tests/testing_tools/adapter/test_functional.py
Labels: skip news

#14064 Update ubuntu images for GPU issue fix
  build/ci/templates/jobs/build_compile.yml
  build/ci/templates/jobs/coverage.yml
  build/ci/vscode-python-ci-manual.yaml
  build/ci/vscode-python-ci.yaml
  build/ci/vscode-python-nightly-ci.yaml
  build/ci/vscode-python-nightly-flake-ci.yaml
  build/ci/vscode-python-pr-validation.yaml
Labels: skip news

#14019 Added environments resolver
  src/client/pythonEnvironments/base/locator.ts
  src/client/pythonEnvironments/base/locators/composite/environmentsReducer.ts
  src/client/pythonEnvironments/base/locators/composite/environmentsResolver.ts
  src/test/pythonEnvironments/base/locators/composite/environmentsReducer.unit.test.ts
  src/test/pythonEnvironments/base/locators/composite/environmentsResolver.unit.test.ts
Labels: skip news

#14108 Do not quote isolated in exec module
  src/client/common/process/internal/python.ts
  src/client/common/process/internal/scripts/index.ts
  src/test/common/moduleInstaller.test.ts
Labels: skip news

#14111 change startpage-ui to startPage-ui, to fix CI
  .eslintignore
  .vscodeignore
  build/webpack/webpack.startPage-ui-viewers.config.js
  build/webpack/webpack.startPage-ui.config.builder.js
  build/webpack/webpack.startPage-ui.config.js
  gulpfile.js
  package.json
  src/client/common/startPage/startPage.ts
  src/test/startPage/mountedWebView.ts
  src/test/startPage/startPage.functional.test.tsx
  tsconfig.extension.json
  tsconfig.startPage-ui.json
Labels: skip news

#13737 Update cell output and metadata using Edit API
  .vscode/launch.json
  src/client/common/utils/decorators.ts
  src/client/datascience/jupyter/kernels/cellExecution.ts
  src/client/datascience/jupyter/kernels/kernel.ts
  src/client/datascience/jupyter/kernels/kernelExecution.ts
  src/client/datascience/jupyter/kernels/kernelProvider.ts
  src/client/datascience/notebook/contentProvider.ts
  src/client/datascience/notebook/helpers/executionHelpers.ts
  src/client/datascience/notebook/helpers/helpers.ts
  src/client/datascience/notebook/notebookEditor.ts
  src/client/datascience/notebookStorage/vscNotebookModel.ts
  src/test/datascience/notebook/cellOutput.ds.test.ts
  src/test/datascience/notebook/contentProvider.ds.test.ts
  src/test/datascience/notebook/contentProvider.unit.test.ts
  src/test/datascience/notebook/edit.ds.test.ts
  src/test/datascience/notebook/executionService.ds.test.ts
  src/test/datascience/notebook/helper.ts
  src/test/datascience/notebook/helpers.unit.test.ts
  src/test/datascience/notebook/interrupRestart.ds.test.ts
  src/test/datascience/notebook/rendererExension.unit.test.ts
  src/test/datascience/notebook/saving.ds.test.ts
  src/test/mocks/vsc/extHostedTypes.ts
  types/vscode-proposed/index.d.ts
  types/vscode.proposed.d.ts
  typings/vscode-proposed/index.d.ts
Labels: skip news

#14122 Fix unit test broken by recent revert
  src/test/common/installer/moduleInstaller.unit.test.ts
  src/test/common/process/pythonProcess.unit.test.ts
  src/test/common/terminals/synchronousTerminalService.unit.test.ts
Labels: skip news

#14125 Cherry pick to address path issues.
  src/client/common/process/internal/python.ts
  src/client/common/process/internal/scripts/index.ts
  src/test/common/installer/moduleInstaller.unit.test.ts
  src/test/common/moduleInstaller.test.ts
  src/test/common/process/pythonProcess.unit.test.ts
  src/test/common/terminals/synchronousTerminalService.unit.test.ts
Labels: skip news

#14133 Port escape fix to release branch
  CHANGELOG.md
  src/client/datascience/jupyter/jupyterNotebook.ts
  src/client/datascience/jupyter/kernelVariables.ts
  src/client/datascience/jupyter/kernels/cellExecution.ts
  src/client/datascience/jupyter/oldJupyterVariables.ts
  src/datascience-ui/interactive-common/cellOutput.tsx
  src/test/datascience/Untitled-1.ipynb
  src/test/datascience/interactiveWindow.functional.test.tsx
  src/test/datascience/liveshare.functional.test.tsx
  src/test/datascience/nativeEditor.functional.test.tsx
  src/test/datascience/notebook.functional.test.ts
  src/test/datascience/trustedNotebooks.functional.test.tsx
  src/test/datascience/uiTests/ipywidget.ui.functional.test.ts
Labels: skip news

#14109 revert VSC_PYTHON_CI_TEST_VSC_CHANNEL changes
  build/ci/templates/globals.yml
Labels: skip news

#14026 Merge environment and compare environments
  src/client/pythonEnvironments/base/info/env.ts
  src/client/pythonEnvironments/base/info/index.ts
  src/client/pythonEnvironments/base/info/pythonVersion.ts
  src/client/pythonEnvironments/base/locators/composite/environmentsReducer.ts
  src/client/pythonEnvironments/base/locators/composite/environmentsResolver.ts
  src/client/pythonEnvironments/common/environmentIdentifier.ts
  src/client/pythonEnvironments/info/index.ts
Labels: skip news

#14139 Update version and changelog for Point Release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip news

#14051 Add PythonEnvInfo-related helpers.
  src/client/common/utils/misc.ts
  src/client/pythonEnvironments/base/info/env.ts
  src/client/pythonEnvironments/base/info/index.ts
  src/client/pythonEnvironments/base/info/pythonVersion.ts
  src/client/pythonEnvironments/base/locator.ts
  src/client/pythonEnvironments/base/locatorUtils.ts
  src/client/pythonEnvironments/base/locators/composite/environmentsReducer.ts
  src/client/pythonEnvironments/base/locators/composite/environmentsResolver.ts
  src/client/pythonEnvironments/discovery/locators/index.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/pythonEnvironments/base/common.ts
  src/test/pythonEnvironments/base/locatorUtils.unit.test.ts
  src/test/pythonEnvironments/base/locators.unit.test.ts
  src/test/pythonEnvironments/base/locators/composite/environmentsReducer.unit.test.ts
  src/test/pythonEnvironments/base/locators/composite/environmentsResolver.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/index.unit.test.ts
Labels: skip news

#14145 Escaping fix broke a number of things
  src/client/datascience/jupyter/jupyterDebugger.ts
  src/datascience-ui/interactive-common/cellOutput.tsx
  src/test/datascience/notebook.functional.test.ts
Labels: skip news

#14147 Auto assign datascience issues
  .github/workflows/assignIssue.yml
  .github/workflows/week.js
Labels: skip news

#14153 Change name of event used to activate extension
  package.json
Labels: skip news

#14154 Escaping fix broke a number of things (#14145)
  src/client/datascience/jupyter/jupyterDebugger.ts
  src/datascience-ui/interactive-common/cellOutput.tsx
  src/test/datascience/notebook.functional.test.ts
Labels: skip news

#14158 Fixes to streamed output in native notebooks
  src/client/datascience/jupyter/kernels/cellExecution.ts
  src/test/datascience/notebook/executionService.ds.test.ts
Labels: skip news

#14159 Fixes to for escaping of output in native notebooks
  src/client/datascience/jupyter/kernels/cellExecution.ts
  src/test/datascience/notebook/executionService.ds.test.ts
  src/test/datascience/notebook/interrupRestart.ds.test.ts
Labels: skip news

#14161 Look for `data science` labels when auto assigning issues
  .github/workflows/assignIssue.yml
Labels: skip news

#14065 Environment info cache class
  src/client/pythonEnvironments/base/envsCache.ts
  src/client/pythonEnvironments/common/externalDependencies.ts
  src/client/pythonEnvironments/index.ts
  src/test/pythonEnvironments/base/envsCache.unit.test.ts
Labels: skip news

#14171 Merge point release back into main
  CHANGELOG.md
Labels: skip news
