Repository microsoft/vscode-python, pull requests merged in 2020-08, with the labels that each got.

#13194 bandit warnings pass 1
  pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py
  pythonFiles/vscode_datascience_helpers/dataframes/vscodeDataFrameHelpers.py
  pythonFiles/vscode_datascience_helpers/getJupyterVariableShape.py
  pythonFiles/vscode_datascience_helpers/getServerInfo.py
  pythonFiles/vscode_datascience_helpers/jupyter_daemon.py
  pythonFiles/vscode_datascience_helpers/kernel_launcher_daemon.py
Labels: skip news

#12529 Issue 12414 python interactive cell editing shortcuts
  news/1 Enhancements/12414.md
  package.json
  package.nls.json
  src/client/common/application/commands.ts
  src/client/datascience/cellFactory.ts
  src/client/datascience/cellMatcher.ts
  src/client/datascience/commands/commandRegistry.ts
  src/client/datascience/constants.ts
  src/client/datascience/editor-integration/codeLensFactory.ts
  src/client/datascience/editor-integration/codewatcher.ts
  src/client/datascience/types.ts
  src/client/telemetry/index.ts
  src/test/datascience/editor-integration/codewatcher.unit.test.ts
Labels: external contributor

#13243 Rename get to getOrCreateModel
  src/client/datascience/export/exportUtil.ts
  src/client/datascience/interactive-ipynb/trustCommandHandler.ts
  src/client/datascience/notebook/contentProvider.ts
  src/client/datascience/notebook/executionService.ts
  src/client/datascience/notebook/notebookEditorProvider.ts
  src/client/datascience/notebookStorage/nativeEditorProvider.ts
  src/client/datascience/notebookStorage/nativeEditorStorage.ts
  src/client/datascience/notebookStorage/notebookStorageProvider.ts
  src/client/datascience/types.ts
  src/test/datascience/export/exportUtil.test.ts
  src/test/datascience/interactive-common/trustCommandHandler.unit.test.ts
  src/test/datascience/interactive-ipynb/nativeEditorStorage.unit.test.ts
  src/test/datascience/notebook/contentProvider.unit.test.ts
Labels: skip news

#13244 Dispose notebook on close of VSC Notebooks
  src/client/datascience/interactive-common/notebookProvider.ts
  src/client/datascience/notebook/notebookDisposeService.ts
  src/client/datascience/notebook/serviceRegistry.ts
  src/client/datascience/types.ts
Labels: skip news

#13226 Add ESLint rules to the repo without enabling them
  .eslintignore
  .eslintrc
  build/.eslintrc
  package-lock.json
  package.json
Labels: skip news

#13246 Limit `python.languageServer` setting scope to `window`
  package.json
Labels: area-intellisense, internal contributor, skip news

#13273 Fix when clauses for new interactive cell shortcuts
  package.json
  package.nls.json
  src/client/common/utils/localize.ts
Labels: skip news

#13245 Support kernel selection in VSC Native Notebooks
  src/client/common/application/notebook.ts
  src/client/common/application/types.ts
  src/client/datascience/baseJupyterSession.ts
  src/client/datascience/jupyter/jupyterNotebook.ts
  src/client/datascience/jupyter/kernels/kernel.ts
  src/client/datascience/jupyter/kernels/kernelProvider.ts
  src/client/datascience/jupyter/kernels/kernelSelections.ts
  src/client/datascience/jupyter/kernels/kernelSelector.ts
  src/client/datascience/jupyter/kernels/types.ts
  src/client/datascience/jupyter/liveshare/guestJupyterNotebook.ts
  src/client/datascience/notebook/contentProvider.ts
  src/client/datascience/notebook/executionService.ts
  src/client/datascience/notebook/helpers/executionHelpers.ts
  src/client/datascience/notebook/helpers/helpers.ts
  src/client/datascience/notebook/integration.ts
  src/client/datascience/notebook/kernelProvider.ts
  src/client/datascience/notebook/notebookEditor.ts
  src/client/datascience/notebook/notebookEditorProvider.ts
  src/client/datascience/notebook/notebookKernel.ts
  src/client/datascience/notebook/serviceRegistry.ts
  src/client/datascience/notebookStorage/baseModel.ts
  src/client/datascience/notebookStorage/vscNotebookModel.ts
  src/client/datascience/types.ts
  src/test/datascience/mockJupyterNotebook.ts
  src/test/datascience/notebook/cellOutput.ds.test.ts
  src/test/datascience/notebook/contentProvider.unit.test.ts
  src/test/datascience/notebook/executionErrors.ds.test.ts
  src/test/datascience/notebook/executionService.ds.test.ts
  src/test/datascience/notebook/helper.ts
  src/test/datascience/notebook/helpers.unit.test.ts
  src/test/datascience/notebook/interrupRestart.ds.test.ts
  src/test/datascience/notebook/saving.ds.test.ts
  types/vscode-proposed/index.d.ts
  types/vscode.proposed.d.ts
  typings/vscode-proposed/index.d.ts
Labels: skip news

#13287 Update dependencies
  package-lock.json
  package.json
Labels: skip news

#13289 Fix nightly failures for remote and new registration test.
  src/client/datascience/jupyter/jupyterSession.ts
  src/test/datascience/jupyter/jupyterSession.unit.test.ts
  src/test/datascience/jupyterUriProviderRegistration.functional.test.ts
Labels: skip news

#13295 update to next month in master
  package-lock.json
  package.json
Labels: skip news

#13292 Fixes to trusting native notebooks
  src/client/datascience/notebook/kernelProvider.ts
  src/client/datascience/notebookStorage/vscNotebookModel.ts
  src/test/datascience/notebook/contentProvider.ds.test.ts
  src/test/datascience/notebook/testJsonContents.ipynb
Labels: skip news

#13293 Notebook undo command is same as standard undo cmd
  package.json
Labels: skip news

#13318 Revert "Notebook undo command is same as standard undo cmd (#13293)"
  package.json
Labels: skip news

#13297 Ensure we do not switch kernel if already the same
  src/client/datascience/jupyter/kernels/kernel.ts
  src/client/datascience/jupyter/kernels/kernelProvider.ts
  src/client/datascience/jupyter/kernels/types.ts
  src/client/datascience/notebook/helpers/executionHelpers.ts
  src/client/datascience/notebook/kernelProvider.ts
  src/client/datascience/notebook/notebookKernel.ts
Labels: skip news

#13296 Port gather survey and icon getting disabled while gathering
  CHANGELOG.md
  package.nls.json
  src/client/common/utils/localize.ts
  src/client/datascience/commands/commandRegistry.ts
  src/client/datascience/gather/gatherListener.ts
  src/client/datascience/interactive-common/interactiveWindowTypes.ts
  src/client/datascience/interactive-common/synchronization.ts
  src/datascience-ui/history-react/interactiveCell.tsx
  src/datascience-ui/history-react/interactivePanel.less
  src/datascience-ui/history-react/redux/reducers/index.ts
  src/datascience-ui/interactive-common/common.css
  src/datascience-ui/interactive-common/mainState.ts
  src/datascience-ui/interactive-common/redux/reducers/transfer.ts
  src/datascience-ui/interactive-common/redux/reducers/types.ts
  src/datascience-ui/native-editor/nativeCell.tsx
  src/datascience-ui/native-editor/nativeEditor.less
  src/datascience-ui/native-editor/redux/reducers/creation.ts
  src/datascience-ui/native-editor/redux/reducers/index.ts
  src/datascience-ui/react-common/image.tsx
  src/datascience-ui/react-common/images/Sync/sync-inverse.svg
  src/datascience-ui/react-common/images/Sync/sync.svg
  src/test/datascience/interactivePanel.functional.test.tsx
  src/test/datascience/mainState.unit.test.ts
Labels: skip news

#13346 Disable flakey CI test
  src/test/linters/lint.multilinter.test.ts
Labels: skip news

#13325 Fix a policheck warning.
  pythonFiles/testing_tools/adapter/__main__.py
Labels: skip news

#13334 Add cell navigation commands as well as a default set of keyboard bindings for most new interactive window cell commands
  package.json
  package.nls.json
  src/client/common/application/commands.ts
  src/client/datascience/commands/commandRegistry.ts
  src/client/datascience/constants.ts
  src/client/datascience/editor-integration/codewatcher.ts
  src/client/datascience/types.ts
  src/client/telemetry/index.ts
Labels: skip news

#13350 Port Flakey CI test disable
  src/test/linters/lint.multilinter.test.ts
Labels: skip news

#13348 Port cell navigation keyboard shortcuts to release
  package.json
  package.nls.json
  src/client/common/application/commands.ts
  src/client/datascience/commands/commandRegistry.ts
  src/client/datascience/constants.ts
  src/client/datascience/editor-integration/codewatcher.ts
  src/client/datascience/types.ts
  src/client/telemetry/index.ts
Labels: skip news

#13353 Autoscroll when extending cell select
  src/client/datascience/editor-integration/codewatcher.ts
Labels: skip news

#13354 Autoscroll when extending cell select (#13353)
  src/client/datascience/editor-integration/codewatcher.ts
Labels: skip news

#13368 Fix test in CI
  src/test/linters/lint.multilinter.test.ts
Labels: internal contributor, skip news

#13373 Fix raw kernel disposed problem
  src/client/datascience/interactive-common/interactiveBase.ts
Labels: skip news

#13384 Fix nyc unit test failures
  src/client/datascience/jupyter/jupyterExporter.ts
  src/client/datascience/notebookStorage/baseModel.ts
Labels: skip news

#13278 Revert #12795, "PyEnvs: Register proxies with the DI framework to replace @inectable usage."
  src/client/common/process/pythonExecutionFactory.ts
  src/client/common/terminal/environmentActivationProviders/pipEnvActivationProvider.ts
  src/client/interpreter/contracts.ts
  src/client/interpreter/helpers.ts
  src/client/interpreter/interpreterService.ts
  src/client/interpreter/locators/types.ts
  src/client/interpreter/virtualEnvs/index.ts
  src/client/pythonEnvironments/discovery/locators/helpers.ts
  src/client/pythonEnvironments/discovery/locators/index.ts
  src/client/pythonEnvironments/discovery/locators/progressService.ts
  src/client/pythonEnvironments/discovery/locators/services/KnownPathsService.ts
  src/client/pythonEnvironments/discovery/locators/services/baseVirtualEnvService.ts
  src/client/pythonEnvironments/discovery/locators/services/cacheableLocatorService.ts
  src/client/pythonEnvironments/discovery/locators/services/condaEnvFileService.ts
  src/client/pythonEnvironments/discovery/locators/services/condaEnvService.ts
  src/client/pythonEnvironments/discovery/locators/services/condaService.ts
  src/client/pythonEnvironments/discovery/locators/services/currentPathService.ts
  src/client/pythonEnvironments/discovery/locators/services/globalVirtualEnvService.ts
  src/client/pythonEnvironments/discovery/locators/services/hashProvider.ts
  src/client/pythonEnvironments/discovery/locators/services/hashProviderFactory.ts
  src/client/pythonEnvironments/discovery/locators/services/interpreterWatcherBuilder.ts
  src/client/pythonEnvironments/discovery/locators/services/pipEnvService.ts
  src/client/pythonEnvironments/discovery/locators/services/pipEnvServiceHelper.ts
  src/client/pythonEnvironments/discovery/locators/services/windowsRegistryService.ts
  src/client/pythonEnvironments/discovery/locators/services/windowsStoreInterpreter.ts
  src/client/pythonEnvironments/discovery/locators/services/workspaceVirtualEnvService.ts
  src/client/pythonEnvironments/discovery/locators/services/workspaceVirtualEnvWatcherService.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/interpreters/virtualEnvManager.unit.test.ts
  src/test/interpreters/virtualEnvs/index.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/hasProviderFactory.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/interpreterWatcherBuilder.unit.test.ts
  src/test/pythonEnvironments/legacyIOC.unit.test.ts
  src/test/testing/pytest/pytest.discovery.test.ts
  src/test/testing/pytest/pytest.run.test.ts
Labels: skip news

#13394 Remove control tower code for trusted notebooks
  package.json
  src/client/common/experiments/groups.ts
  src/client/datascience/interactive-common/interactiveWindowTypes.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/interactive-ipynb/trustCommandHandler.ts
  src/client/datascience/interactive-ipynb/trustService.ts
  src/datascience-ui/interactive-common/jupyterInfo.tsx
  src/datascience-ui/interactive-common/mainState.ts
  src/datascience-ui/interactive-common/redux/store.ts
  src/datascience-ui/native-editor/nativeEditor.tsx
  src/datascience-ui/native-editor/redux/reducers/creation.ts
  src/datascience-ui/native-editor/toolbar.tsx
  src/test/datascience/.vscode/settings.json
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/interactive-common/trustCommandHandler.unit.test.ts
  src/test/datascience/interactive-common/trustService.unit.test.ts
  src/test/datascience/interactivePanel.functional.test.tsx
  src/test/datascience/nativeEditor.toolbar.functional.test.tsx
  src/test/datascience/trustedNotebooks.functional.test.tsx
Labels: skip news

#13401 Update Release branch for August Release
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
  news/1 Enhancements/13252.md
  package-lock.json
  package.json
Labels: skip news

#13402 Refactor cell execution using IKernel
  src/client/datascience/jupyter/kernels/cellExecution.ts
  src/client/datascience/jupyter/kernels/kernel.ts
  src/client/datascience/jupyter/kernels/kernelExecution.ts
  src/client/datascience/jupyter/kernels/kernelProvider.ts
  src/client/datascience/jupyter/kernels/types.ts
  src/client/datascience/notebook/executionService.ts
  src/client/datascience/notebook/helpers/helpers.ts
  src/client/datascience/notebook/helpers/multiCancellationToken.ts
  src/client/datascience/notebook/kernelProvider.ts
  src/client/datascience/notebook/notebookDisposeService.ts
  src/client/datascience/notebook/notebookEditor.ts
  src/client/datascience/notebook/notebookEditorProvider.ts
  src/client/datascience/notebook/notebookKernel.ts
  src/client/datascience/notebook/serviceRegistry.ts
  src/client/datascience/notebook/types.ts
  src/client/datascience/notebookStorage/nativeEditorStorage.ts
  src/client/datascience/notebookStorage/notebookStorageProvider.ts
  src/client/datascience/notebookStorage/vscNotebookModel.ts
  src/client/datascience/types.ts
  src/test/datascience/notebook/executionErrors.ds.test.ts
  src/test/datascience/notebook/helper.ts
  src/test/datascience/notebook/interrupRestart.ds.test.ts
Labels: skip news

#13403 Ensure working directory is an actual directory
  src/client/datascience/jupyter/jupyterUtils.ts
  src/client/datascience/jupyter/liveshare/hostJupyterServer.ts
  src/client/datascience/kernel-launcher/kernelLauncherDaemon.ts
  src/client/datascience/raw-kernel/liveshare/hostRawNotebookProvider.ts
  src/test/datascience/interactiveWindow.functional.test.tsx
  src/test/datascience/nativeEditor.functional.test.tsx
  src/test/datascience/notebook.functional.test.ts
  src/test/datascience/uiTests/ipywidget.ui.functional.test.ts
Labels: skip news

#13407 Refactor KernelSelection type to include a `kind`
  src/client/datascience/jupyter/kernels/kernelExecution.ts
  src/client/datascience/jupyter/kernels/kernelSelections.ts
  src/client/datascience/jupyter/kernels/kernelSelector.ts
  src/client/datascience/jupyter/kernels/types.ts
  src/test/datascience/commands/notebookCommands.functional.test.ts
  src/test/datascience/jupyter/kernels/kernelSelections.unit.test.ts
  src/test/datascience/jupyter/kernels/kernelSelector.unit.test.ts
Labels: skip news

#13412 Merge release branch back to master
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
  news/1 Enhancements/13252.md
  package.json
Labels: skip news

#13414 Don't show trust message for IW
  src/datascience-ui/interactive-common/jupyterInfo.tsx
  src/test/datascience/interactivePanel.functional.test.tsx
Labels: skip news

#13417 Add binding for cell selection
  package.json
Labels: skip news

#13415 Release Plan Updates
  .github/release_plan.md
Labels: skip news

#13435 Update 1_ds_bug_report.md
  .github/ISSUE_TEMPLATE/1_ds_bug_report.md
Labels: skip news

#13416 Use KernelSelection instead of KernelSpecInterpreter
  src/client/common/application/commands.ts
  src/client/common/utils/localize.ts
  src/client/datascience/commands/notebookCommands.ts
  src/client/datascience/interactive-common/interactiveBase.ts
  src/client/datascience/interactive-common/notebookProvider.ts
  src/client/datascience/jupyter/jupyterExecution.ts
  src/client/datascience/jupyter/kernels/helpers.ts
  src/client/datascience/jupyter/kernels/kernel.ts
  src/client/datascience/jupyter/kernels/kernelExecution.ts
  src/client/datascience/jupyter/kernels/kernelSelections.ts
  src/client/datascience/jupyter/kernels/kernelSelector.ts
  src/client/datascience/jupyter/kernels/kernelSwitcher.ts
  src/client/datascience/jupyter/kernels/types.ts
  src/client/datascience/jupyter/liveshare/hostJupyterServer.ts
  src/client/datascience/notebook/kernelProvider.ts
  src/client/datascience/raw-kernel/liveshare/hostRawNotebookProvider.ts
  src/client/datascience/types.ts
  src/test/datascience/commands/notebookCommands.functional.test.ts
  src/test/datascience/execution.unit.test.ts
  src/test/datascience/jupyter/kernels/kernelSelections.unit.test.ts
  src/test/datascience/jupyter/kernels/kernelSelector.unit.test.ts
  src/test/datascience/jupyter/kernels/kernelSwitcher.unit.test.ts
  src/test/datascience/nativeEditor.functional.test.tsx
  src/test/testing/configuration.unit.test.ts
Labels: skip news

#13423 Update dependencies
  package-lock.json
  package.json
Labels: skip news

#13427 Skip flaky file stat test
  src/test/common/platform/filesystem.test.ts
Labels: skip news

#13452 Update ISSUE_TEMPLATE python.logging.level
  .github/ISSUE_TEMPLATE/1_ds_bug_report.md
Labels: external contributor, skip news

#13343 Adding docstrings to snippets
  news/1 Enhancements/5578.md
  snippets/python.json
Labels: external contributor

#13440 User KernelConnectionMetadata instead of KernelSpec+Interpreter
  src/client/datascience/baseJupyterSession.ts
  src/client/datascience/commands/notebookCommands.ts
  src/client/datascience/constants.ts
  src/client/datascience/interactive-common/interactiveBase.ts
  src/client/datascience/interactive-common/interactiveWindowTypes.ts
  src/client/datascience/interactive-common/notebookProvider.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/interactive-window/interactiveWindow.ts
  src/client/datascience/ipywidgets/localWidgetScriptSourceProvider.ts
  src/client/datascience/jupyter/jupyterExecution.ts
  src/client/datascience/jupyter/jupyterExporter.ts
  src/client/datascience/jupyter/jupyterImporter.ts
  src/client/datascience/jupyter/jupyterInvalidKernelError.ts
  src/client/datascience/jupyter/jupyterNotebook.ts
  src/client/datascience/jupyter/jupyterServer.ts
  src/client/datascience/jupyter/jupyterSession.ts
  src/client/datascience/jupyter/jupyterSessionManager.ts
  src/client/datascience/jupyter/kernelVariables.ts
  src/client/datascience/jupyter/kernels/helpers.ts
  src/client/datascience/jupyter/kernels/kernel.ts
  src/client/datascience/jupyter/kernels/kernelSelector.ts
  src/client/datascience/jupyter/kernels/kernelSwitcher.ts
  src/client/datascience/jupyter/kernels/types.ts
  src/client/datascience/jupyter/liveshare/guestJupyterNotebook.ts
  src/client/datascience/jupyter/liveshare/guestJupyterSessionManager.ts
  src/client/datascience/jupyter/liveshare/hostJupyterServer.ts
  src/client/datascience/jupyter/oldJupyterVariables.ts
  src/client/datascience/kernel-launcher/kernelLauncher.ts
  src/client/datascience/kernel-launcher/kernelProcess.ts
  src/client/datascience/kernel-launcher/types.ts
  src/client/datascience/notebook/helpers/helpers.ts
  src/client/datascience/notebook/kernelProvider.ts
  src/client/datascience/notebookStorage/baseModel.ts
  src/client/datascience/raw-kernel/liveshare/hostRawNotebookProvider.ts
  src/client/datascience/raw-kernel/rawJupyterSession.ts
  src/client/datascience/raw-kernel/rawKernel.ts
  src/client/datascience/types.ts
  src/test/datascience/commands/notebookCommands.functional.test.ts
  src/test/datascience/ipywidgets/localWidgetScriptSourceProvider.unit.test.ts
  src/test/datascience/jupyter/jupyterSession.unit.test.ts
  src/test/datascience/jupyter/kernels/kernelSelector.unit.test.ts
  src/test/datascience/jupyter/kernels/kernelSwitcher.unit.test.ts
  src/test/datascience/kernelLauncher.functional.test.ts
  src/test/datascience/mockJupyterManager.ts
  src/test/datascience/mockJupyterNotebook.ts
  src/test/datascience/mockJupyterServer.ts
  src/test/datascience/mockJupyterSession.ts
  src/test/datascience/nativeEditor.functional.test.tsx
  src/test/datascience/notebook/notebookStorage.unit.test.ts
  src/test/datascience/raw-kernel/rawKernel.functional.test.ts
Labels: skip news

#13478 Change kernel only if it is different
  src/client/datascience/notebook/integration.ts
  src/client/datascience/notebook/kernelProvider.ts
  src/client/datascience/types.ts
Labels: skip news

#13506 Use helper fn to check if two kernels are the same
  src/client/datascience/notebook/kernelProvider.ts
Labels: skip news

#13444 Implement merge environments
  src/client/interpreter/helpers.ts
  src/client/pythonEnvironments/info/index.ts
  src/client/pythonEnvironments/info/pythonVersion.ts
  src/test/pythonEnvironments/info/index.unit.test.ts
Labels: skip news

#13513 Fixes to preferred kernels in native notebooks
  src/client/datascience/jupyter/kernels/helpers.ts
  src/client/datascience/jupyter/kernels/kernel.ts
  src/client/datascience/jupyter/kernels/kernelExecution.ts
  src/client/datascience/jupyter/kernels/kernelProvider.ts
  src/client/datascience/jupyter/kernels/kernelSelector.ts
  src/client/datascience/jupyter/kernels/types.ts
  src/client/datascience/notebook/kernelProvider.ts
  src/test/datascience/jupyter/kernels/kernelSelector.unit.test.ts
Labels: skip news

#13511 Update LSP to latest to resolve problems with LS settings
  package-lock.json
  package.json
Labels: internal contributor, skip news

#13294 change language server from Jedi when creating native notebooks
  src/client/datascience/constants.ts
  src/client/datascience/jupyter/kernels/kernel.ts
Labels: skip news

#13525 change some function names
  src/client/datascience/jupyter/jupyterExecution.ts
  src/client/datascience/jupyter/kernels/kernelSelector.ts
  src/client/datascience/jupyter/liveshare/hostJupyterServer.ts
  src/client/datascience/notebook/kernelProvider.ts
  src/client/datascience/raw-kernel/liveshare/hostRawNotebookProvider.ts
  src/test/datascience/execution.unit.test.ts
  src/test/datascience/jupyter/kernels/kernelSelector.unit.test.ts
Labels: skip news

#13524 No empty cell for native notebooks
  src/client/datascience/jupyter/kernels/kernel.ts
  src/client/datascience/notebookStorage/nativeEditorStorage.ts
  src/client/datascience/notebookStorage/notebookStorageProvider.ts
  src/client/datascience/notebookStorage/vscNotebookModel.ts
Labels: skip news

#13527 Update NativeNotebook types in type definition
  src/client/datascience/interactive-ipynb/nativeEditorViewTracker.ts
  src/client/datascience/notebookStorage/baseModel.ts
  src/client/datascience/notebookStorage/nativeEditorStorage.ts
  src/client/datascience/notebookStorage/vscNotebookModel.ts
  src/test/datascience/nativeEditorViewTracker.unit.test.ts
  src/test/datascience/notebook/helper.ts
  src/test/datascience/notebook/rendererExension.unit.test.ts
  types/vscode-proposed/index.d.ts
  types/vscode.proposed.d.ts
  typings/vscode-proposed/index.d.ts
Labels: skip news

#13526 Add telemetry for `switch to Pylance` acceptance
  src/client/languageServices/proposeLanguageServerBanner.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/test/.vscode/settings.json
  src/test/testing/banners/proposeNewLanguageServerBanner.unit.test.ts
Labels: internal contributor, skip news

#13534 Split functional tests into per file so they don't run out of memory during failures
  .gitignore
  .vscode/launch.json
  build/ci/scripts/runFunctionalTests.js
  build/ci/templates/test_phases.yml
  build/ci/vscode-python-nightly-flake-ci.yaml
  build/ci/vscode-python-pr-validation.yaml
  package.json
  src/client/datascience/jupyter/jupyterServer.ts
  src/client/datascience/jupyter/jupyterSession.ts
  src/client/datascience/jupyter/liveshare/hostJupyterServer.ts
  src/test/common/platform/fs-temp.functional.test.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/jupyter/jupyterSession.unit.test.ts
  src/test/datascience/kernelLauncher.functional.test.ts
  src/test/datascience/notebook.functional.test.ts
  src/test/datascience/uiTests/notebookHelpers.ts
Labels: skip news

#13545 Fix ts failure
  src/client/datascience/notebook/helpers/helpers.ts
Labels: skip news

#13537 Update version and change log for bug fix release
  CHANGELOG.md
  package-lock.json
  package.json
  package.nls.json
  src/client/common/utils/localize.ts
  src/client/languageServices/proposeLanguageServerBanner.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/datascience-ui/interactive-common/jupyterInfo.tsx
  src/datascience-ui/react-common/image.tsx
  src/test/.vscode/settings.json
  src/test/testing/banners/proposeNewLanguageServerBanner.unit.test.ts
Labels: skip news

#13574 Merge release back into master
  CHANGELOG.md
  news/1 Enhancements/13177.md
  news/2 Fixes/13543.md
Labels: skip news

#13583 Set CI_PYTHON_VERSION to point to matrix python in GHA
  .github/workflows/insiders.yml
Labels: skip news

#13585 Disable execSelectionInTerminal if notebook is active
  package.json
Labels: skip news

#13528 Add a helper for chaining async iterators.
  src/client/common/utils/async.ts
  src/test/common/utils/async.unit.test.ts
Labels: skip news

#13576 keybindings/cell manipulation parity
  package.json
  package.nls.json
  src/client/common/application/commands.ts
  src/client/datascience/commands/notebookCommands.ts
  src/client/datascience/constants.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/notebook/notebookEditor.ts
  src/client/datascience/types.ts
Labels: skip news

#13494 Suppress stdout from cython layer
  news/2 Fixes/11729.md
  pythonFiles/testing_tools/adapter/util.py
  pythonFiles/tests/testing_tools/adapter/pytest/test_discovery.py
Labels: external contributor

#13592 In Azure Pipelines, run with 'main' everywhere 'master' is
  build/ci/performance/vscode-python-performance.yaml
  build/ci/templates/steps/build.yml
  build/ci/vscode-python-ci-static-analysis.yaml
  build/ci/vscode-python-ci.yaml
  build/ci/vscode-python-nightly-ci.yaml
  build/ci/vscode-python-nightly-flake-ci.yaml
  build/ci/vscode-python-pr-validation.yaml
Labels: skip news

#13558 Fix the scoping of our ESLint rules
  .eslintignore
  .eslintrc
  .prettierignore
  src/ipywidgets/.vscode/settings.json
Labels: skip news

#13604 Specify that blob storage is authorized via az login
  .github/workflows/insiders.yml
Labels: skip news

#13607 Fix an input for codecov-action step for passing in the codecov token
  .github/workflows/insiders.yml
Labels: skip news

#13625 Format using latest black
  pythonFiles/completion.py
  pythonFiles/refactor.py
  pythonFiles/tests/debug_adapter/test_install_debugpy.py
  pythonFiles/tests/testing_tools/adapter/pytest/test_cli.py
  pythonFiles/tests/testing_tools/adapter/pytest/test_discovery.py
  pythonFiles/tests/testing_tools/adapter/test___main__.py
  pythonFiles/tests/testing_tools/adapter/test_discovery.py
  pythonFiles/tests/testing_tools/adapter/test_report.py
  pythonFiles/tests/testing_tools/adapter/test_util.py
  pythonFiles/vscode_datascience_helpers/daemon/__main__.py
  pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py
  pythonFiles/vscode_datascience_helpers/dataframes/vscodeDataFrameHelpers.py
  pythonFiles/vscode_datascience_helpers/getServerInfo.py
  pythonFiles/vscode_datascience_helpers/kernel_launcher.py
  pythonFiles/vscode_datascience_helpers/kernel_launcher_daemon.py
  pythonFiles/vscode_datascience_helpers/win_interrupt.py
Labels: skip news

#13615 Specify the storage account name when interacting with Azure Blob Storage
  .github/workflows/insiders.yml
Labels: skip news

#13629 Static analysis exceptions
  build/ci/static_analysis/credscan/CredScanSuppressions.json
  build/ci/static_analysis/policheck/exceptions.mdb
Labels: skip news

#13633 Fix suppression pattern for credscan
  build/ci/static_analysis/credscan/CredScanSuppressions.json
Labels: skip news

#13610 Update changelog and version for point release.
  CHANGELOG.md
  package-lock.json
  package.json
  pythonFiles/completion.py
  pythonFiles/refactor.py
  pythonFiles/tests/debug_adapter/test_install_debugpy.py
  pythonFiles/tests/testing_tools/adapter/pytest/test_cli.py
  pythonFiles/tests/testing_tools/adapter/pytest/test_discovery.py
  pythonFiles/tests/testing_tools/adapter/test___main__.py
  pythonFiles/tests/testing_tools/adapter/test_discovery.py
  pythonFiles/tests/testing_tools/adapter/test_report.py
  pythonFiles/tests/testing_tools/adapter/test_util.py
  pythonFiles/vscode_datascience_helpers/daemon/__main__.py
  pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py
  pythonFiles/vscode_datascience_helpers/dataframes/vscodeDataFrameHelpers.py
  pythonFiles/vscode_datascience_helpers/getServerInfo.py
  pythonFiles/vscode_datascience_helpers/kernel_launcher.py
  pythonFiles/vscode_datascience_helpers/kernel_launcher_daemon.py
  pythonFiles/vscode_datascience_helpers/win_interrupt.py
  src/client/common/application/commands.ts
  src/client/common/experiments/groups.ts
  src/client/common/experiments/service.ts
  src/client/common/types.ts
  src/client/datascience/gather/gatherLogger.ts
  src/client/datascience/interactive-ipynb/nativeEditorOldWebView.ts
  src/client/datascience/interactive-ipynb/nativeEditorProviderOld.ts
  src/client/datascience/notebookStorage/nativeEditorProvider.ts
  src/client/datascience/notebookStorage/nativeEditorStorage.ts
  src/client/interpreter/display/interpreterSelectionTip.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/datascience-ui/history-react/interactivePanel.tsx
  src/datascience-ui/interactive-common/jupyterInfo.tsx
  src/datascience-ui/interactive-common/redux/store.ts
  src/datascience-ui/native-editor/toolbar.tsx
  src/test/common/experiments/service.unit.test.ts
  src/test/datascience/interactive-ipynb/nativeEditorStorage.unit.test.ts
  src/test/datascience/mountedWebView.ts
  src/test/datascience/nativeEditor.functional.test.tsx
  src/test/datascience/testHelpers.tsx
  src/test/datascience/testNativeEditorProvider.ts
  src/test/interpreters/display/interpreterSelectionTip.unit.test.ts
Labels: skip news

#13632 Add IInterpreterHashProviderFactory to the ioc container
  src/client/interpreter/locators/types.ts
  src/client/pythonEnvironments/discovery/locators/services/hashProviderFactory.ts
  src/test/datascience/dataScienceIocContainer.ts
Labels: skip news

#13439 Remove "no-reload" from debug configurations by default
  news/1 Enhancements/13061.md
  src/client/debugger/extension/configuration/providers/djangoLaunch.ts
  src/client/debugger/extension/configuration/providers/flaskLaunch.ts
  src/test/debugger/extension/configuration/providers/djangoLaunch.unit.test.ts
  src/test/debugger/extension/configuration/providers/flaskLaunch.unit.test.ts
Labels: external contributor

#13386 Use worker pool to get environment info
  package-lock.json
  package.json
  src/client/common/utils/workerPool.ts
  src/client/extensionInit.ts
  src/client/pythonEnvironments/common/externalDependencies.ts
  src/client/pythonEnvironments/info/environmentInfoService.ts
  src/client/pythonEnvironments/info/index.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/common/utils/workerPool.functional.test.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/format/extension.format.test.ts
  src/test/pythonEnvironments/info/environmentInfoService.functional.test.ts
  src/test/pythonEnvironments/legacyIOC.unit.test.ts
  src/test/serviceRegistry.ts
  src/test/testing/nosetest/nosetest.disovery.test.ts
  src/test/testing/pytest/pytest.discovery.test.ts
  src/test/testing/pytest/pytest.run.test.ts
  src/test/testing/unittest/unittest.discovery.test.ts
  src/test/testing/unittest/unittest.run.test.ts
Labels: skip news

#13631 Stop mv from complaining about renaming the VSIX to the same name
  .github/workflows/insiders.yml
  .github/workflows/release.yml
Labels: skip news

#13468 fixed typo in activaiton events
  news/2 Fixes/13612.md
  package.json
Labels: external contributor

#13650 Skip flaky virtual env tests
  src/test/pythonEnvironments/discovery/locators/workspaceVirtualEnvService.test.ts
Labels: skip news

#13653 Add install telemetry
  src/client/extensionActivation.ts
  src/client/telemetry/extensionInstallTelemetry.ts
  src/client/telemetry/index.ts
  src/test/telemetry/extensionInstallTelemetery.unit.test.ts
Labels: skip news

#13669 Disable flakey JupyterServerUriProvider test
  src/test/datascience/jupyterUriProviderRegistration.functional.test.ts
Labels: skip news

#13666 Cherry picks, change log, and version update for point release.
  CHANGELOG.md
  package-lock.json
  package.json
  src/client/extensionActivation.ts
  src/client/telemetry/extensionInstallTelemetry.ts
  src/client/telemetry/index.ts
  src/test/telemetry/extensionInstallTelemetery.unit.test.ts
Labels: skip news

#13671 Set up a configuration for dependabot
  .github/dependabot.yml
Labels: skip news

#13613 Fix autofixable ESLint warnings
  .eslintignore
  .eslintrc
  src/client/pythonEnvironments/discovery/globalenv.ts
  src/client/pythonEnvironments/discovery/locators/helpers.ts
  src/client/pythonEnvironments/discovery/locators/index.ts
  src/client/pythonEnvironments/discovery/locators/progressService.ts
  src/client/pythonEnvironments/discovery/locators/services/KnownPathsService.ts
  src/client/pythonEnvironments/discovery/locators/services/baseVirtualEnvService.ts
  src/client/pythonEnvironments/discovery/locators/services/cacheableLocatorService.ts
  src/client/pythonEnvironments/discovery/locators/services/conda.ts
  src/client/pythonEnvironments/discovery/locators/services/condaEnvFileService.ts
  src/client/pythonEnvironments/discovery/locators/services/condaEnvService.ts
  src/client/pythonEnvironments/discovery/locators/services/condaHelper.ts
  src/client/pythonEnvironments/discovery/locators/services/condaService.ts
  src/client/pythonEnvironments/discovery/locators/services/currentPathService.ts
  src/client/pythonEnvironments/discovery/locators/services/globalVirtualEnvService.ts
  src/client/pythonEnvironments/discovery/locators/services/hashProvider.ts
  src/client/pythonEnvironments/discovery/locators/services/hashProviderFactory.ts
  src/client/pythonEnvironments/discovery/locators/services/interpreterWatcherBuilder.ts
  src/client/pythonEnvironments/discovery/locators/services/pipEnvService.ts
  src/client/pythonEnvironments/discovery/locators/services/pipEnvServiceHelper.ts
  src/client/pythonEnvironments/discovery/locators/services/windowsRegistryService.ts
  src/client/pythonEnvironments/discovery/locators/services/windowsStoreInterpreter.ts
  src/client/pythonEnvironments/discovery/locators/services/workspaceVirtualEnvService.ts
  src/client/pythonEnvironments/discovery/locators/services/workspaceVirtualEnvWatcherService.ts
  src/client/pythonEnvironments/discovery/subenv.ts
  src/client/pythonEnvironments/exec.ts
  src/client/pythonEnvironments/info/environmentInfoService.ts
  src/client/pythonEnvironments/info/index.ts
  src/client/pythonEnvironments/info/interpreter.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/pythonEnvironments/discovery/locators/cacheableLocatorService.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/condaEnvFileService.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/condaEnvService.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/condaHelper.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/condaService.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/hasProviderFactory.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/hashProvider.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/helpers.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/index.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/interpreterFilter.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/interpreterLocatorService.testvirtualenvs.ts
  src/test/pythonEnvironments/discovery/locators/interpreterWatcherBuilder.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/knownPathService.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/pipEnvService.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/progressService.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/venv.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/windowsRegistryService.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/windowsStoreInterpreter.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/workspaceVirtualEnvService.test.ts
  src/test/pythonEnvironments/discovery/locators/workspaceVirtualEnvService.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/workspaceVirtualEnvWatcherService.unit.test.ts
  src/test/pythonEnvironments/discovery/subenv.unit.test.ts
  src/test/pythonEnvironments/info/environmentInfoService.functional.test.ts
  src/test/pythonEnvironments/info/index.unit.test.ts
  src/test/pythonEnvironments/info/interpreter.unit.test.ts
  src/test/pythonEnvironments/legacyIOC.unit.test.ts
Labels: skip news

#13591 Add generic utils: DeepReadonly<T> and VersionInfo.
  src/client/common/utils/misc.ts
  src/client/common/utils/regexp.ts
  src/client/common/utils/version.ts
  src/test/common/utils/version.unit.test.ts
Labels: skip news
