Repository microsoft/vscode-python, pull requests merged in 2020-01, with the labels that each got.

#9354 Skip a few platform-related tests for CI failures (for now).
  src/test/common/platform/filesystem.functional.test.ts
  src/test/common/platform/utils.ts
Labels: skip news

#9249 Attach to process quick pick - Windows support
  src/client/debugger/extension/adapter/activator.ts
  src/client/debugger/extension/attachQuickPick/baseProvider.ts
  src/client/debugger/extension/attachQuickPick/factory.ts
  src/client/debugger/extension/attachQuickPick/provider.ts
  src/client/debugger/extension/attachQuickPick/psProcessParser.ts
  src/client/debugger/extension/attachQuickPick/psProvider.ts
  src/client/debugger/extension/attachQuickPick/types.ts
  src/client/debugger/extension/attachQuickPick/wmicProcessParser.ts
  src/test/debugger/extension/adapter/activator.unit.test.ts
  src/test/debugger/extension/attachQuickPick/baseProvider.unit.test.ts
  src/test/debugger/extension/attachQuickPick/factory.unit.test.ts
  src/test/debugger/extension/attachQuickPick/provider.unit.test.ts
  src/test/debugger/extension/attachQuickPick/psProcessParser.unit.test.ts
  src/test/debugger/extension/attachQuickPick/psProvider.unit.test.ts
  src/test/debugger/extension/attachQuickPick/wmicProcessParser.unit.test.ts
Labels: skip news

#9253 Remove ipywidgets
  src/ipywidgets/.gitignore
  src/ipywidgets/.prettierrc.js
  src/ipywidgets/.vscode/settings.json
  src/ipywidgets/README.md
  src/ipywidgets/package-lock.json
  src/ipywidgets/package.json
  src/ipywidgets/scripts/copyBuild.js
  src/ipywidgets/scripts/copyfiles.js
  src/ipywidgets/src/index.ts
  src/ipywidgets/src/manager.ts
  src/ipywidgets/src/widgetLoader.ts
  src/ipywidgets/src/widgets.css
  src/ipywidgets/tsconfig.json
  src/ipywidgets/tslint.json
  src/ipywidgets/webpack.config.js
Labels: skip news

#9351 Increase extension activation time and handle errors
  src/test/constants.ts
  src/test/index.ts
  src/test/testRunner.ts
Labels: skip news

#9362 Pipeline changes to check if code is formatted using prettier
  .vscode/extensions.json
  CODING_STANDARDS.md
  CONTRIBUTING.md
  build/ci/templates/jobs/build_compile.yml
Labels: skip news

#9364 If sockets are not supported, do not run socket test
  src/test/common/platform/filesystem.test.ts
Labels: skip news

#9276 Refactor kernel selectors and related code into separate classes
  src/client/common/application/commands.ts
  src/client/datascience/commands/commandRegistry.ts
  src/client/datascience/commands/kernelSwitcher.ts
  src/client/datascience/commands/serverSelector.ts
  src/client/datascience/constants.ts
  src/client/datascience/datascience.ts
  src/client/datascience/interactive-common/interactiveBase.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/interactive-window/interactiveWindow.ts
  src/client/datascience/jupyter/jupyterNotebook.ts
  src/client/datascience/jupyter/kernels/kernelSwitcher.ts
  src/client/datascience/jupyter/liveshare/guestJupyterNotebook.ts
  src/client/datascience/jupyter/serverSelector.ts
  src/client/datascience/serviceRegistry.ts
  src/client/datascience/types.ts
  src/test/datascience/cellFactory.unit.test.ts
  src/test/datascience/cellMatcher.unit.test.ts
  src/test/datascience/commands/commandRegistry.unit.test.ts
  src/test/datascience/commands/kernelSwitcher.unit.test.ts
  src/test/datascience/commands/serverSelector.unit.test.ts
  src/test/datascience/common.unit.test.ts
  src/test/datascience/datascience.unit.test.ts
  src/test/datascience/execution.unit.test.ts
  src/test/datascience/inputHistory.unit.test.ts
  src/test/datascience/interactive-ipynb/nativeEditor.unit.test.ts
  src/test/datascience/jupyter/kernels/kernelSwitcher.unit.test.ts
  src/test/datascience/jupyter/serverSelector.unit.test.ts
  src/test/datascience/jupyterUtils.unit.test.ts
  src/test/datascience/mainState.unit.test.ts
Labels: skip news

#9371 Fix Multiroot Environment Variables Provider test
  src/test/common/variables/envVarsProvider.multiroot.test.ts
Labels: skip news

#9375 add plotly to manual test file
  src/test/datascience/manualTestFiles/manualTestFile.py
Labels: skip news

#9381 Set needs IPythonReqs to true for nightly builds
  build/ci/vscode-python-nightly-ci.yaml
Labels: skip news

#9380 Fixes for node 12.4.0
  src/client/common/terminal/shellDetector.ts
  src/test/datascience/interactiveWindow.functional.test.tsx
  src/test/datascience/nativeEditor.functional.test.tsx
Labels: skip news

#9400 When checking if `kernelspec` subcommand is available, use subprocess
  pythonFiles/datascience/getJupyterKernels.py
  pythonFiles/datascience/jupyter_daemon.py
  src/client/datascience/jupyter/jupyterCommand.ts
Labels: skip news

#9382 Sort python processes first
  src/client/debugger/extension/attachQuickPick/provider.ts
  src/test/debugger/extension/attachQuickPick/provider.unit.test.ts
Labels: skip news

#9408 Restore disabled PythonExecutionFactory tests
  src/test/common/process/pythonExecutionFactory.unit.test.ts
Labels: skip news

#9411 Sort using the processName key instead of label
  src/client/debugger/extension/attachQuickPick/provider.ts
  src/client/debugger/extension/attachQuickPick/psProcessParser.ts
  src/client/debugger/extension/attachQuickPick/types.ts
  src/client/debugger/extension/attachQuickPick/wmicProcessParser.ts
  src/test/debugger/extension/attachQuickPick/provider.unit.test.ts
  src/test/debugger/extension/attachQuickPick/psProcessParser.unit.test.ts
  src/test/debugger/extension/attachQuickPick/wmicProcessParser.unit.test.ts
Labels: skip news

#9422 Disable Standard Debugging tests of ports and hosts
  src/test/debugger/portAndHost.test.ts
Labels: skip news

#9429 Fixes to webpack script when bundling DS code
  build/webpack/webpack.datascience-ui.config.js
Labels: skip news

#8913 Turn DebugAdapterFactory experiments on for all users and PtvsdWheels experiment for 20% of users
  experiments.json
Labels: skip news

#9352 Factor out path-related classes for better testing.
  src/client/common/platform/constants.ts
  src/client/common/platform/fileSystem.ts
  src/client/common/platform/fs-paths.ts
  src/client/common/platform/pathUtils.ts
  src/client/common/platform/types.ts
  src/client/common/types.ts
  src/test/common/platform/filesystem.functional.test.ts
  src/test/common/platform/filesystem.test.ts
  src/test/common/platform/filesystem.unit.test.ts
  src/test/common/platform/fs-paths.functional.test.ts
  src/test/common/platform/fs-paths.unit.test.ts
  src/test/common/platform/pathUtils.functional.test.ts
  src/test/common/platform/pathUtils.test.ts
  src/test/common/platform/utils.ts
Labels: skip news

#9454 Bypass conda service when creating daemons
  src/client/datascience/jupyter/notebookStarter.ts
Labels: skip news

#9467 More places in DS code to bypass conda run
  src/client/datascience/jupyter/jupyterCommand.ts
  src/client/datascience/jupyter/jupyterCommandFinder.ts
Labels: skip news

#9465 Prep for point release
  CHANGELOG.md
  news/2 Fixes/9420.md
  news/2 Fixes/9437.md
  news/2 Fixes/9439.md
  news/2 Fixes/9444.md
  package.json
Labels: skip news

#9471 Add support for find in notebook editor
  news/1 Enhancements/9470.md
  src/client/common/application/webPanels/webPanel.ts
Labels: skip news

#9468 Be clearer about our direct dependencies from our transient ones for Python
  requirements.in
  requirements.txt
Labels: skip news

#9498 Cherry pick fixes and update change logs
  CHANGELOG.md
  build/ci/templates/steps/build.yml
  build/ci/templates/test_phases.yml
  gulpfile.js
  news/1 Enhancements/9470.md
  pythonFiles/install_ptvsd.py
Labels: skip news

#9451 changed some pixel and % measurements to em
  src/datascience-ui/interactive-common/common.css
  src/datascience-ui/interactive-common/kernelSelection.tsx
  src/datascience-ui/native-editor/nativeEditor.tsx
Labels: skip news

#9413 Double feedback target group size
  experiments.json
Labels: skip news

#9529 Fix all of the nightly flake failures (well since I last sync'd master)
  src/client/common/process/pythonProcess.ts
  src/client/interpreter/interpreterService.ts
  src/test/common/process/pythonProcess.unit.test.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/nativeEditor.functional.test.tsx
  src/test/datascience/notebook.functional.test.ts
  src/test/datascience/testHelpers.tsx
Labels: skip news

#9530 Cherry pick conda and mypy into release-2019.12
  news/2 Fixes/9490.md
  news/2 Fixes/9496.md
  src/client/common/process/pythonExecutionFactory.ts
  src/client/linters/mypy.ts
  src/test/common/process/condaExecutionService.unit.test.ts
  src/test/common/process/pythonExecutionFactory.unit.test.ts
  src/test/linters/lint.args.test.ts
  src/test/linters/mypy.unit.test.ts
Labels: skip news

#9536 For point release - update change logs.
  CHANGELOG.md
  news/2 Fixes/9490.md
  news/2 Fixes/9496.md
Labels: skip news

#9542 Move jupyter command finder into interpreter dir
  src/client/datascience/jupyter/interpreter/README.md
  src/client/datascience/jupyter/interpreter/jupyterCommand.ts
  src/client/datascience/jupyter/interpreter/jupyterCommandFinder.ts
  src/client/datascience/jupyter/jupyterExecution.ts
  src/client/datascience/jupyter/kernels/kernelService.ts
  src/client/datascience/jupyter/notebookStarter.ts
  src/client/datascience/serviceRegistry.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/execution.unit.test.ts
  src/test/datascience/jupyter/kernels/kernelService.unit.test.ts
  src/test/datascience/notebook.functional.test.ts
Labels: skip news

#9570 Bump version in master
  package.json
Labels: skip news

#9569 First step on improving perf of the variable explorer
  package-lock.json
  package.json
  src/client/common/types.ts
  src/client/datascience/constants.ts
  src/client/datascience/jupyter/interpreter/jupyterCommandFinder.ts
  src/client/datascience/jupyter/jupyterNotebook.ts
  src/client/datascience/jupyter/jupyterSession.ts
  src/client/datascience/jupyter/jupyterVariables.ts
  src/client/datascience/jupyter/liveshare/guestJupyterNotebook.ts
  src/client/datascience/jupyter/liveshare/hostJupyterNotebook.ts
  src/client/datascience/types.ts
  src/datascience-ui/react-common/settingsReactSide.ts
  src/test/common/configSettings/configSettings.unit.test.ts
  src/test/datascience/color.test.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/editor-integration/codewatcher.unit.test.ts
  src/test/datascience/execution.unit.test.ts
  src/test/datascience/helpers.ts
  src/test/datascience/interactiveWindowCommandListener.unit.test.ts
  src/test/datascience/jupyterVariables.unit.test.ts
  src/test/datascience/mockJupyterSession.ts
Labels: skip news

#9565 Configuring single interpreter for jupyter server
  package.json
  package.nls.json
  src/client/common/application/commands.ts
  src/client/common/installer/productInstaller.ts
  src/client/common/installer/productNames.ts
  src/client/common/installer/productService.ts
  src/client/common/types.ts
  src/client/common/utils/localize.ts
  src/client/datascience/constants.ts
  src/client/datascience/jupyter/interpreter/jupyterInterpreterConfiguration.ts
  src/client/datascience/jupyter/interpreter/jupyterInterpreterSelectionCommand.ts
  src/client/datascience/jupyter/interpreter/jupyterInterpreterSelector.ts
  src/client/datascience/jupyter/interpreter/jupyterInterpreterService.ts
  src/client/datascience/jupyter/interpreter/jupyterInterpreterStateStore.ts
  src/client/datascience/serviceRegistry.ts
  src/client/telemetry/index.ts
  src/test/common/installer.test.ts
  src/test/common/installer/installer.invalidPath.unit.test.ts
  src/test/common/installer/installer.unit.test.ts
  src/test/datascience/jupyter/interpreter/jupyterInterpreterConfiguration.unit.test.ts
  src/test/datascience/jupyter/interpreter/jupyterInterpreterSelectionCommand.unit.test.ts
  src/test/datascience/jupyter/interpreter/jupyterInterpreterSelector.unit.test.ts
  src/test/datascience/jupyter/interpreter/jupyterInterpreterService.unit.test.ts
  src/test/datascience/jupyter/interpreter/jupyterInterpreterStateStore.unit.test.ts
Labels: skip news

#9573 Migrate older cached jupyter interpreter to new solution
  package.nls.json
  src/client/common/utils/localize.ts
  src/client/datascience/constants.ts
  src/client/datascience/jupyter/interpreter/jupyterInterpreterConfiguration.ts
  src/client/datascience/jupyter/interpreter/jupyterInterpreterOldCacheStateStore.ts
  src/client/datascience/jupyter/interpreter/jupyterInterpreterSelector.ts
  src/client/datascience/jupyter/interpreter/jupyterInterpreterService.ts
  src/client/datascience/serviceRegistry.ts
  src/client/telemetry/index.ts
  src/test/datascience/jupyter/interpreter/jupyterInterpreterConfiguration.unit.test.ts
  src/test/datascience/jupyter/interpreter/jupyterInterpreterSelector.unit.test.ts
  src/test/datascience/jupyter/interpreter/jupyterInterpreterService.unit.test.ts
Labels: skip news

#9418 Active editor context keys with appropriate events
  src/client/datascience/activation.ts
  src/client/datascience/constants.ts
  src/client/datascience/context/activeEditorContext.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/interactive-ipynb/nativeEditorProvider.ts
  src/client/datascience/interactive-window/interactiveWindow.ts
  src/client/datascience/interactive-window/interactiveWindowProvider.ts
  src/client/datascience/serviceRegistry.ts
  src/client/datascience/types.ts
  src/test/datascience/activation.unit.test.ts
  src/test/datascience/testInteractiveWindowProvider.ts
  src/test/datascience/testNativeEditorProvider.ts
Labels: skip news

#9588 Move command finder and related behind a class
  package.nls.json
  src/client/datascience/jupyter/interpreter/jupyterCommandInterpreterExecutionService.ts
  src/client/datascience/jupyter/jupyterExecution.ts
  src/client/datascience/jupyter/jupyterExecutionFactory.ts
  src/client/datascience/jupyter/kernels/kernelService.ts
  src/client/datascience/jupyter/liveshare/guestJupyterExecution.ts
  src/client/datascience/jupyter/liveshare/hostJupyterExecution.ts
  src/client/datascience/jupyter/notebookStarter.ts
  src/client/datascience/serviceRegistry.ts
  src/client/datascience/types.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/execution.unit.test.ts
  src/test/datascience/jupyter/interpreter/jupyterCommandInterpreterExecutionService.unit.test.ts
  src/test/datascience/jupyter/kernels/kernelService.unit.test.ts
Labels: skip news

#9616 Skip having sources in our index_bundle
  .vscodeignore
  build/webpack/webpack.datascience-ui.config.builder.js
  gulpfile.js
Labels: skip news

#9419 Explicitly clarify the difference between unit and system test files
  CONTRIBUTING.md
Labels: external contributor, skip news

#9615 Add helpers for identifying "system" errors.
  src/client/common/platform/errors.ts
  src/test/common/platform/errors.unit.test.ts
  src/test/common/platform/utils.ts
  src/test/vscode-mock.ts
Labels: skip news

#9625 Switch to a global jupyter interpreter
  package.nls.json
  src/client/common/types.ts
  src/client/common/utils/localize.ts
  src/client/datascience/jupyter/interpreter/jupyterInterpreterDependencyService.ts
  src/client/datascience/jupyter/interpreter/jupyterInterpreterSubCommandExecutionService.ts
  src/client/datascience/jupyter/jupyterConnection.ts
  src/client/datascience/serviceRegistry.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/errorHandler.functional.test.tsx
  src/test/datascience/jupyter/interpreter/jupyterInterpreterDependencyService.unit.test.ts
  src/test/datascience/jupyter/jupyterConnection.unit.test.ts
  src/test/datascience/mockJupyterManager.ts
  src/test/datascience/notebook.functional.test.ts
Labels: skip news

#9587 Added system tests to ensure we are getting all conda environments
  build/ci/templates/test_phases.yml
  src/client/interpreter/serviceRegistry.ts
  src/test/interpreters/locators/interpreterLocatorService.testvirtualenvs.ts
  src/test/serviceRegistry.ts
  src/test/standardTest.ts
Labels: skip news

#9455 Factor out the tempfile-related code.
  src/client/common/platform/fileSystem.ts
  src/client/common/platform/fs-temp.ts
  src/client/common/platform/types.ts
  src/test/common/platform/filesystem.functional.test.ts
  src/test/common/platform/fs-temp.functional.test.ts
  src/test/common/platform/fs-temp.unit.test.ts
Labels: skip news

#9695 Fix nightly flake tests
  build/ci/vscode-python-nightly-flake-ci.yaml
  src/test/datascience/dataviewer.functional.test.tsx
  src/test/datascience/notebook.functional.test.ts
Labels: skip news

#9697 Drop FileSystem.getRealPath().
  src/client/common/platform/fileSystem.ts
  src/client/common/platform/fs-paths.ts
  src/client/common/platform/types.ts
  src/test/common/platform/filesystem.functional.test.ts
  src/test/common/platform/fs-paths.functional.test.ts
  src/test/configuration/interpreterSelector.unit.test.ts
Labels: skip news

#9700 Add doc comment explaining why CondaEnvFileService cannot be removed
  src/client/interpreter/locators/services/condaEnvFileService.ts
Labels: skip news

#9680 Update navigate to file icons on test explorer
  resources/dark/open-file.svg
  resources/light/open-file.svg
Labels: skip news

#9704 Make proper unit tests for EnvironmentVariablesService.
  src/client/common/variables/environment.ts
  src/test/common/variables/envVarsService.functional.test.ts
  src/test/common/variables/envVarsService.unit.test.ts
Labels: skip news

#9717 Change view name in text explorer from PYTHON to Python
  package.json
Labels: skip news

#9727 Remove line by line read of requirements file in installPythonRequirements
  gulpfile.js
Labels: in review, skip news

#9728 Ensure environment variables are always strings in launch.json
  news/2 Fixes/9568.md
  package.json
Labels: in review

#9723 Auto discover tests on interpreter change
  src/client/testing/main.ts
Labels: skip news

#9739 Use options object in terminal methods
  src/client/common/terminal/activator/base.ts
  src/client/common/terminal/activator/index.ts
  src/client/common/terminal/factory.ts
  src/client/common/terminal/helper.ts
  src/client/common/terminal/service.ts
  src/client/common/terminal/syncTerminalService.ts
  src/client/common/terminal/types.ts
  src/client/common/utils/misc.ts
  src/client/common/variables/environmentVariablesProvider.ts
  src/client/common/variables/types.ts
  src/client/providers/terminalProvider.ts
  src/client/terminals/activation.ts
  src/test/common/terminals/activation.unit.test.ts
  src/test/common/terminals/activator/base.unit.test.ts
  src/test/common/terminals/activator/index.unit.test.ts
  src/test/common/terminals/service.unit.test.ts
  src/test/mocks/vsc/extHostedTypes.ts
  src/test/providers/terminal.unit.test.ts
Labels: skip news

#9706 Slow roll out for local web server for notebook
  experiments.json
  package.json
  src/client/common/experimentGroups.ts
  src/client/datascience/data-viewing/dataViewer.ts
  src/client/datascience/interactive-common/interactiveBase.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/interactive-window/interactiveWindow.ts
  src/client/datascience/plotting/plotViewer.ts
  src/client/datascience/webViewHost.ts
  src/test/datascience/interactive-ipynb/nativeEditor.unit.test.ts
Labels: skip news

#9742 Format Python files with Black
  pythonFiles/completion.py
  pythonFiles/datascience/daemon/__main__.py
  pythonFiles/datascience/daemon/daemon_output.py
  pythonFiles/datascience/daemon/daemon_python.py
  pythonFiles/datascience/dummyJupyter.py
  pythonFiles/datascience/getJupyterKernels.py
  pythonFiles/datascience/getJupyterVariableDataFrameInfo.py
  pythonFiles/datascience/getJupyterVariableDataFrameRows.py
  pythonFiles/datascience/getJupyterVariableList.py
  pythonFiles/datascience/getJupyterVariableValue.py
  pythonFiles/datascience/getServerInfo.py
  pythonFiles/datascience/jupyter_daemon.py
  pythonFiles/datascience/jupyter_nbInstalled.py
  pythonFiles/install_ptvsd.py
  pythonFiles/interpreterInfo.py
  pythonFiles/normalizeForInterpreter.py
  pythonFiles/ptvsd_launcher.py
  pythonFiles/refactor.py
  pythonFiles/shell_exec.py
  pythonFiles/sortImports.py
  pythonFiles/symbolProvider.py
  pythonFiles/testing_tools/adapter/__main__.py
  pythonFiles/testing_tools/adapter/discovery.py
  pythonFiles/testing_tools/adapter/errors.py
  pythonFiles/testing_tools/adapter/info.py
  pythonFiles/testing_tools/adapter/pytest/_cli.py
  pythonFiles/testing_tools/adapter/pytest/_discovery.py
  pythonFiles/testing_tools/adapter/pytest/_pytest_item.py
  pythonFiles/testing_tools/adapter/report.py
  pythonFiles/testing_tools/adapter/util.py
  pythonFiles/testing_tools/run_adapter.py
  pythonFiles/testlauncher.py
  pythonFiles/tests/debug_adapter/test_install_ptvsd.py
  pythonFiles/tests/ipython/scripts.py
  pythonFiles/tests/ipython/test_variables.py
  pythonFiles/tests/run_all.py
  pythonFiles/tests/test_normalize_for_interpreter.py
  pythonFiles/tests/testing_tools/adapter/pytest/test_cli.py
  pythonFiles/tests/testing_tools/adapter/pytest/test_discovery.py
  pythonFiles/tests/testing_tools/adapter/test___main__.py
  pythonFiles/tests/testing_tools/adapter/test_discovery.py
  pythonFiles/tests/testing_tools/adapter/test_functional.py
  pythonFiles/tests/testing_tools/adapter/test_report.py
  pythonFiles/tests/testing_tools/adapter/test_util.py
  pythonFiles/tests/util.py
  pythonFiles/visualstudio_py_testlauncher.py
Labels: skip news

#9754 Remove unused steps/build_compile.yml
  build/ci/templates/steps/build_compile.yml
Labels: skip news

#9732 Remove DebugAdapterDescriptor experiment check
  src/client/api.ts
  src/client/datascience/jupyter/jupyterDebugger.ts
  src/client/debugger/extension/adapter/activator.ts
  src/client/debugger/extension/adapter/factory.ts
  src/client/debugger/extension/configuration/resolvers/attach.ts
  src/client/debugger/extension/configuration/resolvers/launchConfigExperiment.ts
  src/test/debugger/attach.ptvsd.test.ts
  src/test/debugger/extension/adapter/activator.unit.test.ts
  src/test/debugger/extension/configuration/resolvers/attach.unit.test.ts
  src/test/debugger/extension/configuration/resolvers/launchConfigExperiments.unit.test.ts
Labels: in review, skip news

#9757 Fix install requirements gulp task
  gulpfile.js
Labels: skip news

#9499 Factor out RawFileSystem.
  src/client/common/platform/fileSystem.ts
  src/client/common/platform/types.ts
  src/test/common/platform/filesystem.functional.test.ts
  src/test/common/platform/filesystem.test.ts
  src/test/common/platform/filesystem.unit.test.ts
  src/test/common/variables/envVarsService.functional.test.ts
  src/test/common/variables/envVarsService.test.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/serviceRegistry.ts
Labels: skip news

#9784 Drop PlatformService as a dependency of FileSystem.
  src/client/common/platform/fileSystem.ts
  src/client/common/utils/localize.ts
  src/client/sourceMapSupport.ts
  src/test/common/crypto.unit.test.ts
  src/test/common/net/fileDownloader.unit.test.ts
  src/test/common/platform/filesystem.functional.test.ts
  src/test/common/platform/filesystem.test.ts
  src/test/common/terminals/environmentActivationProviders/terminalActivation.testvirtualenvs.ts
  src/test/common/variables/envVarsService.functional.test.ts
  src/test/common/variables/envVarsService.test.ts
  src/test/common/webPanel/webPanel.unit.test.ts
  src/test/datascience/color.test.ts
  src/test/interpreters/condaService.unit.test.ts
  src/test/linters/lint.functional.test.ts
  src/test/serviceRegistry.ts
  src/test/sourceMapSupport.test.ts
  src/test/testing/display/picker.functional.test.ts
  src/test/testing/pytest/pytest.testMessageService.test.ts
Labels: skip news

#9788 New run above and below icons
  src/datascience-ui/react-common/images/RunAbove/runabove-inverse.svg
  src/datascience-ui/react-common/images/RunAbove/runabove.svg
  src/datascience-ui/react-common/images/RunBelow/runbelow-inverse.svg
  src/datascience-ui/react-common/images/RunBelow/runbelow.svg
Labels: skip news

#9793 Remove monaco styles from plot and df viewer
  src/client/datascience/interactive-common/interactiveWindowTypes.ts
  src/datascience-ui/react-common/styleInjector.tsx
Labels: skip news

#9800 Fix the return value for FileSystem.isReadOnly().
  src/client/common/installer/moduleInstaller.ts
  src/client/common/platform/fileSystem.ts
  src/test/common/installer/moduleInstaller.unit.test.ts
  src/test/common/platform/filesystem.functional.test.ts
Labels: skip news

#9759 Cache interpreter environment variables in a file
  src/client/common/crypto.ts
  src/client/common/types.ts
  src/client/interpreter/activation/preWarmVariables.ts
  src/client/interpreter/activation/service.ts
  src/client/interpreter/activation/wrapperEnvironmentActivationService.ts
  src/test/common/crypto.unit.test.ts
  src/test/interpreters/activation/preWarmVariables.unit.test.ts
  src/test/interpreters/activation/wrapperEnvironmentActivationService.unit.test.ts
Labels: skip news

#9804 Split bundles for webview using webpack
  .vscodeignore
  build/webpack/common.js
  build/webpack/webpack.datascience-ui-dataExplorer.config.js
  build/webpack/webpack.datascience-ui-dataExplorerChunked.config.js
  build/webpack/webpack.datascience-ui-interactiveWindow.config.js
  build/webpack/webpack.datascience-ui-interactiveWindowChunked.config.js
  build/webpack/webpack.datascience-ui-notebooks.config.js
  build/webpack/webpack.datascience-ui-plotViewer.config.js
  build/webpack/webpack.datascience-ui-plotViewerChunked.config.js
  build/webpack/webpack.datascience-ui-viewers.config.js
  build/webpack/webpack.datascience-ui.config.builder.js
  build/webpack/webpack.datascience-ui.config.js
  gulpfile.js
  package-lock.json
  package.json
  src/client/common/application/webPanels/webPanel.ts
  src/client/datascience/data-viewing/dataViewer.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/interactive-window/interactiveWindow.ts
  src/client/datascience/plotting/plotViewer.ts
  src/client/datascience/webViewHost.ts
  src/datascience-ui/common/index.css
  src/datascience-ui/common/main.ts
  src/datascience-ui/data-explorer/index.tsx
  src/datascience-ui/history-react/index.css
  src/datascience-ui/history-react/index.tsx
  src/datascience-ui/native-editor/index.css
  src/datascience-ui/native-editor/index.tsx
  src/datascience-ui/plot/index.css
  src/datascience-ui/plot/index.tsx
Labels: skip news

#9824 Add ds branches for pr validation
  build/ci/vscode-python-pr-validation.yaml
Labels: skip news

#9823 Clean fs resources in the background
  src/client/common/platform/fileSystem.ts
Labels: skip news

#9818 Closes the file stream once the tracker is done
  src/client/debugger/extension/adapter/logging.ts
Labels: skip news

#9825 Perf improvements to react dev experience
  build/webpack/webpack.datascience-ui.config.builder.js
Labels: skip news

#9827 Remove all uses of static methods of Logger class
  src/client/application/diagnostics/checks/powerShellActivation.ts
  src/client/common/logger.ts
  src/client/interpreter/locators/services/cacheableLocatorService.ts
  src/client/interpreter/locators/services/condaService.ts
  src/client/interpreter/locators/services/workspaceVirtualEnvWatcherService.ts
  src/client/providers/jediProxy.ts
Labels: skip news

#9834 Update README to list all available translations
  README.md
Labels: skip news

#9836 Double test timeout for linter multiroot tests
  src/test/linters/lint.multiroot.test.ts
Labels: skip news

#9833 Ids of new cells must be provided to actions
  src/client/datascience/interactive-common/interactiveWindowTypes.ts
  src/datascience-ui/history-react/redux/mapping.ts
  src/datascience-ui/interactive-common/redux/reducers/types.ts
  src/datascience-ui/native-editor/redux/actions.ts
  src/datascience-ui/native-editor/redux/mapping.ts
  src/datascience-ui/native-editor/redux/reducers/creation.ts
  src/datascience-ui/native-editor/redux/reducers/execution.ts
Labels: skip news

#9839 Use new filesystem in DataScience functional tests
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/mockFileSystem.ts
  src/test/serviceRegistry.ts
Labels: skip news

#9808 Factor out FileSystemUtils
  src/client/common/platform/fileSystem.ts
  src/client/common/platform/types.ts
  src/test/common/platform/filesystem.functional.test.ts
  src/test/common/platform/filesystem.test.ts
  src/test/common/platform/filesystem.unit.test.ts
  src/test/serviceRegistry.ts
Labels: skip news

#9841 Increase timeout for often failing test hooks
  src/test/interpreters/locators/interpreterLocatorService.testvirtualenvs.ts
  src/test/testing/debugger.test.ts
  src/test/testing/rediscover.test.ts
Labels: skip news

#9844 Obliterate Logger class from existence
  src/client/activation/jedi.ts
  src/client/application/diagnostics/applicationDiagnostics.ts
  src/client/common/installer/productInstaller.ts
  src/client/common/logger.ts
  src/client/common/serviceRegistry.ts
  src/client/common/types.ts
  src/client/datascience/codeCssGenerator.ts
  src/client/datascience/interactive-window/interactiveWindowCommandListener.ts
  src/client/datascience/jupyter/interpreter/jupyterCommandFinder.ts
  src/client/datascience/themeFinder.ts
  src/client/debugger/extension/banner.ts
  src/client/interpreter/locators/services/condaEnvFileService.ts
  src/client/interpreter/locators/services/condaEnvService.ts
  src/client/interpreter/locators/services/condaService.ts
  src/client/interpreter/locators/services/pipEnvService.ts
  src/client/linters/baseLinter.ts
  src/client/linters/errorHandlers/baseErrorHandler.ts
  src/client/linters/errorHandlers/notInstalled.ts
  src/client/linters/errorHandlers/standard.ts
  src/client/linters/linterManager.ts
  src/client/linters/prospector.ts
  src/client/linters/pydocstyle.ts
  src/client/providers/importSortProvider.ts
  src/client/providers/jediProxy.ts
  src/client/testing/common/argumentsHelper.ts
  src/client/testing/common/managers/testConfigurationManager.ts
  src/client/testing/main.ts
  src/client/testing/unittest/runner.ts
  src/test/application/diagnostics/applicationDiagnostics.unit.test.ts
  src/test/common/installer.test.ts
  src/test/common/installer/installer.unit.test.ts
  src/test/common/moduleInstaller.test.ts
  src/test/common/process/pythonProc.simple.multiroot.test.ts
  src/test/common/serviceRegistry.unit.test.ts
  src/test/datascience/color.test.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/execution.unit.test.ts
  src/test/datascience/interactiveWindowCommandListener.unit.test.ts
  src/test/debugger/extension/banner.unit.test.ts
  src/test/interpreters/condaEnvFileService.unit.test.ts
  src/test/interpreters/condaEnvService.unit.test.ts
  src/test/interpreters/condaService.unit.test.ts
  src/test/interpreters/pipEnvService.unit.test.ts
  src/test/linters/common.ts
  src/test/linters/lint.args.test.ts
  src/test/linters/pylint.test.ts
  src/test/serviceRegistry.ts
  src/test/testing/argsService.test.ts
  src/test/testing/common/argsHelper.unit.test.ts
  src/test/testing/nosetest/nosetest.argsService.unit.test.ts
  src/test/testing/pytest/pytest.argsService.unit.test.ts
  src/test/testing/unittest/unittest.argsService.unit.test.ts
  src/test/testing/unittest/unittest.unit.test.ts
Labels: skip news
