Repository microsoft/vscode-python, pull requests merged in 2020-06, with the labels that each got.

#12087 Tests to ensure we close nb when VSC is closed
  src/client/datascience/notebook/notebookEditor.ts
  src/test/datascience/notebook/executionWithJupyter.ds.test.ts
  src/test/datascience/notebook/notebookEditorProvider.ds.test.ts
Labels: skip news

#12034 Allow LS to be bundled, versioned
  .gitignore
  .vscodeignore
  src/client/activation/common/downloader.ts
  src/client/activation/common/languageServerFolderService.ts
  src/client/activation/languageServer/languageServerFolderService.ts
  src/client/activation/node/languageServerFolderService.ts
  src/client/activation/node/languageServerProxy.ts
  src/client/activation/types.ts
  src/test/activation/languageServer/downloader.unit.test.ts
  src/test/activation/languageServer/languageServerFolderService.unit.test.ts
  src/test/activation/languageServer/languageServerPackageService.test.ts
  src/test/activation/languageServer/languageServerPackageService.unit.test.ts
  src/test/activation/node/languageServerFolderService.unit.test.ts
  src/test/common/nuget/azureBobStoreRepository.functional.test.ts
Labels: skip news

#12045 Expose API to show DS Data Viewer component from external extension
  src/client/api.ts
  src/client/datascience/data-viewing/dataViewer.ts
  src/client/datascience/data-viewing/dataViewerFactory.ts
  src/client/datascience/data-viewing/jupyterVariableDataProvider.ts
  src/client/datascience/data-viewing/jupyterVariableDataProviderFactory.ts
  src/client/datascience/data-viewing/types.ts
  src/client/datascience/interactive-common/interactiveBase.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/interactive-ipynb/nativeEditorOldWebView.ts
  src/client/datascience/interactive-window/interactiveWindow.ts
  src/client/datascience/serviceRegistry.ts
  src/client/datascience/types.ts
  src/datascience-ui/data-explorer/cellFormatter.tsx
  src/datascience-ui/data-explorer/mainPanel.tsx
  src/datascience-ui/data-explorer/reactSlickGrid.tsx
  src/test/datascience/data-viewing/dataViewer.unit.test.ts
  src/test/datascience/data-viewing/dataViewerProvider.unit.test.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/dataviewer.functional.test.tsx
Labels: skip news

#12092 Add ability to sync INotebookModel with cell text edits
  src/client/common/application/notebook.ts
  src/client/common/application/types.ts
  src/client/common/constants.ts
  src/client/common/utils/misc.ts
  src/client/datascience/notebook/cellEditSyncService.ts
  src/client/datascience/notebook/serviceRegistry.ts
  src/test/datascience/notebook/cellEditSyncService.ds.test.ts
  src/test/datascience/notebook/edit.ds.test.ts
  src/test/datascience/notebook/interrupRestart.ds.test.ts
Labels: skip news

#12089 Support notebook completion doc strings in .ipynb files
  src/client/activation/common/activatorBase.ts
  src/client/activation/node/activator.ts
Labels: skip news

#12095 Let VSCode translate ascii/terminal characters in output
  src/client/datascience/notebook/helpers.ts
  src/test/datascience/notebook/helpers.unit.test.ts
Labels: skip news

#12104 Use openWith command to open notebooks
  src/client/common/application/commands.ts
  src/client/common/application/customEditorService.ts
  src/client/common/application/types.ts
  src/client/datascience/interactive-ipynb/nativeEditorProvider.ts
  src/client/datascience/notebook/constants.ts
  src/client/datascience/notebook/notebookEditorProvider.ts
  src/test/datascience/interactive-ipynb/nativeEditorProvider.functional.test.ts
  src/test/datascience/mockCustomEditorService.ts
  src/test/datascience/notebook/notebookEditorProvider.ds.test.ts
Labels: skip news

#12086 Save variable explorer height persistently
  src/client/datascience/interactive-common/interactiveBase.ts
  src/client/datascience/interactive-common/interactiveWindowTypes.ts
  src/client/datascience/interactive-common/synchronization.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/interactive-ipynb/nativeEditorOldWebView.ts
  src/client/datascience/interactive-ipynb/nativeEditorStorage.ts
  src/client/datascience/interactive-window/interactiveWindow.ts
  src/datascience-ui/history-react/interactivePanel.tsx
  src/datascience-ui/history-react/redux/actions.ts
  src/datascience-ui/interactive-common/redux/reducers/types.ts
  src/datascience-ui/interactive-common/redux/reducers/variables.ts
  src/datascience-ui/interactive-common/variableExplorer.tsx
  src/datascience-ui/interactive-common/variablePanel.tsx
  src/datascience-ui/native-editor/nativeEditor.tsx
  src/datascience-ui/native-editor/redux/actions.ts
  src/datascience-ui/native-editor/toolbar.tsx
  src/test/datascience/interactivePanel.functional.test.tsx
  src/test/datascience/nativeEditor.toolbar.functional.test.tsx
Labels: skip news

#12106 Cancelling should invoke a single interrupt
  src/client/datascience/interactive-ipynb/nativeEditorCommandListener.ts
  src/client/datascience/notebook/executionService.ts
  src/test/datascience/notebook/helper.ts
  src/test/datascience/notebook/interrupRestart.ds.test.ts
Labels: skip news

#12111 Fix raw kernel running other languages
  .vscode/settings.json
  src/client/common/application/commands.ts
  src/client/datascience/commands/kernelSwitcher.ts
  src/client/datascience/interactive-common/interactiveBase.ts
  src/client/datascience/interactive-common/notebookProvider.ts
  src/client/datascience/jupyter/jupyterExecution.ts
  src/client/datascience/jupyter/kernels/kernelSwitcher.ts
  src/client/datascience/kernel-launcher/kernelLauncher.ts
  src/client/datascience/kernel-launcher/kernelProcess.ts
  src/client/datascience/types.ts
  src/datascience-ui/interactive-common/kernelSelection.tsx
  src/test/datascience/commands/kernelSwitcher.unit.test.ts
  src/test/datascience/interactive-common/notebookProvider.unit.test.ts
  src/test/datascience/jupyter/kernels/kernelSwitcher.unit.test.ts
  src/test/datascience/kernelLauncher.functional.test.ts
  src/test/datascience/nativeEditor.functional.test.tsx
  src/test/datascience/raw-kernel/rawKernel.functional.test.ts
Labels: skip news

#12061 Replace typo unitest to unittest.
  news/3 Code Health/10919.md
  src/test/.vscode/tags
  src/test/pythonFiles/testFiles/unittestsWithConfigs/other/test_pytest.py
  src/test/pythonFiles/testFiles/unittestsWithConfigs/other/test_unittest_one.py
  src/test/pythonFiles/testFiles/unittestsWithConfigs/pytest.ini
  src/test/pythonFiles/testFiles/unittestsWithConfigs/test_root.py
  src/test/pythonFiles/testFiles/unittestsWithConfigs/tests/test_another_pytest.py
  src/test/pythonFiles/testFiles/unittestsWithConfigs/tests/test_pytest.py
  src/test/pythonFiles/testFiles/unittestsWithConfigs/tests/test_unittest_one.py
  src/test/pythonFiles/testFiles/unittestsWithConfigs/tests/test_unittest_two.py
  src/test/pythonFiles/testFiles/unittestsWithConfigs/tests/unittest_three_test.py
  src/test/testing/common/trackEnablement.unit.test.ts
  src/test/testing/pytest/pytest.discovery.test.ts
Labels: external contributor

#12126 Updates to cell status displayed in VS Code Notebooks
  src/client/datascience/interactive-ipynb/nativeEditorStorage.ts
  src/client/datascience/notebook/executionHelpers.ts
  src/client/datascience/notebook/executionService.ts
  src/client/datascience/notebook/helpers.ts
  src/test/datascience/notebook/contentProvider.unit.test.ts
  src/test/datascience/notebook/executionService.ds.test.ts
  src/test/datascience/notebook/helper.ts
  src/test/datascience/notebook/helpers.unit.test.ts
  src/test/datascience/notebook/interrupRestart.ds.test.ts
  types/@jupyterlab_coreutils_nbformat.d.ts
Labels: skip news

#12132 Small fix for variable explorer resizing feature
  src/datascience-ui/interactive-common/redux/reducers/variables.ts
Labels: skip news, type-bug

#11908 Enable testing of the new debug adapter.
  build/ci/vscode-python-pr-validation.yaml
  src/test/.vscode/launch.json
  src/test/.vscode/launch.json.README
  src/test/common/platform/utils.ts
  src/test/debugger/attach.ptvsd.test.ts
  src/test/debugger/extension/adapter/adapter.test.ts
  src/test/debugger/misc.test.ts
  src/test/debugger/portAndHost.test.ts
  src/test/debugger/run.test.ts
  src/test/debugger/utils.ts
  src/test/fixtures.ts
  src/test/proc.ts
  src/test/pythonFiles/debugging/wait_for_file.py
  src/test/smoke/debugger.smoke.test.ts
Labels: skip news

#12134 Include error in status and persist exec times
  src/client/datascience/notebook/executionHelpers.ts
  src/client/datascience/notebook/executionService.ts
  src/client/datascience/notebook/helpers.ts
  src/test/common.ts
  src/test/datascience/notebook/contentProvider.unit.test.ts
  src/test/datascience/notebook/helper.ts
  src/test/datascience/notebook/helpers.unit.test.ts
  src/test/datascience/notebook/saving.ds.test.ts
  types/@jupyterlab_coreutils_nbformat.d.ts
Labels: skip news

#12151 Add deprecation message for ptvsdDistPath
  package.json
Labels: skip news

#12026 Fix remote self cert problem
  src/client/common/process/pythonExecutionFactory.ts
  src/client/common/utils/async.ts
  src/client/datascience/jupyter/jupyterNotebook.ts
  src/client/datascience/jupyter/jupyterServer.ts
  src/client/datascience/jupyter/jupyterSessionManager.ts
  src/client/datascience/jupyter/kernels/kernelSelector.ts
  src/client/datascience/jupyter/kernels/kernelService.ts
  src/client/datascience/jupyter/liveshare/hostJupyterExecution.ts
  src/client/datascience/jupyter/liveshare/hostJupyterServer.ts
  src/client/datascience/jupyter/liveshare/serverCache.ts
  src/client/datascience/liveshare/postOffice.ts
  src/client/datascience/themeFinder.ts
  src/client/interpreter/interpreterService.ts
  src/client/ioc/container.ts
  src/client/ioc/serviceManager.ts
  src/client/ioc/types.ts
  src/test/common/process/pythonExecutionFactory.unit.test.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/nativeEditor.functional.test.tsx
  src/test/datascience/notebook.functional.test.ts
  src/test/datascience/serverConfigFiles/remotePassword.py
Labels: skip news

#12156 add start page to experiment, and fix a color
  package.json
  src/client/common/experiments/service.ts
  src/client/common/startPage/startPage.ts
  src/client/common/startPage/types.ts
  src/client/datascience/commands/commandRegistry.ts
  src/client/datascience/constants.ts
  src/datascience-ui/startPage/startPage.css
  src/datascience-ui/startPage/startPage.tsx
  src/test/datascience/commands/commandRegistry.unit.test.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/startPage/startPage.unit.test.ts
  src/test/vscode-mock.ts
Labels: skip news

#12171 Update version and changelog for point release
  CHANGELOG.md
  news/1 Enhancements/10790.md
  news/2 Fixes/11943.md
  news/3 Code Health/11597.md
  package-lock.json
  package.json
Labels: skip news

#12191 Stable way to get script path for split bundles
  src/client/datascience/notebook/renderer.ts
  src/datascience-ui/renderers/index.tsx
  src/datascience-ui/renderers/main.ts
  src/datascience-ui/renderers/pvscDummy.ts
Labels: skip news

#12190 Update change log
  CHANGELOG.md
  news/2 Fixes/12177.md
Labels: skip news

#12197 Fix the variable based tests to search for the appropriate values
  src/test/datascience/variableTestHelpers.ts
Labels: skip news

#12198 Cherry pick fix for hasInterpreters and update change log
  CHANGELOG.md
  src/client/application/diagnostics/checks/pythonInterpreter.ts
  src/test/application/diagnostics/checks/pythonInterpreter.unit.test.ts
Labels: skip news

#12209 Update master to july dev version
  package-lock.json
  package.json
Labels: skip news

#12204 Add tests for notebook cell manipulations
  src/test/datascience/notebook/edit.ds.test.ts
  src/test/datascience/notebook/helper.ts
Labels: skip news

#12192 Turn pythonpath experiment on to 10% of users
  experiments.json
Labels: skip news

#12116 Refactor LinterId from string union to an enum
  news/3 Code Health/12116.md
  src/client/linters/constants.ts
  src/client/linters/linterInfo.ts
  src/client/linters/linterManager.ts
  src/client/linters/types.ts
  src/test/linters/lint.functional.test.ts
  src/test/linters/linter.availability.unit.test.ts
  src/test/linters/mypy.unit.test.ts
Labels: external contributor

#12222 Port custom editor changes to release branch
  .vscode/launch.json
  CHANGELOG.md
  customEditor.json
  experiments.json
  package-lock.json
  package.json
  package.nls.json
  src/client/common/application/customEditorService.ts
  src/client/common/application/notebook.ts
  src/client/common/application/types.ts
  src/client/common/experiments/groups.ts
  src/client/common/utils/localize.ts
  src/client/datascience/common.ts
  src/client/datascience/interactive-common/synchronization.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/interactive-ipynb/nativeEditorProvider.ts
  src/client/datascience/interactive-ipynb/nativeEditorProviderOld.ts
  src/client/datascience/interactive-ipynb/nativeEditorStorage.ts
  src/client/datascience/interactive-ipynb/nativeEditorViewTracker.ts
  src/client/datascience/interactive-ipynb/notebookModelEditEvent.ts
  src/client/datascience/interactive-ipynb/notebookStorageProvider.ts
  src/client/datascience/jupyter/jupyterConnection.ts
  src/client/datascience/jupyter/jupyterExecutionFactory.ts
  src/client/datascience/jupyterDebugService.ts
  src/client/datascience/kernel-launcher/kernelProcess.ts
  src/client/datascience/liveshare/postOffice.ts
  src/client/datascience/multiplexingDebugService.ts
  src/client/datascience/serviceRegistry.ts
  src/client/datascience/types.ts
  src/client/testing/explorer/testTreeViewProvider.ts
  src/datascience-ui/interactive-common/redux/helpers.ts
  src/datascience-ui/native-editor/redux/reducers/creation.ts
  src/datascience-ui/native-editor/redux/reducers/index.ts
  src/test/datascience/activation.unit.test.ts
  src/test/datascience/datascienceSurveyBanner.unit.test.ts
  src/test/datascience/interactive-ipynb/nativeEditorProvider.functional.test.ts
  src/test/datascience/interactive-ipynb/nativeEditorStorage.unit.test.ts
  src/test/datascience/mockCustomEditorService.ts
  src/test/datascience/mockQuickPick.ts
  src/test/datascience/nativeEditor.functional.test.tsx
  src/test/datascience/nativeEditorViewTracker.unit.test.ts
  src/test/mocks/vsc/extHostedTypes.ts
  src/test/mocks/vsc/index.ts
Labels: skip news

#12223 Port run by line stepping fix to release
  CHANGELOG.md
  src/client/datascience/interactive-ipynb/nativeEditorRunByLineListener.ts
Labels: skip news

#12229 Fix ipywidget and other test flakiness (hopefully)
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/interactive-ipynb/nativeEditorProvider.ts
  src/client/datascience/interactive-ipynb/nativeEditorProviderOld.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/nativeEditor.functional.test.tsx
  src/test/datascience/raw-kernel/rawKernel.functional.test.ts
  src/test/datascience/uiTests/notebookHelpers.ts
Labels: skip news

#12248 Disable broken tests
  src/test/pythonEnvironments/discovery/locators/windowsRegistryService.unit.test.ts
Labels: skip news

#12251 Remove font awesome from bundle
  build/webpack/webpack.datascience-ui.config.builder.js
Labels: skip news

#12259 Update to change log and version
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip news

#12270 Modify package.json to run ds tests with VSCNotebook
  package.json
  src/client/common/experiments/manager.ts
  src/test/datascience/.vscode/settings.json
  src/test/datascience/dsTestSetup.ts
  src/test/datascience/notebook/executionService.ds.test.ts
  src/test/datascience/notebook/helper.ts
  src/test/datascience/notebook/interrupRestart.ds.test.ts
  src/test/datascience/notebook/saving.ds.test.ts
Labels: skip news

#12279 Update gh- issues to github links
  src/client/common/platform/constants.ts
  src/client/common/platform/fileSystem.ts
  src/client/common/platform/pathUtils.ts
  src/client/common/platform/types.ts
  src/client/common/process/pythonEnvironment.ts
  src/client/common/types.ts
  src/client/extensionActivation.ts
  src/test/common.ts
  src/test/common/platform/filesystem.functional.test.ts
  src/test/language/languageConfiguration.unit.test.ts
  src/test/languageServers/jedi/autocomplete/base.test.ts
  src/test/languageServers/jedi/definitions/hover.jedi.test.ts
  src/test/linters/lint.test.ts
  src/test/testing/common/xUnitParser.unit.test.ts
Labels: skip news

#12290 Fix nightly flake tests some more
  src/client/datascience/editor-integration/cellhashprovider.ts
  src/client/datascience/interactive-common/interactiveBase.ts
  src/client/datascience/interactive-common/interactiveWindowTypes.ts
  src/client/interpreter/interpreterService.ts
  src/datascience-ui/interactive-common/redux/store.ts
  src/test/datascience/notebook.functional.test.ts
  src/test/datascience/uiTests/notebookUi.ts
Labels: skip news

#12282 Cherry-pick fixes from master to june release
  CHANGELOG.md
  package.json
  src/client/common/interpreterPathService.ts
  src/client/telemetry/index.ts
  src/test/common/interpreterPathService.unit.test.ts
Labels: skip news

#12295 Replace LS bundling with extension API
  .gitignore
  src/client/activation/common/downloader.ts
  src/client/activation/common/languageServerFolderService.ts
  src/client/activation/node/languageClientFactory.ts
  src/client/activation/node/languageServerFolderService.ts
  src/client/activation/types.ts
  src/test/activation/languageServer/downloader.unit.test.ts
  src/test/activation/languageServer/languageServerFolderService.unit.test.ts
  src/test/activation/node/languageServerFolderService.unit.test.ts
Labels: skip news

#12296 Changes to VSCode Notebook cell to INotebookModel cell mapping
  src/client/common/application/types.ts
  src/client/datascience/kernel-launcher/types.ts
  src/client/datascience/notebook/cellEditSyncService.ts
  src/client/datascience/notebook/contentProvider.ts
  src/client/datascience/notebook/executionService.ts
  src/client/datascience/notebook/helpers/cellMappers.ts
  src/client/datascience/notebook/helpers/cellUpdateHelpers.ts
  src/client/datascience/notebook/helpers/executionHelpers.ts
  src/client/datascience/notebook/helpers/helpers.ts
  src/client/datascience/notebook/integration.ts
  src/client/datascience/notebook/notebookEditorProvider.ts
  src/client/datascience/notebook/renderer.ts
  src/test/datascience/notebook/contentProvider.ds.test.ts
  src/test/datascience/notebook/contentProvider.unit.test.ts
  src/test/datascience/notebook/edit.ds.test.ts
  src/test/datascience/notebook/executionService.ds.test.ts
  src/test/datascience/notebook/helper.ts
  src/test/datascience/notebook/helpers.unit.test.ts
  src/test/datascience/notebook/saving.ds.test.ts
  src/test/datascience/notebook/test.png
  src/test/datascience/notebook/withOutput.ipynb
Labels: skip news

#12301 Single experiment group for nb editors
  experiments.json
  package.json
  src/client/common/application/notebook.ts
  src/client/common/experiments/groups.ts
  src/client/common/experiments/manager.ts
  src/client/datascience/context/activeEditorContext.ts
  src/client/datascience/notebook/cellEditSyncService.ts
  src/client/datascience/notebook/integration.ts
  src/client/datascience/serviceRegistry.ts
  src/test/common/experiments/manager.unit.test.ts
Labels: skip news

#12288 Port raw auto start fix to release
  CHANGELOG.md
  src/client/datascience/interactive-common/notebookProvider.ts
  src/client/datascience/raw-kernel/rawNotebookProvider.ts
  src/client/datascience/raw-kernel/rawNotebookProviderWrapper.ts
  src/client/datascience/types.ts
Labels: skip news

#12307 Ability to clear cell output in NativeNotebook
  src/client/common/constants.ts
  src/client/datascience/interactive-ipynb/nativeEditorStorage.ts
  src/client/datascience/notebook/contentProvider.ts
  src/client/datascience/notebook/executionService.ts
  src/client/datascience/notebook/helpers/cellUpdateHelpers.ts
  src/client/datascience/notebook/helpers/executionHelpers.ts
  src/client/datascience/serviceRegistry.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/interactive-ipynb/nativeEditorProvider.functional.test.ts
  src/test/datascience/interactive-ipynb/nativeEditorStorage.unit.test.ts
  src/test/datascience/notebook/edit.ds.test.ts
  src/test/datascience/notebook/executionService.ds.test.ts
  src/test/datascience/notebook/helper.ts
Labels: skip news

#12333 Update VSC Notebook API
  src/client/common/application/notebook.ts
  src/client/common/application/types.ts
  src/client/datascience/notebook/cellEditSyncService.ts
  src/client/datascience/notebook/executionService.ts
  src/client/datascience/notebook/helpers/cellMappers.ts
  src/client/datascience/notebook/helpers/cellUpdateHelpers.ts
  src/client/datascience/notebook/helpers/helpers.ts
  src/test/datascience/notebook/contentProvider.ds.test.ts
  src/test/datascience/notebook/helper.ts
  types/vscode-proposed/index.d.ts
  types/vscode.proposed.d.ts
  typings/vscode-proposed/index.d.ts
Labels: skip news

#12338 Add shortcuts for cut, copy, paste and split cells
  package.json
Labels: skip news

#12232 Refactored exporting notebooks to python script
  .vscode/launch.json
  package.json
  package.nls.json
  src/client/common/application/commands.ts
  src/client/common/utils/localize.ts
  src/client/datascience/commands/commandRegistry.ts
  src/client/datascience/commands/exportCommands.ts
  src/client/datascience/constants.ts
  src/client/datascience/export/README.md
  src/client/datascience/export/exportManager.ts
  src/client/datascience/export/exportManagerDependencyChecker.ts
  src/client/datascience/export/exportManagerFileOpener.ts
  src/client/datascience/export/exportManagerFilePicker.ts
  src/client/datascience/export/exportToHTML.ts
  src/client/datascience/export/exportToPDF.ts
  src/client/datascience/export/exportToPython.ts
  src/client/datascience/export/types.ts
  src/client/datascience/interactive-common/interactiveWindowTypes.ts
  src/client/datascience/interactive-common/synchronization.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/jupyter/interpreter/jupyterInterpreterDependencyService.ts
  src/client/datascience/jupyter/interpreter/jupyterInterpreterSubCommandExecutionService.ts
  src/client/datascience/jupyter/jupyterExecution.ts
  src/client/datascience/progress/messages.ts
  src/client/datascience/progress/types.ts
  src/client/datascience/serviceRegistry.ts
  src/datascience-ui/history-react/interactivePanel.tsx
  src/datascience-ui/history-react/redux/actions.ts
  src/datascience-ui/history-react/redux/reducers/index.ts
  src/datascience-ui/interactive-common/redux/reducers/transfer.ts
  src/datascience-ui/interactive-common/redux/reducers/types.ts
  src/datascience-ui/native-editor/redux/actions.ts
  src/datascience-ui/native-editor/redux/reducers/index.ts
  src/datascience-ui/native-editor/toolbar.tsx
  src/test/.vscode/settings.json
  src/test/datascience/commands/commandRegistry.unit.test.ts
  src/test/datascience/export/exportManagerFileOpener.unit.test.ts
  src/test/datascience/export/exportToPython.test.ts
  src/test/datascience/export/test.ipynb
  src/test/datascience/interactivePanel.functional.test.tsx
  src/test/datascience/nativeEditor.functional.test.tsx
  src/test/datascience/nativeEditor.toolbar.functional.test.tsx
Labels: skip news

#12358 ExP telemetry fixes
  package-lock.json
  package.json
  src/client/common/experiments/service.ts
  src/test/common/experiments/service.unit.test.ts
Labels: skip news

#12356 Rchiodo/rel june update
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
  ThirdPartyNotices-Repository.txt
  package-lock.json
  package.json
  src/client/common/experiments/service.ts
  src/test/common/experiments/service.unit.test.ts
Labels: skip news

#12341 Remove hardcoding of languages
  src/client/datascience/notebook/helpers/cellUpdateHelpers.ts
  src/client/datascience/notebook/helpers/helpers.ts
  src/client/datascience/notebook/notebookEditor.ts
  src/test/datascience/notebook/contentProvider.unit.test.ts
Labels: skip news

#12335 Ignore other notebooks (avoid conflicts with non jupyter nbs)
  src/client/datascience/notebook/cellEditSyncService.ts
  src/client/datascience/notebook/helpers/helpers.ts
  src/client/datascience/notebook/integration.ts
  src/client/datascience/notebook/notebookEditorProvider.ts
Labels: skip news

#12339 start page experiment and fixes
  StartPageReleaseNotes.md
  images/dataviewer.gif
  images/kernelchange.gif
  images/plotviewer.gif
  images/remoteserver.gif
  images/runbyline.gif
  images/savetopythonfile.png
  images/variableexplorer.png
  package.json
  package.nls.json
  pythonFiles/Notebooks intro.ipynb
  pythonFiles/Welcome_To_VSCode_Notebooks.ipynb
  src/client/common/application/commands.ts
  src/client/common/experiments/groups.ts
  src/client/common/startPage/startPage.ts
  src/client/common/startPage/types.ts
  src/client/common/utils/localize.ts
  src/client/datascience/commands/commandRegistry.ts
  src/client/datascience/common.ts
  src/client/datascience/constants.ts
  src/client/datascience/interactive-ipynb/nativeEditorProvider.ts
  src/client/datascience/types.ts
  src/client/telemetry/index.ts
  src/datascience-ui/react-common/image.tsx
  src/datascience-ui/react-common/images/StartPage/OpenFolder-inverse.svg
  src/datascience-ui/react-common/images/StartPage/OpenFolder.svg
  src/datascience-ui/startPage/startPage.css
  src/datascience-ui/startPage/startPage.tsx
  src/test/datascience/commands/commandRegistry.unit.test.ts
  src/test/startPage/startPage.unit.test.ts
Labels: skip news

#12363 Telemetry for notebooks
  src/client/common/types.ts
  src/client/datascience/interactive-common/notebookUsageTracker.ts
  src/client/datascience/interactive-ipynb/nativeEditorProvider.ts
  src/client/datascience/notebook/contentProvider.ts
  src/client/datascience/notebook/executionService.ts
  src/client/datascience/notebook/notebookEditorProvider.ts
  src/client/datascience/serviceRegistry.ts
  src/test/datascience/execution.unit.test.ts
  src/test/datascience/interactive-ipynb/nativeEditorProvider.functional.test.ts
  src/test/testing/navigation/commandHandlers.unit.test.ts
Labels: skip news

#12365 Port start page to release
  StartPageReleaseNotes.md
  images/dataviewer.gif
  images/kernelchange.gif
  images/plotviewer.gif
  images/remoteserver.gif
  images/runbyline.gif
  images/savetopythonfile.png
  images/variableexplorer.png
  package.json
  package.nls.json
  pythonFiles/Notebooks intro.ipynb
  pythonFiles/Welcome_To_VSCode_Notebooks.ipynb
  src/client/common/application/commands.ts
  src/client/common/experiments/groups.ts
  src/client/common/startPage/startPage.ts
  src/client/common/startPage/types.ts
  src/client/common/utils/localize.ts
  src/client/datascience/commands/commandRegistry.ts
  src/client/datascience/common.ts
  src/client/datascience/constants.ts
  src/client/datascience/interactive-ipynb/nativeEditorProvider.ts
  src/client/datascience/types.ts
  src/client/telemetry/index.ts
  src/datascience-ui/react-common/image.tsx
  src/datascience-ui/react-common/images/StartPage/OpenFolder-inverse.svg
  src/datascience-ui/react-common/images/StartPage/OpenFolder.svg
  src/datascience-ui/startPage/startPage.css
  src/datascience-ui/startPage/startPage.tsx
  src/test/datascience/commands/commandRegistry.unit.test.ts
  src/test/startPage/startPage.unit.test.ts
Labels: skip news

#12367 Support hot exit in notebooks
  src/client/datascience/notebook/contentProvider.ts
  src/client/datascience/notebook/renderer.ts
  src/test/datascience/notebook/contentProvider.unit.test.ts
  types/vscode-proposed/index.d.ts
  types/vscode.proposed.d.ts
  typings/vscode-proposed/index.d.ts
Labels: skip news

#12371 Last changes before release
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
Labels: skip news

#12366 Manually send didConfigurationChange on interpreter change
  src/client/activation/node/languageServerProxy.ts
Labels: skip news

#12377 Change hot exit to create new files for each backup
  src/client/datascience/interactive-ipynb/nativeEditorProvider.ts
  src/client/datascience/interactive-ipynb/nativeEditorStorage.ts
  src/client/datascience/interactive-ipynb/notebookStorageProvider.ts
  src/client/datascience/notebook/contentProvider.ts
  src/client/datascience/types.ts
Labels: skip news

#12381 Update Run By Line button count in test
  src/test/datascience/debugger.functional.test.tsx
Labels: skip news

#12236 Move code related to Python version to the py-envs component tree.
  pythonFiles/interpreterInfo.py
  pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py
  src/client/common/process/internal/scripts/index.ts
  src/client/common/process/pythonDaemon.ts
  src/client/common/process/pythonDaemonPool.ts
  src/client/common/process/pythonEnvironment.ts
  src/client/common/process/pythonProcess.ts
  src/client/common/process/types.ts
  src/client/common/utils/version.ts
  src/client/interpreter/interpreterVersion.ts
  src/client/pythonEnvironments/discovery/locators/services/windowsRegistryService.ts
  src/client/pythonEnvironments/exec.ts
  src/client/pythonEnvironments/info.ts
  src/client/pythonEnvironments/pythonVersion.ts
  src/client/terminals/codeExecution/djangoShellCodeExecution.ts
  src/client/terminals/codeExecution/terminalCodeExecution.ts
  src/test/common/process/pythonDaemon.functional.test.ts
  src/test/common/process/pythonDaemonPool.functional.test.ts
  src/test/interpreters/interpreterVersion.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/windowsRegistryService.unit.test.ts
  src/test/pythonEnvironments/info.unit.test.ts
  src/test/pythonEnvironments/pythonVersion.unit.test.ts
Labels: skip news

#12382 Infrastructure for mounting more than one webview at a time
  build/.mocha.functional.json
  build/.mocha.functional.opts
  build/.mocha.functional.perf.json
  build/.mocha.functional.perf.opts
  build/.mocha.performance.json
  build/.mocha.performance.opts
  build/.mocha.unittests.js.json
  build/.mocha.unittests.js.opts
  build/.mocha.unittests.json
  build/.mocha.unittests.opts
  build/.mocha.unittests.ts.json
  build/.mocha.unittests.ts.opts
  package-lock.json
  package.json
  src/test/common/process/pythonDaemon.functional.test.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/dataviewer.functional.test.tsx
  src/test/datascience/debugger.functional.test.tsx
  src/test/datascience/errorHandler.functional.test.tsx
  src/test/datascience/intellisense.functional.test.tsx
  src/test/datascience/interactiveWindow.functional.test.tsx
  src/test/datascience/interactiveWindowTestHelpers.tsx
  src/test/datascience/jupyter/kernels/kernelSwitcher.unit.test.ts
  src/test/datascience/liveshare.functional.test.tsx
  src/test/datascience/mountedWebView.ts
  src/test/datascience/mountedWebViewFactory.ts
  src/test/datascience/nativeEditor.functional.test.tsx
  src/test/datascience/nativeEditorTestHelpers.tsx
  src/test/datascience/plotViewer.functional.test.tsx
  src/test/datascience/testHelpers.tsx
  src/test/datascience/variableTestHelpers.ts
  src/test/datascience/variableexplorer.functional.test.tsx
  src/test/debugger/capabilities.test.ts
  src/test/startPage/startPage.functional.test.tsx
Labels: skip news

#12393 Merging changes back from the release branch
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
  ThirdPartyNotices-Repository.txt
  package-lock.json
  package.json
Labels: skip news

#12402 Allow users to open VSC notebook even when using our own Notebook Editors
  build/ci/templates/steps/compile.yml
  gulpfile.js
  package.json
  package.nls.json
  src/client/common/constants.ts
  src/client/common/utils/localize.ts
  src/client/datascience/constants.ts
  src/client/datascience/context/activeEditorContext.ts
  src/client/datascience/interactive-ipynb/nativeEditorStorage.ts
  src/client/datascience/notebook/cellEditSyncService.ts
  src/client/datascience/notebook/contentProvider.ts
  src/client/datascience/notebook/integration.ts
  src/client/datascience/notebook/notebookEditorCompatibilitySupport.ts
  src/client/datascience/notebook/notebookEditorProvider.ts
  src/client/datascience/notebook/notebookEditorProviderWrapper.ts
  src/client/datascience/notebook/serviceRegistry.ts
  src/client/datascience/serviceRegistry.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/dsTestSetup.ts
  src/test/datascience/notebook/contentProvider.unit.test.ts
Labels: skip news

#12406 Add context menu to open nb with VSC Notebook
  package.json
  package.nls.json
  src/client/common/application/commands.ts
  src/client/datascience/constants.ts
  src/client/datascience/notebook/notebookEditorProvider.ts
  src/client/extensionActivation.ts
Labels: skip news

#12097 Do not trigger unnecessary work in language server when formatting a document
  src/client/common/editor.ts
Labels: skip news

#12409 Fix nightly flake tests
  src/client/datascience/themeFinder.ts
  src/test/datascience/liveshare.functional.test.tsx
  src/test/datascience/uiTests/helpers.ts
  src/test/datascience/uiTests/notebookUi.ts
Labels: skip news

#12411 Disable use of proposedApi in stable VS Code
  package.json
  src/client/datascience/notebook/integration.ts
  src/client/datascience/notebook/notebookEditorProvider.ts
  src/client/datascience/notebook/serviceRegistry.ts
Labels: skip news

#12410 Fixes to reverting notebooks
  src/client/datascience/interactive-ipynb/nativeEditorStorage.ts
  src/client/datascience/notebook/contentProvider.ts
Labels: skip news

#12407 Pin py to 1.8.1 (CI failure - Windows unit tests)
  build/test-requirements.txt
Labels: skip news

#12426 Turn on zmq for five percent
  experiments.json
Labels: skip news

#12401 Turn off LS survey and banner
  src/client/activation/languageClientMiddleware.ts
  src/client/activation/languageServer/manager.ts
  src/client/languageServices/languageServerSurveyBanner.ts
  src/client/languageServices/proposeLanguageServerBanner.ts
  src/test/activation/languageServer/manager.unit.test.ts
  src/test/testing/banners/languageServerSurvey.unit.test.ts
  src/test/testing/banners/proposeNewLanguageServerBanner.unit.test.ts
Labels: skip news

#12430 Remove path from untitled files when using VSC NB
  src/client/datascience/common.ts
  src/client/datascience/interactive-ipynb/notebookStorageProvider.ts
  src/client/datascience/notebook/notebookEditorProvider.ts
Labels: skip news

#12101 Update incorrect JSDoc annotations
  news/3 Code Health/12101.md
  src/client/common/process/pythonDaemonPool.ts
  src/client/common/terminal/environmentActivationProviders/condaActivationProvider.ts
  src/client/common/types.ts
  src/client/common/utils/cacheUtils.ts
  src/client/datascience/jupyter/interpreter/jupyterInterpreterDependencyService.ts
  src/client/datascience/jupyter/jupyterDebugger.ts
  src/client/datascience/jupyter/kernels/kernelSelections.ts
  src/client/datascience/jupyter/kernels/kernelSelector.ts
  src/client/datascience/jupyter/kernels/kernelService.ts
  src/client/debugger/extension/configuration/launch.json/updaterService.ts
  src/client/interpreter/activation/wrapperEnvironmentActivationService.ts
  src/client/interpreter/interpreterService.ts
  src/client/linters/linterAvailability.ts
  src/client/testing/common/services/discoveredTestParser.ts
  src/client/testing/pytest/services/testMessageService.ts
  src/client/testing/unittest/services/parserService.ts
  src/ipywidgets/src/embed.ts
  src/ipywidgets/src/libembed.ts
  src/test/mocks/vsc/uri.ts
  src/test/testing/explorer/explorerTestData.ts
  src/test/testing/pytest/pytest.run.test.ts
  types/@msrvida-python-program-analysis/rewrite-magics.d.ts
Labels: external contributor

#12386 LSP version update
  package-lock.json
  package.json
  pythonFiles/vscode_datascience_helpers/daemon/README.md
  src/client/activation/common/activatorBase.ts
  src/client/activation/common/analysisOptions.ts
  src/client/activation/languageClientMiddleware.ts
  src/client/activation/languageServer/analysisOptions.ts
  src/client/activation/languageServer/languageClientFactory.ts
  src/client/activation/languageServer/languageServerProxy.ts
  src/client/activation/node/activator.ts
  src/client/activation/node/cancellationUtils.ts
  src/client/activation/node/languageClientFactory.ts
  src/client/activation/node/languageServerProxy.ts
  src/client/activation/progress.ts
  src/client/activation/types.ts
  src/client/common/process/pythonDaemonFactory.ts
  src/client/datascience/interactive-common/intellisense/conversion.ts
  src/client/datascience/interactive-common/intellisense/intellisenseDocument.ts
  src/client/datascience/interactive-common/intellisense/intellisenseProvider.ts
  src/client/datascience/interactive-ipynb/nativeEditorProvider.ts
  src/client/providers/symbolProvider.ts
  src/test/activation/languageServer/analysisOptions.unit.test.ts
  src/test/activation/languageServer/languageClientFactory.unit.test.ts
  src/test/activation/languageServer/languageServer.unit.test.ts
  src/test/activation/languageServer/manager.unit.test.ts
  src/test/common/process/pythonDaemon.functional.test.ts
  src/test/common/process/pythonDaemonPool.functional.test.ts
  src/test/datascience/interactive-ipynb/nativeEditorProvider.functional.test.ts
  src/test/datascience/mockCode2ProtocolConverter.ts
  src/test/datascience/mockCustomEditorService.ts
  src/test/datascience/mockLanguageClient.ts
  src/test/datascience/mockLanguageServerAnalysisOptions.ts
  src/test/datascience/mockLanguageServerProxy.ts
  src/test/datascience/mockProtocol2CodeConverter.ts
  src/test/languageServers/jedi/symbolProvider.unit.test.ts
Labels: skip news

#12438 Set max height for variable explorer
  src/datascience-ui/interactive-common/variableExplorer.tsx
Labels: skip news

#12431 Fix disposed execution factory to not have binding failures.
  src/client/common/process/pythonExecutionFactory.ts
  src/test/linters/lint.functional.test.ts
Labels: skip news

#12435 Added telemetry for export to python and html
  src/client/datascience/commands/exportCommands.ts
  src/client/datascience/constants.ts
  src/client/datascience/export/exportManager.ts
  src/client/datascience/export/exportManagerFileOpener.ts
  src/client/datascience/export/exportManagerFilePicker.ts
  src/client/datascience/interactive-window/interactiveWindow.ts
  src/client/datascience/interactive-window/interactiveWindowCommandListener.ts
  src/client/telemetry/index.ts
Labels: skip news

#12447 Prepare for hotfix release
  CHANGELOG.md
  package-lock.json
  package.json
  src/client/testing/common/updateTestSettings.ts
  src/test/application/diagnostics/checks/updateTestSettings.unit.test.ts
Labels: skip news

#12437 Minor refactoring to notebook model
  src/client/datascience/interactive-ipynb/nativeEditorStorage.ts
  src/client/datascience/notebook/contentProvider.ts
  src/client/datascience/notebook/notebookEditorProvider.ts
  src/client/datascience/types.ts
  src/test/datascience/notebook/contentProvider.unit.test.ts
Labels: skip news

#12458 removed space from HTML label
  src/client/common/utils/localize.ts
Labels: skip news

#12456 Support not needing a password on a jupyter connection
  src/client/datascience/jupyter/jupyterPasswordConnect.ts
  src/test/datascience/jupyterPasswordConnect.unit.test.ts
Labels: skip news

#12464 Fixed bug in exporting notebook to HTML
  src/client/datascience/export/exportBase.ts
  src/client/datascience/export/exportManagerFileOpener.ts
  src/client/datascience/export/exportToHTML.ts
Labels: skip news, type-bug

#12483 Restore DebugAdapter experiment
  experiments.json
Labels: skip news

#12432 Pull in the logging-related changes from the "logging-changes-and-drop-old-debugger" branch.
  build/ci/templates/test_phases.yml
  news/3 Code Health/11699.md
  news/3 Code Health/11896.md
  news/3 Code Health/9837.md
  package.json
  src/client/activation/common/downloader.ts
  src/client/common/application/customEditorService.ts
  src/client/common/configSettings.ts
  src/client/common/editor.ts
  src/client/common/logger.ts
  src/client/common/types.ts
  src/client/common/utils/async.ts
  src/client/common/utils/decorators.ts
  src/client/common/utils/misc.ts
  src/client/datascience/common.ts
  src/client/datascience/interactive-ipynb/nativeEditorCommandListener.ts
  src/client/datascience/jupyter/liveshare/hostJupyterExecution.ts
  src/client/datascience/jupyter/liveshare/serverCache.ts
  src/client/datascience/liveshare/postOffice.ts
  src/client/datascience/notebook/cellEditSyncService.ts
  src/client/datascience/notebook/helpers/cellUpdateHelpers.ts
  src/client/datascience/notebook/helpers/helpers.ts
  src/client/datascience/notebook/notebookEditor.ts
  src/client/extensionActivation.ts
  src/client/logging/_console.ts
  src/client/logging/_global.ts
  src/client/logging/_trace.ts
  src/client/logging/formatters.ts
  src/client/logging/index.ts
  src/client/logging/levels.ts
  src/client/logging/logger.ts
  src/client/logging/trace.ts
  src/client/logging/transports.ts
  src/client/logging/types.ts
  src/client/logging/util.ts
  src/test/common/configSettings/configSettings.pythonPath.unit.test.ts
  src/test/common/configSettings/configSettings.unit.test.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/mountedWebView.ts
  src/test/datascience/testexecutionLogger.ts
  src/test/datascience/uiTests/notebookHelpers.ts
  src/test/index.ts
  src/test/multiRootTest.ts
  src/test/performanceTest.ts
  src/test/standardTest.ts
  src/test/testBootstrap.ts
  src/test/testLogger.ts
Labels: skip news

#12488 Fix an errant import.
  src/client/datascience/export/exportManagerFileOpener.ts
Labels: skip news

#12056 Added `workspaceContains:pyproject.toml` to activationEvents
  news/1 Enhancements/12056.md
  package.json
Labels: external contributor

#12398 Move interpreter-info-related code to the py-envs component tree.
  src/client/common/process/pythonEnvironment.ts
  src/client/pythonEnvironments/exec.ts
  src/client/pythonEnvironments/info/executable.ts
  src/client/pythonEnvironments/info/interpreter.ts
  src/client/pythonEnvironments/info/pythonVersion.ts
  src/client/terminals/codeExecution/djangoShellCodeExecution.ts
  src/client/terminals/codeExecution/terminalCodeExecution.ts
  src/test/common/process/pythonEnvironment.unit.test.ts
  src/test/datascience/executionServiceMock.ts
  src/test/datascience/mockPythonService.ts
  src/test/pythonEnvironments/info/executable.unit.test.ts
  src/test/pythonEnvironments/info/interpreter.unit.test.ts
Labels: skip news

#12524 Update experiments.json for raw kernel experiment
  experiments.json
Labels: skip news

#12490 Fixes related to execution & clearing output of Native Notebooks
  src/client/datascience/notebook/executionService.ts
  src/client/datascience/notebook/helpers/cellUpdateHelpers.ts
  src/client/datascience/notebook/notebookEditorProvider.ts
  src/test/datascience/dsTestSetup.ts
  src/test/datascience/notebook/cellEditSyncService.ds.test.ts
  src/test/datascience/notebook/edit.ds.test.ts
  src/test/datascience/notebook/empty.ipynb
  src/test/datascience/notebook/executionErrors.ds.test.ts
  src/test/datascience/notebook/executionService.ds.test.ts
  src/test/datascience/notebook/helper.ts
  src/test/datascience/notebook/interrupRestart.ds.test.ts
  src/test/datascience/notebook/notebookEditorProvider.ds.test.ts
  src/test/datascience/notebook/saving.ds.test.ts
  src/test/datascience/notebook/test.ipynb
  src/test/format/extension.format.ds.test.ts
Labels: skip news

#12528 Make node install version in contributing docs match ci.yml
  .nvmrc
  CONTRIBUTING.md
Labels: skip news

#12515 DS: Ensure atomic key creation for use with trusted notebooks
  src/client/datascience/crossProcessLock.ts
  src/test/datascience/crossProcessLock.unit.test.ts
Labels: skip news

#12517 Added export notebook to PDF
  package.json
  package.nls.json
  src/client/common/utils/localize.ts
  src/client/datascience/commands/exportCommands.ts
  src/client/datascience/export/exportManager.ts
  src/client/datascience/export/exportManagerDependencyChecker.ts
  src/client/datascience/export/exportManagerFileOpener.ts
  src/client/datascience/export/exportToPDF.ts
  src/client/datascience/progress/messages.ts
  src/client/datascience/progress/types.ts
  src/test/datascience/export/exportManagerFileOpener.unit.test.ts
Labels: skip news

#12548 Added tests for export notebook to PDF
  src/test/datascience/export/exportManagerFileOpener.unit.test.ts
Labels: skip news

#12466 DS: Display 'Trusted' / 'Not Trusted' on notebook load
  package.nls.json
  src/client/common/utils/localize.ts
  src/client/datascience/interactive-common/interactiveWindowTypes.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/datascience-ui/interactive-common/common.css
  src/datascience-ui/interactive-common/mainState.ts
  src/datascience-ui/interactive-common/redux/store.ts
  src/datascience-ui/interactive-common/trustMessage.tsx
  src/datascience-ui/native-editor/nativeCell.tsx
  src/datascience-ui/native-editor/nativeEditor.tsx
  src/datascience-ui/native-editor/redux/reducers/creation.ts
  src/datascience-ui/native-editor/toolbar.tsx
  src/test/datascience/interactivePanel.functional.test.tsx
  src/test/datascience/nativeEditor.toolbar.functional.test.tsx
Labels: skip news

#12551 Don't modify LS settings if jediEnabled does not exist
  src/client/testing/common/updateTestSettings.ts
  src/test/application/diagnostics/checks/updateTestSettings.unit.test.ts
Labels: skip news

#12542 Add Telemetry for VSC Notebooks
  package.nls.json
  src/client/common/experiments/telemetry.ts
  src/client/common/utils/localize.ts
  src/client/datascience/activation.ts
  src/client/datascience/constants.ts
  src/client/datascience/context/activeEditorContext.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/interactive-ipynb/nativeEditorOldWebView.ts
  src/client/datascience/notebook/contentProvider.ts
  src/client/datascience/notebook/executionService.ts
  src/client/datascience/notebook/helpers/cellUpdateHelpers.ts
  src/client/datascience/notebook/integration.ts
  src/client/datascience/notebook/notebookEditor.ts
  src/client/datascience/notebook/notebookEditorProvider.ts
  src/client/datascience/types.ts
  src/client/telemetry/index.ts
  src/test/telemetry/index.unit.test.ts
Labels: skip news

#12555 DS: Show banner prompting user to trust notebook
  package.nls.json
  src/client/common/utils/localize.ts
  src/client/datascience/interactive-common/interactiveWindowTypes.ts
  src/client/datascience/interactive-common/synchronization.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/interactive-ipynb/nativeEditorOldWebView.ts
  src/datascience-ui/interactive-common/redux/reducers/commonEffects.ts
  src/datascience-ui/interactive-common/redux/reducers/transfer.ts
  src/datascience-ui/interactive-common/redux/reducers/types.ts
  src/datascience-ui/interactive-common/trustMessage.tsx
  src/datascience-ui/native-editor/redux/actions.ts
  src/datascience-ui/native-editor/redux/reducers/index.ts
  src/datascience-ui/native-editor/toolbar.tsx
  src/test/datascience/nativeEditor.toolbar.functional.test.tsx
Labels: skip news

#12556 Hot fixes for pylint and jediEnabled issues
  CHANGELOG.md
  package-lock.json
  package.json
  src/client/linters/linterInfo.ts
  src/client/testing/common/updateTestSettings.ts
  src/test/application/diagnostics/checks/updateTestSettings.unit.test.ts
  src/test/linters/linterinfo.unit.test.ts
Labels: skip news

#12566 Skip flaky CI tests
  src/test/common/variables/envVarsProvider.multiroot.test.ts
  src/test/format/extension.format.test.ts
  src/test/format/extension.sort.test.ts
  src/test/linters/lint.multiroot.test.ts
Labels: skip news

#12558 VS Code Notebook survey
  package-lock.json
  package.json
  package.nls.json
  src/client/common/utils/localize.ts
  src/client/constants.ts
  src/client/datascience/notebook/serviceRegistry.ts
  src/client/datascience/notebook/survey.ts
  src/test/datascience/notebook/survey.unit.test.ts
Labels: skip news

#12549 Turn pythonPath experiment for 20% of users.
  experiments.json
Labels: skip news

#12573 Bump rawkernel use to 25%
  experiments.json
Labels: skip news

#12577 Skip more flaky CI tests
  src/test/common/platform/filesystem.test.ts
  src/test/common/terminals/environmentActivationProviders/terminalActivation.testvirtualenvs.ts
  src/test/format/extension.format.test.ts
  src/test/testing/argsService.test.ts
Labels: skip news

#12568 Skip failing Python Daemon Pool unit test
  src/test/common/process/pythonDaemonPool.unit.test.ts
Labels: skip news

#12598 Skip another flaky Python daemon test
  src/test/common/process/pythonDaemonPool.unit.test.ts
Labels: skip news

#12575 Refactored importing jupyter notebook as python file
  src/client/datascience/export/exportManagerFileOpener.ts
  src/client/datascience/interactive-window/interactiveWindowCommandListener.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/export/exportManagerFileOpener.unit.test.ts
  src/test/datascience/interactiveWindowCommandListener.unit.test.ts
Labels: skip news

#12599 Moved export interface definitions to types file
  src/client/datascience/export/exportManager.ts
  src/client/datascience/export/exportManagerFilePicker.ts
  src/client/datascience/export/types.ts
  src/client/datascience/serviceRegistry.ts
Labels: skip news

#12570 Fix missing events and hooks from INotebookEditor
  src/client/datascience/interactive-ipynb/nativeEditorStorage.ts
  src/client/datascience/interactive-ipynb/nativeEditorViewTracker.ts
  src/client/datascience/notebook/executionService.ts
  src/client/datascience/notebook/helpers/cellUpdateHelpers.ts
  src/client/datascience/notebook/notebookEditor.ts
  src/client/datascience/notebook/notebookEditorProvider.ts
  src/test/datascience/notebook/edit.ds.test.ts
  src/test/datascience/notebook/executionService.ds.test.ts
  src/test/datascience/notebook/helper.ts
  src/test/datascience/notebook/notebookEditorProvider.ds.test.ts
Labels: skip news

#12600 Start restart session after first cell execution
  src/client/datascience/baseJupyterSession.ts
  src/client/datascience/jupyter/jupyterSession.ts
  src/client/datascience/raw-kernel/rawJupyterSession.ts
Labels: skip news

#12605 pull type from type file
  src/test/datascience/dataScienceIocContainer.ts
Labels: skip news

#12635 Skip more flaky tests
  src/test/common/platform/filesystem.test.ts
  src/test/format/extension.format.test.ts
  src/test/pythonEnvironments/discovery/locators/interpreterLocatorService.testvirtualenvs.ts
  src/test/testing/rediscover.test.ts
Labels: skip news

#12604 Simplify INotebookModel when using VSCode Notebooks
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/interactive-ipynb/nativeEditorProvider.ts
  src/client/datascience/interactive-ipynb/nativeEditorStorage.ts
  src/client/datascience/notebook/contentProvider.ts
  src/client/datascience/notebook/executionService.ts
  src/client/datascience/notebook/helpers/cellMappers.ts
  src/client/datascience/notebook/helpers/cellUpdateHelpers.ts
  src/client/datascience/notebook/notebookEditorProvider.ts
  src/client/datascience/notebookStorage/baseModel.ts
  src/client/datascience/notebookStorage/factory.ts
  src/client/datascience/notebookStorage/notebookModel.ts
  src/client/datascience/notebookStorage/notebookModelEditEvent.ts
  src/client/datascience/notebookStorage/types.ts
  src/client/datascience/notebookStorage/vscNotebookModel.ts
  src/client/datascience/serviceRegistry.ts
  src/client/datascience/types.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/interactive-ipynb/nativeEditorProvider.functional.test.ts
  src/test/datascience/interactive-ipynb/nativeEditorStorage.unit.test.ts
  src/test/datascience/mockCustomEditorService.ts
  src/test/datascience/nativeEditorViewTracker.unit.test.ts
  src/test/datascience/notebook/contentProvider.unit.test.ts
  src/test/datascience/notebook/executionService.ds.test.ts
Labels: skip news

#12639 Port some fixes for point release
  .vscode/launch.json
  CHANGELOG.md
  src/client/datascience/constants.ts
  src/client/datascience/interactive-common/interactiveBase.ts
  src/client/datascience/interactive-common/interactiveWindowTypes.ts
  src/client/datascience/interactive-common/serialization.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/interactive-ipynb/nativeEditorRunByLineListener.ts
  src/client/datascience/jupyter/debuggerVariables.ts
  src/client/telemetry/index.ts
  src/datascience-ui/interactive-common/redux/reducers/monaco.ts
  src/test/datascience/interactiveWindow.functional.test.tsx
Labels: skip news

#12640 Model is in charge of updates to model & cells
  src/client/datascience/notebook/cellEditSyncService.ts
  src/client/datascience/notebook/executionService.ts
  src/client/datascience/notebook/helpers/cellUpdateHelpers.ts
  src/client/datascience/notebook/helpers/executionHelpers.ts
  src/client/datascience/notebook/helpers/helpers.ts
  src/client/datascience/notebook/notebookEditorProvider.ts
  src/client/datascience/notebookStorage/vscNotebookModel.ts
Labels: skip news

#12646 Fix flaky Daemon and MimeType tracker tests
  src/test/common/process/pythonDaemonPool.unit.test.ts
  src/test/datascience/jupyter/jupyterCellOutputMimeTypeTracker.unit.test.ts
Labels: skip news

#12579 DS: Open untrusted notebooks as readonly
  src/datascience-ui/history-react/interactiveCell.tsx
  src/datascience-ui/interactive-common/cellInput.tsx
  src/datascience-ui/interactive-common/jupyterInfo.tsx
  src/datascience-ui/interactive-common/markdown.tsx
  src/datascience-ui/interactive-common/redux/reducers/transfer.ts
  src/datascience-ui/interactive-common/redux/store.ts
  src/datascience-ui/native-editor/addCellLine.tsx
  src/datascience-ui/native-editor/nativeCell.tsx
  src/datascience-ui/native-editor/nativeEditor.tsx
  src/datascience-ui/native-editor/toolbar.tsx
  src/test/datascience/interactivePanel.functional.test.tsx
  src/test/datascience/nativeEditor.functional.test.tsx
Labels: skip news

#12642 Port ZMQ support fix to release
  CHANGELOG.md
  src/client/datascience/raw-kernel/rawNotebookSupportedService.ts
Labels: skip news

#12650 Port start page telemetry
  CHANGELOG.md
  src/client/common/startPage/startPage.ts
  src/client/datascience/commands/commandRegistry.ts
  src/client/datascience/constants.ts
  src/client/telemetry/index.ts
Labels: skip news

#12653 Language server name
  src/client/activation/activationService.ts
  src/client/activation/node/languageServerFolderService.ts
  src/client/activation/types.ts
  src/test/activation/node/languageServerFolderService.unit.test.ts
Labels: skip news

#12649 Cherry picks for point release
  .gitignore
  news/2 Fixes/12614.md
  package.json
  src/client/activation/activationService.ts
  src/client/activation/common/downloader.ts
  src/client/activation/common/languageServerFolderService.ts
  src/client/activation/node/languageClientFactory.ts
  src/client/activation/node/languageServerFolderService.ts
  src/client/activation/node/languageServerProxy.ts
  src/client/activation/types.ts
  src/test/activation/languageServer/downloader.unit.test.ts
  src/test/activation/languageServer/languageServerFolderService.unit.test.ts
  src/test/activation/node/languageServerFolderService.unit.test.ts
Labels: skip news

#12659 Update changelog and version
  CHANGELOG.md
  news/2 Fixes/12614.md
  package-lock.json
  package.json
Labels: skip news

#12670 Fix unit test issues when using ts-node on GHA
  src/client/datascience/notebookStorage/vscNotebookModel.ts
Labels: skip news

#12671 Fixes to opening VSCode Notebook
  src/client/datascience/interactive-ipynb/nativeEditorStorage.ts
  src/client/datascience/interactive-ipynb/notebookStorageProvider.ts
Labels: skip news

#12652 Download & install renderer extension when opening a VSC Notebook
  package.nls.json
  src/client/common/utils/localize.ts
  src/client/datascience/notebook/constants.ts
  src/client/datascience/notebook/rendererExtension.ts
  src/client/datascience/notebook/rendererExtensionDownloader.ts
  src/test/datascience/notebook/rendererExension.unit.test.ts
  src/test/datascience/notebook/rendererExtensionDownloader.unit.test.ts
  src/test/mocks/vsc/index.ts
  src/test/vscode-mock.ts
Labels: skip news

#12657 DS: Hide commands for interacting with notebooks when active notebook is untrusted
  package.json
  src/client/datascience/constants.ts
  src/client/datascience/context/activeEditorContext.ts
  src/client/datascience/interactive-ipynb/trustService.ts
  src/client/datascience/types.ts
Labels: skip news

#12643 Fix linux tests to report correctly, get rid of stream destroyed messages on raw kernel shutdown
  news/3 Code Health/12539.md
  src/client/common/process/baseDaemon.ts
  src/client/common/process/pythonDaemon.ts
  src/client/common/process/pythonDaemonFactory.ts
  src/client/common/process/pythonDaemonPool.ts
  src/client/common/process/pythonExecutionFactory.ts
  src/client/datascience/kernel-launcher/kernelDaemon.ts
  src/test/common/process/pythonDaemon.functional.test.ts
  src/test/common/process/pythonDaemonPool.functional.test.ts
  src/test/common/process/pythonDaemonPool.unit.test.ts
  src/test/common/process/pythonExecutionFactory.unit.test.ts
  src/test/linters/lint.functional.test.ts
  src/test/refactor/rename.test.ts
  src/test/testing/pytest/pytest.discovery.test.ts
  src/test/testing/pytest/pytest.run.test.ts
Labels: skip news

#12676 Ensure we can open VSCode Notebook with old editor
  src/client/datascience/interactive-ipynb/nativeEditorProviderOld.ts
Labels: skip news

#12672 Updates to Notebooks based on latest VSC API changes
  src/client/datascience/notebook/contentProvider.ts
  src/client/datascience/notebook/integration.ts
  src/test/common/process/pythonDaemonPool.unit.test.ts
  types/vscode-proposed/index.d.ts
  types/vscode.proposed.d.ts
  typings/vscode-proposed/index.d.ts
Labels: skip news

#12680 Use composition rather than inheritance for ProtocolParser.
  src/client/debugger/extension/helpers/protocolParser.ts
Labels: skip news

#12683 Add package name to output
  package.nls.json
  src/client/common/utils/localize.ts
  src/client/datascience/jupyterUriProviderRegistration.ts
  src/client/datascience/jupyterUriProviderWrapper.ts
  src/test/datascience/jupyterUriProviderRegistration.unit.test.ts
Labels: skip news

#12681 Register notebook with VSC only in Insiders
  src/client/common/application/notebook.ts
  src/client/datascience/notebook/integration.ts
  src/test/datascience/notebook/helper.ts
Labels: skip news
