Repository microsoft/vscode-python, pull requests merged in 2020-07, with the labels that each got.

#12685 DS: Fixes for trusted notebooks UI
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/datascience-ui/interactive-common/cellInput.tsx
  src/datascience-ui/interactive-common/editor.tsx
  src/datascience-ui/interactive-common/markdown.tsx
  src/datascience-ui/native-editor/nativeCell.tsx
  src/datascience-ui/native-editor/nativeEditor.less
Labels: skip news

#12682 Log time taken by pytest hook
  src/test/testing/pytest/pytest.run.test.ts
Labels: skip news

#12516 Move remaining "virtual"-env-related code to the py-envs component tree.
  src/client/common/terminal/environmentActivationProviders/baseActivationProvider.ts
  src/client/common/terminal/environmentActivationProviders/bash.ts
  src/client/common/terminal/environmentActivationProviders/commandPrompt.ts
  src/client/interpreter/helpers.ts
  src/client/interpreter/virtualEnvs/index.ts
  src/client/pythonEnvironments/discovery/globalenv.ts
  src/client/pythonEnvironments/discovery/index.ts
  src/client/pythonEnvironments/discovery/subenv.ts
  src/client/pythonEnvironments/info/index.ts
  src/test/interpreters/virtualEnvs/index.unit.test.ts
  src/test/pythonEnvironments/discovery/globalenv.unit.test.ts
  src/test/pythonEnvironments/discovery/subenv.unit.test.ts
Labels: skip news

#12609 Bump plotly.js to 1.54.5
  package-lock.json
  package.json
Labels: external contributor, skip news

#12696 Give restarts a chance when running debugger tests
  src/test/datascience/debugger.functional.test.tsx
Labels: skip news

#12695 Refactor ipywidget tests to use real kernel to wait for idle
  src/client/datascience/baseJupyterSession.ts
  src/client/datascience/jupyter/jupyterSession.ts
  src/client/datascience/raw-kernel/rawJupyterSession.ts
  src/client/datascience/raw-kernel/rawSession.ts
  src/test/datascience/uiTests/notebookHelpers.ts
  src/test/datascience/uiTests/notebookUi.ts
Labels: skip news

#12686 Add icon to restart kernel for VSC Notebooks
  package.json
  resources/dark/restart-kernel.svg
  resources/light/restart-kernel.svg
  src/client/common/application/notebook.ts
  src/client/datascience/constants.ts
  src/client/datascience/context/activeEditorContext.ts
  src/client/datascience/interactive-common/notebookProvider.ts
  src/client/datascience/notebook/executionService.ts
  src/client/datascience/notebook/notebookEditor.ts
  src/client/datascience/notebook/notebookEditorProvider.ts
  src/client/datascience/types.ts
Labels: skip news

#12471 Update to Jedi 0.17.1
  ThirdPartyNotices-Distribution.txt
  news/1 Enhancements/12486.md
  requirements.in
  requirements.txt
Labels: external contributor

#12701 Merge back release into master
  CHANGELOG.md
  news/1 Enhancements/10744.md
  news/1 Enhancements/12249.md
  news/2 Fixes/10587.md
  news/2 Fixes/12155.md
  news/2 Fixes/12225.md
  news/2 Fixes/12246.md
  news/2 Fixes/12285.md
  news/2 Fixes/12389.md
  news/2 Fixes/12429.md
  news/2 Fixes/12580.md
  news/2 Fixes/12585.md
  news/2 Fixes/12614.md
  news/3 Code Health/12603.md
Labels: skip news

#12703 Tests for opening multiple notebooks and toggling
  src/client/datascience/notebook/contentProvider.ts
  src/client/datascience/notebook/helpers/cellUpdateHelpers.ts
  src/client/datascience/notebook/notebookEditor.ts
  src/client/datascience/notebook/notebookEditorProvider.ts
  src/client/datascience/notebook/types.ts
  src/test/common.ts
  src/test/datascience/notebook/empty.py
  src/test/datascience/notebook/helper.ts
  src/test/datascience/notebook/notebookEditorProvider.ds.test.ts
  src/test/initialize.ts
Labels: skip news

#12707 Fix #12705: Tests broken due to Prospector / Python 2.7 incompatibility
  build/test-requirements.txt
Labels: skip news

#12677 Remove language server survey
  build/existingFiles.json
  package.nls.json
  package.nls.nl.json
  package.nls.ru.json
  package.nls.zh-tw.json
  src/client/activation/languageClientMiddleware.ts
  src/client/activation/languageServer/manager.ts
  src/client/activation/node/manager.ts
  src/client/activation/serviceRegistry.ts
  src/client/common/types.ts
  src/client/common/utils/localize.ts
  src/client/languageServices/languageServerSurveyBanner.ts
  src/test/activation/serviceRegistry.unit.test.ts
  src/test/common/utils/localize.functional.test.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/testing/banners/languageServerSurvey.unit.test.ts
Labels: skip news

#12702 Add link to python.dataScience.alwaysTrustNotebooks setting
  package.json
  package.nls.json
  src/client/common/utils/localize.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
Labels: skip news

#12711 Add some logging to a flaky test
  src/test/common/process/pythonDaemonPool.unit.test.ts
Labels: skip news

#12721 Log diagnosis info and Increase timeout for flaky tests & hooks
  src/test/common.ts
  src/test/common/terminals/environmentActivationProviders/terminalActivation.testvirtualenvs.ts
  src/test/format/extension.sort.test.ts
  src/test/testing/pytest/pytest.run.test.ts
Labels: skip news

#12734 Use os.realpath instead of assuming location of jupyter kernels
  src/client/datascience/common.ts
  src/client/datascience/jupyter/kernels/jupyterKernelSpec.ts
  src/client/datascience/jupyter/kernels/kernelService.ts
  src/client/datascience/kernel-launcher/kernelFinder.ts
  src/test/datascience/kernelFinder.unit.test.ts
Labels: skip news

#12712 Put trusted notebooks behind an experiment
  src/client/common/experiments/groups.ts
  src/client/datascience/interactive-common/interactiveWindowTypes.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/interactive-ipynb/trustService.ts
  src/datascience-ui/history-react/interactivePanel.tsx
  src/datascience-ui/interactive-common/jupyterInfo.tsx
  src/datascience-ui/interactive-common/mainState.ts
  src/datascience-ui/interactive-common/redux/store.ts
  src/datascience-ui/native-editor/nativeEditor.tsx
  src/datascience-ui/native-editor/redux/reducers/creation.ts
  src/datascience-ui/native-editor/toolbar.tsx
  src/test/datascience/interactivePanel.functional.test.tsx
  src/test/datascience/nativeEditor.toolbar.functional.test.tsx
  src/test/datascience/trustService.unit.test.ts
Labels: skip news

#12755 Disable trust message button if notebook is trusted
  src/datascience-ui/interactive-common/common.css
  src/datascience-ui/interactive-common/jupyterInfo.tsx
Labels: skip news

#12775 Update experiments.json for raw kernel
  experiments.json
Labels: skip news

#12758 Don't indicate dirty when trust changes
  src/client/datascience/notebookStorage/baseModel.ts
Labels: skip news

#12776 Consolidate python envs component registration
  src/client/extensionInit.ts
  src/client/interpreter/serviceRegistry.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/common/installer.test.ts
  src/test/common/moduleInstaller.test.ts
  src/test/common/variables/envVarsProvider.multiroot.test.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/format/extension.format.test.ts
  src/test/format/extension.sort.test.ts
  src/test/interpreters/serviceRegistry.unit.test.ts
  src/test/linters/lint.multiroot.test.ts
  src/test/pythonEnvironments/main.unit.test.ts
  src/test/refactor/extension.refactor.extract.method.test.ts
  src/test/refactor/extension.refactor.extract.var.test.ts
  src/test/serviceRegistry.ts
  src/test/testing/debugger.test.ts
  src/test/testing/nosetest/nosetest.disovery.test.ts
  src/test/testing/nosetest/nosetest.run.test.ts
  src/test/testing/nosetest/nosetest.test.ts
  src/test/testing/pytest/pytest.discovery.test.ts
  src/test/testing/pytest/pytest.run.test.ts
  src/test/testing/pytest/pytest.test.ts
  src/test/testing/rediscover.test.ts
  src/test/testing/stoppingDiscoverAndTest.test.ts
  src/test/testing/unittest/unittest.discovery.test.ts
  src/test/testing/unittest/unittest.run.test.ts
  src/test/testing/unittest/unittest.test.ts
Labels: skip news

#12789 Allow user to opt into/out of trusted nb exp
  package.json
Labels: skip news

#12607 Remove gather from the Python Extension
  build/ci/templates/steps/initialization.yml
  build/webpack/webpack.extension.config.js
  package.json
  package.nls.json
  src/client/common/types.ts
  src/client/common/utils/localize.ts
  src/client/datascience/constants.ts
  src/client/datascience/gather/gather.ts
  src/client/datascience/gather/gatherListener.ts
  src/client/datascience/gather/gatherLogger.ts
  src/client/datascience/serviceRegistry.ts
  src/client/datascience/types.ts
  src/client/datascience/webViewHost.ts
  src/client/telemetry/index.ts
  src/datascience-ui/history-react/interactiveCell.tsx
  src/datascience-ui/native-editor/nativeCell.tsx
  src/datascience-ui/native-editor/nativeEditor.tsx
  src/datascience-ui/react-common/settingsReactSide.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/gather/gather.unit.test.ts
  src/test/datascience/interactiveWindow.functional.test.tsx
  src/test/datascience/mockJupyterNotebook.ts
  types/@msrvida-python-program-analysis/cell.d.ts
  types/@msrvida-python-program-analysis/cellslice.d.ts
  types/@msrvida-python-program-analysis/control-flow.d.ts
  types/@msrvida-python-program-analysis/data-flow.d.ts
  types/@msrvida-python-program-analysis/graph.d.ts
  types/@msrvida-python-program-analysis/index.d.ts
  types/@msrvida-python-program-analysis/log-slicer.d.ts
  types/@msrvida-python-program-analysis/logutil.d.ts
  types/@msrvida-python-program-analysis/printNode.d.ts
  types/@msrvida-python-program-analysis/program-builder.d.ts
  types/@msrvida-python-program-analysis/python-parser.d.ts
  types/@msrvida-python-program-analysis/rewrite-magics.d.ts
  types/@msrvida-python-program-analysis/set.d.ts
  types/@msrvida-python-program-analysis/slice.d.ts
  types/@msrvida-python-program-analysis/specs/index.d.ts
  types/@msrvida-python-program-analysis/symbol-table.d.ts
Labels: skip news

#12792 Simplify interpreter filter
  src/client/interpreter/locators/types.ts
  src/client/pythonEnvironments/discovery/locators/index.ts
  src/client/pythonEnvironments/discovery/locators/services/interpreterFilter.ts
  src/client/pythonEnvironments/discovery/locators/services/windowsStoreInterpreter.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/pythonEnvironments/discovery/locators/index.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/interpreterFilter.unit.test.ts
  src/test/pythonEnvironments/legacyIOC.unit.test.ts
Labels: skip news

#12769 Fixes for trusted notebooks
  src/datascience-ui/interactive-common/jupyterInfo.tsx
Labels: skip news

#12796 Fix perf yaml
  build/ci/performance/perfJobs.yaml
Labels: skip news

#12710 Enable logging in DS tests
  package.json
  src/test/datascience/.vscode/settings.json
  src/test/datascience/dsTestSetup.ts
Labels: skip news

#12801 Fixes related to clearing cells in notebooks
  src/client/datascience/notebook/executionService.ts
  src/client/datascience/notebook/helpers/cellUpdateHelpers.ts
  src/client/datascience/notebookStorage/vscNotebookModel.ts
  src/test/datascience/notebook/cellEditSyncService.ds.test.ts
  src/test/datascience/notebook/cellOutput.ds.test.ts
  src/test/datascience/notebook/contentProvider.ds.test.ts
  src/test/datascience/notebook/edit.ds.test.ts
  src/test/datascience/notebook/executionErrors.ds.test.ts
  src/test/datascience/notebook/executionService.ds.test.ts
  src/test/datascience/notebook/helper.ts
  src/test/datascience/notebook/interrupRestart.ds.test.ts
  src/test/datascience/notebook/notebookEditorProvider.ds.test.ts
  src/test/datascience/notebook/saving.ds.test.ts
  src/test/datascience/notebook/with3CellsAndOutput.ipynb
  src/test/format/extension.format.ds.test.ts
Labels: skip news

#12807 Ability to show/hide interpreter stastubar
  src/client/interpreter/contracts.ts
  src/client/interpreter/display/index.ts
  src/client/interpreter/serviceRegistry.ts
  src/test/datascience/notebook/saving.ds.test.ts
  src/test/interpreters/display.unit.test.ts
Labels: skip news

#12794 Removed svg output from notebooks when exporting to PDF
  .vscode/launch.json
  src/client/datascience/export/exportManager.ts
  src/client/datascience/export/exportUtil.ts
  src/test/datascience/export/exportManager.test.ts
  src/test/datascience/export/exportUtil.test.ts
  src/test/datascience/export/testPDF.ipynb
Labels: skip news

#12795 PyEnvs: Register proxies with the DI framework to replace @injectable usage.
  src/client/common/process/pythonExecutionFactory.ts
  src/client/common/terminal/environmentActivationProviders/pipEnvActivationProvider.ts
  src/client/interpreter/contracts.ts
  src/client/interpreter/helpers.ts
  src/client/interpreter/interpreterService.ts
  src/client/interpreter/locators/types.ts
  src/client/interpreter/virtualEnvs/index.ts
  src/client/pythonEnvironments/discovery/locators/helpers.ts
  src/client/pythonEnvironments/discovery/locators/index.ts
  src/client/pythonEnvironments/discovery/locators/progressService.ts
  src/client/pythonEnvironments/discovery/locators/services/KnownPathsService.ts
  src/client/pythonEnvironments/discovery/locators/services/baseVirtualEnvService.ts
  src/client/pythonEnvironments/discovery/locators/services/cacheableLocatorService.ts
  src/client/pythonEnvironments/discovery/locators/services/condaEnvFileService.ts
  src/client/pythonEnvironments/discovery/locators/services/condaEnvService.ts
  src/client/pythonEnvironments/discovery/locators/services/condaService.ts
  src/client/pythonEnvironments/discovery/locators/services/currentPathService.ts
  src/client/pythonEnvironments/discovery/locators/services/globalVirtualEnvService.ts
  src/client/pythonEnvironments/discovery/locators/services/hashProvider.ts
  src/client/pythonEnvironments/discovery/locators/services/hashProviderFactory.ts
  src/client/pythonEnvironments/discovery/locators/services/interpreterWatcherBuilder.ts
  src/client/pythonEnvironments/discovery/locators/services/pipEnvService.ts
  src/client/pythonEnvironments/discovery/locators/services/pipEnvServiceHelper.ts
  src/client/pythonEnvironments/discovery/locators/services/windowsRegistryService.ts
  src/client/pythonEnvironments/discovery/locators/services/windowsStoreInterpreter.ts
  src/client/pythonEnvironments/discovery/locators/services/workspaceVirtualEnvService.ts
  src/client/pythonEnvironments/discovery/locators/services/workspaceVirtualEnvWatcherService.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/interpreters/virtualEnvManager.unit.test.ts
  src/test/interpreters/virtualEnvs/index.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/hasProviderFactory.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/interpreterWatcherBuilder.unit.test.ts
  src/test/pythonEnvironments/legacyIOC.unit.test.ts
  src/test/testing/pytest/pytest.discovery.test.ts
  src/test/testing/pytest/pytest.run.test.ts
Labels: skip news

#12814 Update change log, version, and tpn
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
  news/1 Enhancements/11678.md
  news/1 Enhancements/12056.md
  news/1 Enhancements/12146.md
  news/1 Enhancements/12195.md
  news/1 Enhancements/12375.md
  news/1 Enhancements/12446.md
  news/1 Enhancements/12486.md
  news/1 Enhancements/12533.md
  news/1 Enhancements/12596.md
  news/1 Enhancements/12611.md
  news/1 Enhancements/12694.md
  news/1 Enhancements/12732.md
  news/1 Enhancements/12764.md
  news/1 Enhancements/9679.md
  news/2 Fixes/10579.md
  news/2 Fixes/10993.md
  news/2 Fixes/11254.md
  news/2 Fixes/11281.md
  news/2 Fixes/11347.md
  news/2 Fixes/11412.md
  news/2 Fixes/11459.md
  news/2 Fixes/11584.md
  news/2 Fixes/11691.md
  news/2 Fixes/11749.md
  news/2 Fixes/11758.md
  news/2 Fixes/11796.md
  news/2 Fixes/11830.md
  news/2 Fixes/12046.md
  news/2 Fixes/12180.md
  news/2 Fixes/12206.md
  news/2 Fixes/12208.md
  news/2 Fixes/12227.md
  news/2 Fixes/12231.md
  news/2 Fixes/12330.md
  news/2 Fixes/12355.md
  news/2 Fixes/12460.md
  news/2 Fixes/12588.md
  news/2 Fixes/12773.md
  news/3 Code Health/11445.md
  news/3 Code Health/11699.md
  news/3 Code Health/11896.md
  news/3 Code Health/11993.md
  news/3 Code Health/11996.md
  news/3 Code Health/12101.md
  news/3 Code Health/12116.md
  news/3 Code Health/12140.md
  news/3 Code Health/12238.md
  news/3 Code Health/12539.md
  news/3 Code Health/12656.md
  news/3 Code Health/12722.md
  news/3 Code Health/9837.md
  package-lock.json
  package.json
Labels: skip news

#12816 Update version
  package-lock.json
  package.json
Labels: skip news

#12815 Changed default save name when exporting from interactive window
  src/client/common/application/commands.ts
  src/client/datascience/commands/exportCommands.ts
  src/client/datascience/export/exportManager.ts
  src/client/datascience/export/exportManagerDependencyChecker.ts
  src/client/datascience/export/exportManagerFileOpener.ts
  src/client/datascience/export/exportManagerFilePicker.ts
  src/client/datascience/export/types.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/interactive-window/interactiveWindow.ts
  src/test/datascience/export/exportManager.test.ts
  src/test/datascience/export/exportManagerFileOpener.unit.test.ts
  src/test/datascience/nativeEditor.functional.test.tsx
Labels: skip news

#12820 Bug fix for trusted notebooks
  src/client/datascience/notebookStorage/baseModel.ts
Labels: skip news

#12823 Update model.isTrusted on trust change (#12820)
  src/client/datascience/notebookStorage/baseModel.ts
Labels: skip news

#12793 Include notebook renderers in extension
  gulpfile.js
  package.json
  src/client/datascience/notebook/integration.ts
  src/client/datascience/notebook/notebookEditorProvider.ts
Labels: skip news

#12839 Reduce visual complexity of trust prompt
  package.nls.json
  src/client/common/utils/localize.ts
  src/client/datascience/interactive-ipynb/digestStorage.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
Labels: skip news

#12847 Reduce visual complexity of trust prompt (#12839)
  package.nls.json
  src/client/common/utils/localize.ts
  src/client/datascience/interactive-ipynb/digestStorage.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
Labels: skip news

#12852 Revert settings changes when opting out of Native NB Experiment
  src/client/datascience/notebook/integration.ts
Labels: skip news

#12879 Ability to export VS Code Native notebooks
  package.json
  resources/dark/export_to_python.svg
  resources/light/export_to_python.svg
  src/client/common/application/commands.ts
  src/client/datascience/commands/exportCommands.ts
Labels: skip news

#12882 Fixes to exporting of notebook to html
  src/client/datascience/export/exportBase.ts
  src/client/datascience/export/exportManager.ts
  src/client/datascience/export/exportManagerFilePicker.ts
  src/client/datascience/export/exportUtil.ts
Labels: skip news

#12818 Add trust feature for VS Code Notebooks
  build/ci/vscode-python-pr-validation.yaml
  package.json
  package.nls.json
  resources/dark/trusted.svg
  resources/dark/un-trusted.svg
  resources/light/run-file.svg
  resources/light/trusted.svg
  resources/light/un-trusted.svg
  src/client/common/application/commands.ts
  src/client/datascience/constants.ts
  src/client/datascience/context/activeEditorContext.ts
  src/client/datascience/export/exportUtil.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/interactive-ipynb/nativeEditorProvider.ts
  src/client/datascience/interactive-ipynb/nativeEditorStorage.ts
  src/client/datascience/interactive-ipynb/notebookStorageProvider.ts
  src/client/datascience/interactive-ipynb/trustCommandHandler.ts
  src/client/datascience/notebook/contentProvider.ts
  src/client/datascience/notebook/executionService.ts
  src/client/datascience/notebook/helpers/cellUpdateHelpers.ts
  src/client/datascience/notebook/helpers/helpers.ts
  src/client/datascience/notebook/notebookEditorProvider.ts
  src/client/datascience/notebook/notebookTrustHandler.ts
  src/client/datascience/notebook/serviceRegistry.ts
  src/client/datascience/serviceRegistry.ts
  src/client/datascience/types.ts
  src/test/datascience/.vscode/settings.json
  src/test/datascience/export/exportUtil.test.ts
  src/test/datascience/interactive-common/trustCommandHandler.unit.test.ts
  src/test/datascience/interactive-common/trustService.unit.test.ts
  src/test/datascience/interactive-ipynb/nativeEditorStorage.unit.test.ts
  src/test/datascience/notebook/contentProvider.unit.test.ts
  src/test/datascience/notebook/helper.ts
  src/test/datascience/notebook/helpers.unit.test.ts
  src/test/datascience/notebook/notebookTrustHandler.unit.test.ts
Labels: skip news

#12883 Update warning message when opening nb in two different editors
  package.nls.json
  src/client/common/utils/localize.ts
Labels: skip news

#12863 Made exporting notebooks cancellable
  package.nls.json
  src/client/common/utils/localize.ts
  src/client/datascience/export/exportBase.ts
  src/client/datascience/export/exportManager.ts
  src/client/datascience/export/exportToHTML.ts
  src/client/datascience/export/exportToPDF.ts
  src/client/datascience/export/exportToPython.ts
  src/client/datascience/export/types.ts
  src/client/datascience/progress/progressReporter.ts
  src/test/datascience/export/exportManager.test.ts
  src/test/datascience/export/exportToHTML.test.ts
  src/test/datascience/export/exportToPython.test.ts
Labels: skip news

#12877 Port python 2.7 fix to release
  CHANGELOG.md
  src/client/datascience/kernel-launcher/kernelLauncherDaemon.ts
  src/client/datascience/kernel-launcher/kernelProcess.ts
  src/test/datascience/kernel-launcher/kernelLauncherDaemon.unit.test.ts
Labels: skip news

#12886 Fixed export manager test
  src/test/datascience/export/exportManager.test.ts
Labels: skip news

#12888 Make trusted message visible on dark backgrounds
  src/datascience-ui/interactive-common/trustMessage.tsx
Labels: skip news

#12895 fix collapse all color
  src/datascience-ui/react-common/images/CollapseAll/CollapseAll_16x_vscode_dark.svg
Labels: skip news

#12897 port color fix on collapse all (#12895)
  CHANGELOG.md
  src/datascience-ui/react-common/images/CollapseAll/CollapseAll_16x_vscode_dark.svg
Labels: skip news

#12904 Closing a notebook marked as trusted shouldn't trigger the save modal
  src/client/datascience/notebookStorage/notebookModel.ts
Labels: skip news

#12905 Gray out the bottom "insert cell below" button for untrusted notebooks
  src/datascience-ui/native-editor/addCellLine.tsx
Labels: skip news

#12812 Log digest file name when updating trust
  src/client/datascience/interactive-ipynb/digestStorage.ts
Labels: skip news

#12902 Fix regressions in trusted notebooks
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/interactive-ipynb/trustCommandHandler.ts
Labels: skip news

#12913 Recover from ENOENT due to missing parent dir when trusting notebook
  src/client/datascience/interactive-ipynb/digestStorage.ts
Labels: skip news

#12914 Disable keydown on native cells in untrusted notebooks
  src/datascience-ui/native-editor/nativeCell.tsx
Labels: skip news

#12929 Port trust fixes
  src/client/datascience/interactive-ipynb/digestStorage.ts
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/interactive-ipynb/trustCommandHandler.ts
  src/datascience-ui/native-editor/nativeCell.tsx
Labels: skip news

#12934 Hide editor icons when editor is not a notebook
  package.json
Labels: skip news

#12939 Only allow Enter / NumpadEnter without ctrl/shift/alt
  src/datascience-ui/native-editor/nativeCell.tsx
Labels: skip news

#12940 update testplan with docker instructions for mac / linux
  .github/test_plan.md
Labels: skip news

#12935 Hide editor icons when editor is not a notebook (#12934)
  package.json
Labels: skip news

#12953 Refactored export related features
  src/client/datascience/export/exportDependencyChecker.ts
  src/client/datascience/export/exportFileOpener.ts
  src/client/datascience/export/exportManager.ts
  src/client/datascience/export/types.ts
  src/client/datascience/serviceRegistry.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/export/exportFileOpener.unit.test.ts
  src/test/datascience/export/exportManager.test.ts
Labels: skip news

#12955 Remove unused node memwatch
  package-lock.json
  package.json
Labels: skip news

#12956 Cherry-pick: Check for hideFromUser before activating current terminal (#12942)
  news/2 Fixes/11122.md
  src/client/providers/terminalProvider.ts
  src/test/providers/terminal.unit.test.ts
Labels: skip news

#12964 Send telemetry for notebook trust prompt selections
  src/client/datascience/constants.ts
  src/client/datascience/interactive-ipynb/trustCommandHandler.ts
  src/client/telemetry/index.ts
Labels: skip news

#12960 Fixes to JUPYTER_PATH
  src/client/datascience/kernel-launcher/kernelFinder.ts
  src/test/datascience/kernelFinder.unit.test.ts
Labels: skip news

#12950 Fixes for persisting trust
  src/client/datascience/interactive-ipynb/nativeEditorStorage.ts
  src/client/datascience/notebookStorage/baseModel.ts
Labels: skip news

#12961 Display survey for native notebooks on/after 1st August
  src/client/datascience/notebook/survey.ts
  src/test/datascience/notebook/survey.unit.test.ts
Labels: skip news

#12965 Port final trust fixes for release
  src/client/datascience/constants.ts
  src/client/datascience/interactive-ipynb/nativeEditorStorage.ts
  src/client/datascience/interactive-ipynb/trustCommandHandler.ts
  src/client/datascience/notebookStorage/baseModel.ts
  src/client/telemetry/index.ts
  src/datascience-ui/native-editor/nativeCell.tsx
Labels: skip news

#12853 Improve detection when LS is fully loaded for IntelliCode
  src/client/activation/languageServer/languageServerProxy.ts
  src/client/activation/node/languageServerProxy.ts
Labels: skip news

#12930 Remove reload experiment
  src/client/debugger/extension/configuration/resolvers/launch.ts
  src/client/debugger/extension/configuration/resolvers/launchConfigExperiment.ts
  src/client/debugger/extension/configuration/types.ts
  src/client/debugger/extension/serviceRegistry.ts
  src/test/debugger/extension/configuration/resolvers/launch.unit.test.ts
  src/test/debugger/extension/configuration/resolvers/launchConfigExperiments.unit.test.ts
  src/test/debugger/extension/serviceRegistry.unit.test.ts
  src/test/testing/common/debugLauncher.unit.test.ts
Labels: skip news

#12975 Display survey for native notebooks on/after 1st August (#12961)
  src/client/datascience/notebook/survey.ts
  src/test/datascience/notebook/survey.unit.test.ts
Labels: skip news

#12981 Hide the gather button while a cell is executing
  src/datascience-ui/history-react/interactiveCell.tsx
  src/datascience-ui/native-editor/nativeCell.tsx
Labels: skip news

#12984 Port hiding the gather button while a cell is executing to release
  src/datascience-ui/history-react/interactiveCell.tsx
  src/datascience-ui/native-editor/nativeCell.tsx
Labels: skip news

#12985 fix startup command tests
  src/test/datascience/notebook.functional.test.ts
Labels: skip news

#12990 Update renderers to use new Api
  src/client/datascience/notebook/constants.ts
  src/client/datascience/notebook/renderer.ts
  src/datascience-ui/renderers/constants.ts
  src/datascience-ui/renderers/index.tsx
  src/datascience-ui/renderers/render.tsx
  src/datascience-ui/renderers/webviewApi.d.ts
  src/test/standardTest.ts
Labels: skip news

#13002 Update date
  CHANGELOG.md
Labels: skip news

#13006 White backgrounds for vega plots
  src/datascience-ui/renderers/render.tsx
Labels: skip news

#13011 Up run by line by 20%
  experiments.json
Labels: skip news

#13010 Mention Pylance in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: skip news

#13025 Remove release notes from the start page
  StartPageReleaseNotes.md
  package.nls.json
  src/client/common/startPage/startPage.ts
  src/client/common/startPage/types.ts
  src/client/common/utils/localize.ts
  src/datascience-ui/startPage/startPage.css
  src/datascience-ui/startPage/startPage.tsx
Labels: skip news

#13032 Port remove release notes from the start page
  StartPageReleaseNotes.md
  package.nls.json
  src/client/common/startPage/startPage.ts
  src/client/common/startPage/types.ts
  src/client/common/utils/localize.ts
  src/datascience-ui/startPage/startPage.css
  src/datascience-ui/startPage/startPage.tsx
Labels: skip news

#13033 Run a cell in native notebook with shift+enter
  package.json
Labels: skip news

#13028 Add a sprint planning issues dashboard
  .vscodeignore
  sprint-planning.github-issues
Labels: area-internal, skip news, type-code health

#13026 Update the contributing guide to cover our weekly sprints
  CONTRIBUTING.md
Labels: area-internal, skip news, type-code health

#13059 Try using timeout
  src/test/common/process/pythonDaemonPool.unit.test.ts
Labels: skip news

#13057 Set cwd for native notebooks before executing code
  src/client/datascience/notebook/executionService.ts
Labels: skip news

#13062 Fix CI failures caused by nyc not building
  src/test/initialize.ts
Labels: skip news

#13055 Update codecov
  package-lock.json
  package.json
Labels: area-internal, skip news, type-code health

#13064 Ensure languageServer value is valid, send event during activate
  src/client/activation/activationService.ts
  src/client/common/configSettings.ts
  src/test/common/configSettings/configSettings.unit.test.ts
Labels: skip news

#13056 Adding some static analysis
  build/ci/vscode-python-ci-static-analysis.yaml
Labels: area-internal, skip news, type-code health

#13082 Enable credscan and bandit static analysis tool
  build/ci/vscode-python-ci-static-analysis.yaml
Labels: skip news

#13084 Add eslint and reporting to static analysis
  build/ci/TSAOptions.json
  build/ci/vscode-python-ci-static-analysis.yaml
Labels: skip news

#12817 Activate banner prompt for Pylance
  experiments.json
  package.json
  package.nls.json
  src/client/activation/activationService.ts
  src/client/activation/languageServer/activator.ts
  src/client/activation/node/languageServerFolderService.ts
  src/client/activation/none/activator.ts
  src/client/activation/serviceRegistry.ts
  src/client/common/application/applicationEnvironment.ts
  src/client/common/application/types.ts
  src/client/common/constants.ts
  src/client/common/experiments/groups.ts
  src/client/common/types.ts
  src/client/common/utils/localize.ts
  src/client/languageServices/proposeLanguageServerBanner.ts
  src/client/providers/jediProxy.ts
  src/test/activation/activationService.unit.test.ts
  src/test/activation/languageServer/activator.unit.test.ts
  src/test/activation/node/languageServerFolderService.unit.test.ts
  src/test/activation/serviceRegistry.unit.test.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/testing/banners/proposeNewLanguageServerBanner.unit.test.ts
Labels: skip news

#13087 Remove blank input
  build/ci/vscode-python-ci-static-analysis.yaml
Labels: skip news

#13037 Update to Jedi 0.17.2
  ThirdPartyNotices-Distribution.txt
  news/1 Enhancements/13037.md
  requirements.in
  requirements.txt
Labels: external contributor

#13079 Cherry pick, version change and change log update
  CHANGELOG.md
  experiments.json
  package-lock.json
  package.json
  package.nls.json
  src/client/activation/activationService.ts
  src/client/activation/languageServer/activator.ts
  src/client/activation/node/languageServerFolderService.ts
  src/client/activation/none/activator.ts
  src/client/activation/serviceRegistry.ts
  src/client/common/application/applicationEnvironment.ts
  src/client/common/application/types.ts
  src/client/common/configSettings.ts
  src/client/common/constants.ts
  src/client/common/experiments/groups.ts
  src/client/common/types.ts
  src/client/common/utils/localize.ts
  src/client/languageServices/proposeLanguageServerBanner.ts
  src/client/providers/jediProxy.ts
  src/test/activation/activationService.unit.test.ts
  src/test/activation/languageServer/activator.unit.test.ts
  src/test/activation/node/languageServerFolderService.unit.test.ts
  src/test/activation/serviceRegistry.unit.test.ts
  src/test/common/configSettings/configSettings.unit.test.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/testing/banners/proposeNewLanguageServerBanner.unit.test.ts
Labels: skip news

#13086 Fix the gather survey
  package.json
  package.nls.json
  src/client/common/application/commands.ts
  src/client/common/utils/localize.ts
  src/client/datascience/commands/commandRegistry.ts
  src/client/datascience/constants.ts
  src/client/datascience/gather/gatherListener.ts
  src/client/datascience/interactive-common/linkProvider.ts
  src/client/telemetry/index.ts
Labels: skip news

#13099 A bunch of fixes for nightly tests
  .vscode/launch.json
  package.nls.json
  src/client/common/utils/localize.ts
  src/client/datascience/jupyter/jupyterNotebook.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/interactiveWindow.functional.test.tsx
  src/test/datascience/nativeEditor.functional.test.tsx
  src/test/datascience/notebook.functional.test.ts
  src/test/datascience/testInteractiveWindowProvider.ts
  src/test/datascience/uiTests/notebookUi.ts
  src/test/initialize.ts
Labels: skip news

#13105 Port fix the gather survey (#13086)
  package.json
  package.nls.json
  src/client/common/application/commands.ts
  src/client/common/utils/localize.ts
  src/client/datascience/commands/commandRegistry.ts
  src/client/datascience/constants.ts
  src/client/datascience/gather/gatherListener.ts
  src/client/datascience/interactive-common/linkProvider.ts
  src/client/telemetry/index.ts
Labels: skip news

#13108 fix finish message to account for multiple interactive windows
  src/client/datascience/gather/gatherListener.ts
Labels: skip news

#13036 Change title of file explorer dialog when browsing for an interpreter
  news/1 Enhancements/12959.md
  package-lock.json
  package.json
  package.nls.json
  src/client/common/utils/localize.ts
  src/client/interpreter/configuration/interpreterSelector/commands/setInterpreter.ts
  src/test/configuration/interpreterSelector/commands/setInterpreter.unit.test.ts
Labels: external contributor

#13131 More nightly failures
  src/test/datascience/interactiveWindow.functional.test.tsx
  src/test/datascience/notebook.functional.test.ts
Labels: skip news

#13130 Catch errors from the gather extension
  src/client/datascience/constants.ts
  src/client/datascience/gather/gatherListener.ts
  src/client/datascience/gather/gatherLogger.ts
  src/client/telemetry/index.ts
Labels: skip news

#13135 Update RunByLine to 40%
  experiments.json
Labels: skip news

#13143 Update VS Code Notebook API
  src/client/datascience/interactive-ipynb/nativeEditor.ts
  src/client/datascience/notebook/executionService.ts
  src/client/datascience/notebook/notebookEditor.ts
  src/client/datascience/notebook/notebookEditorProvider.ts
  src/client/datascience/notebook/notebookKernel.ts
  src/test/datascience/notebook/cellOutput.ds.test.ts
  src/test/datascience/notebook/executionErrors.ds.test.ts
  src/test/datascience/notebook/helper.ts
  src/test/datascience/notebook/interrupRestart.ds.test.ts
  src/test/datascience/notebook/saving.ds.test.ts
  types/vscode-proposed/index.d.ts
  types/vscode.proposed.d.ts
  typings/vscode-proposed/index.d.ts
Labels: skip news

#13144 Move notebook storage related code into separate folder
  src/client/datascience/interactive-common/notebookProvider.ts
  src/client/datascience/interactive-ipynb/nativeEditorOldWebView.ts
  src/client/datascience/interactive-ipynb/nativeEditorProviderOld.ts
  src/client/datascience/interactive-ipynb/nativeEditorViewTracker.ts
  src/client/datascience/interactive-ipynb/trustCommandHandler.ts
  src/client/datascience/interactive-window/interactiveWindowCommandListener.ts
  src/client/datascience/notebook/contentProvider.ts
  src/client/datascience/notebook/executionService.ts
  src/client/datascience/notebook/notebookEditorProvider.ts
  src/client/datascience/notebookStorage/baseModel.ts
  src/client/datascience/notebookStorage/nativeEditorProvider.ts
  src/client/datascience/notebookStorage/nativeEditorStorage.ts
  src/client/datascience/notebookStorage/notebookStorageProvider.ts
  src/client/datascience/serviceRegistry.ts
  src/test/datascience/activation.unit.test.ts
  src/test/datascience/commands/commandRegistry.unit.test.ts
  src/test/datascience/commands/notebookCommands.functional.test.ts
  src/test/datascience/dataScienceIocContainer.ts
  src/test/datascience/datascienceSurveyBanner.unit.test.ts
  src/test/datascience/interactive-common/notebookProvider.unit.test.ts
  src/test/datascience/interactive-common/trustCommandHandler.unit.test.ts
  src/test/datascience/interactive-ipynb/nativeEditorProvider.functional.test.ts
  src/test/datascience/interactive-ipynb/nativeEditorStorage.unit.test.ts
  src/test/datascience/interactiveWindowCommandListener.unit.test.ts
  src/test/datascience/jupyter/jupyterCellOutputMimeTypeTracker.unit.test.ts
  src/test/datascience/mockCustomEditorService.ts
  src/test/datascience/nativeEditorViewTracker.unit.test.ts
  src/test/datascience/notebook/contentProvider.unit.test.ts
  src/test/datascience/testNativeEditorProvider.ts
Labels: skip news

#13145 INotebookEditor need not inherit IInteractiveBase
  src/client/datascience/types.ts
Labels: skip news

#13154 VSC NB doc is source of truth & INotebookModel is a wrapper
  src/client/datascience/constants.ts
  src/client/datascience/interactive-common/interactiveWindowTypes.ts
  src/client/datascience/interactive-ipynb/trustCommandHandler.ts
  src/client/datascience/notebook/cellEditSyncService.ts
  src/client/datascience/notebook/executionService.ts
  src/client/datascience/notebook/helpers/cellMappers.ts
  src/client/datascience/notebook/helpers/cellUpdateHelpers.ts
  src/client/datascience/notebook/helpers/executionHelpers.ts
  src/client/datascience/notebook/helpers/helpers.ts
  src/client/datascience/notebook/integration.ts
  src/client/datascience/notebook/notebookEditorProvider.ts
  src/client/datascience/notebook/notebookTrustHandler.ts
  src/client/datascience/notebook/serviceRegistry.ts
  src/client/datascience/notebookStorage/baseModel.ts
  src/client/datascience/notebookStorage/nativeEditorStorage.ts
  src/client/datascience/notebookStorage/notebookModel.ts
  src/client/datascience/notebookStorage/vscNotebookModel.ts
  src/client/datascience/types.ts
  src/client/telemetry/index.ts
  src/test/datascience/.vscode/settings.json
  src/test/datascience/interactive-common/trustCommandHandler.unit.test.ts
  src/test/datascience/notebook/cellOutput.ds.test.ts
  src/test/datascience/notebook/contentProvider.ds.test.ts
  src/test/datascience/notebook/contentProvider.unit.test.ts
  src/test/datascience/notebook/edit.ds.test.ts
  src/test/datascience/notebook/executionErrors.ds.test.ts
  src/test/datascience/notebook/executionService.ds.test.ts
  src/test/datascience/notebook/helper.ts
  src/test/datascience/notebook/helpers.unit.test.ts
  src/test/datascience/notebook/interrupRestart.ds.test.ts
  src/test/datascience/notebook/notebookEditorProvider.ds.test.ts
  src/test/datascience/notebook/notebookTrust.ds.test.ts
  src/test/datascience/notebook/notebookTrustHandler.unit.test.ts
  src/test/datascience/notebook/saving.ds.test.ts
  src/test/datascience/notebook/withOutput.ipynb
  src/test/datascience/notebook/withOutputForTrust.ipynb
  src/test/datascience/notebook/withOutputNew.ipynb
  src/test/format/extension.format.ds.test.ts
Labels: skip news

#12989 Update bug template with Pylance info
  .github/ISSUE_TEMPLATE/2_bug_report.md
Labels: skip news

#13187 Increase timeout for debugger 'after each' hook
  src/test/testing/debugger.test.ts
Labels: skip news

#13193 Error wasn't showing on notebooks
  src/client/datascience/gather/gatherListener.ts
Labels: skip news

#13207 Update workspace file to support debugging multiple extensions
  pvsc.code-workspace
Labels: skip news
