Repository microsoft/vscode-python, pull requests merged in 2021-07, with the labels that each got.

#16586 Remove diagnostics on notebook/iw close
  src/client/jupyter/languageserver/concatTextDocument.ts
  src/client/jupyter/languageserver/interactiveConcatTextDocument.ts
  src/client/jupyter/languageserver/nativeNotebookConcatTextDocument.ts
  src/client/jupyter/languageserver/notebookConcatDocument.ts
  src/client/jupyter/languageserver/notebookConverter.ts
  src/client/jupyter/languageserver/notebookMiddlewareAddon.ts
Labels: skip news, skip tests

#16607 apply system variables for poetry path
  news/2 Fixes/16607.md
  src/client/pythonEnvironments/common/externalDependencies.ts
  src/client/pythonEnvironments/discovery/locators/services/poetry.ts
Labels: skip tests

#16626 Disable insiders tests
  .github/workflows/build.yml
  .github/workflows/pr-check.yml
Labels: skip news

#16624 Update to latest jedi LS
  jedils_requirements.txt
Labels: skip news

#16559 Sort available environments by assumed usefulness
  news/1 Enhancements/16520.md
  package.json
  src/client/common/experiments/groups.ts
  src/client/interpreter/configuration/environmentTypeComparer.ts
  src/client/interpreter/configuration/interpreterComparer.ts
  src/client/interpreter/configuration/interpreterSelector/interpreterSelector.ts
  src/client/interpreter/configuration/types.ts
  src/client/interpreter/serviceRegistry.ts
  src/test/configuration/environmentTypeComparer.unit.test.ts
  src/test/configuration/interpreterSelector/interpreterSelector.unit.test.ts
  src/test/interpreters/serviceRegistry.unit.test.ts
Labels: skip package*.json

#16515 Correctly set `shellIdentificationSource`.
  news/2 Fixes/16517.md
  src/client/common/terminal/shellDetectors/settingsShellDetector.ts
Labels: skip tests

#16603 Make environment resolving faster by separating resolvers from locators
  src/client/interpreter/contracts.ts
  src/client/interpreter/interpreterService.ts
  src/client/pythonEnvironments/api.ts
  src/client/pythonEnvironments/base/info/env.ts
  src/client/pythonEnvironments/base/locator.ts
  src/client/pythonEnvironments/base/locatorUtils.ts
  src/client/pythonEnvironments/base/locators.ts
  src/client/pythonEnvironments/base/locators/common/resourceBasedLocator.ts
  src/client/pythonEnvironments/base/locators/common/wrappingLocator.ts
  src/client/pythonEnvironments/base/locators/composite/cachingLocator.ts
  src/client/pythonEnvironments/base/locators/composite/environmentsReducer.ts
  src/client/pythonEnvironments/base/locators/composite/environmentsResolver.ts
  src/client/pythonEnvironments/base/locators/composite/resolverUtils.ts
  src/client/pythonEnvironments/base/locators/lowLevel/filesLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/windowsKnownPathsLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/workspaceVirtualEnvLocator.ts
  src/client/pythonEnvironments/common/environmentIdentifier.ts
  src/client/pythonEnvironments/common/externalDependencies.ts
  src/client/pythonEnvironments/discovery/locators/index.ts
  src/client/pythonEnvironments/discovery/locators/services/conda.ts
  src/client/pythonEnvironments/discovery/locators/services/condaLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/condaService.ts
  src/client/pythonEnvironments/discovery/locators/services/customVirtualEnvLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/globalVirtualEnvronmentLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/poetryLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/posixKnownPathsLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/pyenvLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/windowsStoreLocator.ts
  src/client/pythonEnvironments/index.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/pythonEnvironments/base/locators.unit.test.ts
  src/test/pythonEnvironments/base/locators/composite/cachingLocator.unit.test.ts
  src/test/pythonEnvironments/base/locators/composite/environmentsReducer.unit.test.ts
  src/test/pythonEnvironments/base/locators/composite/environmentsResolver.unit.test.ts
  src/test/pythonEnvironments/base/locators/composite/resolverUtils.unit.test.ts
  src/test/pythonEnvironments/base/locators/lowLevel/windowsKnownPathsLocator.functional.test.ts
  src/test/pythonEnvironments/base/locators/lowLevel/workspaceVirtualEnvLocator.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/condaHelper.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/customVirtualEnvLocator.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/globalVirtualEnvironmentLocator.functional.test.ts
  src/test/pythonEnvironments/discovery/locators/index.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/poetryLocator.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/posixKnownPathsLocator.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/pyenvLocator.functional.test.ts
  src/test/pythonEnvironments/discovery/locators/windowsStoreLocator.unit.test.ts
Labels: skip news

#16634 Fix diagnostic position in concat document and proper clearance on document close
  src/client/jupyter/languageserver/concatTextDocument.ts
  src/client/jupyter/languageserver/interactiveConcatTextDocument.ts
  src/client/jupyter/languageserver/nativeNotebookConcatTextDocument.ts
  src/client/jupyter/languageserver/notebookConcatDocument.ts
  src/client/jupyter/languageserver/notebookConverter.ts
  src/client/jupyter/languageserver/notebookMiddlewareAddon.ts
Labels: skip news, skip tests

#16643 expose isProductVersionCompatible
  src/client/jupyter/jupyterIntegration.ts
Labels: skip news, skip tests

#16661 Preparing release candidate
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
  jedils_requirements.txt
  news/1 Enhancements/16520.md
  news/2 Fixes/15199.md
  news/2 Fixes/16368.md
  news/2 Fixes/16441.md
  news/2 Fixes/16517.md
  news/2 Fixes/16528.md
  news/2 Fixes/16607.md
  news/2 Fixes/16615.md
  package-lock.json
  package.json
Labels: skip news

#16663 update main version
  package-lock.json
  package.json
Labels: skip news

#16674 Make getInterpreters() API faster for subsequent calls
  src/client/common/experiments/helpers.ts
  src/client/interpreter/interpreterService.ts
Labels: skip news, skip tests

#16677 Fix 'Cannot read property 'resolveEnv' of undefined' error
  src/client/pythonEnvironments/base/locators/common/wrappingLocator.ts
Labels: skip news, skip tests

#16641 Use resolveEnv from windows registry locator to create registry resolver
  src/client/pythonEnvironments/base/locators/composite/resolverUtils.ts
  src/client/pythonEnvironments/common/windowsUtils.ts
  src/client/pythonEnvironments/discovery/locators/services/windowsRegistryLocator.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/pythonEnvironments/base/locators/composite/environmentsResolver.unit.test.ts
  src/test/pythonEnvironments/base/locators/composite/resolverUtils.unit.test.ts
  src/test/pythonEnvironments/common/envlayouts/winreg/conda3/conda-meta/history
  src/test/pythonEnvironments/discovery/locators/windowsRegistryLocator.unit.test.ts
Labels: skip news

#16644 Change the way auto-selection works
  src/client/interpreter/autoSelection/index.ts
  src/client/interpreter/configuration/environmentTypeComparer.ts
  src/test/configuration/environmentTypeComparer.unit.test.ts
  src/test/interpreters/autoSelection/index.unit.test.ts
Labels: skip news

#16691 Skip Data Science smoke tests
  src/test/smoke/datascience.smoke.test.ts
Labels: skip news

#16696 Sort Settings Alphabetically #8406
  news/3 Code Health/8406.md
  package.json
Labels: skip package*.json

#16642 Do not resolve inside iterEnvs in low-level locators
  src/client/common/utils/async.ts
  src/client/pythonEnvironments/base/info/index.ts
  src/client/pythonEnvironments/base/locator.ts
  src/client/pythonEnvironments/base/locatorUtils.ts
  src/client/pythonEnvironments/base/locators.ts
  src/client/pythonEnvironments/base/locators/common/resourceBasedLocator.ts
  src/client/pythonEnvironments/base/locators/common/wrappingLocator.ts
  src/client/pythonEnvironments/base/locators/composite/environmentsReducer.ts
  src/client/pythonEnvironments/base/locators/composite/environmentsResolver.ts
  src/client/pythonEnvironments/base/locators/composite/resolverUtils.ts
  src/client/pythonEnvironments/base/locators/lowLevel/filesLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/fsWatchingLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/windowsKnownPathsLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/workspaceVirtualEnvLocator.ts
  src/client/pythonEnvironments/common/commonUtils.ts
  src/client/pythonEnvironments/common/windowsUtils.ts
  src/client/pythonEnvironments/discovery/locators/index.ts
  src/client/pythonEnvironments/discovery/locators/services/condaLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/customVirtualEnvLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/globalVirtualEnvronmentLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/poetryLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/posixKnownPathsLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/pyenvLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/windowsRegistryLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/windowsStoreLocator.ts
  src/client/pythonEnvironments/index.ts
  src/test/pythonEnvironments/base/common.ts
  src/test/pythonEnvironments/base/locators/composite/environmentsReducer.unit.test.ts
  src/test/pythonEnvironments/base/locators/composite/environmentsResolver.unit.test.ts
  src/test/pythonEnvironments/base/locators/composite/resolverUtils.unit.test.ts
  src/test/pythonEnvironments/base/locators/lowLevel/windowsKnownPathsLocator.functional.test.ts
  src/test/pythonEnvironments/base/locators/lowLevel/workspaceVirtualEnvLocator.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/condaHelper.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/customVirtualEnvLocator.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/envTestUtils.ts
  src/test/pythonEnvironments/discovery/locators/globalVirtualEnvironmentLocator.functional.test.ts
  src/test/pythonEnvironments/discovery/locators/poetryLocator.testvirtualenvs.ts
  src/test/pythonEnvironments/discovery/locators/poetryLocator.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/posixKnownPathsLocator.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/pyenvLocator.functional.test.ts
  src/test/pythonEnvironments/discovery/locators/watcherTestUtils.ts
  src/test/pythonEnvironments/discovery/locators/windowsRegistryLocator.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/windowsStoreLocator.test.ts
  src/test/pythonEnvironments/discovery/locators/windowsStoreLocator.unit.test.ts
Labels: skip news

#16697 Make resolving related to windows registry faster
  src/client/pythonEnvironments/base/info/index.ts
  src/client/pythonEnvironments/base/locator.ts
  src/client/pythonEnvironments/base/locators/composite/environmentsReducer.ts
  src/client/pythonEnvironments/base/locators/composite/resolverUtils.ts
  src/client/pythonEnvironments/base/locators/lowLevel/filesLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/windowsKnownPathsLocator.ts
  src/client/pythonEnvironments/common/windowsUtils.ts
  src/client/pythonEnvironments/discovery/locators/services/posixKnownPathsLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/windowsRegistryLocator.ts
  src/test/pythonEnvironments/base/common.ts
  src/test/pythonEnvironments/base/locators/composite/environmentsReducer.unit.test.ts
  src/test/pythonEnvironments/base/locators/composite/environmentsResolver.unit.test.ts
  src/test/pythonEnvironments/base/locators/composite/resolverUtils.unit.test.ts
  src/test/pythonEnvironments/base/locators/lowLevel/windowsKnownPathsLocator.functional.test.ts
  src/test/pythonEnvironments/discovery/locators/envTestUtils.ts
  src/test/pythonEnvironments/discovery/locators/posixKnownPathsLocator.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/windowsRegistryLocator.unit.test.ts
Labels: skip news

#16492 Add user settings in issue template
  resources/report_issue_template.md
  resources/report_issue_user_settings.json
  src/client/common/application/commands/reportIssueCommand.ts
  src/test/common/application/commands/issueTemplateVenv1.md
  src/test/common/application/commands/reportIssueCommand.unit.test.ts
Labels: skip news

#16722 Change version for release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip news

#16731 Update change log for release.
  CHANGELOG.md
  news/1 Enhancements/16461.md
  news/2 Fixes/16723.md
Labels: skip news

#16733 Fix autoselection when opening a python file directly
  CHANGELOG.md
  src/client/common/configSettings.ts
  src/test/common/configSettings/configSettings.pythonPath.unit.test.ts
Labels: skip news

#16734 Ignore cache when querying for interpreters during auto-selection
  src/client/activation/activationManager.ts
  src/client/interpreter/autoSelection/index.ts
  src/test/activation/activationManager.unit.test.ts
  src/test/interpreters/autoSelection/index.unit.test.ts
Labels: skip news

#16745 Update wheels to 3.9
  pythonFiles/install_debugpy.py
Labels: skip news

#16746 Update debugger via point release
  CHANGELOG.md
  package-lock.json
  package.json
  pythonFiles/install_debugpy.py
Labels: skip news

#16688 Remove unused telemetry events
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
Labels: skip news, skip tests

#16689 Lint files from sort interpreter and autoselection PRs
  .eslintignore
  src/client/interpreter/autoSelection/constants.ts
  src/client/interpreter/autoSelection/rules/baseRule.ts
  src/client/interpreter/autoSelection/rules/cached.ts
  src/client/interpreter/autoSelection/rules/currentPath.ts
  src/client/interpreter/autoSelection/rules/settings.ts
  src/client/interpreter/autoSelection/rules/system.ts
  src/client/interpreter/autoSelection/rules/winRegistry.ts
  src/client/interpreter/configuration/interpreterComparer.ts
  src/test/interpreters/autoSelection/rules/base.unit.test.ts
  src/test/interpreters/autoSelection/rules/cached.unit.test.ts
  src/test/interpreters/autoSelection/rules/currentPath.unit.test.ts
  src/test/interpreters/autoSelection/rules/settings.unit.test.ts
  src/test/interpreters/autoSelection/rules/system.unit.test.ts
  src/test/interpreters/autoSelection/rules/winRegistry.unit.test.ts
Labels: skip news

#16751 Fix package json formatting
  package.json
Labels: skip news, skip package*.json

#16763 Merge release back into main
  CHANGELOG.md
  news/1 Enhancements/16461.md
  src/client/activation/activationManager.ts
  src/client/common/configSettings.ts
  src/client/common/interpreterPathProxyService.ts
  src/client/common/serviceRegistry.ts
  src/client/common/types.ts
  src/client/interpreter/autoSelection/index.ts
  src/client/interpreter/display/index.ts
  src/test/activation/activationManager.unit.test.ts
  src/test/common/configSettings/configSettings.pythonPath.unit.test.ts
  src/test/common/interpreterPathProxyService.unit.test.ts
  src/test/interpreters/autoSelection/index.unit.test.ts
  src/test/interpreters/display.unit.test.ts
Labels: skip news

#16747 Fix venv tests for terminal activation
  .github/workflows/build.yml
  .github/workflows/nightly-coverage.yml
  .github/workflows/pr-check.yml
  src/client/pythonEnvironments/common/environmentManagers/conda.ts
  src/test/common/terminals/environmentActivationProviders/terminalActivation.testvirtualenvs.ts
  src/test/pythonEnvironments/base/locators/composite/resolverUtils.unit.test.ts
  src/test/pythonEnvironments/common/environmentManagers/conda.unit.test.ts
Labels: skip news

#16714 Replace deprecated vscode-test with @vscode/test-electron
  news/1 Enhancements/16765.md
  package-lock.json
  package.json
  src/test/debuggerTest.ts
  src/test/multiRootTest.ts
  src/test/standardTest.ts
Labels: skip tests

#16776 Point release with debugpy fix
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip news

#16779 Add action for validating testplan items
  .github/workflows/test-plan-item-validator.yml
Labels: skip news

#16709 Add new getting started page
  news/1 Enhancements/16678.md
  package.json
  resources/walkthrough/anaconda-install.png
  resources/walkthrough/change-python-interpreter-dark.gif
  resources/walkthrough/change-python-interpreter-hc.gif
  resources/walkthrough/change-python-interpreter-light.gif
  resources/walkthrough/datascience-learn-more.png
  resources/walkthrough/install-python-linux.md
  resources/walkthrough/install-python-macos.md
  resources/walkthrough/install-python-windows.md
  resources/walkthrough/interactive-window.png
  resources/walkthrough/learn-more.md
  resources/walkthrough/new-notebook.png
  resources/walkthrough/play-button-dark.png
  resources/walkthrough/python-docs-learn-more.png
  resources/walkthrough/run-and-debug-python-file-macOS.md
  resources/walkthrough/run-and-debug-python-file.md
Labels: skip package*.json, skip tests

#16791 Remove start page-related commands and display logic
  package.json
  src/client/common/startPage/startPage.ts
Labels: skip news, skip package*.json, skip tests

#16809 Mergeback changes from point release to main
  CHANGELOG.md
Labels: skip news

#16808 Activate extension on walkthrough
  package.json
Labels: skip news, skip package*.json

#16823 Remove MPLS as enum from package.json
  package.json
Labels: skip news, skip package*.json

#16820 Fixes for getting started page
  package.json
  resources/walkthrough/interactive-window-dark.png
  resources/walkthrough/interactive-window-hc.png
  resources/walkthrough/interactive-window-light.png
  resources/walkthrough/interactive-window.png
  resources/walkthrough/new-notebook-dark.png
  resources/walkthrough/new-notebook-hc.png
  resources/walkthrough/new-notebook-light.png
  resources/walkthrough/new-notebook.png
Labels: skip news, skip package*.json

#16832 Remove myself from the list of reviewers
  .github/assign-reviewers.yml
Labels: skip news
