Repository microsoft/vscode-python, pull requests merged in 2021-04, with the labels that each got.

#15817 Update to latest jedi
  jedils_requirements.in
  jedils_requirements.txt
Labels: skip news

#15826 Remove timeout for poetry commands
  src/client/pythonEnvironments/discovery/locators/services/poetry.ts
Labels: skip news, skip tests

#15833 Check for pyproject.toml file with a tool.poetry section before launching poetry binary
  src/client/pythonEnvironments/discovery/locators/services/poetry.ts
  src/client/pythonEnvironments/discovery/locators/services/poetryLocator.ts
  src/test/common/installer/poetryInstaller.unit.test.ts
  src/test/pythonEnvironments/common/envlayouts/poetry/project3/pyproject.toml
  src/test/pythonEnvironments/discovery/locators/lowLevel/poetry.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/poetryLocator.testvirtualenvs.ts
  src/test/pythonEnvironments/discovery/locators/poetryLocator.unit.test.ts
Labels: skip news

#15832 Remove jedi memory telemetry
  package-lock.json
  package.json
  src/client/activation/jedi/languageServerProxy.ts
  src/client/common/process/memory.ts
  src/client/common/process/rawProcessApis.ts
  src/client/providers/jediProxy.ts
Labels: skip news, skip tests

#15843 Ensure we use async filter when using path exists as predicate
  src/client/pythonEnvironments/base/locators/lowLevel/workspaceVirtualEnvLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/customVirtualEnvLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/globalVirtualEnvronmentLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/poetryLocator.ts
Labels: skip news, skip tests

#15850 Ensure insiders build is uploaded
  .github/workflows/insiders.yml
Labels: skip news

#15830 Add torch.profiler submodule telemetry
  news/3 Code Health/15825.md
  src/client/telemetry/constants.ts
  src/client/telemetry/importTracker.ts
  src/client/telemetry/index.ts
  src/client/tensorBoard/helpers.ts
Labels: skip tests

#15794 Only log assigned experiments in ExperimentsManager
  src/client/common/experiments/manager.ts
Labels: skip news, skip tests

#15857 Install additional jedilsp dependencies
  jedils_requirements.in
  jedils_requirements.txt
Labels: skip news

#15171 Expose a setting to allow a user modify the working directory of linters
  news/1 Enhancements/15170.md
  package.json
  src/client/common/configSettings.ts
  src/client/common/types.ts
  src/client/linters/baseLinter.ts
  src/client/linters/prospector.ts
  src/client/linters/pylint.ts
  src/test/linters/common.ts
  src/test/linters/lint.args.test.ts
  src/test/linters/lint.functional.test.ts
  src/test/linters/pylint.unit.test.ts
  src/test/mockClasses.ts
  src/test/pythonFiles/linting/cwd/.pylintrc
Labels: skip package*.json

#15862 Remove unused code
  src/client/language/braceCounter.ts
  src/client/language/textBuilder.ts
  src/test/language/braceCounter.unit.test.ts
  src/test/language/textBuilder.unit.test.ts
Labels: skip news

#15878 Add a CGManifest file
  cgmanifest.json
Labels: skip news

#15871 Get directories for global watching only if in global watching experiment
  src/client/pythonEnvironments/base/locators/lowLevel/fsWatchingLocator.ts
Labels: skip news, skip tests

#15860 Make poetry discovery faster
  src/client/common/utils/decorators.ts
  src/client/pythonEnvironments/common/externalDependencies.ts
  src/client/pythonEnvironments/discovery/locators/services/conda.ts
  src/client/pythonEnvironments/discovery/locators/services/poetry.ts
  src/client/pythonEnvironments/discovery/locators/services/poetryLocator.ts
  src/test/pythonEnvironments/discovery/locators/lowLevel/poetry.unit.test.ts
Labels: skip news, skip tests

#15883 Add command to clear extension related storage
  news/1 Enhancements/15883.md
  package.json
  package.nls.json
  src/client/common/constants.ts
  src/client/common/persistentState.ts
  src/client/common/serviceRegistry.ts
  src/test/common/persistentState.unit.test.ts
  src/test/linters/lint.provider.test.ts
Labels: skip package*.json

#15903 Update main version
  package-lock.json
  package.json
Labels: skip news

#15816 Add mailing list form to our start page
  package.nls.json
  src/client/common/utils/localize.ts
  src/startPage-ui/startPage/startPage.tsx
Labels: skip news, skip tests

#15904 Correct a news item
  CHANGELOG.md
Labels: skip news

#15894 Remove existing opt-in/out telemetry
  src/client/common/experiments/manager.ts
  src/client/common/experiments/service.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/test/common/experiments/service.unit.test.ts
Labels: skip news

#15898 Do not run `poetry env info -p` to get the type for local poetry environment
  src/client/pythonEnvironments/discovery/locators/services/poetry.ts
  src/test/pythonEnvironments/common/envlayouts/poetry/project4/pyproject.toml
  src/test/pythonEnvironments/discovery/locators/lowLevel/poetry.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/poetryLocator.unit.test.ts
Labels: skip news

#15911 Cherry pick "Do not run `poetry env info -p` to get the type for local poetry environment" into release
  src/client/pythonEnvironments/discovery/locators/services/poetry.ts
  src/test/pythonEnvironments/common/envlayouts/poetry/project4/pyproject.toml
  src/test/pythonEnvironments/discovery/locators/lowLevel/poetry.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/poetryLocator.unit.test.ts
Labels: skip news

#15838 Log error when checking if a module is installed
  news/3 Code Health/15837.md
  src/client/common/process/pythonEnvironment.ts
Labels: skip news, skip tests

#15932 Handle both API versions
  src/client/jupyter/languageserver/notebookConcatDocument.ts
  src/client/jupyter/languageserver/safeNotebookDocument.ts
Labels: skip news, skip tests

#15936 Handle both API versions (#15932)
  src/client/jupyter/languageserver/notebookConcatDocument.ts
  src/client/jupyter/languageserver/safeNotebookDocument.ts
Labels: skip news, skip tests

#15924 Reveal into selection after jump to source command
  news/1 Enhancements/15641.md
  src/client/tensorBoard/tensorBoardSession.ts
Labels: skip tests

#15930 Add tests using real poetry for discovery
  .github/workflows/insiders.yml
  .github/workflows/nightly-coverage.yml
  .github/workflows/pr-check.yml
  .github/workflows/pr-file-check.yml
  .github/workflows/release.yml
  build/ci/pyproject.toml
  src/test/pythonEnvironments/discovery/locators/poetryLocator.testvirtualenvs.ts
Labels: skip news

#15912 Use a more forgiving comparer when comparing version
  src/client/interpreter/autoSelection/index.ts
  src/client/interpreter/autoSelection/rules/baseRule.ts
  src/client/interpreter/helpers.ts
  src/client/pythonEnvironments/base/info/pythonVersion.ts
  src/client/pythonEnvironments/discovery/locators/services/condaLocatorService.ts
  src/client/pythonEnvironments/info/index.ts
  src/test/pythonEnvironments/base/info/pythonVersion.unit.test.ts
Labels: skip news

#15931 Wrap yields with a try catch
  src/client/pythonEnvironments/base/locators/lowLevel/filesLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/workspaceVirtualEnvLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/condaLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/customVirtualEnvLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/globalVirtualEnvronmentLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/poetryLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/posixKnownPathsLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/pyenvLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/windowsRegistryLocator.ts
Labels: skip news, skip tests

#15973 Proposed API Fixes
  src/client/jupyter/languageserver/notebookConverter.ts
  src/client/jupyter/languageserver/safeNotebookDocument.ts
  types/vscode-proposed/index.d.ts
  types/vscode.proposed.d.ts
  typings/vscode-proposed/index.d.ts
Labels: skip news, skip tests

#15989 Updating the version, change-log, and TPN for release
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
  package-lock.json
  package.json
Labels: skip news

#15991 Update TensorBoard launcher script to not use deprecated API
  pythonFiles/tensorboard_launcher.py
Labels: skip news, skip package*.json, skip tests

#15992 Port https://github.com/microsoft/vscode-python/pull/15991 to main
  pythonFiles/tensorboard_launcher.py
Labels: skip news, skip package*.json, skip tests

#16002 Merge from release to master
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
  news/1 Enhancements/15924.md
Labels: skip news

#16005 Use `asExternalUri` API to resolve TensorBoard iframe src
  news/2 Fixes/15807.md
  src/client/tensorBoard/tensorBoardSession.ts
Labels: skip tests

#15758 Enable running tests for folders in tests explorer
  news/1 Enhancements/15862.md
  package.json
  src/client/testing/common/services/testsStatusService.ts
Labels: skip package*.json, skip tests

#16011 Fix bugs reported via sonar
  src/client/pythonEnvironments/discovery/locators/services/posixKnownPathsLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/windowsRegistryLocator.ts
Labels: skip news, skip tests

#16013 Restrict GITHUB_TOKEN permissions
  .github/workflows/assign-reviewers.yml
  .github/workflows/issue-labels.yml
Labels: skip news

#15947 Ensure venvPath and venvFolders setting can only be set at User or Remote settings
  news/2 Fixes/15947.md
  package.json
Labels: skip package*.json, skip tests

#16012 Move find interpreter manual selection option to the top
  src/client/common/experiments/groups.ts
  src/client/interpreter/configuration/interpreterSelector/commands/setInterpreter.ts
  src/test/configuration/interpreterSelector/commands/setInterpreter.unit.test.ts
Labels: skip news

#15946 Improve opt-in/out telemetry
  src/client/common/experiments/service.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/test/common/experiments/service.unit.test.ts
Labels: skip news

#16050 Format files using Black 21.4b0
  pythonFiles/refactor.py
Labels: skip news, skip tests

#16061 Fix coverage failing due to Poetry test
  .github/workflows/nightly-coverage.yml
Labels: skip news, skip tests

#16030 Add automatic code reloading
  news/1 Enhancements/16029.md
  package.json
  src/client/debugger/types.ts
Labels: skip package*.json, skip tests

#16064 Remove rope
  .github/test_plan.md
  build/conda-functional-requirements.txt
  build/test-requirements.txt
  package.json
  package.nls.de.json
  package.nls.es.json
  package.nls.fr.json
  package.nls.it.json
  package.nls.ja.json
  package.nls.json
  package.nls.ko-kr.json
  package.nls.nl.json
  package.nls.pl.json
  package.nls.pt-br.json
  package.nls.ru.json
  package.nls.tr.json
  package.nls.zh-cn.json
  package.nls.zh-tw.json
  pythonFiles/refactor.py
  src/client/activation/common/activatorBase.ts
  src/client/activation/jedi.ts
  src/client/common/constants.ts
  src/client/common/installer/moduleInstaller.ts
  src/client/common/installer/productInstaller.ts
  src/client/common/installer/productNames.ts
  src/client/common/installer/productPath.ts
  src/client/common/installer/productService.ts
  src/client/common/installer/serviceRegistry.ts
  src/client/common/process/internal/scripts/index.ts
  src/client/common/types.ts
  src/client/extensionActivation.ts
  src/client/interpreter/configuration/interpreterSelector/commands/base.ts
  src/client/providers/renameProvider.ts
  src/client/providers/simpleRefactorProvider.ts
  src/client/refactor/proxy.ts
  src/test/common/installer.test.ts
  src/test/common/installer/installer.invalidPath.unit.test.ts
  src/test/common/installer/productPath.unit.test.ts
  src/test/common/installer/serviceRegistry.unit.test.ts
  src/test/linters/lint.multiroot.test.ts
  src/test/linters/lint.test.ts
  src/test/pythonFiles/refactoring/source folder/with empty line.py
  src/test/pythonFiles/refactoring/source folder/without empty line.py
  src/test/pythonFiles/refactoring/standAlone/refactor.py
  src/test/refactor/extension.refactor.extract.method.test.ts
  src/test/refactor/extension.refactor.extract.var.test.ts
  src/test/refactor/rename.test.ts
Labels: skip news, skip package*.json

#16071 Add the 'security-events' permission to the CodeQL workflow
  .github/workflows/codeql-analysis.yml
Labels: skip news

#15971 Block on displaying selected interpreter in the status bar on startup
  src/client/common/configuration/service.ts
  src/client/common/platform/fileSystem.ts
  src/client/common/platform/types.ts
  src/client/common/process/pythonEnvironment.ts
  src/client/common/variables/environment.ts
  src/client/extensionActivation.ts
  src/client/interpreter/autoSelection/index.ts
  src/client/interpreter/display/index.ts
  src/client/interpreter/interpreterService.ts
  src/test/common/configuration/service.unit.test.ts
  src/test/common/platform/filesystem.unit.test.ts
  src/test/common/process/pythonEnvironment.unit.test.ts
  src/test/common/variables/envVarsService.unit.test.ts
  src/test/interpreters/autoSelection/index.unit.test.ts
  src/test/interpreters/interpreterService.unit.test.ts
Labels: skip news
