Repository microsoft/vscode-python, pull requests merged in 2021-11, with the labels that each got.

#17892 Release candidate
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
  news/1 Enhancements/12289.md
  news/1 Enhancements/17590.md
  news/1 Enhancements/7793.md
  news/1 Enhancements/8427.md
  news/2 Fixes/10737.md
  news/2 Fixes/11924.md
  news/2 Fixes/14562.md
  news/2 Fixes/14730.md
  news/2 Fixes/15145.md
  news/2 Fixes/15181.md
  news/2 Fixes/15288.md
  news/2 Fixes/15522.md
  news/2 Fixes/16836.md
  news/2 Fixes/17019.md
  news/2 Fixes/17546.md
  news/2 Fixes/17561.md
  news/2 Fixes/17789.md
  news/2 Fixes/17811.md
  news/2 Fixes/17819.md
  news/2 Fixes/17823.md
  news/2 Fixes/17878.md
  news/2 Fixes/6352.md
  news/3 Code Health/16840.md
  news/3 Code Health/17795.md
  news/3 Code Health/17815.md
  news/3 Code Health/17834.md
  news/3 Code Health/17886.md
  news/3 Code Health/4060.md
  news/3 Code Health/7333.md
  package-lock.json
  package.json
Labels: skip news

#17893 Update main branch version
  package-lock.json
  package.json
Labels: skip news

#17891 Remove duplicate "clear workspace interpreter" command
  news/2 Fixes/17890.md
  package.json
Labels: skip package*.json

#17894 Remove experiments for refresh and failed tests buttons
  news/3 Code Health/17868.md
  package.json
  src/client/common/application/contextKeys.ts
  src/client/common/experiments/groups.ts
  src/client/testing/main.ts
Labels: skip package*.json, skip tests

#17915 Remove duplicate "body" attribute in issue form
  .github/ISSUE_TEMPLATE/1_new_bug_report.yml
Labels: skip news

#17908 Turn-off experiment logs when telemetry is disabled
  .github/ISSUE_TEMPLATE/1_new_bug_report.yml
  src/client/common/experiments/service.ts
Labels: skip news, skip tests

#17924 Update release version and date
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip news

#17963 Remove old discovery code and discovery experiments
  news/3 Code Health/17962.md
Labels: skip tests

#17968 Install pipenv only for Python 3 tests
  .github/workflows/build.yml
  .github/workflows/pr-check.yml
Labels: skip news, skip tests

#17898 Use same `pytest --rootdir` logic as test discovery
  news/2 Fixes/9553.md
  src/client/testing/testController/pytest/runner.ts
Labels: skip tests

#17969 Merge release-2021.11 into main
  CHANGELOG.md
Labels: skip news

#17947 Add stop beaker icon
  package.json
Labels: skip news, skip package*.json

#17970 Fix experiment logging
  src/client/common/experiments/service.ts
Labels: skip news, skip tests

#17705 Update package.nls.zh-tw.json
  package.nls.zh-tw.json
Labels: skip news

#17753 Added onDebugInitialConfigurations to activationEvents
  news/1 Enhancements/9557.md
  package.json
Labels: skip package*.json

#17965 Add tests for environments collection
  src/client/pythonEnvironments/base/info/env.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionCache.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/client/pythonEnvironments/index.ts
  src/test/pythonEnvironments/base/common.ts
  src/test/pythonEnvironments/base/locators/composite/envsCollectionService.unit.test.ts
  src/test/pythonEnvironments/base/locators/envTestUtils.ts
Labels: skip news

#17988 Update data science walkthrough illustrations
  package.json
  resources/walkthrough/create-notebook.svg
  resources/walkthrough/data-science.svg
  resources/walkthrough/interactive-window-dark.png
  resources/walkthrough/interactive-window-hc.png
  resources/walkthrough/interactive-window-light.png
  resources/walkthrough/interactive-window.svg
  resources/walkthrough/new-notebook-dark.png
  resources/walkthrough/new-notebook-hc.png
  resources/walkthrough/new-notebook-light.png
  resources/walkthrough/open-folder-dark.png
  resources/walkthrough/open-folder-hc.png
  resources/walkthrough/open-folder-light.png
  resources/walkthrough/open-folder.svg
Labels: skip news, skip package*.json

#18018 Increase conda activation timeout from 30s to 60s
  news/2 Fixes/18017.md
  src/client/interpreter/activation/service.ts
Labels: skip tests

#18020 Ensure executableSpecified is set correctly
  news/3 Code Health/18019.md
  src/client/linters/lintingEngine.ts
Labels: skip tests

#18026 Revert "Use python version 3.9 due to issues with pandas on 3.10
  .github/actions/smoke-tests/action.yml
  .github/workflows/build.yml
  .github/workflows/pr-check.yml
Labels: skip news

#18008 Mark tool paths scope as machine-overridable
  news/2 Fixes/18008.md
  package.json
Labels: skip package*.json

#17519 Only activate language servers when running in virtual workspaces
  news/1 Enhancements/17519.md
  package.json
  src/client/activation/activationManager.ts
  src/client/activation/activationService.ts
  src/client/activation/common/analysisOptions.ts
  src/client/activation/common/loadLanguageServerExtension.ts
  src/client/activation/extensionSurvey.ts
  src/client/activation/jedi/analysisOptions.ts
  src/client/activation/node/analysisOptions.ts
  src/client/activation/types.ts
  src/client/common/application/commands/reloadCommand.ts
  src/client/common/application/commands/reportIssueCommand.ts
  src/client/common/application/debugSessionTelemetry.ts
  src/client/common/application/types.ts
  src/client/common/application/workspace.ts
  src/client/common/insidersBuild/insidersExtensionService.ts
  src/client/common/persistentState.ts
  src/client/debugger/extension/adapter/activator.ts
  src/client/debugger/extension/configuration/launch.json/completionProvider.ts
  src/client/debugger/extension/configuration/launch.json/interpreterPathCommand.ts
  src/client/debugger/extension/configuration/launch.json/updaterService.ts
  src/client/debugger/extension/debugCommands.ts
  src/client/extension.ts
  src/client/extensionActivation.ts
  src/client/extensionInit.ts
  src/client/interpreter/configuration/interpreterSelector/commands/base.ts
  src/client/interpreter/display/progressDisplay.ts
  src/client/interpreter/virtualEnvs/condaInheritEnvPrompt.ts
  src/client/interpreter/virtualEnvs/virtualEnvPrompt.ts
  src/client/providers/codeActionProvider/main.ts
  src/client/providers/linterProvider.ts
  src/client/telemetry/importTracker.ts
  src/client/tensorBoard/nbextensionCodeLensProvider.ts
  src/client/tensorBoard/tensorBoardFileWatcher.ts
  src/client/tensorBoard/tensorBoardImportCodeLensProvider.ts
  src/client/tensorBoard/tensorBoardSessionProvider.ts
  src/client/tensorBoard/tensorBoardUsageTracker.ts
  src/client/tensorBoard/terminalWatcher.ts
  src/client/testing/common/testConfigurationManager.ts
  src/client/testing/common/updateTestSettings.ts
  src/client/testing/main.ts
  src/client/testing/testController/controller.ts
  src/client/testing/testController/serviceRegistry.ts
  src/test/activation/node/analysisOptions.unit.test.ts
Labels: skip package*.json

#17978 Don't add `cwd` argument when running all tests
  news/2 Fixes/17546.md
  src/client/testing/testController/pytest/runner.ts
Labels: skip tests

#17979 Don't interpret `--rootdir` as a test folder
  news/2 Fixes/16079.md
  src/client/testing/testController/pytest/arguments.ts
Labels: skip tests

#17987 Add comments for vscode-telemetry-extractor
  package-lock.json
  package.json
  src/client/telemetry/index.ts
Labels: skip news, skip tests

#18042 Use Python 3.9 for build workflow
  .github/actions/smoke-tests/action.yml
  .github/workflows/build.yml
  .github/workflows/pr-check.yml
Labels: skip news

#17998 Declare limited support for untrusted workspaces by only supporting Pylance
  news/1 Enhancements/18031.md
  package.json
  package.nls.json
  src/client/activation/activationManager.ts
  src/client/activation/activationService.ts
  src/client/activation/node/analysisOptions.ts
  src/client/activation/node/languageServerProxy.ts
  src/client/application/diagnostics/applicationDiagnostics.ts
  src/client/application/diagnostics/base.ts
  src/client/application/diagnostics/checks/envPathVariable.ts
  src/client/application/diagnostics/checks/pylanceDefault.ts
  src/client/application/diagnostics/checks/switchToDefaultLS.ts
  src/client/application/diagnostics/checks/upgradeCodeRunner.ts
  src/client/application/diagnostics/types.ts
  src/client/common/application/types.ts
  src/client/common/application/workspace.ts
  src/client/common/utils/localize.ts
  src/client/extension.ts
  src/client/extensionActivation.ts
  src/client/extensionInit.ts
  src/client/jupyter/jupyterIntegration.ts
  src/client/startupTelemetry.ts
  src/client/telemetry/index.ts
  src/test/activation/activationManager.unit.test.ts
  src/test/application/diagnostics/applicationDiagnostics.unit.test.ts
  types/vscode.proposed.d.ts
Labels: skip package*.json

#18066 Expose some more api to Jupyter Extension
  src/client/interpreter/activation/service.ts
  src/client/interpreter/activation/types.ts
  src/client/jupyter/jupyterIntegration.ts
Labels: skip news, skip tests

#18096 Update jedi language server to latest
  jedils_requirements.in
  jedils_requirements.txt
Labels: skip news

#18099 Enable A/B test with black being the default formatter
  package.json
Labels: skip news, skip package*.json
