Repository microsoft/vscode-python, pull requests merged in 2021-09, with the labels that each got.

#17170 Update version and change log
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip news

#17186 Fix casing of text in 'unittest' patterns quickpick.
  news/2 Fixes/17093.md
  src/client/testing/common/testConfigurationManager.ts
Labels: skip tests

#17178 Remove src/client/logging/* from .eslintignore
  .eslintignore
  news/3 Code Health/17181.md
  src/client/common/utils/decorators.ts
  src/client/logging/_global.ts
  src/client/logging/formatters.ts
  src/client/logging/index.ts
  src/client/logging/levels.ts
  src/client/logging/logger.ts
  src/client/logging/trace.ts
  src/client/logging/traceDecorators.ts
  src/client/logging/transports.ts
  src/client/logging/transports/consoleTransport.ts
  src/client/logging/transports/index.ts
  src/client/logging/transports/pythonOutputChannelTransport.ts
  src/client/logging/util.ts
Labels: skip news, skip tests

#17255 Fix tar vulnerabilities
  package-lock.json
Labels: skip news, skip package*.json

#17245 Clean up src/test/mocks/vsc/*
  .eslintignore
  src/test/mocks/vsc/arrays.ts
  src/test/mocks/vsc/charCode.ts
  src/test/mocks/vsc/extHostedTypes.ts
  src/test/mocks/vsc/htmlContent.ts
  src/test/mocks/vsc/index.ts
  src/test/mocks/vsc/position.ts
  src/test/mocks/vsc/range.ts
  src/test/mocks/vsc/selection.ts
  src/test/mocks/vsc/strings.ts
  src/test/mocks/vsc/telemetryReporter.ts
  src/test/mocks/vsc/uri.ts
  src/test/mocks/vsc/uuid.ts
  src/test/vscode-mock.ts
Labels: skip news, skip tests

#17257 Make the 'build vsix' composite action reference other actions
  .github/actions/build-vsix/action.yml
  .github/workflows/build.yml
  .github/workflows/pr-check.yml
Labels: skip news

#17244 Do path comparisons appropriately in the discovery component
  news/2 Fixes/17244.md
  src/client/pythonEnvironments/base/info/executable.ts
  src/client/pythonEnvironments/base/locators/composite/resolverUtils.ts
  src/client/pythonEnvironments/common/commonUtils.ts
  src/client/pythonEnvironments/common/environmentManagers/conda.ts
  src/client/pythonEnvironments/common/environmentManagers/pipenv.ts
  src/client/pythonEnvironments/common/environmentManagers/pyenv.ts
  src/client/pythonEnvironments/common/environmentManagers/simplevirtualenvs.ts
  src/client/pythonEnvironments/common/externalDependencies.ts
  src/test/pythonEnvironments/common/environmentManagers/poetry.unit.test.ts
Labels: skip tests

#17260 Introduct a lint composite action
  .github/actions/build-vsix/action.yml
  .github/actions/lint/action.yml
  .github/workflows/build.yml
  .github/workflows/pr-check.yml
Labels: skip news

#17262 Introduce a composite action for smoke tests
  .github/actions/build-vsix/action.yml
  .github/actions/lint/action.yml
  .github/actions/smoke-tests/action.yml
  .github/workflows/build.yml
  .github/workflows/pr-check.yml
Labels: skip news

#17271 Update run failed tests icon
  package.json
Labels: skip news, skip package*.json

#17275 Fix for filenames starting with py.
  news/2 Fixes/17270.md
  src/client/testing/testController/common/resultsHelper.ts
  src/client/testing/testController/common/testItemUtilities.ts
Labels: skip tests

#17304 Ensure we trigger discovery for the first time as part of extension activation
  news/2 Fixes/17303.md
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/client/pythonEnvironments/index.ts
Labels: skip tests

#17302 Fix npm vulnerabilities
  package-lock.json
  package.json
Labels: skip news

#17274 Fix parent path check
  src/client/pythonEnvironments/base/locators/lowLevel/fsWatchingLocator.ts
  src/client/pythonEnvironments/common/externalDependencies.ts
  src/client/pythonEnvironments/common/pythonBinariesWatcher.ts
  src/client/pythonEnvironments/legacyIOC.ts
Labels: skip news, skip tests

#17306 Fix for multiple directories in pytest args.
  news/2 Fixes/17281.md
  src/client/testing/testController/pytest/pytestController.ts
Labels: skip tests

#17311 Fix for a bunch of test issues.
  news/2 Fixes/17280.md
  news/2 Fixes/17285.md
  news/2 Fixes/17309.md
  pythonFiles/testing_tools/unittest_discovery.py
  src/client/common/process/internal/scripts/testing_tools.ts
  src/client/testing/testController/unittest/unittestController.ts
Labels: skip tests

#17313 Fix issue with in complete unittest runs.
  news/2 Fixes/17282.md
  pythonFiles/visualstudio_py_testlauncher.py
  src/client/testing/testController/unittest/runner.ts
Labels: skip tests

#17321 Update to new LSP middleware interface
  package-lock.json
  package.json
  src/client/activation/languageClientMiddleware.ts
  src/client/activation/languageClientMiddlewareBase.ts
Labels: skip news, skip tests

#17333 Point release version, change log, and TPN updates
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
  news/2 Fixes/17089.md
  news/2 Fixes/17144.md
  news/2 Fixes/17244.md
  news/2 Fixes/17280.md
  news/2 Fixes/17281.md
  news/2 Fixes/17282.md
  news/2 Fixes/17285.md
  news/2 Fixes/17303.md
  news/2 Fixes/17309.md
  news/2 Fixes/17325.md
  package-lock.json
  package.json
Labels: skip news

#17335 Correctly indicate when interpreter refresh has finished
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
Labels: skip news, skip tests

#17336 Correctly indicate when a refresh has finished
  CHANGELOG.md
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
Labels: skip news, skip tests

#17338 Fix refreshing progress display in the status bar
  news/2 Fixes/17338.md
  src/client/interpreter/contracts.ts
  src/client/interpreter/display/progressDisplay.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/client/pythonEnvironments/legacyIOC.ts
Labels: skip tests

#17348 Cherry pick fixes from main
  CHANGELOG.md
  src/client/testing/testController/common/resultsHelper.ts
  src/client/testing/testController/common/testItemUtilities.ts
Labels: skip news, skip tests

#17354 Fix for cached debug configuration
  news/2 Fixes/17353.md
  src/client/debugger/extension/configuration/debugConfigurationService.ts
Labels: skip tests

#17355 Cherry pick debug caching fix to release
  CHANGELOG.md
  src/client/debugger/extension/configuration/debugConfigurationService.ts
Labels: skip tests

#17358 Do not display workspace related envs if no workspace is open
  news/2 Fixes/17358.md
  src/client/pythonEnvironments/legacyIOC.ts
Labels: skip tests

#17339 Ensure we do not start a new discovery for an event if one is already scheduled
  news/2 Fixes/17339.md
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
Labels: skip tests

#17369 Fix for `unittest` ModuleNotFoundError when discovering tests
  news/2 Fixes/17363.md
  pythonFiles/testing_tools/unittest_discovery.py
Labels: skip tests

#17373 Improve display of lines in test output.
  news/2 Fixes/17111.md
  src/client/testing/testController/common/resultsHelper.ts
  src/client/testing/testController/common/utils.ts
  src/client/testing/testController/unittest/runner.ts
Labels: skip tests

#17375 Handle debug in terminal with undefined uri
  news/2 Fixes/17374.md
  src/client/debugger/extension/configuration/types.ts
  src/client/debugger/extension/debugCommands.ts
Labels: skip tests

#17402 Fix for buttons not showing up for test items.
  news/2 Fixes/17378.md
  src/client/testing/testController/pytest/pytestController.ts
Labels: skip tests

#17405 DS Product names were inadvertently removed
  src/client/common/installer/productNames.ts
Labels: skip news, skip tests

#17273 Replace Jedi with Jedi LSP
  .github/workflows/nightly-coverage.yml
  .github/workflows/pr-check.yml
  news/1 Enhancements/11995.md
  package.json
  src/client/activation/activationService.ts
  src/client/activation/common/defaultlanguageServer.ts
  src/client/activation/jedi/manager.ts
  src/client/activation/languageClientMiddleware.ts
  src/client/activation/languageClientMiddlewareBase.ts
  src/client/activation/languageServer/deprecationPrompt.ts
  src/client/activation/serviceRegistry.ts
  src/client/common/configSettings.ts
  src/client/common/experiments/groups.ts
  src/client/common/types.ts
  src/client/extensionActivation.ts
  src/client/jupyter/jupyterIntegration.ts
  src/test/activation/activationService.unit.test.ts
  src/test/activation/defaultLanguageServer.unit.test.ts
  src/test/activation/languageServer/deprecationPrompt.unit.test.ts
  src/test/activation/serviceRegistry.unit.test.ts
  src/test/common/configSettings/configSettings.unit.test.ts
  src/test/languageServers/jedi/autocomplete/base.test.ts
  src/test/languageServers/jedi/autocomplete/pep484.test.ts
  src/test/languageServers/jedi/autocomplete/pep526.test.ts
  src/test/languageServers/jedi/completionSource.unit.test.ts
  src/test/languageServers/jedi/definitions/hover.jedi.test.ts
  src/test/languageServers/jedi/definitions/navigation.test.ts
  src/test/languageServers/jedi/definitions/parallel.jedi.test.ts
  src/test/languageServers/jedi/lspSetup.ts
  src/test/languageServers/jedi/lspTeardown.ts
  src/test/languageServers/jedi/pythonSignatureProvider.unit.test.ts
  src/test/languageServers/jedi/signature/signature.jedi.test.ts
  src/test/languageServers/jedi/symbolProvider.unit.test.ts
Labels: skip package*.json

#17415 Use the built-in cache support of actions/setup-node
  .github/actions/build-vsix/action.yml
  .github/actions/lint/action.yml
  .github/actions/smoke-tests/action.yml
  .github/workflows/build.yml
  .github/workflows/nightly-coverage.yml
  .github/workflows/pr-check.yml
Labels: skip news

#17417 Fix broken build action
  .github/workflows/build.yml
Labels: skip news, skip tests

#17362 Ensure we correctly evaluate Unknown type before sending startup telemetry
  news/2 Fixes/17362.md
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/client/pythonEnvironments/common/environmentIdentifier.ts
  src/client/pythonEnvironments/common/environmentManagers/globalInstalledEnvs.ts
  src/client/startupTelemetry.ts
Labels: skip tests

#17407 Display a notification when using JediLSP with Python 2.7
  package.nls.json
  src/client/activation/activationService.ts
  src/client/application/diagnostics/checks/jediPython27NotSupported.ts
  src/client/application/diagnostics/constants.ts
  src/client/application/diagnostics/serviceRegistry.ts
  src/client/common/utils/localize.ts
  src/test/activation/activationService.unit.test.ts
  src/test/application/diagnostics/checks/jediPython27NotSupported.unit.test.ts
  src/test/application/diagnostics/serviceRegistry.unit.test.ts
Labels: skip news

#17418 Normalize spacing for `${{ ... }}` variables in GHA YAML files
  .github/workflows/build.yml
  .github/workflows/issue-labels.yml
  .github/workflows/nightly-coverage.yml
  .github/workflows/pr-check.yml
Labels: skip news

#17430 Add a "Lock Issues" cron job workflow
  .github/lock.yml
  .github/workflows/lock-issues.yml
Labels: skip news

#17428 Delete Jedi-related settings, and update default Pylint settings
  .github/test_plan.md
  news/1 Enhancements/11995.md
  news/1 Enhancements/3007.md
  package.json
  resources/report_issue_user_settings.json
  src/client/common/configSettings.ts
  src/client/common/types.ts
  src/client/linters/linterAvailability.ts
  src/client/linters/linterManager.ts
  src/client/linters/pylint.ts
  src/client/linters/serviceRegistry.ts
  src/client/linters/types.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/test/.vscode/settings.json
  src/test/common/configSettings/configSettings.unit.test.ts
  src/test/linters/common.ts
  src/test/linters/lint.functional.test.ts
  src/test/linters/lint.multilinter.test.ts
  src/test/linters/lint.provider.test.ts
  src/test/linters/lint.test.ts
  src/test/linters/lint.unit.test.ts
  src/test/linters/linter.availability.unit.test.ts
  src/test/linters/pylint.test.ts
  src/test/linters/pylint.unit.test.ts
  src/test/linters/serviceRegistry.unit.test.ts
  src/test/mockClasses.ts
Labels: skip package*.json

#17434 DS Product names were inadvertently removed
  src/client/common/installer/productNames.ts
Labels: skip news, skip tests

#17450 Update change log and version
  CHANGELOG.md
  news/2 Fixes/17447.md
  package-lock.json
  package.json
Labels: skip news, skip tests

#17446 Jedi behind LSP reqs in main reqs files
  .github/actions/build-vsix/action.yml
  .github/workflows/build.yml
  .github/workflows/nightly-coverage.yml
  .github/workflows/pr-check.yml
  gulpfile.js
  jedils_requirements.in
  jedils_requirements.txt
  pythonFiles/run-jedi-language-server.py
  requirements.in
  requirements.txt
  src/client/activation/jedi/manager.ts
Labels: skip news, skip tests

#17470 Fix jedi requirements
  .github/actions/build-vsix/action.yml
  .github/workflows/build.yml
  .github/workflows/nightly-coverage.yml
  .github/workflows/pr-check.yml
  gulpfile.js
  jedils_requirements.in
  jedils_requirements.txt
  pythonFiles/run-jedi-language-server.py
  requirements.in
  requirements.txt
  src/client/activation/jedi/manager.ts
Labels: skip news, skip tests

#17473 Remove limited 2.7 support notification
  news/1 Enhancements/17451.md
  package.nls.json
  src/client/common/utils/localize.ts
  src/client/interpreter/contracts.ts
  src/client/interpreter/display/index.ts
  src/client/interpreter/display/python27Prompt.ts
  src/client/interpreter/serviceRegistry.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/test/interpreters/display.unit.test.ts
  src/test/interpreters/display/python27Prompt.unit.test.ts
Labels: skip package*.json

#17474 Resolve environments using cache if cache has complete info
  news/1 Enhancements/17474.md
  src/client/pythonEnvironments/base/locators/composite/envsCollectionCache.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
Labels: skip tests

#17484 Fix hang caused by loop in getting interpreter information
  news/2 Fixes/17484.md
  src/client/common/process/pythonExecutionFactory.ts
Labels: skip tests

#17487 Merge from release-2021.09 into main
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
  news/2 Fixes/17089.md
  news/2 Fixes/17111.md
  news/2 Fixes/17144.md
  news/2 Fixes/17244.md
  news/2 Fixes/17270.md
  news/2 Fixes/17280.md
  news/2 Fixes/17281.md
  news/2 Fixes/17282.md
  news/2 Fixes/17285.md
  news/2 Fixes/17303.md
  news/2 Fixes/17309.md
  news/2 Fixes/17325.md
  news/2 Fixes/17353.md
  news/2 Fixes/17363.md
  news/2 Fixes/17370.md
  news/2 Fixes/17374.md
  news/2 Fixes/17378.md
  news/2 Fixes/17447.md
Labels: skip news

#17489 Ensure initial scroll position is set based on the selected interpreter in quickpick
  src/client/common/utils/multiStepInput.ts
Labels: skip news, skip tests

#17486 Remove unused localized strings
  package.nls.json
  package.nls.zh-cn.json
  package.nls.zh-tw.json
  pythonFiles/.vscode/.ropeproject/config.py
  pythonFiles/.vscode/.ropeproject/objectdb
  src/client/common/utils/localize.ts
  src/test/common/installer/installer.unit.test.ts
Labels: skip news, skip package*.json

#17494 Use the first workspace folder to query interpreters if no resource is passed in getInterpreters() API
  src/client/pythonEnvironments/legacyIOC.ts
Labels: skip news, skip tests

#17499 Fix `getAllInterpreters` API by always triggering discovery as part of activation
  src/client/pythonEnvironments/index.ts
Labels: skip news, skip tests

#17497 Remove output from report issue command template
  resources/report_issue_template.md
  src/client/common/application/commands/reportIssueCommand.ts
  src/test/common/application/commands/issueTemplateVenv1.md
Labels: skip news, skip tests

#17496 Fix for unittest discovery failure due to root id mismatch
  news/2 Fixes/17386.md
  src/client/testing/testController/common/testItemUtilities.ts
  src/client/testing/testController/common/types.ts
  src/client/testing/testController/controller.ts
  src/client/testing/testController/pytest/pytestController.ts
  src/client/testing/testController/unittest/runner.ts
  src/client/testing/testController/unittest/unittestController.ts
Labels: skip tests

#17509 Don't override user provided `--rootdir` in pytest args.
  news/2 Fixes/8678.md
  src/client/testing/testController/pytest/arguments.ts
  src/client/testing/testController/pytest/runner.ts
Labels: skip tests

#17514 Use workspace dir when cwd is empty for testing
  src/client/testing/testController/pytest/pytestController.ts
  src/client/testing/testController/unittest/unittestController.ts
Labels: skip news, skip tests

#17506 Add telemetry to report issue command
  src/client/common/application/commands/reportIssueCommand.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/test/common/application/commands/reportIssueCommand.unit.test.ts
Labels: skip news

#17515 Fix interpreter fetching for untitled files
  src/client/pythonEnvironments/legacyIOC.ts
Labels: skip news, skip tests

#17246 Replace GIFs with SVGs and tweak instructions
  package.json
  resources/walkthrough/anaconda-install.png
  resources/walkthrough/change-python-interpreter-dark.gif
  resources/walkthrough/change-python-interpreter-hc.gif
  resources/walkthrough/change-python-interpreter-light.gif
  resources/walkthrough/datascience-learn-more.png
  resources/walkthrough/learn-more.md
  resources/walkthrough/learnmore.svg
  resources/walkthrough/python-datascience-learn-more.md
  resources/walkthrough/python-dev-learn-more.md
  resources/walkthrough/python-docs-learn-more.png
  resources/walkthrough/python-interpreter.svg
  resources/walkthrough/run-and-debug-python-file-macOS.md
  resources/walkthrough/run-and-debug-python-file.md
  resources/walkthrough/rundebug2.svg
Labels: skip news, skip package*.json, skip tests

#17549 Update JediLSP to Jedi while diagnosing
  src/client/application/diagnostics/checks/jediPython27NotSupported.ts
  src/test/application/diagnostics/checks/jediPython27NotSupported.unit.test.ts
Labels: skip news, skip tests

#17563 Ensure all users use new discovery code regardless of their experiment settings
  news/2 Fixes/17563.md
  src/client/common/experiments/service.ts
Labels: skip tests

#17560 Add lack elipsis to name
  package.nls.json
Labels: skip news

#17568 Update Report Issue Template
  resources/report_issue_template.md
  src/test/common/application/commands/issueTemplateVenv1.md
Labels: skip news

#17571 Remove pythonSortEnvs from experiments
  package.json
Labels: skip news, skip package*.json

#17575 If user has selected an interpreter which is not discovery cache, correctly add it to cache
  news/1 Enhancements/17575.md
  src/client/pythonEnvironments/base/locators/composite/envsCollectionCache.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
Labels: skip tests

#17577 If active interpreter type is detected as Unknown, make sure we log it as an error
  src/client/startupTelemetry.ts
Labels: skip news, skip tests

#17576 Ensure `conda info --json` times out after 50 seconds
  news/2 Fixes/17576.md
  src/client/pythonEnvironments/common/environmentManagers/conda.ts
Labels: skip tests
