Repository microsoft/vscode-python, pull requests merged in 2021-10, with the labels that each got.

#17589 Ensure debugger contribution points are turned off when using virtual workspaces
  news/1 Enhancements/17493.md
  package.json
Labels: skip package*.json, skip tests

#17584 Reworded message for A/B testing in the output channel as per issue #6352
  news/2 Fixes/6352.md
  package.nls.json
  src/client/common/utils/localize.ts
Labels: skip tests

#17585 Improve setting description for enabling A/B tests
  news/1 Enhancements/7793.md
  package.json
Labels: skip package*.json, skip tests

#17588 Issue #17037: Update text for "entire workspace" when selecting or clearing interpreters
  news/2 Fixes/10737.md
  package.nls.json
  src/client/common/utils/localize.ts
  src/test/configuration/interpreterSelector/commands/resetInterpreter.unit.test.ts
  src/test/configuration/interpreterSelector/commands/setInterpreter.unit.test.ts
Labels: skip tests

#17611 Update main branch version
  package-lock.json
  package.json
Labels: skip news

#17595 Creating new Integrated Terminal doesn't take selected workspace into account when activating environment
  news/2 Fixes/15522.md
  src/client/terminals/activation.ts
Labels: skip tests

#17614 Use correct python executable when running code using Python execution factory
  src/client/common/process/pythonExecutionFactory.ts
  src/test/common/process/pythonExecutionFactory.unit.test.ts
Labels: skip news, skip tests

#17619 Pin debugpy
  .github/release_plan.md
  pythonFiles/install_debugpy.py
Labels: skip news

#17620 Fix handling of empty directories in debugpy wheels when combining them
  pythonFiles/install_debugpy.py
Labels: skip news

#17624 Update news items for cherry picked.
  CHANGELOG.md
  news/2 Fixes/17488.md
Labels: skip news

#17630 Pin wrapt to 1.12.1
  build/test-requirements.txt
Labels: skip news

#17631 Pin wrapt to 1.12.1 (#17630)
  build/test-requirements.txt
Labels: skip news

#17634 Cherry pick "Ensure keys whose default value type is an array are not duplicated" into release
  src/client/common/persistentState.ts
  src/test/common/persistentState.unit.test.ts
Labels: skip news

#17647 Update version and changelog for release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip news

#17594 Rename commands in Run/Debug button
  news/2 Fixes/17019.md
  package.json
  package.nls.json
Labels: skip package*.json

#17650 Fix for formatting notebook cells.
  news/2 Fixes/16980.md
  src/client/common/editor.ts
  src/client/providers/formatProvider.ts
Labels: skip tests

#17664 Investigate why build is failing
  build/test-requirements.txt
Labels: skip news, skip package*.json, skip tests

#17578 Ensure subtest run update parent results
  news/2 Fixes/17561.md
  package.json
  pythonFiles/visualstudio_py_testlauncher.py
  src/client/testing/testController/common/testItemUtilities.ts
  src/client/testing/testController/common/types.ts
  src/client/testing/testController/controller.ts
  src/client/testing/testController/unittest/runner.ts
  src/client/testing/testController/unittest/unittestController.ts
  types/vscode.proposed.d.ts
Labels: skip package*.json, skip tests

#17707 Fix issue labeling with 'classify'
  .github/workflows/issue-labels.yml
Labels: skip news

#17658 Provide IntelliSense status information when using `github.dev`
  news/1 Enhancements/17658.md
  package.nls.json
  src/client/browser/extension.ts
  src/client/browser/intellisenseStatus.ts
  tsconfig.browser.json
  types/vscode.proposed.d.ts
Labels: skip tests

#17714 Localize 'learn more' text
  src/client/browser/intellisenseStatus.ts
  src/client/browser/localize.ts
Labels: skip news, skip tests

#17734 Upgrade to latest jupyter lsp and skip intellisense when inside a cell
  package-lock.json
  package.json
  src/client/activation/jedi/manager.ts
  src/client/activation/languageClientMiddleware.ts
  src/client/activation/languageClientMiddlewareBase.ts
  src/client/activation/languageServer/manager.ts
  src/client/activation/node/manager.ts
  src/client/common/constants.ts
Labels: skip news, skip tests

#17782 Change the way telemetry is sent to take into account possible skipping
  src/client/activation/languageClientMiddlewareBase.ts
Labels: skip news, skip tests

#17815 Do not query for version and kind if it's not needed when reporting an issue
  news/3 Code Health/17815.md
  src/client/common/application/commands/reportIssueCommand.ts
  src/test/common/application/commands/issueTemplateVenv1.md
  src/test/common/application/commands/reportIssueCommand.unit.test.ts
Labels: code-health

#17820 Remove `python.condaPath` from workspace scope
  news/2 Fixes/17819.md
  package.json
  src/test/common/terminals/environmentActivationProviders/terminalActivation.testvirtualenvs.ts
Labels: skip package*.json, skip tests

#17832 Correctly set `failed` property when sending telemetry for TERMINAL_SHELL_IDENTIFICATION
  src/client/common/terminal/shellDetector.ts
  src/client/common/terminal/shellDetectors/vscEnvironmentShellDetector.ts
  src/test/common/terminals/shellDetectors/shellDetectors.unit.test.ts
Labels: skip news

#17837 Support environment variable substitution in "python" property for `launch.json`
  news/1 Enhancements/12289.md
  src/client/debugger/extension/configuration/resolvers/base.ts
Labels: skip tests

#17841 Support installing Insiders extension in remote sessions
  news/2 Fixes/15145.md
  package.json
Labels: skip package*.json, skip tests

#17879 Make middleware wait for connection
  news/2 Fixes/17878.md
  package-lock.json
  src/client/activation/languageClientMiddlewareBase.ts
Labels: skip package*.json, skip tests
