Repository microsoft/vscode-python, pull requests merged in 2021-03, with the labels that each got.

#15515 Add better failure messages for file check jobs
  .github/workflows/pr-file-check.yml
Labels: skip news

#15526 Turn back on insiders tests
  .github/workflows/insiders.yml
  .github/workflows/pr-check.yml
Labels: skip news

#15533 Remove experiments.json downloading steps
  src/client/common/experiments/manager.ts
  src/test/common/experiments/manager.unit.test.ts
Labels: skip news

#15521 Declare "Trusted Workspaces" support.
  news/3 Code Health/15525.md
  package.json
Labels: skip package*.json, skip tests

#15534 Add Jedi memory telemetry
  package-lock.json
  package.json
  src/client/activation/jedi/languageServerProxy.ts
  src/client/common/configSettings.ts
  src/client/common/process/memory.ts
  src/client/providers/jediProxy.ts
Labels: skip news, skip tests

#15547 Remove old DS experiments
  experiments.json
  package.json
Labels: skip news, skip package*.json

#15545 Remove AlwaysDisplayTestExplorer experiment
  experiments.json
  package.json
  src/client/common/experiments/groups.ts
  src/client/common/experiments/manager.ts
  src/client/testing/main.ts
  src/test/common/experiments/manager.unit.test.ts
  src/test/testing/main.unit.test.ts
Labels: skip news, skip package*.json

#15544 Add description for jupyter extension + logos and include discussions for feature request
  README.md
Labels: skip news

#15539 Install new `torch-tb-profiler` package when starting TensorBoard for PyTorch users
  package.nls.json
  src/client/common/experiments/groups.ts
  src/client/common/installer/productInstaller.ts
  src/client/common/installer/productNames.ts
  src/client/common/installer/productPath.ts
  src/client/common/installer/productService.ts
  src/client/common/installer/serviceRegistry.ts
  src/client/common/types.ts
  src/client/common/utils/localize.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/importTracker.ts
  src/client/telemetry/index.ts
  src/client/tensorBoard/helpers.ts
  src/client/tensorBoard/tensorBoardSession.ts
  src/client/tensorBoard/tensorBoardSessionProvider.ts
  src/test/common/installer.test.ts
  src/test/tensorBoard/tensorBoardImportCodeLensProvider.unit.test.ts
  src/test/tensorBoard/tensorBoardSession.test.ts
Labels: skip news

#15556 Enable middleware telemetry for JediLSP, count resultLength
  src/client/activation/languageClientMiddleware.ts
  src/client/telemetry/index.ts
Labels: skip news, skip tests

#15571 cherry pick: Update start-up telemetry for Jedi LSP (#15419)
  src/client/activation/activationService.ts
  src/client/activation/jedi/languageServerProxy.ts
  src/client/activation/jedi/manager.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
Labels: skip news, skip tests

#15572 Version and change log update for point release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip news

#15554 Display Python and Jupyter logo side by side on readme
  README.md
Labels: skip news

#15575 Merge back from release to main
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
  news/2 Fixes/15232.md
  news/2 Fixes/15439.md
  news/2 Fixes/15452.md
Labels: skip news

#15596 Cherry pick fix for error handler to prevent proc from exiting into release
  news/2 Fixes/15395.md
  src/client/common/process/rawProcessApis.ts
Labels: skip tests

#15597 Update changelog and extension version
  CHANGELOG.md
  news/2 Fixes/15395.md
  package-lock.json
  package.json
Labels: skip news, skip tests

#15535 Remove old experiments not referenced in the code
  experiments.json
  package.json
  src/client/common/experiments/manager.ts
  src/test/common/experiments/manager.unit.test.ts
Labels: skip news, skip package*.json

#15536 Remove AA_Testing experiment
  experiments.json
  package.json
  src/client/activation/aaTesting.ts
  src/client/activation/serviceRegistry.ts
  src/client/common/experiments/groups.ts
  src/test/activation/aaTesting.unit.test.ts
  src/test/activation/serviceRegistry.unit.test.ts
Labels: skip news, skip package*.json

#15538 Remove UseTerminalToGetActivatedEnvVars experiment
  .eslintignore
  experiments.json
  package.json
  src/client/common/experiments/groups.ts
  src/client/interpreter/activation/preWarmVariables.ts
  src/client/interpreter/activation/terminalEnvironmentActivationService.ts
  src/client/interpreter/activation/wrapperEnvironmentActivationService.ts
  src/client/interpreter/serviceRegistry.ts
  src/client/telemetry/index.ts
  src/test/common/variables/envVarsProvider.multiroot.test.ts
  src/test/interpreters/activation/preWarmVariables.unit.test.ts
  src/test/interpreters/activation/terminalEnvironmentActivationService.unit.test.ts
  src/test/interpreters/activation/wrapperEnvironmentActivationService.unit.test.ts
  src/test/interpreters/serviceRegistry.unit.test.ts
  src/test/serviceRegistry.ts
  src/test/testing/unittest/unittest.test.ts
Labels: skip news, skip package*.json

#15570 Remove language servers experiments
  experiments.json
  package.json
  src/client/activation/languageClientMiddleware.ts
  src/client/common/experiments/groups.ts
Labels: skip news, skip package*.json, skip tests

#15540 Ship debugger data viewer integration
  package.json
  src/client/common/experiments/debuggerDataViewerExperimentEnabler.ts
  src/client/common/serviceRegistry.ts
Labels: skip news, skip package*.json, skip tests

#15555 Move the "Play" button down a level to the "Run" submenu.
  package.json
  resources/dark/run-file.svg
  resources/light/run-file.svg
Labels: skip news, skip package*.json

#15564 Stop hiding the "Play" button if Code Runner is installed.
  package.json
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/client/terminals/activation.ts
  src/client/terminals/serviceRegistry.ts
  src/test/common/terminals/serviceRegistry.unit.test.ts
  src/test/terminals/activation.unit.test.ts
  src/test/terminals/serviceRegistry.unit.test.ts
Labels: skip news, skip package*.json

#15514 Send telemetry event to check if an entered path had already been discovered
  src/client/interpreter/configuration/interpreterSelector/commands/setInterpreter.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/test/configuration/interpreterSelector/commands/setInterpreter.unit.test.ts
Labels: skip news

#15600 Fixes for eslint.
  .eslintignore
  src/client/terminals/activation.ts
  src/client/terminals/serviceRegistry.ts
  src/test/terminals/activation.unit.test.ts
  src/test/terminals/serviceRegistry.unit.test.ts
Labels: skip news

#15614 Version and change log update for point release.
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip news

#15616 Merging back from release to main
  CHANGELOG.md
  news/2 Fixes/15395.md
  news/3 Code Health/15415.md
  package.json
Labels: skip news, skip package*.json

#15617 Preparing release candidate
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
  news/1 Enhancements/4765.md
  news/2 Fixes/10583.md
  news/2 Fixes/14631.md
  news/2 Fixes/14978.md
  news/2 Fixes/15302.md
  news/2 Fixes/15312.md
  news/2 Fixes/15373.md
  news/2 Fixes/15489.md
  news/2 Fixes/15541.md
  news/2 Fixes/15566.md
  news/2 Fixes/15576.md
  news/2 Fixes/15580.md
  news/2 Fixes/15586.md
  news/2 Fixes/6043.md
  news/3 Code Health/15525.md
  news/3 Code Health/15567.md
  news/3 Code Health/15573.md
  package-lock.json
  package.json
Labels: skip news

#14887 Set ini-language for more Python config files
  news/1 Enhancements/11250.md
  package.json
Labels: skip package*.json

#15615 Rename telemetry variable name to match constant value
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/client/tensorBoard/tensorBoardSession.ts
Labels: skip news, skip tests

#15639 Updates to notebook API
  news/2 Fixes/15638.md
  src/client/common/application/notebook.ts
  src/client/common/application/types.ts
  src/client/jupyter/languageserver/notebookConcatDocument.ts
  src/client/jupyter/languageserver/notebookConverter.ts
  src/test/insiders/languageServer.insiders.test.ts
  src/test/smoke/common.ts
  src/test/tensorBoard/nbextensionCodeLensProvider.insiders.test.ts
  types/vscode-proposed/index.d.ts
  types/vscode.proposed.d.ts
  typings/vscode-proposed/index.d.ts
Labels: skip tests

#15640 Fix GoToDef (F12) for notebook documents
  src/client/jupyter/languageserver/notebookConverter.ts
  src/client/jupyter/languageserver/notebookMiddlewareAddon.ts
Labels: skip news, skip tests

#15625 Restore the play button icon.
  package.json
  resources/dark/run-file.svg
  resources/light/run-file.svg
Labels: skip news, skip package*.json

#15650 Set default logic normalizing code sent to REPL
  news/1 Enhancements/15649.md
  package.json
  pythonFiles/normalizeForInterpreter.py
  pythonFiles/tests/test_normalize_for_interpreter.py
  src/client/common/experiments/groups.ts
  src/client/common/process/internal/scripts/index.ts
  src/client/terminals/codeExecution/helper.ts
  src/test/terminals/codeExecution/helper.test.ts
Labels: skip package*.json

#15588 Start TensorBoard sessions with python.tensorBoard.logDirectory if any
  news/1 Enhancements/15476.md
  package.json
  src/client/common/configSettings.ts
  src/client/common/types.ts
  src/client/tensorBoard/tensorBoardSession.ts
  src/test/tensorBoard/tensorBoardSession.test.ts
Labels: skip package*.json

#15659 Cherry picks from main to release
  news/1 Enhancements/15476.md
  news/2 Fixes/15638.md
  news/3 Code Health/15604.md
  news/3 Code Health/15612.md
  package.json
  resources/dark/run-file.svg
  resources/light/run-file.svg
  src/client/activation/jedi/languageServerProxy.ts
  src/client/common/application/notebook.ts
  src/client/common/application/types.ts
  src/client/common/configSettings.ts
  src/client/common/types.ts
  src/client/jupyter/languageserver/notebookConcatDocument.ts
  src/client/jupyter/languageserver/notebookConverter.ts
  src/client/jupyter/languageserver/notebookMiddlewareAddon.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/client/tensorBoard/tensorBoardSession.ts
  src/test/insiders/languageServer.insiders.test.ts
  src/test/smoke/common.ts
  src/test/tensorBoard/nbextensionCodeLensProvider.insiders.test.ts
  src/test/tensorBoard/tensorBoardSession.test.ts
  types/vscode-proposed/index.d.ts
  types/vscode.proposed.d.ts
  typings/vscode-proposed/index.d.ts
Labels: skip news, skip package*.json

#15670 Fix link to create a new Jupyter notebook in Python start page
  news/2 Fixes/15621.md
  package.nls.json
  package.nls.zh-cn.json
  pythonFiles/Notebooks intro.ipynb
  src/client/common/startPage/startPage.ts
  src/client/common/utils/localize.ts
  src/startPage-ui/startPage/startPage.tsx
Labels: skip tests

#15661 Update LSP packages to latest stable
  package-lock.json
  package.json
Labels: skip news

#15643 Remove icons again from readme
  README.md
Labels: skip news

#15645 Ensure server process is cleaned up on dispose
  news/2 Fixes/15644.md
  src/client/activation/jedi/languageServerProxy.ts
  src/client/common/process/memory.ts
  src/client/common/process/rawProcessApis.ts
Labels: skip tests

#15675 Restore experiment for LS RPC event for old versions
  experiments.json
Labels: skip news

#15676 Update version and change log for release
  CHANGELOG.md
  news/1 Enhancements/15476.md
  news/2 Fixes/15638.md
  news/3 Code Health/15604.md
  news/3 Code Health/15612.md
  package-lock.json
  package.json
Labels: skip news

#15599 Command to report issue
  news/1 Enhancements/67.md
  package.json
  package.nls.json
  resources/report_issue_template.md
  src/client/common/application/commands/reportIssueCommand.ts
  src/client/common/serviceRegistry.ts
  src/test/common/application/commands/reportIssueCommand.unit.test.ts
  src/test/common/installer.test.ts
  src/test/common/moduleInstaller.test.ts
Labels: skip package*.json

#15678 Missed Thanks section in change log.
  CHANGELOG.md
Labels: skip news

#15684 Turn off insider tests
  .github/workflows/insiders.yml
  .github/workflows/pr-check.yml
Labels: skip news

#15682 Simplify issue template for "Report Issue" command
  resources/report_issue_template.md
Labels: skip news

#15651 Forgot a dangling experiment group in groups.ts
  package.json
  src/client/common/experiments/groups.ts
Labels: skip news, skip package*.json, skip tests

#15628 Wait for experiments library to complete loading
  src/client/common/experiments/service.ts
  src/client/common/types.ts
  src/client/extensionActivation.ts
  src/test/common/experiments/service.unit.test.ts
Labels: skip news

#15662 Fix README image indent for VSCode extension page
  README.md
  news/2 Fixes/15662.md
Labels: skip tests

#15686 Implement API to check if poetry environment is related to a folder
  src/client/common/installer/poetryEnvHelper.ts
  src/client/common/platform/fs-paths.ts
Labels: skip news, skip tests

#15693 Move ShowExtensionSurveyPrompt experiment to ExP
  experiments.json
  package.json
  src/client/activation/extensionSurvey.ts
  src/client/common/experiments/groups.ts
  src/client/common/experiments/manager.ts
  src/test/activation/extensionSurvey.unit.test.ts
  src/test/common/experiments/manager.unit.test.ts
Labels: skip news, skip package*.json

#15631 Implement jump to source from PyTorch profiler plugin in integrated TensorBoard session
  news/1 Enhancements/15641.md
  src/client/tensorBoard/tensorBoardSession.ts
Labels: skip tests

#15702 Add miniforge to version parsing
  src/client/pythonEnvironments/discovery/locators/services/pyenvLocator.ts
  src/test/pythonEnvironments/discovery/locators/pyenvLocator.unit.test.ts
Labels: skip news

#15704 Expand no unused vars rule
  .eslintrc
  src/client/activation/jedi/activator.ts
  src/client/common/platform/fileSystem.ts
  src/client/providers/jediProxy.ts
  src/client/pythonEnvironments/base/locator.ts
  src/client/pythonEnvironments/base/locators/composite/cachingWrapper.ts
  src/client/pythonEnvironments/base/locators/lowLevel/filesLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/cacheableLocatorService.ts
  src/client/pythonEnvironments/discovery/locators/services/condaEnvFileService.ts
  src/client/pythonEnvironments/discovery/locators/services/condaEnvService.ts
  src/test/activation/languageServer/downloader.unit.test.ts
  src/test/install/channelManager.channels.test.ts
  src/test/install/channelManager.messages.test.ts
  src/test/linters/lint.args.test.ts
  src/test/mocks/autoSelector.ts
  src/test/mocks/moduleInstaller.ts
  src/test/mocks/process.ts
  src/test/pythonEnvironments/discovery/locators/cacheableLocatorService.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/workspaceVirtualEnvWatcherService.unit.test.ts
Labels: skip news

#15726 Check if file exists instead of launching it
  news/2 Fixes/15725.md
  src/client/common/configSettings.ts
Labels: skip tests

#15733 Added Poetry utility class
  src/client/common/installer/poetryEnvHelper.ts
  src/client/pythonEnvironments/base/info/interpreter.ts
  src/client/pythonEnvironments/common/externalDependencies.ts
  src/client/pythonEnvironments/discovery/locators/services/poetry.ts
  src/client/pythonEnvironments/info/environmentInfoService.ts
Labels: skip news, skip tests

#15741 Remove `export` from un-used exported functions, classes, and constants
  src/client/activation/common/languageServerPackageService.ts
  src/client/activation/common/packageRepository.ts
  src/client/activation/languageServer/languageServerPackageService.ts
  src/client/activation/languageServer/platformData.ts
  src/client/activation/types.ts
  src/client/application/diagnostics/checks/envPathVariable.ts
  src/client/application/diagnostics/checks/invalidPythonPathInDebugger.ts
  src/client/application/diagnostics/checks/lsNotSupported.ts
  src/client/application/diagnostics/commands/types.ts
  src/client/common/installer/productInstaller.ts
  src/client/common/interpreterPathService.ts
  src/client/common/process/rawProcessApis.ts
  src/client/common/terminal/environmentActivationProviders/baseActivationProvider.ts
  src/client/common/types.ts
  src/client/common/utils/async.ts
  src/client/common/utils/enum.ts
  src/client/common/utils/misc.ts
  src/client/common/utils/multiStepInput.ts
  src/client/common/utils/random.ts
  src/client/common/utils/resourceLifecycle.ts
  src/client/common/utils/sysTypes.ts
  src/client/common/utils/version.ts
  src/client/common/variables/sysTypes.ts
  src/client/debugger/extension/adapter/remoteLaunchers.ts
  src/client/debugger/types.ts
  src/client/interpreter/activation/service.ts
  src/client/interpreter/interpreterVersion.ts
  src/client/jupyter/jupyterIntegration.ts
  src/client/jupyter/languageserver/notebookConcatDocument.ts
  src/client/jupyter/types.ts
  src/client/linters/baseLinter.ts
  src/client/logging/_global.ts
  src/client/logging/formatters.ts
  src/client/logging/levels.ts
  src/client/logging/logger.ts
  src/client/providers/jediProxy.ts
  src/client/pythonEnvironments/base/envsCache.ts
  src/client/pythonEnvironments/base/info/index.ts
  src/client/pythonEnvironments/base/locator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/filesLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/fsWatchingLocator.ts
  src/client/pythonEnvironments/common/commonUtils.ts
  src/client/pythonEnvironments/common/environmentIdentifier.ts
  src/client/pythonEnvironments/discovery/locators/services/conda.ts
  src/client/pythonEnvironments/discovery/locators/services/condaLocatorService.ts
  src/client/pythonEnvironments/discovery/locators/services/windowsStoreLocator.ts
  src/client/pythonEnvironments/info/index.ts
  src/client/pythonEnvironments/info/interpreter.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/client/testing/common/runner.ts
  src/client/testing/common/testVisitors/visitor.ts
  src/client/testing/common/types.ts
  src/client/testing/navigation/types.ts
  src/client/workspaceSymbols/parser.ts
Labels: skip news, skip tests

#15734 Fallback to jedi when using python 2.7, <=3.5
  .github/actions/build-vsix/action.yml
  gulpfile.js
  jedils_requirements.in
  jedils_requirements.txt
  news/2 Fixes/15724.md
  pythonFiles/run-jedi-language-server.py
  pythonFiles/runJediLanguageServer.py
  requirements.in
  requirements.txt
  src/client/activation/activationService.ts
  src/client/activation/jedi/languageClientFactory.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
Labels: skip tests

#15747 fix for first time rename and goToDef returning 'no result'
  news/2 Fixes/15727.md
  src/client/activation/languageClientMiddleware.ts
Labels: skip tests

#15749 Fix the path where we look for LS version for telemetry
  src/client/activation/jedi/manager.ts
Labels: skip news, skip tests

#15718 Remove unused code
  news/3 Code Health/15717.md
  src/client/activation/types.ts
  src/client/application/diagnostics/types.ts
  src/client/common/constants.ts
  src/client/common/editor.ts
  src/client/common/helpers.ts
  src/client/common/open.ts
  src/client/common/platform/errors.ts
  src/client/common/platform/types.ts
  src/client/common/process/internal/scripts/index.ts
  src/client/common/process/types.ts
  src/client/common/refBool.ts
  src/client/common/types.ts
  src/client/common/utils/async.ts
  src/client/common/utils/decorators.ts
  src/client/common/utils/filesystem.ts
  src/client/common/utils/logging.ts
  src/client/common/utils/misc.ts
  src/client/common/utils/sysTypes.ts
  src/client/common/variables/sysTypes.ts
  src/client/constants.ts
  src/client/debugger/constants.ts
  src/client/debugger/extension/attachQuickPick/types.ts
  src/client/interpreter/helpers.ts
  src/client/ioc/index.ts
  src/client/language/characters.ts
  src/client/language/textIterator.ts
  src/client/logging/index.ts
  src/client/providers/jediProxy.ts
  src/client/pythonEnvironments/base/info/env.ts
  src/client/pythonEnvironments/base/info/index.ts
  src/client/pythonEnvironments/base/info/pythonVersion.ts
  src/client/pythonEnvironments/base/locators/composite/cachingWrapper.ts
  src/client/pythonEnvironments/discovery/locators/services/condaHelper.ts
  src/client/pythonEnvironments/discovery/locators/services/condaLocatorService.ts
  src/client/pythonEnvironments/info/index.ts
  src/client/pythonEnvironments/info/pythonVersion.ts
  src/client/telemetry/types.ts
  src/client/testing/common/testUtils.ts
Labels: skip tests

#15751 Update version and change log for point release
  CHANGELOG.md
  news/2 Fixes/15621.md
  news/2 Fixes/15724.md
  news/2 Fixes/15725.md
  news/2 Fixes/15727.md
  package-lock.json
  package.json
Labels: skip news

#15711 Add env var to allow TB profiler plugin to check if it was started in VS Code
  pythonFiles/tensorboard_launcher.py
Labels: skip news

#15759 Rollback jedi-ls to 0.27.2
  jedils_requirements.txt
Labels: skip news

#15760 cherry-pick to release: Rollback jedi-ls to 0.27.2
  jedils_requirements.txt
Labels: skip news

#15761 Add cached_property back to requirements
  jedils_requirements.in
  jedils_requirements.txt
Labels: skip news

#15757 Use same name for constant as the telemetry event name
  src/client/activation/activationService.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
Labels: skip news, skip tests

#15756 Update vscode-tas-client package
  package-lock.json
  package.json
  src/client/common/experiments/service.ts
Labels: skip news, skip tests

#15754 Functional test coverage
  .github/workflows/insiders.yml
  .github/workflows/pr-check.yml
  .github/workflows/release.yml
  build/.mocha.functional.json
  build/.mocha.unittests.json
  build/.nycrc
  package.json
Labels: skip news, skip package*.json

#15713 Added Poetry identifier
  src/client/pythonEnvironments/common/environmentIdentifier.ts
  src/client/pythonEnvironments/discovery/locators/services/poetry.ts
  src/test/pythonEnvironments/common/envlayouts/poetry/poetry-tutorial-project-6hnqYwvD-py3.8/Scripts/activate
  src/test/pythonEnvironments/common/envlayouts/poetry/poetry-tutorial-project-6hnqYwvD-py3.8/Scripts/python.exe
  src/test/pythonEnvironments/common/envlayouts/poetry/project1-haha-py3.8/Scripts/python.exe
  src/test/pythonEnvironments/common/envlayouts/poetry/project1/.venv/Scripts/python.exe
  src/test/pythonEnvironments/common/envlayouts/poetry/project1/.venv2/Scripts/python.exe
  src/test/pythonEnvironments/common/envlayouts/poetry/project1/pyproject.toml
  src/test/pythonEnvironments/common/envlayouts/poetry/project2/.venv/Scripts/python.exe
  src/test/pythonEnvironments/common/envlayouts/poetry/project2/.venv2/Scripts/python.exe
  src/test/pythonEnvironments/common/envlayouts/poetry/project2/pyproject.toml
  src/test/pythonEnvironments/common/envlayouts/poetry/wannabeglobalenv/Scripts/activate
  src/test/pythonEnvironments/common/envlayouts/poetry/wannabeglobalenv/Scripts/python.exe
  src/test/pythonEnvironments/discovery/locators/lowLevel/poetry.unit.test.ts
Labels: skip news

#15728 Linting after ExP cleanup
  .eslintignore
  src/client/common/installer/productInstaller.ts
  src/client/common/process/internal/scripts/constants.ts
  src/client/common/process/internal/scripts/index.ts
  src/client/common/process/internal/scripts/testing_tools.ts
  src/client/common/process/internal/scripts/types.ts
  src/client/terminals/codeExecution/helper.ts
  src/client/testing/common/services/discovery.ts
  src/client/testing/common/services/types.ts
  src/test/common/installer.test.ts
  src/test/common/installer/installer.unit.test.ts
  src/test/terminals/codeExecution/helper.test.ts
Labels: skip news

#15771 Set envs found via Windows PATH as system envs
  src/client/pythonEnvironments/base/info/envKind.ts
  src/client/pythonEnvironments/base/locators/lowLevel/filesLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/windowsKnownPathsLocator.ts
  src/client/pythonEnvironments/common/environmentIdentifier.ts
  src/test/pythonEnvironments/base/locators/lowLevel/windowsKnownPathsLocator.functional.test.ts
  src/test/pythonEnvironments/common/environmentIdentifier.unit.test.ts
Labels: skip news

#15783 Update jedi LS to latest
  .github/actions/build-vsix/action.yml
  jedils_requirements.in
  jedils_requirements.txt
Labels: skip news

#15773 Use GHA to add the 'classify' label
  .github/workflows/issue-labels.yml
Labels: skip news

#15776 Move coverage to nightly and simplify reporting
  .github/codecov.yml
  .github/workflows/insiders.yml
  .github/workflows/nightly-coverage.yml
  .github/workflows/pr-check.yml
  .github/workflows/release.yml
  build/.nycrc
  build/functional-test-requirements.txt
  package.json
Labels: skip news, skip package*.json

#15789 Update jedi language server
  jedils_requirements.in
  jedils_requirements.txt
Labels: skip news

#15797 Linting assign-reviewers.yml
  .github/assign-reviewers.yml
Labels: skip news

#15796 Remove uploading to codecov
  .github/codecov.yml
  .github/workflows/nightly-coverage.yml
  .github/workflows/pr-check.yml
  package-lock.json
  package.json
Labels: skip news

#15765 Added Poetry locator
  news/1 Enhancements/15765.md
  src/client/common/extensions.ts
  src/client/pythonEnvironments/discovery/locators/services/poetry.ts
  src/client/pythonEnvironments/discovery/locators/services/poetryLocator.ts
  src/client/pythonEnvironments/index.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/common/extensions.unit.test.ts
  src/test/pythonEnvironments/common/envlayouts/poetry/globalwinproject-9hvDnqYw-py3.11/Scripts/activate
  src/test/pythonEnvironments/common/envlayouts/poetry/globalwinproject-9hvDnqYw-py3.11/Scripts/python.exe
  src/test/pythonEnvironments/common/envlayouts/poetry/globalwinproject-9hvDnqYw-py3.11/pyvenv.cfg
  src/test/pythonEnvironments/common/envlayouts/poetry/poetry-tutorial-project-6hnqYwvD-py3.8/pyvenv.cfg
  src/test/pythonEnvironments/common/envlayouts/poetry/posix1project-9hvDnqYw-py3.4/activate
  src/test/pythonEnvironments/common/envlayouts/poetry/posix1project-9hvDnqYw-py3.4/python
  src/test/pythonEnvironments/common/envlayouts/poetry/posix1project-9hvDnqYw-py3.4/pyvenv.cfg
  src/test/pythonEnvironments/common/envlayouts/poetry/posix2project-6hnqYwvD-py3.7/bin/activate
  src/test/pythonEnvironments/common/envlayouts/poetry/posix2project-6hnqYwvD-py3.7/bin/python
  src/test/pythonEnvironments/common/envlayouts/poetry/posix2project-6hnqYwvD-py3.7/pyvenv.cfg
  src/test/pythonEnvironments/common/envlayouts/poetry/project1/.venv/pyvenv.cfg
  src/test/pythonEnvironments/common/envlayouts/poetry/project2/.venv/Scripts/python.exe
  src/test/pythonEnvironments/common/envlayouts/poetry/project2/.venv/bin/activate
  src/test/pythonEnvironments/common/envlayouts/poetry/project2/.venv/bin/python
  src/test/pythonEnvironments/common/envlayouts/poetry/project2/.venv/pyvenv.cfg
  src/test/pythonEnvironments/common/envlayouts/poetry/project2/.venv2/Scripts/python.exe
  src/test/pythonEnvironments/discovery/locators/lowLevel/poetry.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/poetryLocator.testvirtualenvs.ts
  src/test/pythonEnvironments/discovery/locators/poetryLocator.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/watcherTestUtils.ts
Labels: skip news, skip tests

#15786 Install dev tools using Poetry when the poetry environment related to current folder is selected
  news/1 Enhancements/15786.md
  src/client/common/installer/poetryInstaller.ts
  src/client/pythonEnvironments/discovery/locators/services/poetry.ts
  src/test/common/installer/poetryInstaller.unit.test.ts
Labels: skip news, skip tests

#15815 Fix default poetry binary path to use
  src/client/pythonEnvironments/discovery/locators/services/poetry.ts
  src/test/pythonEnvironments/discovery/locators/lowLevel/poetry.unit.test.ts
Labels: skip news
