Repository microsoft/vscode-python, pull requests merged in 2021-06, with the labels that each got.

#16332 Added synchronus inExperiment API
  src/client/common/experiments/service.ts
  src/client/common/types.ts
  src/test/common/experiments/service.unit.test.ts
Labels: skip news

#16357 Update Jedi Language Server to latest
  jedils_requirements.in
  jedils_requirements.txt
Labels: skip news

#16381 Update tests: `vscode.notebook.activeNotebookEditor` --> `vscode.window.activeNotebookEditor`
  src/test/initialize.ts
Labels: skip news, skip tests

#16385 Fix go to definition in Python notebooks
  src/client/common/application/notebook.ts
  src/test/insiders/languageServer.insiders.test.ts
Labels: skip news

#16390 Remove deprecated `NotebookCellData` constructor parameter
  src/test/insiders/languageServer.insiders.test.ts
Labels: skip news

#16373 Add test location provider
  .eslintignore
  pythonFiles/symbolProvider.py
  src/client/common/process/internal/scripts/index.ts
  src/client/common/process/internal/scripts/types.ts
  src/client/common/process/pythonEnvironment.ts
  src/client/common/process/pythonExecutionFactory.ts
  src/client/common/process/pythonExecutionService.ts
  src/client/common/process/pythonProcess.ts
  src/client/testing/common/testLocationProvider.ts
  src/client/testing/common/types.ts
  src/client/testing/navigation/symbolProvider.ts
  src/test/pythonFiles/testing/test_location.py
  src/test/testing/common/testLocationProvider.unit.test.ts
  src/test/testing/navigation/symbolNavigator.unit.test.ts
Labels: skip news

#16374 Add new option to insiders installExtension command to prevent bundle reinstalls
  src/client/common/application/commands.ts
  src/client/common/installer/extensionBuildInstaller.ts
  src/test/common/installer/extensionBuildInstaller.unit.test.ts
Labels: skip news

#16401 Update Jedi language server
  jedils_requirements.in
  jedils_requirements.txt
Labels: skip news

#16383 Fix type safeness of executeCommand
  src/client/common/application/applicationEnvironment.ts
  src/client/common/application/commands.ts
  src/client/common/application/commands/reportIssueCommand.ts
  src/client/common/application/types.ts
  src/client/common/constants.ts
  src/client/common/serviceRegistry.ts
  src/client/common/startPage/startPage.ts
  src/client/testing/codeLenses/testFiles.ts
  src/client/testing/common/managers/baseTestManager.ts
  src/client/testing/common/testUtils.ts
  src/client/testing/common/types.ts
  src/client/testing/display/picker.ts
  src/client/testing/explorer/commandHandlers.ts
  src/client/testing/explorer/testTreeViewProvider.ts
  src/client/testing/main.ts
  src/client/testing/unittest/main.ts
  src/test/common/application/commands/reportIssueCommand.unit.test.ts
  src/test/common/experiments/service.unit.test.ts
  src/test/common/insidersBuild/insidersExtensionService.unit.test.ts
  src/test/testing/common/managers/baseTestManager.unit.test.ts
  src/test/testing/debugger.test.ts
  src/test/testing/display/picker.functional.test.ts
  src/test/testing/display/picker.unit.test.ts
  src/test/testing/explorer/testExplorerCommandHandler.unit.test.ts
  src/test/testing/explorer/testTreeViewProvider.unit.test.ts
  src/test/testing/nosetest/nosetest.disovery.test.ts
  src/test/testing/nosetest/nosetest.run.test.ts
  src/test/testing/nosetest/nosetest.test.ts
  src/test/testing/pytest/pytest.discovery.test.ts
  src/test/testing/pytest/pytest.run.test.ts
  src/test/testing/pytest/pytest.test.ts
  src/test/testing/rediscover.test.ts
  src/test/testing/stoppingDiscoverAndTest.test.ts
  src/test/testing/unittest/unittest.discovery.test.ts
  src/test/testing/unittest/unittest.run.test.ts
  src/test/testing/unittest/unittest.test.ts
  src/test/testing/unittest/unittest.unit.test.ts
Labels: skip news

#16272 Better telemetry when installing Jupyter dependencies
  news/1 Enhancements/15937.md
  src/client/common/installer/productInstaller.ts
  src/client/telemetry/index.ts
Labels: skip tests

#16372 Use the same "Jupyter is not installed" message everywhere
  src/client/common/application/commandManager.ts
  src/client/common/application/types.ts
  src/client/common/utils/localize.ts
  src/client/jupyter/jupyterExtensionDependencyManager.ts
  src/client/jupyter/jupyterNotInstalledNotificationHelper.ts
  src/client/jupyter/types.ts
  src/test/jupyter/jupyterNotInstalledNotificationHelper.unit.test.ts
Labels: skip news, skip tests

#16400 Remove old pylance banner
  package.nls.json
  package.nls.ru.json
  package.nls.zh-cn.json
  src/client/activation/languageServer/activator.ts
  src/client/activation/none/activator.ts
  src/client/activation/serviceRegistry.ts
  src/client/common/types.ts
  src/client/common/utils/localize.ts
  src/client/languageServices/proposeLanguageServerBanner.ts
  src/test/activation/languageServer/activator.unit.test.ts
  src/test/activation/serviceRegistry.unit.test.ts
  src/test/testing/banners/proposeNewLanguageServerBanner.unit.test.ts
Labels: skip news

#16403 Add survey for MPLS usage
  package.nls.json
  src/client/activation/serviceRegistry.ts
  src/client/application/diagnostics/checks/mplsSurvey.ts
  src/client/application/diagnostics/constants.ts
  src/client/common/utils/localize.ts
  src/test/application/diagnostics/checks/mplsSurvey.unit.test.ts
Labels: skip news

#16415 Fix code removal missed in last PR
  package.json
  src/client/common/experiments/groups.ts
Labels: skip news, skip package*.json, skip tests

#16421 Update jedi-language-server
  jedils_requirements.in
  jedils_requirements.txt
Labels: skip news

#16422 Make the Jupyter extension an optional dependency
  .github/actions/build-vsix/action.yml
  build/license-header.txt
  gulpfile.js
  news/1 Enhancements/16102.md
  package.json
  package.nls.json
  src/client/common/application/commandManager.ts
  src/client/common/application/types.ts
  src/client/common/serviceRegistry.ts
  src/client/common/startPage/startPage.ts
  src/client/common/utils/localize.ts
  src/client/jupyter/jupyterExtensionDependencyManager.ts
  src/client/jupyter/jupyterNotInstalledNotificationHelper.ts
  src/client/jupyter/types.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/startPage-ui/startPage/startPage.tsx
  src/test/common/moduleInstaller.test.ts
  src/test/jupyter/jupyterNotInstalledNotificationHelper.unit.test.ts
  src/test/startPage/startPage.unit.test.ts
  src/test/startPage/startPageIocContainer.ts
Labels: skip package*.json

#16416 Parse pypy versions on windows
  src/client/pythonEnvironments/discovery/locators/services/pyenvLocator.ts
  src/test/pythonEnvironments/discovery/locators/pyenvLocator.unit.test.ts
Labels: skip news

#16437 Release candidate for June
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
  news/1 Enhancements/15937.md
  news/1 Enhancements/16102.md
  news/1 Enhancements/16141.md
  news/2 Fixes/15561.md
  news/2 Fixes/16072.md
  news/2 Fixes/16208.md
  news/2 Fixes/16291.md
  news/2 Fixes/16355.md
  news/2 Fixes/16397.md
  package-lock.json
  package.json
  src/client/activation/common/activatorBase.ts
  src/client/common/utils/workerPool.ts
  src/client/interpreter/configuration/interpreterSelector/commands/base.ts
  src/test/application/diagnostics/checks/updateTestSettings.unit.test.ts
  src/test/application/misc/joinMailingListPrompt.unit.test.ts
  src/test/common/exitCIAfterTestReporter.ts
  src/test/common/insidersBuild/insidersExtensionService.unit.test.ts
  src/test/common/platform/utils.ts
  src/test/interpreters/autoSelection/index.unit.test.ts
  src/test/interpreters/autoSelection/rules/base.unit.test.ts
  src/test/interpreters/autoSelection/rules/cached.unit.test.ts
  src/test/interpreters/autoSelection/rules/currentPath.unit.test.ts
  src/test/interpreters/autoSelection/rules/settings.unit.test.ts
  src/test/interpreters/autoSelection/rules/system.unit.test.ts
  src/test/interpreters/autoSelection/rules/winRegistry.unit.test.ts
  src/test/interpreters/autoSelection/rules/workspaceEnv.unit.test.ts
  src/test/performanceTest.ts
  src/test/smokeTest.ts
  src/test/tensorBoard/tensorBoardPrompt.unit.test.ts
  src/test/testBootstrap.ts
Labels: skip news

#16438 Update main version
  package-lock.json
  package.json
Labels: skip news

#16448 Fix go to definition in Python notebooks (#16385)
  CHANGELOG.md
  src/client/common/application/notebook.ts
  src/test/initialize.ts
  src/test/insiders/languageServer.insiders.test.ts
  src/test/smoke/datascience.smoke.test.ts
Labels: skip news

#16440 Recommend >= 0.2.0 of `torch-tb-profiler`
  CHANGELOG.md
  src/client/common/utils/localize.ts
  src/client/tensorBoard/tensorBoardSession.ts
  src/test/tensorBoard/tensorBoardSession.test.ts
Labels: skip news

#16490 Update release candidate for release
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
  package-lock.json
  package.json
Labels: skip news

#16491 Remove deprecated setting usage in DS smoke test
  src/test/smoke/datascience.smoke.test.ts
Labels: skip news

#16361 Recommend >= 0.2.0 of torch-tb-profiler
  CHANGELOG.md
  src/client/common/utils/localize.ts
  src/client/tensorBoard/tensorBoardSession.ts
  src/test/tensorBoard/tensorBoardSession.test.ts
Labels: skip news

#16529 Better handling of notebook diagnostics
  news/2 Fixes/16528.md
  src/client/jupyter/languageserver/notebookConverter.ts
Labels: skip tests

#16530 Merge back from release to main
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
  src/test/smoke/datascience.smoke.test.ts
Labels: skip news

#16462 Lint files affected by the Jupyter work
  .eslintignore
  package-lock.json
  package.json
  src/client/common/application/commandManager.ts
  src/client/common/application/types.ts
  src/client/common/platform/fileSystem.ts
  src/client/common/serviceRegistry.ts
  src/client/common/utils/localize.ts
  src/client/providers/jediProxy.ts
  src/client/pythonEnvironments/base/locators/lowLevel/windowsKnownPathsLocator.ts
  src/client/testing/configuration/index.ts
  src/startPage-ui/startPage/startPage.tsx
  src/test/activation/activationManager.unit.test.ts
  src/test/common/installer/installer.unit.test.ts
  src/test/common/terminals/activation.conda.unit.test.ts
  src/test/common/variables/environmentVariablesProvider.unit.test.ts
  src/test/configuration/interpreterSelector/commands/setInterpreter.unit.test.ts
  src/test/configuration/interpreterSelector/interpreterSelector.unit.test.ts
  src/test/interpreters/interpreterService.unit.test.ts
  src/test/languageServers/jedi/definitions/navigation.test.ts
  src/test/pythonEnvironments/common/commonUtils.functional.test.ts
  src/test/pythonEnvironments/discovery/locators/lowLevel/poetry.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/poetryLocator.testvirtualenvs.ts
  src/test/pythonEnvironments/discovery/locators/poetryLocator.unit.test.ts
  src/test/pythonEnvironments/legacyIOC.unit.test.ts
  src/test/tensorBoard/tensorBoardFileWatcher.test.ts
  src/test/tensorBoard/tensorBoardSession.test.ts
  src/test/testing/pytest/pytest.run.test.ts
  src/test/testing/pytest/pytest.testMessageService.test.ts
  src/test/testing/pytest/pytest_run_tests_data.ts
  src/test/testing/serviceRegistry.ts
Labels: skip news, skip tests

#16518 Adds support for Pytest run using the new Test UI
  src/client/common/application/commands.ts
  src/client/testing/common/types.ts
  src/client/testing/configuration/index.ts
  src/client/testing/main.ts
  src/client/testing/serviceRegistry.ts
  src/client/testing/testController/common/discoveryHelper.ts
  src/client/testing/testController/common/externalDependencies.ts
  src/client/testing/testController/common/resultsHelper.ts
  src/client/testing/testController/common/testCase.ts
  src/client/testing/testController/common/testFile.ts
  src/client/testing/testController/common/testFolder.ts
  src/client/testing/testController/common/testItemUtilities.ts
  src/client/testing/testController/common/types.ts
  src/client/testing/testController/common/workspaceTestRoot.ts
  src/client/testing/testController/controller.ts
  src/client/testing/testController/pytest/arguments.ts
  src/client/testing/testController/pytest/discovery.ts
  src/client/testing/testController/pytest/pytestController.ts
  src/client/testing/testController/pytest/runner.ts
  src/client/testing/testController/serviceRegistry.ts
Labels: skip news, skip tests

#16540 Update flake8 default path value
  src/client/common/configSettings.ts
Labels: skip news, skip tests

#16551 Ensure JediLSP restart command is registered only once.
  news/2 Fixes/16441.md
  src/client/activation/jedi/manager.ts
Labels: skip tests

#16486 Replace deprecated ExP methods with the newer ones
  src/client/common/experiments/service.ts
  src/test/common/experiments/service.unit.test.ts
  src/test/common/terminals/environmentActivationProviders/terminalActivation.testvirtualenvs.ts
  src/test/tensorBoard/tensorBoardSession.test.ts
Labels: skip news

#16570 Remove `SafeNotebookDocument` API compat wrapper class
  src/client/jupyter/languageserver/notebookConcatDocument.ts
  src/client/jupyter/languageserver/notebookConverter.ts
  src/client/jupyter/languageserver/safeNotebookDocument.ts
Labels: skip news, skip tests

#16560 Add language server support for native interactive window
  src/client/activation/languageClientMiddleware.ts
  src/client/common/constants.ts
  src/client/common/utils/misc.ts
  src/client/jupyter/languageserver/concatTextDocument.ts
  src/client/jupyter/languageserver/interactiveConcatTextDocument.ts
  src/client/jupyter/languageserver/nativeNotebookConcatTextDocument.ts
  src/client/jupyter/languageserver/notebookConcatDocument.ts
  src/client/jupyter/languageserver/notebookConverter.ts
  src/test/activation/languageServer/analysisOptions.unit.test.ts
  types/vscode-proposed/index.d.ts
  types/vscode.proposed.d.ts
Labels: skip news
