Repository microsoft/vscode-python, pull requests merged in 2021-01, with the labels that each got.

#15051 Make `src/test/smoke` pass ESLint
  .eslintignore
  src/test/smoke/common.ts
  src/test/smoke/runInTerminal.smoke.test.ts
Labels: skip news

#15053 Remove files from .eslintignore that don't need to be there
  .eslintignore
Labels: skip news

#15087 Revert "Revert "Add a locator for executables on $PATH on Windows.""
  package.json
  src/client/common/utils/exec.ts
  src/client/common/utils/text.ts
  src/client/pythonEnvironments/base/envsCache.ts
  src/client/pythonEnvironments/base/locators/lowLevel/filesLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/windowsKnownPathsLocator.ts
  src/client/pythonEnvironments/common/commonUtils.ts
  src/client/pythonEnvironments/common/externalDependencies.ts
  src/client/pythonEnvironments/discovery/locators/services/KnownPathsService.ts
  src/client/pythonEnvironments/index.ts
  src/test/common/platform/utils.ts
  src/test/pythonEnvironments/base/common.ts
  src/test/pythonEnvironments/base/locators/lowLevel/windowsKnownPathsLocator.functional.test.ts
  src/test/pythonEnvironments/discovery/locators/globalVirtualEnvironmentLocator.functional.test.ts
  src/test/pythonEnvironments/discovery/locators/pyenvLocator.functional.test.ts
  src/test/pythonEnvironments/discovery/locators/pyenvLocator.unit.test.ts
  src/test/testing/helper.ts
  src/test/testing/results.ts
  src/test/utils/fs.ts
Labels: skip news

#15097 Update vscode tas client.
  package-lock.json
  package.json
Labels: skip news

#15096 Add a GHA workflow to make sure PRs include the expected changed files
  .github/workflows/pr-check.yml
  .github/workflows/pr-file-check.yml
Labels: skip news

#15078 Add TensorBoard file system watcher test
  src/client/tensorBoard/serviceRegistry.ts
  src/test/tensorBoard/tensorBoardFileWatcher.test.ts
Labels: skip news, type-code health

#15073 Refactor TensorBoard prompt and import tracking and add tests
  src/client/tensorBoard/serviceRegistry.ts
  src/client/tensorBoard/tensorBoardImportTracker.ts
  src/client/tensorBoard/tensorBoardPrompt.ts
  src/client/tensorBoard/tensorBoardSession.ts
  src/client/tensorBoard/tensorBoardSessionProvider.ts
  src/test/tensorBoard/helpers.ts
  src/test/tensorBoard/tensorBoardImportTracker.unit.test.ts
  src/test/tensorBoard/tensorBoardPrompt.unit.test.ts
  types/vscode-proposed/index.d.ts
Labels: skip news

#15074 Add TensorBoard telemetry
  src/client/common/application/commands.ts
  src/client/common/installer/productInstaller.ts
  src/client/linters/bandit.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/client/tensorBoard/constants.ts
  src/client/tensorBoard/tensorBoardCodeActionProvider.ts
  src/client/tensorBoard/tensorBoardCodeLensProvider.ts
  src/client/tensorBoard/tensorBoardFileWatcher.ts
  src/client/tensorBoard/tensorBoardImportTracker.ts
  src/client/tensorBoard/tensorBoardPrompt.ts
  src/client/tensorBoard/tensorBoardSession.ts
  src/client/tensorBoard/tensorBoardSessionProvider.ts
  src/test/tensorBoard/tensorBoardPrompt.unit.test.ts
Labels: skip news

#15091 Add TensorBoard session creation test
  build/test-requirements.txt
  src/client/tensorBoard/serviceRegistry.ts
  src/client/tensorBoard/tensorBoardSession.ts
  src/client/tensorBoard/tensorBoardSessionProvider.ts
  src/test/tensorBoard/tensorBoardSession.test.ts
Labels: skip news, type-code health

#15108 Do not add to env cache if already present
  src/client/pythonEnvironments/base/locators/composite/cachingLocator.ts
  src/test/pythonEnvironments/base/locators/composite/cachingLocator.unit.test.ts
Labels: skip news

#15075 Show codelens when user launches TensorBoard from a Python notebook
  src/client/telemetry/importTracker.ts
  src/client/tensorBoard/helpers.ts
  src/client/tensorBoard/nbextensionCodeLensProvider.ts
  src/client/tensorBoard/serviceRegistry.ts
  src/client/tensorBoard/tensorBoardImportCodeLensProvider.ts
  src/client/tensorBoard/tensorBoardPrompt.ts
  src/client/tensorBoard/tensorBoardUsageTracker.ts
  src/test/pythonFiles/tensorBoard/noMatch.py
  src/test/pythonFiles/tensorBoard/tensorboard_import.ipynb
  src/test/pythonFiles/tensorBoard/tensorboard_imports.py
  src/test/pythonFiles/tensorBoard/tensorboard_launch.py
  src/test/pythonFiles/tensorBoard/tensorboard_nbextension.ipynb
  src/test/smoke/common.ts
  src/test/smoke/datascience.smoke.test.ts
  src/test/tensorBoard/nbextensionCodeLensProvider.insiders.test.ts
  src/test/tensorBoard/nbextensionCodeLensProvider.unit.test.ts
  src/test/tensorBoard/tensorBoardImportCodeLensProvider.unit.test.ts
  src/test/tensorBoard/tensorBoardUsageTracker.unit.test.ts
Labels: skip news

#15113 Ensure workspace envs are displayed in the second session
  src/client/pythonEnvironments/base/locators/composite/cachingLocator.ts
  src/test/pythonEnvironments/base/locators/composite/cachingLocator.unit.test.ts
Labels: skip news, skip tests

#15114 Ensure virtualenvwrapper type is displayed in the quickpick list
  src/client/pythonEnvironments/info/index.ts
  src/client/pythonEnvironments/legacyIOC.ts
Labels: skip news, skip tests

#15095 Add support for pytest 6 options
  news/2 Fixes/15094.md
  src/client/testing/pytest/services/argsService.ts
Labels: skip tests

#15100 ESLint fixes in src/test/format/
  .eslintignore
  src/test/format/extension.format.test.ts
  src/test/format/extension.lineFormatter.test.ts
  src/test/format/extension.onEnterFormat.test.ts
  src/test/format/extension.onTypeFormat.test.ts
  src/test/format/extension.sort.test.ts
  src/test/format/formatter.unit.test.ts
Labels: skip news

#15101 Partial ESLint fixes in src/test/mocks/
  .eslintignore
  src/test/mocks/autoSelector.ts
  src/test/mocks/mementos.ts
  src/test/mocks/moduleInstaller.ts
  src/test/mocks/proc.ts
  src/test/mocks/process.ts
Labels: skip news, skip tests

#15047 Update to Node 12.20
  .nvmrc
  CONTRIBUTING.md
  news/3 Code Health/15046.md
  package-lock.json
  package.json
  src/client/common/process/proc.ts
  src/client/providers/importSortProvider.ts
  src/client/providers/jediProxy.ts
  src/client/refactor/proxy.ts
  src/client/terminals/codeExecution/helper.ts
  src/client/testing/unittest/socketServer.ts
Labels: skip tests

#15120 Fire events with searchLocation set when an environment is created/modified/deleted
  src/client/pythonEnvironments/base/locator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/fsWatchingLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/windowsStoreLocator.ts
  src/test/pythonEnvironments/discovery/locators/watcherTestUtils.ts
  src/test/pythonEnvironments/discovery/locators/windowsStoreLocator.test.ts
Labels: skip news, skip tests

#14973 Add PythonEnvKind helpers.
  src/client/pythonEnvironments/base/info/env.ts
  src/client/pythonEnvironments/base/info/envKind.ts
  src/test/pythonEnvironments/base/info/envKind.unit.test.ts
Labels: skip news

#14910 Add more version helpers.
  src/client/common/utils/version.ts
  src/client/pythonEnvironments/base/info/env.ts
  src/client/pythonEnvironments/base/info/pythonVersion.ts
  src/test/pythonEnvironments/base/info/pythonVersion.unit.test.ts
Labels: skip news

#15121 Workspace filesystem watcher should not be behind experiment.
  src/client/pythonEnvironments/base/locators/lowLevel/fsWatchingLocator.ts
  src/test/pythonEnvironments/discovery/locators/lowLevel/fsWatchingLocator.unit.test.ts
Labels: skip news

#15126 Use new workspace virtualenv watcher when component is enabled
  src/client/interpreter/contracts.ts
  src/client/interpreter/virtualEnvs/virtualEnvPrompt.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/interpreters/virtualEnvs/virtualEnvPrompt.unit.test.ts
Labels: skip news

#15125 Track TensorBoard usage in integrated terminals
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/client/tensorBoard/serviceRegistry.ts
  src/client/tensorBoard/terminalWatcher.ts
Labels: skip news, skip tests

#15135 Update Version, Change log, TPN
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
  news/1 Enhancements/14781.md
  news/1 Enhancements/14997.md
  news/1 Enhancements/15003.md
  news/1 Enhancements/15079.md
  news/1 Enhancements/15106.md
  news/2 Fixes/14640.md
  news/2 Fixes/14812.md
  news/2 Fixes/14962.md
  news/2 Fixes/14983.md
  news/2 Fixes/15045.md
  news/2 Fixes/15094.md
  news/2 Fixes/3805.md
  news/3 Code Health/15046.md
  package-lock.json
  package.json
Labels: skip news

#15138 Update version for insiders
  package-lock.json
  package.json
Labels: skip news

#15123 Retain webview context
  src/client/tensorBoard/tensorBoardSession.ts
Labels: skip news, skip tests

#15136 Ensure experiment framework is registered along with platform classes before we initialize components
  src/client/extension.ts
  src/client/extensionActivation.ts
  src/client/extensionInit.ts
Labels: skip news, skip tests

#15144 Log when opt-in or opt-out of ALL experiments
  package.nls.json
  src/client/common/experiments/service.ts
  src/client/common/utils/localize.ts
Labels: skip news, skip tests

#15149 Python side of hiding interpreter for native notebooks
  src/client/interpreter/contracts.ts
  src/client/interpreter/display/index.ts
  src/client/interpreter/serviceRegistry.ts
  src/client/jupyter/jupyterIntegration.ts
  src/test/interpreters/display.unit.test.ts
Labels: skip news

#15134 Leverage ComponentAdapter.getInterpreterInformation in PythonPathUpdaterService
  .eslintignore
  src/client/interpreter/configuration/pythonPathUpdaterService.ts
  src/client/telemetry/index.ts
Labels: skip news, skip tests

#15150 Ensure experiment framework can be created using standard utils
  .eslintignore
  src/client/common/configSettings.ts
  src/client/common/experiments/service.ts
  src/client/extensionActivation.ts
  src/client/extensionInit.ts
  src/test/common/experiments/service.unit.test.ts
Labels: skip news

#15152 Use PythonInterpreterLocatorService and other classes only when in experiment
  src/client/extension.ts
  src/client/extensionInit.ts
  src/client/interpreter/interpreterService.ts
  src/client/pythonEnvironments/index.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/common/installer.test.ts
  src/test/common/moduleInstaller.test.ts
  src/test/common/variables/envVarsProvider.multiroot.test.ts
  src/test/debugger/envVars.test.ts
  src/test/format/extension.format.test.ts
  src/test/format/extension.sort.test.ts
  src/test/languageServers/jedi/autocomplete/base.test.ts
  src/test/languageServers/jedi/autocomplete/pep484.test.ts
  src/test/languageServers/jedi/autocomplete/pep526.test.ts
  src/test/languageServers/jedi/definitions/navigation.test.ts
  src/test/languageServers/jedi/signature/signature.jedi.test.ts
  src/test/linters/lint.multiroot.test.ts
  src/test/linters/lint.test.ts
  src/test/pythonEnvironments/discovery/locators/condaEnvService.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/interpreterLocatorService.testvirtualenvs.ts
  src/test/pythonEnvironments/legacyIOC.ts
  src/test/pythonEnvironments/legacyIOC.unit.test.ts
  src/test/refactor/extension.refactor.extract.method.test.ts
  src/test/refactor/extension.refactor.extract.var.test.ts
  src/test/serviceRegistry.ts
  src/test/testing/debugger.test.ts
  src/test/testing/nosetest/nosetest.disovery.test.ts
  src/test/testing/nosetest/nosetest.run.test.ts
  src/test/testing/nosetest/nosetest.test.ts
  src/test/testing/pytest/pytest.discovery.test.ts
  src/test/testing/pytest/pytest.run.test.ts
  src/test/testing/pytest/pytest.test.ts
  src/test/testing/pytest/pytest.testMessageService.test.ts
  src/test/testing/rediscover.test.ts
  src/test/testing/stoppingDiscoverAndTest.test.ts
  src/test/testing/unittest/unittest.discovery.test.ts
  src/test/testing/unittest/unittest.run.test.ts
  src/test/testing/unittest/unittest.test.ts
Labels: skip news

#15168 Disable windows path locator until it's fixed
  src/client/pythonEnvironments/index.ts
Labels: skip news, skip tests

#15157 Don't register or use InterpreterLocatorProgressService when in discovery experiment
  .eslintignore
  src/client/extensionActivation.ts
  src/client/interpreter/contracts.ts
  src/client/interpreter/display/progressDisplay.ts
  src/client/interpreter/serviceRegistry.ts
  src/client/pythonEnvironments/discovery/locators/progressService.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/interpreters/display/progressDisplay.unit.test.ts
  src/test/interpreters/serviceRegistry.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/progressService.unit.test.ts
Labels: skip news, skip tests

#15139 Implement Conda environment locator using the Conda service.
  src/client/pythonEnvironments/common/commonUtils.ts
  src/client/pythonEnvironments/common/environmentIdentifier.ts
  src/client/pythonEnvironments/discovery/locators/services/conda.ts
  src/client/pythonEnvironments/discovery/locators/services/condaLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/condaService.ts
  src/client/pythonEnvironments/index.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/pythonEnvironments/discovery/locators/condaEnvService.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/condaHelper.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/condaLocator.unit.test.ts
Labels: skip news, skip tests

#15158 Simplify interpreter hash usage
  package-lock.json
  package.json
  src/client/interpreter/helpers.ts
  src/client/interpreter/interpreterService.ts
  src/client/interpreter/locators/types.ts
  src/client/pythonEnvironments/discovery/locators/services/hashProvider.ts
  src/client/pythonEnvironments/discovery/locators/services/hashProviderFactory.ts
  src/client/pythonEnvironments/discovery/locators/services/windowsStoreInterpreter.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/interpreters/helpers.unit.test.ts
  src/test/interpreters/interpreterService.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/hasProviderFactory.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/hashProvider.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/windowsStoreInterpreter.unit.test.ts
  src/test/pythonEnvironments/legacyIOC.unit.test.ts
Labels: skip news

#15169 Address Sonar issues causing PR status check failures
  .eslintignore
  src/client/activation/common/downloader.ts
  src/client/common/crypto.ts
  src/client/common/platform/fileSystem.ts
  src/client/common/process/proc.ts
  src/startPage-ui/react-common/themeDetector.ts
  src/test/activation/languageServer/downloader.unit.test.ts
Labels: skip news

#15176 Stop using a fork of jedi-language-server
  requirements.in
  requirements.txt
Labels: skip news

#15167 Ensure "Python extension loading..." text disappears even when getting interpreters via the new API fails
  src/client/pythonEnvironments/legacyIOC.ts
Labels: skip news, skip tests

#15099 ESLint fixes in src/test/startPage/
  .eslintignore
  src/test/startPage/startPage.functional.test.tsx
  src/test/startPage/startPage.unit.test.ts
Labels: skip news

#15183 Fix getCondaEnvironment() in component adapter
  src/client/pythonEnvironments/legacyIOC.ts
Labels: skip news, skip tests

#15191 Added inDiscoveryExperiment() API
  src/client/common/experiments/helpers.ts
  src/test/common/experiments/helpers.unit.test.ts
Labels: skip news

#15193 Disable windows path locator until it's fixed (#15168)
  src/client/pythonEnvironments/index.ts
Labels: skip news, skip tests

#15173 Use component adapter to fetch workspace envs in autoselection module
  .eslintignore
  src/client/interpreter/autoSelection/rules/workspaceEnv.ts
  src/client/interpreter/contracts.ts
  src/client/pythonEnvironments/base/locators/lowLevel/workspaceVirtualEnvLocator.ts
  src/client/pythonEnvironments/index.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/interpreters/autoSelection/rules/workspaceEnv.unit.test.ts
  src/test/pythonEnvironments/base/locators/lowLevel/workspaceVirtualEnvLocator.unit.test.ts
  src/test/pythonEnvironments/legacyIOC.unit.test.ts
Labels: skip news

#15184 Don't register old workspace virtual env related classes when in discovery experiment
  .eslintignore
  src/client/interpreter/virtualEnvs/virtualEnvPrompt.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/interpreters/virtualEnvs/virtualEnvPrompt.unit.test.ts
Labels: skip news

#15194 Update version and changelog for release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip news

#15186 Add support for ignoreCache option in the API
  src/client/pythonEnvironments/base/locator.ts
  src/client/pythonEnvironments/base/locators/composite/cachingLocator.ts
  src/test/pythonEnvironments/base/locators/composite/cachingLocator.unit.test.ts
Labels: skip news

#15130 Add the getEnvDisplayString() helper.
  src/client/pythonEnvironments/base/info/env.ts
  src/client/pythonEnvironments/base/info/index.ts
  src/client/pythonEnvironments/base/info/pythonVersion.ts
  src/test/pythonEnvironments/base/info/env.unit.test.ts
Labels: skip news

#15178 WindowsStoreInterpreter: Extract the interpreter identifier functions
  .eslintignore
  src/client/common/process/pythonExecutionFactory.ts
  src/client/interpreter/contracts.ts
  src/client/interpreter/locators/types.ts
  src/client/jupyter/jupyterIntegration.ts
  src/client/pythonEnvironments/discovery/locators/services/windowsRegistryService.ts
  src/client/pythonEnvironments/discovery/locators/services/windowsStoreInterpreter.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/common/process/pythonExecutionFactory.unit.test.ts
  src/test/linters/lint.functional.test.ts
  src/test/pythonEnvironments/discovery/locators/windowsRegistryService.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/windowsStoreInterpreter.unit.test.ts
  src/test/pythonEnvironments/legacyIOC.unit.test.ts
  src/test/refactor/rename.test.ts
  src/test/tensorBoard/tensorBoardSession.test.ts
  src/test/testing/pytest/pytest.discovery.test.ts
  src/test/testing/pytest/pytest.run.test.ts
Labels: skip news

#15180 Prompt user to upgrade existing tensorboard < 2.4.1 to use integrated TensorBoard support
  build/test-requirements.txt
  package.nls.json
  src/client/common/installer/condaInstaller.ts
  src/client/common/installer/moduleInstaller.ts
  src/client/common/installer/pipEnvInstaller.ts
  src/client/common/installer/productInstaller.ts
  src/client/common/installer/types.ts
  src/client/common/process/internal/python.ts
  src/client/common/process/pythonEnvironment.ts
  src/client/common/process/pythonExecutionFactory.ts
  src/client/common/process/types.ts
  src/client/common/types.ts
  src/client/common/utils/localize.ts
  src/client/telemetry/index.ts
  src/client/tensorBoard/tensorBoardSession.ts
  src/client/tensorBoard/tensorBoardSessionProvider.ts
  src/test/common/installer/moduleInstaller.unit.test.ts
  src/test/interpreters/interpreterVersion.unit.test.ts
  src/test/tensorBoard/tensorBoardSession.test.ts
  src/test/terminals/codeExecution/djangoShellCodeExect.unit.test.ts
  src/test/terminals/codeExecution/terminalCodeExec.unit.test.ts
  src/test/testing/pytest/pytest.discovery.test.ts
  src/test/testing/pytest/pytest.run.test.ts
Labels: skip news

#15190 Remove old blob download code for Pylance
  src/client/activation/node/languageServerFolderService.ts
  src/client/activation/node/languageServerPackageRepository.ts
  src/client/activation/node/languageServerPackageService.ts
  src/client/activation/serviceRegistry.ts
  src/client/activation/types.ts
  src/test/activation/node/languageServerFolderService.unit.test.ts
Labels: skip news

#15201 Remove fallback from helpers.ts
  src/client/interpreter/helpers.ts
  src/test/interpreters/helpers.unit.test.ts
Labels: skip news

#15203 Remove fallback from interpreterService.ts
  src/client/interpreter/interpreterService.ts
  src/test/interpreters/interpreterService.unit.test.ts
Labels: skip news

#15205 Remove fallback for python path updater service.
  src/client/interpreter/configuration/pythonPathUpdaterService.ts
Labels: skip news, skip tests

#15210 Show prompt, code action and lens for tensorboardX
  src/client/tensorBoard/helpers.ts
  src/test/tensorBoard/tensorBoardCodeActionProvider.unit.test.ts
  src/test/tensorBoard/tensorBoardImportCodeLensProvider.unit.test.ts
  src/test/tensorBoard/tensorBoardUsageTracker.unit.test.ts
Labels: skip news

#15207 Remove fallback from virtual environment prompt
  src/client/interpreter/virtualEnvs/virtualEnvPrompt.ts
Labels: skip news, skip tests

#15206 Remove fallback from the progressDisplay.ts
  src/client/interpreter/display/progressDisplay.ts
  src/test/interpreters/display/progressDisplay.unit.test.ts
Labels: skip news

#15225 Fix discovery when in refactor experiment
  src/client/common/process/pythonExecutionFactory.ts
Labels: skip news, skip tests

#15227 Fix wrong interface passed to PythonPathUpdaterService
  src/client/interpreter/configuration/pythonPathUpdaterService.ts
Labels: skip news, skip tests

#15226 Fallback to the old mechanism to calculate displayName if not set by new discovery component
  src/client/interpreter/interpreterService.ts
Labels: skip news, skip tests

#15192 Add source field to environment info
  src/client/pythonEnvironments/base/info/env.ts
  src/client/pythonEnvironments/base/info/index.ts
  src/client/pythonEnvironments/base/locators/lowLevel/windowsKnownPathsLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/workspaceVirtualEnvLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/condaLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/customVirtualEnvLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/globalVirtualEnvronmentLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/posixKnownPathsLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/pyenvLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/windowsRegistryLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/windowsStoreLocator.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/pythonEnvironments/base/locators/lowLevel/windowsKnownPathsLocator.functional.test.ts
  src/test/pythonEnvironments/base/locators/lowLevel/workspaceVirtualEnvLocator.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/condaHelper.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/customVirtualEnvLocator.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/globalVirtualEnvironmentLocator.functional.test.ts
  src/test/pythonEnvironments/discovery/locators/posixKnownPathsLocator.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/pyenvLocator.functional.test.ts
  src/test/pythonEnvironments/discovery/locators/windowsRegistryLocator.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/windowsStoreLocator.unit.test.ts
Labels: skip news

#15208 Support moving/adding/deleting cells in notebook intellisense
  src/client/jupyter/languageserver/notebookConcatDocument.ts
  src/client/jupyter/languageserver/notebookConverter.ts
  src/client/jupyter/languageserver/notebookMiddlewareAddon.ts
  src/test/initialize.ts
  src/test/insiders/languageServer.insiders.test.ts
Labels: skip news

#15228 Merge back from release
  CHANGELOG.md
Labels: skip news, skip tests

#15223 Send telemetry when an interpreter was selected, or the quickpick dismissed
  .eslintignore
  src/client/common/utils/multiStepInput.ts
  src/client/interpreter/configuration/interpreterSelector/commands/setInterpreter.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/test/configuration/interpreterSelector/commands/setInterpreter.unit.test.ts
Labels: skip news

#15234 Drop A/B test and search 3 directories deep for tfevent files
  package.json
  pythonFiles/tensorboard_launcher.py
  src/client/common/experiments/groups.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/client/tensorBoard/constants.ts
  src/client/tensorBoard/nbextensionCodeLensProvider.ts
  src/client/tensorBoard/serviceRegistry.ts
  src/client/tensorBoard/tensorBoardCodeActionProvider.ts
  src/client/tensorBoard/tensorBoardFileWatcher.ts
  src/client/tensorBoard/tensorBoardImportCodeLensProvider.ts
  src/client/tensorBoard/tensorBoardSessionProvider.ts
  src/test/tensorBoard/tensorBoardCodeActionProvider.unit.test.ts
  src/test/tensorBoard/tensorBoardFileWatcher.test.ts
Labels: skip news, skip package*.json

#15238 Access and register old current path locator when not in experiment
  src/client/interpreter/autoSelection/rules/currentPath.ts
  src/client/interpreter/contracts.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/interpreters/autoSelection/rules/currentPath.unit.test.ts
Labels: skip news

#15195 Ensure workspace environments are autoselected when a workspace is opened for the first time
  src/client/interpreter/autoSelection/rules/workspaceEnv.ts
  src/client/interpreter/contracts.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/interpreters/autoSelection/rules/workspaceEnv.unit.test.ts
Labels: skip news

#15241 Drop PythonEnvInfo.defaultDisplayName.
  src/client/pythonEnvironments/base/info/env.ts
  src/client/pythonEnvironments/base/info/index.ts
  src/client/pythonEnvironments/common/windowsUtils.ts
  src/client/pythonEnvironments/discovery/locators/services/pyenvLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/windowsRegistryLocator.ts
  src/test/pythonEnvironments/base/envsCache.unit.test.ts
  src/test/pythonEnvironments/base/info/env.unit.test.ts
  src/test/pythonEnvironments/base/locators/lowLevel/workspaceVirtualEnvLocator.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/condaHelper.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/customVirtualEnvLocator.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/globalVirtualEnvironmentLocator.functional.test.ts
  src/test/pythonEnvironments/discovery/locators/pyenvLocator.functional.test.ts
  src/test/pythonEnvironments/discovery/locators/windowsRegistryLocator.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/windowsStoreLocator.unit.test.ts
Labels: skip news

#15244 Do not open start page when running in Codespaces
  news/1 Enhancements/14833.md
  news/1 Enhancements/15229.md
  src/client/common/startPage/startPage.ts
Labels: skip news, skip tests

#15196 Ensure bitness and additional info for workspace envs is eventually shown
  src/client/interpreter/interpreterService.ts
  src/client/pythonEnvironments/index.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/client/pythonEnvironments/security.ts
Labels: skip news, skip tests

#15243 Don't register PythonInPathCommandProvider when in experiment
  src/client/pythonEnvironments/legacyIOC.ts
Labels: skip news, skip tests

#15245 Use the component adapter to fetch Windows registry envs in legacy code.
  src/client/interpreter/autoSelection/rules/winRegistry.ts
  src/client/interpreter/contracts.ts
  src/client/pythonEnvironments/discovery/locators/services/condaService.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/interpreters/autoSelection/rules/winRegistry.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/condaService.unit.test.ts
Labels: skip news

#15253 Stub inside the sandbox
  src/test/tensorBoard/tensorBoardFileWatcher.test.ts
Labels: skip news

#15255 Always use test Python for test TensorBoard sessions
  src/test/tensorBoard/tensorBoardSession.test.ts
Labels: skip news

#15259 Only register old WinReg Locator when not in experiment
  src/client/interpreter/autoSelection/rules/winRegistry.ts
  src/client/pythonEnvironments/discovery/locators/services/condaService.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/interpreters/autoSelection/rules/winRegistry.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/condaService.unit.test.ts
  src/test/pythonEnvironments/legacyIOC.unit.test.ts
Labels: skip news

#15242 Add completion metric to jedi completion event
  src/client/providers/completionProvider.ts
  src/client/telemetry/index.ts
Labels: skip news, skip tests
