Repository microsoft/vscode-python, pull requests merged in 2021-05, with the labels that each got.

#16097 Add without watcher option to opt in or out
  package.json
Labels: skip news, skip package*.json

#16077 Bundle Pylance as part of an extension pack (not a hard dependency)
  .github/actions/build-vsix/action.yml
  gulpfile.js
  package.json
Labels: skip news, skip package*.json, skip tests

#16096 Unify build workflows
  .github/workflows/build.yml
  .github/workflows/insiders.yml
Labels: skip news

#16068 Add Python: Refresh TensorBoard command
  news/1 Enhancements/16053.md
  package.json
  package.nls.json
  src/client/common/constants.ts
  src/client/tensorBoard/tensorBoardSession.ts
  src/client/tensorBoard/tensorBoardSessionProvider.ts
Labels: skip package*.json, skip tests

#16074 Remove default pylint when using jedi
  .github/test_plan.md
  package.json
  src/client/common/configSettings.ts
  src/client/common/types.ts
  src/client/linters/linterAvailability.ts
  src/client/linters/linterCommands.ts
  src/client/linters/linterInfo.ts
  src/client/linters/linterManager.ts
  src/client/linters/lintingEngine.ts
  src/client/linters/pylint.ts
  src/client/linters/types.ts
  src/client/providers/linterProvider.ts
  src/test/.vscode/settings.json
  src/test/linters/common.ts
  src/test/linters/lint.args.test.ts
  src/test/linters/lint.functional.test.ts
  src/test/linters/lint.manager.unit.test.ts
  src/test/linters/lint.multilinter.test.ts
  src/test/linters/lint.provider.test.ts
  src/test/linters/lint.test.ts
  src/test/linters/lint.unit.test.ts
  src/test/linters/lintengine.test.ts
  src/test/linters/linter.availability.unit.test.ts
  src/test/linters/linterCommands.unit.test.ts
  src/test/linters/linterManager.unit.test.ts
  src/test/linters/linterinfo.unit.test.ts
  src/test/linters/pylint.test.ts
  src/test/linters/pylint.unit.test.ts
  src/test/mockClasses.ts
Labels: skip news, skip package*.json

#16114 Ignore environment related cache where appropriate
  src/client/interpreter/interpreterService.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/interpreters/interpreterService.unit.test.ts
Labels: skip news

#16125 Remove unused resources
  resources/InstallJupyter.png
  resources/MagicPython.tmLanguage.json
  resources/PythonSelector.png
  resources/defaultTheme.json
Labels: skip news, skip tests

#16134 Update readme + license at build time
  README.md
  build/license-header.txt
  gulpfile.js
  news/1 Enhancements/16116.md
  package.json
Labels: skip package*.json, skip tests

#16129 Add PyTorch profiler jump to source telemetry
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/client/tensorBoard/tensorBoardSession.ts
Labels: skip news, skip package*.json, skip tests

#16069 Display an informational Pylance prompt for existing users
  package.nls.json
  src/client/application/diagnostics/checks/pylanceDefault.ts
  src/client/application/diagnostics/constants.ts
  src/client/application/diagnostics/serviceRegistry.ts
  src/client/common/startPage/startPage.ts
  src/client/common/startPage/types.ts
  src/client/common/utils/localize.ts
  src/test/application/diagnostics/checks/pylanceDefault.unit.test.ts
  src/test/startPage/startPage.unit.test.ts
  src/test/startPage/startPageIocContainer.ts
Labels: skip news

#16140 Correct the vsix artifact name to be uploaded
  .github/workflows/build.yml
Labels: skip news, skip tests

#16143 Update the trusted workspaces setting
  package.json
Labels: skip news, skip package*.json

#16144 Correct the vsix artifact name to be downloaded
  .github/workflows/build.yml
Labels: skip news, skip tests

#16142 Merge default-language-server into main
  .github/actions/build-vsix/action.yml
  README.md
  build/license-header.txt
  gulpfile.js
  news/1 Enhancements/16116.md
  package.json
  package.nls.json
  src/client/application/diagnostics/checks/pylanceDefault.ts
  src/client/application/diagnostics/constants.ts
  src/client/application/diagnostics/serviceRegistry.ts
  src/client/common/startPage/startPage.ts
  src/client/common/startPage/types.ts
  src/client/common/utils/localize.ts
  src/test/application/diagnostics/checks/pylanceDefault.unit.test.ts
  src/test/startPage/startPage.unit.test.ts
  src/test/startPage/startPageIocContainer.ts
Labels: skip package*.json

#16155 Add "Default" LS setting, which picks between Jedi/Pylance
  news/1 Enhancements/16157.md
  package.json
  src/client/activation/activationService.ts
  src/client/activation/common/defaultlanguageServer.ts
  src/client/common/configSettings.ts
  src/client/common/configuration/service.ts
  src/client/common/experiments/helpers.ts
  src/client/common/types.ts
  src/client/extensionActivation.ts
  src/test/activation/defaultLanguageServer.unit.test.ts
  src/test/common/experiments/helpers.unit.test.ts
Labels: skip package*.json

#16158 Fix indentation in build workflow
  .github/workflows/build.yml
Labels: skip news

#16128 Remove unused files and update branch
  .github/workflows/codeql-analysis.yml
  resources/ctagOptions
Labels: skip news

#16164 Do not retrigger discovery on change everytime
  src/client/extensionActivation.ts
  src/client/pythonEnvironments/index.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/pythonEnvironments/legacyIOC.ts
Labels: skip news, skip tests

#16168 Add missing word in Pylance prompt
  package.nls.json
  src/client/common/utils/localize.ts
Labels: skip news, skip tests

#16171 Release candidate for may release
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
  news/1 Enhancements/15695.md
  news/1 Enhancements/15862.md
  news/1 Enhancements/15924.md
  news/1 Enhancements/16029.md
  news/1 Enhancements/16053.md
  news/1 Enhancements/16104.md
  news/1 Enhancements/16116.md
  news/1 Enhancements/16157.md
  news/2 Fixes/15681.md
  news/2 Fixes/15788.md
  news/2 Fixes/15807.md
  news/2 Fixes/15947.md
  news/2 Fixes/15968.md
  news/2 Fixes/16027.md
  news/2 Fixes/16119.md
  news/3 Code Health/15837.md
  news/3 Code Health/15933.md
  news/3 Code Health/16127.md
  news/3 Code Health/16131.md
  package-lock.json
  package.json
Labels: skip news

#16159 Linting pass
  .eslintignore
  src/client/application/diagnostics/serviceRegistry.ts
  src/client/common/startPage/startPage.ts
  src/client/common/startPage/types.ts
  src/test/startPage/startPageIocContainer.ts
Labels: skip news, skip tests

#16165 Update pygls dependency
  jedils_requirements.in
  jedils_requirements.txt
Labels: skip news

#16180 Upgrade all Jedi language server packages
  jedils_requirements.txt
Labels: skip news

#16181 Cherry-picks into release from main
  jedils_requirements.in
  jedils_requirements.txt
Labels: skip news

#16196 Update release version
  package-lock.json
  package.json
Labels: skip news

#16185 Remove `ICustomEditorService`
  src/client/common/application/customEditorService.ts
  src/client/common/application/types.ts
  src/client/common/serviceRegistry.ts
  src/test/common/installer.test.ts
  src/test/common/moduleInstaller.test.ts
Labels: skip news

#16182 Update node modules
  package-lock.json
Labels: skip news, skip package*.json

#16215 Add test view with a welcome button
  package.json
  src/client/testing/explorer/treeView.ts
  src/client/testing/main.ts
  src/client/testing/serviceRegistry.ts
  src/client/testing/testController/controller.ts
  src/test/testing/explorer/treeView.unit.test.ts
  types/vscode.proposed.d.ts
Labels: skip news, skip package*.json, skip tests

#16228 Update npm lockfile version
  news/2 Fixes/16208.md
  package-lock.json
Labels: skip package*.json

#16237 Point release: Update version and change log.
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip news

#16246 Fix Pylance Python 2 mistake
  src/client/activation/activationService.ts
Labels: skip news, skip tests

#16264 Flag that we don't support virtual workspaces
  package.json
Labels: skip news, skip package*.json

#16230 Fill report issue template with output logs
  resources/report_issue_template.md
  src/client/common/application/commands/reportIssueCommand.ts
  src/client/logging/_global.ts
  src/client/logging/index.ts
  src/client/logging/transports.ts
  src/test/common/application/commands/issueTemplateVenv1.md
  src/test/common/application/commands/reportIssueCommand.unit.test.ts
Labels: skip news

#16267 Make Jupyter an optional dependency
  .github/actions/build-vsix/action.yml
  gulpfile.js
  news/1 Enhancements/16102.md
  package.json
Labels: skip package*.json

#16236 Add an "enumDescriptions" key to describe all language server options
  news/1 Enhancements/16141.md
  package.json
Labels: skip package*.json

#16273 Update pydantic
  jedils_requirements.txt
Labels: skip news

#16278 License wording update
  build/license-header.txt
Labels: skip news

#16298 Removing view test ui and view test output commands
  src/client/common/application/commands.ts
  src/client/common/constants.ts
  src/client/testing/common/managers/baseTestManager.ts
  src/client/testing/common/testUtils.ts
  src/client/testing/common/types.ts
  src/client/testing/display/main.ts
  src/client/testing/display/picker.ts
  src/client/testing/main.ts
  src/test/testing/common/trackEnablement.unit.test.ts
  src/test/testing/configuration.unit.test.ts
  src/test/testing/display/main.unit.test.ts
  src/test/testing/display/picker.unit.test.ts
  src/test/testing/unittest/unittest.discovery.unit.test.ts
Labels: skip news

#16300 Remove test picker
  src/client/testing/display/main.ts
  src/client/testing/display/picker.ts
  src/client/testing/serviceRegistry.ts
  src/test/testing/display/main.unit.test.ts
  src/test/testing/display/picker.functional.test.ts
  src/test/testing/display/picker.unit.test.ts
Labels: skip news

#16314 Remove more test commands
  package.json
  package.nls.de.json
  package.nls.es.json
  package.nls.fr.json
  package.nls.it.json
  package.nls.ja.json
  package.nls.json
  package.nls.ko-kr.json
  package.nls.nl.json
  package.nls.pl.json
  package.nls.pt-br.json
  package.nls.ru.json
  package.nls.tr.json
  package.nls.zh-cn.json
  package.nls.zh-tw.json
  src/client/common/application/commands.ts
  src/client/common/constants.ts
  src/client/testing/common/types.ts
  src/client/testing/main.ts
Labels: skip news, skip package*.json, skip tests

#16315 Remove more test commands
  package.json
  package.nls.de.json
  package.nls.es.json
  package.nls.fr.json
  package.nls.it.json
  package.nls.ja.json
  package.nls.json
  package.nls.ko-kr.json
  package.nls.nl.json
  package.nls.pl.json
  package.nls.pt-br.json
  package.nls.ru.json
  package.nls.tr.json
  package.nls.zh-cn.json
  package.nls.zh-tw.json
  src/client/common/application/commands.ts
  src/client/common/constants.ts
  src/client/testing/main.ts
Labels: skip news, skip package*.json, skip tests

#16319 Remove testing dependency on language server
  src/client/activation/jedi.ts
  src/client/activation/jedi/languageServerProxy.ts
  src/client/activation/languageServer/languageServerProxy.ts
  src/client/activation/node/languageServerProxy.ts
  src/client/extensionActivation.ts
  src/client/testing/common/services/contextService.ts
  src/client/testing/common/types.ts
  src/client/testing/main.ts
  src/client/testing/serviceRegistry.ts
  src/client/testing/types.ts
  src/test/activation/languageServer/languageServer.unit.test.ts
  src/test/testing/common/services/contextService.unit.test.ts
  src/test/testing/serviceRegistry.ts
Labels: skip news

#16321 Add a "Jupyter not installed" notification helper
  package.nls.json
  src/client/common/serviceRegistry.ts
  src/client/common/utils/localize.ts
  src/client/jupyter/jupyterNotInstalledNotificationHelper.ts
  src/client/jupyter/types.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/test/common/moduleInstaller.test.ts
  src/test/jupyter/jupyterNotInstalledNotificationHelper.unit.test.ts
Labels: skip news

#16350 Update virtual workspace disablement
  package.json
Labels: skip news, skip package*.json
