Repository microsoft/vscode-python, pull requests merged in 2021-08, with the labels that each got.

#16838 Fix interactive window diagnostics position
  src/client/jupyter/languageserver/interactiveConcatTextDocument.ts
Labels: skip news, skip tests

#16847 Release candidate
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
  news/1 Enhancements/13007.md
  news/1 Enhancements/16678.md
  news/1 Enhancements/16765.md
  news/3 Code Health/8406.md
  package-lock.json
  package.json
Labels: skip news

#16850 Update main branch version
  package-lock.json
  package.json
Labels: skip news

#16868 Update version and change log.
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip news

#16848 Deprecate inExperiment API in favor of inExperimentSync
  news/2 Fixes/16768.md
  src/client/common/experiments/service.ts
  src/client/extension.ts
  src/client/extensionActivation.ts
  src/test/common/experiments/service.unit.test.ts
Labels: skip news

#16880 Fix order of default unittest arguments
  news/2 Fixes/16882.md
  package.json
Labels: skip package*.json

#16886 Remove unused code
  src/client/testing/common/constants.ts
  src/client/testing/common/runner.ts
  src/client/testing/common/testUtils.ts
  src/client/testing/common/types.ts
  src/test/testing/common/services/storageService.unit.test.ts
  src/test/testing/common/testUtils.unit.test.ts
  src/test/testing/helper.ts
  src/test/testing/mocks.ts
  src/test/testing/results.ts
Labels: skip news

#16885 Show re-run failed test command only when there are test failures.
  news/2 Fixes/16856.md
  package-lock.json
  package.json
  src/client/common/application/contextKeyManager.ts
  src/client/common/application/contextKeys.ts
  src/client/common/application/types.ts
  src/client/common/experiments/groups.ts
  src/client/common/serviceRegistry.ts
  src/client/testing/main.ts
  src/client/testing/testController/common/testItemUtilities.ts
  types/vscode.proposed.d.ts
Labels: skip tests

#16892 Triggering test refresh shows stop and refreshing indicator.
  news/2 Fixes/16891.md
  package.json
  package.nls.json
  src/client/common/application/commands.ts
  src/client/common/application/contextKeys.ts
  src/client/common/constants.ts
  src/client/common/experiments/groups.ts
  src/client/testing/main.ts
  src/client/testing/testController/common/types.ts
  src/client/testing/testController/controller.ts
  src/client/testing/testController/pytest/pytestController.ts
  src/client/testing/testController/unittest/unittestController.ts
Labels: skip package*.json, skip tests

#16890 Fix screenshot for open folder tile on Python for data science walkthrough
  images/OpenOrCreateNotebook.gif
  package.json
  resources/walkthrough/open-folder-dark.png
  resources/walkthrough/open-folder-hc.png
  resources/walkthrough/open-folder-light.png
Labels: skip news, skip package*.json

#16904 Turn off automatic code review assignment
  .github/assign-reviewers.yml
  .github/assign-reviewers/__main__.py
  .github/workflows/assign-reviewers.yml
Labels: skip news

#16903 Merge release-2021.08 into merge-back
  CHANGELOG.md
  news/2 Fixes/16768.md
  news/2 Fixes/16882.md
Labels: skip news

#16906 Fix for some bugs
  news/2 Fixes/16855.md
  news/2 Fixes/16902.md
  src/client/testing/testController/controller.ts
  src/client/testing/testController/unittest/unittestController.ts
Labels: skip tests

#16901 Remove MPLS survey
  package.nls.json
  src/client/activation/serviceRegistry.ts
  src/client/application/diagnostics/checks/mplsSurvey.ts
  src/client/common/utils/localize.ts
  src/test/application/diagnostics/checks/mplsSurvey.unit.test.ts
Labels: skip news, skip package*.json

#16913 Add telemetry for testing usage
  src/client/common/constants.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/client/telemetry/types.ts
  src/client/testing/main.ts
  src/client/testing/testController/controller.ts
  src/client/testing/testController/pytest/pytestController.ts
  src/client/testing/testController/unittest/unittestController.ts
Labels: skip news, skip tests

#16925 Add debug file button to editor run menu
  news/1 Enhancements/16924.md
  package.json
  package.nls.json
  src/client/common/application/commands.ts
  src/client/common/constants.ts
  src/client/debugger/extension/debugCommands.ts
  src/client/debugger/extension/serviceRegistry.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/test/debugger/extension/debugCommands.unit.test.ts
  src/test/debugger/extension/serviceRegistry.unit.test.ts
Labels: skip package*.json

#16933 Remove find interpreter experiment
  package.nls.json
  package.nls.zh-cn.json
  src/client/common/experiments/groups.ts
  src/client/common/utils/localize.ts
  src/client/interpreter/configuration/interpreterSelector/commands/setInterpreter.ts
  src/test/configuration/interpreterSelector/commands/setInterpreter.unit.test.ts
Labels: skip news

#16948 Revert "Remove find interpreter experiment"
  package.nls.json
  package.nls.zh-cn.json
  src/client/common/experiments/groups.ts
  src/client/common/utils/localize.ts
  src/client/interpreter/configuration/interpreterSelector/commands/setInterpreter.ts
  src/test/configuration/interpreterSelector/commands/setInterpreter.unit.test.ts
Labels: skip news

#16949 Remove 'test' config option.
  news/2 Fixes/15790.md
  package.json
  src/client/debugger/extension/configuration/debugConfigurationService.ts
  src/client/debugger/extension/configuration/launch.json/launchJsonReader.ts
  src/client/debugger/extension/configuration/resolvers/launch.ts
  src/client/debugger/extension/configuration/types.ts
  src/client/debugger/extension/debugCommands.ts
  src/client/debugger/extension/serviceRegistry.ts
  src/client/debugger/types.ts
  src/client/testing/common/debugLauncher.ts
  src/client/testing/common/types.ts
  src/test/debugger/extension/debugCommands.unit.test.ts
  src/test/debugger/extension/serviceRegistry.unit.test.ts
  src/test/testing/common/debugLauncher.unit.test.ts
Labels: skip package*.json

#16953 Show notification to configure test framework
  news/2 Fixes/16941.md
  package.nls.json
  package.nls.nl.json
  package.nls.zh-cn.json
  package.nls.zh-tw.json
  src/client/common/application/commands.ts
  src/client/common/utils/localize.ts
  src/client/testing/main.ts
  src/client/testing/testController/common/types.ts
  src/client/testing/testController/controller.ts
Labels: skip tests

#16954 Remove find interpreter use enter interpreter instead.
  package.nls.json
  package.nls.zh-cn.json
  src/client/common/experiments/groups.ts
  src/client/common/utils/localize.ts
  src/client/interpreter/configuration/interpreterSelector/commands/setInterpreter.ts
  src/test/configuration/interpreterSelector/commands/setInterpreter.unit.test.ts
Labels: skip news

#16960 Fix TSA warning on test app.
  src/testMultiRootWkspc/workspace5/djangoApp/mysite/settings.py
Labels: skip news

#16955 Wait for 5 mins before showing join insiders prompt.
  news/1 Enhancements/16833.md
  src/client/common/insidersBuild/insidersExtensionService.ts
Labels: skip news, skip tests

#16967 More fixes for test UI
  news/2 Fixes/16962.md
  news/2 Fixes/16963.md
  src/client/testing/testController/common/testItemUtilities.ts
  src/client/testing/testController/unittest/unittestController.ts
Labels: skip tests

#16912 Add webpack build for browser entrypoint
  .gitignore
  build/webpack/webpack.extension.browser.config.js
  gulpfile.js
  news/1 Enhancements/16869.md
  news/1 Enhancements/16870.md
  package.json
  src/client/browser/extension.ts
  tsconfig.browser.json
  typings/webworker.fix.d.ts
Labels: skip package*.json, skip tests

#16938 Update install instructions for data science walkthrough
  package.json
Labels: skip news, skip package*.json

#16660 Notebook/IW language client middleware as separate module
  package-lock.json
  package.json
  src/client/activation/languageClientMiddleware.ts
  src/client/jupyter/languageserver/concatTextDocument.ts
  src/client/jupyter/languageserver/interactiveConcatTextDocument.ts
  src/client/jupyter/languageserver/nativeNotebookConcatTextDocument.ts
  src/client/jupyter/languageserver/notebookConcatDocument.ts
  src/client/jupyter/languageserver/notebookConverter.ts
  src/client/jupyter/languageserver/notebookMiddlewareAddon.ts
Labels: skip news, skip tests

#16775 Add environments collection class
  src/client/pythonEnvironments/base/locator.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionCache.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/client/pythonEnvironments/base/locators/composite/resolverUtils.ts
  src/client/pythonEnvironments/base/watcher.ts
  src/client/pythonEnvironments/common/externalDependencies.ts
  src/client/pythonEnvironments/index.ts
  src/client/pythonEnvironments/newApi.ts
  src/test/pythonEnvironments/base/locators/envTestUtils.ts
Labels: skip news, skip tests

#17005 Change discovery component API
  news/1 Enhancements/17005.md
  src/client/common/utils/backgroundLoop.ts
  src/client/extensionInit.ts
  src/client/interpreter/contracts.ts
  src/client/pythonEnvironments/api.ts
  src/client/pythonEnvironments/base/envsCache.ts
  src/client/pythonEnvironments/base/locators/common/wrappingLocator.ts
  src/client/pythonEnvironments/base/locators/composite/cachingLocator.ts
  src/client/pythonEnvironments/discovery/locators/services/condaLocatorService.ts
  src/client/pythonEnvironments/index.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/client/pythonEnvironments/newApi.ts
  src/test/pythonEnvironments/base/envsCache.unit.test.ts
  src/test/pythonEnvironments/base/locators/composite/cachingLocator.unit.test.ts
  src/test/pythonEnvironments/legacyIOC.ts
Labels: skip news

#17010 Get telemetry client and LS middleware working in the browser
  .vscode/settings.json
  build/webpack/webpack.extension.config.js
  gulpfile.js
  news/3 Code Health/16871.md
  news/3 Code Health/16872.md
  package-lock.json
  package.json
  src/client/activation/languageClientMiddleware.ts
  src/client/activation/languageClientMiddlewareBase.ts
  src/client/browser/extension.ts
  src/client/telemetry/index.ts
Labels: skip tests

#17022 Add telemetry to measure discovery time
  src/client/interpreter/interpreterService.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/client/pythonEnvironments/discovery/locators/services/cacheableLocatorService.ts
  src/client/telemetry/index.ts
Labels: skip news, skip tests

#16982 Minor tweaks to help with startup perf.
  news/3 Code Health/16983.md
  src/client/activation/activationManager.ts
  src/client/common/utils/runAfterActivation.ts
  src/client/extension.ts
  src/client/extensionActivation.ts
  src/client/pythonEnvironments/common/commonUtils.ts
  src/client/pythonEnvironments/index.ts
Labels: skip tests

#17027 Improve discovery API design
  src/client/pythonEnvironments/api.ts
  src/client/pythonEnvironments/base/locator.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/client/pythonEnvironments/index.ts
  src/client/pythonEnvironments/legacyIOC.ts
Labels: skip news, skip tests

#17026 Add caching debug config behind experiment.
  news/1 Enhancements/17025.md
  package.json
  src/client/common/experiments/groups.ts
  src/client/debugger/extension/configuration/debugConfigurationService.ts
  src/test/debugger/extension/configuration/debugConfigurationService.unit.test.ts
Labels: skip package*.json

#17028 Update lsp middleware to latest
  package-lock.json
  package.json
  src/client/activation/languageClientMiddleware.ts
  src/client/activation/languageClientMiddlewareBase.ts
Labels: skip news, skip tests

#17033 Wait for pylance instead of failing in the browser
  src/client/browser/extension.ts
Labels: skip news, skip tests

#17036 Cherry pick "Wait for pylance instead of failing in the browser"
  src/client/browser/extension.ts
Labels: skip news, skip tests

#17023 Update version number and change log for point release
  CHANGELOG.md
  news/1 Enhancements/16869.md
  news/1 Enhancements/16870.md
  news/3 Code Health/16871.md
  news/3 Code Health/16872.md
  package-lock.json
  package.json
Labels: skip news

#17029 Add notification about 2.7 support
  news/1 Enhancements/17009.md
  package.nls.json
  src/client/common/utils/localize.ts
  src/client/interpreter/contracts.ts
  src/client/interpreter/display/index.ts
  src/client/interpreter/display/python27Prompt.ts
  src/client/interpreter/serviceRegistry.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/test/interpreters/display.unit.test.ts
  src/test/interpreters/display/python27Prompt.unit.test.ts
Labels: skip package*.json

#17042 Pass interpreter to shouldShowPrompt directly
  src/client/interpreter/contracts.ts
  src/client/interpreter/display/index.ts
  src/client/interpreter/display/python27Prompt.ts
  src/test/interpreters/display/python27Prompt.unit.test.ts
Labels: skip news

#17053 Add MPLS deprecation prompt
  news/1 Enhancements/17056.md
  package.nls.json
  src/client/activation/languageServer/activator.ts
  src/client/activation/languageServer/deprecationPrompt.ts
  src/client/activation/serviceRegistry.ts
  src/client/activation/types.ts
  src/client/common/utils/localize.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/test/activation/languageServer/activator.unit.test.ts
  src/test/activation/languageServer/deprecationPrompt.unit.test.ts
  src/test/activation/serviceRegistry.unit.test.ts
Labels: skip package*.json

#17057 Fix diag messages for magics
  news/2 Fixes/17058.md
  package-lock.json
  package.json
Labels: skip tests

#17060 Consolidate "Learn More" tile in the Python walkthroughs
  package.json
  resources/walkthrough/python-datascience-learn-more.md
  resources/walkthrough/python-dev-learn-more.md
Labels: skip news, skip package*.json

#17071 Update vscode-extension-telemetry to 0.2.9
  package-lock.json
  package.json
  src/client/browser/extension.ts
  src/client/telemetry/index.ts
Labels: skip news, skip tests

#17074 Update version and change log for point release.
  CHANGELOG.md
  package-lock.json
  package.json
  src/client/browser/extension.ts
  src/client/telemetry/index.ts
Labels: skip news, skip tests

#17077 Merge branch release-2021.08 into main
  CHANGELOG.md
  news/1 Enhancements/16869.md
  news/1 Enhancements/16870.md
  news/2 Fixes/17049.md
  news/3 Code Health/16871.md
  news/3 Code Health/16872.md
Labels: skip news

#17081 Cherry pick and update version for release
  CHANGELOG.md
  gulpfile.js
  package-lock.json
  package.json
Labels: skip news

#17086 Ensure runId is formatted the same way as results.
  news/2 Fixes/17079.md
  src/client/testing/testController/common/resultsHelper.ts
  src/client/testing/testController/common/testItemUtilities.ts
Labels: skip tests

#17143 Disable venv tests on windows
  .github/workflows/build.yml
  .github/workflows/pr-check.yml
Labels: skip news

#17160 Update main branch version
  package-lock.json
  package.json
Labels: skip news

#17161 Ensure default python executable to use is 'python' instead of ''
  news/2 Fixes/17089.md
  src/client/common/configSettings.ts
Labels: skip tests

#17144 Ensure workspace interpreters are discovered and watched
  news/2 Fixes/17144.md
  src/client/common/platform/fs-paths.ts
  src/client/common/utils/misc.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionCache.ts
  src/client/pythonEnvironments/base/locators/lowLevel/fsWatchingLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/poetryLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/workspaceVirtualEnvLocator.ts
  src/client/pythonEnvironments/common/pythonBinariesWatcher.ts
Labels: skip tests
