Repository microsoft/vscode-python, pull requests merged in 2021-12, with the labels that each got.

#18125 Update third party notices
  ThirdPartyNotices-Distribution.txt
Labels: skip news

#18126 Update third party notices
  ThirdPartyNotices-Distribution.txt
Labels: skip news

#18124 Update main branch version
  package-lock.json
  package.json
Labels: skip news

#18107 Add Pylance telemetry
  src/client/telemetry/pylance.ts
Labels: skip news, skip tests

#18131 Update release plan
  .github/release_plan.md
Labels: skip news

#18127 Fix testing with python 3.10
  .github/actions/smoke-tests/action.yml
  .github/workflows/assign-reviewers.yml
  .github/workflows/build.yml
  .github/workflows/pr-check.yml
  build/test-requirements.txt
  news/requirements.in
  news/requirements.txt
  src/test/tensorBoard/tensorBoardSession.test.ts
Labels: skip news

#18145 Ensure we correctly set python executable after validating interpreters
  src/client/pythonEnvironments/base/info/environmentInfoService.ts
  src/client/pythonEnvironments/exec.ts
  src/test/pythonEnvironments/base/info/environmentInfoService.functional.test.ts
Labels: skip news

#18146 Always change drive letter if a file outside the workspace has been run on Windows
  src/client/terminals/codeExecution/terminalCodeExecution.ts
  src/test/terminals/codeExecution/terminalCodeExec.unit.test.ts
Labels: skip news

#18137 update release version
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip news

#18151 Skip watcher tests on Linux
  src/test/pythonEnvironments/base/locators/lowLevel/watcherTestUtils.ts
Labels: skip news, skip tests

#18102 remove expensive filewatcher for tensorboard
  src/client/tensorBoard/tensorBoardFileWatcher.ts
  src/test/tensorBoard/tensorBoardFileWatcher.test.ts
Labels: skip news

#18154 Do not add 'classify' label if needs-* label present
  .github/workflows/issue-labels.yml
Labels: skip news

#18158 Do not add 'classify' label if needs-* label present
  .github/workflows/issue-labels.yml
Labels: skip news

#18160 Do not add 'classify' label if needs-* label present
  .github/workflows/issue-labels.yml
Labels: skip news

#18161 Do not add 'classify' label if needs-* label present (Attempt #4)
  .github/workflows/issue-labels.yml
Labels: skip news

#18163 Log as error when we fail to validate an interpreter
  src/client/pythonEnvironments/base/info/environmentInfoService.ts
Labels: skip news, skip tests

#18166 Fix linting in src/client/linters & src/test/linters
  .eslintignore
  src/client/linters/baseLinter.ts
  src/client/linters/errorHandlers/baseErrorHandler.ts
  src/client/linters/errorHandlers/errorHandler.ts
  src/client/linters/errorHandlers/notInstalled.ts
  src/client/linters/errorHandlers/standard.ts
  src/client/linters/linterCommands.ts
  src/client/linters/linterInfo.ts
  src/client/linters/linterManager.ts
  src/client/linters/lintingEngine.ts
  src/client/linters/prospector.ts
  src/client/linters/pydocstyle.ts
  src/client/linters/pylint.ts
  src/client/linters/serviceRegistry.ts
  src/client/linters/types.ts
  src/test/linters/common.ts
  src/test/linters/lint.test.ts
  src/test/linters/lint.unit.test.ts
  src/test/linters/lintengine.test.ts
  src/test/linters/linterCommands.unit.test.ts
  src/test/linters/pylint.unit.test.ts
Labels: skip news

#18168 Replace deprecated assert.*equal calls with strict versions
  src/test/api.functional.test.ts
  src/test/application/diagnostics/applicationDiagnostics.unit.test.ts
  src/test/common.ts
  src/test/common/configSettings.test.ts
  src/test/common/experiments/telemetry.unit.test.ts
  src/test/common/helpers.test.ts
  src/test/common/insidersBuild/downloadChannelRules.unit.test.ts
  src/test/common/insidersBuild/insidersExtensionService.unit.test.ts
  src/test/common/installer/condaInstaller.unit.test.ts
  src/test/common/installer/poetryInstaller.unit.test.ts
  src/test/common/net/fileDownloader.unit.test.ts
  src/test/common/process/pythonExecutionFactory.unit.test.ts
  src/test/common/socketStream.test.ts
  src/test/common/terminals/activator/index.unit.test.ts
  src/test/common/terminals/environmentActivationProviders/pipEnvActivationProvider.unit.test.ts
  src/test/common/utils/async.unit.test.ts
  src/test/common/utils/cacheUtils.unit.test.ts
  src/test/common/utils/localize.functional.test.ts
  src/test/common/utils/version.unit.test.ts
  src/test/common/variables/environmentVariablesProvider.unit.test.ts
  src/test/debugger/extension/attachQuickPick/factory.unit.test.ts
  src/test/debugger/extension/configuration/launch.json/completionProvider.unit.test.ts
  src/test/debugger/extension/configuration/launch.json/updaterServer.unit.test.ts
  src/test/format/extension.sort.test.ts
  src/test/format/format.helper.test.ts
  src/test/format/formatter.unit.test.ts
  src/test/install/channelManager.channels.test.ts
  src/test/install/channelManager.messages.test.ts
  src/test/interpreters/virtualEnvs/condaInheritEnvPrompt.unit.test.ts
  src/test/language/characterStream.unit.test.ts
  src/test/language/textIterator.unit.test.ts
  src/test/language/textRange.unit.test.ts
  src/test/language/textRangeCollection.unit.test.ts
  src/test/language/tokenizer.unit.test.ts
  src/test/linters/lint.functional.test.ts
  src/test/linters/lint.multilinter.test.ts
  src/test/linters/lint.multiroot.test.ts
  src/test/linters/lint.unit.test.ts
  src/test/linters/linterManager.unit.test.ts
  src/test/pythonEnvironments/base/info/env.unit.test.ts
  src/test/pythonEnvironments/base/info/envKind.unit.test.ts
  src/test/pythonEnvironments/base/info/pythonVersion.unit.test.ts
  src/test/pythonEnvironments/base/locators/lowLevel/fsWatchingLocator.unit.test.ts
  src/test/pythonEnvironments/base/locators/lowLevel/watcherTestUtils.ts
  src/test/pythonEnvironments/base/watcher.unit.test.ts
  src/test/pythonEnvironments/common/environmentIdentifier.unit.test.ts
  src/test/pythonEnvironments/common/environmentManagers/pipenv.functional.test.ts
  src/test/pythonEnvironments/common/environmentManagers/pipenv.unit.test.ts
  src/test/pythonEnvironments/discovery/locators/condaService.unit.test.ts
Labels: skip news

#18149 Upgrade to Node 14
  .github/workflows/build.yml
  .github/workflows/pr-check.yml
  .nvmrc
  news/3 Code Health/18148.md
  package-lock.json
  package.json
  src/client/common/platform/fileSystem.ts
Labels: skip tests

#18169 More .eslintignore cleanup
  .eslintignore
  src/client/language/characterStream.ts
  src/client/language/characters.ts
  src/client/language/iterableTextRange.ts
  src/client/language/languageConfiguration.ts
  src/client/language/textIterator.ts
  src/client/language/textRangeCollection.ts
  src/client/language/tokenizer.ts
  src/client/language/types.ts
  src/client/language/unicode.ts
  src/client/providers/codeActionProvider/launchJsonCodeActionProvider.ts
  src/client/providers/codeActionProvider/main.ts
  src/client/providers/codeActionProvider/pythonCodeActionProvider.ts
  src/client/providers/formatProvider.ts
  src/client/providers/importSortProvider.ts
  src/client/providers/linterProvider.ts
  src/client/providers/replProvider.ts
  src/client/providers/serviceRegistry.ts
  src/client/providers/terminalProvider.ts
  src/test/language/characterStream.unit.test.ts
  src/test/language/languageConfiguration.unit.test.ts
  src/test/language/textIterator.unit.test.ts
  src/test/language/textRange.unit.test.ts
  src/test/language/textRangeCollection.unit.test.ts
  src/test/language/tokenizer.unit.test.ts
  src/test/providers/codeActionProvider/main.unit.test.ts
  src/test/providers/importSortProvider.unit.test.ts
  src/test/providers/repl.unit.test.ts
  src/test/providers/shebangCodeLenseProvider.unit.test.ts
  src/test/providers/terminal.unit.test.ts
Labels: skip news

#18172 Simplify label check
  .github/workflows/issue-labels.yml
Labels: skip news

#18176 Handle scenarios where validating interpreters via `conda run` emits more than just the validation script output
  pythonFiles/interpreterInfo.py
  src/client/common/process/internal/scripts/index.ts
  src/client/pythonEnvironments/base/info/interpreter.ts
  src/client/pythonEnvironments/info/interpreter.ts
  src/test/common/process/pythonEnvironment.unit.test.ts
  src/test/pythonEnvironments/base/info/environmentInfoService.functional.test.ts
  src/test/pythonEnvironments/base/locators/composite/envsResolver.unit.test.ts
  src/test/pythonEnvironments/info/interpreter.unit.test.ts
Labels: skip news

#18190 Increase timeout for validating conda envs
  src/client/pythonEnvironments/base/info/environmentInfoService.ts
  src/client/pythonEnvironments/base/info/interpreter.ts
  src/client/pythonEnvironments/common/environmentManagers/conda.ts
Labels: skip news, skip tests

#18191 Ensure commands run by extension are logged regardless of logging level
  src/client/common/process/logger.ts
Labels: skip news, skip tests

#18197 No longer test against Pylint for Python 2.7
  build/test-requirements.txt
Labels: skip news

#18186 Add in missing telemetry
  src/client/telemetry/index.ts
  src/client/telemetry/pylance.ts
Labels: skip news, skip tests

#18181 Intercept `conda run` output to filter out stdout from the script which is run
  pythonFiles/conda_run_script.py
  pythonFiles/interpreterInfo.py
  src/client/common/process/internal/scripts/index.ts
  src/client/common/process/rawProcessApis.ts
  src/client/pythonEnvironments/base/info/environmentInfoService.ts
  src/client/pythonEnvironments/common/environmentManagers/conda.ts
  src/test/common/process/proc.exec.test.ts
  src/test/common/process/proc.observable.test.ts
  src/test/common/process/pythonEnvironment.unit.test.ts
  src/test/pythonEnvironments/base/info/environmentInfoService.functional.test.ts
  src/test/pythonEnvironments/base/locators/composite/envsResolver.unit.test.ts
  src/test/pythonEnvironments/info/interpreter.unit.test.ts
Labels: skip news

#18195 Use `conda run` to validate conda interpreters only if attempt to validate it normally fails
  src/client/common/process/proc.ts
  src/client/pythonEnvironments/base/info/environmentInfoService.ts
  src/client/pythonEnvironments/common/environmentManagers/conda.ts
  src/test/pythonEnvironments/base/info/environmentInfoService.functional.test.ts
  src/test/pythonEnvironments/common/environmentManagers/conda.unit.test.ts
Labels: skip news, skip tests

#18210 Improve conda/poetry related verbose logging
  src/client/pythonEnvironments/common/environmentManagers/conda.ts
  src/client/pythonEnvironments/common/environmentManagers/poetry.ts
Labels: skip news, skip tests

#18211 Fixe language server middleware telemetry handler
  news/2 Fixes/18188.md
  src/client/activation/languageClientMiddlewareBase.ts
Labels: skip tests

#18212 Set a timeout on running poetry CLI commands
  src/client/pythonEnvironments/base/info/environmentInfoService.ts
  src/client/pythonEnvironments/common/environmentManagers/conda.ts
  src/client/pythonEnvironments/common/environmentManagers/poetry.ts
Labels: skip news, skip tests
