Repository microsoft/vscode-python, pull requests merged in 2022-06, with the labels that each got.

#19217 Update version and change log.
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip news

#19216 Made suggested changes from LSP
  src/client/activation/jedi/languageServerProxy.ts
  src/client/activation/node/languageServerProxy.ts
Labels: skip news, skip tests

#19229 Add `skip news` label for all python dependencies except isort and jedi-language-server
  .github/dependabot.yml
Labels: skip news, skip tests

#19235 Fix tests for pylint 2.14.0
  src/test/pythonFiles/linting/pylintconfig/.pylintrc
Labels: area-linting, debt, skip news

#19224 Fix validation in remote attach
  src/client/debugger/extension/configuration/providers/remoteAttach.ts
Labels: skip news, skip tests

#19245 Remove `python.disableInstallationCheck` setting
  package.json
  resources/report_issue_user_settings.json
  src/client/application/diagnostics/checks/macPythonInterpreter.ts
  src/client/application/diagnostics/checks/pythonInterpreter.ts
  src/client/common/configSettings.ts
  src/client/common/process/internal/python.ts
  src/client/common/types.ts
  src/test/application/diagnostics/checks/macPythonInterpreter.unit.test.ts
  src/test/application/diagnostics/checks/pythonInterpreter.unit.test.ts
  src/test/common/configSettings/configSettings.unit.test.ts
Labels: skip news, skip package*.json

#19247 Do not use `--user` flag when installing in a virtual environment
  news/2 Fixes/14327.md
  src/client/common/installer/moduleInstaller.ts
Labels: skip tests

#19248 Re-enable tests skipped during LSP update.
  src/test/debuggerTest.ts
  src/test/multiRootTest.ts
  src/test/standardTest.ts
  src/test/tensorBoard/nbextensionCodeLensProvider.insiders.test.ts
Labels: skip news

#19244 Fix regex expression in env file
  src/client/common/variables/environment.ts
  src/test/common/variables/envVarsService.unit.test.ts
Labels: skip news

#19252 Add warning icon next to problematic conda envs without an interpreter
  src/client/common/constants.ts
  src/client/interpreter/configuration/interpreterSelector/commands/setInterpreter.ts
Labels: skip news, skip tests

#19251 Remove unused interpreterPathService.onDidChange notification
  src/client/activation/jedi/languageServerProxy.ts
  src/client/languageServer/jediLSExtensionManager.ts
Labels: skip news, skip tests

#19259 Release candidate
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
  ThirdPartyNotices-Repository.txt
  news/1 Enhancements/14851.md
  news/1 Enhancements/18286.md
  news/1 Enhancements/18650.md
  news/1 Enhancements/18934.md
  news/1 Enhancements/19067.md
  news/1 Enhancements/19102.md
  news/1 Enhancements/19103.md
  news/1 Enhancements/19114.md
  news/1 Enhancements/19139.md
  news/2 Fixes/14327.md
  news/2 Fixes/18989.md
  news/2 Fixes/19079.md
  news/3 Code Health/19077.md
  package-lock.json
  package.json
Labels: skip news

#19254 Add back onTelemetry handler for desktop
  src/client/activation/node/languageServerProxy.ts
Labels: skip news, skip tests

#19262 Update main version.
  package-lock.json
  package.json
Labels: skip news

#19264 Update version for release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip news

#19266 Log server startup message when returning early
  src/client/languageServer/watcher.ts
Labels: skip news, skip tests

#19267 Remove unused telemetry
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
Labels: skip news, skip tests

#19268 Cleanup environment discovery types
  src/client/pythonEnvironments/base/info/envKind.ts
  src/client/pythonEnvironments/base/info/index.ts
  src/client/pythonEnvironments/base/locators/composite/envsReducer.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/pythonEnvironments/base/info/envKind.unit.test.ts
  src/test/pythonEnvironments/base/locatorUtils.unit.test.ts
Labels: skip news, skip tests

#19274 Update requirements for assign-reviewers
  .github/assign-reviewers/dev-requirements.in
  .github/assign-reviewers/dev-requirements.txt
  .github/assign-reviewers/requirements.txt
Labels: skip news

#19273 Update CI for using GItHub Actions for release notes
  .github/workflows/pr-file-check.yml
  .github/workflows/pr-labels.yml
Labels: debt

#19260 Upgrade LSP to 8.0.2-next.5
  package-lock.json
  package.json
  src/client/activation/jedi/languageServerProxy.ts
  src/client/activation/node/languageServerProxy.ts
  src/client/browser/extension.ts
Labels: skip news, skip tests

#19296 Ensure pytest stub calls check for unique calls rather than adjusting the calls by version.
  pythonFiles/tests/testing_tools/adapter/pytest/test_discovery.py
Labels: skip news

#19306 Set explicit python version for CI
  .github/workflows/assign-reviewers.yml
  .github/workflows/build.yml
Labels: skip news

#19307 Ensure the python version is a string.
  .github/workflows/build.yml
Labels: skip news

#19288 Add `breakpoint` support for `django-html` & `django-txt`
  package.json
Labels: feature-request, skip package*.json

#19305 Add missing translations
  package.json
  package.nls.json
  src/client/application/diagnostics/checks/envPathVariable.ts
  src/client/application/diagnostics/checks/invalidPythonPathInDebugger.ts
  src/client/application/diagnostics/checks/macPythonInterpreter.ts
  src/client/application/diagnostics/checks/powerShellActivation.ts
  src/client/application/diagnostics/checks/pythonInterpreter.ts
  src/client/common/utils/localize.ts
  src/client/debugger/extension/adapter/factory.ts
  src/client/debugger/extension/banner.ts
  src/client/debugger/extension/hooks/childProcessAttachService.ts
  src/client/formatters/blackFormatter.ts
  src/client/interpreter/configuration/pythonPathUpdaterService.ts
  src/client/linters/errorHandlers/standard.ts
  src/client/providers/importSortProvider.ts
  src/client/terminals/codeExecution/helper.ts
  src/client/testing/common/debugLauncher.ts
  src/test/debugger/extension/banner.unit.test.ts
Labels: debt, skip package*.json

#19308 Delete the `news` directory
  .github/release_plan.md
  .vscodeignore
  news/.vscode/settings.json
  news/1 Enhancements/README.md
  news/2 Fixes/README.md
  news/3 Code Health/README.md
  news/README.md
  news/__main__.py
  news/announce.py
  news/requirements.in
  news/requirements.txt
  news/test_announce.py
Labels: debt

#19313 Fix variable name for flake8Path's description
  package.json
Labels: bug, skip package*.json

#19319 Fix interpreter discovery related telemetry
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
Labels: debt, skip tests

#19341 Ensure we dispose objects on deactivate.
  src/client/activation/common/outputChannel.ts
  src/client/common/application/commands/createFileCommand.ts
  src/client/common/asyncDisposableRegistry.ts
  src/client/common/types.ts
  src/client/common/utils/resourceLifecycle.ts
  src/client/extension.ts
  src/client/extensionInit.ts
  src/client/interpreter/autoSelection/proxy.ts
  src/client/languageServer/watcher.ts
  src/test/activation/outputChannel.unit.test.ts
  src/test/common/application/commands/createNewFileCommand.unit.test.ts
  src/test/languageServer/watcher.unit.test.ts
Labels: bug

#19348 Simplify and merge async dispose and dispose.
  src/client/common/asyncDisposableRegistry.ts
  src/client/common/platform/fileSystemWatcher.ts
  src/client/common/serviceRegistry.ts
  src/client/common/types.ts
  src/client/common/utils/resourceLifecycle.ts
  src/client/extension.ts
  src/client/languageServer/watcher.ts
  src/client/pythonEnvironments/base/locators/common/resourceBasedLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/windowsKnownPathsLocator.ts
  src/client/pythonEnvironments/base/locators/wrappers.ts
  src/client/pythonEnvironments/base/watchers.ts
  src/client/pythonEnvironments/common/pythonBinariesWatcher.ts
  src/client/pythonEnvironments/index.ts
  src/test/common/configuration/service.test.ts
  src/test/common/installer.test.ts
  src/test/common/moduleInstaller.test.ts
  src/test/common/serviceRegistry.unit.test.ts
  src/test/format/extension.sort.test.ts
  src/test/languageServer/watcher.unit.test.ts
  src/test/pythonEnvironments/base/locators/lowLevel/index.unit.test.ts
  src/test/pythonEnvironments/base/locators/lowLevel/watcherTestUtils.ts
Labels: debt

#19353 Ensure we can change interpreters after trusting a workspace
  src/client/common/configSettings.ts
  src/client/common/types.ts
  src/client/extensionActivation.ts
  src/client/interpreter/interpreterService.ts
Labels: bug, skip tests

#19356 Fix for :::: in node id for pytest.
  pythonFiles/testing_tools/adapter/pytest/_pytest_item.py
  pythonFiles/tests/testing_tools/adapter/pytest/test_discovery.py
Labels: bug

#19351 Ensure we register for interpreter change when moving from untrusted to trusted.
  src/client/activation/node/lspNotebooksExperiment.ts
  src/client/extensionActivation.ts
  src/client/extensionInit.ts
  src/client/languageServer/watcher.ts
  src/test/languageServer/watcher.unit.test.ts
Labels: bug

#19361 Trigger refresh when using `Select Interpreter` command if no envs were found previously
  src/client/pythonEnvironments/base/locator.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
Labels: feature-request, skip tests

#19388 Update the issue notebook
  sprint-planning.github-issues
Labels: debt
