Repository microsoft/vscode-python, pull requests merged in 2022-09, with the labels that each got.

#19771 Update release version.
  package-lock.json
  package.json
Labels: no-changelog

#19748 Assign data science telemetry to Don
  src/client/telemetry/index.ts
Labels: debt, skip tests

#19786 Merge back release to main.
  package-lock.json
  package.json
Labels: no-changelog

#19795 Add comment for call-tas-error telemetry event
  src/client/telemetry/index.ts
Labels: no-changelog, area-internal, skip tests

#19806 Ensure full refresh icon removes any environment which isn't relevant and remove hard refresh icon in quickpick
  src/client/apiTypes.ts
  src/client/common/constants.ts
  src/client/common/utils/localize.ts
  src/client/interpreter/configuration/interpreterSelector/commands/setInterpreter.ts
  src/client/interpreter/interpreterService.ts
  src/client/proposedApi.ts
  src/client/pythonEnvironments/base/locator.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionCache.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/test/configuration/interpreterSelector/commands/setInterpreter.unit.test.ts
  src/test/pythonEnvironments/base/locators/composite/envsCollectionService.unit.test.ts
Labels: bug

#19819 Revert to using `conda activate` for fetching activated environment variables
  src/client/interpreter/activation/service.ts
  src/test/interpreters/activation/service.unit.test.ts
Labels: feature-request

#19828 Ensure interpreter quickpick is initialized synchronously
  src/client/common/utils/multiStepInput.ts
  src/client/interpreter/configuration/interpreterSelector/commands/setInterpreter.ts
  src/test/configuration/interpreterSelector/commands/setInterpreter.unit.test.ts
Labels: bug

#19827 Ensure we start watching environments when activating discovery component
  src/client/pythonEnvironments/base/locators/common/resourceBasedLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/fsWatchingLocator.ts
  src/client/pythonEnvironments/base/locators/wrappers.ts
Labels: bug, skip tests

#19821 Ensure an environment is only reported after the final type of environment is known
  package.nls.json
  src/client/pythonEnvironments/base/locators/composite/envsResolver.ts
  src/test/pythonEnvironments/base/locators/composite/envsResolver.unit.test.ts
Labels: feature-request

#19836 Simplify buffer decoder.
  src/client/common/process/decoder.ts
  src/client/common/process/proc.ts
  src/client/common/process/processFactory.ts
  src/client/common/process/pythonExecutionFactory.ts
  src/client/common/process/rawProcessApis.ts
  src/client/common/process/serviceRegistry.ts
  src/client/common/process/types.ts
  src/test/common.ts
  src/test/common/process/decoder.test.ts
  src/test/common/process/proc.exec.test.ts
  src/test/common/process/proc.observable.test.ts
  src/test/common/process/processFactory.unit.test.ts
  src/test/common/process/pythonExecutionFactory.unit.test.ts
  src/test/common/process/serviceRegistry.unit.test.ts
  src/test/linters/lint.functional.test.ts
  src/test/serviceRegistry.ts
  src/test/terminals/codeExecution/helper.test.ts
Labels: debt

#19839 Expose interpreter quickpick API with filtering
  src/client/interpreter/configuration/interpreterSelector/commands/setInterpreter.ts
  src/client/interpreter/configuration/types.ts
  src/client/interpreter/serviceRegistry.ts
  src/test/configuration/interpreterSelector/commands/setInterpreter.unit.test.ts
  src/test/interpreters/serviceRegistry.unit.test.ts
Labels: no-changelog

#19853 Remove code lenses for "set as interpreter"
  .eslintignore
  build/existingFiles.json
  src/client/interpreter/configuration/interpreterSelector/commands/setShebangInterpreter.ts
  src/client/interpreter/contracts.ts
  src/client/interpreter/display/shebangCodeLensProvider.ts
  src/client/interpreter/serviceRegistry.ts
  src/test/interpreters/serviceRegistry.unit.test.ts
  src/test/providers/shebangCodeLenseProvider.unit.test.ts
Labels: debt

#19862 Add type info which can be used to differentiate Pyenv global installs from Pyenv virtualenvs
  src/client/pythonEnvironments/base/info/env.ts
  src/client/pythonEnvironments/base/info/index.ts
  src/client/pythonEnvironments/base/locators/composite/resolverUtils.ts
  src/client/pythonEnvironments/common/environmentManagers/simplevirtualenvs.ts
  src/test/pythonEnvironments/base/locators/composite/envsResolver.unit.test.ts
  src/test/pythonEnvironments/base/locators/composite/resolverUtils.unit.test.ts
Labels: no-changelog

#19854 Update property name under GDPR classification
  src/client/telemetry/index.ts
Labels: no-changelog, skip package*.json, skip tests

#19848 Create environment using `venv` or `conda`
  package.json
  package.nls.json
  pythonFiles/create_conda.py
  pythonFiles/create_venv.py
  pythonFiles/tests/test_create_conda.py
  pythonFiles/tests/test_create_venv.py
  src/client/common/constants.ts
  src/client/common/process/internal/scripts/index.ts
  src/client/common/utils/localize.ts
  src/client/common/vscodeApis/commandApis.ts
  src/client/common/vscodeApis/windowApis.ts
  src/client/common/vscodeApis/workspaceApis.ts
  src/client/extension.ts
  src/client/extensionActivation.ts
  src/client/pythonEnvironments/base/locators/composite/resolverUtils.ts
  src/client/pythonEnvironments/common/externalDependencies.ts
  src/client/pythonEnvironments/creation/common/commonUtils.ts
  src/client/pythonEnvironments/creation/common/workspaceSelection.ts
  src/client/pythonEnvironments/creation/createEnvApi.ts
  src/client/pythonEnvironments/creation/createEnvQuickPick.ts
  src/client/pythonEnvironments/creation/createEnvironment.ts
  src/client/pythonEnvironments/creation/provider/condaCreationProvider.ts
  src/client/pythonEnvironments/creation/provider/condaUtils.ts
  src/client/pythonEnvironments/creation/provider/venvCreationProvider.ts
  src/client/pythonEnvironments/creation/types.ts
  src/test/pythonEnvironments/base/locators/composite/envsResolver.unit.test.ts
  src/test/pythonEnvironments/base/locators/composite/resolverUtils.unit.test.ts
  src/test/pythonEnvironments/creation/common/workspaceSelection.unit.test.ts
  src/test/pythonEnvironments/creation/createEnvQuickPick.unit.test.ts
  src/test/pythonEnvironments/creation/createEnvironment.unit.test.ts
  src/test/pythonEnvironments/creation/provider/condaCreationProvider.unit.test.ts
  src/test/pythonEnvironments/creation/provider/venvCreationProvider.unit.test.ts
Labels: feature-request, skip package*.json

#19877 Watch for new conda environments
  src/client/pythonEnvironments/base/locators/lowLevel/condaLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/fsWatchingLocator.ts
  src/client/pythonEnvironments/common/environmentManagers/conda.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/pythonEnvironments/base/locators/lowLevel/condaLocator.testvirtualenvs.ts
Labels: feature-request

#19882 Add cancellation token support and link to logs.
  src/client/common/utils/localize.ts
  src/client/pythonEnvironments/creation/common/workspaceSelection.ts
  src/client/pythonEnvironments/creation/createEnvironment.ts
  src/client/pythonEnvironments/creation/provider/condaCreationProvider.ts
  src/client/pythonEnvironments/creation/provider/condaUtils.ts
  src/client/pythonEnvironments/creation/provider/venvCreationProvider.ts
  src/test/pythonEnvironments/creation/createEnvironment.unit.test.ts
Labels: bug

#19841 Finalizing design of proposed API for python environments
  .eslintignore
  package-lock.json
  package.json
  src/client/apiTypes.ts
  src/client/common/application/extensions.ts
  src/client/common/types.ts
  src/client/deprecatedProposedApi.ts
  src/client/deprecatedProposedApiTypes.ts
  src/client/extension.ts
  src/client/interpreter/interpreterService.ts
  src/client/proposedApi.ts
  src/client/proposedApiTypes.ts
  src/client/pythonEnvironments/api.ts
  src/client/pythonEnvironments/base/locator.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionCache.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/test/interpreters/interpreterService.unit.test.ts
  src/test/proposedApi.unit.test.ts
  src/test/pythonEnvironments/base/locators/composite/envsCollectionService.unit.test.ts
Labels: feature-request

#19887 Rename `EnvironmentId` to `EnvironmentPath`
  src/client/deprecatedProposedApi.ts
  src/client/deprecatedProposedApiTypes.ts
  src/client/proposedApi.ts
  src/client/proposedApiTypes.ts
  src/test/proposedApi.unit.test.ts
Labels: no-changelog

#19895 Remove API telemetry containing extension display name
  src/client/deprecatedProposedApi.ts
  src/client/proposedApi.ts
  src/client/telemetry/index.ts
Labels: no-changelog, skip tests

#19896 Allow to specify title and placeholder in API for interpreter quickpick
  src/client/common/utils/multiStepInput.ts
  src/client/interpreter/configuration/interpreterSelector/commands/setInterpreter.ts
  src/client/interpreter/configuration/types.ts
Labels: no-changelog, skip tests

#19899 Temporarily expose `PYTHONPATH` for Pylance
  src/client/api.ts
  src/test/api.functional.test.ts
Labels: no-changelog, skip tests

#19901 Only log deprecation warning once for each extension
  src/client/deprecatedProposedApi.ts
Labels: no-changelog, skip tests

#19915 Add createEnvironment to activation trigger.
  package.json
Labels: no-changelog, skip package*.json

#19921 Removed ILanguageServer no longer used.
  src/client/activation/jedi/languageServerProxy.ts
  src/client/activation/jedi/manager.ts
  src/client/activation/node/manager.ts
  src/client/activation/serviceRegistry.ts
  src/client/activation/types.ts
  src/client/jupyter/jupyterIntegration.ts
  src/client/languageServer/jediLSExtensionManager.ts
  src/client/languageServer/languageServerCapabilities.ts
  src/client/languageServer/noneLSExtensionManager.ts
  src/client/languageServer/pylanceLSExtensionManager.ts
  src/client/languageServer/types.ts
  src/client/languageServer/watcher.ts
  src/test/activation/node/lspInteractiveWindowMiddlewareAddon.unit.test.ts
  src/test/activation/serviceRegistry.unit.test.ts
  src/test/languageServer/jediLSExtensionManager.unit.test.ts
  src/test/languageServer/languageServerCapabilities.unit.test.ts
  src/test/languageServer/noneLSExtensionManager.unit.test.ts
  src/test/languageServer/pylanceLSExtensionManager.unit.test.ts
Labels: no-changelog, skip package*.json, skip tests
