Repository microsoft/vscode-python, pull requests merged in 2022-01, with the labels that each got.

#18238 Remove PyTorch experiments
  news/3 Code Health/18074.md
  package.json
  src/client/common/experiments/groups.ts
  src/client/tensorBoard/nbextensionCodeLensProvider.ts
  src/client/tensorBoard/tensorBoardFileWatcher.ts
  src/client/tensorBoard/tensorBoardImportCodeLensProvider.ts
  src/client/tensorBoard/tensorBoardPrompt.ts
  src/client/tensorBoard/tensorBoardSession.ts
  src/client/tensorBoard/tensorBoardSessionProvider.ts
  src/client/tensorBoard/tensorBoardUsageTracker.ts
  src/test/tensorBoard/helpers.ts
  src/test/tensorBoard/nbextensionCodeLensProvider.unit.test.ts
  src/test/tensorBoard/tensorBoardImportCodeLensProvider.unit.test.ts
  src/test/tensorBoard/tensorBoardPrompt.unit.test.ts
  src/test/tensorBoard/tensorBoardSession.test.ts
  src/test/tensorBoard/tensorBoardUsageTracker.unit.test.ts
Labels: skip package*.json

#18243 Switch from jedils_requirements.txt to requirements.txt
  .github/actions/build-vsix/action.yml
  .github/workflows/build.yml
  .github/workflows/pr-check.yml
  .vscodeignore
  gulpfile.js
  news/3 Code Health/18185.md
  pythonFiles/jedilsp_requirements/requirements.in
  pythonFiles/jedilsp_requirements/requirements.txt
  src/client/activation/jedi/manager.ts
Labels: skip tests

#18213 Remove `python.pythonPath` experiment
  data/.vscode/settings.json
  news/3 Code Health/17977.md
  package.json
  src/client/activation/activationManager.ts
  src/client/activation/jedi/languageServerProxy.ts
  src/client/activation/node/languageServerProxy.ts
  src/client/application/diagnostics/checks/macPythonInterpreter.ts
  src/client/application/diagnostics/checks/pythonPathDeprecated.ts
  src/client/application/diagnostics/checks/upgradeCodeRunner.ts
  src/client/common/configSettings.ts
  src/client/common/configuration/service.ts
  src/client/common/experiments/groups.ts
  src/client/common/interpreterPathProxyService.ts
  src/client/common/interpreterPathService.ts
  src/client/common/persistentState.ts
  src/client/common/process/pythonExecutionFactory.ts
  src/client/common/serviceRegistry.ts
  src/client/common/types.ts
  src/client/interpreter/configuration/pythonPathUpdaterServiceFactory.ts
  src/client/interpreter/configuration/services/globalUpdaterService.ts
  src/client/interpreter/configuration/services/workspaceFolderUpdaterService.ts
  src/client/interpreter/configuration/services/workspaceUpdaterService.ts
  src/client/interpreter/interpreterService.ts
  src/client/startupTelemetry.ts
  src/test/activation/activationManager.unit.test.ts
  src/test/application/diagnostics/checks/macPythonInterpreter.unit.test.ts
  src/test/application/diagnostics/checks/pythonPathDeprecated.unit.test.ts
  src/test/application/diagnostics/checks/upgradeCodeRunner.unit.test.ts
  src/test/common.ts
  src/test/common/configSettings.test.ts
  src/test/common/configSettings/configSettings.pythonPath.unit.test.ts
  src/test/common/configSettings/configSettings.unit.test.ts
  src/test/common/configuration/service.test.ts
  src/test/common/configuration/service.unit.test.ts
  src/test/common/installer.test.ts
  src/test/common/interpreterPathProxyService.unit.test.ts
  src/test/common/interpreterPathService.unit.test.ts
  src/test/common/moduleInstaller.test.ts
  src/test/common/process/proc.exec.test.ts
  src/test/common/process/proc.observable.test.ts
  src/test/common/process/pythonExecutionFactory.unit.test.ts
  src/test/common/process/pythonProc.simple.multiroot.test.ts
  src/test/common/terminals/environmentActivationProviders/terminalActivation.testvirtualenvs.ts
  src/test/extensionSettings.ts
  src/test/format/format.helper.test.ts
  src/test/interpreters/interpreterService.unit.test.ts
  src/test/interpreters/pythonPathUpdaterFactory.unit.test.ts
  src/test/linters/lint.functional.test.ts
  src/test/startupTelemetry.unit.test.ts
Labels: skip package*.json

#18249 Cleanup PythonPath related objects
  src/client/common/experiments/groups.ts
  src/client/interpreter/configuration/pythonPathUpdaterService.ts
  src/test/interpreters/pythonPathUpdaterFactory.unit.test.ts
  src/test/mocks/mockWorkspaceConfig.ts
Labels: skip news, skip tests

#18251 Do not special case python.pythonPath setting in config service
  src/client/common/configuration/service.ts
  src/test/common/configuration/service.unit.test.ts
Labels: skip news, skip tests

#18266 Ensure we fire an event correctly when interpreter information changes
  news/2 Fixes/18257.md
  src/client/interpreter/interpreterService.ts
Labels: skip tests

#18268 Run Pyright for all workflows
  .github/workflows/build.yml
  .github/workflows/pr-check.yml
  pythonFiles/normalizeSelection.py
  pythonFiles/pyproject.toml
Labels: skip news

#18269 Migrate over to using `enabledApiProposals` in `package.json`
  package-lock.json
  package.json
  src/client/activation/node/activator.ts
  src/client/common/application/debugService.ts
  src/client/common/application/documentManager.ts
  src/client/common/application/notebook.ts
  src/client/common/application/types.ts
  src/client/common/serviceRegistry.ts
  src/client/testing/testController/common/types.ts
  src/client/testing/testController/unittest/runner.ts
  src/test/common/terminals/activation.unit.test.ts
  src/test/insiders/languageServer.insiders.test.ts
  src/test/mockClasses.ts
  src/test/mocks/mementos.ts
  src/test/mocks/mockDocumentManager.ts
  src/test/mocks/vsc/extHostedTypes.ts
  src/test/terminals/activation.unit.test.ts
  tsconfig.browser.json
  types/vscode-proposed/index.d.ts
  types/vscode.proposed.d.ts
  types/vscode.proposed.languageStatus.d.ts
  types/vscode.proposed.notebookEditor.d.ts
  types/vscode.proposed.quickPickSeparators.d.ts
  types/vscode.proposed.quickPickSortByLabel.d.ts
  types/vscode.proposed.testObserver.d.ts
Labels: skip news, skip tests

#18224 Update vscode-extension-telemetry
  package-lock.json
  package.json
Labels: skip news

#18274 Use Python 3.7 to generate the requirements files
  requirements.txt
Labels: skip news

#18152 Add experiments to move interpreter display status bar item to the right
  news/1 Enhancements/18282.md
  news/1 Enhancements/18283.md
  src/client/common/application/applicationShell.ts
  src/client/common/application/types.ts
  src/client/common/experiments/groups.ts
  src/client/interpreter/display/index.ts
  src/client/interpreter/interpreterService.ts
  src/client/interpreter/serviceRegistry.ts
  src/test/interpreters/display.unit.test.ts
  src/test/interpreters/interpreterService.unit.test.ts
  src/test/mocks/vsc/index.ts
  src/test/vscode-mock.ts
Labels: skip news

#18290 Removing restriction when using purpose
  news/2 Fixes/18248.md
  src/client/debugger/extension/configuration/debugConfigurationService.ts
Labels: skip tests

#17747 Test envVarsService newline substitution behavior
  news/3 Code Health/17747.md
  src/test/common/variables/envVarsService.unit.test.ts
Labels: investigating

#18308 Do not block updates from reducer on the resolver
  src/client/pythonEnvironments/base/locators/composite/envsResolver.ts
Labels: skip news, skip tests

#18289 Add step to create Python file and modify svg for interpreter selection
  package.json
  resources/walkthrough/python-interpreter-v2.svg
Labels: skip news, skip package*.json

#18316 Provide options support for refreshInterpreters API.
  src/client/apiTypes.ts
  src/client/proposedApi.ts
  src/client/pythonEnvironments/base/locator.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionCache.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/test/pythonEnvironments/base/locators/composite/envsCollectionService.unit.test.ts
Labels: skip news

#18321 Getting started walkthrough for data scientists
  package.json
Labels: skip news, skip package*.json

#18304 Remove experimental tag from formatting.provider setting
  package.json
Labels: skip news, skip package*.json

#18352 Update VS Code engine to 1.63.1
  package.json
Labels: skip news, skip package*.json

#18338 Tests failing on main
  .eslintignore
  src/test/common/process/pythonProc.simple.multiroot.test.ts
  src/test/linters/lint.multiroot.test.ts
Labels: skip news

#18325 Update packages
  news/1 Enhancements/18325.md
  package-lock.json
  pythonFiles/jedilsp_requirements/requirements.txt
Labels: skip package*.json

#18331 Use `pip-secure-install` action
  .github/actions/build-vsix/action.yml
  .github/actions/smoke-tests/action.yml
  .github/workflows/assign-reviewers.yml
  .github/workflows/build.yml
  .github/workflows/pr-check.yml
Labels: skip news

#18345 Fixed namespace and type errors, changed null to undefined where applicable
  news/3 Code Health/18345.md
  src/client/browser/extension.ts
  src/client/browser/intellisenseStatus.ts
  src/client/extension.ts
  src/client/interpreter/helpers.ts
  src/client/interpreter/interpreterService.ts
  typings/index.d.ts
Labels: skip tests

#18380 Update README.md
  .github/assign-reviewers/requirements.txt
  .github/workflows/assign-reviewers.yml
  README.md
Labels: skip news

#18384 Remove `quickPickSeparators` API proposal from package.json
  package.json
Labels: skip news, skip package*.json, skip tests

#18387 Remove open interactive window to side from walkthrough
  package.json
Labels: skip news, skip package*.json

#18383 Remove items from array in reverse order
  news/2 Fixes/18382.md
  src/client/pythonEnvironments/base/locators/composite/envsCollectionCache.ts
Labels: skip tests

#18392 Add interpreter status bar experiments in `package.json`
  package.json
Labels: skip news, skip package*.json, skip tests

#18136 Update python execution factory using `conda.ts`
  src/client/common/process/pythonEnvironment.ts
  src/client/common/process/pythonExecutionFactory.ts
  src/client/common/process/pythonProcess.ts
  src/client/common/process/types.ts
  src/test/common/process/pythonEnvironment.unit.test.ts
  src/test/common/process/pythonExecutionFactory.unit.test.ts
  src/test/linters/lint.functional.test.ts
  src/test/terminals/codeExecution/djangoShellCodeExect.unit.test.ts
  src/test/terminals/codeExecution/terminalCodeExec.unit.test.ts
Labels: skip news

#18391 Re-enable tests
  src/test/common/process/pythonProc.simple.multiroot.test.ts
Labels: skip news

#18400 Fix test line endings
  src/test/common/process/pythonProc.simple.multiroot.test.ts
Labels: skip news

#18399 Fix debugger with conda-run
  package-lock.json
  src/client/debugger/extension/adapter/factory.ts
  src/test/debugger/extension/adapter/factory.unit.test.ts
Labels: skip news, skip package*.json

#18401 Release candidate
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
  cgmanifest.json
  news/1 Enhancements/17693.md
  news/1 Enhancements/17905.md
  news/1 Enhancements/17944.md
  news/1 Enhancements/18068.md
  news/1 Enhancements/18282.md
  news/1 Enhancements/18283.md
  news/1 Enhancements/18325.md
  news/1 Enhancements/7696.md
  news/2 Fixes/17991.md
  news/2 Fixes/18128.md
  news/2 Fixes/18188.md
  news/2 Fixes/18207.md
  news/2 Fixes/18234.md
  news/2 Fixes/18248.md
  news/2 Fixes/18257.md
  news/2 Fixes/18258.md
  news/2 Fixes/18259.md
  news/2 Fixes/18285.md
  news/2 Fixes/18364.md
  news/2 Fixes/18382.md
  news/2 Fixes/18393.md
  news/3 Code Health/17747.md
  news/3 Code Health/17977.md
  news/3 Code Health/18074.md
  news/3 Code Health/18132.md
  news/3 Code Health/18148.md
  news/3 Code Health/18185.md
  news/3 Code Health/18235.md
  news/3 Code Health/18345.md
  news/announce.py
  package-lock.json
  package.json
Labels: skip news

#18402 Update main branch version
  package-lock.json
  package.json
Labels: skip news
