Repository microsoft/vscode-python, pull requests merged in 2022-02, with the labels that each got.

#18406 Fix terminal activation tests
  src/test/common/terminals/environmentActivationProviders/terminalActivation.testvirtualenvs.ts
Labels: skip news, skip tests

#18410 Use python instead of python3 in gulp tasks
  gulpfile.js
Labels: skip news

#18412 Fix conda run output marker script
  pythonFiles/get_output_via_markers.py
  src/client/common/process/rawProcessApis.ts
Labels: skip news, skip tests

#18413 Cherry pick fix for conda run output marker script into release
  pythonFiles/get_output_via_markers.py
  src/client/common/process/rawProcessApis.ts
Labels: skip news, skip tests

#18417 Fix the interpreter selected by 'new venv' prompt
  src/client/pythonEnvironments/legacyIOC.ts
Labels: skip news, skip tests

#18418 Fix marker script support for `-c` flag
  pythonFiles/get_output_via_markers.py
Labels: skip news, skip tests

#18421 Update version and changelog for release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip news

#18420 Update to vsce 2.6.6
  news/3 Code Health/18411.md
  package-lock.json
  package.json
Labels: skip news

#18422 Fix `trigger` prop for debug_session.* events
  src/client/common/application/debugSessionTelemetry.ts
Labels: skip news, skip tests

#18423 Remove linter install prompt telemetry
  src/client/common/installer/productInstaller.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
Labels: skip news, skip tests

#18424 Remove UpgradeCodeRunnerDiagnostic
  .eslintignore
  package.nls.json
  package.nls.zh-cn.json
  package.nls.zh-tw.json
  src/client/application/diagnostics/checks/upgradeCodeRunner.ts
  src/client/application/diagnostics/constants.ts
  src/client/application/diagnostics/serviceRegistry.ts
  src/client/common/constants.ts
  src/client/common/utils/localize.ts
  src/test/application/diagnostics/checks/upgradeCodeRunner.unit.test.ts
  src/test/application/diagnostics/serviceRegistry.unit.test.ts
Labels: skip news

#18430 Do not resolve interpreter path when setting active interpreter
  src/client/interpreter/interpreterService.ts
Labels: skip news, skip tests

#18440 Resolve interpreter paths like `python`, `python3` etc. when setting active interpreter
  src/client/interpreter/interpreterService.ts
Labels: skip news, skip tests

#18441 Add support for base interpreter paths
  src/client/common/process/pythonEnvironment.ts
  src/client/pythonEnvironments/info/executable.ts
  src/test/common/process/pythonEnvironment.unit.test.ts
  src/test/pythonEnvironments/info/executable.unit.test.ts
Labels: skip news

#18442 Improve Python execution factory `getExecutable()`
  src/client/common/process/pythonEnvironment.ts
  src/client/common/process/types.ts
  src/client/pythonEnvironments/info/executable.ts
  src/client/pythonEnvironments/info/interpreter.ts
  src/test/pythonEnvironments/info/executable.unit.test.ts
  src/test/pythonEnvironments/info/interpreter.unit.test.ts
Labels: skip news

#18446 CI failures: Pin prospector to 1.6.0, pytest to < 7.0.0, and fix linting issues with flake8 3.9.2
  build/test-requirements.txt
  src/test/pythonFiles/linting/flake8config/file.py
Labels: skip news, skip tests

#18449 Fix multiroot workspace CI failures on main
  src/testMultiRootWkspc/workspace1/file.py
  src/testMultiRootWkspc/workspace2/file.py
  src/testMultiRootWkspc/workspace2/workspace2File.py
  src/testMultiRootWkspc/workspace3/file.py
Labels: skip news

#18451 Use older way of launching debugger when using conda less than 4.9.0
  news/2 Fixes/18436.md
  src/client/debugger/extension/adapter/factory.ts
  src/client/pythonEnvironments/common/environmentManagers/conda.ts
Labels: skip tests

#18481 Fix `invalid patch string` error when using conda
  news/2 Fixes/18455.md
  src/client/common/process/rawProcessApis.ts
  src/client/pythonEnvironments/common/environmentManagers/conda.ts
  src/test/common/process/pythonEnvironment.unit.test.ts
  src/test/pythonEnvironments/common/environmentManagers/conda.unit.test.ts
Labels: skip tests

#18470 Update release version and change log for point release
  CHANGELOG.md
  news/2 Fixes/18436.md
  package-lock.json
  package.json
  src/client/common/process/rawProcessApis.ts
  src/client/pythonEnvironments/common/environmentManagers/conda.ts
  src/test/common/process/pythonEnvironment.unit.test.ts
  src/test/pythonEnvironments/common/environmentManagers/conda.unit.test.ts
Labels: skip news

#18218 Update package.nls.es.json
  package.nls.es.json
Labels: skip news

#18471 Explicitly add `"justMyCode": "true"` to all `launch.json` configurations
  news/2 Fixes/18471.md
  package.json
  src/client/debugger/extension/configuration/providers/djangoLaunch.ts
  src/client/debugger/extension/configuration/providers/fastapiLaunch.ts
  src/client/debugger/extension/configuration/providers/fileLaunch.ts
  src/client/debugger/extension/configuration/providers/flaskLaunch.ts
  src/client/debugger/extension/configuration/providers/moduleLaunch.ts
  src/client/debugger/extension/configuration/providers/pidAttach.ts
  src/client/debugger/extension/configuration/providers/pyramidLaunch.ts
  src/client/debugger/extension/configuration/providers/remoteAttach.ts
  src/test/debugger/extension/configuration/providers/djangoLaunch.unit.test.ts
  src/test/debugger/extension/configuration/providers/fastapiLaunch.unit.test.ts
  src/test/debugger/extension/configuration/providers/fileLaunch.unit.test.ts
  src/test/debugger/extension/configuration/providers/flaskLaunch.unit.test.ts
  src/test/debugger/extension/configuration/providers/moduleLaunch.unit.test.ts
  src/test/debugger/extension/configuration/providers/pidAttach.unit.test.ts
  src/test/debugger/extension/configuration/providers/pyramidLaunch.unit.test.ts
  src/test/debugger/extension/configuration/providers/remoteAttach.unit.test.ts
Labels: skip package*.json

#18487 Fix pip-requirements filename patterns
  news/1 Enhancements/18498.md
  package.json
Labels: skip package*.json

#18549 Fix unit tests related to terminal code execution
  src/test/terminals/codeExecution/djangoShellCodeExect.unit.test.ts
  src/test/terminals/codeExecution/terminalCodeExec.unit.test.ts
Labels: skip news

#18522 Create new Python file command
  news/1 Enhancements/18376.md
  package.json
  package.nls.json
  src/client/common/application/applicationShell.ts
  src/client/common/application/commands.ts
  src/client/common/application/commands/createFileCommand.ts
  src/client/common/application/types.ts
  src/client/common/application/workspace.ts
  src/client/common/constants.ts
  src/client/common/serviceRegistry.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/test/common/application/commands/createNewFileCommand.unit.test.ts
Labels: skip package*.json

#18339 Fixed regex for Pylama output
  news/2 Fixes/15609.md
  src/client/linters/pylama.ts
Labels: skip tests

#18565 Fixed regex for Pylama output - comments
  news/2 Fixes/15609.md
  src/client/linters/pylama.ts
Labels: skip tests

#18569 Pin pyright to 1.1.223 in GHA
  .github/workflows/pr-check.yml
Labels: skip news

#18573 Pin pyright in build workflow
  .github/workflows/build.yml
Labels: skip news

#18597 Remove `languageStatus` from `enabledApiProposals`
  package.json
Labels: skip news, skip package*.json

#18598 Fix for a crash when loading environments with no info
  news/2 Fixes/18594.md
  src/client/interpreter/display/index.ts
Labels: skip tests

#18599 Upgrade pyright to 1.1.225
  .github/workflows/build.yml
  .github/workflows/pr-check.yml
  pythonFiles/pyproject.toml
Labels: skip news
