Repository microsoft/vscode-python, pull requests merged in 2022-04, with the labels that each got.

#18858 Do not use conda run when launching a debugger
  news/2 Fixes/18847.md
  src/client/debugger/extension/adapter/factory.ts
Labels: skip tests

#18860 Fixes support for python binaries not following the standard names
  news/2 Fixes/18835.md
  src/client/pythonEnvironments/common/commonUtils.ts
  src/client/pythonEnvironments/common/posixUtils.ts
Labels: skip tests

#18866 Do not validate conda binaries using shell by default
  src/client/common/installer/condaInstaller.ts
  src/client/interpreter/contracts.ts
  src/client/pythonEnvironments/base/info/environmentInfoService.ts
  src/client/pythonEnvironments/common/environmentManagers/conda.ts
  src/client/pythonEnvironments/common/environmentManagers/condaService.ts
  src/test/common/installer/condaInstaller.unit.test.ts
  src/test/common/installer/moduleInstaller.unit.test.ts
  src/test/pythonEnvironments/base/locators/composite/envsResolver.unit.test.ts
  src/test/pythonEnvironments/base/locators/composite/resolverUtils.unit.test.ts
  src/test/pythonEnvironments/common/environmentManagers/conda.unit.test.ts
Labels: skip news

#18870 Ensure string prototypes extension extends are unique enough
  src/client/common/extensions.ts
  src/client/common/installer/condaInstaller.ts
  src/client/common/installer/moduleInstaller.ts
  src/client/common/process/internal/scripts/index.ts
  src/client/common/process/logger.ts
  src/client/common/terminal/environmentActivationProviders/bash.ts
  src/client/common/terminal/environmentActivationProviders/commandPrompt.ts
  src/client/common/terminal/environmentActivationProviders/condaActivationProvider.ts
  src/client/common/terminal/environmentActivationProviders/pipEnvActivationProvider.ts
  src/client/common/terminal/environmentActivationProviders/pyenvActivationProvider.ts
  src/client/common/terminal/helper.ts
  src/client/debugger/extension/adapter/remoteLaunchers.ts
  src/client/interpreter/activation/service.ts
  src/client/pythonEnvironments/base/info/interpreter.ts
  src/client/pythonEnvironments/info/executable.ts
  src/client/terminals/codeExecution/djangoShellCodeExecution.ts
  src/client/terminals/codeExecution/terminalCodeExecution.ts
  src/test/api.functional.test.ts
  src/test/common/extensions.unit.test.ts
  src/test/common/installer/condaInstaller.unit.test.ts
  src/test/common/installer/moduleInstaller.unit.test.ts
  src/test/common/terminals/activation.bash.unit.test.ts
  src/test/common/terminals/activation.commandPrompt.unit.test.ts
  src/test/common/terminals/activation.conda.unit.test.ts
  src/test/common/terminals/environmentActivationProviders/terminalActivation.testvirtualenvs.ts
  src/test/common/terminals/helper.unit.test.ts
  src/test/common/terminals/synchronousTerminalService.unit.test.ts
  src/test/interpreters/activation/service.unit.test.ts
  src/test/pythonEnvironments/base/locators/lowLevel/watcherTestUtils.ts
  src/test/terminals/codeExecution/djangoShellCodeExect.unit.test.ts
  src/test/terminals/codeExecution/terminalCodeExec.unit.test.ts
  typings/extensions.d.ts
Labels: skip news

#18881 Add publish extension parameter
  build/azure-pipeline.stable.yml
Labels: skip news

#18877 Updates for point release
  CHANGELOG.md
  build/azure-pipeline.stable.yml
  news/2 Fixes/18200.md
  news/2 Fixes/18530.md
  news/2 Fixes/18722.md
  news/2 Fixes/18835.md
  news/2 Fixes/18847.md
  package-lock.json
  package.json
Labels: skip news

#18878 Fixed problem where match string contain special characters
  news/2 Fixes/18829.md
  src/client/common/process/logger.ts
Labels: skip tests

#18903 Merge from release to main
  CHANGELOG.md
  news/2 Fixes/18200.md
  news/2 Fixes/18530.md
  news/2 Fixes/18722.md
  news/2 Fixes/18835.md
  news/2 Fixes/18847.md
  package-lock.json
  package.json
Labels: skip news

#18920 Fix support for selecting shell-like interpreter paths which may not exist on filesystem
  src/client/pythonEnvironments/base/locators/composite/envsResolver.ts
Labels: skip news, skip tests

#18965 Ignore testplan-item label in classify check
  .github/workflows/issue-labels.yml
Labels: skip news

#18967 Return union of all envs from all workspace folders
  src/client/pythonEnvironments/legacyIOC.ts
Labels: skip news, skip tests

#18975 Remove process code from browser entry point
  news/2 Fixes/18974.md
  src/client/browser/extension.ts
Labels: skip tests

#18977 Fix error handling when iterating through conda envs + add logging
  src/client/pythonEnvironments/base/locators/lowLevel/condaLocator.ts
  src/client/pythonEnvironments/common/environmentManagers/conda.ts
Labels: skip news, skip tests

#18984 Fixes to the LS no reload work
  .eslintignore
  package.nls.json
  src/client/activation/refCountedLanguageServer.ts
  src/client/common/utils/localize.ts
  src/client/languageServer/watcher.ts
  src/test/languageServer/watcher.unit.test.ts
Labels: skip news

#19029 Handle `process` usage in browser scenario.
  src/client/common/utils/localizeHelpers.ts
Labels: skip news, skip tests

#19037 fix typo
  news/README.md
Labels: skip news

#19047 Fix Pylance not installed - Revert to Jedi requires reload
  src/client/languageServer/watcher.ts
Labels: skip news, skip tests
