Repository microsoft/vscode-python, pull requests merged in 2022-08, with the labels that each got.

#19588 Display problematic environments towards the end of the interpreters list
  src/client/interpreter/configuration/environmentTypeComparer.ts
  src/client/interpreter/configuration/interpreterSelector/commands/setInterpreter.ts
  src/client/pythonEnvironments/base/locators/composite/resolverUtils.ts
  src/test/configuration/environmentTypeComparer.unit.test.ts
Labels: bug

#19602 Update version, and changelog.
  CHANGELOG.md
  build/test-requirements.txt
  package-lock.json
  package.json
Labels: no-changelog

#19603 Update to main next pre-release version.
  package-lock.json
  package.json
Labels: no-changelog

#19599 Rename command to clear internal cache and ensure it also reloads window after it finishes
  package.json
  package.nls.json
  src/client/common/constants.ts
  src/client/common/persistentState.ts
  src/test/common/persistentState.unit.test.ts
Labels: feature-request, skip package*.json

#19386 New Unittest Execution
  pythonFiles/tests/unittestadapter/test_discovery.py
  pythonFiles/tests/unittestadapter/test_utils.py
  pythonFiles/unittestadapter/discovery.py
  pythonFiles/unittestadapter/execution.py
  pythonFiles/unittestadapter/utils.py
  src/client/common/process/internal/scripts/index.ts
  src/client/common/utils/localize.ts
  src/client/testing/common/debugLauncher.ts
  src/client/testing/testController/common/server.ts
  src/client/testing/testController/common/types.ts
  src/client/testing/testController/controller.ts
  src/client/testing/testController/unittest/testExecutionAdapter.ts
  src/client/testing/testController/workspaceTestAdapter.ts
  src/test/testing/testController/server.unit.test.ts
  src/test/testing/testController/workspaceTestAdapter.unit.test.ts
Labels: feature-request

#19326 Fix HOME folder substitution when is not in the beginning of path
  src/client/common/process/logger.ts
  src/test/common/process/logger.unit.test.ts
Labels: bug

#19606 Ensure command to get executable is run only once per session
  src/client/common/process/pythonEnvironment.ts
  src/client/common/process/types.ts
  src/client/pythonEnvironments/info/executable.ts
  src/test/common/process/pythonEnvironment.unit.test.ts
Labels: bug

#19620 Do not pin setuptools
  build/test-requirements.txt
Labels: no-changelog, skip tests

#19612 Use `Microsoft Store` instead of `Windows Store` to represent store related utilities
  src/client/common/process/pythonEnvironment.ts
  src/client/common/process/pythonExecutionFactory.ts
  src/client/interpreter/configuration/environmentTypeComparer.ts
  src/client/interpreter/configuration/interpreterSelector/commands/setInterpreter.ts
  src/client/interpreter/contracts.ts
  src/client/jupyter/jupyterIntegration.ts
  src/client/pythonEnvironments/base/info/env.ts
  src/client/pythonEnvironments/base/info/envKind.ts
  src/client/pythonEnvironments/base/info/index.ts
  src/client/pythonEnvironments/base/locators/composite/resolverUtils.ts
  src/client/pythonEnvironments/base/locators/lowLevel/microsoftStoreLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/windowsKnownPathsLocator.ts
  src/client/pythonEnvironments/common/environmentIdentifier.ts
  src/client/pythonEnvironments/common/environmentManagers/microsoftStoreEnv.ts
  src/client/pythonEnvironments/index.ts
  src/client/pythonEnvironments/info/index.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/common/process/pythonEnvironment.unit.test.ts
  src/test/common/process/pythonExecutionFactory.unit.test.ts
  src/test/configuration/environmentTypeComparer.unit.test.ts
  src/test/configuration/interpreterSelector/commands/installPython.unit.test.ts
  src/test/pythonEnvironments/base/info/envKind.unit.test.ts
  src/test/pythonEnvironments/base/locatorUtils.unit.test.ts
  src/test/pythonEnvironments/base/locators/composite/resolverUtils.unit.test.ts
  src/test/pythonEnvironments/base/locators/lowLevel/microsoftStoreLocator.test.ts
  src/test/pythonEnvironments/base/locators/lowLevel/microsoftStoreLocator.unit.test.ts
  src/test/pythonEnvironments/common/environmentIdentifier.unit.test.ts
  src/test/pythonEnvironments/common/environmentManagers/microsoftStoreEnv.unit.test.ts
Labels: debt

#19479 Only show args for pytest parameterized test
  pythonFiles/testing_tools/adapter/pytest/_pytest_item.py
  pythonFiles/tests/testing_tools/adapter/pytest/test_discovery.py
  pythonFiles/tests/testing_tools/adapter/test_functional.py
Labels: feature-request

#19636 Update version.
  package-lock.json
  package.json
Labels: no-changelog

#19611 Fix buttons in the interpreter quickpick list
  src/client/common/constants.ts
  src/client/common/extensions.ts
  src/client/common/utils/localize.ts
  src/client/common/utils/multiStepInput.ts
  src/client/interpreter/configuration/interpreterSelector/commands/setInterpreter.ts
  src/test/configuration/interpreterSelector/commands/setInterpreter.unit.test.ts
  src/test/mocks/vsc/index.ts
  src/test/vscode-mock.ts
  typings/extensions.d.ts
Labels: feature-request

#19628 Add button to clear list and refresh in interpreters quickpick
  src/client/common/constants.ts
  src/client/common/utils/localize.ts
  src/client/common/utils/multiStepInput.ts
  src/client/interpreter/configuration/interpreterSelector/commands/setInterpreter.ts
  src/test/configuration/interpreterSelector/commands/setInterpreter.unit.test.ts
Labels: feature-request

#19627 Update release plan.
  .github/release_plan.md
  package.json
Labels: no-changelog, skip package*.json

#19656 Ensure any labels or assignees do not carry over when transferring issues to `vscode-python`
  .github/workflows/getLabels.js
  .github/workflows/issue-labels.yml
Labels: debt, skip tests

#19658 add more pylance settings to telemetry
  src/client/telemetry/pylance.ts
Labels: debt, skip tests

#19661 Fix workflow for removing assignees
  .github/workflows/issue-labels.yml
Labels: no-changelog, skip tests

#19662 Disable removing labels until label list is upto-date
  .github/workflows/issue-labels.yml
Labels: no-changelog, skip tests

#19664 Fix the hardcoded labels on the repository
  .github/workflows/getLabels.js
  .github/workflows/issue-labels.yml
Labels: no-changelog, skip tests

#19675 Fix for telemetry JSON extraction.
  src/client/telemetry/pylance.ts
Labels: no-changelog, skip tests

#19625 Update variables in Flask Debug Configuration
  src/client/debugger/extension/configuration/dynamicdebugConfigurationService.ts
  src/client/debugger/extension/configuration/providers/flaskLaunch.ts
  src/test/debugger/extension/configuration/providers/flaskLaunch.unit.test.ts
Labels: bug, area-debugging

#19689 Adds the yml file necessary for the codereview bot
  .github/workflows/pr-chat.yml
Labels: debt

#19698 Update debugger to latest v1.6.3.
  pythonFiles/install_debugpy.py
Labels: feature-request

#19690 Delete test_plan.md
  .github/test_plan.md
Labels: debt

#19699 Update debugger to latest (`debugpy` v1.6.3).
  pythonFiles/install_debugpy.py
Labels: feature-request

#19700 Update version for point release.
  package-lock.json
  package.json
Labels: no-changelog

#19708 Update Pylance settings telemetry properties
  src/client/telemetry/pylance.ts
Labels: no-changelog, skip tests

#19718 Fix commas in pylance.ts json
  src/client/telemetry/pylance.ts
Labels: no-changelog, skip tests

#19722 Logic to control Pylance auto-indent experiment
  src/client/activation/languageClientMiddlewareBase.ts
  src/client/activation/node/analysisOptions.ts
  src/client/activation/node/languageClientMiddleware.ts
  src/client/common/application/types.ts
  src/client/common/application/workspace.ts
  src/client/languageServer/pylanceLSExtensionManager.ts
  src/test/activation/node/analysisOptions.unit.test.ts
Labels: no-changelog

#19735 Test server should bind to localhost.
  src/client/testing/testController/common/server.ts
  src/client/testing/testController/common/types.ts
  src/client/testing/testController/common/utils.ts
  src/client/testing/testController/controller.ts
  src/test/testing/testController/server.unit.test.ts
Labels: bug

#19739 Prevent auto-indent inExperiment method from returning undefined
  src/client/activation/node/analysisOptions.ts
Labels: bug, skip tests

#19740 Fix `any` type issue that caused experiment bug to be missed
  src/client/activation/node/analysisOptions.ts
Labels: debt, skip tests

#19738 Check telemetry metadata in CI
  .github/workflows/telemetry.yml
  package-lock.json
  package.json
Labels: debt

#19747 Fix a YAML mistake in a GH workflow file
  .github/workflows/telemetry.yml
Labels: debt

#19750 Enable notebooks behind LSP by default
  package.json
Labels: no-changelog, area-data science, skip package*.json

#19752 Update main version for release candidate.
  package-lock.json
  package.json
Labels: no-changelog

#19753 Update main to next pre-release.
  package-lock.json
  package.json
Labels: no-changelog

#19749 Re-assign Kim-Adeline's telemetry
  src/client/telemetry/index.ts
Labels: debt, skip tests

#19683 Remove dynamic prefix in debug configuration providers
  src/client/debugger/extension/configuration/dynamicdebugConfigurationService.ts
Labels: feature-request, area-debugging, skip tests

#19592 Launch python tb with the activated env vars
  src/client/tensorBoard/tensorBoardSession.ts
  src/client/tensorBoard/tensorBoardSessionProvider.ts
Labels: bug, skip tests

#19638 Update args type
  package.json
Labels: bug, area-debugging, skip package*.json
