Repository microsoft/vscode-python, pull requests merged in 2022-07, with the labels that each got.

#19407 Version, changelog and TPN updates for release candidate.
  .github/release.yml
  CHANGELOG.md
  ThirdPartyNotices-Distribution.txt
  package-lock.json
  package.json
Labels: skip news

#19408 Update main version to next pre-release.
  package-lock.json
  package.json
Labels: skip news

#19416 Add verbose logging as to what activation command is sent to terminal
  src/client/common/terminal/activator/base.ts
Labels: debt, skip tests

#19424 Update debugpy to 1.6.2
  CHANGELOG.md
  pythonFiles/install_debugpy.py
Labels: skip news

#19425 Do not restart language server for Pylance on interpreter change
  src/client/common/interpreterPathService.ts
  src/client/languageServer/watcher.ts
Labels: bug, skip tests

#19428 Merge back release into main
  CHANGELOG.md
  pythonFiles/install_debugpy.py
Labels: skip news

#19446 Add tip to reload window if user has attempted to install Python in the interpreter quickpick
  package.json
  src/client/common/constants.ts
  src/client/interpreter/configuration/interpreterSelector/commands/setInterpreter.ts
  src/test/configuration/interpreterSelector/commands/setInterpreter.unit.test.ts
Labels: feature-request, skip package*.json

#19397 Improve prompts in case no Python is installed or an invalid interpreter is selected
  src/client/application/diagnostics/base.ts
  src/client/application/diagnostics/checks/invalidLaunchJsonDebugger.ts
  src/client/application/diagnostics/checks/invalidPythonPathInDebugger.ts
  src/client/application/diagnostics/checks/powerShellActivation.ts
  src/client/application/diagnostics/checks/pythonInterpreter.ts
  src/client/application/diagnostics/constants.ts
  src/client/application/diagnostics/types.ts
  src/test/application/diagnostics/checks/pythonInterpreter.unit.test.ts
Labels: feature-request

#19449 Do not attempt to launch Jedi language server in case when selected Python interpreter is invalid
  src/client/languageServer/jediLSExtensionManager.ts
  src/client/languageServer/types.ts
  src/client/languageServer/watcher.ts
  src/test/languageServer/jediLSExtensionManager.unit.test.ts
Labels: feature-request

#19462 Register a command to trigger environment diagnostic prompts
  src/client/application/diagnostics/base.ts
  src/client/application/diagnostics/checks/pythonInterpreter.ts
  src/client/application/diagnostics/serviceRegistry.ts
  src/client/common/application/commands.ts
  src/client/common/constants.ts
  src/test/application/diagnostics/checks/pythonInterpreter.unit.test.ts
  src/test/application/diagnostics/serviceRegistry.unit.test.ts
Labels: feature-request

#19463 Update app insights key.
  src/client/common/constants.ts
Labels: skip news, skip tests

#19475 Add LimitChunkCountPlugin to handle importScripts error
  build/webpack/webpack.extension.browser.config.js
Labels: skip news

#19474 Cherry-pick update app insights key into release
  src/client/common/constants.ts
Labels: skip news, skip tests

#19477 Cherry pick Add LimitChunkCountPlugin to handle importScripts error
  build/webpack/webpack.extension.browser.config.js
Labels: skip news

#19473 Trigger select environment prompt if an invalid interpreter is selected
  src/client/application/diagnostics/checks/pythonInterpreter.ts
  src/test/application/diagnostics/checks/pythonInterpreter.unit.test.ts
Labels: feature-request, skip tests

#19470 Do not trigger test discovery if an invalid interpreter is selected for the workspace
  src/client/testing/main.ts
  src/client/testing/testController/controller.ts
Labels: feature-request, skip tests

#19398 Unittest top-level-directory option
  pythonFiles/testing_tools/unittest_discovery.py
  pythonFiles/visualstudio_py_testlauncher.py
  src/client/testing/testController/unittest/arguments.ts
  src/client/testing/testController/unittest/unittestController.ts
Labels: bug, skip tests

#19483 Ensure prompts related to environment selection do not show up at startup
  src/client/application/diagnostics/checks/pythonInterpreter.ts
  src/test/application/diagnostics/checks/pythonInterpreter.unit.test.ts
Labels: feature-request

#19481 Do not trigger any commands which requires an interpreter if an invalid interpreter is selected
  src/client/debugger/extension/configuration/resolvers/base.ts
  src/client/debugger/extension/debugCommands.ts
  src/client/linters/linterCommands.ts
  src/client/linters/lintingEngine.ts
  src/client/linters/types.ts
  src/client/providers/importSortProvider.ts
  src/client/providers/replProvider.ts
  src/client/telemetry/types.ts
  src/client/terminals/codeExecution/codeExecutionManager.ts
  src/client/testing/main.ts
  src/client/testing/testController/controller.ts
  src/test/debugger/extension/debugCommands.unit.test.ts
  src/test/format/extension.sort.test.ts
  src/test/linters/lintengine.test.ts
  src/test/linters/linterCommands.unit.test.ts
  src/test/providers/importSortProvider.unit.test.ts
  src/test/providers/repl.unit.test.ts
  src/test/terminals/codeExecution/codeExecutionManager.unit.test.ts
Labels: feature-request

#19488 Ensure all components in extension are correctly re-activated when a workspace is trusted
  src/client/activation/activationManager.ts
Labels: bug, skip tests

#19487 Ensure `Install Python` button on the walkthrough opens and fills in the suggested command
  package-lock.json
  package.json
  src/client/common/application/commands.ts
  src/client/common/constants.ts
  src/client/interpreter/configuration/interpreterSelector/commands/installPython/index.ts
  src/client/interpreter/configuration/interpreterSelector/commands/installPython/installPythonViaTerminal.ts
  src/client/interpreter/serviceRegistry.ts
  src/test/configuration/interpreterSelector/commands/installPythonViaTerminal.unit.test.ts
  src/test/interpreters/serviceRegistry.unit.test.ts
Labels: feature-request

#19350 Implement automatic configuration for Django
  package.json
  src/client/debugger/extension/configuration/dynamicdebugConfigurationService.ts
  src/client/debugger/extension/serviceRegistry.ts
  src/client/debugger/extension/types.ts
  src/client/extensionActivation.ts
Labels: feature-request, area-debugging, skip package*.json, skip tests

#19495 Ensure install pylance prompt does not show up when starting codespaces
  .vscode/extensions.json
  .vscode/settings.json
Labels: feature-request

#19510 Use status bar to indicate whether selected Python interpreter is invalid
  src/client/interpreter/display/index.ts
  src/test/interpreters/display.unit.test.ts
  src/test/mocks/vsc/index.ts
  src/test/vscode-mock.ts
Labels: feature-request

#19514 Remove automatic PR assignment for externally-contributed PRs
  .github/assign-reviewers.yml
  .github/assign-reviewers/__main__.py
  .github/assign-reviewers/dev-requirements.in
  .github/assign-reviewers/dev-requirements.txt
  .github/assign-reviewers/requirements.in
  .github/assign-reviewers/requirements.txt
  .github/workflows/assign-reviewers.yml
  .github/workflows/pr-labels.yml
Labels: debt, skip news

#19511 Add python-insider and python-public target populations
  src/client/common/experiments/service.ts
  src/test/common/experiments/service.unit.test.ts
Labels: debt, skip news

#19522 Rename `skip news` to `no-changelog`
  .github/dependabot.yml
  .github/release.yml
  .github/workflows/pr-labels.yml
Labels: no-changelog

#19436 More clear error message for invalid debug configuration
  src/client/debugger/extension/configuration/debugConfigurationService.ts
Labels: bug, skip tests

#19505 Add dynamic FastAPI debug config
  src/client/debugger/extension/configuration/dynamicdebugConfigurationService.ts
Labels: feature-request, area-debugging, skip tests

#19513 Added setting to control when interpreter information is displayed in the status bar
  package.json
  package.nls.json
  src/client/common/configSettings.ts
  src/client/common/configuration/service.ts
  src/client/common/types.ts
  src/client/interpreter/interpreterService.ts
  src/test/common/configSettings/configSettings.unit.test.ts
Labels: feature-request, skip package*.json

#19528 Fix color if a valid interpreter is selected
  src/client/interpreter/display/index.ts
Labels: no-changelog, skip tests

#19501 Interactive window middleware for Pylance LSP notebooks
  src/client/activation/languageClientMiddlewareBase.ts
  src/client/activation/node/analysisOptions.ts
  src/client/activation/node/languageClientMiddleware.ts
  src/client/activation/node/lspInteractiveWindowMiddlewareAddon.ts
  src/client/activation/node/lspNotebooksExperiment.ts
  src/client/activation/node/manager.ts
  src/client/jupyter/jupyterIntegration.ts
  src/test/activation/node/lspInteractiveWindowMiddlewareAddon.unit.test.ts
Labels: no-changelog, skip tests

#19536 Add flask debug config
  src/client/debugger/extension/configuration/dynamicdebugConfigurationService.ts
Labels: feature-request, area-debugging, skip tests

#19541 Tweak info visibility explanations
  package.nls.json
Labels: no-changelog

#19543 Ensure virtual environment created using `python -m venv .` is recognized
  src/client/pythonEnvironments/base/locators/composite/resolverUtils.ts
  src/test/pythonEnvironments/base/locators/composite/envsResolver.unit.test.ts
  src/test/pythonEnvironments/base/locators/composite/resolverUtils.unit.test.ts
Labels: bug

#19552 Source the conda activation script when using Gitbash
  src/client/common/terminal/environmentActivationProviders/condaActivationProvider.ts
  src/test/common/terminals/activation.conda.unit.test.ts
Labels: feature-request

#19561 Fix prompt that shows up when debugging using an invalid Python
  src/client/common/utils/localize.ts
  src/client/debugger/extension/configuration/resolvers/base.ts
  src/client/debugger/extension/configuration/resolvers/launch.ts
Labels: bug, skip tests

#19582 Do not assume the Linux distro to be debian if dnf is not found while installing python
  src/client/common/utils/localize.ts
  src/client/interpreter/configuration/interpreterSelector/commands/installPython/installPythonViaTerminal.ts
  src/test/configuration/interpreterSelector/commands/installPythonViaTerminal.unit.test.ts
Labels: no-changelog

#19579 Ensure a refresh is only triggered after all handlers are registered in quickpicker
  src/client/common/utils/multiStepInput.ts
  src/client/interpreter/configuration/interpreterSelector/commands/setInterpreter.ts
  src/client/pythonEnvironments/base/locator.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/test/configuration/interpreterSelector/commands/setInterpreter.unit.test.ts
Labels: no-changelog

#19578 Look one more level deep in the fastAPI detection
  src/client/debugger/extension/configuration/dynamicdebugConfigurationService.ts
Labels: feature-request, area-debugging, skip tests

#19585 If an interpreter has been explicitly set to an invalid value, trigger the correct prompt
  src/client/application/diagnostics/checks/pythonInterpreter.ts
  src/test/application/diagnostics/checks/pythonInterpreter.unit.test.ts
Labels: no-changelog
