Repository microsoft/vscode-python, pull requests merged in 2022-11, with the labels that each got.

#20125 Update `package.json` for release
  package-lock.json
  package.json
Labels: no-changelog, skip tests

#20126 Post release
  package-lock.json
  package.json
Labels: no-changelog, skip tests

#19977 Don't show certain python commands in command palette when you don't have a python file open
  package.json
Labels: bug, skip package*.json, skip tests

#20128 Update engine to upcoming VS Code version
  package-lock.json
  package.json
  src/test/debuggerTest.ts
  src/test/standardTest.ts
Labels: bug, skip tests

#20127 Cherry pick fixes and update `package.json`
  package-lock.json
  package.json
  src/test/debuggerTest.ts
  src/test/standardTest.ts
Labels: no-changelog, skip tests

#20134 Update Jedi to latest
  pythonFiles/jedilsp_requirements/requirements.txt
Labels: debt

#20143 Update Jedi to latest (#20134)
  pythonFiles/jedilsp_requirements/requirements.txt
Labels: debt

#20136 Fix GDPR tagging for package failure event
  src/client/telemetry/index.ts
Labels: no-changelog, skip tests

#20146 Update engine to latest VS Code release version 1.73.0
  package-lock.json
  package.json
Labels: debt

#20156 Merge back from release
  package-lock.json
  package.json
Labels: no-changelog

#20057 Remove DI from factory
  src/client/common/vscodeApis/browserApis.ts
  src/client/debugger/extension/adapter/factory.ts
  src/client/debugger/extension/adapter/outdatedDebuggerPrompt.ts
  src/test/debugger/extension/adapter/factory.unit.test.ts
  src/test/debugger/extension/adapter/outdatedDebuggerPrompt.unit.test.ts
Labels: debt, area-debugging

#20165 Add more logging when resolving environments
  src/client/common/process/internal/scripts/index.ts
  src/client/proposedApi.ts
  src/client/pythonEnvironments/base/info/interpreter.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionCache.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/client/pythonEnvironments/base/locators/composite/envsResolver.ts
  src/client/pythonEnvironments/common/externalDependencies.ts
Labels: no-changelog, skip tests

#20166 Add tests for active environment API
  src/test/api.test.ts
  src/test/common.ts
Labels: no-changelog

#20152 Fix linting in debugger
  .eslintignore
  src/client/debugger/extension/configuration/debugConfigurationService.ts
  src/client/debugger/extension/configuration/launch.json/completionProvider.ts
  src/client/debugger/extension/configuration/launch.json/interpreterPathCommand.ts
  src/client/debugger/extension/configuration/launch.json/updaterService.ts
  src/client/debugger/extension/configuration/launch.json/updaterServiceHelper.ts
  src/client/debugger/extension/configuration/providers/djangoLaunch.ts
  src/client/debugger/extension/configuration/providers/fastapiLaunch.ts
  src/client/debugger/extension/configuration/providers/fileLaunch.ts
  src/client/debugger/extension/configuration/providers/flaskLaunch.ts
  src/client/debugger/extension/configuration/providers/moduleLaunch.ts
  src/client/debugger/extension/configuration/providers/pidAttach.ts
  src/client/debugger/extension/configuration/providers/pyramidLaunch.ts
  src/client/debugger/extension/configuration/resolvers/attach.ts
  src/client/debugger/extension/configuration/resolvers/base.ts
  src/client/debugger/extension/configuration/resolvers/helper.ts
  src/client/debugger/extension/configuration/resolvers/launch.ts
  src/client/debugger/extension/helpers/protocolParser.ts
  src/client/debugger/extension/serviceRegistry.ts
  src/client/debugger/extension/types.ts
  src/test/debugger/extension/configuration/debugConfigurationService.unit.test.ts
  src/test/debugger/extension/configuration/launch.json/completionProvider.unit.test.ts
  src/test/debugger/extension/configuration/launch.json/interpreterPathCommand.unit.test.ts
  src/test/debugger/extension/configuration/launch.json/updaterServer.unit.test.ts
  src/test/debugger/extension/configuration/launch.json/updaterServerHelper.unit.test.ts
  src/test/debugger/extension/configuration/providers/fileLaunch.unit.test.ts
  src/test/debugger/extension/configuration/providers/pidAttach.unit.test.ts
  src/test/debugger/extension/configuration/resolvers/attach.unit.test.ts
  src/test/debugger/extension/configuration/resolvers/base.unit.test.ts
  src/test/debugger/extension/configuration/resolvers/helper.unit.test.ts
  src/test/debugger/extension/configuration/resolvers/launch.unit.test.ts
Labels: debt

#20074 Accept pytest exit code 1 for some tests cannot be collected
  pythonFiles/testing_tools/adapter/pytest/_discovery.py
  pythonFiles/tests/testing_tools/adapter/pytest/test_discovery.py
Labels: bug

#20173 Monkeypatch terminals created to log commands sent
  src/client/common/application/terminalManager.ts
Labels: debt, skip tests

#20178 Do not cache result if running an interpreter fails
  src/client/common/variables/environmentVariablesProvider.ts
  src/client/pythonEnvironments/base/info/environmentInfoService.ts
  src/client/pythonEnvironments/common/environmentManagers/conda.ts
Labels: no-changelog, skip tests

#20180 Add more logging and only retry once if fetching interpreter information fails
  src/client/common/process/rawProcessApis.ts
  src/client/proposedApi.ts
  src/client/pythonEnvironments/base/info/environmentInfoService.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionCache.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
Labels: no-changelog, skip tests

#20181 Fix poetry discovery
  src/client/extensionActivation.ts
  src/client/extensionInit.ts
  src/client/pythonEnvironments/common/environmentManagers/poetry.ts
Labels: bug, skip tests

#20158 Fix issue with extension prompt being shown to users after install
  src/client/linters/linterManager.ts
  src/client/linters/prompts/common.ts
  src/client/linters/prompts/flake8Prompt.ts
  src/client/linters/prompts/pylintPrompt.ts
Labels: bug, skip tests

#20186 Only use environment cache to resolve environment if it has complete information
  src/client/pythonEnvironments/base/locators/composite/envsCollectionCache.ts
  src/test/pythonEnvironments/base/locators/composite/envsCollectionService.unit.test.ts
Labels: bug

#20192 Fix errors related to `python.envFile` setting
  src/client/common/variables/environmentVariablesProvider.ts
  src/client/proposedApi.ts
  src/client/pythonEnvironments/common/externalDependencies.ts
Labels: bug, skip tests

#20187 Fix issue with extension prompt being shown to users after install
  src/client/linters/linterManager.ts
  src/client/linters/prompts/common.ts
  src/client/linters/prompts/flake8Prompt.ts
  src/client/linters/prompts/pylintPrompt.ts
Labels: bug, skip tests

#20200 Update package version for recovery release.
  package-lock.json
  package.json
Labels: no-changelog

#20195 Improve description for `python.terminal.focusAfterLaunch` setting
  package.nls.json
Labels: debt, skip tests

#20212 Ensure we don't use the same interpreter for equally named project on different hosts
  src/client/activation/activationManager.ts
  src/client/common/interpreterPathService.ts
  src/client/common/types.ts
  src/test/activation/activationManager.unit.test.ts
  src/test/common/configSettings/configSettings.unit.test.ts
  src/test/common/interpreterPathService.unit.test.ts
  src/test/extensionSettings.ts
Labels: bug

#20103 Extend scope of "python.tensorBoard.logDirectory" and support variable substitution
  package.json
  src/client/common/configSettings.ts
  src/client/common/types.ts
  src/client/tensorBoard/tensorBoardSession.ts
  src/client/tensorBoard/tensorBoardSessionProvider.ts
Labels: feature-request, skip package*.json, skip tests

#20222 Cache the value of `extensions.all`
  src/client/common/application/extensions.ts
  src/client/proposedApi.ts
  src/test/proposedApi.unit.test.ts
Labels: debt, skip tests

#20229 Update cached list of extensions correctly
  src/client/common/application/extensions.ts
Labels: no-changelog, skip tests

#20230 Fix venv tests
  src/client/common/interpreterPathService.ts
Labels: no-changelog, skip tests

#20226 Remove DI from config launch
  src/client/debugger/extension/configuration/dynamicdebugConfigurationService.ts
  src/client/debugger/extension/configuration/launch.json/launchJsonReader.ts
  src/client/debugger/extension/configuration/launch.json/updaterService.ts
  src/client/debugger/extension/configuration/launch.json/updaterServiceHelper.ts
  src/client/debugger/extension/configuration/types.ts
  src/client/debugger/extension/configuration/utils/common.ts
  src/client/debugger/extension/debugCommands.ts
  src/client/debugger/extension/hooks/childProcessAttachService.ts
  src/client/debugger/extension/serviceRegistry.ts
  src/client/testing/common/debugLauncher.ts
  src/test/debugger/extension/configuration/launch.json/updaterServer.unit.test.ts
  src/test/debugger/extension/configuration/launch.json/updaterServerHelper.unit.test.ts
  src/test/debugger/extension/debugCommands.unit.test.ts
  src/test/debugger/extension/hooks/childProcessAttachService.unit.test.ts
  src/test/debugger/extension/serviceRegistry.unit.test.ts
  src/test/testing/common/debugLauncher.unit.test.ts
Labels: debt, area-debugging

#20238 Update to proposed telemetry logger
  package-lock.json
  package.json
  src/client/browser/extension.ts
  src/client/telemetry/index.ts
Labels: debt, skip tests

#20172 Show user deprecated message for unsupported Python versions when launching the debugger
  src/client/common/utils/localize.ts
  src/client/debugger/extension/adapter/factory.ts
  src/test/debugger/extension/adapter/factory.unit.test.ts
Labels: debt

#20237 Notify Pylance on `jupyter.runStartupCommands` config change
  src/client/activation/common/analysisOptions.ts
  src/client/activation/node/analysisOptions.ts
  src/client/browser/extension.ts
Labels: no-changelog, skip tests

#20243 Add button to open folder from venv failure message
  src/client/common/utils/localize.ts
  src/client/pythonEnvironments/creation/common/workspaceSelection.ts
Labels: feature-request, skip tests

#20255 Bump VS Code engine to `1.74.0-insiders`
  package.json
Labels: debt, area-editor-*, skip package*.json

#20256 Drop the `-insiders` suffix from the VS Code engine
  package.json
Labels: debt, skip package*.json

#20258 Merge Getting Started walkthrough to include Create Environment Tile
  package.json
Labels: debt, experimenting, skip package*.json

#20273 Fix CI tests
  package-lock.json
  package.json
  src/test/debuggerTest.ts
  src/test/insiders/languageServer.insiders.test.ts
  src/test/multiRootTest.ts
  src/test/standardTest.ts
  src/test/tensorBoard/nbextensionCodeLensProvider.insiders.test.ts
Labels: debt, skip package*.json, skip tests

#20285 Catch exceptions when changing `formatOnType` setting
  src/client/activation/node/analysisOptions.ts
Labels: no-changelog, skip tests

#20291 Upgrade debugpy to 1.6.4
  pythonFiles/install_debugpy.py
Labels: debt

#20286 Simplify launch debug
  .eslintignore
  src/client/common/vscodeApis/windowApis.ts
  src/client/common/vscodeApis/workspaceApis.ts
  src/client/debugger/extension/configuration/launch.json/interpreterPathCommand.ts
  src/client/debugger/extension/configuration/launch.json/launchJsonReader.ts
  src/client/debugger/extension/configuration/launch.json/updaterService.ts
  src/client/debugger/extension/configuration/launch.json/updaterServiceHelper.ts
  src/client/debugger/extension/configuration/resolvers/base.ts
  src/client/debugger/extension/configuration/resolvers/helper.ts
  src/client/debugger/extension/configuration/utils/common.ts
  src/client/debugger/extension/configuration/utils/workspaceFolder.ts
  src/client/testing/common/debugLauncher.ts
  src/test/debugger/envVars.test.ts
  src/test/debugger/extension/adapter/factory.unit.test.ts
  src/test/debugger/extension/configuration/launch.json/interpreterPathCommand.unit.test.ts
  src/test/debugger/extension/configuration/launch.json/updaterServer.unit.test.ts
  src/test/debugger/extension/configuration/launch.json/updaterServerHelper.unit.test.ts
  src/test/debugger/extension/configuration/providers/djangoLaunch.unit.test.ts
  src/test/debugger/extension/configuration/providers/pyramidLaunch.unit.test.ts
  src/test/debugger/extension/configuration/resolvers/attach.unit.test.ts
  src/test/debugger/extension/configuration/resolvers/base.unit.test.ts
  src/test/debugger/extension/configuration/resolvers/helper.unit.test.ts
  src/test/debugger/extension/configuration/resolvers/launch.unit.test.ts
Labels: debt, area-debugging
