Repository microsoft/vscode-python, pull requests merged in 2023-02, with the labels that each got.

#20616 Ensure dependency quick pick is not shown when user exits env creation
  src/client/pythonEnvironments/creation/provider/venvCreationProvider.ts
  src/test/pythonEnvironments/creation/provider/venvCreationProvider.unit.test.ts
Labels: no-changelog

#20617 Fix test failures due to linting
  pythonFiles/testing_tools/adapter/info.py
  pythonFiles/testing_tools/adapter/pytest/_discovery.py
  pythonFiles/tests/testing_tools/adapter/pytest/test_discovery.py
  pythonFiles/tests/testing_tools/adapter/test___main__.py
  pythonFiles/tests/testing_tools/adapter/test_discovery.py
  pythonFiles/unittestadapter/execution.py
  src/test/linters/lint.multiroot.test.ts
Labels: debt

#20609 Ensure IDs of Conda environments without python does not change after python is installed
  src/client/common/installer/condaInstaller.ts
  src/client/proposedApi.ts
  src/client/pythonEnvironments/base/info/env.ts
  src/client/pythonEnvironments/base/locators/composite/resolverUtils.ts
  src/client/pythonEnvironments/common/environmentManagers/conda.ts
  src/test/proposedApi.unit.test.ts
Labels: bug

#20627 Fix wording in conda inherit env prompt
  src/client/common/utils/localize.ts
  src/client/interpreter/virtualEnvs/condaInheritEnvPrompt.ts
  src/client/telemetry/index.ts
  src/test/interpreters/virtualEnvs/condaInheritEnvPrompt.unit.test.ts
Labels: debt

#20625 Ensure editable install only when [build-system] is present `pyproject.toml`
  src/client/pythonEnvironments/creation/provider/venvUtils.ts
  src/test/pythonEnvironments/creation/provider/venvUtils.unit.test.ts
Labels: bug

#20630 Update version for release
  package-lock.json
  package.json
  pythonFiles/testing_tools/adapter/info.py
  pythonFiles/testing_tools/adapter/pytest/_discovery.py
  pythonFiles/tests/testing_tools/adapter/pytest/test_discovery.py
  pythonFiles/tests/testing_tools/adapter/test___main__.py
  pythonFiles/tests/testing_tools/adapter/test_discovery.py
  pythonFiles/unittestadapter/execution.py
Labels: no-changelog

#20639 Allow to select a Python2.7 interpreter
  src/client/pythonEnvironments/base/info/environmentInfoService.ts
Labels: bug, skip tests

#20642 Add a button in prompt to check logs in case the selected interpreter is invalid
  src/client/application/diagnostics/checks/pythonInterpreter.ts
  src/test/application/diagnostics/checks/pythonInterpreter.unit.test.ts
Labels: feature-request

#20656 Use correct API to get interpreter path for language servers
  src/client/activation/languageClientMiddlewareBase.ts
  src/client/interpreter/configuration/pythonPathUpdaterService.ts
Labels: bug, skip tests

#20661 Ensure interpreter path isn't truncated for workspace-relative paths when storing value
  src/client/interpreter/configuration/services/workspaceFolderUpdaterService.ts
  src/client/interpreter/configuration/services/workspaceUpdaterService.ts
  src/client/interpreter/interpreterService.ts
  src/test/interpreters/pythonPathUpdaterFactory.unit.test.ts
Labels: bug

#20667 Only use activated environment from terminal if VSCode was launched via CLI
  src/client/interpreter/virtualEnvs/activatedEnvLaunch.ts
  src/test/interpreters/virtualEnvs/activatedEnvLaunch.unit.test.ts
Labels: feature-request

#20690 Call the correct API to determine if a user is in treatment or control group
  .github/workflows/pr-check.yml
  src/client/common/experiments/service.ts
  src/test/common/experiments/service.unit.test.ts
Labels: bug

#20653 Inactive pytest run command
  src/client/testing/testController/common/types.ts
  src/client/testing/testController/controller.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/client/testing/testController/workspaceTestAdapter.ts
Labels: no-changelog, skip tests

#20693 Add support for 'back' to all create env UI.
  pythonFiles/create_venv.py
  src/client/common/utils/async.ts
  src/client/common/utils/multiStepInput.ts
  src/client/common/vscodeApis/windowApis.ts
  src/client/interpreter/configuration/interpreterSelector/commands/setInterpreter.ts
  src/client/interpreter/configuration/types.ts
  src/client/pythonEnvironments/creation/common/workspaceSelection.ts
  src/client/pythonEnvironments/creation/createEnvironment.ts
  src/client/pythonEnvironments/creation/provider/condaCreationProvider.ts
  src/client/pythonEnvironments/creation/provider/condaUtils.ts
  src/client/pythonEnvironments/creation/provider/venvCreationProvider.ts
  src/client/pythonEnvironments/creation/provider/venvUtils.ts
  src/client/pythonEnvironments/creation/types.ts
  src/test/pythonEnvironments/creation/common/workspaceSelection.unit.test.ts
  src/test/pythonEnvironments/creation/createEnvironment.unit.test.ts
  src/test/pythonEnvironments/creation/provider/condaCreationProvider.unit.test.ts
  src/test/pythonEnvironments/creation/provider/venvCreationProvider.unit.test.ts
  src/test/pythonEnvironments/creation/provider/venvUtils.unit.test.ts
Labels: feature-request

#20710 Don't set `formatOnType` for auto-indent experiment if it's already set
  src/client/activation/node/analysisOptions.ts
Labels: no-changelog, skip tests

#20534 Detect ActiveState Python runtimes
  package.json
  package.nls.json
  resources/report_issue_user_settings.json
  src/client/common/configSettings.ts
  src/client/common/types.ts
  src/client/interpreter/configuration/environmentTypeComparer.ts
  src/client/interpreter/configuration/interpreterSelector/commands/setInterpreter.ts
  src/client/pythonEnvironments/base/info/envKind.ts
  src/client/pythonEnvironments/base/info/index.ts
  src/client/pythonEnvironments/base/locators/composite/resolverUtils.ts
  src/client/pythonEnvironments/base/locators/lowLevel/activestateLocator.ts
  src/client/pythonEnvironments/common/environmentIdentifier.ts
  src/client/pythonEnvironments/common/environmentManagers/activestate.ts
  src/client/pythonEnvironments/index.ts
  src/client/pythonEnvironments/info/index.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/common/configSettings/configSettings.unit.test.ts
  src/test/pythonEnvironments/base/info/envKind.unit.test.ts
  src/test/pythonEnvironments/base/locators/lowLevel/activestateLocator.unit.test.ts
  src/test/pythonEnvironments/common/environmentManagers/activestate.unit.test.ts
  src/test/pythonEnvironments/common/envlayouts/activestate/2af6390a/_runtime_store/completed
  src/test/pythonEnvironments/common/envlayouts/activestate/2af6390a/exec/not-python3
  src/test/pythonEnvironments/common/envlayouts/activestate/2af6390a/exec/not-python3.exe
  src/test/pythonEnvironments/common/envlayouts/activestate/b6a0705d/exec/python3
  src/test/pythonEnvironments/common/envlayouts/activestate/b6a0705d/exec/python3.exe
  src/test/pythonEnvironments/common/envlayouts/activestate/c09080d1/_runtime_store/completed
  src/test/pythonEnvironments/common/envlayouts/activestate/c09080d1/exec/python3
  src/test/pythonEnvironments/common/envlayouts/activestate/c09080d1/exec/python3.exe
Labels: feature-request, skip package*.json

#20726 Show `Python: Report issue` command in palette regardless of whether a Python file is opened
  package.json
Labels: bug, skip package*.json

#20742 Point to Python v3.11 instead of Python v3.10 when opening windows store
  src/client/interpreter/configuration/interpreterSelector/commands/installPython/index.ts
Labels: feature-request, skip tests

#20751 Add description for `python.experiment` settings values
  package.json
  package.nls.json
Labels: debt, skip package*.json, skip tests

#20745 Tag Pylance settings properties for GDPR
  src/client/telemetry/pylance.ts
Labels: no-changelog, skip tests

#20739 Ensure escape on TOML and requirements is treated as cancel.
  src/client/pythonEnvironments/creation/provider/condaCreationProvider.ts
  src/client/pythonEnvironments/creation/provider/venvUtils.ts
  src/test/pythonEnvironments/creation/provider/condaCreationProvider.unit.test.ts
  src/test/pythonEnvironments/creation/provider/venvUtils.unit.test.ts
Labels: bug

#20741 Fix debugger attach to process when running on WSL
  src/client/common/process/rawProcessApis.ts
Labels: bug, skip tests

#20760 Make sure conda activate is used for micromamba
  src/client/common/terminal/environmentActivationProviders/condaActivationProvider.ts
  src/test/common/terminals/activation.conda.unit.test.ts
Labels: feature-request

#20762 Updating version for release candidate.
  package-lock.json
  package.json
Labels: no-changelog

#20764 Update main to next pre-release
  package-lock.json
  package.json
Labels: no-changelog
