Repository microsoft/vscode-python, pull requests merged in 2023-12, with the labels that each got.

#22587 bump-release-2023.22
  package-lock.json
  package.json
Labels: no-changelog

#22608 finalized-release-2023.22
  package-lock.json
  package.json
Labels: no-changelog

#22638 Revert "Remove old code for folder support in interpreter path setting"
  src/client/common/configSettings.ts
Labels: bug, skip tests

#22639 Fix localization failure for pre-release
  src/client/logging/settingLogs.ts
  src/client/pythonEnvironments/creation/common/installCheckUtils.ts
  src/test/terminals/codeExecution/smartSend.test.ts
Labels: debt

#22640 More fixes to pre-release
  src/test/terminals/codeExecution/smartSend.test.ts
Labels: no-changelog, skip tests

#22641 More fixes to pre-release
  src/client/common/utils/localize.ts
Labels: no-changelog, skip tests

#22629 Remove experimental tag from createEnvironment.contentButton setting
  package.json
Labels: debt, skip package*.json

#22645 Add to release plan steps with point release steps
  .github/release_plan.md
Labels: no-changelog

#22646 Add localization check to CI
  .github/workflows/build.yml
  .github/workflows/pr-check.yml
Labels: debt, skip tests

#22653 add logging for when testing is already running and causes new runs to be canceled
  src/client/testing/testController/workspaceTestAdapter.ts
Labels: debt, skip tests

#22663 Add permissions to triage-info-needed.yml
  .github/workflows/triage-info-needed.yml
Labels: debt

#22681 support multi-level nested classes pytest
  pythonFiles/tests/pytestadapter/.data/test_multi_class_nest.py
  pythonFiles/tests/pytestadapter/expected_discovery_test_output.py
  pythonFiles/tests/pytestadapter/test_discovery.py
  pythonFiles/vscode_pytest/__init__.py
Labels: bug, area-testing
