Repository microsoft/vscode-python, pull requests merged in 2023-11, with the labels that each got.

#22387 Add cwd to error logs
  src/client/testing/testController/common/resultResolver.ts
  src/client/testing/testController/common/server.ts
  src/client/testing/testController/common/utils.ts
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/client/testing/testController/workspaceTestAdapter.ts
  src/test/testing/testController/workspaceTestAdapter.unit.test.ts
Labels: debt, skip tests

#22401 Update version for release
  package-lock.json
  package.json
Labels: no-changelog

#22402 remove new line chars from error text messages in testing rewrite
  src/client/testing/testController/common/resultResolver.ts
Labels: debt, area-testing, skip tests

#22413 Remove old code for folder support in interpreter path setting
  src/client/common/configSettings.ts
Labels: debt, skip tests

#22424 Do not attempt to kill the process if it has already exited
  src/client/common/process/rawProcessApis.ts
Labels: bug, skip tests

#22391 Improve shell identifier on case-insensitive system
  src/client/common/terminal/shellDetectors/baseShellDetector.ts
  src/test/common/terminals/shellDetectors/shellDetectors.unit.test.ts
Labels: bug

#22440 Reliably detect whether shell integration is working
  package.json
  src/client/common/application/applicationShell.ts
  src/client/common/application/types.ts
  src/client/terminals/envCollectionActivation/service.ts
  src/client/terminals/envCollectionActivation/shellIntegration.ts
  src/client/terminals/envCollectionActivation/shellIntegrationService.ts
  src/client/terminals/serviceRegistry.ts
  src/client/terminals/types.ts
  src/test/interpreters/activation/terminalEnvVarCollectionService.unit.test.ts
  src/test/terminals/serviceRegistry.unit.test.ts
  typings/vscode-proposed/vscode.proposed.terminalExecuteCommandEvent.d.ts
Labels: feature-request, skip package*.json

#22406 Add consoleTitle to launch.json properties schema
  package.json
Labels: feature-request, skip package*.json

#22445 Revert "Reliably detect whether shell integration is working"
  package.json
  src/client/common/application/applicationShell.ts
  src/client/common/application/types.ts
  src/client/terminals/envCollectionActivation/service.ts
  src/client/terminals/envCollectionActivation/shellIntegration.ts
  src/client/terminals/envCollectionActivation/shellIntegrationService.ts
  src/client/terminals/serviceRegistry.ts
  src/client/terminals/types.ts
  src/test/interpreters/activation/terminalEnvVarCollectionService.unit.test.ts
  src/test/terminals/serviceRegistry.unit.test.ts
  typings/vscode-proposed/vscode.proposed.terminalExecuteCommandEvent.d.ts
Labels: no-changelog, skip package*.json

#22432 Adding `Locked` comments to walkthrough commands
  package.nls.json
Labels: bug, area-editor-*, skip package*.json

#22446 Fix shell integration API reliability
  package.json
  src/client/common/application/applicationShell.ts
  src/client/common/application/types.ts
  src/client/terminals/envCollectionActivation/service.ts
  src/client/terminals/envCollectionActivation/shellIntegration.ts
  src/client/terminals/envCollectionActivation/shellIntegrationService.ts
  src/client/terminals/serviceRegistry.ts
  src/client/terminals/types.ts
  src/test/interpreters/activation/terminalEnvVarCollectionService.unit.test.ts
  src/test/terminals/serviceRegistry.unit.test.ts
  typings/vscode-proposed/vscode.proposed.terminalExecuteCommandEvent.d.ts
Labels: no-changelog, skip package*.json

#22405 Support deactivating virtual environments without user intervention
  pythonFiles/deactivate.csh
  pythonFiles/deactivate.fish
  pythonFiles/deactivate.ps1
  pythonFiles/deactivate/bash/deactivate
  pythonFiles/deactivate/fish/deactivate
  pythonFiles/deactivate/powershell/deactivate.ps1
  pythonFiles/deactivate/zsh/deactivate
  pythonFiles/printEnvVariablesToFile.py
  src/client/common/utils/async.ts
  src/client/common/utils/localize.ts
  src/client/interpreter/activation/service.ts
  src/client/terminals/envCollectionActivation/deactivatePrompt.ts
  src/client/terminals/envCollectionActivation/deactivateScripts.ts
  src/client/terminals/envCollectionActivation/deactivateService.ts
  src/client/terminals/envCollectionActivation/service.ts
  src/client/terminals/envCollectionActivation/shellIntegrationService.ts
  src/client/terminals/serviceRegistry.ts
  src/client/terminals/types.ts
  src/test/interpreters/activation/terminalEnvVarCollectionService.unit.test.ts
  src/test/terminals/envCollectionActivation/deactivatePrompt.unit.test.ts
  src/test/terminals/serviceRegistry.unit.test.ts
Labels: feature-request

#22450 If active editor opened is outside the editor, activate the first workspace
  src/client/activation/activationManager.ts
  src/client/interpreter/activation/service.ts
  src/test/activation/activationManager.unit.test.ts
Labels: bug, skip tests

#22468 Install requirements before toml
  pythonFiles/create_venv.py
  pythonFiles/tests/test_create_venv.py
Labels: bug

#22470 Add 3.12 to conda version list
  src/client/pythonEnvironments/creation/provider/condaUtils.ts
Labels: debt, skip tests

#22471 Use `WorkspaceFolder.name` in addition to workspace folder's basename when resolving `${workspaceFolder:name}` syntax in settings
  src/client/common/variables/systemVariables.ts
Labels: bug, skip tests

#22479 Use worker threads for fetching Windows Registry interpreters
  .github/workflows/pr-check.yml
  package.json
  package.nls.json
  src/client/common/experiments/groups.ts
  src/client/pythonEnvironments/base/locator.ts
  src/client/pythonEnvironments/base/locators/composite/resolverUtils.ts
  src/client/pythonEnvironments/base/locators/lowLevel/windowsRegistryLocator.ts
  src/client/pythonEnvironments/base/locators/wrappers.ts
  src/client/pythonEnvironments/common/environmentManagers/conda.ts
  src/client/pythonEnvironments/common/externalDependencies.ts
  src/client/pythonEnvironments/common/registryKeysWorker.ts
  src/client/pythonEnvironments/common/registryValuesWorker.ts
  src/client/pythonEnvironments/common/windowsRegistry.ts
  src/client/pythonEnvironments/common/windowsUtils.ts
  src/test/pythonEnvironments/base/locators/lowLevel/windowsRegistryLocator.testvirtualenvs.ts
Labels: feature-request, skip package*.json, skip tests

#22493 Bump `vscode-tas-client` and fix tests
  package-lock.json
  package.json
  src/test/common/experiments/service.unit.test.ts
Labels: bug

#22353 Show warning and allow user to turn off smart send for deprecated Python code
  package.json
  package.nls.json
  pythonFiles/normalizeSelection.py
  src/client/common/application/commands.ts
  src/client/common/configSettings.ts
  src/client/common/types.ts
  src/client/common/utils/localize.ts
  src/client/terminals/codeExecution/djangoShellCodeExecution.ts
  src/client/terminals/codeExecution/helper.ts
  src/client/terminals/codeExecution/repl.ts
  src/client/terminals/codeExecution/terminalCodeExecution.ts
  src/test/pythonFiles/terminalExec/sample_invalid_smart_selection.py
  src/test/terminals/codeExecution/smartSend.test.ts
  src/test/terminals/codeExecution/terminalCodeExec.unit.test.ts
Labels: feature-request, skip package*.json

#22487 Use shell integration to denote success/failure
  pythonFiles/pythonrc.py
  pythonFiles/tests/test_shell_integration.py
  src/client/common/terminal/service.ts
  src/test/common/terminals/service.unit.test.ts
Labels: feature-request, area-repl

#22454 Resolve test suite discovery import errors due to path ordering
  pythonFiles/unittestadapter/discovery.py
Labels: bug

#22534 switch to conditional error message on check for UUID and port during pytest config
  pythonFiles/vscode_pytest/__init__.py
Labels: bug

#22466 Improvement: Pass along python interpreter to jedi-language-server
  src/client/activation/jedi/analysisOptions.ts
  src/test/activation/jedi/jediAnalysisOptions.unit.test.ts
Labels: bug

#22549 White space after REPL prompt
  pythonFiles/pythonrc.py
  pythonFiles/tests/test_shell_integration.py
Labels: bug, area-repl

#22560 Fix shell integration decoration for windows pwsh
  pythonFiles/pythonrc.py
  pythonFiles/tests/test_shell_integration.py
Labels: bug, area-repl

#22566 Do not throw if initializing deactivate script fails
  src/client/terminals/envCollectionActivation/service.ts
  src/test/interpreters/activation/terminalEnvVarCollectionService.unit.test.ts
Labels: no-changelog, skip tests

#22570 Properly build deactivate commands for powershell
  src/client/terminals/envCollectionActivation/deactivateService.ts
  src/test/interpreters/activation/terminalEnvVarCollectionService.unit.test.ts
Labels: no-changelog, skip tests

#22569 fix no test id provided for pytest run
  pythonFiles/vscode_pytest/run_pytest_script.py
Labels: bug, area-testing

#22572 Fix shell integration decoration bug for Windows pwsh
  pythonFiles/pythonrc.py
  pythonFiles/tests/test_shell_integration.py
Labels: bug, area-repl

#22578 Revert unsuccessful REPL decoration fix and disable for windows
  pythonFiles/pythonrc.py
  pythonFiles/tests/test_shell_integration.py
Labels: bug, area-repl
