Repository microsoft/vscode-python, pull requests merged in 2023-07, with the labels that each got.

#21556 Update version for release candidate
  package-lock.json
  package.json
Labels: no-changelog

#21559 Update main to next pre-release
  package-lock.json
  package.json
Labels: no-changelog

#21564 Correct PATH env var name for non-Windows when applying env var collection for microvenv
  src/client/interpreter/activation/terminalEnvVarCollectionService.ts
Labels: bug, skip tests

#21569 updating version for release
  package-lock.json
  package.json
Labels: no-changelog

#21572 Remove needs labels
  .github/workflows/remove-needs-labels.yml
Labels: debt

#21575 Info needed closer
  .github/workflows/info-needed-closer.yml
Labels: debt

#21580 Move lock issues
  .github/workflows/lock-issues.yml
Labels: debt

#21581 Move more workflows to python
  .github/workflows/community-feedback-auto-comment.yml
  .github/workflows/pr-file-check.yml
  .github/workflows/pr-labels.yml
  .github/workflows/remove-needs-labels.yml
Labels: debt

#21601 fix duplicate class names processed as single node in build test tree pytest
  pythonFiles/tests/pytestadapter/.data/unittest_folder/test_add.py
  pythonFiles/tests/pytestadapter/.data/unittest_folder/test_subtract.py
  pythonFiles/tests/pytestadapter/expected_discovery_test_output.py
  pythonFiles/vscode_pytest/__init__.py
Labels: bug, area-testing

#21603 Return exceptions & skips correctly pytest
  pythonFiles/tests/pytestadapter/.data/error_raise_exception.py
  pythonFiles/tests/pytestadapter/.data/parametrize_tests.py
  pythonFiles/tests/pytestadapter/.data/skip_tests.py
  pythonFiles/tests/pytestadapter/expected_discovery_test_output.py
  pythonFiles/tests/pytestadapter/expected_execution_test_output.py
  pythonFiles/tests/pytestadapter/test_execution.py
  pythonFiles/vscode_pytest/__init__.py
Labels: bug, area-testing

#21604 Refactor API code in a separate module
  src/client/api.ts
  src/client/api/main.ts
  src/client/api/package-lock.json
  src/client/api/package.json
  src/client/deprecatedProposedApiTypes.ts
  src/client/environmentApi.ts
  src/client/extension.ts
  src/client/pythonEnvironments/creation/proposed.createEnvApis.ts
  src/test/api.test.ts
  src/test/common.ts
  src/test/environmentApi.unit.test.ts
  src/test/initialize.ts
Labels: no-changelog, skip tests

#21589 Download `get-pip.py` during build
  .github/actions/build-vsix/action.yml
  .github/workflows/build.yml
  .github/workflows/pr-check.yml
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
  build/build-install-requirements.txt
  build/debugger-install-requirements.txt
  gulpfile.js
  pythonFiles/download_get_pip.py
  pythonFiles/get-pip.py
  src/client/common/process/internal/scripts/index.ts
Labels: debt, skip tests

#21618 Bump semver
  package-lock.json
Labels: no-changelog, skip package*.json

#21620 delete run messages
  src/client/testing/testController/common/resultResolver.ts
Labels: debt, skip tests

#21629 display errors and tests on discovery
  src/client/testing/testController/common/resultResolver.ts
  src/test/testing/testController/resultResolver.unit.test.ts
Labels: feature-request, area-testing

#21585 Add deprecation warning for linting and formatting settings
  package.json
  package.nls.json
Labels: area-linting, debt, area-formatting, skip package*.json

#21525 Update writing style based on recommendation
  src/client/common/utils/localize.ts
  src/client/debugger/extension/adapter/factory.ts
Labels: debt, skip tests

#21630 Handle error tests as a different test icon
  pythonFiles/tests/pytestadapter/expected_execution_test_output.py
  pythonFiles/tests/pytestadapter/test_execution.py
  pythonFiles/vscode_pytest/__init__.py
  src/client/testing/testController/common/resultResolver.ts
  src/test/testing/testController/resultResolver.unit.test.ts
Labels: bug

#21638 Update README for Python extension API to point to examples
  build/azure-pipelines/pipeline.yml
  pythonExtensionApi/README.md
  pythonExtensionApi/example/todo.txt
Labels: no-changelog, skip tests

#21636 Compare global storage data using only `key`
  src/client/common/persistentState.ts
Labels: bug, skip tests

#21639 Add extra logging regarding interpreter discovery
  src/client/common/process/rawProcessApis.ts
  src/client/common/utils/async.ts
  src/client/pythonEnvironments/base/locators/lowLevel/activeStateLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/microsoftStoreLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/posixKnownPathsLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/pyenvLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/windowsKnownPathsLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/windowsRegistryLocator.ts
Labels: debt, skip tests

#21651 Use correct `tsconfig.json` when generating npm package
  pythonExtensionApi/.eslintrc
  pythonExtensionApi/README.md
  pythonExtensionApi/package-lock.json
  pythonExtensionApi/package.json
  pythonExtensionApi/src/main.ts
  pythonExtensionApi/tsconfig.json
Labels: no-changelog, skip tests

#21652 Modify .eslintrc to turn off any errors for declaration files
  pythonExtensionApi/.eslintrc
Labels: no-changelog, skip tests

#21656 Bring back feature to Run Python file in dedicated terminal
  package.json
  package.nls.json
  src/client/common/constants.ts
  src/client/common/terminal/factory.ts
  src/client/common/terminal/types.ts
  src/client/telemetry/index.ts
  src/client/terminals/codeExecution/codeExecutionManager.ts
  src/client/terminals/codeExecution/terminalCodeExecution.ts
  src/client/terminals/types.ts
  src/test/common/terminals/factory.unit.test.ts
  src/test/terminals/codeExecution/codeExecutionManager.unit.test.ts
  src/test/terminals/codeExecution/terminalCodeExec.unit.test.ts
Labels: debt, skip package*.json

#21657 Prevent posix paths locator from crashing
  src/client/pythonEnvironments/base/locators/lowLevel/posixKnownPathsLocator.ts
Labels: debt, skip tests

#21658 Do not resolve symbolic links in posix locator if they exceed the count limit
  src/client/pythonEnvironments/base/locators/lowLevel/posixKnownPathsLocator.ts
  src/client/pythonEnvironments/common/externalDependencies.ts
  src/client/pythonEnvironments/common/posixUtils.ts
Labels: debt, skip tests

#21665 correct discovery on unittest skip at file level
  pythonFiles/tests/unittestadapter/.data/unittest_skip/unittest_skip_file.py
  pythonFiles/tests/unittestadapter/.data/unittest_skip/unittest_skip_function.py
  pythonFiles/tests/unittestadapter/expected_discovery_test_output.py
  pythonFiles/tests/unittestadapter/test_discovery.py
  pythonFiles/unittestadapter/utils.py
Labels: bug, area-testing

#21681 Ensure `Run Python in dedicated terminal` uses `python.executeInFirDir` setting
  src/client/pythonEnvironments/base/locators/lowLevel/windowsKnownPathsLocator.ts
  src/client/terminals/codeExecution/terminalCodeExecution.ts
Labels: bug, skip tests

#21678 handle skip unittest at file without error
  pythonFiles/tests/pytestadapter/.data/unittest_skiptest_file_level.py
  pythonFiles/tests/pytestadapter/expected_discovery_test_output.py
  pythonFiles/tests/pytestadapter/test_discovery.py
  pythonFiles/vscode_pytest/__init__.py
Labels: bug

#21675 Dev Container Using MCR
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  scripts/onCreateCommand.sh
  scripts/postCreateCommand.sh
  src/client/common/interpreterPathService.ts
  src/test/common/interpreterPathService.unit.test.ts
  src/test/pythonEnvironments/common/commonUtils.functional.test.ts
Labels: feature-request

#21683 Add new telemetry property to GPDR
  src/client/telemetry/pylance.ts
Labels: debt, skip tests

#21685 Edit issue-labels.yml, triage-info-needed.yml
  .github/workflows/issue-labels.yml
  .github/workflows/triage-info-needed.yml
Labels: debt

#21689 Do not show "Select at workspace level" option if only one workspace folder is opened
  src/client/interpreter/configuration/interpreterSelector/commands/base.ts
Labels: debt, skip tests

#21692 Convert JS-style typings to native TS in `@vscode/python-extension`
  pythonExtensionApi/src/main.ts
  src/client/api/types.ts
Labels: no-changelog, skip tests

#21701 Move "vscode" out of required dependencies for npm package
  pythonExtensionApi/package-lock.json
  pythonExtensionApi/package.json
Labels: no-changelog, skip tests

#21703 Update homepage for Python API package
  pythonExtensionApi/package.json
Labels: no-changelog, skip package*.json, skip tests

#21682 Make test_ids relative to workspace path not root dir
  pythonFiles/tests/pytestadapter/.data/root/tests/pytest.ini
  pythonFiles/tests/pytestadapter/.data/root/tests/test_a.py
  pythonFiles/tests/pytestadapter/.data/root/tests/test_b.py
  pythonFiles/tests/pytestadapter/expected_discovery_test_output.py
  pythonFiles/tests/pytestadapter/expected_execution_test_output.py
  pythonFiles/tests/pytestadapter/helpers.py
  pythonFiles/tests/pytestadapter/test_discovery.py
  pythonFiles/tests/pytestadapter/test_execution.py
  pythonFiles/vscode_pytest/__init__.py
Labels: bug, area-testing

#21708 Removing Jupyter Notebooks mentions from package.json
  package.json
Labels: debt, skip package*.json, documentation

#21718 add area-repl to issue label
  .github/workflows/issue-labels.yml
Labels: debt

#21667 Fix UUID and disposing
  src/client/testing/testController/common/server.ts
  src/client/testing/testController/common/types.ts
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/client/testing/testController/unittest/testDiscoveryAdapter.ts
  src/client/testing/testController/unittest/testExecutionAdapter.ts
  src/test/mocks/mockChildProcess.ts
  src/test/testing/testController/pytest/pytestDiscoveryAdapter.unit.test.ts
  src/test/testing/testController/pytest/pytestExecutionAdapter.unit.test.ts
  src/test/testing/testController/server.unit.test.ts
  src/test/testing/testController/workspaceTestAdapter.unit.test.ts
Labels: bug, area-testing
