Repository microsoft/vscode-python, pull requests merged in 2023-05, with the labels that each got.

#21152 Revert "Default to `--no-cov` when debugging pytest"
  src/client/testing/testController/pytest/runner.ts
Labels: no-changelog, skip tests

#21138 Show formatter extension install prompt and not the old prompt
  src/client/formatters/baseFormatter.ts
  src/client/providers/prompts/installFormatterPrompt.ts
Labels: bug, skip tests

#21159 Release candidate
  package-lock.json
  package.json
Labels: no-changelog

#21160 Update main to next pre-release version
  package-lock.json
  package.json
Labels: no-changelog

#21161 Update extension to node 16
  .github/workflows/build.yml
  .github/workflows/pr-check.yml
  .nvmrc
  package-lock.json
  package.json
  src/client/common/process/logger.ts
  src/client/common/process/rawProcessApis.ts
  src/test/common/installer/poetryInstaller.unit.test.ts
  src/test/common/process/proc.unit.test.ts
  src/test/proc.ts
  src/test/pythonEnvironments/base/locators/lowLevel/poetryLocator.unit.test.ts
  src/test/pythonEnvironments/common/environmentManagers/poetry.unit.test.ts
Labels: debt

#21162 Migrate azure pipelines to node 16
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
Labels: no-changelog

#21156 Fix typo in a type declaration of MultiStepInput module
  src/client/common/utils/multiStepInput.ts
Labels: debt, skip tests

#21174 Update version for release
  package-lock.json
  package.json
Labels: no-changelog

#21172 Add telemetry event when creating environment using button
  package.json
  src/client/common/constants.ts
  src/client/pythonEnvironments/creation/createEnvApi.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
Labels: no-changelog, skip package*.json, skip tests

#21026 Add some more coverage to utils functions
  src/test/common/terminals/shellDetector.unit.test.ts
  src/test/common/utils/exec.unit.test.ts
  src/test/common/utils/filesystem.unit.test.ts
  src/test/common/utils/platform.unit.test.ts
  src/test/common/utils/text.unit.test.ts
Labels: debt

#21183 Use `saveEditor` proposed API for running untitled Python files
  package.json
  src/client/common/application/types.ts
  src/client/common/application/workspace.ts
  src/client/terminals/codeExecution/helper.ts
  src/test/terminals/codeExecution/helper.test.ts
  typings/vscode-proposed/vscode.proposed.saveEditor.d.ts
Labels: debt, skip package*.json

#21180 Remove hack to check the vscode version
  package-lock.json
  package.json
  src/test/debuggerTest.ts
  src/test/multiRootTest.ts
  src/test/standardTest.ts
  src/test/utils/vscode.ts
Labels: debt, skip tests

#21178 Use actions from `vscode-github-triage-actions` in all Python automations
  .github/workflows/community-feedback-auto-comment.yml
  .github/workflows/issue-labels.yml
  .github/workflows/lock-issues.yml
  .github/workflows/pr-file-check.yml
  .github/workflows/pr-labels.yml
  .github/workflows/test-plan-item-validator.yml
  .github/workflows/triage-info-needed.yml
Labels: debt

#21202 Open separate Python terminals when running different Python files
  src/client/common/terminal/factory.ts
  src/client/terminals/codeExecution/terminalCodeExecution.ts
  src/test/common/terminals/factory.unit.test.ts
Labels: debt, skip tests

#21194 Disable "snippets" expansion in Jedi LSP
  src/client/activation/jedi/analysisOptions.ts
  src/test/activation/jedi/jediAnalysisOptions.unit.test.ts
Labels: feature-request

#21210 Add logging when interpreter path changes
  src/client/common/interpreterPathService.ts
Labels: debt, skip tests

#21223 Added option to run multiple Python files in separate terminals
  package.json
  package.nls.json
  src/client/common/constants.ts
  src/client/common/terminal/factory.ts
  src/client/common/terminal/types.ts
  src/client/telemetry/index.ts
  src/client/terminals/codeExecution/codeExecutionManager.ts
  src/client/terminals/codeExecution/terminalCodeExecution.ts
  src/client/terminals/types.ts
  src/test/common/terminals/factory.unit.test.ts
  src/test/terminals/codeExecution/codeExecutionManager.unit.test.ts
Labels: feature-request, skip package*.json

#21229 Change name of command to run Python files in separate terminals
  package.json
  package.nls.json
  src/client/common/constants.ts
Labels: no-changelog, skip package*.json, skip tests

#21157 Remove IS_WINDOWS constant in favor of PlatformService
  src/client/common/configSettings.ts
  src/client/common/platform/constants.ts
  src/client/common/platform/platformService.ts
  src/client/common/serviceRegistry.ts
  src/client/linters/pydocstyle.ts
  src/test/common/configSettings.test.ts
  src/test/serviceRegistry.ts
Labels: debt

#21232 Do not open "save as" window when running existing Python files
  src/client/common/application/types.ts
  src/client/common/application/workspace.ts
  src/client/terminals/codeExecution/helper.ts
  src/test/terminals/codeExecution/helper.test.ts
Labels: debt

#21219 Add option for pyenv interpreters when creating environments with venv
  src/client/pythonEnvironments/creation/provider/venvCreationProvider.ts
  src/client/pythonEnvironments/info/index.ts
  src/client/pythonEnvironments/legacyIOC.ts
Labels: feature-request, area-environments, skip tests

#21241 Add reload flag on fastApi provider
  src/client/debugger/extension/configuration/dynamicdebugConfigurationService.ts
  src/client/debugger/extension/configuration/providers/fastapiLaunch.ts
  src/test/debugger/extension/configuration/providers/fastapiLaunch.unit.test.ts
Labels: bug, area-debugging

#21242 revert testing to using socket
  pythonFiles/tests/pytestadapter/helpers.py
  pythonFiles/vscode_pytest/__init__.py
Labels: no-changelog

#21228 Enable debug pytest
  .vscode/launch.json
  pythonFiles/vscode_pytest/__init__.py
  src/client/testing/common/debugLauncher.ts
  src/client/testing/common/types.ts
  src/client/testing/testController/common/types.ts
  src/client/testing/testController/controller.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/client/testing/testController/workspaceTestAdapter.ts
Labels: no-changelog, skip tests

#21294 Revert "Remove hack to check the vscode version"
  package-lock.json
  package.json
  src/test/debuggerTest.ts
  src/test/multiRootTest.ts
  src/test/standardTest.ts
  src/test/utils/vscode.ts
Labels: debt, skip package*.json, skip tests

#21296 Update pyright version
  .github/workflows/build.yml
  .github/workflows/pr-check.yml
Labels: debt

#21269 allow large scale testing
  .vscode/launch.json
  pythonFiles/unittestadapter/discovery.py
  pythonFiles/unittestadapter/utils.py
  pythonFiles/vscode_pytest/run_pytest_script.py
  src/client/common/process/types.ts
  src/client/testing/testController/common/server.ts
  src/client/testing/testController/common/utils.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/client/testing/testController/workspaceTestAdapter.ts
Labels: no-changelog, skip tests

#21295 remove unneeded multiroot code
  src/client/testing/testController/controller.ts
  src/client/testing/testController/workspaceTestAdapter.ts
Labels: no-changelog, skip tests

#21299 fix debugging with new pytest run script
  src/client/common/process/internal/scripts/index.ts
  src/client/testing/common/debugLauncher.ts
  src/client/testing/common/types.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
Labels: no-changelog, skip tests

#21258 Set up testing rewrite experiment
  src/client/common/experiments/groups.ts
  src/client/testing/common/debugLauncher.ts
  src/client/testing/testController/common/utils.ts
  src/client/testing/testController/controller.ts
  src/client/testing/testController/pytest/pytestController.ts
  src/client/testing/testController/unittest/unittestController.ts
  src/test/testing/common/debugLauncher.unit.test.ts
Labels: feature-request, skip tests

#21301 allow pytest tests to handle multiple payloads
  pythonFiles/tests/pytestadapter/helpers.py
  pythonFiles/tests/pytestadapter/test_discovery.py
  pythonFiles/tests/pytestadapter/test_execution.py
Labels: debt

#21347 remove duplicates from test_ids array
  src/client/testing/testController/workspaceTestAdapter.ts
Labels: no-changelog, skip tests

#21350 Dont show command for button trigger in command pallet
  package.json
Labels: bug, skip package*.json

#21352 adding extra log messages for rewrite debugging
  src/client/testing/testController/common/server.ts
  src/client/testing/testController/controller.ts
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/client/testing/testController/unittest/testDiscoveryAdapter.ts
  src/client/testing/testController/workspaceTestAdapter.ts
Labels: debt, skip tests
