Repository microsoft/vscode-python, pull requests merged in 2023-08, with the labels that each got.

#21710 Update packages for Jedi and core python
  pythonFiles/jedilsp_requirements/requirements.txt
  requirements.txt
Labels: debt

#21727 Update version for release candidate
  package-lock.json
  package.json
Labels: no-changelog

#21728 Update main to next pre-release
  package-lock.json
  package.json
Labels: no-changelog

#21726 unittest discovery errors not displaying in test explorer
  src/client/testing/testController/common/resultResolver.ts
Labels: debt, skip tests

#21731 Remove old and unused API for Jupyter Ext
  src/client/common/installer/condaInstaller.ts
  src/client/common/installer/moduleInstaller.ts
  src/client/common/installer/productNames.ts
  src/client/common/installer/productService.ts
  src/client/common/types.ts
  src/client/jupyter/jupyterIntegration.ts
  src/test/activation/node/lspInteractiveWindowMiddlewareAddon.unit.test.ts
  src/test/common/installer/productInstaller.unit.test.ts
Labels: debt, skip tests

#21740 Update version for release
  package-lock.json
  package.json
Labels: no-changelog

#21729 Clean up smoke test requirement
  .github/actions/smoke-tests/action.yml
  build/smoke-test-requirements.txt
  scripts/onCreateCommand.sh
Labels: debt

#21668 add cwd for debugging
  src/client/testing/common/debugLauncher.ts
  src/client/testing/common/helpers.ts
  src/test/testing/common/debugLauncher.unit.test.ts
  src/test/testing/common/helpers.unit.test.ts
Labels: bug

#21741 update tests only on save with more files excluded
  src/client/testing/testController/controller.ts
Labels: bug, skip tests

#21742 revert absolute test-ids
  pythonFiles/tests/pytestadapter/.data/root/tests/pytest.ini
  pythonFiles/tests/pytestadapter/.data/root/tests/test_a.py
  pythonFiles/tests/pytestadapter/.data/root/tests/test_b.py
  pythonFiles/tests/pytestadapter/expected_discovery_test_output.py
  pythonFiles/tests/pytestadapter/expected_execution_test_output.py
  pythonFiles/tests/pytestadapter/helpers.py
  pythonFiles/tests/pytestadapter/test_discovery.py
  pythonFiles/tests/pytestadapter/test_execution.py
  pythonFiles/vscode_pytest/__init__.py
Labels: bug

#21743 Update release plan to document what to do with `main` during endgame week
  .github/release_plan.md
Labels: no-changelog, area-internal

#21750 Update package json and versions for release
  package-lock.json
  package.json
Labels: no-changelog

#21752 fix spelling for get-pip.py
  .gitignore
Labels: no-changelog

#21761 Remove private Jupyter APIs from public API types
  pythonExtensionApi/package-lock.json
  pythonExtensionApi/package.json
  src/client/api.ts
  src/client/api/types.ts
Labels: no-changelog, skip tests

#21762 revert due to buffer overflow on subprocess
  src/client/testing/testController/common/server.ts
  src/client/testing/testController/common/types.ts
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/client/testing/testController/unittest/testDiscoveryAdapter.ts
  src/client/testing/testController/unittest/testExecutionAdapter.ts
  src/test/mocks/mockChildProcess.ts
  src/test/testing/testController/pytest/pytestDiscoveryAdapter.unit.test.ts
  src/test/testing/testController/pytest/pytestExecutionAdapter.unit.test.ts
  src/test/testing/testController/server.unit.test.ts
  src/test/testing/testController/workspaceTestAdapter.unit.test.ts
Labels: bug

#21763 Use `optionalDependencies` instead of `peerDependencies` for `@vscode/python-extension` npm package
  pythonExtensionApi/package-lock.json
  pythonExtensionApi/package.json
Labels: debt, skip tests

#21764 Remove optionalDependencies from API npm package and document to install vscode types separately
  pythonExtensionApi/README.md
  pythonExtensionApi/package-lock.json
  pythonExtensionApi/package.json
Labels: debt, skip tests

#21765 Update version of npm package
  pythonExtensionApi/package-lock.json
  pythonExtensionApi/package.json
Labels: no-changelog, skip package*.json, skip tests

#21739 Add Ruff to CI
  .github/actions/lint/action.yml
  pythonFiles/installed_check.py
  pythonFiles/normalizeSelection.py
  pythonFiles/pyproject.toml
  pythonFiles/shell_exec.py
  pythonFiles/testing_tools/adapter/pytest/__init__.py
  pythonFiles/tests/pytestadapter/expected_execution_test_output.py
  pythonFiles/tests/pytestadapter/helpers.py
  pythonFiles/tests/pytestadapter/test_execution.py
  pythonFiles/tests/test_create_microvenv.py
  pythonFiles/tests/test_create_venv.py
  pythonFiles/tests/unittestadapter/.data/discovery_error/file_one.py
  pythonFiles/tests/unittestadapter/test_utils.py
  pythonFiles/unittestadapter/execution.py
  pythonFiles/unittestadapter/utils.py
  pythonFiles/vscode_datascience_helpers/tests/logParser.py
Labels: debt

#21766 Update README.md for npm package
  pythonExtensionApi/README.md
Labels: no-changelog, skip package*.json, skip tests

#21788 Use updated API to fetch scoped env collection
  package-lock.json
  package.json
  src/client/interpreter/activation/terminalEnvVarCollectionService.ts
  src/test/interpreters/activation/terminalEnvVarCollectionService.unit.test.ts
  types/vscode.proposed.envCollectionWorkspace.d.ts
Labels: debt

#21759 Consistent disposal of receivers across adapters
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/client/testing/testController/unittest/testDiscoveryAdapter.ts
  src/client/testing/testController/unittest/testExecutionAdapter.ts
Labels: bug, skip tests

#21794 Add setting to control severity of missing package diagnostic.
  package.json
  package.nls.json
  pythonFiles/installed_check.py
  pythonFiles/tests/test_installed_check.py
  src/client/pythonEnvironments/creation/common/installCheckUtils.ts
  src/test/pythonEnvironments/creation/common/installCheckUtils.unit.test.ts
Labels: feature-request, skip package*.json

#21799 Update VS Code engine
  package-lock.json
  package.json
Labels: no-changelog, skip package*.json, skip tests

#21758 add std out to subprocess to stop overflow
  pythonFiles/tests/pytestadapter/test_execution.py
  src/client/testing/testController/common/server.ts
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/test/mocks/helper.ts
  src/test/mocks/mockChildProcess.ts
Labels: bug, skip tests

#21800 Add one more property to load event
  src/client/startupTelemetry.ts
  src/client/telemetry/index.ts
Labels: no-changelog, skip tests

#21809 Add `language_server.jinja_usage` to `pylance.ts`
  src/client/telemetry/pylance.ts
Labels: no-changelog, skip tests

#21811 Fix `service.test.ts` to stop disposing of all services
  src/test/common/configuration/service.test.ts
Labels: debt

#21803 Add functional tests for test adapter
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/test/linters/lint.functional.test.ts
  src/test/testing/common/testingAdapter.test.ts
  src/testTestingRootWkspc/largeWorkspace/test_parameterized_subtest.py
  src/testTestingRootWkspc/smallWorkspace/test_simple.py
Labels: debt, area-testing

#21812 Feature branch testing overflow bug fix
  pythonFiles/tests/pytestadapter/.data/root/tests/pytest.ini
  pythonFiles/tests/pytestadapter/.data/root/tests/test_a.py
  pythonFiles/tests/pytestadapter/.data/root/tests/test_b.py
  pythonFiles/tests/pytestadapter/expected_discovery_test_output.py
  pythonFiles/tests/pytestadapter/expected_execution_test_output.py
  pythonFiles/tests/pytestadapter/helpers.py
  pythonFiles/tests/pytestadapter/test_discovery.py
  pythonFiles/tests/pytestadapter/test_execution.py
  pythonFiles/vscode_pytest/__init__.py
  src/client/testing/testController/common/server.ts
  src/client/testing/testController/common/types.ts
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/client/testing/testController/unittest/testDiscoveryAdapter.ts
  src/client/testing/testController/unittest/testExecutionAdapter.ts
  src/test/linters/lint.functional.test.ts
  src/test/mocks/helper.ts
  src/test/mocks/mockChildProcess.ts
  src/test/testing/common/testingAdapter.test.ts
  src/test/testing/testController/pytest/pytestDiscoveryAdapter.unit.test.ts
  src/test/testing/testController/pytest/pytestExecutionAdapter.unit.test.ts
  src/test/testing/testController/server.unit.test.ts
  src/test/testing/testController/workspaceTestAdapter.unit.test.ts
  src/testTestingRootWkspc/largeWorkspace/test_parameterized_subtest.py
  src/testTestingRootWkspc/smallWorkspace/test_simple.py
Labels: bug

#21802 Show notification reaffirming Python extension still handles activation when in `pythonTerminalEnvVarActivation` experiment
  src/client/activation/extensionSurvey.ts
  src/client/common/experiments/helpers.ts
  src/client/common/utils/localize.ts
  src/client/interpreter/activation/terminalEnvVarCollectionPrompt.ts
  src/client/interpreter/activation/terminalEnvVarCollectionService.ts
  src/client/interpreter/activation/types.ts
  src/client/interpreter/serviceRegistry.ts
  src/client/pythonEnvironments/info/index.ts
  src/client/telemetry/index.ts
  src/test/activation/extensionSurvey.unit.test.ts
  src/test/application/diagnostics/checks/macPythonInterpreter.unit.test.ts
  src/test/common/installer/installer.unit.test.ts
  src/test/interpreters/activation/terminalEnvVarCollectionPrompt.unit.test.ts
  src/test/interpreters/activation/terminalEnvVarCollectionService.unit.test.ts
  src/test/interpreters/virtualEnvs/virtualEnvPrompt.unit.test.ts
Labels: debt

#21814 fixing failing tests on CI
  src/test/testing/common/testingAdapter.test.ts
Labels: bug

#21804 Apply API recommendations for Create Env API
  src/client/pythonEnvironments/creation/createEnvironment.ts
  src/client/pythonEnvironments/creation/proposed.createEnvApis.ts
  src/client/pythonEnvironments/creation/provider/condaCreationProvider.ts
  src/client/pythonEnvironments/creation/provider/venvCreationProvider.ts
  src/test/pythonEnvironments/creation/provider/condaCreationProvider.unit.test.ts
  src/test/pythonEnvironments/creation/provider/venvCreationProvider.unit.test.ts
Labels: debt, area-api

#21821 fix data to string from buffer for output channel
  src/client/testing/testController/common/server.ts
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
Labels: bug, area-testing, skip tests

#21835 Set workspaceFolder in debug config before substituting command variables
  src/client/debugger/extension/configuration/resolvers/launch.ts
Labels: bug, skip tests

#21846 Wrap env collection workspace proposed APIs in `try...catch` block
  package.json
  src/client/interpreter/activation/terminalEnvVarCollectionService.ts
  src/test/interpreters/activation/terminalEnvVarCollectionService.unit.test.ts
Labels: bug, skip package*.json

#21847 Update VS Code engine
  package.json
Labels: no-changelog, skip package*.json, skip tests

#21859 remove usage of pytest CollectReport in rewrite
  pythonFiles/vscode_pytest/__init__.py
Labels: bug, area-testing

#21862 Do not filter using scheme when filtering environments
  src/client/common/utils/misc.ts
  src/client/pythonEnvironments/base/info/env.ts
Labels: bug, skip tests

#21819 Update proposed API for env collection
  package-lock.json
  package.json
  src/client/interpreter/activation/terminalEnvVarCollectionService.ts
  src/test/interpreters/activation/terminalEnvVarCollectionService.unit.test.ts
  types/vscode.proposed.envCollectionWorkspace.d.ts
Labels: no-changelog

#21829 Support for Create Env command to re-create env for venv
  src/client/common/utils/localize.ts
  src/client/pythonEnvironments/creation/common/commonUtils.ts
  src/client/pythonEnvironments/creation/provider/venvCreationProvider.ts
  src/client/pythonEnvironments/creation/provider/venvDeleteUtils.ts
  src/client/pythonEnvironments/creation/provider/venvSwitchPython.ts
  src/client/pythonEnvironments/creation/provider/venvUtils.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/test/pythonEnvironments/creation/provider/venvCreationProvider.unit.test.ts
  src/test/pythonEnvironments/creation/provider/venvDeleteUtils.unit.test.ts
  src/test/pythonEnvironments/creation/provider/venvUtils.unit.test.ts
Labels: feature-request

#21880 Activate environment when not using integrated terminal for debugging
  src/client/debugger/extension/configuration/resolvers/launch.ts
Labels: bug, skip tests

#21894 Also show interpreter in status bar when a Python related output channel is opened
  src/client/interpreter/interpreterService.ts
Labels: feature-request, skip tests

#21897 Call out that env name may not show in terminal activation notification
  src/client/common/utils/localize.ts
  src/client/interpreter/activation/terminalEnvVarCollectionPrompt.ts
  src/test/interpreters/activation/terminalEnvVarCollectionPrompt.unit.test.ts
Labels: no-changelog

#21896 Fixes from TPIs
  src/client/common/utils/localize.ts
  src/client/pythonEnvironments/creation/provider/condaCreationProvider.ts
  src/client/pythonEnvironments/creation/provider/venvCreationProvider.ts
  src/test/pythonEnvironments/creation/provider/condaCreationProvider.unit.test.ts
  src/test/pythonEnvironments/creation/provider/venvCreationProvider.unit.test.ts
Labels: bug

#21899 Also show env name for prefixed conda envs in terminal prompt
  src/client/interpreter/activation/terminalEnvVarCollectionPrompt.ts
  src/test/interpreters/activation/terminalEnvVarCollectionPrompt.unit.test.ts
Labels: no-changelog

#21900 Remove finalized api proposals from package.json
  package.json
Labels: debt, skip package*.json

#21902 Set PS1 for conda environments in non-Windows when in `pythonTerminalEnvVarActivation` experiment
  src/client/interpreter/activation/terminalEnvVarCollectionService.ts
  src/test/interpreters/activation/terminalEnvVarCollectionService.unit.test.ts
Labels: no-changelog

#21905 Apply feedback for terminal activation prompt
  src/client/interpreter/activation/terminalEnvVarCollectionPrompt.ts
  src/client/interpreter/activation/terminalEnvVarCollectionService.ts
  src/test/interpreters/activation/terminalEnvVarCollectionPrompt.unit.test.ts
  src/test/interpreters/activation/terminalEnvVarCollectionService.unit.test.ts
Labels: no-changelog
