Repository microsoft/vscode-python, pull requests merged in 2023-03, with the labels that each got.

#20772 Ensure picker returns array only if multi-select is enabled
  src/client/common/vscodeApis/windowApis.ts
  src/test/pythonEnvironments/creation/provider/condaUtils.unit.test.ts
Labels: bug

#20773 Update version for release
  package-lock.json
  package.json
Labels: no-changelog

#20778 Ensure picker returns array only if multi-select is enabled (#20772)
  src/client/common/vscodeApis/windowApis.ts
  src/test/pythonEnvironments/creation/provider/condaUtils.unit.test.ts
Labels: bug

#20781 Ensure both `python` and `pythonPath` are not set when resolving config.
  src/client/debugger/extension/configuration/resolvers/base.ts
  src/test/debugger/extension/configuration/resolvers/base.unit.test.ts
Labels: bug

#20780 Increase timeout of running `interpreterInfo.py` script on CI
  src/client/proposedApi.ts
  src/client/pythonEnvironments/base/info/interpreter.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionCache.ts
Labels: debt, skip tests

#20787 Update README.md for isort changes
  README.md
  build/license-header.txt
Labels: debt, documentation

#20788 Update description of `python.terminal.activateEnvironment` setting
  package.nls.json
Labels: debt, skip package*.json, skip tests

#20789 Improve getting started experience when starting on a fresh macOS
  src/client/common/utils/localize.ts
  src/client/interpreter/configuration/interpreterSelector/commands/installPython/installPythonViaTerminal.ts
  src/client/pythonEnvironments/base/locators/lowLevel/macDefaultLocator.ts
  src/test/configuration/interpreterSelector/commands/installPythonViaTerminal.unit.test.ts
  src/test/pythonEnvironments/base/locators/lowLevel/macDefaultLocator.unit.test.ts
Labels: debt

#20791 Fix ability to recognize extensions which access environment API
  src/client/proposedApi.ts
  src/test/proposedApi.unit.test.ts
Labels: debt

#20792 Add logging which could help indicate why `Discovering Python Interpreters...` never finishes
  src/client/pythonEnvironments/base/locators/composite/envsReducer.ts
  src/client/pythonEnvironments/base/locators/composite/envsResolver.ts
  src/client/pythonEnvironments/base/locators/lowLevel/activeStateLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/condaLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/customVirtualEnvLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/globalVirtualEnvronmentLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/microsoftStoreLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/poetryLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/posixKnownPathsLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/pyenvLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/windowsKnownPathsLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/windowsRegistryLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/workspaceVirtualEnvLocator.ts
  src/client/pythonEnvironments/common/environmentManagers/macDefault.ts
  src/client/pythonEnvironments/index.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/pythonEnvironments/base/locators/lowLevel/activestateLocator.unit.test.ts
  src/test/pythonEnvironments/base/locators/lowLevel/macDefaultLocator.unit.test.ts
  src/test/pythonEnvironments/base/locators/lowLevel/posixKnownPathsLocator.unit.test.ts
Labels: debt, skip tests

#20803 Do not use `-I` flag in case we're unable to find `encodings` module when validating python
  src/client/pythonEnvironments/base/info/environmentInfoService.ts
Labels: bug, skip tests

#20738 Add option to control if environment is selected after creation
  src/client/pythonEnvironments/creation/createEnvApi.ts
  src/client/pythonEnvironments/creation/createEnvironment.ts
  src/client/pythonEnvironments/creation/types.ts
  src/test/pythonEnvironments/creation/createEnvApi.unit.test.ts
Labels: feature-request

#20805 Set clientOS debug option
  src/client/debugger/extension/configuration/resolvers/attach.ts
  src/client/debugger/extension/configuration/resolvers/base.ts
  src/client/debugger/extension/configuration/resolvers/launch.ts
  src/test/debugger/extension/configuration/resolvers/attach.unit.test.ts
  src/test/debugger/extension/configuration/resolvers/launch.unit.test.ts
  src/test/testing/common/debugLauncher.unit.test.ts
Labels: bug, area-debugging

#20801 Cherry-Pick: Ensure both `python` and `pythonPath` are not set when resolving config
  src/client/debugger/extension/configuration/resolvers/base.ts
  src/test/debugger/extension/configuration/resolvers/base.unit.test.ts
Labels: bug

#20819 Fix typo with `clientOS`
  src/client/debugger/extension/configuration/resolvers/attach.ts
  src/client/debugger/extension/configuration/resolvers/base.ts
  src/client/debugger/extension/configuration/resolvers/launch.ts
  src/client/debugger/types.ts
Labels: no-changelog, skip tests

#20818 Cherry-pick: Set clientOS debug option
  src/client/debugger/extension/configuration/resolvers/attach.ts
  src/client/debugger/extension/configuration/resolvers/base.ts
  src/client/debugger/extension/configuration/resolvers/launch.ts
  src/client/debugger/types.ts
  src/test/debugger/extension/configuration/resolvers/attach.unit.test.ts
  src/test/debugger/extension/configuration/resolvers/launch.unit.test.ts
  src/test/testing/common/debugLauncher.unit.test.ts
Labels: bug

#20651 Add experiment to implicitly use environment variables for environment activation
  .eslintignore
  package-lock.json
  package.json
  package.nls.json
  src/client/common/application/applicationEnvironment.ts
  src/client/common/application/types.ts
  src/client/common/experiments/groups.ts
  src/client/common/experiments/helpers.ts
  src/client/common/process/logger.ts
  src/client/common/terminal/activator/index.ts
  src/client/common/terminal/shellDetectors/baseShellDetector.ts
  src/client/common/utils/localize.ts
  src/client/debugger/extension/configuration/resolvers/helper.ts
  src/client/debugger/extension/configuration/resolvers/launch.ts
  src/client/interpreter/activation/service.ts
  src/client/interpreter/activation/terminalEnvVarCollectionService.ts
  src/client/interpreter/activation/types.ts
  src/client/interpreter/contracts.ts
  src/client/interpreter/interpreterService.ts
  src/client/interpreter/serviceRegistry.ts
  src/client/jupyter/jupyterIntegration.ts
  src/client/providers/terminalProvider.ts
  src/client/pythonEnvironments/common/environmentManagers/conda.ts
  src/test/common/process/logger.unit.test.ts
  src/test/common/terminals/activator/index.unit.test.ts
  src/test/debugger/envVars.test.ts
  src/test/debugger/extension/configuration/resolvers/launch.unit.test.ts
  src/test/interpreters/activation/service.unit.test.ts
  src/test/interpreters/activation/terminalEnvVarCollectionService.unit.test.ts
  src/test/linters/lint.provider.test.ts
  src/test/providers/terminal.unit.test.ts
  src/test/testing/common/debugLauncher.unit.test.ts
  types/vscode.proposed.envShellEvent.d.ts
Labels: feature-request

#20821 Restart reason telemetry event for `pylance`
  src/client/activation/node/manager.ts
  src/client/languageServer/watcher.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
Labels: feature-request, skip tests

#20816 Expose client creation API for pylance
  src/client/activation/languageClientMiddleware.ts
  src/client/activation/node/analysisOptions.ts
  src/client/activation/node/languageClientFactory.ts
  src/client/activation/node/languageClientMiddleware.ts
  src/client/activation/node/languageServerProxy.ts
  src/client/activation/node/lspNotebooksExperiment.ts
  src/client/activation/node/pylanceApi.ts
  src/client/api.ts
  src/client/browser/extension.ts
  src/client/jupyter/jupyterIntegration.ts
  src/client/languageServer/pylanceLSExtensionManager.ts
  src/client/languageServer/watcher.ts
  src/test/activation/node/analysisOptions.unit.test.ts
  src/test/languageServer/pylanceLSExtensionManager.unit.test.ts
  src/test/languageServer/watcher.unit.test.ts
Labels: no-changelog

#20831 Fixed a bug where pylance not working on interactive window.
  src/client/activation/languageClientMiddleware.ts
  src/client/activation/node/languageClientMiddleware.ts
Labels: no-changelog, skip tests

#20833 Share output channel with pylance
  src/client/api.ts
Labels: no-changelog, skip tests

#20847 Made browser to expose pylance api.
  src/client/browser/api.ts
  src/client/browser/extension.ts
Labels: no-changelog, skip tests

#20857 Update walkthrough title
  package.json
Labels: no-changelog, skip package*.json

#20861 Show prompt asking user to install formatter extension
  package-lock.json
  src/client/common/application/commands.ts
  src/client/common/experiments/groups.ts
  src/client/common/utils/localize.ts
  src/client/common/vscodeApis/extensionsApi.ts
  src/client/common/vscodeApis/workspaceApis.ts
  src/client/extensionActivation.ts
  src/client/providers/prompts/installFormatterPrompt.ts
  src/client/providers/prompts/promptUtils.ts
  src/client/providers/prompts/types.ts
  src/test/providers/prompt/installFormatterPrompt.unit.test.ts
Labels: feature-request, skip package*.json

#20862 Ensure `resolveEnvironment` API resolves the latest details for conda envs without python
  src/client/interpreter/interpreterService.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionCache.ts
  src/test/pythonEnvironments/base/common.ts
  src/test/pythonEnvironments/base/locators/composite/envsCollectionService.unit.test.ts
  src/test/pythonEnvironments/base/locators/envTestUtils.ts
  src/test/pythonEnvironments/common/envlayouts/envsWithoutPython/condaLackingPython/bin/dummy
Labels: feature-request

#20869 Update text shown in formatter install prompt
  src/client/common/utils/localize.ts
Labels: no-changelog, skip tests

#20871 Add GDPR tag to new telemetry property
  src/client/telemetry/pylance.ts
Labels: no-changelog, skip package*.json, skip tests

#20879 Add create environment button to `requirements.txt` and `pyproject.toml` files
  package.json
  package.nls.json
  src/client/common/vscodeApis/workspaceApis.ts
  src/client/extensionActivation.ts
  src/client/pythonEnvironments/creation/provider/venvUtils.ts
  src/client/pythonEnvironments/creation/pyprojectTomlCreateEnv.ts
  src/test/pythonEnvironments/creation/pyprojectTomlCreateEnv.unit.test.ts
Labels: feature-request, skip package*.json

#20893 Share telemetry from core extension.
  src/client/api.ts
  src/client/browser/api.ts
  src/client/browser/extension.ts
  src/client/pylanceApi.ts
  src/client/telemetry/index.ts
Labels: no-changelog, skip tests

#20896 Fix title and placeholder for python selection when using create env command
  src/client/common/utils/localize.ts
  src/client/pythonEnvironments/creation/provider/venvCreationProvider.ts
Labels: bug, skip tests

#20900 Adjust a few strings that mention Python
  src/client/common/utils/localize.ts
Labels: no-changelog, skip package*.json, skip tests

#20910 Make sure we delay start pylance server
  src/client/browser/extension.ts
Labels: no-changelog, skip tests

#20922 Remove HTTP Client usage
  build/webpack/common.js
  package-lock.json
  package.json
  src/client/common/net/fileDownloader.ts
  src/client/common/net/httpClient.ts
  src/client/common/serviceRegistry.ts
  src/client/common/types.ts
  src/test/common/installer.test.ts
  src/test/common/moduleInstaller.test.ts
  src/test/common/net/fileDownloader.unit.test.ts
  src/test/common/net/httpClient.unit.test.ts
  src/test/common/serviceRegistry.unit.test.ts
  src/test/performanceTest.ts
Labels: debt

#20904 Use new formatter install prompt on missing formatter
  src/client/formatters/baseFormatter.ts
  src/client/providers/prompts/installFormatterPrompt.ts
  src/client/providers/prompts/types.ts
  src/client/providers/serviceRegistry.ts
Labels: no-changelog, skip tests

#20923 Update version of main to release candidate
  package-lock.json
  package.json
Labels: no-changelog

#20929 Update release candidate version
  package-lock.json
  package.json
Labels: no-changelog

#20928 Update main to next pre-release
  package-lock.json
  package.json
Labels: no-changelog

#20927 Add diagnostic to validate ComSpec
  src/client/application/diagnostics/checks/pythonInterpreter.ts
  src/client/application/diagnostics/constants.ts
  src/client/common/utils/localize.ts
  src/client/pythonEnvironments/info/executable.ts
  src/test/application/diagnostics/checks/pythonInterpreter.unit.test.ts
Labels: debt

#20937 Fix diagnostic to use "System32" instead of "SystemRoot"
  src/client/application/diagnostics/checks/pythonInterpreter.ts
  src/test/application/diagnostics/checks/pythonInterpreter.unit.test.ts
Labels: no-changelog

#20218 No longer install the Jupyter extension by default
  README.md
  gulpfile.js
Labels: feature-request, skip package*.json

#20623 Fix linting in APIs
  .eslintignore
  src/client/api.ts
Labels: debt, skip tests

#20946 Update note on the Jupyter extension in README
  README.md
Labels: no-changelog

#20954 Update version for stable release
  package-lock.json
  package.json
Labels: no-changelog

#20952 Do not deprecate `python.terminal.activateEnvironmentInTerminal` setting along with terminal env var experiment
  src/client/common/terminal/activator/index.ts
  src/test/common/terminals/activator/index.unit.test.ts
Labels: no-changelog

#20955 Fix running Untitled files with the play button
  src/client/terminals/codeExecution/codeExecutionManager.ts
  src/client/terminals/codeExecution/helper.ts
  src/client/terminals/types.ts
  src/test/terminals/codeExecution/helper.test.ts
Labels: bug
