Repository microsoft/vscode-python, pull requests merged in 2023-09, with the labels that each got.

#21919 Update version for release candidate
  package-lock.json
  package.json
Labels: no-changelog

#21921 Update main to next pre-release version
  package-lock.json
  package.json
Labels: no-changelog

#21920 Update paths for dependabot
  .github/dependabot.yml
Labels: no-changelog

#21918 Remove activation triggers that are handled automatically
  package.json
Labels: debt, skip package*.json

#21914 Update telemetry package
  package-lock.json
  package.json
Labels: debt

#21946 Update version for release
  package-lock.json
  package.json
Labels: no-changelog

#21948 Catch errors when looking up python binaries in a PATH
  src/client/pythonEnvironments/common/posixUtils.ts
Labels: debt, skip tests

#21953 Update Python extension API version
  pythonExtensionApi/package-lock.json
  pythonExtensionApi/package.json
Labels: debt, skip tests

#21954 Added git settings for branch name suggestion, protection, pull, and mergeEditor
  .vscode/settings.json
Labels: debt

#21947 Fix unittest subtest names that have spaces
  src/client/testing/testController/common/resultResolver.ts
  src/test/testing/testController/resultResolver.unit.test.ts
Labels: bug

#21932 incorrect print included for absolute path calculations
  pythonFiles/vscode_pytest/__init__.py
Labels: bug, regression

#21970 Do not assume casing of activated environment variables Python returns
  src/client/interpreter/activation/terminalEnvVarCollectionService.ts
Labels: debt, skip tests

#21962 Drop Python 3.7 support
  .github/actions/build-vsix/action.yml
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
  build/ci/conda_env_1.yml
  pythonFiles/jedilsp_requirements/requirements.in
  pythonFiles/jedilsp_requirements/requirements.txt
  pythonFiles/tests/test_data/missing-deps.data
  pythonFiles/tests/test_data/no-missing-deps.data
  pythonFiles/tests/test_data/pyproject-missing-deps.data
  pythonFiles/tests/test_data/pyproject-no-missing-deps.data
  requirements.txt
  scripts/onCreateCommand.sh
  src/client/pythonEnvironments/creation/provider/condaUtils.ts
  src/test/pythonEnvironments/common/envlayouts/pipenv/project1/CustomPipfileName
  src/test/pythonEnvironments/common/envlayouts/pipenv/project2/Pipfile
  src/test/pythonEnvironments/common/envlayouts/pipenv/project3/Pipfile
  src/test/pythonEnvironments/common/envlayouts/workspace/folder1/Pipfile
  src/test/pythonEnvironments/creation/installedPackagesDiagnostics.unit.test.ts
Labels: debt, dependencies

#21963 handle subprocess segfaults for testAdapters
  src/client/testing/testController/common/server.ts
  src/client/testing/testController/common/types.ts
  src/client/testing/testController/common/utils.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/client/testing/testController/unittest/testDiscoveryAdapter.ts
  src/client/testing/testController/unittest/testExecutionAdapter.ts
  src/test/testing/common/testingAdapter.test.ts
  src/testTestingRootWkspc/errorWorkspace/test_seg_fault.py
  src/testTestingRootWkspc/largeWorkspace/test_parameterized_subtest.py
Labels: bug

#21977 Add support to delete and re-create .conda environments
  src/client/common/utils/localize.ts
  src/client/pythonEnvironments/creation/common/commonUtils.ts
  src/client/pythonEnvironments/creation/provider/condaCreationProvider.ts
  src/client/pythonEnvironments/creation/provider/condaDeleteUtils.ts
  src/client/pythonEnvironments/creation/provider/condaUtils.ts
  src/test/pythonEnvironments/creation/provider/condaCreationProvider.unit.test.ts
  src/test/pythonEnvironments/creation/provider/condaDeleteUtils.unit.test.ts
  src/test/pythonEnvironments/creation/provider/condaUtils.unit.test.ts
Labels: feature-request

#21980 Fix `${command:python.interpreterPath}` in tasks.json in multiroot workspaces
  src/client/debugger/extension/configuration/launch.json/interpreterPathCommand.ts
  src/test/debugger/extension/configuration/launch.json/interpreterPathCommand.unit.test.ts
Labels: bug

#21917 Open requirement files
  src/client/common/utils/localize.ts
  src/client/common/vscodeApis/windowApis.ts
  src/client/pythonEnvironments/creation/provider/venvUtils.ts
  src/test/pythonEnvironments/creation/provider/venvUtils.unit.test.ts
Labels: feature-request

#21988 Use stdin if workspace has large number of requirements
  pythonFiles/create_venv.py
  pythonFiles/tests/test_create_venv.py
  src/client/pythonEnvironments/creation/provider/venvCreationProvider.ts
  src/test/pythonEnvironments/creation/provider/venvCreationProvider.unit.test.ts
Labels: bug

#21993 Fix bug in rawprocess where stdinStr was not passed
  src/client/common/process/rawProcessApis.ts
Labels: no-changelog, skip tests

#21997 Remove envShellEvent proposal usage
  package.json
Labels: debt, skip package*.json

#22004 Do not upper case custom env variables
  src/client/interpreter/activation/terminalEnvVarCollectionService.ts
Labels: bug, skip tests

#22001 pytest complicated parameterize test parsing
  pythonFiles/tests/pytestadapter/.data/parametrize_tests.py
  pythonFiles/tests/pytestadapter/expected_discovery_test_output.py
  pythonFiles/tests/pytestadapter/helpers.py
  pythonFiles/vscode_pytest/__init__.py
Labels: bug

#22009 Allow publish of pre-releases to VS Code stable this iteration
  package.json
Labels: no-changelog, skip package*.json

#22022 Remove repo labels corresponding to removing unrecognized label workflow
  .github/workflows/getLabels.js
  .github/workflows/issue-labels.yml
  .vscode/settings.json
Labels: debt, skip tests

#21979 Remove old linter and formatter prompts and commands
  package.json
  package.nls.json
  src/client/common/application/commands.ts
  src/client/common/constants.ts
  src/client/common/installer/productInstaller.ts
  src/client/extensionActivation.ts
  src/client/linters/errorHandlers/errorHandler.ts
  src/client/linters/errorHandlers/notInstalled.ts
  src/client/linters/errorHandlers/standard.ts
  src/client/linters/linterCommands.ts
  src/test/common/installer.test.ts
  src/test/common/installer/installer.invalidPath.unit.test.ts
  src/test/common/installer/installer.unit.test.ts
  src/test/common/installer/productInstaller.unit.test.ts
  src/test/common/installer/productPath.unit.test.ts
  src/test/common/productsToTest.ts
  src/test/linters/lint.multilinter.test.ts
  src/test/linters/linterCommands.unit.test.ts
Labels: feature-request, skip package*.json

#22030 Fix duplicate environments showing up on macOS
  src/client/pythonEnvironments/base/locators/lowLevel/globalVirtualEnvronmentLocator.ts
Labels: bug, skip tests

#22019 Update language to encourage reading "Migration to Python Tools Extensions"
  package.nls.json
Labels: bug, documentation

#22040 De-duplicate directories at the very end in Global virtual env locators
  src/client/pythonEnvironments/base/locators/lowLevel/globalVirtualEnvronmentLocator.ts
Labels: no-changelog, skip tests

#22046 Make sure `PATH` ends with a separator before prepending
  src/client/interpreter/activation/terminalEnvVarCollectionService.ts
  src/test/interpreters/activation/terminalEnvVarCollectionService.unit.test.ts
Labels: bug

#22041 Fix bugs related to discovery blocking other features
  src/client/common/utils/multiStepInput.ts
  src/client/interpreter/autoSelection/index.ts
  src/client/interpreter/configuration/interpreterSelector/commands/setInterpreter.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/test/configuration/interpreterSelector/commands/setInterpreter.unit.test.ts
Labels: bug

#22053 Respect `VIRTUAL_ENV_DISABLE_PROMPT` when activating virtual envs
  src/client/interpreter/activation/terminalEnvVarCollectionService.ts
Labels: bug, skip tests

#22054 Respect conda changeps1 config when setting PS1
  src/client/interpreter/activation/terminalEnvVarCollectionService.ts
  src/test/interpreters/activation/terminalEnvVarCollectionService.unit.test.ts
Labels: bug, skip tests

#22055 Changed order of options in Create Environment flow when .venv exists…
  src/client/pythonEnvironments/creation/provider/venvUtils.ts
Labels: feature-request, skip tests

#22058 Remove sort imports from command palette and context menu
  package.json
Labels: debt, skip package*.json, skip tests

#22062 Pytest to pytest
  src/client/common/utils/localize.ts
  src/client/testing/testController/common/utils.ts
  src/client/testing/testController/pytest/pytestController.ts
Labels: debt, skip tests

#22071 Show a prompt asking users if they want to create environment
  package.json
  package.nls.json
  src/client/common/constants.ts
  src/client/common/persistentState.ts
  src/client/common/utils/localize.ts
  src/client/debugger/extension/configuration/resolvers/launch.ts
  src/client/debugger/extension/debugCommands.ts
  src/client/extensionActivation.ts
  src/client/pythonEnvironments/creation/common/createEnvTriggerUtils.ts
  src/client/pythonEnvironments/creation/createEnvironmentTrigger.ts
  src/client/pythonEnvironments/creation/provider/venvUtils.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/client/terminals/codeExecution/codeExecutionManager.ts
  src/test/debugger/extension/configuration/resolvers/launch.unit.test.ts
  src/test/debugger/extension/debugCommands.unit.test.ts
  src/test/pythonEnvironments/creation/createEnvironmentTrigger.unit.test.ts
  src/test/terminals/codeExecution/codeExecutionManager.unit.test.ts
Labels: feature-request, skip package*.json

#22049 Add await for stdout
  src/client/testing/testController/common/server.ts
  src/client/testing/testController/common/utils.ts
  src/client/testing/testController/controller.ts
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/test/mocks/mockChildProcess.ts
  src/test/testing/common/testingPayloadsEot.test.ts
  src/test/testing/testController/pytest/pytestExecutionAdapter.unit.test.ts
  src/test/testing/testController/testCancellationRunAdapters.unit.test.ts
Labels: bug, area-testing

#22072 Explicitly continue execution after timeout on launching conda binary is reached
  src/client/pythonEnvironments/common/environmentManagers/conda.ts
Labels: bug, skip tests

#22078 Calculate PS1 instead of using PS1 returned by shell
  src/client/interpreter/activation/terminalEnvVarCollectionService.ts
  src/test/interpreters/activation/terminalEnvVarCollectionService.unit.test.ts
Labels: bug

#22082 Fix progress indicator when reactivating terminals
  src/client/interpreter/activation/terminalEnvVarCollectionService.ts
Labels: bug, skip tests

#22096 Fix "reactivating terminals..." for global interpreters
  src/client/interpreter/activation/terminalEnvVarCollectionService.ts
Labels: no-changelog, skip tests

#22069 Bump jedi-language-server and jedi
  pythonFiles/jedilsp_requirements/requirements.txt
Labels: debt

#22099 Ensure we don't show version selection when user selects useExisting
  src/client/pythonEnvironments/creation/provider/condaCreationProvider.ts
  src/test/pythonEnvironments/creation/provider/condaCreationProvider.unit.test.ts
Labels: bug

#22107 fix regex split for subtest names
  src/client/testing/testController/common/resultResolver.ts
  src/client/testing/testController/common/utils.ts
  src/test/testing/testController/utils.unit.test.ts
Labels: bug

#22105 ignore payload key-value if value is empty
  src/client/testing/testController/common/utils.ts
  src/test/testing/common/testingPayloadsEot.test.ts
  src/test/testing/testController/payloadTestCases.ts
Labels: bug

#22110 switch to verbose for raw data logs
  src/client/testing/testController/common/server.ts
Labels: debt, area-testing, skip tests

#22113 Fire active environment change event if active environment is deleted
  src/client/interpreter/interpreterService.ts
Labels: bug, skip tests

#22103 Align env type capitalization with tool recommendation
  src/client/pythonEnvironments/info/index.ts
Labels: debt, skip tests

#22115 Correct display name for env kinds
  src/client/pythonEnvironments/base/info/envKind.ts
Labels: no-changelog, skip tests

#22116 check existence of value in header before trim process json prc
  src/client/testing/testController/common/utils.ts
  src/test/testing/testController/utils.unit.test.ts
Labels: debt, area-testing, skip tests
