Repository microsoft/vscode-python, pull requests merged in 2023-04, with the labels that each got.

#20956 Auto add community feedback comment
  .github/workflows/community-feedback-auto-comment.yml
Labels: debt

#20965 Move 'Run in ...' commands to sub-menu
  package.json
  package.nls.json
Labels: debt, skip package*.json

#20980 Switch to UUID from CWD for testing
  src/client/testing/testController/common/server.ts
  src/client/testing/testController/common/types.ts
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/client/testing/testController/unittest/testDiscoveryAdapter.ts
  src/client/testing/testController/unittest/testExecutionAdapter.ts
  src/test/testing/testController/unittest/testDiscoveryAdapter.unit.test.ts
Labels: area-testing, no-changelog

#20989 fix request format unittest
  pythonFiles/unittestadapter/discovery.py
  pythonFiles/unittestadapter/execution.py
Labels: no-changelog

#20970 Automatically add and remove the "info needed" label
  .github/workflows/triage-info-needed.yml
Labels: debt

#20998 Don't show create env in diff editor
  package.json
Labels: bug, skip package*.json

#20996 Fix UUID unittest
  src/client/testing/testController/common/server.ts
  src/client/testing/testController/common/types.ts
  src/client/testing/testController/unittest/testDiscoveryAdapter.ts
  src/client/testing/testController/unittest/testExecutionAdapter.ts
  src/test/testing/testController/server.unit.test.ts
  src/test/testing/testController/unittest/testDiscoveryAdapter.unit.test.ts
Labels: area-testing, no-changelog

#20999 Don't show create env in diff editor
  package.json
Labels: bug, skip package*.json

#20985 Add `microvenv` support for non-windows platforms
  pythonFiles/create_conda.py
  pythonFiles/create_microvenv.py
  pythonFiles/create_venv.py
  pythonFiles/tests/test_create_microvenv.py
  pythonFiles/tests/test_create_venv.py
  requirements.in
  requirements.txt
  src/client/common/utils/localize.ts
  src/client/pythonEnvironments/creation/provider/venvProgressAndTelemetry.ts
  src/client/telemetry/index.ts
  src/test/pythonEnvironments/creation/provider/venvProgressAndTelemetry.unit.test.ts
Labels: feature-request

#21001 Update to latest `debugpy` version 1.6.7
  pythonFiles/install_debugpy.py
Labels: bug

#21011 Remove non-existent files from `.eslintignore`
  .eslintignore
Labels: debt

#21000 Update version for recovery release
  package-lock.json
  package.json
Labels: no-changelog

#21003 Add an automation to close issue with response if Python 2.7 was selected
  .github/workflows/python27-issue-response.yml
Labels: debt, skip tests

#20981 switch to using tcp for comm with server
  pythonFiles/unittestadapter/discovery.py
  pythonFiles/unittestadapter/execution.py
  src/client/testing/testController/common/server.ts
  src/client/testing/testController/common/utils.ts
  src/test/testing/testController/server.unit.test.ts
  src/test/testing/testController/utils.unit.test.ts
Labels: area-testing, no-changelog

#21012 fix typing to be 3.7 compatible
  pythonFiles/unittestadapter/discovery.py
  pythonFiles/unittestadapter/execution.py
Labels: debt

#21017 add tests for unittest execution adapter
  src/test/testing/testController/unittest/testExecutionAdapter.unit.test.ts
Labels: debt

#21018 Switch to List Data Structure for Checking Known UUIDs in Test Server
  src/client/testing/testController/common/server.ts
Labels: debt, skip tests

#21021 Fix info needed workflow
  .github/workflows/triage-info-needed.yml
Labels: no-changelog, skip tests

#21019 Add Testing for PytestExecutionAdapter
  src/test/testing/testController/pytest/pytestExecutionAdapter.unit.test.ts
Labels: debt

#21022 Add testing for unittest execution python logic
  pythonFiles/tests/unittestadapter/test_execution.py
  pythonFiles/unittestadapter/execution.py
Labels: debt

#21033 Fix debugging when using "internalConsole"
  src/client/common/platform/fs-paths.ts
  src/client/common/variables/environment.ts
  src/client/debugger/extension/configuration/resolvers/helper.ts
  src/test/common/variables/envVarsService.unit.test.ts
  src/test/debugger/envVars.test.ts
Labels: debt

#21035 Undo unwanted change in env var tests
  src/test/common/variables/envVarsService.unit.test.ts
Labels: no-changelog

#21037 Update packages for Component Governance
  package-lock.json
  package.json
Labels: no-changelog

#21036 Make fixes to `pythonTerminalEnvVarActivation` experiment
  src/client/common/terminal/activator/index.ts
  src/client/common/variables/environment.ts
  src/client/common/variables/types.ts
  src/client/debugger/extension/configuration/resolvers/helper.ts
  src/client/debugger/extension/configuration/resolvers/launch.ts
  src/client/interpreter/activation/terminalEnvVarCollectionService.ts
  src/test/common/terminals/activator/index.unit.test.ts
  src/test/interpreters/activation/terminalEnvVarCollectionService.unit.test.ts
Labels: bug

#21028 Expand Testing for Unittest Run in PythonFiles
  pythonFiles/tests/unittestadapter/.data/test_fail_simple.py
  pythonFiles/tests/unittestadapter/.data/test_two_classes.py
  pythonFiles/tests/unittestadapter/.data/two_patterns/pattern_a_test.py
  pythonFiles/tests/unittestadapter/.data/two_patterns/test_pattern_b.py
  pythonFiles/tests/unittestadapter/.data/unittest_folder/test_add.py
  pythonFiles/tests/unittestadapter/.data/unittest_folder/test_subtract.py
  pythonFiles/tests/unittestadapter/test_execution.py
  pythonFiles/unittestadapter/execution.py
Labels: debt

#21041 Fix for missing `pip` in codespaces with `venv`
  pythonFiles/create_microvenv.py
  pythonFiles/create_venv.py
  pythonFiles/tests/test_create_microvenv.py
  pythonFiles/tests/test_create_venv.py
  src/client/pythonEnvironments/creation/provider/venvProgressAndTelemetry.ts
Labels: no-changelog, skip tests

#21046 Remove unused bits entries from package.json
  package.json
Labels: debt, skip package*.json

#21045 Localize walkthroughs
  package.json
  package.nls.json
Labels: feature-request, skip package*.json

#20631 Edited Discovery Logic
  .vscode/launch.json
  pythonFiles/tests/pytestadapter/.data/double_nested_folder/nested_folder_one/nested_folder_two/test_nest.py
  pythonFiles/tests/pytestadapter/.data/dual_level_nested_folder/nested_folder_one/test_bottom_folder.py
  pythonFiles/tests/pytestadapter/.data/dual_level_nested_folder/test_top_folder.py
  pythonFiles/tests/pytestadapter/.data/empty_discovery.py
  pythonFiles/tests/pytestadapter/.data/error_parametrize_discovery.py
  pythonFiles/tests/pytestadapter/.data/error_syntax_discovery.txt
  pythonFiles/tests/pytestadapter/.data/parametrize_tests.py
  pythonFiles/tests/pytestadapter/.data/simple_pytest.py
  pythonFiles/tests/pytestadapter/.data/text_docstring.txt
  pythonFiles/tests/pytestadapter/.data/unittest_folder/test_add.py
  pythonFiles/tests/pytestadapter/.data/unittest_folder/test_subtract.py
  pythonFiles/tests/pytestadapter/.data/unittest_pytest_same_file.py
  pythonFiles/tests/pytestadapter/__init__.py
  pythonFiles/tests/pytestadapter/expected_discovery_test_output.py
  pythonFiles/tests/pytestadapter/helpers.py
  pythonFiles/tests/pytestadapter/test_discovery.py
  pythonFiles/vscode_pytest/__init__.py
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/client/testing/testController/unittest/testExecutionAdapter.ts
  src/test/testing/testController/pytest/pytestDiscoveryAdapter.unit.test.ts
Labels: no-changelog

#21068 Fix debugging when using "internalConsole"
  src/client/common/platform/fs-paths.ts
  src/client/common/variables/environment.ts
  src/client/debugger/extension/configuration/resolvers/helper.ts
  src/test/common/variables/envVarsService.unit.test.ts
  src/test/debugger/envVars.test.ts
Labels: bug

#21071 Attempt to fix pre-release build
  build/webpack/webpack.extension.config.js
Labels: no-changelog, skip tests

#21062 Use new logging API for python extension logger and LS logger
  src/client/activation/common/analysisOptions.ts
  src/client/activation/common/outputChannel.ts
  src/client/activation/types.ts
  src/client/common/application/applicationShell.ts
  src/client/common/application/types.ts
  src/client/common/constants.ts
  src/client/common/installer/moduleInstaller.ts
  src/client/common/process/rawProcessApis.ts
  src/client/common/process/types.ts
  src/client/common/types.ts
  src/client/extensionActivation.ts
  src/client/extensionInit.ts
  src/client/linters/errorHandlers/standard.ts
  src/client/logging/outputChannelLogger.ts
  src/client/testing/constants.ts
  src/client/testing/testController/common/server.ts
  src/client/testing/testController/controller.ts
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/client/testing/testController/pytest/runner.ts
  src/client/testing/testController/unittest/runner.ts
  src/client/testing/testController/unittest/testDiscoveryAdapter.ts
  src/client/testing/testController/unittest/testExecutionAdapter.ts
  src/test/activation/node/analysisOptions.unit.test.ts
  src/test/activation/outputChannel.unit.test.ts
  src/test/common/installer/moduleInstaller.unit.test.ts
  src/test/format/formatter.unit.test.ts
  src/test/linters/common.ts
  src/test/linters/lintengine.test.ts
  src/test/mockClasses.ts
  src/test/mocks/vsc/index.ts
  src/test/serviceRegistry.ts
  src/test/testing/common/managers/testConfigurationManager.unit.test.ts
  src/test/testing/configuration.unit.test.ts
  src/test/testing/configurationFactory.unit.test.ts
  src/test/testing/testController/unittest/testDiscoveryAdapter.unit.test.ts
  src/test/testing/testController/unittest/testExecutionAdapter.unit.test.ts
  src/test/testing/testController/workspaceTestAdapter.unit.test.ts
  src/test/vscode-mock.ts
Labels: debt

#21072 Direct users to the Jupyter extension when using Run in Interactive window
  package.json
  package.nls.json
  src/client/common/application/commands.ts
  src/client/common/application/contextKeys.ts
  src/client/common/constants.ts
  src/client/common/serviceRegistry.ts
  src/client/common/utils/localize.ts
  src/client/jupyter/jupyterIntegration.ts
  src/client/jupyter/requireJupyterPrompt.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/test/activation/node/lspInteractiveWindowMiddlewareAddon.unit.test.ts
  src/test/jupyter/requireJupyterPrompt.unit.test.ts
Labels: feature-request, skip package*.json

#21073 Add quick pick hover support to explain conda environment lacking a Python interpreter
  package.json
  src/client/common/utils/localize.ts
  src/client/interpreter/configuration/interpreterSelector/commands/setInterpreter.ts
  src/client/interpreter/configuration/types.ts
  typings/vscode-proposed/vscode.proposed.quickPickItemTooltip.d.ts
Labels: feature-request, skip package*.json, skip tests

#21053 Python test execution simple
  pythonFiles/tests/pytestadapter/.data/unittest_folder/test_subtract.py
  pythonFiles/tests/pytestadapter/expected_discovery_test_output.py
  pythonFiles/tests/pytestadapter/expected_execution_test_output.py
  pythonFiles/tests/pytestadapter/helpers.py
  pythonFiles/tests/pytestadapter/test_discovery.py
  pythonFiles/tests/pytestadapter/test_execution.py
  pythonFiles/vscode_pytest/__init__.py
Labels: no-changelog

#20912 Add black to `extensions.json`
  .vscode/extensions.json
Labels: debt, skip tests

#21081 Add unittest subtest
  pythonFiles/tests/unittestadapter/.data/test_subtest.py
  pythonFiles/tests/unittestadapter/test_execution.py
  pythonFiles/unittestadapter/execution.py
  src/client/testing/testController/workspaceTestAdapter.ts
Labels: no-changelog, skip tests

#21048 Default to `--no-cov` when debugging pytest
  src/client/testing/testController/pytest/runner.ts
Labels: feature-request, skip tests

#21074 Create environment proposed API
  src/client/environmentApi.ts
  src/client/proposedApiTypes.ts
  src/client/pythonEnvironments/creation/createEnvApi.ts
  src/client/pythonEnvironments/creation/createEnvironment.ts
  src/client/pythonEnvironments/creation/proposed.createEnvApis.ts
  src/client/pythonEnvironments/creation/provider/condaCreationProvider.ts
  src/client/pythonEnvironments/creation/provider/venvCreationProvider.ts
  src/client/pythonEnvironments/creation/types.ts
  src/test/pythonEnvironments/creation/createEnvApi.unit.test.ts
  src/test/pythonEnvironments/creation/createEnvironment.unit.test.ts
  src/test/pythonEnvironments/creation/provider/condaCreationProvider.unit.test.ts
  src/test/pythonEnvironments/creation/provider/venvCreationProvider.unit.test.ts
Labels: feature-request

#21083 Deprecate python logging level setting
  package.json
  package.nls.json
  src/client/application/diagnostics/applicationDiagnostics.ts
  src/client/common/process/pythonEnvironment.ts
  src/client/extensionActivation.ts
  src/client/interpreter/activation/service.ts
  src/client/logging/index.ts
  src/client/logging/settings.ts
  src/client/logging/types.ts
  src/client/pythonEnvironments/base/info/environmentInfoService.ts
  src/client/pythonEnvironments/base/info/interpreter.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionCache.ts
  src/client/pythonEnvironments/creation/provider/venvCreationProvider.ts
  src/client/pythonEnvironments/creation/provider/venvUtils.ts
  src/client/pythonEnvironments/info/interpreter.ts
  src/client/tensorBoard/tensorBoardSession.ts
  src/client/tensorBoard/tensorBoardSessionProvider.ts
  src/client/testing/common/testConfigurationManager.ts
  src/client/testing/testController/unittest/runner.ts
  src/test/testLogger.ts
Labels: debt, skip package*.json, skip tests

#21088 Remove Pylance auto-indent experiment code
  src/client/activation/node/analysisOptions.ts
  src/client/languageServer/pylanceLSExtensionManager.ts
  src/test/activation/node/analysisOptions.unit.test.ts
Labels: no-changelog

#21082 Overload methods testing rewrite
  src/client/testing/testController/common/types.ts
  src/client/testing/testController/controller.ts
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/client/testing/testController/workspaceTestAdapter.ts
  src/test/testing/testController/pytest/pytestDiscoveryAdapter.unit.test.ts
Labels: no-changelog

#21094 Pytest fix execution args
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
Labels: debt, skip tests

#21047 Support `pythonTerminalEnvVarActivation` experiment in multiroot workspaces
  package.json
  src/client/common/experiments/helpers.ts
  src/client/common/utils/localize.ts
  src/client/interpreter/activation/terminalEnvVarCollectionService.ts
  src/client/interpreter/serviceRegistry.ts
  src/test/interpreters/activation/terminalEnvVarCollectionService.unit.test.ts
  types/vscode.proposed.envCollectionWorkspace.d.ts
Labels: feature-request, skip package*.json

#21125 Show message in logs when `distutils` is missing.
  pythonFiles/create_venv.py
  src/client/pythonEnvironments/creation/provider/venvProgressAndTelemetry.ts
  src/client/telemetry/index.ts
Labels: no-changelog, skip tests

#21133 Add Pytest Logging On Workspace Level
  src/client/common/utils/localize.ts
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/workspaceTestAdapter.ts
Labels: no-changelog, skip tests

#21132 Ensure microvenv is added to path after selection.
  src/client/interpreter/activation/service.ts
  src/client/interpreter/activation/terminalEnvVarCollectionService.ts
  src/test/interpreters/activation/service.unit.test.ts
  src/test/interpreters/activation/terminalEnvVarCollectionService.unit.test.ts
Labels: no-changelog

#21095 Fix workspaceFolderToken -> workspaceFolder
  src/client/common/utils/localize.ts
Labels: bug, skip tests

#21135 Add GDPR classification tag for new event
  src/client/telemetry/pylance.ts
Labels: no-changelog, skip tests
