Repository microsoft/vscode-python, pull requests merged in 2024-01, with the labels that each got.

#22609 unittest: switch to using top dir since test ids are relative to it
  pythonFiles/tests/unittestadapter/.data/utils_complex_tree/__init__.py
  pythonFiles/tests/unittestadapter/.data/utils_complex_tree/test_outer_folder/__init__.py
  pythonFiles/tests/unittestadapter/.data/utils_complex_tree/test_outer_folder/test_inner_folder/__init__.py
  pythonFiles/tests/unittestadapter/.data/utils_complex_tree/test_outer_folder/test_inner_folder/test_utils_complex_tree.py
  pythonFiles/tests/unittestadapter/expected_discovery_test_output.py
  pythonFiles/tests/unittestadapter/test_discovery.py
  pythonFiles/unittestadapter/discovery.py
  pythonFiles/unittestadapter/utils.py
Labels: bug

#22714 Bring back REPL shell integration decoration for Mac and Linux
  pythonFiles/pythonrc.py
  pythonFiles/tests/test_shell_integration.py
Labels: bug, area-repl

#22713 Fix for issue with environment path and Jedi
  src/client/activation/jedi/analysisOptions.ts
  src/test/activation/jedi/jediAnalysisOptions.unit.test.ts
Labels: bug

#22734 Relax major version check for pre-releases
  build/update_ext_version.py
Labels: no-changelog

#22737 Fix version for pre-release
  package-lock.json
  package.json
Labels: no-changelog

#22738 Set debug as deprecated
  package.json
  package.nls.json
  src/client/debugger/extension/configuration/debugConfigurationService.ts
  src/client/debugger/extension/serviceRegistry.ts
  src/client/debugger/extension/types.ts
  src/client/extensionActivation.ts
  src/test/debugger/extension/configuration/debugConfigurationService.unit.test.ts
Labels: debt, area-debugging, skip package*.json

#22740 use abspath for top_level_dir for build_test_tree
  pythonFiles/tests/unittestadapter/test_discovery.py
  pythonFiles/unittestadapter/discovery.py
Labels: bug

#22746 Add create environment to select interpreter
  src/client/common/application/commands.ts
  src/client/common/constants.ts
  src/client/common/utils/localize.ts
  src/client/interpreter/configuration/interpreterSelector/commands/setInterpreter.ts
  src/client/interpreter/configuration/types.ts
  src/test/configuration/interpreterSelector/commands/setInterpreter.unit.test.ts
Labels: feature-request

#22759 Remove star from recommended
  src/client/interpreter/configuration/interpreterSelector/commands/setInterpreter.ts
  src/test/configuration/interpreterSelector/commands/setInterpreter.unit.test.ts
Labels: bug

#22760 Rename `utils` to `pvsc_utils` to prevent shadowing
  pythonFiles/tests/unittestadapter/expected_discovery_test_output.py
  pythonFiles/tests/unittestadapter/test_discovery.py
  pythonFiles/tests/unittestadapter/test_utils.py
  pythonFiles/unittestadapter/discovery.py
  pythonFiles/unittestadapter/execution.py
  pythonFiles/unittestadapter/pvsc_utils.py
Labels: bug

#22701 Show name for conda environments created in the workspace
  src/client/pythonEnvironments/base/info/env.ts
  src/test/pythonEnvironments/base/info/env.unit.test.ts
Labels: bug

#22720 Allow run recent command for REPL using shell integration
  package-lock.json
  package.json
  pythonFiles/pythonrc.py
  pythonFiles/tests/test_shell_integration.py
Labels: feature-request, area-repl

#22787 Remove unsupported proposed APIs enablement from `package.json`
  package.json
Labels: bug, skip package*.json

#22799 changes to support pytest 8
  pythonFiles/tests/pytestadapter/.data/dual_level_nested_folder/z_nested_folder_one/test_bottom_folder.py
  pythonFiles/tests/pytestadapter/expected_discovery_test_output.py
  pythonFiles/tests/pytestadapter/expected_execution_test_output.py
  pythonFiles/tests/pytestadapter/test_discovery.py
  pythonFiles/tests/pytestadapter/test_execution.py
  pythonFiles/vscode_pytest/__init__.py
Labels: bug, verification-needed, candidate

#22801 Bump-release-2024.2
  package-lock.json
  package.json
Labels: no-changelog

#22802 Revert "Bump-release-2024.2"
  package-lock.json
  package.json
Labels: no-changelog

#22804 bump release 2024.0
  package-lock.json
  package.json
Labels: no-changelog

#22805 Bump dev version 2024.1
  package-lock.json
  package.json
Labels: no-changelog

#22813 include multiple pytest versions in PR check
  .github/workflows/pr-check.yml
Labels: no-changelog
