Repository microsoft/vscode-python, pull requests merged in 2024-05, with the labels that each got.

#23315 Fix Pyenv for Codespaces
  scripts/onCreateCommand.sh
Labels: bug

#23316 Fix typo on GDPR tag
  src/client/telemetry/index.ts
Labels: no-changelog, skip tests

#23296 Update release_plan.md
  .github/release_plan.md
Labels: no-changelog

#23208 Add native locator for finding pythons
  .github/actions/build-vsix/action.yml
  .gitignore
  .vscode/settings.json
  .vscodeignore
  native_locator/Cargo.toml
  native_locator/src/conda.rs
  native_locator/src/known.rs
  native_locator/src/main.rs
  native_locator/src/messaging.rs
  noxfile.py
  package.json
  src/client/pythonEnvironments/base/locator.ts
  src/client/pythonEnvironments/base/locators/composite/resolverUtils.ts
  src/client/pythonEnvironments/base/locators/lowLevel/nativeLocator.ts
  src/client/pythonEnvironments/common/environmentManagers/conda.ts
  src/client/pythonEnvironments/index.ts
Labels: feature-request

#23339 Fix compilation error and use PathBuf::from
  native_locator/src/common_python.rs
  native_locator/src/conda.rs
  native_locator/src/known.rs
Labels: no-changelog, skip package*.json, skip tests

#23349 Conda and Known Python Tests
  .github/workflows/pr-check.yml
  native_locator/Cargo.toml
  native_locator/src/common_python.rs
  native_locator/src/conda.rs
  native_locator/src/known.rs
  native_locator/src/lib.rs
  native_locator/src/logging.rs
  native_locator/src/main.rs
  native_locator/src/messaging.rs
  native_locator/src/utils.rs
  native_locator/src/windows_python.rs
  native_locator/tests/common.rs
  native_locator/tests/common_python_test.rs
  native_locator/tests/conda_test.rs
  native_locator/tests/unix/conda/.conda/environments.txt
  native_locator/tests/unix/conda/conda
  native_locator/tests/unix/conda/envs/one/conda-meta/python-10.0.1-hdf0ec26_0_cpython.json
  native_locator/tests/unix/conda/envs/one/python
  native_locator/tests/unix/conda/envs/two/python
  native_locator/tests/unix/conda_without_envs/.conda/environments.txt
  native_locator/tests/unix/conda_without_envs/conda
  native_locator/tests/unix/known/python
  native_locator/tests/unix/known/python.version
Labels: no-changelog, skip package*.json, skip tests

#23353 Fix get-pip download where `tags` may not be available
  python_files/download_get_pip.py
Labels: bug

#23354 Fix get-pip download where `tags` may not be available (#23353)
  python_files/download_get_pip.py
Labels: bug

#23355 Fix typo in windows locator
  native_locator/src/main.rs
Labels: no-changelog, skip package*.json, skip tests

#23356 Support for pyenv locator
  native_locator/src/conda.rs
  native_locator/src/main.rs
  native_locator/src/pyenv.rs
  native_locator/src/utils.rs
Labels: no-changelog, skip package*.json, skip tests

#23357 Use enum for category
  native_locator/src/common_python.rs
  native_locator/src/conda.rs
  native_locator/src/messaging.rs
  native_locator/src/pyenv.rs
  native_locator/src/windows_python.rs
  native_locator/tests/common_python_test.rs
Labels: no-changelog, skip package*.json, skip tests

#23359 Adopt native pyenv locator in TS land
  src/client/pythonEnvironments/base/locators/lowLevel/nativeLocator.ts
  src/client/pythonEnvironments/common/environmentManagers/pyenv.ts
Labels: no-changelog, skip package*.json, skip tests

#23360 Add sysPrefixPath to native locator
  native_locator/src/common_python.rs
  native_locator/src/conda.rs
  native_locator/src/messaging.rs
  native_locator/src/pyenv.rs
  native_locator/src/windows_python.rs
  native_locator/tests/common_python_test.rs
  src/client/pythonEnvironments/base/locators/lowLevel/nativeLocator.ts
Labels: no-changelog, skip package*.json, skip tests

#23361 Fix discovery of native conda locator
  native_locator/src/conda.rs
Labels: no-changelog, skip package*.json, skip tests

#23363 Add native homebrew locator on mac
  native_locator/src/homebrew.rs
  native_locator/src/main.rs
  native_locator/src/messaging.rs
  src/client/pythonEnvironments/base/locators/lowLevel/nativeLocator.ts
Labels: no-changelog, skip package*.json, skip tests

#23364 Homebrew only on unix and not windows
  native_locator/src/main.rs
Labels: no-changelog, skip package*.json, skip tests

#23288 Show PyPi link in requirements
  src/client/activation/requirementsTxtLinkActivator.ts
  src/client/activation/serviceRegistry.ts
  src/test/activation/requirementsTxtLinkActivator.unit.test.ts
  src/test/activation/serviceRegistry.unit.test.ts
Labels: feature-request

#23368 Better py env version extraction
  .github/workflows/pr-check.yml
  native_locator/src/lib.rs
  native_locator/src/pyenv.rs
  native_locator/tests/common.rs
  native_locator/tests/pyenv_test.rs
  native_locator/tests/unix/pyenv/.pyenv/versions/3.12.1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/3.12.1a3/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/3.13-dev/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/3.9.9/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/anaconda-4.0.0/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/anaconda-4.0.0/mambaforge-4.10.1-4/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/anaconda-4.0.0/mambaforge-4.10.1-4/miniconda3-3.10-22.11.1-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/anaconda-4.0.0/mambaforge-4.10.1-4/miniconda3-3.10-22.11.1-1/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/anaconda-4.0.0/mambaforge-4.10.1-4/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/anaconda-4.0.0/miniconda3-3.10-22.11.1-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/anaconda-4.0.0/miniconda3-3.10-22.11.1-1/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/anaconda-4.0.0/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/anaconda3-2021.04/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/anaconda3-2021.04/mambaforge-4.10.1-4/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/anaconda3-2021.04/mambaforge-4.10.1-4/miniconda3-3.10-22.11.1-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/anaconda3-2021.04/mambaforge-4.10.1-4/miniconda3-3.10-22.11.1-1/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/anaconda3-2021.04/mambaforge-4.10.1-4/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/anaconda3-2021.04/miniconda3-3.10-22.11.1-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/anaconda3-2021.04/miniconda3-3.10-22.11.1-1/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/anaconda3-2021.04/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/mambaforge-4.10.1-4/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/mambaforge-4.10.1-4/miniconda3-3.10-22.11.1-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/mambaforge-4.10.1-4/miniconda3-3.10-22.11.1-1/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/mambaforge-4.10.1-4/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/mambaforge/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/mambaforge/miniconda3-3.10-22.11.1-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/mambaforge/miniconda3-3.10-22.11.1-1/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/mambaforge/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/miniconda-latest/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/miniconda-latest/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/miniconda3-3.10-22.11.1-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/miniconda3-3.10-22.11.1-1/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/miniconda3-3.10.1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/miniconda3-3.10.1/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/miniconda3-4.0.5/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/miniconda3-4.0.5/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/nogil-3.9.10/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/pypy3.10-7.3.14/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/pyston-2.3.5/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/stacklets-3.7.5/bin/python
  native_locator/tests/unix/pyenv/opt/homebrew/bin/pyenv
  native_locator/tests/unix/pyenv_without_envs/opt/homebrew/bin/pyenv
Labels: no-changelog, skip package*.json, skip tests

#23370 Fix get-pip download where `tags` may not be available
  python_files/download_get_pip.py
Labels: bug

#23371 Remove unwanted test feature
  native_locator/Cargo.toml
  native_locator/src/utils.rs
Labels: no-changelog, skip package*.json, skip tests

#23372 Support for pyenv virtual-env in native locator
  native_locator/src/messaging.rs
  native_locator/src/pyenv.rs
  native_locator/tests/common.rs
  native_locator/tests/conda_test.rs
  native_locator/tests/pyenv_test.rs
  native_locator/tests/unix/pyenv/.pyenv/versions/my-virtual-env/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/my-virtual-env/pyvenv.cfg
  src/client/pythonEnvironments/base/locators/lowLevel/nativeLocator.ts
Labels: no-changelog, skip package*.json, skip tests

#23374 Extract conda version where possible
  native_locator/src/conda.rs
Labels: no-changelog, skip package*.json, skip tests

#23375 Compute regex once in native locator
  native_locator/src/homebrew.rs
Labels: no-changelog, skip package*.json, skip tests

#23377 Strip 'envs' prefix from conda env name
  native_locator/src/conda.rs
  native_locator/tests/conda_test.rs
Labels: no-changelog, skip package*.json, skip tests

#23378 Update python env properties sent back to TS layer
  native_locator/src/common_python.rs
  native_locator/src/conda.rs
  native_locator/src/homebrew.rs
  native_locator/src/messaging.rs
  native_locator/src/pyenv.rs
  native_locator/src/windows_python.rs
  native_locator/tests/common_python_test.rs
  native_locator/tests/conda_test.rs
  native_locator/tests/pyenv_test.rs
Labels: no-changelog, skip package*.json, skip tests

#23379 Add support for pipenv environments
  native_locator/src/global_virtualenvs.rs
  native_locator/src/lib.rs
  native_locator/src/main.rs
  native_locator/src/messaging.rs
  native_locator/src/pipenv.rs
  native_locator/src/pyenv.rs
  native_locator/src/utils.rs
  native_locator/tests/common_python_test.rs
  native_locator/tests/conda_test.rs
  native_locator/tests/pyenv_test.rs
  src/client/pythonEnvironments/base/locators/lowLevel/nativeLocator.ts
Labels: no-changelog, skip package*.json, skip tests

#23383 Tweek pyenv version detection on windows
  native_locator/src/pyenv.rs
Labels: no-changelog, skip package*.json, skip tests

#23388 Support virtualenvwrapper in nativelocator
  native_locator/src/conda.rs
  native_locator/src/global_virtualenvs.rs
  native_locator/src/lib.rs
  native_locator/src/main.rs
  native_locator/src/messaging.rs
  native_locator/src/pipenv.rs
  native_locator/src/pyenv.rs
  native_locator/src/utils.rs
  native_locator/src/virtualenv.rs
  native_locator/src/virtualenvwrapper.rs
  native_locator/tests/conda_test.rs
  native_locator/tests/pyenv_test.rs
Labels: no-changelog, skip package*.json, skip tests

#23390 virtualenvwrapper support in ts layer of native locator
  native_locator/src/messaging.rs
  src/client/pythonEnvironments/base/locators/lowLevel/nativeLocator.ts
Labels: no-changelog, skip package*.json, skip tests

#23389 dont execute to console from the IW input box
  package.json
Labels: bug, skip package*.json, area-repl

#23387 Tweaks to how native finder is spawned and logging
  package.json
  package.nls.json
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
  src/client/pythonEnvironments/base/locators/lowLevel/nativeLocator.ts
  src/client/pythonEnvironments/index.ts
Labels: no-changelog, skip package*.json, skip tests

#23391 Drop jsonrpc connection after all messages are handled
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
Labels: no-changelog, skip package*.json, skip tests

#23393 Use PathBufs to avoid regular conversions
  native_locator/src/common_python.rs
  native_locator/src/conda.rs
  native_locator/src/homebrew.rs
  native_locator/src/known.rs
  native_locator/src/main.rs
  native_locator/src/messaging.rs
  native_locator/src/pipenv.rs
  native_locator/src/pyenv.rs
  native_locator/src/virtualenvwrapper.rs
  native_locator/src/windows_python.rs
  native_locator/tests/common.rs
  native_locator/tests/common_python_test.rs
  native_locator/tests/conda_test.rs
  native_locator/tests/pyenv_test.rs
Labels: no-changelog, skip package*.json, skip tests

#23394 Use structs instead of loose json in native test
  native_locator/src/conda.rs
  native_locator/tests/common.rs
  native_locator/tests/common_python_test.rs
  native_locator/tests/conda_test.rs
  native_locator/tests/pyenv_test.rs
Labels: no-changelog, skip package*.json, skip tests

#23397 Fixes `KeyError: 'params'` when running tests
  python_files/vscode_pytest/run_pytest_script.py
Labels: bug

#23395 Support venv, virtualEnv in global folders
  native_locator/src/global_virtualenvs.rs
  native_locator/src/lib.rs
  native_locator/src/main.rs
  native_locator/src/messaging.rs
  native_locator/src/pyenv.rs
  native_locator/src/utils.rs
  native_locator/src/venv.rs
  native_locator/src/virtualenv.rs
  native_locator/src/virtualenvwrapper.rs
  native_locator/tests/unix/pyenv/.pyenv/versions/anaconda-4.0.0/mambaforge-4.10.1-4/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/anaconda-4.0.0/mambaforge-4.10.1-4/miniconda3-3.10-22.11.1-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/anaconda-4.0.0/mambaforge-4.10.1-4/miniconda3-3.10-22.11.1-1/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/anaconda-4.0.0/mambaforge-4.10.1-4/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/anaconda-4.0.0/miniconda3-3.10-22.11.1-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/anaconda-4.0.0/miniconda3-3.10-22.11.1-1/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/anaconda-4.0.0/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/anaconda3-2021.04/mambaforge-4.10.1-4/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/anaconda3-2021.04/mambaforge-4.10.1-4/miniconda3-3.10-22.11.1-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/anaconda3-2021.04/mambaforge-4.10.1-4/miniconda3-3.10-22.11.1-1/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/anaconda3-2021.04/mambaforge-4.10.1-4/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/anaconda3-2021.04/miniconda3-3.10-22.11.1-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/anaconda3-2021.04/miniconda3-3.10-22.11.1-1/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/anaconda3-2021.04/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/mambaforge-4.10.1-4/miniconda3-3.10-22.11.1-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/mambaforge-4.10.1-4/miniconda3-3.10-22.11.1-1/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/mambaforge-4.10.1-4/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/mambaforge/miniconda3-3.10-22.11.1-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/mambaforge/miniconda3-3.10-22.11.1-1/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/mambaforge/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/miniconda-latest/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/miniconda3-3.10-22.11.1-1/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/miniconda3-3.10.1/miniforge3-4.11.0-1/bin/python
  native_locator/tests/unix/pyenv/.pyenv/versions/miniconda3-4.0.5/miniforge3-4.11.0-1/bin/python
Labels: no-changelog, skip package*.json, skip tests

#23404 Refactor locators to implement a specific trait
  native_locator/src/common_python.rs
  native_locator/src/conda.rs
  native_locator/src/global_virtualenvs.rs
  native_locator/src/homebrew.rs
  native_locator/src/lib.rs
  native_locator/src/locator.rs
  native_locator/src/main.rs
  native_locator/src/messaging.rs
  native_locator/src/pipenv.rs
  native_locator/src/pyenv.rs
  native_locator/src/utils.rs
  native_locator/src/venv.rs
  native_locator/src/virtualenv.rs
  native_locator/src/virtualenvwrapper.rs
  native_locator/src/windows_python.rs
  native_locator/tests/common_python_test.rs
  native_locator/tests/conda_test.rs
  native_locator/tests/pyenv_test.rs
Labels: no-changelog, skip package*.json, skip tests

#23405 Use logger formatter to send log msgs via json rpc
  native_locator/Cargo.toml
  native_locator/src/main.rs
  native_locator/src/messaging.rs
  native_locator/tests/common.rs
Labels: no-changelog, skip package*.json, skip tests

#23406 Remove duplicate environment finder event handlers
  src/client/pythonEnvironments/base/locators/lowLevel/nativeLocator.ts
Labels: no-changelog, skip package*.json, skip tests

#23407 Remove duplicates from reported envs & refactor locators
  native_locator/src/common_python.rs
  native_locator/src/conda.rs
  native_locator/src/homebrew.rs
  native_locator/src/locator.rs
  native_locator/src/main.rs
  native_locator/src/messaging.rs
  native_locator/src/pipenv.rs
  native_locator/src/pyenv.rs
  native_locator/src/venv.rs
  native_locator/src/virtualenv.rs
  native_locator/src/virtualenvwrapper.rs
  native_locator/src/windows_python.rs
  native_locator/src/windows_registry.rs
  native_locator/tests/common.rs
  native_locator/tests/common_python_test.rs
  native_locator/tests/conda_test.rs
  native_locator/tests/pyenv_test.rs
Labels: no-changelog, skip package*.json, skip tests

#23412 Replace locator enum with struct
  native_locator/src/common_python.rs
  native_locator/src/conda.rs
  native_locator/src/homebrew.rs
  native_locator/src/locator.rs
  native_locator/src/main.rs
  native_locator/src/pyenv.rs
  native_locator/src/virtualenvwrapper.rs
  native_locator/src/windows_python.rs
  native_locator/tests/common.rs
Labels: no-changelog, skip package*.json, skip tests

#23414 Look for Python (PythonCore) in windows registry
  native_locator/src/lib.rs
  native_locator/src/main.rs
  native_locator/src/messaging.rs
  native_locator/src/windows_registry.rs
  native_locator/src/windows_store.rs
Labels: no-changelog, skip package*.json, skip tests

#23415 Fix extraction of Python version for Conda environments
  native_locator/src/conda.rs
  native_locator/tests/unix/conda/envs/one/conda-meta/python-slugify-5.0.2-pyhd3eb1b0_0.json
Labels: no-changelog, skip package*.json, skip tests

#23417 Fixes to comparing of Python environments
  src/client/pythonEnvironments/base/info/env.ts
Labels: no-changelog, skip package*.json, skip tests

#23416 Revised native conda locator
  native_locator/src/common_python.rs
  native_locator/src/conda.rs
  native_locator/src/conda_old.rs
  native_locator/src/homebrew.rs
  native_locator/src/locator.rs
  native_locator/src/main.rs
  native_locator/src/messaging.rs
  native_locator/src/pipenv.rs
  native_locator/src/pyenv.rs
  native_locator/src/utils.rs
  native_locator/src/venv.rs
  native_locator/src/virtualenv.rs
  native_locator/src/virtualenvwrapper.rs
  native_locator/src/windows_registry.rs
  native_locator/src/windows_store.rs
  native_locator/tests/common_python_test.rs
  native_locator/tests/conda_test.rs
  native_locator/tests/pyenv_test.rs
  native_locator/tests/unix/conda/.conda/environments.txt
  native_locator/tests/unix/conda/anaconda3/bin/conda
  native_locator/tests/unix/conda/anaconda3/conda-meta/conda-4.0.2-pyhd3eb1b0_0.json
  native_locator/tests/unix/conda/anaconda3/conda-meta/python-10.0.1-hdf0ec26_0_cpython.json
  native_locator/tests/unix/conda/anaconda3/conda-meta/python-slugify-5.0.2-pyhd3eb1b0_0.json
  native_locator/tests/unix/conda/anaconda3/envs/one/conda-meta/python-10.0.1-hdf0ec26_0_cpython.json
  native_locator/tests/unix/conda/anaconda3/envs/one/conda-meta/python-slugify-5.0.2-pyhd3eb1b0_0.json
  native_locator/tests/unix/conda/anaconda3/envs/one/python
  native_locator/tests/unix/conda/anaconda3/envs/two/python
  native_locator/tests/unix/conda_without_envs/anaconda3/bin/conda
  native_locator/tests/unix/conda_without_envs/anaconda3/conda-meta/conda-4.0.2-pyhd3eb1b0_0.json
  native_locator/tests/unix/conda_without_envs/anaconda3/conda-meta/python-10.0.1-hdf0ec26_0_cpython.json
  native_locator/tests/unix/conda_without_envs/anaconda3/conda-meta/python-slugify-5.0.2-pyhd3eb1b0_0.json
  src/client/pythonEnvironments/base/locators/lowLevel/nativeLocator.ts
Labels: no-changelog, skip package*.json, skip tests

#23422 Fix winreg locator & add conda registry locator on windows
  native_locator/src/common_python.rs
  native_locator/src/conda.rs
  native_locator/src/conda_old.rs
  native_locator/src/homebrew.rs
  native_locator/src/main.rs
  native_locator/src/messaging.rs
  native_locator/src/pyenv.rs
  native_locator/src/venv.rs
  native_locator/src/virtualenv.rs
  native_locator/src/virtualenvwrapper.rs
  native_locator/src/windows_registry.rs
  native_locator/src/windows_store.rs
  native_locator/tests/common_python_test.rs
  native_locator/tests/conda_test.rs
  native_locator/tests/pyenv_test.rs
Labels: no-changelog, skip package*.json, skip tests

#23426 Updates to the native windows store locator
  native_locator/src/common_python.rs
  native_locator/src/windows_store.rs
Labels: no-changelog, skip package*.json, skip tests

#23425 Add more logging and some tweaks
  native_locator/Cargo.toml
  src/client/common/utils/async.ts
  src/client/pythonEnvironments/base/info/environmentInfoService.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/client/pythonEnvironments/base/locators/lowLevel/activeStateLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/condaLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/customVirtualEnvLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/globalVirtualEnvronmentLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/microsoftStoreLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/nativeLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/posixKnownPathsLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/pyenvLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/windowsKnownPathsLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/windowsRegistryLocator.ts
Labels: no-changelog, skip tests

#23427 Remove sysPrefixPath from native locator
  native_locator/src/common_python.rs
  native_locator/src/conda.rs
  native_locator/src/conda_old.rs
  native_locator/src/homebrew.rs
  native_locator/src/messaging.rs
  native_locator/src/pipenv.rs
  native_locator/src/pyenv.rs
  native_locator/src/venv.rs
  native_locator/src/virtualenv.rs
  native_locator/src/virtualenvwrapper.rs
  native_locator/src/windows_registry.rs
  native_locator/src/windows_store.rs
  native_locator/tests/common_python_test.rs
  native_locator/tests/conda_test.rs
  native_locator/tests/pyenv_test.rs
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
  src/client/pythonEnvironments/base/locators/lowLevel/nativeLocator.ts
Labels: no-changelog, skip package*.json, skip tests

#23420 Resolve bug with session not being a parent of tests while building test tree with pytest
  python_files/tests/pytestadapter/.data/config_sub_folder/config/pytest.ini
  python_files/tests/pytestadapter/.data/config_sub_folder/tests/test_hello.py
  python_files/tests/pytestadapter/test_discovery.py
  python_files/vscode_pytest/__init__.py
Labels: bug, area-testing

#23418 add sys config scripts path to test execution path
  python_files/unittestadapter/execution.py
  python_files/vscode_pytest/run_pytest_script.py
Labels: bug, skip tests

#23431 Update release plan
  .github/release_plan.md
Labels: no-changelog

#23436 Ignore native locator tests folder
  .vscodeignore
Labels: no-changelog, skip package*.json, skip tests

#23235 Add Interactive REPL Experiment
  .vscode/launch.json
  package.json
  package.nls.json
  python_files/python_server.py
  src/client/common/application/commands.ts
  src/client/common/constants.ts
  src/client/common/experiments/groups.ts
  src/client/common/types.ts
  src/client/extensionActivation.ts
  src/client/repl/pythonServer.ts
  src/client/repl/replCommands.ts
  src/client/repl/replController.ts
  src/client/terminals/codeExecution/helper.ts
  src/test/terminals/codeExecution/helper.test.ts
  src/test/terminals/codeExecution/smartSend.test.ts
Labels: feature-request, skip package*.json, area-repl

#23439 fix parameterized test duplicate function different classes
  python_files/tests/pytestadapter/.data/same_function_new_class_param.py
  python_files/tests/pytestadapter/expected_discovery_test_output.py
  python_files/tests/pytestadapter/test_discovery.py
  python_files/tests/tree_comparison_helper.py
  python_files/tests/unittestadapter/test_discovery.py
  python_files/tests/unittestadapter/test_utils.py
  python_files/vscode_pytest/__init__.py
Labels: bug, area-testing

#23443 Activate base conda envs using 'name', add env_path for homebrew
  native_locator/src/conda.rs
  native_locator/src/homebrew.rs
  native_locator/tests/conda_test.rs
Labels: no-changelog, skip package*.json, skip tests

#23444 Ensure resolvers accept data from native locators
  src/client/pythonEnvironments/base/info/env.ts
  src/client/pythonEnvironments/base/info/index.ts
  src/client/pythonEnvironments/base/locator.ts
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
  src/client/pythonEnvironments/base/locators/composite/envsResolver.ts
  src/client/pythonEnvironments/base/locators/composite/resolverUtils.ts
  src/client/pythonEnvironments/base/locators/lowLevel/nativeLocator.ts
  src/test/pythonEnvironments/base/locators/composite/envsResolver.unit.test.ts
  src/test/pythonEnvironments/base/locators/composite/resolverUtils.unit.test.ts
Labels: no-changelog, skip package*.json, skip tests

#23446 Updates to python locator
  native_locator/src/common_python.rs
  native_locator/src/conda.rs
  native_locator/src/homebrew.rs
  native_locator/src/main.rs
  native_locator/src/messaging.rs
  native_locator/src/pipenv.rs
  native_locator/src/pyenv.rs
  native_locator/src/utils.rs
  native_locator/src/venv.rs
  native_locator/src/virtualenv.rs
  native_locator/src/virtualenvwrapper.rs
  native_locator/src/windows_store.rs
  native_locator/tests/common.rs
  native_locator/tests/common_python_test.rs
  native_locator/tests/conda_test.rs
  native_locator/tests/pyenv_test.rs
Labels: no-changelog, skip package*.json, skip tests

#23465 Build rust python finder for CI and produce a package
  .github/actions/build-vsix/action.yml
  .github/workflows/pr-check.yml
  noxfile.py
  package-lock.json
  package.json
Labels: feature-request

#23471 Capture count of envs collected
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/client/pythonEnvironments/base/locators/lowLevel/nativeLocator.ts
  src/client/pythonEnvironments/index.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/test/pythonEnvironments/base/locators/composite/envsCollectionService.unit.test.ts
Labels: no-changelog, skip package*.json, skip tests

#23463 Ensure Windows Store takes precedence over Registry and fix Conda locators
  native_locator/src/common_python.rs
  native_locator/src/conda.rs
  native_locator/src/homebrew.rs
  native_locator/src/known.rs
  native_locator/src/main.rs
  native_locator/src/messaging.rs
  native_locator/src/pipenv.rs
  native_locator/src/pyenv.rs
  native_locator/src/venv.rs
  native_locator/src/virtualenv.rs
  native_locator/src/virtualenvwrapper.rs
  native_locator/src/windows_registry.rs
  native_locator/src/windows_store.rs
  native_locator/tests/common_python_test.rs
  native_locator/tests/conda_test.rs
  native_locator/tests/pyenv_test.rs
  src/client/pythonEnvironments/base/info/environmentInfoService.ts
  src/client/pythonEnvironments/base/locator.ts
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
  src/client/pythonEnvironments/base/locators/composite/envsResolver.ts
  src/client/pythonEnvironments/base/locators/composite/resolverUtils.ts
  src/client/pythonEnvironments/base/locators/lowLevel/nativeLocator.ts
Labels: no-changelog, skip package*.json, skip tests

#23470 Adding detail to create environment pip install prompt
  src/client/common/utils/localize.ts
Labels: debt, experimenting, area-editor-*, skip tests

#23483 Add flags to optimize binary size
  native_locator/Cargo.toml
Labels: no-changelog

#23486 Fx win reg locator
  native_locator/src/windows_registry.rs
Labels: no-changelog, skip package*.json, skip tests

#23490 Parallelize locating of global python environments
  native_locator/src/conda.rs
  native_locator/src/global_virtualenvs.rs
  native_locator/src/known.rs
  native_locator/src/lib.rs
  native_locator/src/main.rs
Labels: no-changelog, skip package*.json, skip tests

#23492 Ignore Win Store Python in Windows Registry search
  native_locator/src/windows_registry.rs
  native_locator/src/windows_store.rs
Labels: no-changelog, skip package*.json, skip tests

#23494 Fix build arguments to pipeline
  .github/workflows/build.yml
Labels: no-changelog

#23496 Stop creating duplicate REPL and allow new REPL instance
  src/client/repl/replCommands.ts
Labels: bug, skip tests, area-repl

#23516 Support VSC in VS Code when opening native_locator
  .vscodeignore
  native_locator/.vscode/settings.json
Labels: no-changelog, skip package*.json, skip tests

#23526 Bug: Fix python.execInREPL stealing shift+enter
  package.json
Labels: bug, skip package*.json, area-repl

#23530 Bug Fix: REPL reuse and do not overwrite Jupyter's IW title
  src/client/repl/replCommands.ts
Labels: bug, skip tests, area-repl
