Repository microsoft/vscode-python, pull requests merged in 2024-04, with the labels that each got.

#23148 revert symlink changes which switched to using argMap for testing args
  ThirdPartyNotices-Repository.txt
  src/client/testing/testController/common/utils.ts
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/test/testing/common/testingAdapter.test.ts
  src/test/testing/testController/utils.unit.test.ts
Labels: bug, area-testing

#23158 Update version for release candidate
  package-lock.json
  package.json
Labels: no-changelog

#23160 revert arg map change to remove from stable release
  ThirdPartyNotices-Repository.txt
  src/client/testing/testController/common/utils.ts
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/test/testing/common/testingAdapter.test.ts
  src/test/testing/testController/utils.unit.test.ts
Labels: no-changelog

#22954 Ensure that we check `.venv` dir not `.venv` file
  python_files/create_venv.py
  src/client/pythonEnvironments/creation/common/commonUtils.ts
  src/test/pythonEnvironments/creation/provider/commonUtils.unit.test.ts
Labels: bug

#23165 Fix python path for install checker
  src/client/extensionActivation.ts
  src/client/pythonEnvironments/creation/common/installCheckUtils.ts
  src/client/pythonEnvironments/creation/installedPackagesDiagnostic.ts
  src/client/pythonEnvironments/creation/registrations.ts
  src/test/pythonEnvironments/creation/common/installCheckUtils.unit.test.ts
  src/test/pythonEnvironments/creation/installedPackagesDiagnostics.unit.test.ts
Labels: bug

#23166 Fix check install bug when running global python
  src/client/pythonEnvironments/creation/common/installCheckUtils.ts
Labels: bug, skip tests

#23172 Use editable install only when `project` and `build-system` are present in `pyproject.toml`
  src/client/pythonEnvironments/creation/provider/venvUtils.ts
  src/test/pythonEnvironments/creation/provider/venvUtils.unit.test.ts
Labels: bug

#23171 Add `homebrew` path to `conda` search list
  src/client/pythonEnvironments/common/environmentManagers/conda.ts
  src/test/pythonEnvironments/common/environmentManagers/conda.unit.test.ts
Labels: bug

#23176 Revert "revert arg map change to remove from stable release (#23160)"
  ThirdPartyNotices-Repository.txt
  src/client/testing/testController/common/utils.ts
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/test/testing/common/testingAdapter.test.ts
  src/test/testing/testController/utils.unit.test.ts
Labels: bug

#23201 Fix duplicated venv prompt
  src/client/terminals/envCollectionActivation/service.ts
Labels: bug, area-terminal, skip tests

#23206 Fix duplicated `.venv` prompt parenthesis
  src/client/terminals/envCollectionActivation/service.ts
Labels: bug, regression, skip tests

#23207 Revert arg map handler for test arguments
  ThirdPartyNotices-Repository.txt
  src/client/testing/testController/common/utils.ts
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/test/testing/common/testingAdapter.test.ts
  src/test/testing/testController/utils.unit.test.ts
Labels: bug, regression, skip tests

#23212 Fix activated Conda Envs vars in Jupyter Ext API
  src/client/jupyter/jupyterIntegration.ts
Labels: bug, skip tests

#23220 Add missing jedi requirements file to VSIX
  .vscodeignore
Labels: bug

#23221 Update release version for recovery release
  package-lock.json
  package.json
Labels: no-changelog

#23222 Fix activated Conda Envs vars in Jupyter Ext API
  src/client/jupyter/jupyterIntegration.ts
Labels: bug, skip tests

#23210 Use `nox` for python dependency installs
  .github/actions/build-vsix/action.yml
  .github/workflows/build.yml
  .github/workflows/pr-check.yml
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
Labels: debt

#22390 Switch to using named pipes for test communication
  build/test-requirements.txt
  python_files/testing_tools/process_json_util.py
  python_files/testing_tools/socket_manager.py
  python_files/tests/pytestadapter/.data/pytest.ini
  python_files/tests/pytestadapter/helpers.py
  python_files/tests/pytestadapter/test_discovery.py
  python_files/tests/pytestadapter/test_execution.py
  python_files/tests/unittestadapter/test_discovery.py
  python_files/tests/unittestadapter/test_execution.py
  python_files/unittestadapter/discovery.py
  python_files/unittestadapter/execution.py
  python_files/unittestadapter/pvsc_utils.py
  python_files/vscode_pytest/__init__.py
  python_files/vscode_pytest/run_pytest_script.py
  src/client/common/pipes/namedPipes.ts
  src/client/testing/common/debugLauncher.ts
  src/client/testing/testController/common/resultResolver.ts
  src/client/testing/testController/common/server.ts
  src/client/testing/testController/common/types.ts
  src/client/testing/testController/common/utils.ts
  src/client/testing/testController/controller.ts
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/client/testing/testController/unittest/testDiscoveryAdapter.ts
  src/client/testing/testController/unittest/testExecutionAdapter.ts
  src/test/testing/common/testingAdapter.test.ts
  src/test/testing/common/testingPayloadsEot.test.ts
  src/test/testing/testController/payloadTestCases.ts
  src/test/testing/testController/pytest/pytestDiscoveryAdapter.unit.test.ts
  src/test/testing/testController/pytest/pytestExecutionAdapter.unit.test.ts
  src/test/testing/testController/server.unit.test.ts
  src/test/testing/testController/testCancellationRunAdapters.unit.test.ts
  src/test/testing/testController/unittest/testDiscoveryAdapter.unit.test.ts
  src/test/testing/testController/unittest/testExecutionAdapter.unit.test.ts
  src/test/testing/testController/workspaceTestAdapter.unit.test.ts
Labels: debt

#23214 Adopting Python Walkthrough edits
  package.json
  package.nls.json
Labels: debt, experimenting, area-editor-*, skip package*.json, skip tests

#23247 Trigger env creation prompt on `pip install` in terminal with global environment
  package.json
  src/client/common/experiments/groups.ts
  src/client/common/utils/localize.ts
  src/client/common/vscodeApis/windowApis.ts
  src/client/pythonEnvironments/creation/common/workspaceSelection.ts
  src/client/pythonEnvironments/creation/createEnvApi.ts
  src/client/pythonEnvironments/creation/createEnvironment.ts
  src/client/pythonEnvironments/creation/globalPipInTerminalTrigger.ts
  src/client/pythonEnvironments/creation/provider/venvCreationProvider.ts
  src/client/pythonEnvironments/creation/registrations.ts
  src/client/pythonEnvironments/creation/types.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/test/pythonEnvironments/creation/globalPipInTerminalTrigger.unit.test.ts
  types/vscode.proposed.terminalShellIntegration.d.ts
Labels: feature-request, skip package*.json

#23251 Add cred scan suppression for dist utils
  .config/CredScanSuppressions.json
Labels: no-changelog

#23252 Try a different pattern for the path
  .config/CredScanSuppressions.json
Labels: no-changelog

#23254 Try another path pattern
  .config/CredScanSuppressions.json
  .vscodeignore
Labels: no-changelog

#23255 chore: use full names for CredScan false positives
  .config/CredScanSuppressions.json
Labels: no-changelog

#23263 Add module version telemetry
  src/client/telemetry/pylance.ts
Labels: debt, skip package*.json, skip tests

#23256 Remove some unused files
  data/.vscode/settings.json
  data/test.py
  types/vscode.proposed.envCollectionOptions.d.ts
Labels: debt

#23257 support symlinks in parents of the root of the workspace
  python_files/tests/pytestadapter/test_utils.py
  python_files/vscode_pytest/__init__.py
  src/client/testing/testController/common/utils.ts
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/unittest/testExecutionAdapter.ts
  src/test/testing/common/testingAdapter.test.ts
  src/test/testing/testController/pytest/pytestDiscoveryAdapter.unit.test.ts
  src/testTestingRootWkspc/target workspace/custom_sub_folder/test_simple.py
Labels: bug

#23258 Apply feedback for the create env trigger prompts
  .vscode/launch.json
  src/client/common/utils/localize.ts
  src/client/pythonEnvironments/creation/common/createEnvTriggerUtils.ts
  src/client/pythonEnvironments/creation/createEnvironmentTrigger.ts
  src/client/pythonEnvironments/creation/globalPipInTerminalTrigger.ts
  src/test/pythonEnvironments/creation/createEnvironmentTrigger.unit.test.ts
  src/test/pythonEnvironments/creation/globalPipInTerminalTrigger.unit.test.ts
Labels: bug

#23262 Debug cancelation
  src/client/testing/common/debugLauncher.ts
  src/client/testing/testController/common/utils.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/test/testing/common/debugLauncher.unit.test.ts
  src/test/testing/common/testingAdapter.test.ts
Labels: bug

#23273 Add more command patterns for pip trigger
  src/client/pythonEnvironments/creation/globalPipInTerminalTrigger.ts
  src/test/pythonEnvironments/creation/globalPipInTerminalTrigger.unit.test.ts
Labels: bug

#23274 Cleanup `.nox` environments after build
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
Labels: debt

#23275 Fix the YML for azure build
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
Labels: no-changelog

#23301 Revert "Debug cancelation (#23262)"
  src/client/testing/common/debugLauncher.ts
  src/client/testing/testController/common/utils.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/test/testing/common/debugLauncher.unit.test.ts
  src/test/testing/common/testingAdapter.test.ts
Labels: no-changelog

#23267 support configuring experiments in workspace settings
  package.json
Labels: bug, skip package*.json

#23310 bump release 2024.6
  package-lock.json
  package.json
Labels: no-changelog

#23312 bump to dev version 2024.7
  package-lock.json
  package.json
Labels: no-changelog
