Repository microsoft/vscode-python, pull requests merged in 2024-03, with the labels that each got.

#23007 chore: add APIScan field
  build/azure-pipeline.stable.yml
Labels: no-changelog

#23010 Make `environments.known` API faster
  src/client/environmentApi.ts
  src/client/environmentKnownCache.ts
  src/test/api.functional.test.ts
  src/test/environmentApi.unit.test.ts
Labels: bug

#23011 Do not use readSync everytime telemetry is sent
  src/client/telemetry/index.ts
  src/test/telemetry/index.unit.test.ts
Labels: bug

#23024 fixes bug which stops duplicate pytest args
  src/client/testing/testController/common/utils.ts
  src/test/testing/testController/utils.unit.test.ts
Labels: bug, area-testing

#23025 Fix backed up command and false exit code
  python_files/pythonrc.py
  python_files/tests/test_shell_integration.py
Labels: bug, area-repl

#23030 Do not use worker threads to launching binaries
  src/client/pythonEnvironments/base/locators/lowLevel/condaLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/windowsRegistryLocator.ts
  src/client/pythonEnvironments/common/environmentManagers/conda.ts
  src/client/pythonEnvironments/common/externalDependencies.ts
  src/test/pythonEnvironments/base/locators/lowLevel/windowsRegistryLocator.testvirtualenvs.ts
Labels: debt

#23031 Add `server_side_request` to `telemetry\pylance.ts`
  src/client/telemetry/pylance.ts
Labels: no-changelog, skip tests

#22741 Add linting rules for ruff
  .github/actions/lint/action.yml
  python_files/installed_check.py
  python_files/pyproject.toml
  python_files/run-jedi-language-server.py
  python_files/testing_tools/adapter/util.py
  python_files/testing_tools/unittest_discovery.py
  python_files/tests/debug_adapter/test_install_debugpy.py
  python_files/tests/pytestadapter/helpers.py
  python_files/tests/pytestadapter/test_discovery.py
  python_files/tests/run_all.py
  python_files/tests/testing_tools/adapter/test_discovery.py
  python_files/tests/testing_tools/adapter/test_util.py
  python_files/tests/unittestadapter/test_discovery.py
  python_files/tests/unittestadapter/test_execution.py
  python_files/tests/unittestadapter/test_utils.py
  python_files/unittestadapter/discovery.py
  python_files/unittestadapter/execution.py
  python_files/unittestadapter/pvsc_utils.py
  python_files/visualstudio_py_testlauncher.py
  python_files/vscode_datascience_helpers/tests/logParser.py
  python_files/vscode_pytest/__init__.py
  python_files/vscode_pytest/run_pytest_script.py
Labels: debt

#23060 Move to Ruff for formatting
  .devcontainer/devcontainer.json
  .github/actions/lint/action.yml
  .vscode/extensions.json
  .vscode/settings.json
  python_files/linter.py
  python_files/normalizeSelection.py
  python_files/pyproject.toml
  python_files/testing_tools/adapter/__main__.py
  python_files/testing_tools/adapter/info.py
  python_files/testing_tools/adapter/pytest/_discovery.py
  python_files/testing_tools/adapter/pytest/_pytest_item.py
  python_files/testing_tools/adapter/report.py
  python_files/testing_tools/adapter/util.py
  python_files/testing_tools/socket_manager.py
  python_files/tests/__main__.py
  python_files/tests/debug_adapter/test_install_debugpy.py
  python_files/tests/pytestadapter/expected_discovery_test_output.py
  python_files/tests/pytestadapter/expected_execution_test_output.py
  python_files/tests/pytestadapter/helpers.py
  python_files/tests/pytestadapter/test_discovery.py
  python_files/tests/pytestadapter/test_execution.py
  python_files/tests/test_create_conda.py
  python_files/tests/test_create_venv.py
  python_files/tests/testing_tools/adapter/pytest/test_discovery.py
  python_files/tests/testing_tools/adapter/test_discovery.py
  python_files/tests/testing_tools/adapter/test_functional.py
  python_files/tests/testing_tools/adapter/test_util.py
  python_files/tests/unittestadapter/.data/two_patterns/pattern_a_test.py
  python_files/tests/unittestadapter/.data/two_patterns/test_pattern_b.py
  python_files/tests/unittestadapter/.data/unittest_folder/test_add.py
  python_files/tests/unittestadapter/.data/unittest_folder/test_subtract.py
  python_files/tests/unittestadapter/expected_discovery_test_output.py
  python_files/tests/unittestadapter/test_discovery.py
  python_files/unittestadapter/discovery.py
  python_files/unittestadapter/execution.py
  python_files/unittestadapter/pvsc_utils.py
  python_files/visualstudio_py_testlauncher.py
  python_files/vscode_datascience_helpers/tests/logParser.py
  python_files/vscode_pytest/__init__.py
  python_files/vscode_pytest/run_pytest_script.py
Labels: debt

#23063 Ignore reformatting commits in `git blame`
  .git-blame-ignore-revs
Labels: debt

#23033 Use new report issue command api
  package.json
  resources/report_issue_template.md
  resources/report_issue_user_data_template.md
  src/client/common/application/commands/reportIssueCommand.ts
  src/client/common/vscodeApis/extensionsApi.ts
  src/test/common/application/commands/issueTemplate.md
  src/test/common/application/commands/issueTemplateVenv2.md
  src/test/common/application/commands/issueUserDataTemplateVenv1.md
  src/test/common/application/commands/issueUserDataTemplateVenv2.md
  src/test/common/application/commands/reportIssueCommand.unit.test.ts
Labels: debt, skip package*.json

#23067 Take Smart Send Out of Experiment
  python_files/normalizeSelection.py
  src/client/common/experiments/groups.ts
  src/client/terminals/codeExecution/helper.ts
  src/test/terminals/codeExecution/smartSend.test.ts
Labels: feature-request, area-repl

#23075 Include windows registry perf improvement in `pythonDiscoveryUsingWorkers` experiment
  src/client/pythonEnvironments/base/locators/composite/resolverUtils.ts
  src/client/pythonEnvironments/base/locators/lowLevel/condaLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/windowsRegistryLocator.ts
  src/client/pythonEnvironments/common/environmentManagers/conda.ts
  src/client/pythonEnvironments/common/windowsUtils.ts
  src/test/pythonEnvironments/base/locators/lowLevel/condaLocator.testvirtualenvs.ts
Labels: debt

#23076 Clear duplicated environments from storage
  src/client/pythonEnvironments/index.ts
Labels: bug, skip tests

#23074 Smart Send default value should be true
  src/client/terminals/codeExecution/helper.ts
  src/test/terminals/codeExecution/helper.test.ts
Labels: feature-request, skip tests, area-repl

#22779 Add support for Hatch environments
  src/client/pythonEnvironments/base/info/envKind.ts
  src/client/pythonEnvironments/base/info/index.ts
  src/client/pythonEnvironments/base/locators/lowLevel/hatchLocator.ts
  src/client/pythonEnvironments/common/environmentManagers/hatch.ts
  src/client/pythonEnvironments/index.ts
  src/test/pythonEnvironments/base/info/envKind.unit.test.ts
  src/test/pythonEnvironments/base/locators/lowLevel/hatchLocator.unit.test.ts
  src/test/pythonEnvironments/common/environmentManagers/hatch.unit.test.ts
  src/test/pythonEnvironments/common/envlayouts/hatch/env/virtual/python/cK2g6fIm/project1/Scripts/python.exe
  src/test/pythonEnvironments/common/envlayouts/hatch/env/virtual/python/cK2g6fIm/project1/bin/python
  src/test/pythonEnvironments/common/envlayouts/hatch/env/virtual/python/cK2g6fIm/project1/pyvenv.cfg
  src/test/pythonEnvironments/common/envlayouts/hatch/env/virtual/python/q4In3tK-/project2/bin/python
  src/test/pythonEnvironments/common/envlayouts/hatch/env/virtual/python/q4In3tK-/project2/pyvenv.cfg
  src/test/pythonEnvironments/common/envlayouts/hatch/env/virtual/python/q4In3tK-/test/bin/python
  src/test/pythonEnvironments/common/envlayouts/hatch/env/virtual/python/q4In3tK-/test/pyvenv.cfg
  src/test/pythonEnvironments/common/envlayouts/hatch/project1/.gitkeep
  src/test/pythonEnvironments/common/envlayouts/hatch/project2/hatch.toml
Labels: feature-request, skip package*.json

#23080 Respect `VIRTUAL_ENV_PROMPT` when calculating PS1
  src/client/terminals/envCollectionActivation/service.ts
Labels: bug, skip tests

#23083 If type identifier for an environment is not registered, infer type from locator
  src/client/api/types.ts
  src/client/environmentApi.ts
  src/client/interpreter/configuration/environmentTypeComparer.ts
  src/client/interpreter/configuration/interpreterSelector/commands/setInterpreter.ts
  src/client/pythonEnvironments/base/locators/composite/envsResolver.ts
  src/client/pythonEnvironments/common/environmentIdentifier.ts
  src/client/pythonEnvironments/info/index.ts
  src/client/pythonEnvironments/legacyIOC.ts
Labels: bug, skip tests

#23085 Double quote value returned by `${command:python.interpreterPath}` if it contains spaces
  src/client/interpreter/interpreterPathCommand.ts
  src/test/interpreters/interpreterPathCommand.unit.test.ts
Labels: bug

#23081 Upgrade to latest prerelease LSP 3.18 (python)
  package-lock.json
  package.json
Labels: no-changelog

#23094 Select pyenv environment based on folder `.python-version` file
  src/client/interpreter/autoSelection/index.ts
  src/client/interpreter/configuration/environmentTypeComparer.ts
  src/client/interpreter/configuration/types.ts
  src/client/pythonEnvironments/common/environmentManagers/pyenv.ts
  src/test/configuration/environmentTypeComparer.unit.test.ts
Labels: feature-request, skip tests

#23103 Use random sampling for sending Python environments API telemetry
  src/client/environmentApi.ts
Labels: debt, skip tests

#23102 Auto select pipenv and poetry environments created for a workspace
  src/client/interpreter/configuration/environmentTypeComparer.ts
  src/client/interpreter/configuration/interpreterSelector/interpreterSelector.ts
  src/client/pythonEnvironments/base/info/env.ts
  src/client/pythonEnvironments/base/info/index.ts
  src/client/pythonEnvironments/base/locator.ts
  src/client/pythonEnvironments/base/locators/composite/envsReducer.ts
  src/client/pythonEnvironments/base/locators/composite/resolverUtils.ts
  src/client/pythonEnvironments/base/locators/lowLevel/globalVirtualEnvronmentLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/poetryLocator.ts
  src/client/pythonEnvironments/common/environmentManagers/pipenv.ts
  src/client/pythonEnvironments/info/index.ts
  src/test/pythonEnvironments/base/locators/composite/envsResolver.unit.test.ts
  src/test/pythonEnvironments/base/locators/envTestUtils.ts
  src/test/pythonEnvironments/base/locators/lowLevel/globalVirtualEnvironmentLocator.unit.test.ts
  src/test/pythonEnvironments/base/locators/lowLevel/poetryLocator.unit.test.ts
Labels: feature-request

#23107 Updates to walkthrough
  package.json
  package.nls.json
Labels: debt, experimenting, area-editor-*, skip package*.json, skip tests

#23112 Address localization bug in walkthrough
  package.nls.json
Labels: bug, area-editor-*, skip package*.json, skip tests

#23129 Add workaround for hatch environment discovery on Windows
  src/client/pythonEnvironments/common/environmentManagers/hatch.ts
Labels: bug, skip tests

#23132 Fix Pyenv auto-selection on MacOS
  src/client/pythonEnvironments/common/environmentManagers/pyenv.ts
Labels: no-changelog, area-environments, skip tests

#23144 Change default value of env settings
  package.json
Labels: feature-request, skip package*.json

#23099 Resolve test suite execution import errors due to path ordering
  python_files/unittestadapter/execution.py
Labels: bug

#23149 Update release_plan.md
  .github/release_plan.md
Labels: no-changelog
