Repository microsoft/vscode-python, pull requests merged in 2024-12, with the labels that each got.

#24542 Fix: Don’t use executeCommand on python sub-shell for windows.
  src/client/common/configSettings.ts
  src/client/common/pipes/namedPipes.ts
  src/client/common/platform/platformService.ts
  src/client/common/serviceRegistry.ts
  src/client/common/terminal/service.ts
  src/client/common/utils/platform.ts
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
  src/client/pythonEnvironments/base/locators/common/pythonWatcher.ts
  src/client/pythonEnvironments/common/environmentManagers/pixi.ts
  src/client/pythonEnvironments/creation/common/commonUtils.ts
  src/client/pythonEnvironments/creation/provider/venvUtils.ts
  src/test/common/configSettings.test.ts
  src/test/common/terminals/service.unit.test.ts
  src/test/pythonEnvironments/nativeAPI.unit.test.ts
  src/test/serviceRegistry.ts
Labels: bug, area-terminal

#24544 add uri for unittest subtests fix "go to test" bug
  src/client/testing/testController/common/resultResolver.ts
  src/test/testing/testController/resultResolver.unit.test.ts
Labels: bug

#24555 Fix) Prevent keyboard interrupt for Python3.13 REPL non-Windows
  src/client/common/terminal/service.ts
  src/test/common/terminals/service.unit.test.ts
Labels: bug, area-repl

#24559 Revert "Fix) Prevent keyboard interrupt for Python3.13 REPL non-Windows "
  src/client/common/terminal/service.ts
  src/test/common/terminals/service.unit.test.ts
Labels: bug

#24563 Update `main` to next pre-release
  package-lock.json
  package.json
Labels: no-changelog

#24546 Remove unused files from VSIX
  .vscodeignore
Labels: debt

#24561 Remove sourceMaps
  .eslintignore
  gulpfile.js
  package.json
  package.nls.json
  src/client/application/diagnostics/applicationDiagnostics.ts
  src/client/application/diagnostics/surceMapSupportService.ts
  src/client/application/diagnostics/types.ts
  src/client/application/serviceRegistry.ts
  src/client/common/application/commands.ts
  src/client/common/constants.ts
  src/client/common/utils/localize.ts
  src/client/extension.ts
  src/client/sourceMapSupport.ts
  src/test/application/diagnostics/applicationDiagnostics.unit.test.ts
  src/test/application/diagnostics/sourceMapSupportService.unit.test.ts
  src/test/sourceMapSupport.test.ts
  src/test/sourceMapSupport.unit.test.ts
Labels: debt, skip package*.json

#24504 Remove usage of `hash.js`
  package-lock.json
  package.json
  src/client/telemetry/importTracker.ts
Labels: debt, skip tests

#24564 Use env extension when available
  src/client/common/persistentState.ts
  src/client/common/terminal/activator/index.ts
  src/client/common/terminal/service.ts
  src/client/envExt/api.internal.ts
  src/client/envExt/api.legacy.ts
  src/client/envExt/envExtApi.ts
  src/client/envExt/types.ts
  src/client/interpreter/configuration/interpreterSelector/commands/resetInterpreter.ts
  src/client/interpreter/configuration/interpreterSelector/commands/setInterpreter.ts
  src/client/interpreter/display/index.ts
  src/client/interpreter/interpreterService.ts
  src/client/providers/terminalProvider.ts
  src/client/pythonEnvironments/creation/createEnvApi.ts
  src/client/pythonEnvironments/index.ts
  src/client/terminals/codeExecution/codeExecutionManager.ts
  src/client/terminals/envCollectionActivation/indicatorPrompt.ts
  src/client/terminals/envCollectionActivation/service.ts
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/client/testing/testController/unittest/testDiscoveryAdapter.ts
  src/client/testing/testController/unittest/testExecutionAdapter.ts
  src/test/common/terminals/activator/index.unit.test.ts
  src/test/common/terminals/service.unit.test.ts
  src/test/configuration/interpreterSelector/commands/resetInterpreter.unit.test.ts
  src/test/configuration/interpreterSelector/commands/setInterpreter.unit.test.ts
  src/test/interpreters/activation/indicatorPrompt.unit.test.ts
  src/test/interpreters/activation/terminalEnvVarCollectionService.unit.test.ts
  src/test/interpreters/display.unit.test.ts
  src/test/interpreters/interpreterService.unit.test.ts
  src/test/providers/terminal.unit.test.ts
  src/test/terminals/codeExecution/codeExecutionManager.unit.test.ts
  src/test/testing/testController/pytest/pytestDiscoveryAdapter.unit.test.ts
  src/test/testing/testController/pytest/pytestExecutionAdapter.unit.test.ts
  src/test/testing/testController/testCancellationRunAdapters.unit.test.ts
  src/test/testing/testController/unittest/testDiscoveryAdapter.unit.test.ts
  src/test/testing/testController/unittest/testExecutionAdapter.unit.test.ts
Labels: feature-request

#24574 fix typo
  schemas/conda-environment.json
Labels: debt

#24570 Issue reporter uses name and publisher id
  src/client/common/application/commands/reportIssueCommand.ts
  src/test/common/application/commands/issueUserDataTemplateVenv1.md
  src/test/common/application/commands/issueUserDataTemplateVenv2.md
  src/test/common/application/commands/reportIssueCommand.unit.test.ts
Labels: bug

#24576 Update issue-labels.yml
  .github/workflows/issue-labels.yml
Labels: debt

#24577 Removing duplicate word in settings description
  package.nls.json
Labels: debt, area-testing

#24584 Update version for release
  package-lock.json
  package.json
Labels: no-changelog

#24553 Fix for prefix conda environments
  src/client/pythonEnvironments/common/environmentManagers/conda.ts
  src/client/pythonEnvironments/nativeAPI.ts
Labels: bug, regression, skip tests

#24571 Update to latest packages
  .github/actions/smoke-tests/action.yml
  .github/workflows/build.yml
  .github/workflows/pr-check.yml
  python_files/jedilsp_requirements/requirements.in
  python_files/jedilsp_requirements/requirements.txt
  requirements.in
  requirements.txt
Labels: debt

#24588 support skip in fixture
  python_files/tests/pytestadapter/.data/skip_test_fixture.py
  python_files/tests/pytestadapter/expected_execution_test_output.py
  python_files/tests/pytestadapter/test_execution.py
  python_files/vscode_pytest/__init__.py
Labels: bug

#24596 Create commands.json
  .github/commands.json
Labels: debt

#24595 Remove support execution order from native repl
  src/client/repl/replController.ts
Labels: debt, skip tests, area-repl

#24597 add error node on errored subprocess close
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
Labels: bug, skip tests

#24611 fix read streams blocking node threads during testing
  src/client/common/pipes/namedPipes.ts
Labels: bug, skip tests

#24615 warn about month old stale PRs
  .github/workflows/stale-prs.yml
Labels: debt

#24616 Add Github action to ensure PR's have an associated issue
  .github/workflows/pr-file-check.yml
Labels: debt

#24618 endorsement_velocity_summary script
  .github/workflows/issues-summary.yml
  scripts/generate_summary.py
Labels: debt

#24619 update from v3 to v4 for github actions
  .github/actions/build-vsix/action.yml
  .github/actions/smoke-tests/action.yml
Labels: debt

#24617 cleanup eslintignore file and create cleanup script
  .eslintignore
  scripts/cleanup-eslintignore.js
Labels: debt

#24608 Fix 'coverage.exceptions.NoSource` import to fallback to previous exception path
  python_files/vscode_pytest/__init__.py
Labels: bug, skip-issue-check

#24598 make vscode-python specific
  .github/commands.json
Labels: debt

#24629 remove console. in production code
  src/client/browser/extension.ts
  src/client/common/process/worker/workerRawProcessApis.ts
  src/client/common/utils/resourceLifecycle.ts
  src/client/deprecatedProposedApi.ts
  src/client/repl/pythonServer.ts
  src/client/telemetry/index.ts
  src/client/testing/testController/common/utils.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
Labels: debt, skip tests

#24634 fix gen velocity script
  .github/workflows/gen-issue-velocity.yml
  scripts/generate_summary.py
  scripts/issue_velocity_summary_script.py
Labels: debt, skip tests, skip-issue-check

#24641 Remove dead tensorboard code
  package.json
  src/client/common/application/commands.ts
  src/client/common/configSettings.ts
  src/client/common/constants.ts
  src/client/common/experiments/groups.ts
  src/client/common/types.ts
  src/client/common/utils/localize.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/client/tensorBoard/helpers.ts
  src/client/tensorBoard/nbextensionCodeLensProvider.ts
  src/client/tensorBoard/serviceRegistry.ts
  src/client/tensorBoard/tensorBoardFileWatcher.ts
  src/client/tensorBoard/tensorBoardImportCodeLensProvider.ts
  src/client/tensorBoard/tensorBoardPrompt.ts
  src/client/tensorBoard/tensorBoardSession.ts
  src/client/tensorBoard/tensorBoardSessionProvider.ts
  src/client/tensorBoard/tensorBoardUsageTracker.ts
  src/client/tensorBoard/tensorboarExperiment.ts
  src/client/tensorBoard/tensorboardDependencyChecker.ts
  src/client/tensorBoard/tensorboardIntegration.ts
  src/client/tensorBoard/terminalWatcher.ts
  src/client/tensorBoard/types.ts
  src/test/tensorBoard/helpers.ts
  src/test/tensorBoard/nbextensionCodeLensProvider.unit.test.ts
  src/test/tensorBoard/tensorBoardFileWatcher.test.ts
  src/test/tensorBoard/tensorBoardImportCodeLensProvider.unit.test.ts
  src/test/tensorBoard/tensorBoardPrompt.unit.test.ts
  src/test/tensorBoard/tensorBoardSession.test.ts
  src/test/tensorBoard/tensorBoardUsageTracker.unit.test.ts
Labels: debt, skip package*.json

#24651 Update version for recovery release
  package-lock.json
  package.json
Labels: no-changelog
