Repository microsoft/vscode-python, pull requests merged in 2024-11, with the labels that each got.

#24384 add python.testing.cwd to pytest discovery if present
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/test/testing/testController/pytest/pytestDiscoveryAdapter.unit.test.ts
Labels: bug, area-testing

#24385 error msg for adapter unalignment issue
  src/client/testing/testController/controller.ts
  src/client/testing/testController/workspaceTestAdapter.ts
Labels: bug, area-testing, skip tests

#24387 Update version for recovery release
  package-lock.json
  package.json
Labels: no-changelog

#24386 dont automatically inject PYTHONSTARTUP (#24346)
  src/client/common/terminal/service.ts
  src/client/common/terminal/syncTerminalService.ts
  src/client/common/terminal/types.ts
  src/test/common/terminals/helper.unit.test.ts
  src/test/smoke/smartSend.smoke.test.ts
  src/test/smokeTest.ts
Labels: bug, area-terminal

#24400 add support for pytest describe
  build/test-requirements.txt
  python_files/tests/pytestadapter/.data/pytest_describe_plugin/describe_only.py
  python_files/tests/pytestadapter/.data/pytest_describe_plugin/nested_describe.py
  python_files/tests/pytestadapter/expected_discovery_test_output.py
  python_files/tests/pytestadapter/expected_execution_test_output.py
  python_files/tests/pytestadapter/test_discovery.py
  python_files/tests/pytestadapter/test_execution.py
  python_files/vscode_pytest/__init__.py
Labels: feature-request

#24401 add bracketed paste mode for Python3.13 and above
  python_files/normalizeSelection.py
  src/client/terminals/codeExecution/helper.ts
  src/test/terminals/codeExecution/helper.test.ts
Labels: bug, area-repl

#24343 Switch testing communication to `fifo` on linux/mac
  noxfile.py
  python_files/testing_tools/socket_manager.py
  python_files/tests/pytestadapter/helpers.py
  python_files/unittestadapter/pvsc_utils.py
  python_files/vscode_pytest/__init__.py
  python_files/vscode_pytest/_common.py
  requirements.in
  src/client/common/pipes/namedPipes.ts
  src/client/testing/testController/common/utils.ts
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/client/testing/testController/unittest/testDiscoveryAdapter.ts
  src/client/testing/testController/unittest/testExecutionAdapter.ts
  src/test/testing/common/testingAdapter.test.ts
  src/test/testing/testController/pytest/pytestDiscoveryAdapter.unit.test.ts
  src/test/testing/testController/pytest/pytestExecutionAdapter.unit.test.ts
  src/test/testing/testController/testCancellationRunAdapters.unit.test.ts
  src/test/testing/testController/unittest/testDiscoveryAdapter.unit.test.ts
  src/test/testing/testController/unittest/testExecutionAdapter.unit.test.ts
  src/testTestingRootWkspc/errorWorkspace/test_seg_fault.py
Labels: bug

#24419 Remove `debugpy` from `requirements`
  requirements.in
Labels: no-changelog

#24418 do not use shell integration for Python subshell if Python setting is disabled
  src/client/common/terminal/service.ts
  src/client/common/terminal/syncTerminalService.ts
  src/client/common/terminal/types.ts
  src/client/terminals/codeExecution/terminalCodeExecution.ts
  src/test/common/terminals/service.unit.test.ts
  src/test/terminals/codeExecution/terminalCodeExec.unit.test.ts
Labels: bug, area-terminal

#24420 Keep focus on editor when executing to native REPL
  src/client/repl/replCommandHandler.ts
Labels: bug, skip tests, area-repl

#24429 Fix for running `pet` only in trusted workspaces
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
Labels: bug, skip tests

#24430 Update main version to next pre-release
  package-lock.json
  package.json
Labels: no-changelog

#24421 Add needs to CI coverage check
  .github/workflows/pr-check.yml
Labels: debt

#24432 Ensure native finder is disposed correctly
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
  src/client/pythonEnvironments/index.ts
Labels: debt, skip tests

#24433 Do not use bracketed paste mode for native repl
  src/client/repl/replCommands.ts
  src/client/repl/types.ts
  src/client/terminals/codeExecution/codeExecutionManager.ts
  src/client/terminals/codeExecution/helper.ts
  src/client/terminals/types.ts
  src/test/terminals/codeExecution/helper.test.ts
  src/test/terminals/codeExecution/smartSend.test.ts
Labels: bug, area-repl

#24412 Set Insiders target population as VS Code Insiders for ExP
  src/client/common/experiments/service.ts
  src/test/common/experiments/service.unit.test.ts
Labels: debt

#24440 enable send to native REPL for SR users
  package.json
Labels: feature-request, skip package*.json, area-repl

#24441 handle NoSource exception for coverage
  python_files/vscode_pytest/__init__.py
Labels: bug, area-testing

#24438 fix debug restart
  src/client/common/application/debugService.ts
  src/client/testing/common/debugLauncher.ts
  src/client/testing/common/types.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/client/testing/testController/unittest/testExecutionAdapter.ts
  src/test/testing/common/debugLauncher.unit.test.ts
  src/test/testing/testController/pytest/pytestExecutionAdapter.unit.test.ts
  src/test/testing/testController/testCancellationRunAdapters.unit.test.ts
  src/test/testing/testController/unittest/testExecutionAdapter.unit.test.ts
Labels: bug

#24446 disable python shell integration for wsl
  python_files/pythonrc.py
  python_files/tests/test_shell_integration.py
Labels: bug, area-terminal, area-repl

#24450 Fix bad GDPR annotations
  src/client/telemetry/pylance.ts
Labels: no-changelog, skip package*.json, skip tests

#24465 dont execute from outside the REPL
  package.json
Labels: bug, skip package*.json, skip tests, area-repl

#24431 Remove `conda` specific telemetry
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/client/pythonEnvironments/index.ts
  src/test/pythonEnvironments/base/locators/composite/envsCollectionService.unit.test.ts
Labels: bug

#24148 Handle reloading of REPL Window
  src/client/repl/nativeRepl.ts
  src/client/repl/replCommandHandler.ts
  src/client/repl/replCommands.ts
  src/client/repl/replUtils.ts
  src/test/repl/nativeRepl.test.ts
  src/test/repl/replCommand.test.ts
Labels: bug, area-repl

#24488 ruff 0.8.0 fixes
  python_files/create_conda.py
  python_files/create_microvenv.py
  python_files/create_venv.py
  python_files/installed_check.py
  python_files/normalizeSelection.py
  python_files/python_server.py
  python_files/testing_tools/process_json_util.py
  python_files/tests/pytestadapter/helpers.py
  python_files/tests/pytestadapter/test_discovery.py
  python_files/tests/pytestadapter/test_execution.py
  python_files/tests/test_installed_check.py
  python_files/tests/unittestadapter/test_discovery.py
  python_files/tests/unittestadapter/test_execution.py
  python_files/unittestadapter/discovery.py
  python_files/unittestadapter/django_handler.py
  python_files/unittestadapter/execution.py
  python_files/unittestadapter/pvsc_utils.py
  python_files/visualstudio_py_testlauncher.py
  python_files/vscode_pytest/__init__.py
Labels: debt

#24484 Pin ruff to specific version
  .github/actions/lint/action.yml
Labels: bug

#24489 Revert "ruff 0.8.0 fixes"
  python_files/create_conda.py
  python_files/create_microvenv.py
  python_files/create_venv.py
  python_files/installed_check.py
  python_files/normalizeSelection.py
  python_files/python_server.py
  python_files/testing_tools/process_json_util.py
  python_files/tests/pytestadapter/helpers.py
  python_files/tests/pytestadapter/test_discovery.py
  python_files/tests/pytestadapter/test_execution.py
  python_files/tests/test_installed_check.py
  python_files/tests/unittestadapter/test_discovery.py
  python_files/tests/unittestadapter/test_execution.py
  python_files/unittestadapter/discovery.py
  python_files/unittestadapter/django_handler.py
  python_files/unittestadapter/execution.py
  python_files/unittestadapter/pvsc_utils.py
  python_files/visualstudio_py_testlauncher.py
  python_files/vscode_pytest/__init__.py
Labels: no-changelog

#24442 Add native Pixi locator
  src/client/pythonEnvironments/base/locators/common/nativePythonTelemetry.ts
  src/client/pythonEnvironments/base/locators/common/nativePythonUtils.ts
  src/client/telemetry/index.ts
Labels: feature-request, skip tests

#24492 Support ruff `0.8.0` by setting ruff `target-version` to `py38`
  .github/actions/lint/action.yml
  python_files/pyproject.toml
  python_files/visualstudio_py_testlauncher.py
Labels: debt

#24480 Fix the wrong Content-Length in python-server.py for non-ascii characters.
  python_files/python_server.py
Labels: bug

#24487 printEnvVariablesToFile.py overwrites itself if invoked without arguments
  python_files/printEnvVariablesToFile.py
Labels: bug

#24494 chore: remove needsTools parameter
  build/azure-pipeline.stable.yml
Labels: debt

#24495 chore: remove needsTools param
  .github/actions/lint/action.yml
  build/azure-pipeline.stable.yml
Labels: debt

#24496 chore: register dependent pipeline for APIScan
  build/azure-pipeline.stable.yml
Labels: debt

#24497 chore: register dependent pipeline for APIScan
  build/azure-pipeline.stable.yml
Labels: debt
