Repository microsoft/vscode-python, pull requests merged in 2024-09, with the labels that each got.

#24040 Version updates for Python Extension Release 2024.14.0
  build/azure-pipeline.stable.yml
  package-lock.json
  package.json
Labels: no-changelog

#24043 Update `main` to next pre-release version
  package-lock.json
  package.json
Labels: no-changelog

#24019 fix django manage.py path validation
  python_files/unittestadapter/django_handler.py
Labels: bug, skip tests

#24049 Fix failing multiroot test
  .vscode/launch.json
  src/test/common/variables/envVarsProvider.multiroot.test.ts
Labels: area-testing, no-changelog

#24045 fix django manage.py path validation (#24019)
  python_files/unittestadapter/django_handler.py
Labels: bug, skip tests

#24051 Remove use of mocked output channel in virtual workspace
  src/client/extensionInit.ts
Labels: bug, skip tests

#24056 Remove use of mocked output channel in virtual workspace (#24051)
  src/client/extensionInit.ts
Labels: bug, skip tests

#24059 Update extension version for release
  .github/actions/lint/action.yml
  package-lock.json
  package.json
Labels: no-changelog

#24054 switch to using temp file for test_ids
  python_files/tests/unittestadapter/conftest.py
  python_files/unittestadapter/execution.py
  python_files/vscode_pytest/run_pytest_script.py
  src/client/testing/testController/common/utils.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/client/testing/testController/unittest/testExecutionAdapter.ts
  src/test/testing/testController/pytest/pytestExecutionAdapter.unit.test.ts
  src/test/testing/testController/testCancellationRunAdapters.unit.test.ts
  src/test/testing/testController/unittest/testExecutionAdapter.unit.test.ts
Labels: bug

#24052 Download `pet` from azure pipeline build
  build/azure-pipeline.pre-release.yml
Labels: debt

#24060 Better messaging for tests output in virtual or untrusted scenario
  src/client/common/vscodeApis/workspaceApis.ts
  src/client/extensionInit.ts
Labels: debt, skip tests

#24063 Stable extension builds using `pet` from Azure Feed
  build/azure-pipeline.stable.yml
  noxfile.py
Labels: debt

#24065 Update engine version to match LSP client
  package-lock.json
  package.json
Labels: no-changelog

#24079 Update engine version to match LSP client
  package-lock.json
  package.json
Labels: bug

#24080 Update version for recovery release
  package-lock.json
  package.json
Labels: no-changelog

#24096 Revert "Do not truncate whitespace for multi-line string"
  python_files/normalizeSelection.py
  src/test/python_files/terminalExec/sample2_normalized_selection.py
  src/test/python_files/terminalExec/sample2_raw.py
Labels: bug, area-repl

#24099 Revert "Do not truncate whitespace for multi-line string" (#24096)
  python_files/normalizeSelection.py
  src/test/python_files/terminalExec/sample2_normalized_selection.py
  src/test/python_files/terminalExec/sample2_raw.py
Labels: bug, area-repl

#24078 Switch over to executeCommand from sendText
  .github/actions/smoke-tests/action.yml
  package-lock.json
  package.json
  src/client/common/application/terminalManager.ts
  src/client/common/application/types.ts
  src/client/common/terminal/service.ts
  src/client/common/terminal/syncTerminalService.ts
  src/client/common/terminal/types.ts
  src/client/terminals/codeExecution/terminalCodeExecution.ts
  src/test/common/terminals/service.unit.test.ts
  src/test/interpreters/activation/terminalEnvVarCollectionService.unit.test.ts
  src/test/mocks/vsc/index.ts
  src/test/smoke/smartSend.smoke.test.ts
  src/test/terminals/codeExecution/terminalCodeExec.unit.test.ts
  types/vscode.proposed.envCollectionWorkspace.d.ts
  types/vscode.proposed.envShellEvent.d.ts
  types/vscode.proposed.terminalShellIntegration.d.ts
Labels: feature-request, area-terminal

#23991 Add `uv.lock` to file associations
  package.json
Labels: feature-request, skip package*.json

#24108 Enable proposed APIs for `codeActionAI`
  package-lock.json
  package.json
Labels: feature-request

#24114 Contribute problem matcher
  package.json
Labels: feature-request, area-terminal, skip package*.json

#24094 variable provider for native repl
  package.json
  python_files/get_variable_info.py
  python_files/tests/test_get_variable_info.py
  src/client/repl/nativeRepl.ts
  src/client/repl/pythonServer.ts
  src/client/repl/variables/types.ts
  src/client/repl/variables/variableRequester.ts
  src/client/repl/variables/variableResultCache.ts
  src/client/repl/variables/variablesProvider.ts
  src/test/repl/variableProvider.test.ts
  types/vscode.proposed.notebookVariableProvider.d.ts
Labels: feature-request, skip package*.json

#24118 Implementation of Test Coverage
  .gitignore
  build/functional-test-requirements.txt
  build/test-requirements.txt
  python_files/tests/pytestadapter/.data/coverage_gen/__init__.py
  python_files/tests/pytestadapter/.data/coverage_gen/reverse.py
  python_files/tests/pytestadapter/.data/coverage_gen/test_reverse.py
  python_files/tests/pytestadapter/helpers.py
  python_files/tests/pytestadapter/test_coverage.py
  python_files/tests/unittestadapter/.data/coverage_ex/__init__.py
  python_files/tests/unittestadapter/.data/coverage_ex/reverse.py
  python_files/tests/unittestadapter/.data/coverage_ex/test_reverse.py
  python_files/tests/unittestadapter/test_coverage.py
  python_files/unittestadapter/execution.py
  python_files/unittestadapter/pvsc_utils.py
  python_files/vscode_pytest/__init__.py
  python_files/vscode_pytest/run_pytest_script.py
  src/client/testing/testController/common/resultResolver.ts
  src/client/testing/testController/common/types.ts
  src/client/testing/testController/controller.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/client/testing/testController/unittest/testExecutionAdapter.ts
  src/client/testing/testController/workspaceTestAdapter.ts
  src/test/mocks/vsc/index.ts
  src/test/testing/common/testingAdapter.test.ts
  src/test/testing/testController/pytest/pytestExecutionAdapter.unit.test.ts
  src/test/testing/testController/testCancellationRunAdapters.unit.test.ts
  src/test/testing/testController/unittest/testExecutionAdapter.unit.test.ts
  src/test/vscode-mock.ts
  src/testTestingRootWkspc/coverageWorkspace/even.py
  src/testTestingRootWkspc/coverageWorkspace/test_even.py
Labels: feature-request

#24130 account for inline chat widget
  package.json
Labels: bug, skip package*.json

#24131 use new context key for both repl-type editors
  package.json
Labels: bug, skip package*.json

#24128 Add a command copilot calls back to ensure testing is set up
  package.json
  src/client/common/application/commands.ts
  src/client/common/constants.ts
  src/client/common/utils/localize.ts
  src/client/testing/common/types.ts
  src/client/testing/configuration/index.ts
  src/client/testing/main.ts
  src/test/testing/configuration.unit.test.ts
Labels: feature-request, skip package*.json

#24138 Add logging for executeCommand
  src/client/common/terminal/service.ts
Labels: debt, area-terminal, skip tests

#24140 Default PYTHONSTARTUP to opt out/off for Stable Release
  package.json
Labels: feature-request, area-terminal, skip package*.json, area-repl

#24029 Use new REPL notebook API
  package-lock.json
  package.json
  src/client/common/application/commands.ts
  src/client/common/constants.ts
  src/client/repl/nativeRepl.ts
  src/client/repl/replCommandHandler.ts
  src/client/repl/replCommands.ts
  src/client/repl/replController.ts
  types/vscode.proposed.notebookReplDocument.d.ts
Labels: debt, skip package*.json, skip tests

#24144 add experimental tag for enableShellIntegration
  package.json
Labels: debt, area-terminal, skip package*.json

#24146 Remove variableProvider suite.only from limiting other tests
  src/test/repl/variableProvider.test.ts
Labels: bug

#24153 Change PYTHONSTARTUP setting name to Python.terminal.shell integration.enabled
  package.json
  package.nls.json
  src/client/common/configSettings.ts
  src/client/common/types.ts
  src/client/terminals/pythonStartup.ts
  src/test/terminals/codeExecution/helper.test.ts
  src/test/terminals/codeExecution/smartSend.test.ts
Labels: feature-request, area-terminal, skip package*.json, area-repl

#24155 Fix issue with creating `.gitignore` with venvs
  python_files/create_venv.py
  python_files/tests/test_create_venv.py
Labels: bug

#24091 Remove redundant @typescript-eslint/no-explicit-any suppression
  src/client/common/types.ts
Labels: debt, skip tests

#24157 Add separate enum for telemetry when running python manually.
  src/client/telemetry/index.ts
  src/client/terminals/codeExecution/terminalReplWatcher.ts
Labels: no-changelog, skip tests

#24165 Adjust PythonStartUp test for new setting value
  src/test/terminals/shellIntegration/pythonStartup.test.ts
Labels: debt, area-terminal

#24164 Change log level on pixi interpreter discovery to reduce confusion
  src/client/pythonEnvironments/common/environmentManagers/pixi.ts
Labels: debt, area-environments, skip tests

#24187 Fix) Python Shell Integration setting should have markdown description
  package.json
Labels: bug, area-editor-*, skip package*.json

#24180 Remove branch coverage and refactor coverage.py methods for accessing
  python_files/tests/pytestadapter/test_coverage.py
  python_files/tests/unittestadapter/test_coverage.py
  python_files/unittestadapter/execution.py
  python_files/unittestadapter/pvsc_utils.py
  python_files/vscode_pytest/__init__.py
  python_files/vscode_pytest/run_pytest_script.py
  src/client/testing/testController/common/resultResolver.ts
  src/client/testing/testController/common/types.ts
  src/test/testing/common/testingAdapter.test.ts
Labels: bug, area-testing

#24198 Prioritize `conda` handler over `pixi` handler
  src/client/common/process/pythonExecutionFactory.ts
  src/test/common/process/pythonExecutionFactory.unit.test.ts
Labels: bug

#24212 Update version for 2024.16.0 release
  package-lock.json
  package.json
Labels: no-changelog

#24213 Update version for pre-release
  package-lock.json
  package.json
Labels: no-changelog
