Repository microsoft/vscode-python, pull requests merged in 2024-07, with the labels that each got.

#23726 Fix telemetry annotations
  src/client/telemetry/index.ts
Labels: no-changelog, skip tests

#23728 Remove the `pip` trigger to create environment
  src/client/common/experiments/groups.ts
  src/client/pythonEnvironments/creation/globalPipInTerminalTrigger.ts
  src/test/pythonEnvironments/creation/globalPipInTerminalTrigger.unit.test.ts
Labels: debt

#23742 Updates to categories and request object
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
Labels: no-changelog, skip package*.json, skip tests

#23744 Rename category to kind
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/client/pythonEnvironments/base/locators/lowLevel/nativeLocator.ts
Labels: no-changelog, skip package*.json, skip tests

#23745 Support category being undefined
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
Labels: no-changelog, skip package*.json, skip tests

#23753 Handle & track conda envs not found
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
  src/client/pythonEnvironments/base/locators/common/nativePythonTelemetry.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
Labels: no-changelog, skip package*.json, skip tests

#23755 update to finalized release 2024.10
  package-lock.json
  package.json
Labels: no-changelog

#23770 Add more data for conda envs not found
  src/client/pythonEnvironments/base/locators/common/nativePythonTelemetry.ts
  src/client/telemetry/index.ts
Labels: no-changelog, skip package*.json, skip tests

#23771 Determine reasons for Poetry find failures
  src/client/pythonEnvironments/base/locators/common/nativePythonTelemetry.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
Labels: no-changelog, skip package*.json, skip tests

#23732 Hide Run Python option when in Jupyter Notebook
  package.json
Labels: debt, skip package*.json, area-repl

#23782 Add configuration request
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
Labels: no-changelog, skip package*.json, skip tests

#23779 Gather additional data to determine failures in identifying conda envs
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/client/telemetry/index.ts
Labels: no-changelog, skip package*.json, skip tests

#23787 Native Conda Telemetry
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/client/telemetry/index.ts
Labels: no-changelog, skip package*.json, skip tests

#23789 Update pylance.ts for GDPR clearning
  src/client/telemetry/pylance.ts
Labels: no-changelog, skip tests

#23790 Additional conda telemetry
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/client/pythonEnvironments/common/environmentManagers/conda.ts
  src/client/telemetry/index.ts
  src/test/pythonEnvironments/base/locators/composite/envsCollectionService.unit.test.ts
Labels: no-changelog, skip package*.json, skip tests

#23792 Performance telemetry for native locator
  src/client/pythonEnvironments/base/locators/common/nativePythonTelemetry.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
Labels: no-changelog, skip package*.json, skip tests

#23786 Minimize execution output when there is no output for new REPL
  src/client/repl/replController.ts
Labels: feature-request, skip tests, area-repl

#23796 Capture info for missing conda envs in native locator
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/client/telemetry/index.ts
Labels: no-changelog, skip package*.json, skip tests

#23802 Await on promises
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
Labels: no-changelog, skip package*.json, skip tests

#23805 Additional data to compare conda environments.txt
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/client/telemetry/index.ts
Labels: no-changelog, skip package*.json, skip tests

#23810 Capture additional telemetry for conda
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/client/telemetry/index.ts
Labels: no-changelog, skip package*.json, skip tests

#23814 Fix debug arg error
  src/client/debugger/extension/configuration/resolvers/attach.ts
  src/client/debugger/extension/configuration/resolvers/launch.ts
  src/client/debugger/types.ts
  src/client/testing/common/debugLauncher.ts
  src/test/debugger/extension/configuration/resolvers/attach.unit.test.ts
  src/test/debugger/extension/configuration/resolvers/launch.unit.test.ts
  src/test/testing/common/debugLauncher.unit.test.ts
Labels: bug, area-debugging

#23781 add backwards compatibility for pytest hook wrapper
  python_files/vscode_pytest/__init__.py
Labels: bug, area-testing

#23817 Read launch from devcontainer
  src/client/debugger/extension/configuration/launch.json/launchJsonReader.ts
Labels: bug, area-debugging, skip tests

#23825 Add some more telemetry for missing conda envs
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/client/telemetry/index.ts
  src/test/pythonEnvironments/base/locators/composite/envsCollectionService.unit.test.ts
Labels: no-changelog, skip package*.json, skip tests

#23823 Use Native Python Finder as the main locator
  src/client/environmentApi.ts
  src/client/interpreter/display/progressDisplay.ts
  src/client/pythonEnvironments/base/locator.ts
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/client/pythonEnvironments/base/locators/lowLevel/nativeLocator.ts
  src/client/pythonEnvironments/index.ts
  src/client/pythonEnvironments/nativeAPI.ts
  src/test/pythonEnvironments/base/locators/composite/envsCollectionService.unit.test.ts
  src/test/pythonEnvironments/nativeAPI.unit.test.ts
Labels: feature-request

#23832 Updates to use new Python locator Api
  src/client/common/utils/async.ts
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/client/pythonEnvironments/base/locators/lowLevel/nativeLocator.ts
  src/client/pythonEnvironments/nativeAPI.ts
  src/test/pythonEnvironments/base/locators/composite/envsCollectionService.unit.test.ts
  src/test/pythonEnvironments/nativeAPI.unit.test.ts
Labels: no-changelog, skip package*.json, skip tests

#23834 Configure before resolving and remove old API call
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
Labels: no-changelog, skip package*.json, skip tests

#23797 Correctly display native REPL execution status
  python_files/python_server.py
  src/client/repl/pythonServer.ts
  src/client/repl/replController.ts
Labels: feature-request, skip tests, area-repl

#23831 More native tests for Native python finder
  .github/workflows/build.yml
  .github/workflows/pr-check.yml
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
  src/client/pythonEnvironments/base/locators/common/nativePythonUtils.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/client/pythonEnvironments/base/locators/lowLevel/nativeLocator.ts
  src/client/pythonEnvironments/nativeAPI.ts
  src/test/pythonEnvironments/base/locators/composite/envsCollectionService.unit.test.ts
  src/test/pythonEnvironments/nativeAPI.unit.test.ts
  src/test/pythonEnvironments/nativePythonFinder.unit.test.ts
Labels: no-changelog

#23840 Add executable path as `id` for envs
  src/client/pythonEnvironments/nativeAPI.ts
  src/test/pythonEnvironments/nativeAPI.unit.test.ts
Labels: bug

#23791 xdist fixes
  python_files/vscode_pytest/__init__.py
Labels: feature-request

#23845 Ensure env manager executable is set
  src/client/pythonEnvironments/common/environmentManagers/conda.ts
  src/client/pythonEnvironments/nativeAPI.ts
  src/test/pythonEnvironments/nativeAPI.unit.test.ts
Labels: bug

#23847 Update logging in getConfigurationsForWorkspace
  src/client/debugger/extension/configuration/launch.json/launchJsonReader.ts
Labels: no-changelog, skip tests

#23851 Fix `location` for native environments
  src/client/pythonEnvironments/nativeAPI.ts
  src/test/pythonEnvironments/nativeAPI.unit.test.ts
Labels: bug

#23850 Ensure telemetry measurements are sent correctly
  src/client/pythonEnvironments/base/locators/common/nativePythonTelemetry.ts
Labels: no-changelog, skip package*.json, skip tests

#23852 Add support for file system watching with native python locator
  src/client/common/vscodeApis/workspaceApis.ts
  src/client/pythonEnvironments/base/locator.ts
  src/client/pythonEnvironments/base/locators/common/pythonWatcher.ts
  src/client/pythonEnvironments/index.ts
  src/client/pythonEnvironments/nativeAPI.ts
  src/test/pythonEnvironments/nativeAPI.unit.test.ts
Labels: feature-request

#23853 Add Cache dir for native locator
  src/client/common/persistentState.ts
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/client/pythonEnvironments/index.ts
Labels: no-changelog, skip package*.json, skip tests

#23854 Metrics tracking launch times for native locator
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
  src/client/pythonEnvironments/base/locators/common/nativePythonTelemetry.ts
  src/client/telemetry/index.ts
Labels: no-changelog, skip package*.json, skip tests

#23861 Add a new measure for native finder perf
  src/client/pythonEnvironments/base/locators/common/nativePythonTelemetry.ts
  src/client/telemetry/index.ts
Labels: no-changelog, skip package*.json, skip tests

#23866 fix crash when importing `pluggy.Result` on old versions of pluggy
  python_files/vscode_pytest/__init__.py
Labels: bug

#23873 Update release_plan.md
  .github/release_plan.md
Labels: debt

#23881 Bump version to 2024.12.0-rc
  package-lock.json
  package.json
Labels: no-changelog

#23876 Update info-needed-closer.yml
  .github/workflows/info-needed-closer.yml
Labels: debt

#23882 Bump version to 2024.13.0-dev
  package-lock.json
  package.json
Labels: no-changelog

#23890 Downgrade lsp packages
  package-lock.json
  package.json
  src/client/browser/extension.ts
Labels: no-changelog, skip tests

#23892 Finalize 2024.12.0
  package-lock.json
  package.json
Labels: no-changelog

#23729 Add tests for native REPL
  package-lock.json
  package.json
  src/client/common/application/commands.ts
  src/client/extensionActivation.ts
  src/client/repl/replCommands.ts
  src/test/repl/replCommand.test.ts
Labels: debt, area-repl

#23894 Updating micro to pull in latest python environment tools
  package-lock.json
  package.json
Labels: bug
