Repository microsoft/vscode-python, pull requests merged in 2024-06, with the labels that each got.

#23546 dont override shift+enter behavior
  package.json
  src/client/common/constants.ts
  src/client/extensionActivation.ts
  src/client/repl/replCommands.ts
Labels: bug, skip package*.json, skip tests

#23547 bump release 2024.8.0
  package-lock.json
  package.json
Labels: no-changelog

#23548 bump-dev-version-2024.9
  package-lock.json
  package.json
Labels: no-changelog

#23535 Support pytest parameterized tests spanning multiple classes when calling the same setup function
  python_files/tests/pytestadapter/.data/test_param_span_class.py
  python_files/tests/pytestadapter/expected_discovery_test_output.py
  python_files/tests/pytestadapter/test_discovery.py
  python_files/vscode_pytest/__init__.py
Labels: bug, area-testing

#23537 bug fix to have load bar show during test discovery
  src/client/testing/testController/controller.ts
Labels: bug, skip tests

#23559 Finalized release 2024.8
  package-lock.json
  package.json
Labels: no-changelog

#23534 chore: use Linux pools for Alpine builds
  build/azure-pipeline.pre-release.yml
Labels: no-changelog

#23572 dont send to REPL from a notebook editor
  package.json
Labels: bug, skip package*.json, skip tests

#23574 Update info-needed-closer.yml
  .github/workflows/info-needed-closer.yml
Labels: debt

#23598 Remove macos runner
  .github/workflows/build.yml
  .github/workflows/pr-check.yml
Labels: no-changelog

#23596 Restore computing version in legacy locators
  src/client/pythonEnvironments/base/locators/composite/resolverUtils.ts
Labels: bug, skip tests

#23597 Fix smoke tests
  .github/workflows/build.yml
Labels: bug

#23599 Audit fix and some clean up
  package-lock.json
  python_files/tests/unittestadapter/test_execution.py
  python_files/unittestadapter/pvsc_utils.py
  requirements.txt
Labels: debt, skip package*.json

#23591 Add missing telemetry for REPL
  src/client/repl/pythonServer.ts
Labels: bug, skip tests, area-repl

#23608 Don't send to REPL from a notebook editor
  package.json
Labels: bug, skip package*.json, skip tests, area-repl

#23609 Restore computing version in legacy locators
  src/client/pythonEnvironments/base/locators/composite/resolverUtils.ts
Labels: bug, skip tests

#23610 Add missing telemetry for REPL
  src/client/repl/pythonServer.ts
Labels: bug, skip tests, area-repl

#23612 Fix smoke tests
  .github/workflows/build.yml
Labels: no-changelog

#23611 Point release 2024.8.1 version update
  package-lock.json
  package.json
Labels: no-changelog

#23617 Adopt new locator
  src/client/common/utils/iterable.ts
  src/client/common/utils/resourceLifecycle.ts
  src/client/pythonEnvironments/base/locator.ts
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
  src/client/pythonEnvironments/base/locators/composite/envsResolver.ts
  src/client/pythonEnvironments/base/locators/composite/resolverUtils.ts
  src/client/pythonEnvironments/base/locators/lowLevel/nativeLocator.ts
Labels: no-changelog, skip package*.json, skip tests

#23620 Restore execute bits on deactivate scripts
  python_files/deactivate/bash/deactivate
  python_files/deactivate/fish/deactivate
  python_files/deactivate/zsh/deactivate
Labels: bug

#23623 Update language server modules to latest release
  package-lock.json
  package.json
  src/client/activation/hidingMiddleware.ts
  src/client/activation/languageClientMiddleware.ts
  src/client/browser/extension.ts
Labels: bug, skip tests

#23613 Rename REPL to Terminal REPL
  README.md
  package.nls.json
Labels: feature-request, area-repl

#23631 Adopt native locator resolve methods
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
  src/client/pythonEnvironments/base/locators/composite/resolverUtils.ts
  src/client/pythonEnvironments/index.ts
Labels: no-changelog, skip package*.json, skip tests

#23550 Refactor Native REPL code
  src/client/repl/nativeRepl.ts
  src/client/repl/replCommandHandler.ts
  src/client/repl/replCommands.ts
  src/client/repl/replUtils.ts
Labels: debt, skip tests, area-repl

#23638 Allow Smart send with new REPL
  src/client/extensionActivation.ts
  src/client/repl/replCommands.ts
Labels: feature-request, skip tests, area-repl

#23642 Activate extension when .venv or .conda found in workspace
  package.json
Labels: feature-request, skip package*.json

#22968 Add locator for pixi environments
  package.json
  package.nls.json
  resources/report_issue_user_settings.json
  src/client/common/configSettings.ts
  src/client/common/installer/pixiInstaller.ts
  src/client/common/installer/productInstaller.ts
  src/client/common/installer/serviceRegistry.ts
  src/client/common/process/pythonEnvironment.ts
  src/client/common/process/pythonExecutionFactory.ts
  src/client/common/serviceRegistry.ts
  src/client/common/terminal/environmentActivationProviders/pixiActivationProvider.ts
  src/client/common/terminal/helper.ts
  src/client/common/terminal/types.ts
  src/client/common/types.ts
  src/client/interpreter/configuration/interpreterSelector/commands/setInterpreter.ts
  src/client/pythonEnvironments/base/info/envKind.ts
  src/client/pythonEnvironments/base/info/index.ts
  src/client/pythonEnvironments/base/locators/lowLevel/pixiLocator.ts
  src/client/pythonEnvironments/common/environmentIdentifier.ts
  src/client/pythonEnvironments/common/environmentManagers/pixi.ts
  src/client/pythonEnvironments/index.ts
  src/client/pythonEnvironments/info/index.ts
  src/client/pythonEnvironments/legacyIOC.ts
  src/test/common/configSettings/configSettings.unit.test.ts
  src/test/common/terminals/activation.conda.unit.test.ts
  src/test/common/terminals/helper.unit.test.ts
  src/test/pythonEnvironments/base/info/envKind.unit.test.ts
  src/test/pythonEnvironments/base/locators/lowLevel/pixiLocator.unit.test.ts
  src/test/pythonEnvironments/common/environmentManagers/pixi.unit.test.ts
  src/test/pythonEnvironments/common/envlayouts/pixi/multi-env/.pixi/envs/py310/bin/python
  src/test/pythonEnvironments/common/envlayouts/pixi/multi-env/.pixi/envs/py310/conda-meta/pixi
  src/test/pythonEnvironments/common/envlayouts/pixi/multi-env/.pixi/envs/py311/bin/python
  src/test/pythonEnvironments/common/envlayouts/pixi/multi-env/.pixi/envs/py311/conda-meta/pixi
  src/test/pythonEnvironments/common/envlayouts/pixi/multi-env/.pixi/envs/py311/python
  src/test/pythonEnvironments/common/envlayouts/pixi/multi-env/pixi.toml
  src/test/pythonEnvironments/common/envlayouts/pixi/non-windows/.pixi/envs/default/bin/python
  src/test/pythonEnvironments/common/envlayouts/pixi/non-windows/.pixi/envs/default/conda-meta/pixi
  src/test/pythonEnvironments/common/envlayouts/pixi/non-windows/pixi.toml
  src/test/pythonEnvironments/common/envlayouts/pixi/windows/.pixi/envs/default/python.exe
  src/test/pythonEnvironments/common/envlayouts/pixi/windows/pixi.toml
Labels: feature-request, skip package*.json

#23539 Add hook to `vscode_pytest` to determine number `xdist` workers to use based on count of selected tests
  python_files/vscode_pytest/__init__.py
Labels: bug

#23648 Separate output channel for native finder
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
Labels: no-changelog, skip package*.json, skip tests

#23646 Get native finder telemetry
  src/client/common/vscodeApis/windowApis.ts
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/client/pythonEnvironments/base/locators/lowLevel/nativeLocator.ts
  src/client/pythonEnvironments/index.ts
  src/client/telemetry/index.ts
  src/test/mocks/vsc/index.ts
  src/test/pythonEnvironments/base/locators/composite/envsCollectionService.unit.test.ts
Labels: no-changelog, skip package*.json

#23650 Use conda-meta to get python version
  src/client/pythonEnvironments/base/locators/composite/resolverUtils.ts
Labels: bug, skip tests

#23641 Unify Terminal REPL triggers
  src/client/common/terminal/service.ts
  src/client/providers/replProvider.ts
  src/client/terminals/codeExecution/terminalCodeExecution.ts
  src/test/providers/repl.unit.test.ts
Labels: bug, area-terminal, area-repl

#23663 Revert changes introduced for Native Locator
  src/client/pythonEnvironments/base/info/environmentInfoService.ts
  src/client/pythonEnvironments/base/locators/composite/envsResolver.ts
Labels: no-changelog, skip package*.json, skip tests

#23668 Add support for poetry and mac-xcode
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
  src/client/pythonEnvironments/base/locators/lowLevel/nativeLocator.ts
Labels: no-changelog, skip package*.json, skip tests

#23672 Fix telemetry events
  src/client/telemetry/index.ts
Labels: no-changelog, skip tests

#23678 Display prefix if there's no exe
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
Labels: no-changelog, skip package*.json, skip tests

#23664 Improved telemetry for Native Locator
  src/client/pythonEnvironments/base/info/environmentInfoService.ts
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
Labels: no-changelog, skip package*.json, skip tests

#23680 Ensure pet binary is marked as executable
  noxfile.py
Labels: no-changelog, skip package*.json, skip tests

#23681 Fix python error in nox file
  noxfile.py
Labels: no-changelog, skip package*.json, skip tests

#23682 Fix permissions on built file
  noxfile.py
Labels: no-changelog

#23684 Fix pre-release platform specific build number
  build/azure-pipeline.pre-release.yml
  build/update_ext_version.py
Labels: no-changelog

#23685 Enable linux arm64 and armhf builds
  build/azure-pipeline.pre-release.yml
Labels: no-changelog

#23702 Detect some more missing categories
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
Labels: no-changelog, skip package*.json, skip tests

#23713 Exclude other workspace envs when comparing envs
  src/client/pythonEnvironments/base/locators/composite/envsCollectionService.ts
  src/client/telemetry/index.ts
Labels: no-changelog, skip package*.json, skip tests

#23711 Redirect accessibility users to terminal REPL instead of native REPL
  package.json
Labels: bug, skip package*.json, area-repl

#23712 Add parent directory to sys.path for unittest discovery and execution
  python_files/unittestadapter/discovery.py
  python_files/unittestadapter/execution.py
Labels: bug, area-testing

#23718 Clean up vsce package contents
  .vscodeignore
Labels: no-changelog

#23716 Stable release platform specific pipeline
  build/azure-pipeline.stable.yml
Labels: no-changelog

#23721 Update package version for release
  package-lock.json
  package.json
Labels: no-changelog

#23722 Update main to next pre-release
  package-lock.json
  package.json
Labels: no-changelog
