Repository microsoft/vscode-python, pull requests merged in 2024-10, with the labels that each got.

#24196 Remove unnecessary file read on execution
  src/client/terminals/codeExecution/codeExecutionManager.ts
  src/client/terminals/types.ts
  src/test/terminals/codeExecution/codeExecutionManager.unit.test.ts
Labels: bug

#24221 Update version for release
  build/azure-pipeline.stable.yml
  package-lock.json
  package.json
Labels: no-changelog

#24223 Use latest build of `pet` from `main` for pre-release
  build/azure-pipeline.pre-release.yml
Labels: no-changelog

#24225 support setting only `--cov-report` arg
  python_files/tests/pytestadapter/test_coverage.py
  python_files/vscode_pytest/run_pytest_script.py
Labels: bug

#24230 Avoid prefixing with home when unnecessary
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
  src/client/pythonEnvironments/base/locators/lowLevel/customVirtualEnvLocator.ts
Labels: no-changelog, skip package*.json, skip tests

#24228 Fix `pet` branch used with release
  build/azure-pipeline.stable.yml
Labels: no-changelog

#24232 Avoid prefixing with home when unnecessary
  src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts
  src/client/pythonEnvironments/base/locators/lowLevel/customVirtualEnvLocator.ts
Labels: bug, skip tests

#24235 prevent test.only
  .eslintrc
  package-lock.json
  package.json
Labels: debt, skip tests

#24220 remove EOT from testing communication
  python_files/tests/pytestadapter/helpers.py
  python_files/unittestadapter/discovery.py
  python_files/unittestadapter/django_test_runner.py
  python_files/unittestadapter/execution.py
  python_files/unittestadapter/pvsc_utils.py
  python_files/vscode_pytest/__init__.py
  src/client/testing/testController/common/resultResolver.ts
  src/client/testing/testController/common/types.ts
  src/client/testing/testController/common/utils.ts
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/client/testing/testController/unittest/testDiscoveryAdapter.ts
  src/client/testing/testController/unittest/testExecutionAdapter.ts
  src/test/testing/testController/payloadTestCases.ts
  src/test/testing/testController/pytest/pytestExecutionAdapter.unit.test.ts
  src/test/testing/testController/resultResolver.unit.test.ts
  src/test/testing/testController/testCancellationRunAdapters.unit.test.ts
  src/test/testing/testController/unittest/testExecutionAdapter.unit.test.ts
Labels: debt

#24237 Update pylance.ts
  src/client/telemetry/pylance.ts
Labels: debt, skip tests

#24240 Remove notification for old linter formatter settings
  src/client/extensionActivation.ts
  src/client/logging/settingLogs.ts
Labels: debt, skip tests

#24246 Fix error with `displayName` is missing in PackageJSON
  src/client/common/application/commands/reportIssueCommand.ts
Labels: bug, skip tests

#24248 Wait 0.5 second for shell integration event, otherwise fall back to sendtext.
  src/client/common/terminal/service.ts
Labels: bug, area-terminal, skip tests

#24250 Allow pytest to use correct interpreter from getActiveInterpreter
  src/client/testing/testController/common/types.ts
  src/client/testing/testController/controller.ts
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/client/testing/testController/workspaceTestAdapter.ts
Labels: bug, area-environments, skip tests

#24249 only show coverage button for rewrite
  src/client/testing/testController/controller.ts
Labels: bug, skip tests

#24227 Add customizable interpreter discovery timeout
  src/client/pythonEnvironments/base/info/interpreter.ts
Labels: bug, skip tests

#24271 Update version for recovery release
  package-lock.json
  package.json
Labels: no-changelog

#24274 Update pylance gdpr classification tag
  src/client/telemetry/pylance.ts
Labels: debt, skip tests

#24278 Fix GDPR annotations
  src/client/telemetry/pylance.ts
Labels: no-changelog, skip package*.json, skip tests

#24287 fix: tag non-stable settings with new system
  package.json
  package.nls.json
Labels: debt, skip package*.json

#24300 Refactor code to remove unused JSDoc types
  pythonExtensionApi/src/main.ts
  src/client/activation/types.ts
  src/client/api.ts
  src/client/api/types.ts
  src/client/application/diagnostics/base.ts
  src/client/application/types.ts
  src/client/common/application/commands.ts
  src/client/common/application/types.ts
  src/client/common/cancellation.ts
  src/client/common/constants.ts
  src/client/common/extensions.ts
  src/client/common/installer/types.ts
  src/client/common/terminal/shellDetector.ts
  src/client/common/terminal/shellDetectors/settingsShellDetector.ts
  src/client/common/terminal/shellDetectors/terminalNameShellDetector.ts
  src/client/common/terminal/shellDetectors/userEnvironmentShellDetector.ts
  src/client/common/terminal/shellDetectors/vscEnvironmentShellDetector.ts
  src/client/common/terminal/syncTerminalService.ts
  src/client/common/terminal/types.ts
  src/client/common/utils/async.ts
  src/client/common/utils/cacheUtils.ts
  src/client/common/utils/misc.ts
  src/client/debugger/extension/hooks/childProcessAttachHandler.ts
  src/client/debugger/extension/hooks/childProcessAttachService.ts
  src/client/deprecatedProposedApiTypes.ts
  src/client/interpreter/autoSelection/types.ts
  src/client/pythonEnvironments/creation/common/createEnvTriggerUtils.ts
  src/client/repl/nativeRepl.ts
  src/client/repl/replCommandHandler.ts
  src/client/repl/replCommands.ts
  src/client/repl/replUtils.ts
  src/client/telemetry/index.ts
  src/test/common.ts
  src/test/common/utils/decorators.unit.test.ts
  src/test/index.ts
  src/test/mocks/vsc/arrays.ts
  src/test/utils/interpreters.ts
Labels: debt

#24295 Fix for conda activation during testing
  src/client/pythonEnvironments/nativeAPI.ts
  src/test/pythonEnvironments/nativeAPI.unit.test.ts
Labels: bug

#24252 Make `python_server.py` compatible to Python 3.7
  python_files/python_server.py
Labels: bug, area-repl

#24304 Update version for recovery release
  package-lock.json
  package.json
Labels: no-changelog

#24303 Fix for conda activation during testing
  src/client/pythonEnvironments/nativeAPI.ts
  src/test/pythonEnvironments/nativeAPI.unit.test.ts
Labels: bug

#24320 Add properties to GDPR tags
  src/client/telemetry/pylance.ts
Labels: debt, skip tests

#24314 Fix typo in class name
  src/client/interpreter/display/progressDisplay.ts
  src/client/interpreter/serviceRegistry.ts
  src/test/interpreters/display/progressDisplay.unit.test.ts
  src/test/interpreters/serviceRegistry.unit.test.ts
Labels: debt

#24288 add error message for missing pytest-cov while running coverage
  python_files/vscode_pytest/__init__.py
Labels: debt

#24319 Restore `pixi` functionality only when Pixi is available
  src/client/common/process/pythonExecutionFactory.ts
  src/client/common/terminal/environmentActivationProviders/pixiActivationProvider.ts
  src/client/common/terminal/helper.ts
  src/client/extensionActivation.ts
  src/client/interpreter/activation/service.ts
  src/client/pythonEnvironments/base/locators/lowLevel/pixiLocator.ts
  src/client/pythonEnvironments/common/environmentManagers/pixi.ts
  src/test/common/process/pythonExecutionFactory.unit.test.ts
  src/test/common/terminals/helper.unit.test.ts
  src/test/pythonEnvironments/base/locators/lowLevel/pixiLocator.unit.test.ts
  src/test/pythonEnvironments/common/environmentManagers/pixi.unit.test.ts
  src/test/testing/common/testingAdapter.test.ts
Labels: bug

#24321 Fix for duplication of python envs
  src/client/pythonEnvironments/nativeAPI.ts
  src/test/pythonEnvironments/nativeAPI.unit.test.ts
Labels: bug

#24335 Update VS Code engine and `@types/vscode` for APIs
  pythonExtensionApi/package-lock.json
  pythonExtensionApi/package.json
Labels: debt

#24330 update jedi dependencies to add python 3.13 support
  python_files/jedilsp_requirements/requirements.txt
Labels: debt

#24341 disable shell integration for 3.13
  python_files/pythonrc.py
Labels: bug, area-terminal, area-repl

#24338 Update main version for release
  build/azure-pipeline.stable.yml
  package-lock.json
  package.json
Labels: no-changelog

#24344 Update main to next pre-release
  package-lock.json
  package.json
Labels: no-changelog

#24354 fix: upgrade settings to preview
  package.json
Labels: bug, skip package*.json

#24356 Update node version to 20.18.0
  .github/workflows/build.yml
  .github/workflows/pr-check.yml
  .nvmrc
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
  build/azure-pipelines/pipeline.yml
  pythonExtensionApi/package-lock.json
  pythonExtensionApi/package.json
Labels: debt

#24362 no longer need this proposed API
  package.json
Labels: debt, skip package*.json

#24370 Update version for release
  package-lock.json
  package.json
Labels: no-changelog
