Repository microsoft/vscode-python, pull requests merged in 2024-08, with the labels that each got.

#23899 porting `downgrade lsp packages` to release branch
  package-lock.json
  package.json
  src/client/browser/extension.ts
Labels: no-changelog, skip tests

#23900 Add GDPR tags for Pylance event
  src/client/telemetry/pylance.ts
Labels: no-changelog, skip tests

#23896 Update release plan for stable
  .github/release_plan.md
  build/azure-pipeline.stable.yml
Labels: no-changelog

#23903 Ensure older extensions versions have `pet` pinned to branch
  build/azure-pipeline.stable.yml
Labels: debt

#23910 Update version for recovery release
  package-lock.json
  package.json
Labels: no-changelog

#23898 Remove the middleware addon component from all language servers
  src/client/activation/hidingMiddleware.ts
  src/client/activation/jedi/languageClientMiddleware.ts
  src/client/activation/languageClientMiddleware.ts
  src/client/activation/node/languageClientMiddleware.ts
Labels: no-changelog, skip package*.json, skip tests

#23891 Debug test session proposed
  src/client/testing/common/debugLauncher.ts
  src/client/testing/testController/controller.ts
  src/test/testing/common/debugLauncher.unit.test.ts
Labels: bug, skip tests

#23917 Fix event name in GDPR tag
  src/client/telemetry/pylance.ts
Labels: no-changelog, skip tests

#23912 Allow native REPL launch from command palette
  package-lock.json
  package.json
  package.nls.json
  src/client/common/application/commands.ts
  src/client/common/constants.ts
  src/client/extensionActivation.ts
  src/client/repl/nativeRepl.ts
  src/client/repl/pythonServer.ts
  src/client/repl/replCommands.ts
  src/client/repl/replController.ts
  src/test/repl/nativeRepl.test.ts
Labels: feature-request, area-repl

#23931 Fix issues with localization and signing
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
  noxfile.py
Labels: bug

#23939 Fix issues with localization and signing
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
  noxfile.py
Labels: bug

#23940 Remove finalized terminalShellIntegration from proposals
  package.json
Labels: debt, skip package*.json

#23937 Attempt to handle pixi error more gracefully
  src/client/pythonEnvironments/common/environmentManagers/pixi.ts
Labels: bug, area-environments, skip tests

#23938 Update version for recovery release
  package-lock.json
  package.json
Labels: no-changelog

#23941 REPL Telemetry for Terminal REPL and Native REPL
  src/client/extensionActivation.ts
  src/client/providers/replProvider.ts
  src/client/repl/replCommands.ts
  src/client/telemetry/index.ts
  src/client/terminals/codeExecution/terminalReplWatcher.ts
Labels: feature-request, area-terminal, skip tests, area-repl

#23944 Fire telemetry when REPLs are launched via shift+enter
  src/client/repl/nativeRepl.ts
  src/client/terminals/codeExecution/terminalCodeExecution.ts
Labels: feature-request, area-terminal, skip tests, area-repl

#23935 Django Test Compatibility
  build/test-requirements.txt
  python_files/tests/pytestadapter/helpers.py
  python_files/tests/unittestadapter/.data/simple_django/db.sqlite3
  python_files/tests/unittestadapter/.data/simple_django/manage.py
  python_files/tests/unittestadapter/.data/simple_django/mysite/__init__.py
  python_files/tests/unittestadapter/.data/simple_django/mysite/asgi.py
  python_files/tests/unittestadapter/.data/simple_django/mysite/settings.py
  python_files/tests/unittestadapter/.data/simple_django/mysite/urls.py
  python_files/tests/unittestadapter/.data/simple_django/mysite/wsgi.py
  python_files/tests/unittestadapter/.data/simple_django/polls/__init__.py
  python_files/tests/unittestadapter/.data/simple_django/polls/admin.py
  python_files/tests/unittestadapter/.data/simple_django/polls/apps.py
  python_files/tests/unittestadapter/.data/simple_django/polls/migrations/0001_initial.py
  python_files/tests/unittestadapter/.data/simple_django/polls/migrations/__init__.py
  python_files/tests/unittestadapter/.data/simple_django/polls/models.py
  python_files/tests/unittestadapter/.data/simple_django/polls/tests.py
  python_files/tests/unittestadapter/.data/simple_django/polls/urls.py
  python_files/tests/unittestadapter/.data/simple_django/polls/views.py
  python_files/tests/unittestadapter/django_test_execution_script.py
  python_files/tests/unittestadapter/test_discovery.py
  python_files/tests/unittestadapter/test_execution.py
  python_files/unittestadapter/discovery.py
  python_files/unittestadapter/django_handler.py
  python_files/unittestadapter/django_test_runner.py
  python_files/unittestadapter/execution.py
  python_files/unittestadapter/pvsc_utils.py
Labels: feature-request

#23958 Fix telemetry not getting picked up for Terminal REPL
  python_files/Notebooks intro.ipynb
  src/client/terminals/codeExecution/terminalReplWatcher.ts
Labels: bug, skip tests, area-repl

#23973 Fix execInREPL Enter to respect complete expression
  src/client/repl/pythonServer.ts
Labels: bug, skip tests, area-repl

#23974 Add GDPR comment for `repltype`
  src/client/telemetry/index.ts
Labels: debt, area-internal, skip tests

#23942 Additional graceful handling for pixi
  src/client/pythonEnvironments/base/locators/common/resourceBasedLocator.ts
  src/client/pythonEnvironments/base/locators/lowLevel/fsWatchingLocator.ts
  src/client/pythonEnvironments/common/environmentManagers/pixi.ts
Labels: bug, area-environments, skip tests

#23977 Do not truncate whitespace for multi-line string
  python_files/normalizeSelection.py
  src/test/python_files/terminalExec/sample2_normalized_selection.py
  src/test/python_files/terminalExec/sample2_raw.py
Labels: feature-request, area-repl

#23983 Handle poetry env manager from native locator
  src/client/pythonEnvironments/nativeAPI.ts
Labels: no-changelog, skip package*.json, skip tests

#23995 Fix stop sending double telemetry for Terminal REPL
  src/client/providers/replProvider.ts
Labels: bug, skip tests, area-repl

#23997 Correctly track native REPL state
  src/client/repl/nativeRepl.ts
Labels: bug, skip tests, area-repl
