Repository microsoft/vscode-python, pull requests merged in 2025-03, with the labels that each got.

#24860 Finalize 2025.2.0
  package-lock.json
  package.json
Labels: no-changelog, skip-issue-check

#24867 remove airbnb rules
  .eslintrc
  package-lock.json
  package.json
Labels: debt

#24868 update eslint version
  .eslintrc
  package-lock.json
  package.json
  src/client/common/pipes/namedPipes.ts
  src/client/interpreter/activation/service.ts
  src/client/pythonEnvironments/common/environmentManagers/activestate.ts
  src/client/pythonEnvironments/common/environmentManagers/condaService.ts
  src/client/pythonEnvironments/common/environmentManagers/pixi.ts
Labels: debt, skip tests, skip-issue-check

#24882 switch to use eslint.config.mjs
  build/ci/scripts/spec_with_pid.js
  eslint.config.mjs
  package.json
  src/client/common/extensions.ts
  src/client/common/terminal/service.ts
  src/test/common.ts
Labels: debt, skip package*.json, skip tests, skip-issue-check

#24859 default to XDG_RUNTIME_DIR for mac/linux in temp file for testing comms
  src/client/testing/testController/common/utils.ts
  src/test/testing/testController/utils.unit.test.ts
Labels: bug

#24884 add no bad gdpr comments plugin
  .eslintplugin/no-bad-gdpr-comment.js
  .eslintplugin/no-bad-gdpr-comment.ts
  eslint.config.mjs
Labels: debt, skip-issue-check

#24883 remove old .eslintrc and ignore file
  .eslintignore
  .eslintrc
Labels: debt, skip-issue-check

#24903 Ensure survey notification respects telemetry.disableFeedback setting
  src/client/activation/extensionSurvey.ts
  src/test/activation/extensionSurvey.unit.test.ts
Labels: no-changelog

#24921 move clear envCollection to after await
  src/client/terminals/envCollectionActivation/service.ts
Labels: bug, skip tests

#24925 fix: use vsceTarget to rustTarget conversion when pulling `pet`
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
Labels: debt, skip-issue-check

#24929 Use new feedback setting
  src/client/activation/extensionSurvey.ts
  src/test/activation/extensionSurvey.unit.test.ts
Labels: no-changelog, skip-issue-check

#24936 bump to 2025.5.0-dev
  package-lock.json
  package.json
Labels: no-changelog, skip-issue-check

#24939 fix: for PR file check failure
  .github/workflows/pr-file-check.yml
Labels: debt
