Repository microsoft/vscode-python, pull requests merged in 2025-04, with the labels that each got.

#24952 Set native repl to default to false, remove experiment
  package.json
Labels: debt, skip package*.json, area-repl

#24937 fix: log only the required environment variables
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
Labels: debt, skip tests

#24941 fix: use wrapper functions for easier testing
  src/client/common/vscodeApis/commandApis.ts
  src/client/common/vscodeApis/windowApis.ts
  src/client/common/vscodeApis/workspaceApis.ts
  src/client/repl/replCommandHandler.ts
Labels: debt, skip tests

#24857 prevent native REPL from caching state between sessions
  .github/actions/smoke-tests/action.yml
  src/client/common/vscodeApis/workspaceApis.ts
  src/client/repl/nativeRepl.ts
  src/client/repl/pythonServer.ts
  src/test/repl/nativeRepl.test.ts
Labels: bug, area-repl, skip-issue-check

#24954 remove ITestLogChannel
  python_files/vscode_pytest/__init__.py
  src/client/common/types.ts
  src/client/common/utils/localize.ts
  src/client/extensionInit.ts
  src/client/testing/testController/common/utils.ts
  src/client/testing/testController/controller.ts
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/client/testing/testController/unittest/testDiscoveryAdapter.ts
  src/client/testing/testController/unittest/testExecutionAdapter.ts
  src/test/serviceRegistry.ts
  src/test/testing/common/managers/testConfigurationManager.unit.test.ts
  src/test/testing/common/testingAdapter.test.ts
  src/test/testing/configuration.unit.test.ts
  src/test/testing/configurationFactory.unit.test.ts
  src/test/testing/testController/pytest/pytestDiscoveryAdapter.unit.test.ts
  src/test/testing/testController/pytest/pytestExecutionAdapter.unit.test.ts
  src/test/testing/testController/testCancellationRunAdapters.unit.test.ts
  src/test/testing/testController/unittest/testDiscoveryAdapter.unit.test.ts
  src/test/testing/testController/unittest/testExecutionAdapter.unit.test.ts
  src/test/testing/testController/workspaceTestAdapter.unit.test.ts
Labels: debt, skip-issue-check

#24962 fix: use latest `pet`
  build/azure-pipeline.stable.yml
Labels: bug, skip-issue-check

#24964 fix: use latest `pet`
  build/azure-pipeline.stable.yml
Labels: debt, skip-issue-check

#24927 Django Test Runs with Coverage
  build/test-requirements.txt
  python_files/tests/pytestadapter/helpers.py
  python_files/tests/unittestadapter/test_coverage.py
  python_files/unittestadapter/django_handler.py
Labels: bug

#24968 Test Coverage for older django versions
  python_files/tests/unittestadapter/.data/simple_django/old_manage.py
  python_files/tests/unittestadapter/test_coverage.py
  python_files/unittestadapter/django_handler.py
Labels: bug, skip-issue-check

#24959 Update pylance.ts
  src/client/telemetry/pylance.ts
Labels: no-changelog, skip tests, skip-issue-check

#24983 fix: ensure that we use new extension when available for terminal creation
  src/client/common/application/commands.ts
  src/client/providers/terminalProvider.ts
Labels: bug, skip tests

#24979 Add metadata for Pylance's documentcolor_slow telemetry event
  src/client/telemetry/pylance.ts
Labels: no-changelog, skip package*.json, skip tests, skip-issue-check

#24984 Added some pylance telemetry
  src/client/telemetry/pylance.ts
Labels: debt, skip tests, skip-issue-check

#24986 fix: let Python Envs extension handle missing `python` in conda envs
  src/client/envExt/api.legacy.ts
  src/client/interpreter/interpreterService.ts
Labels: bug, skip tests

#24988 Revert "move clear envCollection to after await (#24921)"
  src/client/terminals/envCollectionActivation/service.ts
Labels: bug, skip tests

#24990 chore: update version for recovery release
  .github/actions/smoke-tests/action.yml
  package-lock.json
  package.json
Labels: no-changelog, skip-issue-check

#24993 fix: terminal error notification in untrusted workspace
  src/client/terminals/envCollectionActivation/shellIntegrationService.ts
Labels: bug, skip tests

#24998 chore: update required dependencies
  .config/CredScanSuppressions.json
  .github/actions/build-vsix/action.yml
  .github/workflows/build.yml
  .github/workflows/pr-check.yml
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
  build/ci/conda_env_1.yml
  build/ci/conda_env_2.yml
  python_files/jedilsp_requirements/requirements.in
  requirements.in
  requirements.txt
Labels: debt, skip-issue-check

#24997 feat: update to `jedi-language-server` v0.45.0
  python_files/jedilsp_requirements/requirements.in
  python_files/jedilsp_requirements/requirements.txt
Labels: feature-request, skip-issue-check

#25001 fix: ensure options are passed to python envs
  src/client/pythonEnvironments/creation/createEnvApi.ts
Labels: bug, skip tests, skip-issue-check

#24987 Disable language services if Pyrefly extension installed + active
  src/client/common/configSettings.ts
  src/client/common/configuration/service.ts
  src/client/common/constants.ts
  src/test/common/configSettings/configSettings.pythonPath.unit.test.ts
  src/test/common/configSettings/configSettings.unit.test.ts
  src/test/extensionSettings.ts
  src/test/mocks/extension.ts
  src/test/mocks/extensions.ts
Labels: feature-request

#25004 Added some GDPR for pylance
  src/client/telemetry/pylance.ts
Labels: no-changelog, skip tests, skip-issue-check

#25006 feat: enable semantic tokens in Jedi language server analysis options
  src/client/activation/jedi/analysisOptions.ts
  src/test/activation/jedi/jediAnalysisOptions.unit.test.ts
Labels: feature-request, skip-issue-check
