Repository microsoft/vscode-python, pull requests merged in 2025-09, with the labels that each got.

#25403 Be explicit about the fact that Tools are specific to Python
  package.json
Labels: no-changelog, skip package*.json, skip tests, skip-issue-check

#25445 bump to 2025.15
  package-lock.json
  package.json
Labels: no-changelog, skip-issue-check

#25477 Add implementation and usage instruction prompts for VS Code components
  .github/prompts/extract-impl-instructions.prompt.md
  .github/prompts/extract-usage-instructions.prompt.md
Labels: debt, skip-issue-check
