Repository microsoft/vscode-python, pull requests merged in 2025-07, with the labels that each got.

#25232 fix bugs in telemetry for envs ext
  src/client/startupTelemetry.ts
  src/client/terminals/codeExecution/codeExecutionManager.ts
Labels: debt, skip tests, skip-issue-check

#25247 Bump dev 2025.11
  package-lock.json
  package.json
Labels: debt, skip-issue-check

#25235 docs: Fix grammar in macOS Python note in Quick Start
  README.md
Labels: bug, documentation, skip-issue-check

#25256 Cherry pick fixes from main
  package.json
Labels: bug, skip package*.json

#25141 Allow Activated Virtual Envs to Be Detected w/ a Workspace File
  src/client/interpreter/virtualEnvs/activatedEnvLaunch.ts
  src/test/interpreters/virtualEnvs/activatedEnvLaunch.unit.test.ts
Labels: bug, skip tests

#25263 Only select the python REPL kernel when creating/restoring the REPL
  src/client/repl/nativeRepl.ts
  src/client/repl/replCommandHandler.ts
  src/client/repl/replCommands.ts
Labels: bug, skip tests, area-repl

#25269 remove stale code for displaying config error
  src/client/common/utils/localize.ts
  src/client/testing/common/types.ts
  src/client/testing/configuration/index.ts
  src/client/testing/main.ts
  src/test/testing/configuration.unit.test.ts
Labels: debt, skip-issue-check

#25266 switch to absolute ids for class type testing objects
  python_files/tests/pytestadapter/expected_discovery_test_output.py
  python_files/vscode_pytest/__init__.py
Labels: debt, skip-issue-check

#25286 Return early in activate from env var collection
  src/client/terminals/envCollectionActivation/service.ts
Labels: bug, area-terminal, area-environments, skip tests

#25296 Resolve REPL regression on indentation, disable PyREPL only when shell integration is enabled
  package.nls.json
  python_files/pythonrc.py
  src/client/common/configSettings.ts
  src/client/common/types.ts
  src/client/extensionActivation.ts
  src/client/terminals/codeExecution/helper.ts
  src/client/terminals/pythonStartup.ts
  src/test/terminals/shellIntegration/pythonStartup.test.ts
Labels: bug, regression, area-repl

#25309 bundle envs ext with stable
  .github/actions/build-vsix/action.yml
  build/azure-pipeline.pre-release.yml
  gulpfile.js
  package.json
Labels: feature-request, skip package*.json, skip-issue-check

#25311 bump version to 2025.10.1
  package-lock.json
  package.json
Labels: no-changelog, skip-issue-check

#25321 Pompt model to use tool before running any Python command in terminal
  package.json
Labels: no-changelog, skip package*.json, skip tests, skip-issue-check
