Repository microsoft/vscode-python, pull requests merged in 2025-01, with the labels that each got.

#24685 Remove fifo regression
  noxfile.py
  python_files/testing_tools/socket_manager.py
  python_files/tests/pytestadapter/helpers.py
  python_files/unittestadapter/pvsc_utils.py
  python_files/vscode_pytest/__init__.py
  python_files/vscode_pytest/_common.py
  src/client/common/pipes/namedPipes.ts
  src/client/testing/testController/common/utils.ts
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/client/testing/testController/unittest/testDiscoveryAdapter.ts
  src/client/testing/testController/unittest/testExecutionAdapter.ts
  src/test/testing/common/testingAdapter.test.ts
  src/test/testing/testController/pytest/pytestDiscoveryAdapter.unit.test.ts
  src/test/testing/testController/pytest/pytestExecutionAdapter.unit.test.ts
  src/test/testing/testController/testCancellationRunAdapters.unit.test.ts
  src/test/testing/testController/unittest/testDiscoveryAdapter.unit.test.ts
  src/test/testing/testController/unittest/testExecutionAdapter.unit.test.ts
  src/testTestingRootWkspc/errorWorkspace/test_seg_fault.py
Labels: bug

#24687 Remove fifo regression (#24685)
  noxfile.py
  python_files/testing_tools/socket_manager.py
  python_files/tests/pytestadapter/helpers.py
  python_files/unittestadapter/pvsc_utils.py
  python_files/vscode_pytest/__init__.py
  python_files/vscode_pytest/_common.py
  src/client/common/pipes/namedPipes.ts
  src/client/testing/testController/common/utils.ts
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/client/testing/testController/unittest/testDiscoveryAdapter.ts
  src/client/testing/testController/unittest/testExecutionAdapter.ts
  src/test/testing/common/testingAdapter.test.ts
  src/test/testing/testController/pytest/pytestDiscoveryAdapter.unit.test.ts
  src/test/testing/testController/pytest/pytestExecutionAdapter.unit.test.ts
  src/test/testing/testController/testCancellationRunAdapters.unit.test.ts
  src/test/testing/testController/unittest/testDiscoveryAdapter.unit.test.ts
  src/test/testing/testController/unittest/testExecutionAdapter.unit.test.ts
  src/testTestingRootWkspc/errorWorkspace/test_seg_fault.py
Labels: bug

#24690 Fix fifo communication for large testing projects
  noxfile.py
  python_files/testing_tools/socket_manager.py
  python_files/tests/pytestadapter/helpers.py
  python_files/unittestadapter/pvsc_utils.py
  python_files/vscode_pytest/__init__.py
  python_files/vscode_pytest/_common.py
  src/client/common/pipes/namedPipes.ts
  src/client/testing/testController/common/utils.ts
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/client/testing/testController/unittest/testDiscoveryAdapter.ts
  src/client/testing/testController/unittest/testExecutionAdapter.ts
  src/test/testing/common/testingAdapter.test.ts
  src/test/testing/testController/pytest/pytestDiscoveryAdapter.unit.test.ts
  src/test/testing/testController/pytest/pytestExecutionAdapter.unit.test.ts
  src/test/testing/testController/testCancellationRunAdapters.unit.test.ts
  src/test/testing/testController/unittest/testDiscoveryAdapter.unit.test.ts
  src/test/testing/testController/unittest/testExecutionAdapter.unit.test.ts
  src/testTestingRootWkspc/errorWorkspace/test_seg_fault.py
  src/testTestingRootWkspc/largeWorkspace/test_parameterized_subtest.py
Labels: bug

#24695 fix for testing capacity
  noxfile.py
  python_files/testing_tools/socket_manager.py
  python_files/tests/pytestadapter/helpers.py
  python_files/unittestadapter/pvsc_utils.py
  python_files/vscode_pytest/__init__.py
  python_files/vscode_pytest/_common.py
  src/client/common/pipes/namedPipes.ts
  src/client/testing/testController/common/utils.ts
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/client/testing/testController/unittest/testDiscoveryAdapter.ts
  src/client/testing/testController/unittest/testExecutionAdapter.ts
  src/test/testing/common/testingAdapter.test.ts
  src/test/testing/testController/pytest/pytestDiscoveryAdapter.unit.test.ts
  src/test/testing/testController/pytest/pytestExecutionAdapter.unit.test.ts
  src/test/testing/testController/testCancellationRunAdapters.unit.test.ts
  src/test/testing/testController/unittest/testDiscoveryAdapter.unit.test.ts
  src/test/testing/testController/unittest/testExecutionAdapter.unit.test.ts
  src/testTestingRootWkspc/errorWorkspace/test_seg_fault.py
  src/testTestingRootWkspc/largeWorkspace/test_parameterized_subtest.py
Labels: bug

#24696 bump version 2024.22.2
  package-lock.json
  package.json
Labels: debt, skip tests, skip-issue-check

#24697 switch to use file path as key in building test tree
  python_files/vscode_pytest/__init__.py
Labels: debt

#24702 remove commands for python.refreshTensorBoard and python.launchTensorBoard
  package.json
Labels: debt, skip package*.json, skip-issue-check

#24698 support pytest-ruff plugin for testing
  build/test-requirements.txt
  python_files/tests/pytestadapter/.data/folder_with_script/script_random.py
  python_files/tests/pytestadapter/.data/folder_with_script/test_simple.py
  python_files/tests/pytestadapter/expected_discovery_test_output.py
  python_files/tests/pytestadapter/test_discovery.py
  python_files/vscode_pytest/__init__.py
  src/client/testing/testController/common/resultResolver.ts
  src/client/testing/testController/common/utils.ts
Labels: feature-request, skip tests

#24708 remove stale PR check
  .github/workflows/stale-prs.yml
  python_files/tests/pytestadapter/test_discovery.py
  python_files/tests/pytestadapter/test_execution.py
  python_files/tests/unittestadapter/test_discovery.py
Labels: debt, skip-issue-check

#24710 stray debugging print left behind
  python_files/unittestadapter/pvsc_utils.py
Labels: debt, skip-issue-check

#24709 Restrict conda binary to be from PATH or Settings
  src/client/common/utils/platform.ts
  src/client/pythonEnvironments/common/environmentManagers/conda.ts
  src/client/pythonEnvironments/nativeAPI.ts
  src/test/pythonEnvironments/nativeAPI.unit.test.ts
Labels: bug, area-environments

#24719 Update release_plan.md
  .github/release_plan.md
Labels: debt, skip-issue-check

#24713 Discovery cancellation
  src/client/testing/testController/common/types.ts
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/client/testing/testController/unittest/testDiscoveryAdapter.ts
  src/client/testing/testController/unittest/testExecutionAdapter.ts
  src/client/testing/testController/workspaceTestAdapter.ts
  src/test/testing/testController/pytest/pytestDiscoveryAdapter.unit.test.ts
  src/test/testing/testController/unittest/testDiscoveryAdapter.unit.test.ts
Labels: feature-request

#24731 Update pylance telemetry for new experiment
  src/client/telemetry/pylance.ts
Labels: no-changelog, skip tests, skip-issue-check

#24734 Launch Native REPL using terminal link
  python_files/pythonrc.py
  python_files/tests/test_shell_integration.py
  src/client/common/utils/localize.ts
  src/client/common/vscodeApis/windowApis.ts
  src/client/extensionActivation.ts
  src/client/terminals/pythonStartupLinkProvider.ts
  src/test/terminals/shellIntegration/pythonStartup.test.ts
Labels: debt, area-repl

#24739 Remove env var collection related debris in pythonStartup test
  src/test/terminals/shellIntegration/pythonStartup.test.ts
Labels: debt, area-environments, skip tests
