Repository microsoft/vscode-python, pull requests merged in 2025-02, with the labels that each got.

#24775 Resolve >= 3.13 failing REPL CI tests
  src/test/terminals/codeExecution/helper.test.ts
  src/test/terminals/codeExecution/smartSend.test.ts
Labels: debt, area-repl

#24778 bump-release-2025.0
  package-lock.json
  package.json
Labels: no-changelog, skip-issue-check

#24779 Bump dev version 2025.1
  package-lock.json
  package.json
Labels: no-changelog, skip-issue-check

#24781 update release plan to move release branching to prior thurs
  .github/release_plan.md
Labels: debt, skip-issue-check

#24771 Jupyter API to get Env associated with Notebooks
  pythonExtensionApi/src/main.ts
  src/client/api.ts
  src/client/api/types.ts
  src/client/environmentApi.ts
  src/client/jupyter/jupyterIntegration.ts
  src/test/api.functional.test.ts
  src/test/environmentApi.unit.test.ts
Labels: no-changelog, skip-issue-check

#24784 add extra newline to execute when returning dictionary
  python_files/normalizeSelection.py
  python_files/tests/test_normalize_selection.py
Labels: bug, area-terminal

#24785 Add "Native" in front of "Python REPL" under Run Python menu
  package.nls.json
Labels: debt, area-repl, skip-issue-check

#24786 Fix event duplication when using Python Environments
  src/client/envExt/api.legacy.ts
  src/client/interpreter/interpreterService.ts
Labels: bug, skip tests

#24793 finalized release for 2025.0
  package-lock.json
  package.json
Labels: no-changelog, skip-issue-check

#24794 Update Pylance GDPR tags
  src/client/telemetry/pylance.ts
Labels: no-changelog, skip tests, skip-issue-check

#24798 add check for tmp dir access error on testIds file
  src/client/testing/testController/common/utils.ts
  src/test/testing/testController/utils.unit.test.ts
Labels: bug, skip-issue-check

#24799 improve logging for python testing env and interpreter
  src/client/testing/testController/pytest/pytestDiscoveryAdapter.ts
  src/client/testing/testController/pytest/pytestExecutionAdapter.ts
  src/client/testing/testController/unittest/testDiscoveryAdapter.ts
  src/client/testing/testController/unittest/testExecutionAdapter.ts
  src/test/testing/testController/pytest/pytestDiscoveryAdapter.unit.test.ts
  src/test/testing/testController/pytest/pytestExecutionAdapter.unit.test.ts
  src/test/testing/testController/unittest/testDiscoveryAdapter.unit.test.ts
  src/test/testing/testController/unittest/testExecutionAdapter.unit.test.ts
Labels: debt

#24800 handle un-analyzable files in coverage run
  python_files/vscode_pytest/__init__.py
Labels: bug

#24807 Always use environment path when running conda environment commands
  src/client/pythonEnvironments/common/environmentManagers/conda.ts
  src/test/common/process/pythonEnvironment.unit.test.ts
  src/test/pythonEnvironments/common/environmentManagers/conda.unit.test.ts
Labels: bug

#24728 Introduce `autoTestDiscoverOnSavePattern` configuration option
  package.json
  package.nls.json
  resources/report_issue_user_settings.json
  src/client/common/configSettings.ts
  src/client/testing/configuration/types.ts
  src/client/testing/testController/controller.ts
Labels: feature-request, skip package*.json, skip tests

#24826 Ensure Python Terminal Shell Integration setting is effective without reloading
  src/client/terminals/pythonStartup.ts
  src/test/terminals/shellIntegration/pythonStartup.test.ts
Labels: feature-request, area-terminal

#24832 Prevent python extension from overriding gitbash pwd
  src/client/terminals/envCollectionActivation/service.ts
Labels: bug, area-terminal, skip tests, skip-issue-check

#24843 remove TERMINAL_DEACTIVATE_PROMPT telemetry event
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
Labels: debt, skip tests, skip-issue-check

#24842 remove stale debugging telemetry
  src/client/common/application/debugSessionTelemetry.ts
  src/client/common/serviceRegistry.ts
  src/client/debugger/extension/adapter/factory.ts
  src/client/debugger/extension/configuration/resolvers/attach.ts
  src/client/debugger/extension/configuration/resolvers/base.ts
  src/client/debugger/extension/configuration/resolvers/launch.ts
  src/client/debugger/extension/debugCommands.ts
  src/client/debugger/extension/hooks/childProcessAttachService.ts
  src/client/telemetry/constants.ts
  src/client/telemetry/index.ts
  src/client/telemetry/types.ts
  src/test/common/moduleInstaller.test.ts
  src/test/debugger/extension/adapter/factory.unit.test.ts
Labels: debt, skip-issue-check

#24844 fix: identify script/module launch vs repl launch from terminal
  src/client/telemetry/index.ts
  src/client/terminals/codeExecution/terminalReplWatcher.ts
Labels: debt, skip tests

#24838 fix: ensure interpreter change event is raised when using environments extension
  src/client/envExt/api.internal.ts
  src/client/environmentApi.ts
  src/client/extensionActivation.ts
  src/test/common/persistentState.unit.test.ts
Labels: bug

#24853 Bump release 2025.2.0
  build/azure-pipeline.stable.yml
  package-lock.json
  package.json
Labels: no-changelog, skip-issue-check

#24854 Bump to 2025.3.0-dev
  package-lock.json
  package.json
Labels: no-changelog, skip-issue-check
